### ISSUE TITLE
Mid-year bufr station additions

### ISSUE THREAD

**Issue by GuangPingLou-NOAA** [NOAA-EMC/global-workflow#10]
Per users requests that accumulated throughout the year, 25 new stations are being added to operational GFS bufr station list, along with 3 existing stations modifications. This is part of a mid-year station update for all models.

**Comment by GuangPingLou-NOAA** [comment]
The expanded bufr station list has been pushed to GitHub:
under global-workflow/gfsv16b
in directory 
parm/product/bufr_stalist.meteo.gfs

**Comment by KateFriedman-NOAA** [comment]
Pulled updated bufr_stalist.meteo.gfs file into operations branch and committed it back at e393828.

**Comment by KateFriedman-NOAA** [comment]
Committed same update to develop branch at 3ed9267.

**Comment by KateFriedman-NOAA** [comment]
Action items for this issue are complete. Further updates for GFSv15.2.8 will be documented in issue #11. Closing issue now.
