### ISSUE TITLE
forecast fails when running with RRTMGP radiation

### ISSUE THREAD

**Issue by yangfanglin** [NOAA-EMC/global-workflow#1000]
The fixed files for running RRTMGP are not presented/copied to the running directory.  It seems the section that copies those files were removed in recent versions of workflow.   Please add the following section back to forecast_postdet.sh  after line 273

#--RRTMGP fixed fields
  if [ $do_RRTMGP = .true.  ]; then
    #$NLN $FIX_AM/rrtmgp-data-lw-g256-2018-12-04.nc       $DATA/.
    #$NLN $FIX_AM/rrtmgp-data-sw-g224-2018-12-04.nc       $DATA/.
    #$NLN $FIX_AM/rrtmgp-lw-prototype-g128-210413.nc      $DATA/.
    #$NLN $FIX_AM/rrtmgp-sw-prototype-g131-210413.nc      $DATA/.
    $NLN $FIX_AM/rrtmgp-data-lw-g128-210809.nc           $DATA/.
    $NLN $FIX_AM/rrtmgp-data-sw-g112-210809.nc           $DATA/.
    $NLN $FIX_AM/rrtmgp-cloud-optics-coeffs-lw.nc        $DATA/.
    $NLN $FIX_AM/rrtmgp-cloud-optics-coeffs-sw.nc        $DATA/.
  fi

In parsing_namelists_FV3.sh please also set
doGP_cldoptics_LUT = ${doGP_cldoptics_LUT:-".true."}
doGP_lwscat        = ${doGP_lwscat:-".true."}

The model will crash if doGP_cldoptics_LUT is set to false by default.

**Comment by WalterKolczynski-NOAA** [comment]
Issue #193 that was supposed to add RRTMGP is still open. Was the capability added without the issue being properly closed?

**Comment by WalterKolczynski-NOAA** [comment]
Closed as invalid since RRTMGP capability hasn't even been added to workflow yet.
