### ISSUE TITLE
Archive jobs fail for fourth full cycle when starting with a half-cycle

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#1003]
**Expected behavior**
Archive jobs should complete normally

**Current behavior**
When running cold start, the archive job fails for the fourth full cycle (24 h after the half-cycle).

**Machines affected**
All

**To Reproduce**
Set up a cycled cold-start experiment that runs for more than a day.

**Detailed Description**

Failure is caused near the end of the archive script when it attempts to delete data no longer needed. It is checking the rocoto log(!) to see if the cycle 24 h previous completed successfully. However, the key string that is being searched for, `This cycle is complete: Success` is not written for the half-cycle. This is likely caused by not all jobs running in the half-cycle and no task assigned as the "final" task, so the cycle is never "complete" from a rocoto perspective.

**Possible Implementation**
There are a lot of things going on here that can be fixed. First, there are prerequisites that can be used so the job only runs if the cycle is complete (if it exists) rather than parsing the rocoto log file. Even if that approach is used, it will be unsuccessful unless the half-cycle is marked as complete. This can be done by setting `final="true"` in the task definition, or preferably by specifying a new cycledef for the half-cycle that includes only the jobs to be run (or both for good measure).

**Comment by AndrewEichmann-NOAA** [comment]
@WalterKolczynski-NOAA Would you expect this bug in cycles after that fourth full cycle?

```
Orion-login-2[37] aeichman$ tail -6 logs/2021061006/gdasearc00.log
++ earc.sh[237]: tail -n 1 /work/noaa/da/aeichman/para//xylose/logs/2021060900.log
++ earc.sh[237]: grep 'This cycle is complete: Success'
+ earc.sh[237]: testend=
+ earc.sh[1]: postamble earc.sh 1662778819 1
+ preamble.sh[67]: set +x
End earc.sh at 03:00:31 with error code 1 (time elapsed: 00:00:12)
Orion-login-2[38] aeichman$ 
```

**Comment by KateFriedman-NOAA** [comment]
I'm seeing this error in almost every cycle in new cycled tests on Orion and WCOSS2. Sometimes it's a race condition unrelated to the half-cycle and other times happens when the prior cycle has a DEAD job (e.g. gdasvrfy) or otherwise hasn't completed.

**Comment by AndrewEichmann-NOAA** [comment]
I've encountered the race condition as well. The problem is compounded by rocotocompleting the dead archiving tasks leaving no string to be grepped in the rocoto log, so each cycle winds up requiring intervention to complete.

**Comment by AndrewEichmann-NOAA** [comment]
Are there any plans for this? Any cycled run longer than a day requires intervention on each cycle to keep running.

**Comment by WalterKolczynski-NOAA** [comment]
I'm going to start tackling this today, I hope.

**Comment by AndrewEichmann-NOAA** [comment]
Great - once it's working I'll merge it into the EFSOI branch, get the PR in, and get that out of everybody's hair.
