### ISSUE TITLE
gdaspostanl resources must be resolution dependent

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/global-workflow#1006]
**Expected behavior**
all jobs should complete successfully (including `gdaspostanl`)

**Current behavior**
When running at C96, `gdaspostanl` will fail. The `stdout` does not go to the logfile... (that's a different issue), but the problem boils down to:
`too many MPI tasks, max is 96, stopping`

In this case `96=jm/2` where `jm=192`. So the max number of MPI tasks must equal the resolution.

**Machines affected**
Probably all

**To Reproduce**
Run the workflow at a resolution of C96 or lower.

**Comment by Alien2one1two** [comment]
37f1611bb908f1df8bed667facf0d079d95f02b6

**Comment by KateFriedman-NOAA** [comment]
This is no longer an issue as demonstrated by the tests. Will reopen if needed.
