### ISSUE TITLE
Modify RadMon tank (archive) directory for rocoto-based parallels

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/global-workflow#1010]
**Expected behavior**
Execution of the Radiance Monitor (RadMon) package in rocoto-based parallels should write output to unique tank (archive) directories.

**Current behavior**
While RadMon output is correctly written to $PSLOT/$CDUMP.$PDY, no distinction is made between $cyc.  As a result tar'd RadMon output from each successive cycle overwrites the tarball from the previous cycle for a given $PDY.  This behavior was round in a rocoto-based parallel built from g-w `release/gfs.v16.3.0`.

**Machines affected**
Only confirmed on WCOSS2 but expect similar behavior on other machines.

**To Reproduce**
To observe the current behavior
1. Install g-w `release/gfsda.v16.3.0` on WCOSS2
2. Set up `$EXPDIR` for experiment `$PSLOT`
3. Populate `$ROTDIR` with the files needed to run RadMon for gdas `$PDY$cyc`
4. Submit `gdasvrfy` for `$PDY$cyc`

RadMon output will be written to `TANKverf_rad="$TANKverf/stats/$PSLOT/$CDUMP.$PDY"` where `TANKverf="$NOSCRUB/monitor/radmon"`.   This directory is not unique to the `$cyc` for which the job was submitted.  As a result execution for `gdasvrfy` for subsequent cycles for the same `$PDY` overwrite output from the previous cycle.

**Possible Implementation**
`$cyc` should be added to `TANKverf_rad` in `vrfy.sh`.   To be consistent, `$cyc` should also be added to `TANKverf_radM1` in `vrfy.sh`.  These changes will be committed to `vrfy.sh` in fork [Russ.Treadon-NOAA/global-workflow/release/gfs.v16.3.0](https://github.com/RussTreadon-NOAA/global-workflow/tree/release/gfs.v16.3.0)

**Comment by WalterKolczynski-NOAA** [comment]
Is there a difference between this issue and #993? Did the PR attached solve the issue for the release branch, and have those changes made their way back to develop?

**Comment by RussTreadon-NOAA** [comment]
@EdwardSafford-NOAA , from your perspective do we will need this open issue or did #993 take care of this?

**Comment by EdwardSafford-NOAA** [comment]
@RussTreadon-NOAA @WalterKolczynski-NOAA From my perspective it can be closed.  #993 would apply the same fix to the MinMon output directory (adding $cyc), and the same fix should be applied to the OznMon's output in branch gfsda.v16.3.0.

#1065 has made changes to all default output file locations for RadMon, MinMon and OznMon, (adding a $cyc to the end of the output location) in branch develop.

**Comment by RussTreadon-NOAA** [comment]
Thanks, @EdwardSafford-NOAA .   @WalterKolczynski-NOAA , we can close this issue.   I'll do so with this comment.
