### ISSUE TITLE
Absorb GLDAS scripts

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#1014]
**Description**

As part of the overarching goal of moving global workflow scripts out of component repositories and under global workflow, all of the scripts currently linked in GLDAS should be moved to global-workflow. FYI @HelinWei-NOAA , please let us know of any concerns, questions, or objections. Once we absorb the following scripts you can remove them in your GLDAS repo.

Scripts to be absorbed:
* jobs/
  * JGDAS_ATMOS_GLDAS
* scripts/
  * exgdas_atmos_gldas.sh
* ush/
  * ~~gldas_archive.sh~~ (not bringing into global-workflow, see discussion below https://github.com/NOAA-EMC/global-workflow/issues/1014#issuecomment-1247045987)
  * gldas_forcing.sh
  * gldas_get_data.sh
  * gldas_liscrd.sh
  * ~~gldas_post.sh~~ (not bringing into global-workflow, see discussion below https://github.com/NOAA-EMC/global-workflow/issues/1014#issuecomment-1247045987)
  * gldas_process_data.sh

**Requirements**

All GLDAS jobs, scripts, and ush scripts that are currently linked by global workflow added to the global workflow repo instead and removed from the ignore list.

**Acceptance Criteria (Definition of Done)**

No jobs, scripts, or ush scripts linked from GLDAS.

**Dependencies**

None

**Comment by HelinWei-NOAA** [comment]
I don't think there will be any issue as long as the right path is given in the scripts.

**Comment by KateFriedman-NOAA** [comment]
> I don't think there will be any issue as long as the right path is given in the scripts.

Great! Yep, I'll be making the necessary workflow-side updates related to paths and such. :)

**Comment by KateFriedman-NOAA** [comment]
@HelinWei-NOAA It does not appear that `ush/gldas_archive.sh` or `gldas_post.sh` are invoked at runtime. I checked both my test logs and the ops GLDAS log. Is there any reason to keep either of those scripts? If not, I will not pull them into global-workflow. Thanks!

**Comment by HelinWei-NOAA** [comment]
@KateFriedman-NOAA Both scripts are invoked by exgdas_atmos_gldas.sh.  gldas_archive.sh is turn on only for offline gldas run. But I am surprise that gldas_post.sh isn't invoked at runtime. Can you point me to your log file running gldas? Thanks.

**Comment by KateFriedman-NOAA** [comment]
> gldas_archive.sh is turn on only for offline gldas run.

Good to know, thanks!

> But I am surprise that gldas_post.sh isn't invoked at runtime. Can you point me to your log file running gldas?

I checked both the ops 00z gldas job logs and my own testing logs:

Ops logs from 00z last night (/lfs/h1/ops/prod/output/20220914/gdas_atmos_gldas_00.o19964486):
```
kate.friedman@clogin08:/lfs/h1/ops/prod/output> grep gldas_archive.sh 20220914/gdas_atmos_gldas_00.o19964486
kate.friedman@clogin08:/lfs/h1/ops/prod/output> grep gldas_post.sh 20220914/gdas_atmos_gldas_00.o19964486                                                               
kate.friedman@clogin08:/lfs/h1/ops/prod/output> 
```

My test logs on Cactus:
```
kate.friedman@clogin08:/lfs/h2/emc/ptmp/kate.friedman/comrot/devcyc768c> pwd
/lfs/h2/emc/ptmp/kate.friedman/comrot/devcyc768c
kate.friedman@clogin08:/lfs/h2/emc/ptmp/kate.friedman/comrot/devcyc768c> grep gldas_post.sh logs/*/gdasgldas.log                                                          
kate.friedman@clogin08:/lfs/h2/emc/ptmp/kate.friedman/comrot/devcyc768c> 
```

**Comment by HelinWei-NOAA** [comment]
@KateFriedman-NOAA If you just search gldas_post, you can find one in the log. 

line 114656 of gdas_atmos_gldas_00.o19964486
pgm=gldas_post

This is part of gldas_post.sh. So it is invoked at runtime.

**Comment by KateFriedman-NOAA** [comment]
The `gldas_post` exec is invoked by both the `scripts/exgdas_atmos_gldas.sh` script and the `gldas_post.sh` script but in ops and in my testing the `gldas_post` exec is only invoked from `scripts/exgdas_atmos_gldas.sh`. The `gldas_post.sh` script isn't invoked in ops or developer parallel testing. When would it be invoked? In offline mode like `gldas_archive.sh`?

**Comment by HelinWei-NOAA** [comment]
@KateFriedman-NOAA You are right. I can confirm that gldas_post.sh is not invoked at runtime. Thanks.

**Comment by KateFriedman-NOAA** [comment]
Thanks @HelinWei-NOAA ! Since `gldas_post.sh` is not invoked at runtime is there any reason to keep it?

Related question...how does one run GLDAS in offline mode and invoke `gldas_archive.sh`? Thanks!

**Comment by HelinWei-NOAA** [comment]
There is no reason to keep gldas_post.sh. We need to set OFFLINE_GLDAS = "YES"  to invoke gldas_arch.sh in the offline driver submit_test_gdas_gldas_dell.sh. We haven't updated this driver for a long time.

**Comment by KateFriedman-NOAA** [comment]
> There is no reason to keep gldas_post.sh.

Ok, thanks @HelinWei-NOAA for confirming! I will delete it from my global-workflow branch and not include it in the GLDAS script absorption.

> We need to set OFFLINE_GLDAS = "YES" to invoke gldas_arch.sh in the offline driver submit_test_gdas_gldas_dell.sh. We haven't updated this driver for a long time.

Gotcha, thanks for explaining! Since `gldas_archive.sh` isn't used at runtime, would only be used in offline mode, and appears to need updating (since it references nemsio still) I will also forgo including it in the GLDAS script absorption into global-workflow. I'll leave it to you to decide what's best for it's possible future use within the GLDAS repo. Should we stick with GLDAS in the future GFSv17 system and the need to support offline GLDAS via global-workflow comes up, we can add an updated version of `gldas_archive.sh` into global-workflow.

Let me know if you have any objections to the above. Thanks!
