### ISSUE TITLE
Setting up global-workflow to run S2S at low (aC48o500) resolution

### ISSUE THREAD

**Issue by AndrewEichmann-NOAA** [NOAA-EMC/global-workflow#1027]
**Description**

Goal: Allow global-workflow to run S2S at aC48o500 resolution in the manner in currently does in aC384o025

**Acceptance Criteria (Definition of Done)**

Feeding setup_expt.py the correct options produces a successful S2S run at aC48o500

**Dependencies**

No upstream dependencies, downstream this allows efficient testing of the coupled model

**Requirements**

- @JessicaMeixner-NOAA provided the source and destination for the following fix files: grid_spec file, CICE inputs, MOM6. Plus MOM_input_template_500 in parm/mom6
 
- Changes will also be needed to the workflow setup for coupled_ic task, which has idiosyncratic handling.

- ICs will have to be arranged in the manner of existing S2S experiments. @guillaumevernieres , any preferences for dates?

**Comment by guillaumevernieres** [comment]
@AndrewEichmann-NOAA , for the IC, whatever is used in the UFS RT test is fine. For the MOM6 and CICE fix files that need to be added to Orion and Hera, we need to coordinate with @KateFriedman-NOAA .

**Comment by AndrewEichmann-NOAA** [comment]
@guillaumevernieres @KateFriedman-NOAA 

 Would the fix files not be part of a PR? I was about to set up a branch on my fork to get things started.

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres @KateFriedman-NOAA
> 
> Would the fix files not be part of a PR? I was about to set up a branch on my fork to get things started.

@AndrewEichmann-NOAA , 1/2 and 1/2. We have a few binary files that will not be part of a pr.

**Comment by AndrewEichmann-NOAA** [comment]
@guillaumevernieres Got it. Sleep dep yesterday took its toll. Are we aiming for both Hera and Orion?

@KateFriedman-NOAA These are the files on Hera Jessica indicated:

grid_spec file:

cp -r /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/input-data-20220414/CPL_FIX/aC48o500  /scratch1/NCEPDEV/global/glopara/fix/cpl/20220805/

CICE inputs

cp -r  /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/input-data-20220414/CICE_FIX/500    /scratch1/NCEPDEV/global/glopara/fix/cice/20220805/

MOM6:

cp -r /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/input-data-20220414/MOM6_FIX/500 /scratch1/NCEPDEV/global/glopara/fix/mom6/20220805/

**Comment by guillaumevernieres** [comment]
Yes @AndrewEichmann-NOAA , both, Hera and Orion.

**Comment by KateFriedman-NOAA** [comment]
@AndrewEichmann-NOAA @guillaumevernieres I have pulled the new fix files into the primary fix set on Hera:
```
[glopara@hfe09 fix]$ pwd
/scratch1/NCEPDEV/global/glopara/fix
[glopara@hfe09 fix]$ ll cpl/20220805/aC48o500/
total 24
-rw-r--r-- 1 glopara global 24468 Jul 14 13:54 grid_spec.nc
[glopara@hfe09 fix]$ ll cice/20220805/500/
total 276
-rw-r--r-- 1 glopara global 111924 Jul 14 13:52 grid_cice_NEMS_mx500.nc
-rw-r--r-- 1 glopara global  10804 Jul 14 13:52 kmtu_cice_NEMS_mx500.nc
-rw-r--r-- 1 glopara global 154762 Jul 14 13:52 mesh.mx500.nc
[glopara@hfe09 fix]$ ll mom6/20220805/500/
total 144
-rw-r--r-- 1 glopara global   113 Jul 14 13:55 MOM_override
-rw-r--r-- 1 glopara global  6642 Jul 14 13:55 hycom1_25.nc
-rw-r--r-- 1 glopara global   745 Jul 14 13:55 layer_coord25.nc
-rw-r--r-- 1 glopara global 74704 Jul 14 13:55 ocean_hgrid.nc
-rw-r--r-- 1 glopara global  9982 Jul 14 13:55 ocean_mask.nc
-rw-r--r-- 1 glopara global 15861 Jul 14 13:55 ocean_mosaic.nc
-rw-r--r-- 1 glopara global 22403 Jul 14 13:55 ocean_topog.nc
```

I will now rsync them to the other platform fix sets on WCOSS2, Orion, and Jet. Thanks!

**Comment by AndrewEichmann-NOAA** [comment]
@KateFriedman-NOAA Thank you, Kate.

@guillaumevernieres I forget if we discussed this, but what do I do for the ICs for ice and ocean? I presume these need to be in the target resolution:

Orion-login-4[74] aeichman$ ls ics/2013010100/ice/
cice_model_0.25.res_2013010100.nc
Orion-login-4[75] aeichman$ ls ics/2013010100/ocn/
MOM.res_1.nc  MOM.res_2.nc  MOM.res_3.nc  MOM.res_4.nc  MOM.res.nc
Orion-login-4[76] aeichman$

**Comment by guillaumevernieres** [comment]
@AndrewEichmann-NOAA , grab the IC from the RT test.

**Comment by KateFriedman-NOAA** [comment]
Update to confirm that these new fix files are now also in the primary fix sets on both WCOSS2s, Orion, and Jet. Took longer than usual to do these rsync's because I took the opportunity to use the `--checksum` flag with rsync to make sure nothing was missing in any set beyond the usual checks that rsync does. The checksum flag significantly increases the rsync time so I don't use it every time. Nothing came up as missing. All is good and updated!

**Comment by guillaumevernieres** [comment]
> Update to confirm that these new fix files are now also in the primary fix sets on both WCOSS2s, Orion, and Jet. Took longer than usual to do these rsync's because I took the opportunity to use the `--checksum` flag with rsync to make sure nothing was missing in any set beyond the usual checks that rsync does. The checksum flag significantly increases the rsync time so I don't use it every time. Nothing came up as missing. All is good and updated!

Thanks @KateFriedman-NOAA

**Comment by AndrewEichmann-NOAA** [comment]
@guillaumevernieres So now I'm curious why the 025 ocean fix directory is so different from the 500. This is the ocean fix directory on Orion (same on Hera):

Orion-login-1[39] aeichman$ ls -1 /work/noaa/da/aeichman/fv3gfs/develop/global-workflow/fix/fix_mom6/025/
All_edits.nc
geothermal_davies2013_v1.nc
hycom1_75_800m.nc
interpolate_zgrid_40L.nc
layer_coord.nc
MOM_channels_global_025
MOM_layout
MOM_override
ocean_hgrid.nc
ocean_mask.nc
ocean_mosaic.nc
ocean_topog.nc
runoff.daitren.clim.1440x1080.v20180328.nc
seawifs-clim-1997-2010.1440x1080.v20180328.nc
tidal_amplitude.v20140616.nc
topog.nc
Orion-login-1[40] aeichman$ 

This is the 500:

Orion-login-1[61] aeichman$  ls -1 /work/noaa/da/aeichman/fv3gfs/develop/global-workflow/fix/fix_mom6/500/
hycom1_25.nc
layer_coord25.nc
MOM_override
ocean_hgrid.nc
ocean_mask.nc
ocean_mosaic.nc
ocean_topog.nc
Orion-login-1[62] aeichman$ 

The ice and cpl seem the same,  mutatis mutandis.

**Comment by jiandewang** [comment]
@AndrewEichmann-NOAA MOM6 at 5x5 is a very simple setting for IT test, some physical processes such as runoff, tide and shortwave penetration are turned off, thus you don't see them here.
