### ISSUE TITLE
Radiance verification fails to find diag files

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/global-workflow#1028]
**Expected behavior**

The ges diag files should be found and used when performing radiance verification.

**Current behavior**

The lines
`if [[ -f "diag_${type}_ges.${PDATE}*.${Z}" ]]; then`
and
`if [[ -f "diag_${type}_anl.${PDATE}*.${Z}" ]]; then`
in [exgdas_atmos_verfrad.sh](https://github.com/NOAA-EMC/global-workflow/blob/develop/scripts/exgdas_atmos_verfrad.sh#L147-L155) fail to find anything as the use of wildcards in a `-f` conditional are not expanded.

**Machines affected**

All

**To Reproduce**

Run a gdasvrfy job in a cycle in which gdasanal also ran.

**Possible Implementation**

One possible fix is to use ls instead of -f:
```
if ls "diag_${type}_ges.${PDATE}*.${Z}" 1> /dev/null 2>&1; then
  mv diag_${type}_ges.${PDATE}*.${Z} ${type}.${Z}
  ${UNCOMPRESS} ./${type}.${Z}
else
  echo "WARNING: diag_${type}_ges.${PDATE}*.${Z} not available, skipping"
fi
```

**Comment by WalterKolczynski-NOAA** [comment]
Prefer `if (( ls "diag_${type}_ges.${PDATE}*.${Z}" 2> /dev/null | wc -l > 0 )); then` as a solution, as it is more explicit in what it is doing.
