### ISSUE TITLE
Loading anaconda in bashrc enables running of global-workflow tasks

### ISSUE THREAD

**Issue by AndrewEichmann-NOAA** [NOAA-EMC/global-workflow#1040]
**Description**
When running a forecast-only experiment for the first time in a while on Hera, gfsgetic ends with the following:

```
++ load_fv3gfs_modules.sh[6]: set +x
/home/Andrew.Eichmann/miniconda3/etc/conda/deactivate.d/proj4-deactivate.sh: line 5: _CONDA_SET_PROJ_LIB: unbound variable
End getic.sh at 20:17:53 with error code 1 (time elapsed: 00:00:02)

```

The wiki instructions say to run the following before building and running g-w:

module use -a /contrib/anaconda/modulefiles
module load anaconda/anaconda3-5.3.1

Putting these lines in .bashrc (and removing the previously installed anaconda invocation) fixed the problem. Is this the desired arrangement, as opposed to having this covered automatically in the task scripts? The requirement isn't documented, and I'm guessing it wasn't noticed because many people set this in their .bashrc.

**Comment by aerorahul** [comment]
@AndrewEichmann-NOAA 
In general, it is considered poor practice to load modules such as anaconda (or any for that matter) by default via ones login shell such as `.bashrc`.
One should only load the relevant modules when they are needed (and unload them once their use is done).
For the global-workflow, consider adding functions such as these in `.bashrc`.

```
load_gw_env(){
  if [[ ${GW_ENV_LOADED:-0} =~ 1 ]]; then
    echo "global-workflow environment is already loaded"
    return
  fi
  echo "Loading global-workflow environment"
  module use -a /contrib/anaconda/modulefiles
  module load anaconda/anaconda3-5.3.1
  module load rocoto/1.3.3
  module list
  export GW_ENV_LOADED=1
}

unload_gw_env(){
  if [[ ${GW_ENV_LOADED:-0} =~ 0 ]]; then
    echo "global-workflow environment is not loaded"
    return
  fi
  echo "Unloading global-workflow environment"
  module unload anaconda/anaconda3-5.3.1
  module unload rocoto/1.3.3
  module unuse /contrib/anaconda/modulefiles
  module list
  unset GW_ENV_LOADED
}
```

This will allow the user to load and unload the global-workflow environment much easily and when needed.
Load the global-workflow environment needed to setup the experiment:
```
$> load_gw_env
Loading global-workflow environment

Currently Loaded Modules:
  1) anaconda/anaconda3-5.3.1   2) rocoto/1.3.3
```
Setup the experiment etc.
```
$> setup_expt.py ...
$> setup_xml.py ...
```
Unload the global-workflow environment
```
$> unload_gw_env
Unloading global-workflow environment
No modules loaded
```

**Comment by WalterKolczynski-NOAA** [comment]
The instructions in the wiki are specifically for running the experiment setup interactively. You shouldn't need to add anything to your bashrc. I suspect there is some error loading the modulefile at runtime. in `load_fv3gfs_modules.sh`, change the default of `DEBUG_WORKFLOW` to `YES` on L4†.

† We made this a setting, but I don't think we have a way to set it in time unless it is added to the rocoto task definition. By the time it would be set if you put it in config.base, it would be too late. We'll need to rethink that setting.

**Comment by AndrewEichmann-NOAA** [comment]
Never mind, I had added things in my .bashrc that were conflicting. Thanks @aerorahul for the tips.
