### ISSUE TITLE
Wrong naming of the orography fixed files for the coupled c48 5 deg ocean/ice

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/global-workflow#1054]
## The bug
The orography fixed files for the C48/5 degree MOM6-CICE are not named properly on `Hera` (probably true for other HPC):
`400` should be replaced by `500`. As far as I know there isn't an existing 4 degree MOM6/CICE. Correct me if I am wrong @jiandewang , @DeniseWorthen or @JessicaMeixner-NOAA. 

## The solution
```/scratch1/NCEPDEV/global/glopara/fix/orog/20220805/C48.mx400_frac```
should be 
```/scratch1/NCEPDEV/global/glopara/fix/orog/20220805/C48.mx500_frac```

and 

```oro_C48.mx400.tile*.nc``` should be ```oro_C48.mx500.tile*.nc```

**Comment by jiandewang** [comment]
@guillaumevernieres you are right on this. Originally we got the fixed files from Travis and thought it is 4x4. A simple renaming will cause the job failure for users working branch. A viable way is to copy them to 5x5 naming style while keep 4x4 on disk for a period of time. In the meantime we need to have a simple PR to correct the fixed file directory in rt.sh. After the PR is done, we can ask users to sync their working branch and delete the original 4x4 fixed file directory.

**Comment by guillaumevernieres** [comment]
Thanks for your input @jiandewang . 
@KateFriedman-NOAA , could you make a copy instead of renaming as @jiandewang suggested?

**Comment by jiandewang** [comment]
@KateFriedman-NOAA can you do the coping on all platforms as I don't have permission on most of them ?
@WalterKolczynski-NOAA Can you also assign this issue to me? I am going to have a PR on script changing for this.

**Comment by WalterKolczynski-NOAA** [comment]
@jiandewang I think I can just fix it quickly.

**Comment by jiandewang** [comment]
> @jiandewang I think I can just fix it quickly.

sounds good

**Comment by KateFriedman-NOAA** [comment]
I have fixed this in the fix set on Hera and am currently rsyncing the change to the other platform fix sets:

```
[glopara@hfe05 20220805]$ pwd
/scratch1/NCEPDEV/global/glopara/fix/orog/20220805
[glopara@hfe05 20220805]$ ll C48.mx500_frac
total 190568
-rw-r--r-- 1 glopara global    539002 May  4 01:39 C48_grid.tile1.nc
-rw-r--r-- 1 glopara global    539002 May  4 01:39 C48_grid.tile2.nc
-rw-r--r-- 1 glopara global    539002 May  4 01:39 C48_grid.tile3.nc
-rw-r--r-- 1 glopara global    539002 May  4 01:39 C48_grid.tile4.nc
-rw-r--r-- 1 glopara global    539002 May  4 01:39 C48_grid.tile5.nc
-rw-r--r-- 1 glopara global    539002 May  4 01:39 C48_grid.tile6.nc
-rw-r--r-- 1 glopara global     22010 May  4 01:39 C48_mosaic.nc
drwxr-sr-x 2 glopara global      4096 May  4 01:55 fix_sfc
-rw-r--r-- 1 glopara global   3459336 May  4 01:39 fv3_SCRIP_C48_GRIDSPEC_lon192_lat94.gaussian.bilinear.nc
-rw-r--r-- 1 glopara global   2593056 May  4 01:39 fv3_SCRIP_C48_GRIDSPEC_lon192_lat94.gaussian.neareststod.nc
-rw-r--r-- 1 glopara global    226627 May  4 01:50 oro_C48.mx500.tile1.nc
-rw-r--r-- 1 glopara global    226627 May  4 01:50 oro_C48.mx500.tile2.nc
-rw-r--r-- 1 glopara global    226627 May  4 01:50 oro_C48.mx500.tile3.nc
-rw-r--r-- 1 glopara global    226627 May  4 01:50 oro_C48.mx500.tile4.nc
-rw-r--r-- 1 glopara global    226627 May  4 01:50 oro_C48.mx500.tile5.nc
-rw-r--r-- 1 glopara global    226627 May  4 01:50 oro_C48.mx500.tile6.nc
-rw-r--r-- 1 glopara global 131815449 May  4 01:39 remap_weights_C48_0p125deg.nc
-rw-r--r-- 1 glopara global  37056281 May  4 01:39 remap_weights_C48_0p25deg.nc
-rw-r--r-- 1 glopara global  11457561 May  4 01:39 remap_weights_C48_0p5deg.nc
-rw-r--r-- 1 glopara global   4096473 May  4 01:39 remap_weights_C48_1deg.nc
```

@WalterKolczynski-NOAA is working on the associated workflow update.

**Comment by guillaumevernieres** [comment]
Thanks @KateFriedman-NOAA .

**Comment by KateFriedman-NOAA** [comment]
@guillaumevernieres The fix sets on Hera, Orion, Cactus, and Dogwood are updated. Waiting for Jet to come back from maintenance to update the set there.

**Comment by KateFriedman-NOAA** [comment]
Jet fix set is now also updated.
