### ISSUE TITLE
finddate.sh not found

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/global-workflow#1059]
**Expected behavior**
Job `gdasgldas` should run to completion.

**Current behavior**
Job `gdasgldas` fails with the error
```
+ gldas_forcing.sh[25](20211222): sdate=20211222
++ gldas_forcing.sh[26](20211222): sh /work/noaa/da/Russ.Treadon/git/global_workflow/develop/util/ush/finddate.sh 20211225 d-1
sh: /work/noaa/da/Russ.Treadon/git/global_workflow/develop/util/ush/finddate.sh: No such file or directory
+ gldas_forcing.sh[26](20211222): edate=
+ gldas_forcing.sh[1](20211222): postamble gldas_forcing.sh 1665485341 127
+ preamble.sh[68](20211222): set +x
End gldas_forcing.sh at 10:49:01 with error code 127 (time elapsed: 00:00:00)
```
`config.gldas` sets

`export FINDDATE=$HOMEgfs/util/ush/finddate.sh`

`finddate.sh` does not exist at this path.

**Machines affected**
Only tested on Orion

**To Reproduce**
Install the g-w from the current head of develop (e915eb64).   Set up `EXPDIR` to run a parallel.  Populate `ROTDIR` with the files needed to fully execute `gdasgldas`.  Submit `gdasgldas`.

**Additional Information**
Due to this bug we can not run a cycled experiment with gldas.

**Comment by WalterKolczynski-NOAA** [comment]
I think @KateFriedman-NOAA is already working on this.

**Comment by RussTreadon-NOAA** [comment]
Thanks @WalterKolczynski-NOAA .  @KateFriedman-NOAA , do we have an estimate as to when this will be fixed?

As a patch, I copied `finddate.sh` from an old g-w checkout to my `EXPDIR` and updated `config.gldas` to point at my local copy.  This, obviously, is not a solution.

**Comment by WalterKolczynski-NOAA** [comment]
`find_date.sh` was moved into the new gfs-utils repo, which is located in `sorc/` as `gfs_utils.fd`. You can find it there without using an old copy of g-w. The fix will be linking the ush scripts there into `ush/`

**Comment by RussTreadon-NOAA** [comment]
Thanks, @WalterKolczynski-NOAA .   I updated `config.gldas` in my `EXPDIR` to read

`export FINDDATE=$HOMEgfs/sorc/gfs_utils.fd/ush/finddate.sh`

I'll undo this local mod when the official fix is developed, tested, and committed to `develop`.

**Comment by aerorahul** [comment]
Just an FYI, `finddate.sh` is a utility in `prod_util` and should be the one that is used rather than the local copy from gfs-utils.
https://github.com/NCEP-NCO/prod_util/tree/operations/ush
https://github.com/NOAA-EMC/NCEPLIBS-prod_util/tree/develop/ush

I believe both are available on all systems

**Comment by RussTreadon-NOAA** [comment]
g-w develop `modulefiles/module_base.orion.lua` loads `prod_util/1.2.2`.    This module points at `/work2/noaa/global/wkolczyn/save/hpc-stack/intel-2018.4/prod_util/1.2.2`.   This directory does not exist on Orion.  

I see `finddate.sh` in `/apps/contrib/NCEP/libs/hpc-stack/intel-2018.4/prod_util/1.2.2/bin`

**Comment by WalterKolczynski-NOAA** [comment]
The hpc-stack under my name is only a hack job for a couple modules related to MET. All other modules are loaded from the main hpc-stack installation.

**Comment by RussTreadon-NOAA** [comment]
Great, I look forward to exercising the updated g-w develop with `finddate.sh` picked up via prod_util.

**Comment by RussTreadon-NOAA** [comment]
Two problems encountered with develop at [9118ab3](https://github.com/NOAA-EMC/global-workflow/commit/9118ab33eca68690f99a4be288101b0b1d565bf6).

- the updated `sorc/checkout.sh` is cloned without execute file permission.  The cloned copy has `-rw-r--r--` permissions.   Thus, `./checkout.sh` does not execute.   The user needs to `chmod` the file
- `sorc/build_all.sh` fails with `FATAL: Unable to determine target machine`.   `build_all.sh` executes `gfs_utils.fd/ush/machine-setup.sh`.   gfs_utils hash [`af933d3`](https://github.com/NOAA-EMC/gfs-utils/commit/af933d347533bba8a3bdba5dddc33a71ba691815) deleted `machine-setup.sh` 

Tagging @WalterKolczynski-NOAA , @KateFriedman-NOAA , and @aerorahul

**Comment by RussTreadon-NOAA** [comment]
Bug issue #1086 opened to report checkout and build issues for develop at [9118ab3](https://github.com/NOAA-EMC/global-workflow/commit/9118ab33eca68690f99a4be288101b0b1d565bf6).
