### ISSUE TITLE
gdasprep fails in cycling with  HOMEobsproc: unbound variable

### ISSUE THREAD

**Issue by AndrewEichmann-NOAA** [NOAA-EMC/global-workflow#1068]
**Expected behavior**

gdasprep in cycling fails with unbound variable error

**Current behavior**

Job fails with following in log /work/noaa/stmp/aeichman/comrot/bosco/logs/2021060906/gdasprep.log: 

```
 prep.sh[110]: export MAKE_NSSTBUFR=NO
+ prep.sh[110]: MAKE_NSSTBUFR=NO
/work/noaa/da/aeichman/fv3gfs/mydevelop/global-workflow/jobs/rocoto/prep.sh: line 113: HOMEobsproc: unbound variable
++ prep.sh[1]: postamble prep.sh 1665525231 1
++ preamble.sh[68]: set +x
End prep.sh at 21:54:01 with error code 1 (time elapsed: 00:00:10)

```

Line in question is following:

`    $HOMEobsproc/jobs/JOBSPROC_GLOBAL_PREP
`

Variable does not appear before in log, though string is base name for other variables (eg HOMEobsproc_prep)

**Machines affected**

Orion

**To Reproduce**

comrot: /work/noaa/stmp/aeichman/comrot/bosco
expdir: /work/noaa/da/aeichman/para/bosco

Experiment was set up for cycling with all defaults and failed on first full cycle

g-w hash 9553ef690b12709fd3024f07ad81257d02453ac6 (Oct 11)

**Comment by KateFriedman-NOAA** [comment]
@AndrewEichmann-NOAA Your config.base in your expdir is old:
```
Orion-login-4[9] /work/noaa/da/aeichman/para/bosco$ grep HOMEobsproc config.base
export HOMEobsproc_prep="$BASE_GIT/obsproc/obsproc_prep.v5.5.0_hpc-stack"
export HOMEobsproc_network="$BASE_GIT/obsproc/obsproc_global.v3.4.2_hpc-stack"
export HOMEobsproc_global=$HOMEobsproc_network
Orion-login-4[10] /work/noaa/da/aeichman/para/bosco$ grep HOMEgfs= config.base
export HOMEgfs=/work/noaa/da/aeichman/fv3gfs/mydevelop/global-workflow
```
The config.base.emc.dyn in your `HOMEgfs`/clone is updated with the newer `HOMEobsproc`:
```
Orion-login-4[6] /work/noaa/da/aeichman/fv3gfs/mydevelop/global-workflow$ grep HOMEobsproc parm/config/config.base.*
parm/config/config.base.emc.dyn:export HOMEobsproc="$BASE_GIT/obsproc/v1.0.2"
parm/config/config.base.nco.static:export HOMEobsproc="/lfs/h1/ops/prod/packages/obsproc.v1.0.2"
```
Diff your updated clone's configs with your expdir versions to see what you need to pull into your expdir or remake/restart the run with the updated configs in your clone.

**Comment by aerorahul** [comment]
@AndrewEichmann-NOAA 
I ran an experiment yesterday with updates from `develop` and was able to run the gdas/gfs prep jobs to completion.
The logs are here:
```
/work2/noaa/stmp/rmahajan/gwWork/EXPDIR/testjobs01/ROTDIR/logs/2021122100/gdasprep.log
/work2/noaa/stmp/rmahajan/gwWork/EXPDIR/testjobs01/ROTDIR/logs/2021122100/gfsprep.log
```

**Comment by AndrewEichmann-NOAA** [comment]
Wetware malf mitigated, thank you for your time and effort.
