### ISSUE TITLE
GSI minmon script should not run in forecast-only mode

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#1076]
**Expected behavior**
The GSI minmon script should be turned off when in forecast-only mode. Under the current configuration the gfsvrfy job fails starting in the second cycle because there is no gsistat file.

**Current behavior**
Minmon is run for gfs CDUMP even in forecast-only mode

**Machines affected**
All

**To Reproduce**
1. Setup a forecast-only experiment of longer than one cycle
2. Witness the `gfsvrfy` job fail in every cycle after the first

**Possible Implementation**
Update [jobs/rocoto/vrfy.sh](https://github.com/NOAA-EMC/global-workflow/blob/develop/jobs/rocoto/vrfy.sh) to only run the VMINMON script if `${MODE}` is cycled.

**Comment by WalterKolczynski-NOAA** [comment]
I'll fix this one tonight/tomorrow.

**Comment by KateFriedman-NOAA** [comment]
Making change and testing in ongoing forecast-only tests of wavepost timing on WCOSS2.
