### ISSUE TITLE
2023 CO2 fix file update

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#1077]
The annual CO2 fix file update is here. Pull the new CO2 files from:

/lfs/h2/emc/physics/noscrub/qingfu.liu/CO2_for_NCO_2023/gfs.v16.2.3/fix/fix_am

New files:

- fix_am/co2dat_4a/global_co2historicaldata_2021.txt
- fix_am/co2dat_4a/global_co2historicaldata_2022.txt_proj_u
- fix_am/co2dat_4a/global_co2historicaldata_2023.txt_proj
- fix_am/fix_co2_proj/global_co2historicaldata_2023.txt
- fix_am/fix_co2_update/global_co2historicaldata_2022.txt

Tentatively going into operations as GFSv16.2.3.

Document on update in ops: https://docs.google.com/document/d/1D-3nqMAtd24tu2NbZBpXX8fkhmltZSny/edit

- [x] Pull new fix files into fix_nco_gfsv16 fix set (all new files).
- [x] Pull new fix files into primary fix set.
- [x] Check new files get into GFSv16.3.0 NCO install.
- [x] Tag and release NCO-v16.2.3.
- [x] Announce to users.

**Comment by KateFriedman-NOAA** [comment]
October 28th RFC memo:
> RFC 10196 - On WCOSS2, install 2023 carbon dioxide (CO2) fix file updates for
several model packages. The CFS, GEFS, GFS, HIRESW, HMON, NAM, and
SREF models rely on the historical/projected global CO2 abundance data in their
forecasts. To be implemented on November 3, 1230Z to 1600Z.

**Comment by XianwuXue-NOAA** [comment]
@KateFriedman-NOAA Could you also update the /lfs/h2/emc/global/save/emc.global/FIX/fix_nco_gfsv15 for GEFSv12.3.x? I am working on deliver the GEFSv12.3.2 to NCO this week, if the CO2 fix files is ready before the GEFSv12.3.2 implementation , then we don't need request to the co2 file update.

**Comment by KateFriedman-NOAA** [comment]
@XianwuXue-NOAA I have added the new CO2 files into the `fix_nco_gfsv15` set on both sides of WCOSS2. Do you want the Hera set updated too?
```
fix_nco_gfsv15/fix_am/co2dat_4a/
fix_nco_gfsv15/fix_am/co2dat_4a/global_co2historicaldata_2021.txt
fix_nco_gfsv15/fix_am/co2dat_4a/global_co2historicaldata_2022.txt_proj_u
fix_nco_gfsv15/fix_am/co2dat_4a/global_co2historicaldata_2023.txt_proj
fix_nco_gfsv15/fix_am/fix_co2_proj/
fix_nco_gfsv15/fix_am/fix_co2_proj/global_co2historicaldata_2023.txt
fix_nco_gfsv15/fix_am/fix_co2_update/
fix_nco_gfsv15/fix_am/fix_co2_update/global_co2historicaldata_2022.txt
```

**Comment by XianwuXue-NOAA** [comment]
@KateFriedman-NOAA Thanks a lot. Tough we don't run GEFS on Hera, however, it is good to update the Hera set for the future use.

**Comment by KateFriedman-NOAA** [comment]
@XianwuXue-NOAA The Hera copy of `fix_nco_gfsv15` is now updated with the new CO2 files.

**Comment by XianwuXue-NOAA** [comment]
@KateFriedman-NOAA Thank you very much!
