### ISSUE TITLE
preferred method of updating non-develop branch to develop

### ISSUE THREAD

**Issue by AndrewEichmann-NOAA** [NOAA-EMC/global-workflow#1087]
**Description**

What would be the preferred approach to updating a non-develop branch (such as feature/efsoi) to develop? Would one merge from develop, or rebase directly within the g-w repository?

Thanks

**Comment by WalterKolczynski-NOAA** [comment]
A lot depends on how much they've diverged and whether they are making overlapping changes. Rebasing can be cleaner (though I would recommend doing it on the command line), but complicated if you have to resolve a bunch of conflicts as you replay the feature branch commits on top of rebased base. Rebasing also requires force-pushes. For a long-lived branch like efsoi, simple merging is probably the way to go.

**Comment by KateFriedman-NOAA** [comment]
@AndrewEichmann-NOAA Was your question answered? If so, can this issue be closed? Thanks!

**Comment by AndrewEichmann-NOAA** [comment]
@KateFriedman-NOAA Yes, thank you
