### ISSUE TITLE
gfs_utils build fails on Orion

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/global-workflow#1093]
**Expected behavior**
The gfs_utils build should succeed when executing `sorc/build_all.sh` on Orion.

**Current behavior**
The gfs_utils build fails on Orion with the following message:
```
 .... Building gfs_utils ....
Fatal error in building gfs_utils.
The log file is in /work/noaa/da/Russ.Treadon/git/global_workflow/test/sorc/logs                              /build_gfs_utils.log
FATAL BUILD ERROR: Please check the log file for detail, ABORT!
```

The following error message is found in `sorc/logs/build_gfs_utils.log`
```
CMake Error at CMakeLists.txt:44 (find_package):
  By not providing "Findg2.cmake" in CMAKE_MODULE_PATH this project has asked
  CMake to find a package configuration file provided by "g2", but CMake did
  not find one.

  Could not find a package configuration file provided by "g2" with any of
  the following names:

    g2Config.cmake
    g2-config.cmake

  Add the installation prefix of "g2" to CMAKE_PREFIX_PATH or set "g2_DIR" to
  a directory containing one of the above files.  If "g2" provides a separate
  development package or SDK, be sure it has been installed.
```

**Machines affected**
Orion

**To Reproduce**

1. git clone https://github.com/NOAA-EMC/global-workflow.git .
2. cd sorc
3. ./checkout.sh
4. `./build_all.sh`.   If one wants to more quickly see the failure, edit `gfs_build.cfg` so that all builds are off except gfs_utils
 
**Possible Implementation**
According to `build_gfs_utils.log` the g2 package is not found.   `gfsutils_common.lua` loads, by default, `g2/3.4.5`   However, `logs/build_gfs_utils.log` does not include `g2` in the  module list.    The module use and load commands in `gfs_utils.fd/ush/build.sh` were executed in an interactive Orion session.  It was found that `g2/3.4.5` requires `hpc-intel/2022.1.2`.    This is problematic.   `gfsutils_orion` loads `hpc-impi/2018.4`.    

Correction of the problem reported in this issue will require changes be made in [gfs-utils](https://github.com/NOAA-EMC/gfs-utils).

**Comment by KateFriedman-NOAA** [comment]
I just hit this too and have a remedy. Will fix in gfs-utils. Thanks!

**Comment by KateFriedman-NOAA** [comment]
FYI: https://github.com/NOAA-EMC/gfs-utils/issues/14

**Comment by KateFriedman-NOAA** [comment]
FYI: https://github.com/NOAA-EMC/gfs-utils/pull/15

**Comment by KateFriedman-NOAA** [comment]
New hash of gfs-utils ([56e6880](https://github.com/NOAA-EMC/gfs-utils/commit/56e688085c8f6ab77dc48ac02637e322cc2ab4f7)) resolves the build error on Orion. That hash also updated gfs-utils to use `module reset` instead of `module purge` on most of the machines. @WalterKolczynski-NOAA will have a companion PR to make a similar `module reset` update to global-workflow build scripts and move to this new hash shortly. @RussTreadon-NOAA you can checkout that new hash on Orion for now to get it built in your clone.

**Comment by RussTreadon-NOAA** [comment]
@KateFriedman-NOAA , I updated my working copy of `gfs_utils.fd` to [56e6880](https://github.com/NOAA-EMC/gfs-utils/commit/56e688085c8f6ab77dc48ac02637e322cc2ab4f7) and reran g-w `build_all.sh` for gfs_utils alone.   The build was successful.
```
Orion-login-2:/work/noaa/da/Russ.Treadon/git/global_workflow/test/sorc$ ./build_all.sh
 .... Skip building gsi and enkf ....
 .... Skip building gsi utilities ....
 .... Skip building GDASApp  ....
 .... Skip building gsi monitor ....
 .... Skip building gldas ....
 .... Building gfs_utils ....

 .... Build system finished ....

```
I did not attempt to execute any gfs_util apps or scripts.

**Comment by KateFriedman-NOAA** [comment]
Cool, thanks for confirming @RussTreadon-NOAA !
