### ISSUE TITLE
Review CFP usage in GLDAS scripts

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#1095]
**Description**

The GLDAS job currently needs `USE_CFP=NO` on the R&Ds (Hera/Orion). Review CFP usage/method in the GLDAS scripts and update the scripts to use CFP again.

**Comment by WalterKolczynski-NOAA** [comment]
With GLDAS being replaced for v17, I think we can close this one.

**Comment by KateFriedman-NOAA** [comment]
Agreed. Closing.
