### ISSUE TITLE
GFS v16.3 VIIRS realtime parallel for implementation

### ISSUE THREAD

**Issue by lgannoaa** [NOAA-EMC/global-workflow#1097]
**Description**

@emilyhcliu requested assistance in running VIIRS experiment on Cactus for DA group.
This is a operational resolution realtime parallel experiment for VIIRS using ecflow workflow on Cactus.
The warm start file rsync from the NCO 30 days parallel for the starting cycle on CDATE=2022102600.

The configuration for this parallel is:
First full cycle starting CDATE is 2022102600
HOMEgfs: /lfs/h2/emc/global/noscrub/lin.gan/git/gfsda.v16.3.0
pslot: v163viirs
EXPDIR: /lfs/h2/emc/global/noscrub/lin.gan/git/gfsda.v16.3.0/parm/config
COM: /lfs/h2/emc/ptmp/lin.gan/v163viirs/para/com/gfs/v16.3
log: /lfs/h2/emc/ptmp/lin.gan/v163viirs/para/com/output/prod/today
on-line archive: /lfs/h2/emc/global/noscrub/lin.gan/archive/v163viirs
METPlus stat files: Does not run
FIT2OBS: /lfs/h2/emc/global/noscrub/lin.gan/archive/v163viirs/fits
Verification Web site: Does not run
The obsproc and rtofs will be using the same location from NCO 30 days parallel.  The obsproc prepbufr for example, will be accessed from /lfs/h1/ops/prod/com/obsproc/v1.1
HPSS archive: /NCEPDEV/emc-global/5year/lin.gan/WCOSS2/scratch/v163viirs

This realtime parallel experiment will not run the following jobs:
obsproc jobs (i.e. prepbufr...), prep jobs
GFS post_processing - include bufr sounding, fbwind, wafs, and awips
GFS gempak
GDAS gempak

Change use flags (the third column) for VIIRS in the global_satinfo.txt as the following:
 viirs-m_npp            12   1    0.500    0.000    6.000   10.000    0.000      1     -1     -1
 viirs-m_npp            13  -1    0.800    0.000    6.000   10.000    0.000     -1     -1     -1
 viirs-m_npp            14  -1    0.800    0.000    6.000   10.000    0.000     -1     -1     -1
 viirs-m_npp            15   1    0.580    0.000    6.000   10.000    0.000      1     -1     -1
 viirs-m_npp            16   1    0.620    0.000    6.000   10.000    0.000      1     -1     -1
 viirs-m_j1             12   1    0.500    0.000    6.000   10.000    0.000      1     -1     -1
 viirs-m_j1             13  -1    0.800    0.000    6.000   10.000    0.000     -1     -1     -1
 viirs-m_j1             14  -1    0.800    0.000    6.000   10.000    0.000     -1     -1     -1
 viirs-m_j1             15   1    0.580    0.000    6.000   10.000    0.000      1     -1     -1
 viirs-m_j1             16   1    0.620    0.000    6.000   10.000    0.000      1     -1     -1

**Comment by lgannoaa** [comment]
Both PTMP and STMP are at 95% on 10/31 morning.
There is a scheduled WCOSS2 Parallel production test on Cactus for 11/1.
This parallel will be paused for a few cycles.

**Comment by lgannoaa** [comment]
This parallel is paused on CDATE=2022103106 due to Cactus STMP is full. This parallel is resumed at noon.

**Comment by lgannoaa** [comment]
This parallel is paused on CDATE=2022110100 due to ptmp/stmp full.

**Comment by lgannoaa** [comment]
The GFS cycle on CDATE=2022110106 failed due to system issue rerun is progress.
This parallel is in halt on CDATE=2022110112 due to NCO mirror issue with obsproc data.
Resumed after file arrival.

**Comment by lgannoaa** [comment]
There are combination of system issue caused multiple jobs failed. Node slowness and long I/O time are observed.
Recover is in progress.

**Comment by lgannoaa** [comment]
This parallel is now caught on realtime.

**Comment by lgannoaa** [comment]
The gfs fcst is in queue for over a day due to Cactus busy. CDATE=2022110806
If system remain busy, the COM will be touched by noon on 11/10/22
It proceed a bit more over the night of 11/09. Therefor the COM will not be touched at this time.

**Comment by lgannoaa** [comment]
COM is touched and parallel paused on CDATE=2022120818 due to production switch on 12/09/22.

**Comment by emilyhcliu** [comment]
We have 1.5-month-long assimilation results from the VIIRS run.  The developers assessed the impact of VIIRS from this run. 
So, it is time to end the VIIRS experiment.

**Comment by lgannoaa** [comment]
Last successful run is CDATE=2022120812
Ending ecflow parallel run. PTMP/STMP clean out.
Close issue.
