### ISSUE TITLE
rerunning link_workflow.sh generates gdas fix error

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/global-workflow#1100]
**Expected behavior**
Reruns `./link_workflow.sh` should complete without error.

**Current behavior**
Rerunning `./link_workflow.sh` returns an error as shown below
```
[Russ.Treadon@hfe11 sorc]$ ./link_workflow.sh
ln: failed to create symbolic link 'bump/20220805': Permission denied
./link_workflow.sh encounted an error at line 184 (rc=1)

```
**Machines affected**
Only tested on Hera but may occur on other machines.

**To Reproduce**

1. clone g-w develop
2. `cd sorc`
3. `./checkout.sh -u`
4. `./build_all.sh`
5. `./link_workflow.sh`
6. `./link_workflow.sh`

The second execution of `./link_workflow.sh` will generate an error.

**Context**
It is not uncommon for a developer change of a g-w component to necessitate relinking files.

**Additional Information**
If the gdas fix section of `./link_workflow.sh` is commented out, reruns of `./link_workflow.sh` complete without error.

**Comment by RussTreadon-NOAA** [comment]
The following change to `./link_workflow.sh` removes the gdas fix error
```
[Russ.Treadon@hfe11 sorc]$ git diff link_workflow.sh
diff --git a/sorc/link_workflow.sh b/sorc/link_workflow.sh
index 3c21a3ea..91f9222d 100755
--- a/sorc/link_workflow.sh
+++ b/sorc/link_workflow.sh
@@ -180,6 +180,9 @@ if [ -d "${script_dir}/gdas.cd" ]; then
     [[ ! -d gdas ]] && mkdir -p gdas
     cd gdas || exit 1
     for gdas_sub in bump crtm fv3jedi; do
+      if [ -d ${gdas_sub} ]; then
+         rm -rf "${gdas_sub}"
+      fi
       fix_ver="gdas_${gdas_sub}_ver"
       ${LINK} "${FIX_DIR}/gdas/${gdas_sub}/${!fix_ver}" "${gdas_sub}"
     done
```

Executing `./link_workflow.sh` with the above change yields
```
[Russ.Treadon@hfe11 sorc]$ ./link_workflow.sh
./link_workflow.sh completed successfully
[Russ.Treadon@hfe11 sorc]$
```

**Comment by RussTreadon-NOAA** [comment]
Another error noted in `fix/gdas`.   File `fix/gdas/gdas_minmon_gnorm.txt` is a dead link

```
rwxr-sr-x 4 glopara      global   4096 Oct 11 16:28 bump
drwxr-sr-x 4 glopara      global   4096 Oct 11 16:58 crtm
drwxr-sr-x 5 glopara      global   4096 Oct 11 16:58 fv3jedi
-rw-r--r-- 1 Russ.Treadon da         92 Oct 25 00:09 gdas_minmon_cost.txt
l????????? ? ?            ?           ?            ? gdas_minmon_gnorm.txt
-rw-r--r-- 1 Russ.Treadon da      30720 Oct 25 00:09 gdas_oznmon_base.tar
-rw-r--r-- 1 Russ.Treadon da        125 Oct 25 00:09 gdas_oznmon_satype.txt
-rw-r--r-- 1 Russ.Treadon da     471040 Oct 25 00:09 gdas_radmon_base.tar
-rw-r--r-- 1 Russ.Treadon da        385 Oct 25 00:09 gdas_radmon_satype.txt
-rw-r--r-- 1 Russ.Treadon da       3741 Oct 25 00:09 gdas_radmon_scaninfo.txt
```

[`link_workflow.sh`](https://github.com/NOAA-EMC/global-workflow/blob/develop/sorc/link_workflow.sh) includes two whitespace characters at the end of the quoted path/filename linked to `gdas_minmon_gnorm.txt`.   

    ${LINK} "${script_dir}/gsi_monitor.fd/src/Minimization_Monitor/nwprod/gdas/fix/gdas_minmon_gnorm.txt  "                .

The two extra whitespace trace back to the initial commit of `link_workflow.sh` at [e7f72ed](https://github.com/NOAA-EMC/global-workflow/commit/e7f72e8).   Removing the extra whitespace in `link_workflow.sh` 


```
@@ -203,7 +206,7 @@ if [ -d "${script_dir}/gsi_monitor.fd" ]; then
     [[ ! -d gdas ]] && ( mkdir -p gdas || exit 1 )
     cd gdas || exit 1
     ${LINK} "${script_dir}/gsi_monitor.fd/src/Minimization_Monitor/nwprod/gdas/fix/gdas_minmon_cost.txt"                   .
-    ${LINK} "${script_dir}/gsi_monitor.fd/src/Minimization_Monitor/nwprod/gdas/fix/gdas_minmon_gnorm.txt  "                .
+    ${LINK} "${script_dir}/gsi_monitor.fd/src/Minimization_Monitor/nwprod/gdas/fix/gdas_minmon_gnorm.txt"                  .
     ${LINK} "${script_dir}/gsi_monitor.fd/src/Ozone_Monitor/nwprod/gdas_oznmon/fix/gdas_oznmon_base.tar"                   .
     ${LINK} "${script_dir}/gsi_monitor.fd/src/Ozone_Monitor/nwprod/gdas_oznmon/fix/gdas_oznmon_satype.txt"                 .
     ${LINK} "${script_dir}/gsi_monitor.fd/src/Radiance_Monitor/nwprod/gdas_radmon/fix/gdas_radmon_base.tar"                .
```
yields a functional link in `fix/gdas`.

**Comment by KateFriedman-NOAA** [comment]
Thanks for these fixes @RussTreadon-NOAA ! I've tested it myself as well and confirm the error and resulting fix works (including the dead link and its fix). I will initiate a PR to get these fixes into `develop`.
