### ISSUE TITLE
Update MODULEPATH on Orion

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#1119]
**Description**

The `MODULEPATH` currently used in `develop` is owned by a user who is no longer at EMC. @Hang-Lei-NOAA made a copy on Orion and is adding new modules to this install now as needed. The `develop` branch needs to now use this new `MODULEPATH` owned by @Hang-Lei-NOAA .

Old `MODULEPATH` : `/apps/contrib/NCEP/libs/hpc-stack/modulefiles/stack`
New `MODULEPATH`: `/apps/contrib/NCEP/hpc-stack/libs/hpc-stack/modulefiles/stack`

A related update happened in the `release/gfs.v16.3.0` branch.

FYI to component manages using hpc-stack on Orion: @junwang-noaa @DusanJovic-NOAA @GeorgeGayno-NOAA @HelinWei-NOAA @RussTreadon-NOAA @WenMeng-NOAA 

**Requirements**

The `develop` branch needs to build and run on Orion using this updated `MODULEPATH`.

**Acceptance Criteria (Definition of Done)**

The `develop` branch builds and runs without issue on Orion using this updated `MODULEPATH`.

**Dependencies**

New hpc-stack install is already in place. Through build and run testing I will determine if any needed modules are missing and will request resolution through the hpc-stack team.

**Comment by WenMeng-NOAA** [comment]
@KateFriedman-NOAA The UPP develop branch was already updated with the new MODULEPATH. See:
https://github.com/NOAA-EMC/UPP/blob/develop/modulefiles/orion.lua
Please let me know if any updates are needed at UPP side.

**Comment by KateFriedman-NOAA** [comment]
> The UPP develop branch was already updated with the new MODULEPATH. See: https://github.com/NOAA-EMC/UPP/blob/develop/modulefiles/orion.lua 

@WenMeng-NOAA Excellent! Thanks for letting me know! :)

> Please let me know if any updates are needed at UPP side.

Will do, thanks!
