### ISSUE TITLE
Stage GSI fix files in global/glopara space and disable recursive clone of GSI

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/global-workflow#1128]
**Description**
The global DA group would like to stage GSI fix files in the global/glopara space similar to the model fix files.
Part of this is motivated from the unknown and recurring issues with cloning GSI-fix from gerrit.

**Requirements**
1. Stage GSI-fix in the global/glopara space on RDHPCS and WCOSS2.  Do so by cloning `gerrit:GSI-fix` at `023f81d` (head of `rev2` branch).
2. Disable recursive clone of GSI in `checkout.sh`
3. Update `link_workflow.sh` to create a link of the GSI-fix files from glopara space to the global-workflow `fix/`

**Acceptance Criteria (Definition of Done)**
1. GSI fix files are staged in global/glopara spaces on RDHPCS (Hera, Orion, Jet, S4) and WCOSS2
2. GSI should not clone fix files from global-workflow
3. GSI-fix files should be linked from global/glopara spaces similar to model fix files.

@KateFriedman-NOAA maintains Hera, Orion and WCOSS2
@DavidHuber-NOAA maintains Jet and S4 spaces
@aerorahul will update the global-workflow `develop` to make the links and disable the recursive clone of GSI in global-workflow.

**Comment by DavidHuber-NOAA** [comment]
@aerorahul I will pull the fix files into the S4 glopara space.  However, I do not  have write access in Jet's glopara space.

**Comment by KateFriedman-NOAA** [comment]
I maintain the Jet (glopara) copy (in addition to the WCOSS2, Hera, and Orion ones). I can update the Jet copy.

**Comment by KateFriedman-NOAA** [comment]
@RussTreadon-NOAA I'm working on the staging task now...is the `VLabRepoQuickTips.txt` necessary to be included? Also wondering about the `example_unformatted_fileinfo.txt` file. Let me know, thanks!

**Comment by RussTreadon-NOAA** [comment]
> @RussTreadon-NOAA I'm working on the staging task now...is the `VLabRepoQuickTips.txt` necessary to be included? Also wondering about the `example_unformatted_fileinfo.txt` file. Let me know, thanks!

@KateFriedman-NOAA , for the time being I recommend preserving the integrity of GSI fix.

**Comment by KateFriedman-NOAA** [comment]
@RussTreadon-NOAA Okie dokie. I have copied the contents of your `/scratch1/NCEPDEV/da/Russ.Treadon/git/gsi/develop/fix` folder (the requested hash/branch) into a new `gsi/20221128` folder in the Hera fix set. Please see the following and let me know if it looks good: `/scratch1/NCEPDEV/global/glopara/fix/gsi/20221128`
FYI, I adjusted file/folder permissions to match the rest of the fix subfolders. Once I get the thumbs up that the Hera fix copy is good I'll rsync it to WCOSS2, Orion, and Jet. @DavidHuber-NOAA can rsync to S4.
@aerorahul did you want to test the Hera copy before I rsync to the other platforms?

**Comment by RussTreadon-NOAA** [comment]
@KateFriedman-NOAA , thank you for adding the GSI fix files to the glopara account on Hera.  A local copy of the GSI has been updated to run regression tests using glopara fix.   I'll update this issue upon successful completion of this test.

**Comment by KateFriedman-NOAA** [comment]
@RussTreadon-NOAA indicated regression tests are going well so far on Hera (https://github.com/NOAA-EMC/global-workflow/pull/1132#issuecomment-1329661015). Rsyncing new Hera `gsi` subfolder to WCOSS2s, Orion, and Jet now. @DavidHuber-NOAA feel free to update the S4 set now.

**Comment by DavidHuber-NOAA** [comment]
@KateFriedman-NOAA All finished on S4.

**Comment by KateFriedman-NOAA** [comment]
Hera, Orion, Jet, S4 fix copies now updated with new `gsi` subfolder. WCOSS2 (Cactus/Dogwood) will be updated within the next few hours.

**Comment by KateFriedman-NOAA** [comment]
New `gsi` subfolder is now in place on both WCOSS2s.
