### ISSUE TITLE
C48 fails on WCOSS2

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/global-workflow#1129]
**Expected behavior**
`C48` should run on all platforms.

**Current behavior**
`C48` is currently the ensemble resolution test case and fails on WCOSS2.  (All) members successfully complete integration on Hera and Orion.

**Machines affected**
WCOSS2

**To Reproduce**
Try and run a cycled experiment at C96/C48 on WCOSS2.

**Detailed Description**
It is found that the number of threads is set to 2 for C48 and that seems to be causing the failures on WCOSS2.

**Possible Implementation**
Reduce number of threads for C48 to 1 for all platforms unless someone from the modeling teams can address the threading issue.  Running w/ 1 thread should allow development and testing of the global-workflow.

**Comment by WalterKolczynski-NOAA** [comment]
Is there an issue open with UFS to fix the underlying problem?
