### ISSUE TITLE
gdaspostanl fails on the first half cycle in cycled mode

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/global-workflow#1130]
**Expected behavior**
All post tasks should complete successfully

**Current behavior**
In cycled mode, the first half cycle is attempting to run the `gdaspostanl`.  This task requires the existence of `gdas.tHHz.atmanl.nc` and is not present.
As a result the task fails and the workflow cycle is not complete.

**Machines affected**
All machines, though hard failure is seen on WCOSS2 and no error is reported on Hera and Orion. 🤷🏾‍♂️ 

**To Reproduce**
Attempt running a cycled workflow on WCOSS2

**Context**

As seen here,
![unnamed](https://user-images.githubusercontent.com/11394126/203368955-8d34e350-65f3-4163-aa92-fe221a73f60e.png)

the task gdaspost#grp# runs in both the gdas_half and gdas cycledefs.
The #grp# contains anl, along with the forecast hours.

**Possible Implementation**
A `gdaspostanl` task should be created that runs the offline post for post-processing the analysis (It also uses different resources than those needed for processing forecast hours)

The `gdaspost` metatask should only contain forecast hours.

**Comment by lgannoaa** [comment]
The first half cycle GDAS does not run analysis step. Therefore the required file is not created. Two recommended solutions:
1. Modify setup_expt.py to exclude gdaspostanl job in rocoto XML file.
2. Review exception handling on gdaspostanl job to ensure it report error and fail job on all supported platforms.

**Comment by lgannoaa** [comment]
We maybe able to address #1006 with this ticket at the same time.

**Comment by KateFriedman-NOAA** [comment]
No longer fails because of a hack put in place. Closing.

**Comment by KateFriedman-NOAA** [comment]
Hack in question:
https://github.com/NOAA-EMC/global-workflow/blob/develop/jobs/JGLOBAL_ATMOS_POST#L21:L29
```
##############################################
# TODO: Remove this egregious HACK
##############################################
if [[ "${SDATE:-}" = "${PDY}${cyc}" ]]; then
  if [[ ${post_times} = "anl" ]]; then
    echo "No offline post-processing in the first half cycle for analysis"
    exit 0
  fi
fi
```
