### ISSUE TITLE
Unbound variable (RSTDIR_ATM) in forecast_det.sh (minor bug)

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/global-workflow#1140]
Your bug may already be reported!
Please search on the [Issue tracker](https://github.com/NOAA-EMC/global-workflow/issues) before creating one.

**Expected behavior**

FV3_GFS_det should run without error when called during gdasfcst jobs.  `RSTDIR_ATM` is only a required variable for gfsfcst jobs (set in [forecast_predet.sh:212](https://github.com/NOAA-EMC/global-workflow/blob/e2c29749ffe4050ce4e0273ef4802b8458bbc59c/ush/forecast_predet.sh#L212)) and should not be referenced.

**Current behavior**

`RSTDIR_ATM` is referenced during both gdas and gfs fcst steps, resulting in an unbound error at [forecast_det.sh:43](https://github.com/NOAA-EMC/global-workflow/blob/develop/ush/forecast_det.sh#L43) during gdasfcst.  It appears that this unbound error only affects the `find` command within the command substitution and so flow continues with `filecount=0`, which does not affect on the remainder of the function.  I'm not sure if this is the usual/constant behavior when `set -u` is toggled.

**Machines affected**

Found on Google Cloud.

**To Reproduce**

Run a gdasfcst job and check the resulting log.

**Possible Implementation**

Replace
`filecount=$(find $RSTDIR_ATM -type f | wc -l)`
with
`[[ $CDUMP = "gfs" ]] && filecount=$(find $RSTDIR_ATM -type f | wc -l)`
or
remove `$CDUMP = "gfs"` from the proceeding `if` and move the `filecount` assignment and the proceeding `if` into a new `if [ $CDUMP = "gfs" ]; then` block.

**Comment by lgannoaa** [comment]
@DavidHuber-NOAA, It looks to me the description is point to a different file. Please update and confirm this issue. The file in question should be forecast_det.sh. Line number for the logic in question is 43.

**Comment by DavidHuber-NOAA** [comment]
@lgannoaa You are correct that the file is forecast_det.sh and the line in question is 43.  This is what is stated in the description under "Current behavior".  I also mention that the variable is created in forecast_predet.sh.  I felt this was relevant information as it is apparent in forecast_predet.sh that the variable should only be used during GDAS forecasts.  Apologies if this caused confusion.

**Comment by lgannoaa** [comment]
@DavidHuber-NOAA , I have a file ready for you to test. Please let me know if it looks good for you, so I can create PR for it.
hera:/scratch1/NCEPDEV/global/Lin.Gan/git/PR/issue-1140/ush/forecast_det.sh

**Comment by DavidHuber-NOAA** [comment]
@lgannoaa the changes look good to me.  Thanks!
