### ISSUE TITLE
Octal forecast hour unintentionally used in logical expression

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/global-workflow#1141]
**Expected behavior**

Forecast hours (`fhr`) should be treated as a decimal, not octal, when executing math expressions.

**Current behavior**

In [exgdas_atmos_post.sh:222](https://github.com/NOAA-EMC/global-workflow/blob/e2c29749ffe4050ce4e0273ef4802b8458bbc59c/scripts/exgdas_atmos_post.sh#L222), `fhr` is treated as an octal, resulting in an error when `fhr=008`, etc.  This results in the `if` evaluating to `false` and `IGEN=${IGEN_ANL}`.  In the end, this makes not difference as `IGEN` is not used in any meaningful way.

**Machines affected**

All

**To Reproduce**

Run a post job for forecast hour 008 or 009.

**Possible Implementation**

Remove all references to `IGEN`, unless there are plans to use this variable in the future.  If so, then replace
`if (( fhr > 0 )); then`
with
```
d_fhr=$((10#$fhr))
if (( d_fhr > 0 )); then
```

**Comment by lgannoaa** [comment]
I will take a look.
