### ISSUE TITLE
Update getic.sh script to handle naming convention of HPSS tarballs after 00Z 27Jun22 

### ISSUE THREAD

**Issue by jkhender** [NOAA-EMC/global-workflow#1155]
**Expected behavior**
getic.sh should extract _gfs.t00z.pgrb2.0p25.anl, gfs.t00z.pgrb2.0p50.anl,_ and _gfs.t00z.pgrb2.1p0.anl_ files from the HPSS tarball, com_gfs_v16.2_gfs.20221115_00.gfs_pgrb2.tar, since cycle date is after 06/27/22

**Current behavior**
filename is hardwired to com_gfs_prod_gfs.20221115_00.gfs_pgrb2.tar in getic.sh, so following error is returned

ERROR:  [FATAL] no such HPSS archive file:

**Machines affected**
All

**To Reproduce**
Run getic task for cycle date after 06/27/22

**Possible Implementation**
Update getic.sh to handle different HPSS tarball names

**Comment by lgannoaa** [comment]
I will take a look.

**Comment by lgannoaa** [comment]
A solution to address this issue has been developed by the https://github.com/ufs-community/UFS_UTILS/pull/723

**Comment by jkhender** [comment]
To clarify, there are 2 sections where the file names will be incorrect. Lines 85-91 pull data for warm starts.

```
 85   else # Opertional input - warm starts
 86
 87     cd $ROTDIR
 88     # Pull CDATE gfs restart tarball
 89     htar -xvf ${PRODHPSSDIR}/rh${yy}/${yy}${mm}/${yy}${mm}${dd}/com_gfs_prod_gfs.${yy}${mm}${dd}_${hh}.gfs_restart.tar
 90     # Pull GDATE gdas restart tarball
 91     htar -xvf ${PRODHPSSDIR}/rh${gyy}/${gyy}${gmm}/${gyy}${gmm}${gdd}/com_gfs_prod_gdas.${gyy}${gmm}${gdd}_${ghh}.gdas_restart.tar
 92   fi
```

Since I was testing a cold start experiment, my script executed line 97 instead which calls the ufs_utils script, sorc/ufs_utils.fd/util/gdas_init/get_v16.data.sh. I did not get an error there, since it had been updated to handle v16.2 filenames.

```
 94 else # Pull chgres cube inputs for cold start IC generation
 95
 96   # Run UFS_UTILS GETICSH
 97   sh ${GETICSH} ${CDUMP}
 98   status=$?
 99   [[ $status -ne 0 ]] && exit $status
100
101 fi
```

Farther down in the getic.sh script, the pgbanl files are pulled from the tarballs. This is where I saw the incorrect name for the tarball in line 146.

```
143       else # Production source
144
145         cd $ROTDIR
146         export tarball="com_gfs_prod_gfs.${yy}${mm}${dd}_${hh}.gfs_pgrb2.tar"
147         htar -xvf ${PRODHPSSDIR}/rh${yy}/${yy}${mm}/${yy}${mm}${dd}/${tarball} ./${CDUMP}.${yy}${mm}${dd}/${hh}/atmos/${file}
148
149       fi # RETRO vs production
```

**Comment by aerorahul** [comment]
OBE
