### ISSUE TITLE
Error with getic task if ROTDIR directory not cleaned up

### ISSUE THREAD

**Issue by jkhender** [NOAA-EMC/global-workflow#1156]
**Expected behavior**
User should not have to clean up $ROTDIR before running getic again after it fails

**Current behavior**
After I ran the getic task and it failed (see issue #1155), the job was resubmitted. The job gave an error when running the following statement.

` mv ${EXTRACT_DIR}/${CDUMP}.${yy}${mm}${dd}/${hh}/* ${ROTDIR}/${CDUMP}.${yy}${mm}${dd}/${hh}
`

mv: cannot move <EXTRACT_DIR>/gfs.20221115/00/* to <ROT_DIR>/gfs.20221115/00/atmos': Directory not empty

**Machines affected**
All

**To Reproduce**
run getic.sh before fixing it for issue #1155 and then resubmit job

**Comment by lgannoaa** [comment]
Job getic task successfully completed on first attempt. It is recommended only rerun the failed job as needed.
The job getic.sh should be updated with exception handlining in place to fail the job if the target directory is not empty.
Will provide a PR for the fix.
