### ISSUE TITLE
Missing jobid in some jobs

### ISSUE THREAD

**Issue by XianwuXue-NOAA** [NOAA-EMC/global-workflow#1169]
**Expected behavior**

Missing jobid in some jobs

**Current behavior**

It will cause the failure of the jobs

**Machines affected**

WCOSS2

**To Reproduce**

Run these jobs, it will fail due to missing jobid

The affected scripts:

Tested: 
- [x] jobs/rocoto/arch.sh
- [x] jobs/rocoto/earc.sh
- [x] jobs/rocoto/gldas.sh

Not tested, maybe need to add:

- [ ] jobs/rocoto/aerosol_init.sh
- [ ] jobs/rocoto/awips.sh
- [ ] jobs/rocoto/coupled_ic.sh
- [ ] jobs/rocoto/gempak.sh
- [ ] jobs/rocoto/getic.sh
- [ ] jobs/rocoto/init.sh
- [ ] jobs/rocoto/postsnd.sh
- [ ] jobs/rocoto/prep.sh
- [ ] jobs/rocoto/waveawipsbulls.sh
- [ ] jobs/rocoto/waveawipsgridded.sh
- [ ] jobs/rocoto/wavegempak.sh

For futures use jobs:

- [x] jobs/rocoto/aeroanlfinal.sh
- [x] jobs/rocoto/aeroanlinit.sh
- [x] jobs/rocoto/aeroanlrun.sh
- [x] jobs/rocoto/ocnanalpost.sh
- [x] jobs/rocoto/ocnanalprep.sh
- [x] jobs/rocoto/ocnanalrun.sh

**Comment by XianwuXue-NOAA** [comment]
The affected scripts:

- jobs/rocoto/arch.sh
- jobs/rocoto/earc.sh
- jobs/rocoto/gldas.sh

**Comment by aerorahul** [comment]
@XianwuXue-NOAA 
Can you please test w/ https://github.com/aerorahul/global-workflow/tree/hotfix/missing-jobids

**Comment by XianwuXue-NOAA** [comment]
ok

**Comment by XianwuXue-NOAA** [comment]
@aerorahul tested successfully

**Comment by aerorahul** [comment]
> @aerorahul tested successfully

Great.  Thanks.
Please review #1176
