### ISSUE TITLE
Change bufr station Hilo's grid point representation

### ISSUE THREAD

**Issue by GuangPingLou-NOAA** [NOAA-EMC/global-workflow#117]
Current bufr station Hilo's model grid point is on the west of the station where terrain is mountainous and it is not a good representation for the station. After thorough testings and analyses it was found a grid point on the south of the station is a better representation for the station. The original grid point (i,j=1749,600) is therefore replaced by (i,j)=(1750,601).

**Comment by KateFriedman-NOAA** [comment]
@GuangPingLou-NOAA Is this issue complete? If so, please close, thanks!
