### ISSUE TITLE
Fix global workflow post resource assignment issue when WRITE_DOPOST=".false."

### ISSUE THREAD

**Issue by lgannoaa** [NOAA-EMC/global-workflow#1180]
A test on global workflow develop #3e53e06 (latest as of 12/13/22) found the offline post resource assignments are not working for Hera. In which, the offline post is enabled by setting WRITE_DOPOST=".false." in config.base file.

There are two ways to run post; turn on in-line post or not (offline post) . A research found issue #678 indicated likely the offline post should still be supported.

**Expected behavior**

The global workflow generate the xml file in EXPDIR with correct post job resource assignment.

**Current behavior**

Post job resource reservation is wrong when using offline post. 

**Machines affected**

Observed in Hera. Similar behavior is likely on other platforms.

**To Reproduce**

Checkout global workflow develop, build, and link. 
Create expdir using python script. 
Modify config.base and set WRITE_DOPOST=".false.". 
Create xml file using python script.
Run a test and observe post failed with resource assignment issue.

**Detailed Description**

The resource required for post job is different between using inline post and offline post. Therefor, global workflow should be able to assign right resource in XML by according to the WRITE_DOPOST setting in config.base. 

**Possible Implementation**

Update resource file to include inline post support.
Update python script to create xml file according to the WRITE_DOPOST setting in config.base.

**Comment by WalterKolczynski-NOAA** [comment]
OBE. Offline post and product generation have been separated, so post resources can be set separately. If an issue persists, please open a new issue with current details.
