### ISSUE TITLE
Create an `obs` component in preparation for coupled DA

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/global-workflow#1198]
**Description**
All observations in the current cycled system are linked/copied or created into the `atmos/` subdirectory under `ROTDIR` as follows:
```
gdas.20211220
    └── 18
        ├── atmos
        │   ├── gdas.t18z.*.bufr_d # These are typically soft-linked from GDA
        │   ├── gdas.t18z.prepbufr
        │   ├── gdas.t18z.prepbufr.acft_profiles
        │   ├── gdas.t18z.nsstbufr
        │   ├── INPUT/
        │   └── RESTART/
        └── wave/
```

As the GFS evolves towards coupled system, these observations should be treated as a component accessible to other components of the GFS, e.g. ocean, ice etc.

The proposed structure is to create an `obs` component where all the observations for a cycle are linked/copied or created into.

```
gdas.20211220
    └── 18
        ├── atmos
        │   ├── INPUT
        │   └── RESTART
        ├── obs
        │   ├── gdas.t18z.*.bufr_d # These are typically soft-linked from GDA
        │   ├── gdas.t18z.prepbufr
        │   ├── gdas.t18z.prepbufr.acft_profiles
        │   └── gdas.t18z.nsstbufr
        └── wave
``` 

The `gfs` cycle would have a similar directory structure and requirement as the `gdas` shown above.

**Requirements**
- [ ] Create an `obs` component
- [ ] Link/copy observations from `DMPDIR` into this `obs` component
- [ ] If new observation files are created e.g. `prepbufr`, they should be placed in the `obs/` component instead of `atmos/`

**Acceptance Criteria (Definition of Done)**
Cycled mode of the GFS should produce bit-reproducible results

**Dependencies**
None

**Notes**
@dtkleist @RussTreadon-NOAA @CoryMartin-NOAA @guillaumevernieres 
Please take a note of this for GDASApp applications.
It is suggested that all observations used/generated within the application are placed in this `obs` component.

**Comment by lgannoaa** [comment]
A meeting on 2023/01/06 has decided this issue will be addressed in multiple PR. 

The first PR is #1202 which address the following:
(1) "${CDUMP}.${cycle}.seaice.5min.blend.grb" file will be located under atmos subdirectory.
(2) "${CDUMP}.${cycle}.snogrb_t1534.3072.1536" file will be located under atmos subdirectory.
(3) "${CDUMP}.${cycle}.syndata.tcvitals.tm00" file will be located under atmos subdirectory.
(4) Link/copy observations from DMPDIR into this obs component.
(5) Some observation files created (e.g. prepbufr) are placed in the obs component.
