### ISSUE TITLE
Developer parallels do not use self generated prepbufr, prepbufr_profl, and nsstbufr files

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/global-workflow#1207]
**Expected behavior**
If a developer runs a parallel with `MAKE_PREPBUFR`, `MAKE_ACFTBUFR`, or `MAKE_NSSTBUFR` set to `YES`, the parallel anal job should use the corresponding dump file(s) created by the prep job.

**Current behavior**
Even if `MAKE_PREPBUFR`, `MAKE_ACFTBUFR`, or `MAKE_NSSTBUFR` are set to `YES`, the parallel uses the prepbufr, prepbufr_profl, and nsstbufr file from the machine specific GDA.

**Machines affected**
Observed on Hera but likely occurs on other platforms too.

**To Reproduce**
1. clone g-w and check out components
2. build g-w apps
3. set up an experiment
4. ensure ` MAKE_PREPBUFR="YES"` in `config.prep`
5. ensure `MAKE_ACFTBUFR="YES"`, and `MAKE_NSSTBUFR="YES"` in `config.base`
6. execute gdas prep
7. execute gdas anal
8. check the paths used for `PREPQC`, `PREPQCPF`, and `NSSTBF` in gdasanal.log.

The paths for these three dump files will point at the machine specific GDA `DMPDIR`.

**Additional Information**
`config.base.emc.dyn` contains `COMIN_OBS=${DMPDIR}/${CDUMP}.${PDY}/$cyc/atmos`.  The workflow generation scripts in `workflow\` set `DMPDIR` based on the `$machine` on which the workflow is generated.   As a result, `COMIN_OBS` in the developer `config.base` points at the machine specific `DMPDIR`.   This is okay for most dump files.   It is not okay if the developer wants to use the prepbufr, prepbufr_profl, or nsstbufr file generated by the parallel prep step.   

Script `exglobal_atmos_analysis.sh` picks up the prepbufr, prepbufr_profl and nsstbufr files via
```
PREPQC=${PREPQC:-${COMIN_OBS}/${OPREFIX}prepbufr${OSUFFIX}}
PREPQCPF=${PREPQCPF:-${COMIN_OBS}/${OPREFIX}prepbufr.acft_profiles${OSUFFIX}}
NSSTBF=${NSSTBF:-${COMIN_OBS}/${OPREFIX}nsstbufr${OSUFFIX}}
```
Since `COMIN_OBS` is set to `DMPDIR` in `config.base` the prepbufr, prepbufr_profl, and nsstbufr generated by the parallel are not used.   

This is _okay_ if the developer wants to use the GDA versions of these files.   It is **not okay** if the developer wants to use these files from the parallel prep step.

**Comment by WalterKolczynski-NOAA** [comment]
This will be addressed as part of #761
