### ISSUE TITLE
GDAS diag jobs failing due to insufficient wallclock

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#1215]
**Expected behavior**
GDAS diag jobs (analdiag and ediag) should complete before hitting the wallclock limit.

**Current behavior**
GDAS diag jobs (analdiag and ediag) are killed after hitting the wallclock limit, even at low resolution.

**Machines affected**
Orion, possibly others

**To Reproduce**
1. Setup a cycled experiment
2. Wait for diag jobs to fail

**Context**
Uncovered during refactoring of j-jobs.

**Detailed Description**
Unsure why this seems to be a problem now even at low resolutions. Maybe only on Orion or in certain situations?

**Additional Information**

**Possible Implementation**
Wallclock will be increased in a package of PRs for the j-job refactoring to eliminate the immediate issue. Longer-term, a more thorough evaluation of resources is needed.

**Comment by AndrewEichmann-NOAA** [comment]
@WalterKolczynski-NOAA If this is exclusive to Orion, there have been intermittent system problems recently, apparently with the filesystem, that slow everything (such as builds) down
