### ISSUE TITLE
Development workflow lacks FBWIND bulletin job

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#1221]
**Description**
The development (rocoto) workflow lacks an equivalent of the operational FBWIND bulletin job, so the `JGFS_ATMOS_FBWIND` j-job and child scripts never get exercised.

**Requirements**
A new fbwind job that creates the same bulletin files as operational.

**Acceptance Criteria (Definition of Done)**
A new FBWIND job that runs when AWIPS is turned on.

**Dependencies**
Existing AWIPS needs to be fixed for development first.

**Comment by GwenChen-NOAA** [comment]
@WalterKolczynski-NOAA, any timeline when the `JGFS_ATMOS_FBWIND` j-job will be added into the development (rocoto) workflow? Thanks!
