### ISSUE TITLE
Development workflow lacks many gempak jobs

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#1222]
**Description**
The development (rocoto) workflow lacks several gempak jobs, so that the following j-jobs and their children are not exercised:
`JGDAS_ATMOS_GEMPAK_META`
`JGFS_ATMOS_GEMPAK_META`
`JGFS_ATMOS_GEMPAK_NCDC_UPAPGIF`
`JGFS_ATMOS_GEMPAK_PGRB2_SPEC`

**Requirements**
New jobs for gempak tasks that run when `DO_GEMPAK` is `YES`.

**Acceptance Criteria (Definition of Done)**
New jobs that replicate what is done in operations.

**Dependencies**
#1219 Adding GDAS gempak job

**Comment by GwenChen-NOAA** [comment]
The `JGFS_ATMOS_PGRB2_SPEC_NPOESS` gempak job is also lacking and need to be added. This job uses gfs special files to generate goessimpgrb2 and npoess files. The `JGFS_ATMOS_PGRB2_SPEC_NPOESS` and `JGFS_ATMOS_GEMPAK_PGRB2_SPEC` jobs are pending for removal and thus have lower priority than the `JGFS_ATMOS_GEMPAK_META` and `JGFS_ATMOS_GEMPAK_NCDC_UPAPGIF` jobs. These gempak jobs use the rdbfmsua and webtitle utilities, which are currently missing under global-workflow/exec after running build_all.sh and link_workflow.sh.

**Comment by WalterKolczynski-NOAA** [comment]
Resolved by #2127
