### ISSUE TITLE
ecflow commit for GFS.v16 implementation

### ISSUE THREAD

**Issue by lgannoaa** [NOAA-EMC/global-workflow#123]
This action is for ecflow commit with GFS v16 implementation. The GFS v15 style of ecflow workflow design is changed by NCO. A new coupled ecflow workflow design will replace it going forward. EMC management requested ecflow be in version control.

**Comment by lgannoaa** [comment]
NCO requested ecflow workflow structure to be changed. I put together a new design and was approved from NCO.
NCO also requested a change on HOMEgfs (the implementation package) in j-job and ex-script to follow the naming used in ecflow . Code manager were contacted to make such change. I tested the modified HOMEgfs (as of 9/26/2020) with ecflow. There are still known bug and changes. A first commit was made on 9/30 with the following condition:

There are known condition and upcoming changes from the individual package developer after the ecflow test on 9/26:
- forecast job resource may need to be changed.
- wave package resource is not finalized.
- wave job jgfs_wave_prdgen_bulls need fix a bug with silent fail.
- Some module not installed in production.
- obsproc packages not installed in production.
- post implementation tag is not finalized.
- wafs implementation tag is not finalized.

This merge included an update from high watermark testing result from the gfs team for the following jobs:
jgfs_atmos_analysis.ecf
jgfs_forecast.ecf
jgdas_atmos_analysis.ecf
jgdas_enkf_update.ecf
jgdas_enkf_ecen.ecf
These five high watermark testing result can not be tested by non-devonprod ecflow on dev queue.

**Comment by KateFriedman-NOAA** [comment]
@lgannoaa Is the work in this issue completed? If so, please document completion of task in here and close issue. Thanks!

**Comment by lgannoaa** [comment]
Task was done.
