### ISSUE TITLE
GDASApp commit does not build anymore

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/global-workflow#1243]
## Description
What the title says ... I'm not sure why and I don't think I want to investigate! A wild guess is the eckit/fckit/atlas libs that we get pre-built from the stack that have probably changed. 

## Solution(s)
Pinging @RussTreadon-NOAA , @CoryMartin-NOAA and @aerorahul. 
I don't like the idea of pointing to a specific commit when we're in the midst of mostly constant development.
The simple fix is to point to the `gdas.cd` stable branch until we've converged to a system that doesn't change wildly on a daily basis.
We've discussed this in the past, but I forgot what the consensus was. Thoughts?

**Comment by WalterKolczynski-NOAA** [comment]
Being volatile is all the more reason to point to a specific version. Having a floating version breaks all kinds of good code management practices because a g-w commit would no longer be a stationary thing.

Issue seems to be a missing gdasapp module.

**Comment by CoryMartin-NOAA** [comment]
@guillaumevernieres I tend to agree with @WalterKolczynski-NOAA , we want stable versions that we know build for the 'average joes', what PR to g-w updated the hash of GDASApp? It should be pointing to a specific hash.

**Comment by guillaumevernieres** [comment]
Boooo to @CoryMartin-NOAA  :-1: 
:)

**Comment by WalterKolczynski-NOAA** [comment]
Looks like a module issue:
```
Building GDASApp on orion
Lmod has detected the following error: The following module(s) are unknown: "gdasapp/1.0.0" "miniconda3/4.6.14" "hpc/1.2.0"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore-cache load "gdasapp/1.0.0" "miniconda3/4.6.14" "hpc/1.2.0"
```

**Comment by aerorahul** [comment]
I thought this was working without which the Aerosol DA jobs would not work.
Feel free to close if this works @CoryMartin-NOAA

**Comment by CoryMartin-NOAA** [comment]
Yeah this should build, and we can confirm as part of my imminent bugfix PR.

**Comment by WalterKolczynski-NOAA** [comment]
UFSDA builds fine for me now. Okay to close this?

**Comment by WalterKolczynski-NOAA** [comment]
Closing. Please reopen if this remains an issue.
