### ISSUE TITLE
[NCO Bug] Use $COMIN for input data in GFS and GDAS atmos_nceppost.sh scripts

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#1247]
Bugzilla [#1266](http://www2.spa.ncep.noaa.gov/bugzilla/show_bug.cgi?id=1266)

Details from NCO in bugzilla:
```
In the current GFS v16.1.? scripts/exgdas_atmos_nceppost.sh and exgfs_atmos_nceppost.sh scripts, it copies the gfs master 
input data from $COMOUT, that is not compliant with the implementation standards, since the COMOUT is defined and 
used for output data.

Please look into this and improve this at the coming upgrade to use the $COMIN for input data and the $COMOUT for output 
data.

scripts/exgdas_atmos_nceppost.sh - 
300       cp $COMOUT/${MASTERFHR} $PGBOUT

scripts/exgfs_atmos_nceppost.sh - 
346       cp -p $COMOUT/${MASTERFL} $PGBOUT
```

**Comment by HuiyaChuang-NOAA** [comment]
@WenMeng-NOAA @KateFriedman-NOAA @WalterKolczynski-NOAA @aerorahul 
Is this part of post processing scripts which EIB is taking over?

**Comment by WenMeng-NOAA** [comment]
Since the exgdas_atmos_nceppost.sh and exgfs_atmos_nceppost.sh were adapted in the global-workflow repos., I would think the fixes regarding this bugzilla ticket will be implemented by global-workflow managers. @WalterKolczynski-NOAA may chime in.

**Comment by aerorahul** [comment]
@WenMeng-NOAA @HuiyaChuang-NOAA 
As discussed, we will be refactoring post-processing and product generation jobs.
This ticket will likely become irrelevant.

However, I want to ensure that it is understood that even though scripts live in the global-workflow (as do other components) to conform to project and NCO standards and conventions, the SME's must be able to validate the inputs and outputs of these jobs.

**Comment by WenMeng-NOAA** [comment]
Copying master file from $COMOUT is for generating pgrb2/pgrb2b files after master file is created from inline post due to the gfs forecast job and post job using different working directories. I would expect this can be updated during your refactoring post process scripts, or you might get an exemption from NCO? @aerorahul @WalterKolczynski-NOAA

**Comment by aerorahul** [comment]
@WenMeng-NOAA 
Yes, we have a plan for it during the refactoring that is in line with the NCO EE2 standards.  We will include you to seek your feedback before we start the refactoring work, and your review when the work is being done.

**Comment by WalterKolczynski-NOAA** [comment]
I'm pretty sure this has been mooted by the COM refactor and the move away from using `$COMIN` and `$COMOUT` in most cases.

**Comment by WalterKolczynski-NOAA** [comment]
OBE. These scripts have been refactored. Any issues wrt the com refactor and COMIN/COMOUT will need to be addressed in the new scripting.
