### ISSUE TITLE
[NCO Bug] Add interpreter name to the top of all interpreted scripts

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#1249]
Bugzilla [#1341](http://www2.spa.ncep.noaa.gov/bugzilla/show_bug.cgi?id=1341)

Details from NCO in bugzilla:
```
Please correct for the next upgrade. The following scripts were found for gfs.v16.3 delivery without an interpreter 
at the top of the script:

in scripts/
exgdas_atmos_nceppost.sh
exgfs_atmos_nceppost.sh
exglobal_atmos_tropcy_qc_reloc.sh

in ush/
fix_precip.sh
gfs_nceppost.sh
mkwfsgbl.sh
syndat_getjtbul.sh
syndat_qctropcy.sh
```

**Comment by HenryRWinterbottom** [comment]
@KateFriedman-NOAA I can try to address this bug. However, I am having trouble finding the following files:

- `/ush`
    -  `fix_precip.sh`
    - `gfs_nceppost.sh`
    - `mkwfsgbl.sh`
    
- `/scripts`
    - `exgdas_atmos_nceppost.sh`
    - `exgfs_atmos_nceppost.sh`
    
Further, I see that the scripts `ush/syndat_getjtbul.sh`, `ush/syndat_qctropcy.sh`, and `scripts/exglobal_atmos_tropcy_qc_reloc.sh`  now have the `#! /usr/bin/env bash` interpreter. 

Am I missing something obvious?

**Comment by KateFriedman-NOAA** [comment]
@HenryWinterbottom-NOAA Oooooooo looks like this has been resolved when the post scripts were redone and when @WalterKolczynski-NOAA added the preamble. We can close this now. Sweet! Thanks for looking at this and pinging me!

I have access to the NCO Bugzilla server so I will note in the associated bugzilla that this is resolved for GFSv17 and confirm with you so you can close this. Stay tuned.

**Comment by HenryRWinterbottom** [comment]
@KateFriedman-NOAA Great! I am trying to knock down these `bugs` and `nco-bug` issues before we introduce any (too much) more development. So if you see others that I can tackle please feel free to assign them to me.

**Comment by KateFriedman-NOAA** [comment]
Made update comment in NCO Bugzilla [#1341](http://www2.spa.ncep.noaa.gov/bugzilla/show_bug.cgi?id=1341):
```
 Kate Friedman 2023-10-02 16:06:48 UTC

This has been resolved within the developmental version for GFSv17. The noted scripts were either rewritten (with 
interpreter added) or had the missing interpreter added.

The associated global-workflow issue will be closed now.

NCO, please close this. Thanks!
```

Updated [our bugzilla spreadsheet](https://docs.google.com/spreadsheets/d/1JF5GcHjqrdAIRI9nIUdxRz95GvALxHd9IDri-S3fVco/edit#gid=0) (line 31) to note it has been resolved.

Closing now.

**Comment by KateFriedman-NOAA** [comment]
Reply from NCO on Bugzilla:

[Comment # 3](http://www2.spa.ncep.noaa.gov/bugzilla/show_bug.cgi?id=1341#c3) on [bug 1341](http://www2.spa.ncep.noaa.gov/bugzilla/show_bug.cgi?id=1341) from [Steven Earle](mailto:steven.earle@noaa.gov)
```
I'm glad to see issues getting worked >1 week before a code delivery. Good job
on that.
This bugzilla will be officially closed once it's verified by the SPA team and
implemented into production.
For now, the status of "resolved" is appropriate. Thank you
```
