### ISSUE TITLE
Model fails in module_write_netcdf

### ISSUE THREAD

**Issue by lisa-bengtsson** [NOAA-EMC/global-workflow#1256]
When trying to run a version of the model and workflow that I checked out (and ran successfully) before the Holidays on Hera, I now (yesterday) got an error message in running the forecast step, saying:
 
"1219:  file: module_write_netcdf.F90 line:          663 NetCDF: HDF error
  1219: application called MPI_Abort(comm=0x84000002, 1) - process 1219"

I know @Qingfu-Liu also got this error message in one of his recent experiments on Hera which was difficult to explain. 

I wonder if there is some recent netcdf module update on Hera that we need to take into consideration in the workflow scripts? 

My log files are here: /scratch2/BMC/rem/Lisa.Bengtsson/MJO_MC_C384/comrot/landca/logs/2018010100
My expdir is here: /scratch2/BMC/rem/Lisa.Bengtsson/MJO_MC_C384/expdir/
And my workflow directory is here: /scratch2/BMC/rem/Lisa.Bengtsson/MJO_MC_C384/

**Comment by WalterKolczynski-NOAA** [comment]
Hera admins are already aware of this issue. Something changed during the last scheduled maintenance.

**Comment by lisa-bengtsson** [comment]
Thank you Walter for confirming, is there another issue created, or thread somewhere we should follow instead to learn about the progress of the issue?

**Comment by KateFriedman-NOAA** [comment]
@lisa-bengtsson For now you should be able to change to run with serial netcdf to get around this issue.

Change `OUTPUT_FILETYPE_ATM` and `OUTPUT_FILETYPE_SFC` from `"netcdf_parallel"` to `"netcdf"` in your `config.fv3`. We recently moved C384 from the parallel to the serial case in that config (in `develop`), I suggest doing the same. See here for example: https://github.com/NOAA-EMC/global-workflow/blob/develop/parm/config/config.fv3#L172

**Comment by lisa-bengtsson** [comment]
Great, thank you @KateFriedman-NOAA !

**Comment by KateFriedman-NOAA** [comment]
@RaghuReddy-NOAA Any updates by chance? Thanks!

**Comment by lisa-bengtsson** [comment]
@KateFriedman-NOAA I changed netcdf_paralllel to netcdf in config.fv3, and now run into this problem: 
"1312:  file: module_write_netcdf.F90 line:          207 Permission denied" 

Did you run into this issue? 

Line 207 is below the "else" statement:
`if (do_io) then

       if (par) then
          ncerr = nf90_create(trim(filename),&
                  cmode=IOR(IOR(NF90_CLOBBER,NF90_NETCDF4),NF90_CLASSIC_MODEL),&
                  comm=mpi_comm, info = MPI_INFO_NULL, ncid=ncid); NC_ERR_STOP(ncerr)
       else
          ncerr = nf90_create(trim(filename),&
                  cmode=IOR(IOR(NF90_CLOBBER,NF90_NETCDF4),NF90_CLASSIC_MODEL),&
                  ncid=ncid); NC_ERR_STOP(ncerr)
       end if`

Thank you

**Comment by KateFriedman-NOAA** [comment]
That's a new one...can you point me to the log with that error? Thanks!

**Comment by lisa-bengtsson** [comment]
@KateFriedman-NOAA unfortunately there isn't much more information:
/scratch2/BMC/rem/Lisa.Bengtsson/MJO_MC_C384/comrot/landca/logs/2018010100/gfsfcst.log

Thank you!

**Comment by KateFriedman-NOAA** [comment]
@lisa-bengtsson Delete this file and try again:

/scratch2/BMC/rem/Lisa.Bengtsson/MJO_MC_C384/comrot/landca/gfs.20180101/00/atmos/gfs.t00z.sfcf006.nc

We're thinking that may have gotten corrupted in the initial parallel netcdf failure. That's the file it's trying to write to when it gets the "Permission denied" error. Let me know if you hit the same error again.

**Comment by lisa-bengtsson** [comment]
@KateFriedman-NOAA thanks! That did the trick! Much appreciated.

**Comment by KateFriedman-NOAA** [comment]
Excellent, thanks for the update!

**Comment by KateFriedman-NOAA** [comment]
I will leave this issue open for now while the Hera sysadmins are investigating the post-maintenance issue.

**Comment by rreddy2001** [comment]
Based on what I am seeing here: https://stackoverflow.com/questions/59506059/parallel-read-write-of-netcdf-file-using-fortran-and-mpi

It looks netcdf and pnetcdf are different libraries, but it looks like netcdf itself has the capability to do serial as well as parallel IO.

So netcdf-parallel is not the same as pnetcdf, right?

It will be helpful to have a simple MPI program that writes a NetCDF file that demonstrates this problem, not sure if it is easy to create such a program or if it only happens with a combination of things.

Would anyone  have a simple test program that has write a netCDF file so that we can experiment with and without the "parallel" setting mentioned by Lisa above?

Thanks!

**Comment by aerorahul** [comment]
Is this issue still relevant?  There have been several updates to the model dependencies including hdf5/1.14.0, which may resolve this issue.
Should a more specific issue be opened for enabling parallel_netcdf IO capability in the workflow for model output?

**Comment by lisa-bengtsson** [comment]
sounds good to me @aerorahul thanks
