### ISSUE TITLE
Update coupled model output and restart filenames in ROTDIR to conform with the GFS application

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/global-workflow#1277]
**Description**
The coupled model components produces a variety of output with a mixture of prefix and time-stamp formats.
They do not conform with the existing GFS application and needs to be updated.

This issue will be updated with a table of files that need to be renamed as they are discovered.

**Requirements**
The model output should be consistently named and timestamped.

**Acceptance Criteria (Definition of Done)**
All output is cataloged and clearly identified

@AvichalMehra-NOAA @arunchawla-NOAA we would like to work with someone from the coupled modeling group to fix this inconsistency introduced during the development of the coupled capabilities.

**Comment by WalterKolczynski-NOAA** [comment]
It looks like https://github.com/ufs-community/ufs-weather-model/issues/1577 was completed a while ago. We should be able to take care of this the next time we upgrade the model version (which we should probably do soon, it has been a couple months).

**Comment by WalterKolczynski-NOAA** [comment]
Completed at some point.
