### ISSUE TITLE
Add logging to aerosol DA python scripts

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/global-workflow#1282]
**Description**
@aerorahul and I need to add logging capabilities to the aerosol DA ex python scripts

**Requirements**
Use @aerorahul 's new logging methods

**Acceptance Criteria (Definition of Done)**

**Dependencies**
None? Will do after #1106 is merged

**Comment by aerorahul** [comment]
There is always more logging that can be done, but I thought we did add the basic functionality.  No? @CoryMartin-NOAA

**Comment by CoryMartin-NOAA** [comment]
Yeah this should be considered done
