### ISSUE TITLE
Tracker job fails without providing non-zero exit

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#1283]
**Expected behavior**
If the tracker script (`extrkr_gfs.sh`) encounters a fatal error, the job should exit with a non-zero code.

**Current behavior**
If there is a fatal error running during the MPMD portion of the tracker script it prints an error message and tries to call `err_exit`, but that error is not passed up to the calling j-job script.

**Machines affected**
Orion, likely Hera

**To Reproduce**
1. Generate a cold-start workflow
2. Kill the gdasfcst job or remove it from the workflow
3. Force the gdasvrfy job to run without a completed gdasfcst

**Context**
Though the `err_chk` and `err_exit` scripts have been added to RDHPCS machines, they still rely on LSF options to actually work properly. So `err_exit` gets called, but it swallows the error code without killing the job.

**Detailed Description**

**Additional Information**

**Possible Implementation**

**Comment by lgannoaa** [comment]
Looks like the tracker j-job and script have no issues.

The installation of err_chk and err_exit did not work on development platform. err_chk has hardwired file system location. err_exit does not support SLURM.
The installation of err_chk and err_exit is under a personal location
pwd
/apps/contrib/NCEP/libs/hpc-stack/intel-2018.4/prod_util/1.2.2/bin
Orion-login-4[637] /apps/contrib/NCEP/libs/hpc-stack/intel-2018.4/prod_util/1.2.2/bin$ ls -al err_exit err_chk
-rwxr-xr-x 1 gkyle noaa-hpc 1282 Nov 24  2020 err_chk
-rwxr-xr-x 1 gkyle noaa-hpc 2053 Nov 24  2020 err_exit

This issue can be addressed in issue #752

**Comment by WalterKolczynski-NOAA** [comment]
Closing as duplicate of #752
