### ISSUE TITLE
Add CROW to develop branch

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#13]

**Comment by jkuang-exploro** [comment]
Pull request #20 created.

**Comment by KateFriedman-NOAA** [comment]
Taking a deep dive into these changes. Checked out feature/crow-merge on Venus, did a sync merge of develop into feature/crow-merge, adjusted .gitignore a bit, adjusted FIX_DIR linking in link_fv3gfs.sh, and added CROW to Externals.cfg config (removed .gitmodules). Committed all that at 
[ea5f8f6](https://github.com/NOAA-EMC/global-workflow/commit/ea5f8f6b6a2e545dd285aeb51d765e323b77c835).

**Comment by KateFriedman-NOAA** [comment]
Unclear if coupled-crow will come back to develop soon. Closing issue.
