### ISSUE TITLE
EE2 compliance, dbn_alert issues and err_chk

### ISSUE THREAD

**Issue by GuangPingLou-NOAA** [NOAA-EMC/global-workflow#131]
DBNROOT and dbn_alert are not working on EMC parallel runs even though it works fine in operations.  This update removes error messages in the real time EMC parallel runs.

**Comment by KateFriedman-NOAA** [comment]
@GuangPingLou-NOAA May this issue now be closed? Thanks!

**Comment by GuangPingLou-NOAA** [comment]
will update new scripts soon and a PR will be requested.

**Comment by GuangPingLou-NOAA** [comment]
This issue is resolved.
