### ISSUE TITLE
gfs.v16.3.5: gdasfcst task can begin before gdasanal has ended, causing a failure

### ISSUE THREAD

**Issue by BrettHoover-NOAA** [NOAA-EMC/global-workflow#1320]
**Expected behavior**
The gdasfcst task requires the gdasanal task to complete before it can run successfully. 

**Current behavior**
There are several parallels running using the gfs.v16.3.5 branch of global-workflow on Hera that are repeatedly finding the gdasfcst task beginning prior to the completion of gdasanal, which results in crashes and dead gdasfcst tasks. The immediate failure-point is reached when gdasfcst looks for the gdas RESTART/*.nc and atmospheric increment files, can't find them, and then exits. An example from my parallel on Hera:

expdir: /scratch1/NCEPDEV/da/Brett.Hoover/para/v16.3.5_nog18
ROTDIR: /scratch1/NCEPDEV/stmp2/Brett.Hoover/ROTDIRS/v16.3.5_nog18
cycle: 2023011212
from [ROTDIR]/logs/2023011212/gdasfcst.log.0:
```
ls: cannot access /scratch1/NCEPDEV/stmp2/Brett.Hoover/ROTDIRS/v16.3.5_nog18/gdas.20230112/12/atmos//RESTART/20230112.090000.*.nc: No such file or directory
...
ERROR: DOIAU = YES, but missing increment file for fhr 009 at /scratch1/NCEPDEV/stmp2/Brett.Hoover/ROTDIRS/v16.3.5_nog18/gdas.20230112/12/atmos//gdas.t12z.atmi009.nc
0.366 + echo Abort!
Abort!
0.366 + exit 1
0.660 + status=1
0.660 + [[ 1 -ne 0 ]]
0.660 + exit 1
+ status=1
+ exit 1
```

**Machines affected**
So far this behavior has been observed only on RDHPCS Hera.

**To Reproduce**
The live example is provided above, but @ADCollard has also experienced these events in his control run for my experiment. We are using the same global-workflow build, /scratch1/NCEPDEV/da/Andrew.Collard/git/global-workflow_v16.3.5.

The problem is intermittent. I have experienced this so far only on the 2023011212 cycle. Looking at Andrew's log files in: /scratch1/NCEPDEV/stmp2/Andrew.Collard/ROTDIRS/v16.3.5_ctl/logs, I see 4 cycles where this failure appears: 2023010600, 2023011006, 2023012206, and 2023021218.

**Context**
When I look at the dependencies for gdasfcst in the XML file, I see the following:
```
	<dependency>
		<or>
			<not><cycleexistdep cycle_offset="-06:00:00"/></not>
			<taskdep task="gdasgldas"/>
		</or>
	</dependency>
```
I am not totally literate with XML architecture, but it looks like there's no explicit dependency for gdasanal to complete before beginning gdasfcst. 

**Additional Information**
I see a reference to the gdasgldas task as a gdasfcst dependency in the XML file – it may be noteworthy that in all observed cases of the gdasfcst task starting prior to gdasanal finishing, gdasgldas is not scheduled to run. The settings used in these parallels only run gdasgldas on 00 UTC cycles. All of the failures have happened on non-00 UTC cycles, with the exception of Andrew's failure on 2023010600, which was the first 00 UTC cycle from a cold-start on 2023010518 and would have skipped the gdasgldas task because there were not enough prior cycles completed to run gdasgldas. In these circumstances, the gdasgldas task will start, recognize that it should not run gldas (either because there aren't enough prior cycles completed or it isn't currently a 00 UTC cycle), and then finish successfully. I am wondering if this is enough to satisfy gdasfcst's dependencies and start gdasfcst whether gdasanal has successfully completed or not.

**Possible Implementation**
I am proposing that a dependency may be necessary in the XML file for gdasfcst to explicitly wait until the gdasanal task has finished, although I would like confirmation that this is a reasonable solution.

**Comment by KateFriedman-NOAA** [comment]
Taking a look...

**Comment by KateFriedman-NOAA** [comment]
Ok, so the gdasfcst job needs the gdasgldas job to be complete (ignoring the prior cycle existence dependency):
```
        <dependency>
                <or>
                        <not><cycleexistdep cycle_offset="-06:00:00"/></not>
                        <taskdep task="gdasgldas"/>
                </or>
        </dependency>
```

...and the gdasgldas job needs the gdasanal job complete OR the `gdas.tCCz.loginc.txt` file available:

```
        <dependency>
                <and>
                        <or>
                                <datadep><cyclestr>&ROTDIR;/gdas.@Y@m@d/@H/atmos/gdas.t@Hz.loginc.txt</cyclestr></datadep>
                                <taskdep task="gdasanal"/>
                        </or>
                        <cycleexistdep cycle_offset="-06:00:00"/>
                </and>
        </dependency>
```

For the first 16ish cycles the gldas job is spinning up (waiting for sufficient prior cycles worth of sflux files) so it starts and ends very quickly. Once enough past sflux files are in place it will run and take time to do so.

Taking a look at the rocoto log for the 2023011212 cycle and pulling out the sequence of events for gdasanal, gdasgldas, and gdasfcst....I see that the gdasanal failed and was rerunning but the gdasgldas fired off anyway:
```
2023-02-16 19:55:13 +0000 :: hfe11 :: Submitting gdasanal
2023-02-16 19:55:13 +0000 :: hfe11 :: Submission of gdasanal succeeded, jobid=42062782
2023-02-16 20:00:16 +0000 :: hfe11 :: Task gdasanal, jobid=42062782, in state RUNNING (RUNNING)
2023-02-16 20:05:09 +0000 :: hfe11 :: Task gdasanal, jobid=42062782, in state RUNNING (RUNNING)
2023-02-16 20:10:12 +0000 :: hfe11 :: Task gdasanal, jobid=42062782, in state FAILED (FAILED), ran for 675.0 seconds, exit status=512, try=1 (of 2)
2023-02-16 20:10:12 +0000 :: hfe11 :: Submitting gdasanal
2023-02-16 20:10:13 +0000 :: hfe11 :: Submitting gdasgldas
2023-02-16 20:10:13 +0000 :: hfe11 :: Submission of gdasanal succeeded, jobid=42063364
2023-02-16 20:10:13 +0000 :: hfe11 :: Submission of gdasgldas succeeded, jobid=42063366
2023-02-16 20:15:16 +0000 :: hfe11 :: Task gdasanal, jobid=42063364, in state RUNNING (RUNNING)
2023-02-16 20:15:16 +0000 :: hfe11 :: Task gdasgldas, jobid=42063366, in state SUCCEEDED (COMPLETED), ran for 4.0 seconds, exit status=0, try=1 (of 2)
2023-02-16 20:15:16 +0000 :: hfe11 :: Submitting gdasfcst
2023-02-16 20:15:16 +0000 :: hfe11 :: Submission of gdasfcst succeeded, jobid=42063467
2023-02-16 20:20:08 +0000 :: hfe11 :: Task gdasanal, jobid=42063364, in state RUNNING (RUNNING)
2023-02-16 20:20:08 +0000 :: hfe11 :: Task gdasfcst, jobid=42063467, in state FAILED (FAILED), ran for 5.0 seconds, exit status=256, try=1 (of 2)
2023-02-16 20:20:08 +0000 :: hfe11 :: Submitting gdasfcst
2023-02-16 20:20:08 +0000 :: hfe11 :: Submission status of gdasfcst is pending at druby://hfe11:38319
2023-02-16 20:25:06 +0000 :: hfe11 :: Submission status of previously pending gdasfcst is success, jobid=42063699
2023-02-16 20:25:06 +0000 :: hfe11 :: Task gdasanal, jobid=42063364, in state RUNNING (RUNNING)
2023-02-16 20:25:06 +0000 :: hfe11 :: Task gdasfcst, jobid=42063699, in state DEAD (FAILED), ran for 4.0 seconds, exit status=256, try=2 (of 2)
2023-02-16 20:30:10 +0000 :: hfe11 :: Task gdasanal, jobid=42063364, in state RUNNING (RUNNING)
2023-02-16 20:30:10 +0000 :: hfe11 :: Task gdaseupd, jobid=42063468, in state SUCCEEDED (COMPLETED), ran for 623.0 seconds, exit status=0, try=1 (of 2)
2023-02-16 20:51:52 +0000 :: hfe06 :: Task gdasanal, jobid=42063364, in state SUCCEEDED (COMPLETED), ran for 2056.0 seconds, exit status=0, try=2 (of 2)
2023-02-16 20:52:07 +0000 :: hfe06 :: Forcibly submitting gdasfcst
2023-02-16 20:52:07 +0000 :: hfe06 :: Submission status of gdasfcst is pending at druby://hfe06:33376
2023-02-16 16:31:50 -0500 :: hfe06 :: Submission status of previously pending gdasfcst is success, jobid=42064869
2023-02-16 16:31:52 -0500 :: hfe06 :: Task gdasfcst, jobid=42064869, in state SUCCEEDED (COMPLETED), ran for 801.0 seconds, exit status=0, try=1 (of 2)
```

Unfortunately the cycle is old enough that I can no longer see when the `loginc.txt` file for the 2023011212 cycle came into existence but I suspect that it appeared (from the failed gdasanal) and fired off gdasgldas and then gdasfcst but the gdasanal had failed and was rerunning.

Also unfortunately, the `loginc.txt` file is overwritten/rewritten each time the analysis job completes so I can't even see if that's the case unless I look while another case is happening. Just tried looking at Andrew's last instance and was thwarted by that.

Diving into gdasfcst dependencies a bit more...if GLDAS isn't on then the gdasfcst job waits for the gdasanalcalc job to be complete (which needs gdasanal complete). Although gdasfcst doesn't need gdasanalcalc complete. So yeah, given this intermittent situation I agree that changing it so gdasfcst waits for gdasanal AND gdasgldas (if it's on) is likely the solution. We're only talking about rocoto dependencies so this doesn't impact ops/ecflow. The gfsfcst job waits for gfsanal to complete, so a similar dependency for gdasanal seems reasonable.

@BrettHoover-NOAA @ADCollard Please update the gdasfcst dependency section in your xmls in the following way:
```
        <dependency>
                <or>
                        <not><cycleexistdep cycle_offset="-06:00:00"/></not>
                        <and>
                                <taskdep task="gdasanal"/>
                                <taskdep task="gdasgldas"/>
                        </and>
                </or>
        </dependency>

```
Note, tabs are used for indentation. It'll error if you use spaces.

Also, let's harden the gdasgldas dependency given what I suspect may be happening with the `loginc.txt` file. Change the gdasgldas dependency section in the following way:
```
        <dependency>
                <and>
                        <taskdep task="gdasanal"/>
                        <cycleexistdep cycle_offset="-06:00:00"/>
                </and>
        </dependency>
```

Please run with these modifications and let me know if this resolves the intermittent early firing of the gdasfcst job. If so, I will submit a PR into the `dev/gfs.v16` branch to resolve this bug.

I also suspect that this hasn't cropped up earlier for two reasons:

1. runs on WCOSS2 (with very little queue time) generally have successful analysis job (pre-implementation parallels) and are running the full-blown gldas job (past spin-up)
2. garbage fairshare for many users (myself included) on Hera means no race conditions like this in general testing

Anywho, let's get this fixed. Thanks for reporting!

**Comment by BrettHoover-NOAA** [comment]
Thank you @KateFriedman-NOAA, I will make this change and let you know if I run into this issue again (or if I explicitly don't run into it again)

**Comment by KateFriedman-NOAA** [comment]
@BrettHoover-NOAA Checking in to see if this is working for you. If so, I can submit a PR to resolve this. Let me know, thanks!

**Comment by BrettHoover-NOAA** [comment]
@KateFriedman-NOAA I have been running with your suggested settings for about 2 weeks and I have not seen any reoccurrence of the gdasfcst failure problem. I ran into a new perplexing issue today with the gdasefcs tasks but I don't have any reason to believe it has anything to do with this particular gdasfcst issue.

**Comment by KateFriedman-NOAA** [comment]
@BrettHoover-NOAA Okie dokie, thanks for the update! I'll get a PR initiated into `dev/gfs.v16` to adjust the rocoto dependencies (as outlined in comments above).

**Comment by KateFriedman-NOAA** [comment]
Completed by #1358
