### ISSUE TITLE
gdasanal job fails with missing crtm file when testing 2023 date

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#1321]
**Expected behavior**

The gdasanal job should complete successfully and have needed crtm files as its disposal.

**Current behavior**

A fresh high-res C768C384L127 cycled atmos-only test on WCOSS2 started with checksum'd warm-starts from ops 2023021518 fails in the first full cycle gdasanal job with the following error:
```
nid003394.dogwood.wcoss2.ncep.noaa.gov 761:   in setupw, num_bad_ikx ( ikx<1 or ikx>nconvtype ) =        10153
nid002066.dogwood.wcoss2.ncep.noaa.gov 0:            0 setuprad: passive obs          42 ssmis_f18           
nid002066.dogwood.wcoss2.ncep.noaa.gov 0:            0 setuprad: passive obs          59 hirs4_n19           
nid002066.dogwood.wcoss2.ncep.noaa.gov 0:            0 setuprad: passive obs          67 hirs4_metop-b       
nid003278.dogwood.wcoss2.ncep.noaa.gov 566:  SpcCoeff_ReadFile(Binary)(FAILURE) : File ./crtm_coeffs/abi_g18.SpcCoeff.bin not found.
 CRTM_SpcCoeff_Load(FAILURE) : Error reading SpcCoeff file #1, ./crtm_coeffs/abi_g18.SpcCoeff.bin; Process ID: 566
 CRTM_Init(FAILURE) : Error loading SpcCoeff data; Process ID: 566        
 crtm_interface*init_crtm:  ***ERROR*** crtm_init error_status=           3
    TERMINATE PROGRAM EXECUTIONnid003278.dogwood.wcoss2.ncep.noaa.gov 566: MPICH ERROR [Rank 566] [job id 399d5969-f18a-4aa9-a65c-dd52abe7c439] [Fri Feb 17 02:59:08 2023] [nid003278] - Abort(71) (rank 566 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 71) - process 566

aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 71) - process 566
nid003277.dogwood.wcoss2.ncep.noaa.gov 548:  SpcCoeff_ReadFile(Binary)(FAILURE) : File ./crtm_coeffs/abi_g18.SpcCoeff.bin not found.
 CRTM_SpcCoeff_Load(FAILURE) : Error reading SpcCoeff file #1, ./crtm_coeffs/abi_g18.SpcCoeff.bin; Process ID: 548
 CRTM_Init(FAILURE) : Error loading SpcCoeff data; Process ID: 548        
 crtm_interface*init_crtm:  ***ERROR*** crtm_init error_status=           3
    TERMINATE PROGRAM EXECUTIONnid003277.dogwood.wcoss2.ncep.noaa.gov 548: MPICH ERROR [Rank 548] [job id 399d5969-f18a-4aa9-a65c-dd52abe7c439] [Fri Feb 17 02:59:08 2023] [nid003277] - Abort(71) (rank 548 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 71) - process 548
```

Log: /lfs/h2/emc/ptmp/kate.friedman/comrot/deveff2otest/logs/2023021600/gdasanal.log.2

The gfsanal job in the same cycle does not fail. Log: /lfs/h2/emc/ptmp/kate.friedman/comrot/deveff2otest/logs/2023021600/gfsanal.log

Cold-start tests using early 2022 ICs do not fail with this error. Is this error due to the date of ICs being after v16.3.5[6] went into ops? The crtm file appears to be for GOES-18? I also do no see an error related to this crtm file in ops.

The crtm file it croaks on does not exist in either `crtm/2.3.0` (used here) or `crtm/2.4.0`:
```
kate.friedman@dlogin01:/lfs/h2/emc/ptmp/kate.friedman/comrot/deveff2otest> ll /apps/ops/prod/libs/intel/19.1.3.304/crtm/2.3.0/fix/abi_g18.SpcCoeff.bin
ls: cannot access '/apps/ops/prod/libs/intel/19.1.3.304/crtm/2.3.0/fix/abi_g18.SpcCoeff.bin': No such file or directory
kate.friedman@dlogin01:/lfs/h2/emc/ptmp/kate.friedman/comrot/deveff2otest> ll /apps/ops/prod/libs/intel/19.1.3.304/crtm/2.4.0/fix/abi_g18.SpcCoeff.bin                    
ls: cannot access '/apps/ops/prod/libs/intel/19.1.3.304/crtm/2.4.0/fix/abi_g18.SpcCoeff.bin': No such file or directory
```

This crtm file is symlinked into the rundir for both anal jobs in this test (and in other cold-start tests completed for other dates recently) but it's non-existence doesn't appear to cause issues in those other jobs/tests:
```
+ exglobal_atmos_analysis.sh[411]: /bin/ln -sf /apps/ops/prod/libs/intel/19.1.3.304/crtm/2.3.0/fix/abi_g18.SpcCoeff.bin ./crtm_coeffs/abi_g18.SpcCoeff.bin
+ exglobal_atmos_analysis.sh[412]: /bin/ln -sf /apps/ops/prod/libs/intel/19.1.3.304/crtm/2.3.0/fix/abi_g18.TauCoeff.bin ./crtm_coeffs/abi_g18.TauCoeff.bin
```

Thinking I might need recent ops updates to fix files and info files (v16.3.5) I pointed my clone `fix/gsi` folder to the ops `fix/fix_gsi` folder. Same error occurred though (see most recent two gdasanal.log files).

@CoryMartin-NOAA @RussTreadon-NOAA @ADCollard Have you run into a similar error with the analysis for recent dates? Thanks for any help!

**Machines affected**

Only tested on WCOSS2 but likely happens on all machines.

**To Reproduce**

Set up a warm-start test on WCOSS2 with the current `develop` branch. Run checksum on warm-starts for use with updated forecast model.

**Comment by RussTreadon-NOAA** [comment]
@KateFriedman-NOAA , GFS v16.3.5 included a one line change to `scripts/exglobal_atmos_analysis.sh` which removed GOES-18 ABI from the list of observations to process.   Done at NOAA-EMC/GSI hash [8c3609](https://github.com/NOAA-EMC/GSI/commit/8c360974de29d5e3d1f87d46b8fecb14c4972170).

As you found out the crtm coefficients for g18_abi are not in `$CRTM_FIX`.

**Comment by KateFriedman-NOAA** [comment]
> GFS v16.3.5 included a one line change to scripts/exglobal_atmos_analysis.sh which removed GOES-18 ABI from the list of observations to process. Done at NOAA-EMC/GSI hash [8c3609](https://github.com/NOAA-EMC/GSI/commit/8c360974de29d5e3d1f87d46b8fecb14c4972170).

Aha! I forgot that change! Thanks @RussTreadon-NOAA ! Let me make that edit locally and see how the job runs. I'll need to pull that script change into global-workflow.

**Comment by RussTreadon-NOAA** [comment]
@ADCollard , are the crtm/2.4.0 `abi_gr` coefficients below

```
russ.treadon@dlogin04:/apps/ops/prod/libs/intel/19.1.3.304/crtm/2.4.0/fix> ls -l abi_gr*                               
-rw-r--r-- 1 ops.prod prod    872 Aug 22 16:10 abi_gr.SpcCoeff.bin
-rw-r--r-- 1 ops.prod prod 184588 Aug 22 16:10 abi_gr.TauCoeff.bin
```
the `abi_g18` coefficients?

**Comment by KateFriedman-NOAA** [comment]
@RussTreadon-NOAA Confirming that removing that line in `scripts/exglobal_atmos_analysis.sh` does indeed resolve the issue I was encountering. Thanks again for the reminder of that change from v16.3.6. I have opened issue #1322 to pull this update into `develop`.

**Comment by ADCollard** [comment]
> @ADCollard , are the crtm/2.4.0 `abi_gr` coefficients below
> 
> ```
> russ.treadon@dlogin04:/apps/ops/prod/libs/intel/19.1.3.304/crtm/2.4.0/fix> ls -l abi_gr*                               
> -rw-r--r-- 1 ops.prod prod    872 Aug 22 16:10 abi_gr.SpcCoeff.bin
> -rw-r--r-- 1 ops.prod prod 184588 Aug 22 16:10 abi_gr.TauCoeff.bin
> ```
> 
> the `abi_g18` coefficients?

@RussTreadon-NOAA Sorry just saw your question.    GOES-R is actually GOES-16.  The CRTM team seem to have gotten into the habit of using pre-launch names for the coefficient files, so GOES-R for GOES-16 and j2 for NOAA21.  Unfortunately this is used inside the (binary) file and we actually use this in the GSI code (hard-coded).  So for now we need them to regenerate the files.  It's all a mess really.

**Comment by RussTreadon-NOAA** [comment]
Thank you, @ADCollard , for the correction.   I agree.  This is messy.
