### ISSUE TITLE
Update "checkout.sh" in gefs_v12 since a new tag was created in the GSL-prep-chem repository

### ISSUE THREAD

**Issue by lipan-NOAA** [NOAA-EMC/global-workflow#1324]
References:
 issue (https://github.com/NOAA-GSL/GSL-prep-chem/issues/5)
 PR (https://github.com/NOAA-GSL/GSL-prep-chem/pull/6)

**Comment by XianwuXue-NOAA** [comment]
Because NCO will submit gefs.v12.3.5 update with minor gefs upgrade for scripts/exwave_nawips.sh, so the tag of prep_chem should be changed to 12.3.6.

**Comment by WalterKolczynski-NOAA** [comment]
@XianwuXue-NOAA if this is all done now, can you close it?

**Comment by XianwuXue-NOAA** [comment]
It was already merged in the PR: #1379. I just checked and found I forgot to add the fixes #. Sorry for that. So I will close it after this comment.
