### ISSUE TITLE
Provide lower resolution wave model grid & IC set-ups

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#1333]
**Description**
For efficient testing and development, a low resolution wave model set-up is needed within the workflow.   In addition to grids, ICs are needed to be staged (Please let me know if there's already a specific date being used for other testing).  

**Requirements**
Able to run waves within low resolution testing. 

**Acceptance Criteria (Definition of Done)**
Merged in the develop branch and can run low-res fully coupled tests for whatever configurations are currently being tested.  

**Dependencies**
The biggest blocking issue here is my time.

**Comment by JessicaMeixner-NOAA** [comment]
FYI @aerorahul  -- If there is a specific date for ICs please let me know.

**Comment by aerorahul** [comment]
Is https://github.com/NOAA-EMC/global-workflow/issues/259 related to this issue?

**Comment by JessicaMeixner-NOAA** [comment]
Good catch @aerorahul --  I would consider these more/less the same.
