### ISSUE TITLE
[Bug] Sanitize low res IC's (C48/500)

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/global-workflow#1335]
It is not a requirement for this PR (yet), but a check of running the cycled atmosphere with the coupled model fails out of the blocks.
I set up an experiment to cycle the atmosphere, but w. a coupled model using the ICs from @guillaumevernieres 
The experiment fails in the first half cycle forecast with a `checksum` error like the one below:
```
0: FATAL from PE     0: The checksum in the file:INPUT/fv_core.res.tile1.nc and variable:u does not match the checksum calculated from the data. file:89A9B07933A58B2A from data:73DB4D4D82EB
 0:
```

The experiment directory is at:
```
/scratch1/NCEPDEV/stmp2/Rahul.Mahajan/EXPDIR/hr1soca
```

The experiment was setup as follows:
```bash
$> ./workflow/setup_expt.py cycled --expdir /scratch1/NCEPDEV/stmp2/Rahul.Mahajan/EXPDIR --comrot /scratch1/NCEPDEV/stmp2/Rahul.Mahajan/ROTDIR --idate 2021032312 --edate 2021032400 --resdet 48 --nens 0 --gfs_cyc 0 --pslot hr1soca --app S2S --icsdir /scratch1/NCEPDEV/stmp2/Rahul.Mahajan/ICSDIR/C48O500 --start warm
```

Edit `config.base` to disable IAU (`DOIAU=NO`).

_Originally posted by @aerorahul in https://github.com/NOAA-EMC/global-workflow/issues/1197#issuecomment-1446446019_
            

See here: 
https://global-workflow.readthedocs.io/en/latest/init.html#gfsv17-checksum

**Comment by jiandewang** [comment]
@guillaumevernieres I think the IC you are using is generated from other platform than the one you are running cycle, there is a flag to turn that checksum off in fv3 (though I don't which one it is)

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres I think the IC you are using is generated from other platform than the one you are running cycle, there is a flag to turn that checksum off in fv3 (though I don't which one it is)

@jiandewang , we do disable that checksum on the DA side. 
These IC's were generated on Hera, so that's not the issue, maybe the 32bit build? I don't know what the default is in develop.

**Comment by WalterKolczynski-NOAA** [comment]
Right now it is 64-bit. The PR changes it to 32-bit.

Stripping the checksums from the ICs is a very simple process we already have instructions for: https://global-workflow.readthedocs.io/en/latest/init.html#gfsv17-checksum

**Comment by aerorahul** [comment]
I stripped the checksums using the instructions in the global-workflow RTD and restarted the forecast task.
The forecast has since progressed beyond the failure.

**Comment by aerorahul** [comment]
I think this is done.   The ICs have been copied to a central place.  @guillaumevernieres when you are ready to replace the ones you gave us with updated ones, please let us know.
For now, the ones you gave us have been sanitized and copied over.
Documentation will be updated to point to those.

Closing.
