### ISSUE TITLE
Fix bugs to add the creating analysis files for early-cycle EnKF functions back

### ISSUE THREAD

**Issue by XianwuXue-NOAA** [NOAA-EMC/global-workflow#1340]
**Expected behavior**

When DO_CALC_INCREMENT_ENKF_GFS=YES, then early-cycle EnKF should produce analysis files 

**Current behavior**

No analysis files were produced due to the CDUMP has been changed to "enkfgfs" instead of "gfs"

**Machines affected**

All machines, however, I only tested it on WCOSS2

**To Reproduce**

Run early-cycled enkf

**Context**

Change the corresponding scripts

**Detailed Description**

Change the corresponding scripts below from "gfs" to "enkfgfs"

```
scripts/exgdas_enkf_update.sh
scripts/exgdas_enkf_ecen.sh
```

**Comment by WalterKolczynski-NOAA** [comment]
I have this fixed in the work for #761

**Comment by XianwuXue-NOAA** [comment]
Thanks @WalterKolczynski-NOAA I already merged in the develop branch in PR #1343.

**Comment by XianwuXue-NOAA** [comment]
@WalterKolczynski-NOAA Sorry for the fusion. I will close this issue after this comment.

**Comment by WalterKolczynski-NOAA** [comment]
Then it is some other thing that is wrong because my early cycle fails with develop but runs fine in my branch.

**Comment by XianwuXue-NOAA** [comment]
I successfully tested the develop branch with some changes for my preference last night. Please send me the log file, I will check it.
