### ISSUE TITLE
Update EMC_verif-global to verif_global_v2.10.3

### ISSUE THREAD

**Issue by malloryprow** [NOAA-EMC/global-workflow#1342]
**Description**
Update the EMC_verif-global tag in the necessary branches to verif_global_v2.10.3. This new tag updates paths for the new FIX files (https://github.com/NOAA-EMC/EMC_verif-global/issues/108) for EMC_verif-global running standalone and in the global workflow, and updates from @DavidHuber-NOAA for Jet support.

**Requirements**
EMC_verif-global when running in the workflow uses the correct fix files. 

**Acceptance Criteria (Definition of Done)**
EMC_verif-global tag updated in sorc/checkout.sh. @DavidHuber-NOAA ran a cycled test on S4 already and output was god. https://github.com/NOAA-EMC/EMC_verif-global/pull/109#issuecomment-1448109994

**Dependencies**
N/A

**Comment by malloryprow** [comment]
@KateFriedman-NOAA @WalterKolczynski-NOAA I could do this, I think, but I'm not sure what branches it all needs to be done in.

I see from https://github.com/NOAA-EMC/global-workflow/issues/971 the branches were dev_v16.2.x, and release/gfs.v16.3.0, but I don't see those anymore.

**Comment by KateFriedman-NOAA** [comment]
@malloryprow The GFSv16 branch was renamed to `dev/gfs.v16` (from `dev_v16.2.x` ahead of `release/gfs.v16.3.0` being merged into it). I initially thought we can update the v16 package version but this new `verif_global_v2.10.2` has updates for the GFSv17 developmental fix set so it won't work for v16 (frozen fix set with older structure). We'll keep the `dev/gfs.v16` branch using `verif_global_v2.10.0` and maybe make a separate version from that tag if needed before v17 goes in.

Will let @WalterKolczynski-NOAA comment on the feasibility of updating the v17/develop version. The fact that @DavidHuber-NOAA was able to run it on S4 with `develop` is encouraging but Walter knows more about the hang-ups we've had with this in `develop`. Happy to help test though depending on Walter's thoughts.

**Comment by malloryprow** [comment]
@KateFriedman-NOAA Ah, got it, thank you!

**Comment by WalterKolczynski-NOAA** [comment]
Will open a new issue for the current version of verify (or maybe EVS) after the module situation gets fixed.
