### ISSUE TITLE
Define testing requirements for CI/CD

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/global-workflow#1346]
**Description**
This issue will define the testing requirements for an initial CI/CD implementation.

Initial discussion is captured [here](https://docs.google.com/presentation/d/1OtsAQbAaFxqUuZMXPGo__SKC_R9yIdMtyNAGqN88e9U/edit)

**Acceptance Criteria (Definition of Done)**
A plan for CI/CD tests and framework.

**Comment by WalterKolczynski-NOAA** [comment]
Done
