### ISSUE TITLE
Remove prod_util hack from UFSDA module load script

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/global-workflow#1350]
**Description**
Discussed in #1349 and offline with @aerorahul , there really is no need for prod_util things here besides a `UTILROOT` in config.base. This should be cleaned up/fixed properly.

**Requirements**
Make `UTILROOT` not cause failures in `set -e` mode.
Do not do an ugly hack in ush/load_ufsda_modules.sh for prod_util

**Acceptance Criteria (Definition of Done)**
Tested and cleaned up

**Dependencies**
None known

**Comment by aerorahul** [comment]
Does spack-stack 1.6.0 resolve this issue where `UTILROOT` is defined differently/correctly?

**Comment by WalterKolczynski-NOAA** [comment]
This was handled long ago in #2245
