### ISSUE TITLE
Missing gdas.t??z.ocnf009.nc when cycling S2S at C384O025 with no iau

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/global-workflow#1352]
**Expected behavior**
At the end of a cycle, we should have 3 ocean backgrounds, for ex: `gdas.t00z.ocnf003.nc`, `gdas.t00z.ocnf006.nc` and `gdas.t00z.ocnf009.nc`. 

**Current behavior**
`gdas.t00z.ocnf009.nc` is missing

**Comment by aerorahul** [comment]
I think there is something peculiar with the model + `diag_table` that I can't quite put a finger on.
Tagging some experts who might be able to help
@jiandewang @junwang-noaa
