### ISSUE TITLE
Out Of Memory error running gdasfcst from develop on Hera

### ISSUE THREAD

**Issue by AndrewEichmann-NOAA** [NOAA-EMC/global-workflow#1361]
**Expected behavior**

gdasfcst (running just ATM) completes 1st 1/2-cycle as usual

**Current behavior**

```
288:  twmax=   272.1335       266.5500     twtop=   270.2471
288:  PROCESS SURFCE done
288:  PROCESS CLDRAD done
292: slurmstepd: error: Detected 1 oom-kill event(s) in StepId=42461529.0. Some of your processes may have been killed by the cgroup out-of-memory handler.
srun: error: h19c54: task 300: Out Of Memory
srun: launch/slurm: _step_signal: Terminating StepId=42461529.0
  0: slurmstepd: error: *** STEP 42461529.0 ON h3c03 CANCELLED AT 2023-03-01T22:07:26 ***
```

**Machines affected**
Hera

**To Reproduce**

logs/comrot: /scratch1/NCEPDEV/stmp4/Andrew.Eichmann/babka/logs/2021063006
expdir: /scratch1/NCEPDEV/da/Andrew.Eichmann/para_gfs/babka

**Context**

Experiment is to run global-workflow cycling, ATM only,  a couple of cycles to produce warm starts for coupled run. ICs were freshly pulled/converted. Model is fresh build of develop, hash as of Tue Feb 28 16:27:46 2023 -0500

**Additional Information**

I tried changing the node count from 17 to 18 then 19 - I'm guessing those don't get taken advantage of automatically

**Comment by AndrewEichmann-NOAA** [comment]
FYI @guillaumevernieres

**Comment by KateFriedman-NOAA** [comment]
@AndrewEichmann-NOAA This looks like the same OOM kill (same resolution) that Jessica got while testing the HR1 PR but without a change that is now included in that PR: https://github.com/NOAA-EMC/global-workflow/pull/1197/files#diff-1e60b31f6f03a79b1b8b50c49261378d82d5dd27a2d8fd8d3c247bd467442a05

Try commenting out those same `WRTTASK` lines in your `config.fv3` and rerunning the gdasfcst job. Your rerun should use more tasks without the `WRTTASK` value relaxation happening in `config.fv3`. Let me know how it goes.

**Comment by AndrewEichmann-NOAA** [comment]
@KateFriedman-NOAA This seems to have worked. Thank you!
