### ISSUE TITLE
Archiving of WCDA output and restarts

### ISSUE THREAD

**Issue by AndrewEichmann-NOAA** [NOAA-EMC/global-workflow#1383]
**Description**

Currently, @guillaumevernieres's dev/ocnda branch of global-workflow, used for WCDA, does not archive ocean, ice, or mediator output or restarts. The free-forecast (gfs) already has a section for this, but the da (gdas) run does not. This will become an issue with longer runs on machines with HPSS access, since the archive task sweeps the COMROT directories after a couple of model days. Fixing this will require a PR to global-workflow.

**Requirements**

Save the output and restarts of the ocean, ice, and mediator components

**Acceptance Criteria (Definition of Done)**

Output and restarts of  the ocean, ice, and mediator components can be pulled from HPSS

**Comment by AndrewEichmann-NOAA** [comment]
Parallel issue with https://github.com/NOAA-EMC/GDASApp/issues/385

**Comment by KateFriedman-NOAA** [comment]
@AndrewEichmann-NOAA Is this complete?

**Comment by AndrewEichmann-NOAA** [comment]
@KateFriedman-NOAA yes
