### ISSUE TITLE
Wrong averaging intervals in atm grib2 output when FHOUT_GFS=3

### ISSUE THREAD

**Issue by LydiaStefanova-NOAA** [NOAA-EMC/global-workflow#1390]
**Expected behavior**

changing FHOUT_GFS=6 to FHOUT_GFS=3 in global workflow,  tag: prototype/hr1 would produce 3-hourly atmospheric output with averages/min/max calculated over the preceding 3-hour interval

**Current behavior**

changing FHOUT_GFS=6 to FHOUT_GFS=3 in global workflow,  tag: prototype/hr1  does produce 3-hourly atmospheric output, but the averages/min/max interval is **incorrect for every other output time**, i.e. it is correct at forecast hours 3, 9, 15, 21, etc but incorrect at forecast hours 6, 12, 18, 24, etc (there, the averages/min/max are calculated over the preceding 6-hour interval).

**Machines affected**

This is seen when running on Cactus

**To Reproduce**

run the global workflow with tag: prototype/hr1 on Cactus, with a single change: FHOUT_GFS in config.defaults.s2sw
is changed from 6 to 3

**Context**

The ability to produce correct 3-hourly output is needed for the HR1 experiment, to allow for appropriate verification of near-surface fields

**Additional Information**
Config files: 
/lfs/h2/emc/couple/noscrub/Jiande.Wang/UFS-HR1/work/EXPDIR/HR12019122100

Log files:
/lfs/h2/emc/couple/noscrub/Jiande.Wang/UFS-HR1/work/COMROOT/HR12019122100/logs/2019122100/

master and other grib2 files: 
/lfs/h2/emc/couple/noscrub/Jiande.Wang/UFS-HR1/work/COMROOT/HR12019122100/gfs.20191221/00/atmos

global-workflow code and script :
/lfs/h2/emc/couple/noscrub/Jiande.Wang/UFS-HR1/global-workflow

**Comment by aerorahul** [comment]
@LydiaStefanova-NOAA 

Thank you for opening an issue.

I am trying to understand if this is a post-processing issue or a model processing issue or a workflow configuration issue.

As you say, the model produces 3-hourly output in the following atmosphere files:`atmfHHH.nc`, `sfcfHHH.nc`, `.master.grb2fHHH` and `sfluxgrbfHHH.grib2` where `HHH` is `003`, `006`, `009`, ...

Can you explain which of these files contain "averages" and of which fields?

**Comment by yangfanglin** [comment]
The behavior is as expected.  FHOUT_GFS is different from the "bucket" which determines the averaging length.

The operational GFS has hourly output. but the bucket is still 6 hours

**Comment by junwang-noaa** [comment]
I agree with Fanglin. The fhzero is the namelist variable that controls the
bucket (statistical process interval, usually 6), fhout controls the output
frequency. If you only change fhout=3, the history files will be output
every 3 hours, but the average/max/min are still 6 hourly interval
averaged/min/max. You need to change fhzero to 3 to get 3 hourly interval
averaged/min/max fields. Thanks.

**Comment by yangfanglin** [comment]
But for GFS and GEFS, PLEASE keep fhzero=6; otherwise, it will break a lot of downstream jobs.  It is not difficult to figure out how to obtain the right average values at each forecast hour and max/min values  in a given time period from model output with fixed fhzero=6 but different output frequencies.

**Comment by LydiaStefanova-NOAA** [comment]
Thanks a lot to everyone for this information, and apologies for having the wrong expectations. @yangfanglin , since you said we need 3 hourly output for HR1: do you want us to leave everything as is for the HR1 (6-hourly bucket, but with output every 3 hours)?

**Comment by yangfanglin** [comment]
yes

**Comment by LydiaStefanova-NOAA** [comment]
thanks. leaving everything as is, since this is the expected behavior.
