### ISSUE TITLE
Document modules used in ATM cycled jobs

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#1396]
**Description**

First pass at documenting the modules loaded in ATM-only cycled mode jobs in advance of work to update the system to only load modules used by jobs during the job instead of the full `module_base` modulefile (overkill loading).

Spreadsheet: https://docs.google.com/spreadsheets/d/1ZJRwKxk5ogay3pidZd18Pi2EUzeSKBM-xWxTUWvP2U0/edit#gid=0

- [x] document WCOSS2 modules
- [ ] document Hera modules
- [ ] document Orion modules

**Comment by KateFriedman-NOAA** [comment]
See spreadsheet for list of modules loaded in GFSv16 operations (ATM w/ waves + downstream jobs): https://docs.google.com/spreadsheets/d/1ZJRwKxk5ogay3pidZd18Pi2EUzeSKBM-xWxTUWvP2U0/edit#gid=0

**Comment by aerorahul** [comment]
I think this is done.
