### ISSUE TITLE
S2SWA produces dependencies on undefined tasks

### ISSUE THREAD

**Issue by cristianastan2** [NOAA-EMC/global-workflow#1398]
**Current behavior**
When I set up an experiment with 

./setup_expt.py forecast-only --app S2SWA 

I get the following error message:

$ rocotorun -d p8_climate_run.db -w p8_climate_run.xml
03/14/23 18:30:16 UTC :: p8_climate_run.xml :: Error: Extra element dependency in interleave.
03/14/23 18:30:16 UTC :: p8_climate_run.xml :: Error: Element task failed to validate content at p8_climate_run.xml:74.
03/14/23 18:30:16 UTC :: p8_climate_run.xml :: Error: Extra element task in interleave.
03/14/23 18:30:16 UTC :: p8_climate_run.xml :: Error: Element workflow failed to validate content at p8_climate_run.xml:18.
03/14/23 18:30:16 UTC :: p8_climate_run.xml :: Error: Element workflow failed to validate content at p8_climate_run.xml:18.

When I set up the experiment with 
./setup_expt.py forecast-only --app S2SW
and then modify the APP settings in 'config.base' to S2SWA I don't get any error and the chem/ output is being generated in the comrot/

**Machines affected**
Hera

**Comment by JessicaMeixner-NOAA** [comment]
What version of the workflow are you using?

**Comment by cristianastan2** [comment]
https://github.com/shansun6/global-workflow.git




________________________________

**Comment by aerorahul** [comment]
@cristianastan2 
It appears your branch is extremely stale
![Screenshot 2023-03-15 at 11 35 01 AM](https://user-images.githubusercontent.com/11394126/225362988-02146ba6-e153-4f2b-b024-c6dea36dadd2.png)

**Comment by cristianastan2** [comment]
Good to hear that the issue has been resolved in the updeted versions of the workflow.




________________________________

**Comment by aerorahul** [comment]
@cristianastan2 
Please update your branch and let us know if the problem persists.
