### ISSUE TITLE
Fix Exception Handling Issue Found in build_all.sh

### ISSUE THREAD

**Issue by lgannoaa** [NOAA-EMC/global-workflow#14]
Arun assigned Lin to fix the exception handling issues found in build_all.sh.

**Comment by lgannoaa** [comment]
Implement exception handling in build_all.sh. Tested in Dell, Hera, and Cray. This improved solution will identify building error and handle exception by fail in proper message.

**Comment by KateFriedman-NOAA** [comment]
Pull request initiated: https://github.com/NOAA-EMC/global-workflow/pull/15

**Comment by KateFriedman-NOAA** [comment]
Cancelled prior pull request after request for additional changes to script. Retested after modifications were made and the changes looked good.

@lgannoaa Are you ready to do the pull request again? Any further changes to make or tests to do? @EricRogers-NOAA @arunchawla-NOAA @Hang-Lei-NOAA any further feedback on the changes Lin made to build_all.sh?

**Comment by arunchawla-NOAA** [comment]
I liked what was done. If Lin makes the PR it looks good to me.
---------------------------------------------------------------
Arun Chawla
Chief
Engineering & Implementation Branch
Room 2083
National Center for Weather & Climate Prediction
5830 University Research Court
College Park, MD 20740
Phone : 301-683-3740
Mobile : 240-564-5675
     Fax : 301-683-3703
------------------------------------------------------------

**Comment by Hang-Lei-NOAA** [comment]
It looks good!
Okay to be pushed into develop.

Hang

**Comment by EricRogers-NOAA** [comment]
I agree with Arun and Hang.
Eric

**Comment by lgannoaa** [comment]
PR is done. Thanks everyone :-)

**Comment by KateFriedman-NOAA** [comment]
Thanks Lin! I'll take a look in the morning and process it with Hang.

Kate Friedman (formerly Howard)
NOAA/NWS/NCEP/EMC Engineering and Implementation Branch

**Comment by KateFriedman-NOAA** [comment]
Submitting PR.

**Comment by KateFriedman-NOAA** [comment]
PR #18 submitted and committed to develop branch. Closing ticket now. Thanks @lgannoaa !
