### ISSUE TITLE
Experiment setup errors with the latest version of the global-workflow

### ISSUE THREAD

**Issue by jiaruidong2017** [NOAA-EMC/global-workflow#1402]
When I updated to the latest version of the global workflow, the setup of experiment failed with the following error messages:

```
+ /scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GlobalWorkflow/global-workflow.ref8/workflow/setup_expt.py cycled --app ATMA --pslot aodid8 --configdir /scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GlobalWorkflow/global-workflow.ref8/parm/config --idate 2019061400 --edate 2019061500 --resdet 96 --resens 96 --comrot /scratch1/NCEPDEV/global/Jiarui.Dong/ptmp --expdir /scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GlobalWorkflow/para_gfs --cdump gdas --gfs_cyc 0 --nens 0
Traceback (most recent call last):
  File "/scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GlobalWorkflow/global-workflow.ref8/workflow/setup_expt.py", line 12, in <module>
    from hosts import Host
  File "/scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GlobalWorkflow/global-workflow.ref8/workflow/hosts.py", line 6, in <module>
    from pygw.yaml_file import YAMLFile
  File "/scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GlobalWorkflow/global-workflow.ref8/workflow/pygw/yaml_file.py", line 8, in <module>
    from .jinja import Jinja
  File "/scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GlobalWorkflow/global-workflow.ref8/workflow/pygw/jinja.py", line 13, in <module>
    @jinja2.pass_eval_context
AttributeError: module 'jinja2' has no attribute 'pass_eval_context'
```
Any suggestions? Thanks.

**Comment by HenryRWinterbottom** [comment]
@jiaruidong2017 Let me dig into this. If I don't get back to you this evening I will try to have an answer for you in the morning.

**Comment by jiaruidong2017** [comment]
Thanks @HenryWinterbottom-NOAA for your efforts.

**Comment by HenryRWinterbottom** [comment]
@jiaruidong2017 This appears to be related to an older version of Jinja2 in the global-workflow Python stack.

As a work around, you can try `/scratch1/NCEPDEV/da/Henry.Winterbottom/UFS/ufs_stack/stack/miniconda/bin/python` on RDHPCS Hera. This will be temporary until the stack is patched. I will open an issue. 

In order to implement this hack, do as follows:

```
user@host:$ module use -a /contrib/anaconda/modulefiles; module load anaconda/anaconda3-5.3.1
user@host:$ alias python /scratch1/NCEPDEV/da/Henry.Winterbottom/UFS/ufs_stack/stack/miniconda/bin/python
```

Note that this assumes that one is working is `csh` or `tcsh` shell.

**Comment by jiaruidong2017** [comment]
@HenryWinterbottom-NOAA Thanks again for your efforts. My experiment setup script used `ksh`, and the command `alias` didn't work for my `ksh` script with the errors below: 

```
+ eval
+ alias python /scratch1/NCEPDEV/da/Henry.Winterbottom/UFS/ufs_stack/stack/miniconda/bin/python
python: alias not found
./CORI8_rocoto_cycled_noahmp.sh[5]: alias: /scratch1/NCEPDEV/da/Henry.Winterbottom/UFS/ufs_stack/stack/miniconda/bin/python: invalid alias name
```

**Comment by HenryRWinterbottom** [comment]
@jiaruidong2017 OK thank you for trying. I admittedly only tried the unittests and not the entire GW system.

I will work with the GW team to get the stack patched ASAP. Keep an eye on the updates to `develop` for additional information.

In the meantime, for `ksh` you could try:

`alias python=/scratch1/NCEPDEV/da/Henry.Winterbottom/UFS/ufs_stack/stack/miniconda/bin/python`

Note that the syntax is slightly different for the different shells.

**Comment by jiaruidong2017** [comment]
@HenryWinterbottom-NOAA I just tried your suggested `alias` for `ksh` and it worked. However, the experiment setup still had the same problems. Anyway, I can wait for your updates to the `develop` branch. Many thanks to your great efforts.

**Comment by HenryRWinterbottom** [comment]
@jiaruidong2017 OK, at least that resolves one bug. I am trying to update the Anaconda stack but the unit tests are still failing. I will take a look at this again tomorrow. 

Thank you for trying/debugging.

**Comment by HenryRWinterbottom** [comment]
@jiaruidong2017 Could you try your experiment again? Some updates were made overnight and I am curious is they address your issue(s).

**Comment by jiaruidong2017** [comment]
@HenryWinterbottom-NOAA I just checked the global workflow package, but I didn't find any updates available in the `develop` branch. I would like to make a try. Would you please let me know how to proceed? Thank you.

**Comment by jiaruidong2017** [comment]
@HenryWinterbottom-NOAA I just tried to run my experiment setup, and it seemed working now. What happened? Thanks.

**Comment by HenryRWinterbottom** [comment]
@jiaruidong2017 I believe the patches @WalterKolczynski-NOAA installed likely fixed the problem.

I am closing this. Please feel free to open a new issue if additional problems arise.
