### ISSUE TITLE
Create dedicated Fit2Obs job

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#1405]
**Description**

The fit2obs package currently runs as part of the vrfy job and is submitted from within that job. Move fit2obs out of the vrfy job and into its own job. This work should help resolve issue #1232 and broken functionality on R&Ds machines.

- [x] Create `parm/config/config.fit2obs`
- [x] Create `jobs/rocoto` script (`fit2obs.sh`)
- [x] Create JJOB script (`JGDAS_FIT2OBS`)
- [x] Add `DO_FIT2OBS` switch in `config.base`
- [x] Add fit2obs task to gdas tasks in setup scripts
- [x] Add fit2obs task to `config.resources`
- [x] Add fit2obs task to env files.
- [x] Test new job on WCOSS2
- [x] Test new job on Hera
- [x] Test new job on Orion
- [x] Check if resolution still needed for #311

**Requirements**

Updates to fit2obs repo needed for functionality on WCOSS2. See https://github.com/NOAA-EMC/Fit2Obs/issues/4.

**Acceptance Criteria (Definition of Done)**

Fit2obs package is run and produces correct output from new separate job.

**Dependencies**

- [x] Completion of https://github.com/NOAA-EMC/Fit2Obs/issues/4.
- [x] Install new Fit2Obs `wflow.1.0` tag on supported platforms (WCOSS2s, Hera, Orion, Jet).

**Comment by KateFriedman-NOAA** [comment]
Began C96C48L127 test with new `fit2obs` job on Hera. Using fit2obs repo branch referenced in https://github.com/NOAA-EMC/Fit2Obs/issues/4.

New job in generated xml:
```
<task name="gdasfit2obs" cycledefs="gdas" maxtries="&MAXTRIES;">

        <command>&JOBS_DIR;/fit2obs.sh</command>

        <jobname><cyclestr>&PSLOT;_gdasfit2obs_@H</cyclestr></jobname>
        <account>fv3-cpu</account>
        <queue>batch</queue>
        <partition>hera</partition>
        <walltime>00:20:00</walltime>
        <nodes>3:ppn=1:tpp=1</nodes>
        <native>--export=NONE</native>

        <join><cyclestr>&ROTDIR;/logs/@Y@m@d@H/gdasfit2obs.log</cyclestr></join>

        <envar><name>RUN_ENVIR</name><value>emc</value></envar>
        <envar><name>HOMEgfs</name><value>/scratch1/NCEPDEV/global/Kate.Friedman/git/feature-fit2obs</value></envar>
        <envar><name>EXPDIR</name><value>/scratch1/NCEPDEV/global/Kate.Friedman/expdir/testfit2obs</value></envar>
        <envar><name>NET</name><value>gfs</value></envar>
        <envar><name>CDUMP</name><value>gdas</value></envar>
        <envar><name>RUN</name><value>gdas</value></envar>
        <envar><name>CDATE</name><value><cyclestr>@Y@m@d@H</cyclestr></value></envar>
        <envar><name>PDY</name><value><cyclestr>@Y@m@d</cyclestr></value></envar>
        <envar><name>cyc</name><value><cyclestr>@H</cyclestr></value></envar>
        <envar><name>COMROOT</name><value>/scratch1/NCEPDEV/global/glopara/com</value></envar>
        <envar><name>DATAROOT</name><value>/scratch1/NCEPDEV/stmp2/Kate.Friedman/RUNDIRS/testfit2obs</value></envar>

        <dependency>
                <metataskdep metatask="gdaspost"/>
        </dependency>

</task>
```
Updated `gdasarch` task dependency:
```
        <dependency>
                <and>
                        <taskdep task="gdasvrfy"/>
                        <taskdep task="gdasfit2obs"/>
                </and>
        </dependency>
```
Tested `DO_FIT2OBS` switch in `config.base` (turned it on and off to check job is added or not added to resulting xml).

**Comment by aerorahul** [comment]
Here is a branch with cmake for fit2obs. 
Built and tested on Hera.
https://github.com/NOAA-EMC/Fit2Obs/tree/feature/cmake

executables have `.x` extension.

To build;
`./ush/build.sh`

**Comment by KateFriedman-NOAA** [comment]
Installed new Fit2obs `wflow.1.0` tag on supported platforms: `${BASE_GIT}/Fit2Obs/wflow.1.0`
