### ISSUE TITLE
markupsafe not found on Orion

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/global-workflow#1410]
**Expected behavior**
Job `enkfgdasatmensanlinit` should successfully run to completion on Orion.   It successfully runs to completion on Hera.

**Current behavior**
Job `enkfgdasatmensanlinit` fails on Orion with the traceback
```
+ JGLOBAL_ATMENS_ANALYSIS_INITIALIZE[40]: /work/noaa/da/rtreadon/git/global_workflow/test2/scripts/exglobal_atmens_analysis_initialize.py
Traceback (most recent call last):
  File "/work/noaa/da/rtreadon/git/global_workflow/test2/scripts/exglobal_atmens_analysis_initialize.py", line 12, in <module>
    from pygfs.task.atmens_analysis import AtmEnsAnalysis
  File "/work/noaa/da/rtreadon/git/global_workflow/test2/ush/python/pygfs/task/atmens_analysis.py", line 16, in <module>
    from pygw.yaml_file import YAMLFile
  File "/work/noaa/da/rtreadon/git/global_workflow/test2/ush/python/pygw/src/pygw/yaml_file.py", line 8, in <module>
    from .jinja import Jinja
  File "/work/noaa/da/rtreadon/git/global_workflow/test2/ush/python/pygw/src/pygw/jinja.py", line 3, in <module>
    import jinja2
  File "/work2/noaa/da/python/opt/core/miniconda3/4.6.14/envs/gdasapp/lib/python3.7/site-packages/jinja2/__init__.py", line 8, in <module>
    from .environment import Environment as Environment
  File "/work2/noaa/da/python/opt/core/miniconda3/4.6.14/envs/gdasapp/lib/python3.7/site-packages/jinja2/environment.py", line 14, in <module>
    from markupsafe import Markup
ModuleNotFoundError: No module named 'markupsafe'
```
The above was copied from `/work/noaa/stmp/rtreadon/comrot/prufsatm/logs/2021123100/enkfgdasatmensanlinit.log`

**Machines affected**
Orion

**To Reproduce**
To reproduce this error
1. cd /work/noaa/da/rtreadon/para_gfs/prufsatm
2. rocotorewind -d prufsatm.db -w prufsatm.xml -c 202112310000 -t enkfgdasatmensanlinit
3. rocotoboot -d prufsatm.db -w prufsatm.xml -c 202112310000 -t enkfgdasatmensanlinit
4. tail -f /work/noaa/stmp/rtreadon/comrot/prufsatm/logs/2021123100/enkfgdasatmensanlinit.log

The job will abort with the traceback cited above.

**Possible Implementation**
g-w issue #1403 reported that the jinja2 stack loaded by g-w on Hera was too old.   

- Are we experiencing a similar problem on Orion?   
- Would updating the jinja2 stack on Orion as was done on Hera resolve the Orion failure?

**Comment by WalterKolczynski-NOAA** [comment]
AFAIK, the UFSDA jobs are currently using their own software stack, not the one the rest of workflow is using.

**Comment by RussTreadon-NOAA** [comment]
True @WalterKolczynski-NOAA.   UFS-DA executes `ush/load_ufsda_modules.sh`, not `ush/load_fv3gfs_modules.sh`.

g-w successfully drives atmospheric UFS-DA on Hera.  g-w no longer drives atmospheric UFS-DA on Orion.   Help from anyone in figuring out how to fix this is appreciated.

**Comment by RussTreadon-NOAA** [comment]
Interesting.   Set `DEBUG_WORKFLOW=YES` in `atmensanlinit.sh` and reran job on Hera and Orion.   

The Hera `pip list` includes
```
...
iniconfig                    1.1.1
Jinja2                       3.1.2
jmespath                     0.10.0
keras                        2.11.0
libclang                     15.0.6.1
locket                       1.0.0
Markdown                     3.4.1
MarkupSafe                   2.1.1
mkl-fft                      1.3.1
...
```
In contrast the Orion `pip list` has
```
...
iniconfig          1.1.1
Jinja2             3.1.2
jmespath           1.0.0
mkl-fft            1.3.1
...
```

We need to add `Markdown` and `MarkupSafe` to the Orion environment.   Resolution of this problem probably requires opening a [GDASApp issue](https://github.com/NOAA-EMC/GDASApp/issues).   

I'll leave this g-w issue open until g-w can successfully drive atmospheric UFS-DA on Orion.

**Comment by RussTreadon-NOAA** [comment]
@CoryMartin-NOAA , @guillaumevernieres , @AndrewEichmann-NOAA , or @jiaruidong2017 :  have you encountered any problems running GDASApp from the g-w on Orion?

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA no but I haven't tried recently unfortunately :-(
You need the gdas environment updated on orion to include `MarkupSafe`?

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA try it now, those have been installed on Orion, you can confirm by looking at: `/work2/noaa/da/python/opt/core/miniconda3/4.6.14/envs/gdasapp/lib/python3.7/site-packages`

(I just did a quick `pip install markupsafe` and `pip install markdown` just now)

**Comment by RussTreadon-NOAA** [comment]
@CoryMartin-NOAA , your fix works!   `enkfgdasatmensanlinit` ran to completion on Orion.   Thank you for the quick response.

I'll close this issue.
