### ISSUE TITLE
Update Thompson MP input files 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#1411]
**Expected behavior**
Link to different files for Thompson MP 

**Current behavior**
@guillaumevernieres and others  have reported slowness in initialization and stalling at Thompson MP for a long time.   

Looking at where files are linked in for Thompson MP: https://github.com/NOAA-EMC/global-workflow/blob/develop/ush/forecast_postdet.sh#L240-L250
```
  ####
  #  Copy CCN_ACTIVATE.BIN for Thompson microphysics
  #  Thompson microphysics used when CCPP_SUITE set to FV3_GSD_v0 or FV3_GSD_noah
  #  imp_physics should be 8
  ####
  if [ $imp_physics -eq 8 ]; then
    $NLN $FIX_AM/CCN_ACTIVATE.BIN  $DATA/CCN_ACTIVATE.BIN
    $NLN $FIX_AM/freezeH2O.dat     $DATA/freezeH2O.dat
    $NLN $FIX_AM/qr_acr_qg.dat     $DATA/qr_acr_qg.dat
    $NLN $FIX_AM/qr_acr_qs.dat     $DATA/qr_acr_qs.dat
  fi
```
However in the ufs-weather-model these files are named a little differently: 
 in 
https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/fv3_conf/control_run.IN#L137-L143
```
if [ $IMP_PHYSICS = 8 ]; then
  cp    @[INPUTDATA_ROOT]/FV3_input_data_gsd/qr_acr_qsV2.dat .
  cp    @[INPUTDATA_ROOT]/FV3_input_data_gsd/qr_acr_qgV2.dat .
  cp    @[INPUTDATA_ROOT]/FV3_input_data_gsd/freezeH2O.dat .
  cp    @[INPUTDATA_ROOT]/FV3_input_data_gsd/CCN_ACTIVATE.BIN .
fi
```

but in 
https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/fv3_conf/cpld_control_run.IN#L169-L174
```
if [ $IMP_PHYSICS = 8 ]; then
  cp    @[INPUTDATA_ROOT]/FV3_input_data_gsd/CCN_ACTIVATE.BIN CCN_ACTIVATE.BIN
  cp    @[INPUTDATA_ROOT]/FV3_input_data_gsd/freezeH2O.dat freezeH2O.dat
  cp    @[INPUTDATA_ROOT]/FV3_input_data_gsd/qr_acr_qg.dat qr_acr_qg.dat
  cp    @[INPUTDATA_ROOT]/FV3_input_data_gsd/qr_acr_qs.dat qr_acr_qs.dat
fi
```
these are named more consistently with the workflow.  

**Machines affected**
All

**To Reproduce**
Ask @guillaumevernieres 

**Additional Information**
A ufs-weather-model issue will also be created and referenced here.  

**Possible Implementation**
Link different fix files and have different names.

**Comment by JessicaMeixner-NOAA** [comment]
ufs-weather-model issue is here: https://github.com/ufs-community/ufs-weather-model/issues/1670

**Comment by aerorahul** [comment]
@JessicaMeixner-NOAA 

Per @junwang-noaa the workflow should be copying as follows:
```
    $NLN $FIX_AM/qr_acr_qgV2.dat     $DATA/qr_acr_qgV2.dat
    $NLN $FIX_AM/qr_acr_qsV2.dat     $DATA/qr_acr_qsV2.dat
```

The RT's are using the `V2` version files for both coupled and atm-only tests.

I will open a PR with the update momentarily.

**Comment by yangfanglin** [comment]
@aerorahul Rahul,  Please wait for us to run a test to check the science impact
