### ISSUE TITLE
GSI archives need to be restricted

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/global-workflow#1433]
**Expected behavior**

Any archive that is created in the *arch steps that contains restricted (rstprod) data should itself be assigned to the rstprod group.

**Current behavior**

The archiving scripts do not assign groups.  In particular, the gdas.tar, gdas_restarta.tar, and enkfgdas.tar archives all contain restricted data and are not assigned to the rstprod group.

**Machines affected**

All

**To Reproduce**

Run a cycled experiment through one full cycle, archiving the files locally, then `ls -l` the gdas.tar file.

**Context**

Discovered during globus tests (#1357).

**Additional Information**

Owners of previous experiments that are archived to HPSS or locally on Orion may wish to/should change their group membership for all gdas.tar, gdas_restarta.tar, and enkfgdas.tar files.  This can be achieved with
`find [archive/location] -name "gdas.tar" -o -name "gdas_restarta.tar" -o -name "enkfgdas.tar" -exec chgroup rstprod {} +;`

**Possible Implementation**

The `htar`/`tar` commands could be wrapped within an `sg` when dealing with restricted data.  For example,
```
sg rstprod -c ${TARCMD} -P -cvf "${ATARDIR}"/"${CDATE}"/"${targrp}".tar $(cat "${ARCH_LIST}"/"${targrp}".txt)'
```

**Comment by WalterKolczynski-NOAA** [comment]
This is a high-priority issue, so I'll endeavor to have a PR tonight.
