### ISSUE TITLE
Add new capability of writing restart files on the write grid comp

### ISSUE THREAD

**Issue by junwang-noaa** [NOAA-EMC/global-workflow#1445]
**Description**
The new capability of writing restart files on the write grid components is available in ufs WM ([PR#1633](https://github.com/ufs-community/ufs-weather-model/pull/1633)), committed on 3/28/23). The new feature needs to be integrated in the global_workflow to be used by GFSv17/GEFSv13.

To use the feature, the following changes are required: 
- Add following variable in model_configure: 
quilting_restart:        @[QUILTING_RESTART]
- QUILTING_RESTART:  
1) when .false., the restart files will be written out by FMS during the forecast time (current way)
2) when .true., the restart files will be written out through write grid component with asynchronized IO.

**Requirements**

**Acceptance Criteria (Definition of Done)**

**(Optional): Suggest A Solution**

**Comment by yangfanglin** [comment]
@junwang-noaa Jun, this is a great new capability.   For operation, GFS writes out restart files every 12 hours.  Do we know how much faster the forecast is with this new capability turned on ?   How should the tasks assigned to the Write Grid Component be changed for different resolutions ?
