### ISSUE TITLE
Using similar nemalist templates and configuration files to remove the discrepancy between RT test runs and the global workflow runs

### ISSUE THREAD

**Issue by sadeghitabas** [NOAA-EMC/global-workflow#1447]
**Description**

We are updating nemalist templates and configuration files (model_configure and nems.configure) used in the global RT tests to have consistent format as the global workflow. The goal is to remove the discrepancy between RT test runs and the global workflow runs. We suggest using updated namelist templates and configuration files once its ready. We will notify you once the updates are ready to be used in global workflow.

**Workflow Changes**

The updated files are "cpld_control.nml.IN", "model_configure.IN", "nems.configure.cpld_noaero.IN" and "diag_table_template" in the ufs_weather_model github repository.

**Tasks**
- [ ] Create release branch
- [ ] Make workflow changes for upgrade in release branch (add additional checklist items as needed)
- [ ] Create release notes
- [ ] Cut hand-off tag for CDF
- [ ] Submit CDF to NCO
- [ ] Implementation into operations complete
- [ ] Merge release branch into operational branch
- [ ] Cut version tag from operational branch
- [ ] Release new version tag
- [ ] Announce to users
- [ ] Update Read-The-Docs operations status version in develop

**Comment by WalterKolczynski-NOAA** [comment]
I don't believe this counts as a "production update". Kate and Rahul are both on leave for the rest of the week, but I believe we would need justification as to why this requires an update to the operational version rather than just being absorbed into develop for GFS v17. As such, many of the tasks in the list are probably moot.

That said, we are excited to move away from creating our own namelists in develop.

**Comment by sadeghitabas** [comment]
> I don't believe this counts as a "production update". Kate and Rahul are both on leave for the rest of the week, but I believe we would need justification as to why this requires an update to the operational version rather than just being absorbed into develop for GFS v17. As such, many of the tasks in the list are probably moot.
> 
> That said, we are excited to move away from creating our own namelists in develop.

@WalterKolczynski-NOAA Thank you. Unfortunately, I cannot update the label, could you please update it or let me know how I can do it? Thanks

**Comment by WalterKolczynski-NOAA** [comment]
Done. You probably don't need the task list anymore, since it is just do the work in a feature branch in your fork and then submit a PR.

**Comment by aerorahul** [comment]
partially this done. model_configure and nems.configure (ufs.configure) are using RT templates.
input.nml template work is being done in another issue.
