### ISSUE TITLE
Update RTD to include information on sflux files/GLDAS

### ISSUE THREAD

**Issue by CatherineThomas-NOAA** [NOAA-EMC/global-workflow#1450]
**Description**
As observed by @ADCollard and @emilyhcliu, the section of [Readthedocs](https://global-workflow.readthedocs.io/en/latest/init.html#warm-starts-from-production) on warm starts does not mention the need for sflux files when running with GLDAS.  These files are required when attempting to reproduce previous experiments/operations that are running with GLDAS on.  The global-workflow documentation needs to be updated to include this information.

**Requirements**
Confirm the set of required files for GLDAS to run.
Confirm whether the required files are being saved in operational tarballs.
Update the documentation with needed sflux files.

**Acceptance Criteria (Definition of Done)**
Updated documentation that when followed will allow users to reproduce a run with GLDAS on.

**Dependencies**
None

**Comment by WalterKolczynski-NOAA** [comment]
OBE. Develop is no longer using GLDAS.
