### ISSUE TITLE
HPSS archive of UFS-DA files

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/global-workflow#1454]
**Description**
GSI-DA and UFS-DA ATM generate output files with different names.   g-w `hpssarch_gen.sh` is hardwired for GSI-DA filenames.  This needs to be generalized to easily handle UFS-DA filenames.    Currently script `exglobal_archive.sh` returns a non-zero return code and the archive jobs fail because expected GSI-DA files are not present.

**Requirements**
The g-w archive jobs need to write analysis files to HPSS independent of the DA engine (GSI or UFS-DA).   Ideally a list of files to write to HPSS along with the tarball(s) to which to write the files to would be processed by g-w scripts.   This steps away from hardwiring filenames in `hpssarch_gen.sh`

**Acceptance Criteria (Definition of Done)**
Cycled g-w parallels should be able to write GSI-DA or UFS-DA files to HPSS without error.   Users should be able to easily edit the list of files written to HPSS.

**Comment by RussTreadon-NOAA** [comment]
Tagging @CoryMartin-NOAA, @guillaumevernieres , and @AndrewEichmann-NOAA for awareness.   Perhaps we are already developing a solution in GFS v17 with the addition of UFS-DA marine component.

**Comment by CoryMartin-NOAA** [comment]
In fact, I've discussed with @andytangborn that we need to modify this for aerosol DA archived files. Definitely need to think about how best to refactor this for JEDI+coupled DA

**Comment by aerorahul** [comment]
@RussTreadon-NOAA 
Thank you for opening this issue.
We have some plans for refactoring the archiving scripts by adding a yaml file with templates to archive the various sets of files.  Unfortunately, this is not on our work schedule for the next 2 quarters (atleast).

**Comment by aerorahul** [comment]
I will note that opening this issue definitely helps in gauging the urgency and will help in prioritization.

**Comment by RussTreadon-NOAA** [comment]
Thanks @aerorahul .    A two quarter delay means we'll need to hack something for use in the short term.   I'm cycling UFS-DA ATM.   I just turned on HPSS archiving.  The gdas and enkf archive jobs fail.   My options are to hack the archive step or turn off HPSS archiving.   The later isn't ideal.   We're at the point where want to save output from cycled runs for later evaluation and comparison with other runs.

**Comment by aerorahul** [comment]
Hacking is fine with me at the moment.  However, it would be good to open a descriptive issue of what files need to be archived, at what intervals and patterns should they match so that we can refer to the issue when the work begins.  
Does that work?

**Comment by RussTreadon-NOAA** [comment]
> Hacking is fine with me at the moment. However, it would be good to open a descriptive issue of what files need to be archived, at what intervals and patterns should they match so that we can refer to the issue when the work begins. Does that work?

Sure, I'll add UFS-DA ATM files to this issue.

**Comment by RussTreadon-NOAA** [comment]
**UFSDA ATM var files**
The following new files are created when `fv3jedi_var.x` is run for ATM 3dvar.  These files are in `gdas.$PDY/$cyc/analysis/atmos/`
- radiance bias correction files
  - `${prefix}.${sensor_satid}.satbias.nc4`   (e.g., `gdas.t00z.amsua_n19.satbias.nc4`)
  - `${prefix}.${sensor_satid}.satbias_cov.nc4`
  - `${prefix}.${sensor_satid}.satbias_tlapse.nc4`
- omb and oma diagnostic files (tarball)
  - `${prefix}.atmstat` 
- `${prefix}.atmvar.yaml`

UFSDA ATM var does not create the following GSI-DA files
- `${prefix}.abias*`
- `${prefix}.cnvstat, oznstat, radstat`
- `${prefix}.gsistat`
- `${prefix}.loginc.txt`

Future UFSDA development will likely add more output files or rename existing output files.   It would be very helpful if g-w archive jobs accepted a user generated list of files to archive.  This is preferable to embedding this information via logic in `hpssarch_gen.sh` and then requiring users edit the script as files are added, removed, or renamed.

**Comment by aerorahul** [comment]
@RussTreadon-NOAA 
Thanks for identifying the issues in the archival of UFSDA produced files.
Please create an issue and document the files that are currently being created and if known expected to be created by UFSDA.
We will tackle this capability in the coming months as time and resources allow.

**Comment by RussTreadon-NOAA** [comment]
@aerorahul , may I add the requested information to this existing issue?   I've already done so for UFSDA ATM var.

**Comment by RussTreadon-NOAA** [comment]
**UFSDA ATM ens files**
The following new files are created when `fv3jedi_letkf.x` is run for ATM local ensemble DA. These files are in  `enkfgdas.$PDY/$cyc/ensstat/analysis/atmos/`
- omb diagnostic files (tarball)
  - `${prefix}.atmensstat`
- `${prefix}.atmens.yaml`

UFSDA ATM ens does not create the following GSI-EnKF DA files
- `${prefix}.enkfstat`
- `${prefix}.gsistat.ensmean`

**Comment by RussTreadon-NOAA** [comment]
@guillaumevernieres , @AndrewEichmann-NOAA , @andytangborn , @jiaruidong2017 , and @CoryMartin-NOAA 

Please feel free to use this issue to capture new UFSDA marine DA, aerosol DA, and land DA files we need written to HPSS in cycled parallels.  

EIB would like a central location with UFSDA HPSS archive needs are captured.   They will tackle adding archival flexibility in the coming months as time and resources allow.

**Comment by andytangborn** [comment]
In gdas.yyyymmdd/hh/chem  I'd like to archive:   aeroges.yyyymmdd.hh0000.fv_tracer*,  aeroinc.yyyymmdd.hh0000.fv_tracer* and gdas.thhz.aerostat

**Comment by CoryMartin-NOAA** [comment]
@andytangborn that's the 'old' COM structure btw, you might want to try out a newer version of global-workflow soon.

**Comment by RussTreadon-NOAA** [comment]
Do we still need this issue?  A C48L127 UFSDA parallel was run on Hera.  Jobs gdasarch and enkfgdasarc successfully wrote tarballs to HPSS.

**Comment by CoryMartin-NOAA** [comment]
I think we need to ensure that we have everything we need archived for all the components, and that may be subject to change as the system matures, but I'll leave it up to you if we want to close and open a later one or keep it open

**Comment by RussTreadon-NOAA** [comment]
Good point.  I'll let @WalterKolczynski-NOAA decide whether or not to close this issue.

**Comment by RussTreadon-NOAA** [comment]
HPSS archiving currently works for UFS-DA atmospheric cycling.  Given this, close this issue with the option of reopening at a later date to bring in updates or additions to UFS-DA archiving.  Alternatively, open a new issue or issues as needed.
