### ISSUE TITLE
atm log file name change in ufs-weather-model 

### ISSUE THREAD

**Issue by junwang-noaa** [NOAA-EMC/global-workflow#1458]
In the ufs-weather-model [PR#1704](https://github.com/ufs-community/ufs-weather-model/pull/1704), the atm log file name is changed from: logfXXX to atm.logfxxx. This is to accommodate the need of coupled runs in global workflow that each model component needs to write out its own log file to trigger its downstream jobs. 

The global workflow needs to be updated to use atm.logfxxx instead of logfxxx.

**Description**

**Requirements**

**Acceptance Criteria (Definition of Done)**

**(Optional): Suggest A Solution**

**Comment by WalterKolczynski-NOAA** [comment]
This was covered by #1509
