### ISSUE TITLE
Add WQDMS monitoring tool for conventional & marine data to global-workflow

### ISSUE THREAD

**Issue by ilianagenkova** [NOAA-EMC/global-workflow#1459]
**Description**

WDQMS (WIGOS Data Quality Monitoring System) is a tool generating data quality reports for conventional and marine data.
It was developed by DA team and is being run in real time by Obsproc.
Once a day, the code uses the four gdas.YYYYMMDD/HH/atmos/gdas.tHHz.cnvstat files from the prior day to generate 12 reports:
NCEP_TEMP_YYYYMMDD_HH.csv
NCEP_SYNOP_YYYYMMDD_HH.csv
NCEP_MARINE_YYYYMMDD_HH.csv
where HH=00,06,12,18

The reports are then staged on emcrzdm ftp for downstream users:
https://ftp.emc.ncep.noaa.gov/wdqms/ncep

Code: https://github.com/kevindougherty-noaa/wdqms

Currently, the cron schedule for WDQMS is:
07 14 * * * bash /lfs/h2/emc/obsproc/noscrub/ashley.stanfield/wdqms_new/scripts/WDQMS_new.sh
and a run lasts about 15 minutes on a dev machine.

The operationalization of this tool will prevent reporting gaps and delays during prod switches, wcoss tests, etc.

**Requirements**
Generate 12 monitoring reports per day and stage on emcrzdm ftp, in a prescribed directory

**Acceptance Criteria (Definition of Done)**
The 12 reports are generated and staged by 12 UTC of the next day

** Suggest A Solution**
We propose to include WDMQS as a step in the $pslot.xml file

**Comment by ilianagenkova** [comment]
@dtkleist @HaixiaLiu-NOAA @kevindougherty-noaa @AshleyStanfield-NOAA , I'm tagging you to chime in if I had missed anything. Opening a Feature Request Issue was EIB's preferred way of communicating this request. Thanks!

**Comment by WalterKolczynski-NOAA** [comment]
I don't know if NCO is going to allow posting of files to rzdm from ops. These may need to migrate to NOMADS (and be renamed to meet NCO standards).

**Comment by WalterKolczynski-NOAA** [comment]
Might be best to generate these reports right after we generate the cnvstat files (in the same job).

**Comment by KateFriedman-NOAA** [comment]
Draft PR #2372 opened for review and testing. Developer will redo PR to send it into an official release branch in the near future ahead of hand-off.

**Comment by KateFriedman-NOAA** [comment]
Closing in lieu of official issue for this being opened (#2389). @ilianagenkova please see issue #2389 for this work now.
