### ISSUE TITLE
Update verif-global to include Jet support

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/global-workflow#1462]
**Description**

The develop branch of verif-global currently supports Jet.  The hash should be updated to allow the package to run within the global workflow.

**Requirements**

Some updates outside of the port to Jet of verif-global require testing and possible modification in the current global workflow.

**Acceptance Criteria (Definition of Done)**

All .stat files are successfully generated and comparable across systems.

**Comment by KateFriedman-NOAA** [comment]
Similar to another issue, closing for now and will reopen down the road when we can come back to either updating to a newer version of verif-global or move to EVS.
