### ISSUE TITLE
Update the TC tracker to incorporate Jet support

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/global-workflow#1463]
**Description**

The TC tracker tag should be incremented and incorporated to include support for Jet.

New tag: https://github.com/NOAA-EMC/TC_tracker/releases/tag/ens_tracker.v1.1.15.6

**Requirements**

**Acceptance Criteria (Definition of Done)**

The tracker can be run within the workflow with comparable results to other HPCs.

**Comment by KateFriedman-NOAA** [comment]
New tag installed on supported platforms under `${BASE_GIT}/TC_tracker/v1.1.15.6`.
