### ISSUE TITLE
numpy.int does not exist after version 1.24.0

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/global-workflow#1467]
**Description**
The numpy.int type is deprecated in recent versions of the package and in the newest version, 1.24.1, it has been removed.  This will cause issues with some of the workflow scripts.  The use of `numpy.int` can be replaced with `numpy.int_` and be backward compatible in most cases.

**Acceptance Criteria (Definition of Done)**
All workflow scripts work correctly with numpy version 1.24.1+.

**Comment by WalterKolczynski-NOAA** [comment]
@DavidHuber-NOAA Can you please point out where this needs to be updated? A grep failed to reveal any.

Can we just use native `int()` instead of the numpy one?

**Comment by DavidHuber-NOAA** [comment]
@WalterKolczynski-NOAA At the time, this just existed in workflow/rocoto/workflow_tasks.py (now tasks.py), but the number of nodes is now calculated a different way.
Old: `nodes = np.int(np.ceil(np.float(cores) / np.float(ppn)))`
New: `nodes = int(np.ceil(float(cores) / float(ppn)))`

There are a few places in gsi_utils that use `np.as_type(np.int)`, but I can open an issue to handle those in that repo.

So yes, it does look like `int()` will work in for the global workflow.  I'll go ahead and close this.  Thanks!
