### ISSUE TITLE
Scripting for soil moisture and temperature analysis

### ISSUE THREAD

**Issue by ClaraDraper-NOAA** [NOAA-EMC/global-workflow#1479]
**Description**

GSI issue  #508 (Add EnKF updating of soil temperature and soil moisture to the global EnKF) and the associated PR (#557) will add the capability to use the GSI EnKF to perform a soil moisture and/or temperature analysis. Implementing this at EMC will require changes to the global_workflow (including staging of obs, updates to anavinfo and convinfo, code to add increments to the model restarts ).

Note: addition of the soil increments to the model state is done outside of the GSI, and must be tailored to the land model (i.e, Noah, Noah-MP). Land increments have historically been added using global_cycle, however this code cannot handle fractional grids, so it may be better to add the increments using a purpose-built code base. Current code at PSL (not in global_cycle) for doing this for snow depth cannot interpolate between grids.

**Requirements**
Ability to run GSI (enkf only? or hybrid?) cycling experiments assimilating T2m and q2m to update model soil moisture and soil temperature.

**Acceptance Criteria (Definition of Done)**
Ability to run experiment described above without changing output from current experiments.

**Comment by CatherineThomas-NOAA** [comment]
Additional information: The current plan is to run the surface EnKF with the atmospheric part, which will not require any new jobs in the workflow.  However if running them together degrades skill, we may need to run the sfc part separately.  For now, it was agreed to proceed with the assumption that they will run together and cross the "new job" bridge later if we need it.

Related issues: [GSI#507](https://github.com/NOAA-EMC/GSI/issues/507), [GSI#508](https://github.com/NOAA-EMC/GSI/issues/508)

**Comment by CatherineThomas-NOAA** [comment]
@CoryMartin-NOAA @aerorahul 

Tagging @GeorgeGayno-NOAA for awareness on upcoming global_cycle requests.

**Comment by ClaraDraper-NOAA** [comment]
@CatherineThomas-NOAA I'm mostly done with the global_cycle PR, and should finalize it next week (once hera is back). 

UFS_UTILS issue:
https://github.com/ufs-community/UFS_UTILS/issues/832

**Comment by KateFriedman-NOAA** [comment]
@ClaraDraper-NOAA checking the status of this issue :)

**Comment by ClaraDraper-NOAA** [comment]
The pieces are all in place, in terms of the individual programs ( I do need to submit a tidyup PR to the GSI - but I think it will run in the current code). I'm using global cycle to do the soil update. The big out-standing issue is how to update the deterministic member / re-center the ensemble. This probably won't be resolved until early next year. 

I'm also not sure who will actually do the scripting work. @barlage @CoryMartin-NOAA?   

@KateFriedman-NOAA  - does this answer your question?

**Comment by KateFriedman-NOAA** [comment]
> @KateFriedman-NOAA - does this answer your question?

Yep, thanks! Wanted to check this was still in progress. :)

**Comment by ClaraDraper-NOAA** [comment]
If anyone is interested, I have a first pass at a branch to add the soil analysis: 
https://github.com/ClaraDraper-NOAA/global-workflow/tree/feature/soil_updates

It requires changes to the GSI and UFS_UTILS code that I haven't added to the branch - happy to provide details. 

Next up, I'll add code to update the deterministic member.

**Comment by ClaraDraper-NOAA** [comment]
@CoryMartin-NOAA @KateFriedman-NOAA @CatherineThomas-NOAA @aerorahul 

@barlage suggested that I submit this as a PR now, since the next step will be much more meddlesome (adding code to add the ensemble mean soil increment to the deterministic member). I'd clean it up to avoid some of my hard-coded decisions/files in the current version. The result would add a flag to config.base, which if turned on would calculate soil increments using the EnKF, then add these increments to the ensemble members restarts only (so, no land IAU yet). Scientifically, this is an intermediate step towards the system we're hoping to use in GFSv17, which would also add the increment to the deterministic member (since we don't yet know how to directly do a Var analysis on soil states).

We'd probably want to compare this to what @jiaruidong2017 has done for the snow DA to see if we can streamline them. The soil DA uses the GSI, and the snow DA is JEDI, so they're quite different and I don't think there'll be any overlap.

What do folks think?

**Comment by CoryMartin-NOAA** [comment]
Seems reasonable to me!

**Comment by CatherineThomas-NOAA** [comment]
@ClaraDraper-NOAA 
I think adding this piece in before the deterministic member part is sorted is good.  Also, thinking about the land DA as a whole and how the soil DA will or won't interact with the snow DA (and global cycle) is a great idea, particularly when it comes to potential job failures and needing to restart the system.

**Comment by ClaraDraper-NOAA** [comment]
I'll try to prepare the PR this week. 

I've also scoped what we have to do to deal with the deterministic member, and it's much less messy than I was thinking (we will need to add a dependence of the deterministic forecast job on the ensemble analysis though). 

@jiaruidong2017 Can you please send me the repo details for your code for adding the JEDI snow depth increments to the ensemble members?  And, if you've changed the workflow .xml much, maybe also send me an example experiment directory so that I can have a look at the job dependencies. Then I can code the re-centering step so that you can also use it for the snow depth.

**Comment by jiaruidong2017** [comment]
@ClaraDraper-NOAA You can find the details of my changes at a draft PR #2033.
