### ISSUE TITLE
gdasanalcalc runs out of memory (C384) on Hera

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/global-workflow#1481]
**Bug description**
The "change resolution" executable (`chgres_inc.x`) fails and throws an error related to not enough memory.
log: ```/scratch2/NCEPDEV/ocean/Guillaume.Vernieres/runs/low-res/golden-c384/COMROT/golden-c384/logs/2021071518/gdasanalcalc.log```

**Machines affected**
Hera

**To Reproduce**
Run an atmos 3DVAR no IAU cycle at C384

**Context**
This happened when running the WCDA system, which has the atmos analysis done at the same resolution as the background (not 100% sure on that one ...) instead of 1/2. Could that be the issue?

**Possible Implementation**
Set resolution dependent memory requests ...

**Comment by aerorahul** [comment]
If the experiment is a single resolution one, what and why is there a change of resolution?

Is the experiment a 3DVar for the atmosphere?

**Comment by guillaumevernieres** [comment]
> If the experiment is a single resolution one, what and why is there a change of resolution?
> 
> Is the experiment a 3DVar for the atmosphere?

I have not looked at what the change of resolution is for yet, just reporting the bug before I forget. I'll take a closer look tomorrow.

Yes, it's a 3DVAR for the atmosphere.

**Comment by CoryMartin-NOAA** [comment]
Confirming this is an issue. `analcalc` uses the same resources regardless of resolution, so for C384, it runs out of memory (only 4 nodes for 127 PEs...)

**Comment by CoryMartin-NOAA** [comment]
I think the 'correct' solution here is to not run the interp_inc when not running `DOHYBVAR`. I am working on hacking this to get it to work and will PR when ready.

**Comment by jiaruidong2017** [comment]
I still had this issue, and the task `gdasanalcalc` failed on the C384 runs as below: 

![image](https://github.com/NOAA-EMC/global-workflow/assets/27369703/81212ca7-ffd6-49d4-b6d9-c69956d7e419)

The log file on hera: /scratch1/NCEPDEV/global/Jiarui.Dong/ptmp/landid9/logs/2021113006/gdasanalcalc.log

I did try to increase the computing resources to several times of current settings, but the runs failed again. Does anybody have any suggestions? Thanks.

**Comment by RussTreadon-NOAA** [comment]
Instead of changing the computing resources, try specifying the memory required for the job.   

Several of the jobs in `landid9.xml` include a `<memory>` entry.   These are specified in `config.resources`.  

For example, the `analdaig` section of `config.resources` includes the line `export memory_analdiag="48GB"`.   This winds up as `<memory>48GB</memory>` in `landid9.xml`.   

You could try a large number, say 48GB and see what happens.

**Comment by jiaruidong2017** [comment]
Thanks @RussTreadon-NOAA, and I will try it.

**Comment by jiaruidong2017** [comment]
It works. Thanks @RussTreadon-NOAA again.

**Comment by WalterKolczynski-NOAA** [comment]
I think this particular one was resolved by #1763, and failing that this has been subsumed by #1664
