### ISSUE TITLE
Rename WW3 grids to fit G-W desired standards 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#1493]
**Description**

There is a request to change the name of wave grids.  This issue is describing current grids so that we can determine if new names are needed and what that naming convention is: 

| Current name in fix file |  Description of grid | Current use scenario (operations/experiments) | Likely use in v13/v17 or for testing | 
| -----  | -----  | -----  | -----  | 
| ww3_grid.inp.ak_10m |  Alaskan 10 min wave grid |    |  possible output grid   | 
| ww3_grid.inp.ant_9km   |   Antarctic Ocean PolarStereo 9km | likely made for testing |  unlikely    | 
| ww3_grid.inp.ao_20m |  ArcticOcean 0.25deg  |  GEFSv12 operational computational grid    |  unlikely  | 
| ww3_grid.inp.aoc_9km |   Arctic Ocean PolarStereo 9km  |  Operational v16 computational grid |  unlikely |
| ww3_grid.inp.at_10m |  NW Atlantic 10 min wave grid  | Operational v16 output grid   |   likely v17 output grid |
| ww3_grid.inp.ep_10m |  East Pacific 10 min wave grid   |  Operational v16 output grid   |   likely v17 output grid |
| ww3_grid.inp.gefsv13_025 |   Global 0.25 masked > 82.5 N, regular lat/lon grid  |   |  GEFSv13 operational grid   |
| ww3_grid.inp.glix_10m |  GFSv16-wave Global 1/6 deg exchange grid  | v16 input grid   |  unlikely |
| ww3_grid.inp.glo_10m |  GFSv16-wave Global Core 1/6 deg  |  unsure  | unlikely  |
| ww3_grid.inp.glo_15m |  Global 0.25  |  GEFSv13 operational computational grid  | unlikely   |
| ww3_grid.inp.glo_15mxt |  GFSv16-wave Global 1/4 extended grid   |  v16 interpolated output grid  (and GEFS)  |  likely an output for v17 |
| ww3_grid.inp.glo_30m |   Global 30 min wave grid |  Operational v16 output grid   |   likely v17 output grid |
| ww3_grid.inp.glox_10m |  GFSv16-wave Global 1/6 deg exchange grid  (same as ww3_grid.inp.glix_10m) |  v16 input grid | unlikely  |
| ww3_grid.inp.gnh_10m |  GFSv16-wave N Hemisphere 1/6 deg grid  | Operational v16 computational grid  |  unlikely |
| ww3_grid.inp.gsh_15m |  GFSv16-wave S Hemisphere 1/4 deg  |  Operational v16 computational grid   | unlikely |
| ww3_grid.inp.gwes_30m | Global NAWES 30 min wave grid GWES v3.0.0   |  Used in many prototypes, former or updated GWES grid |  only if someone wanted to go back to prototype testing |
| ww3_grid.inp.icean_5m |  GFSv16 Global 1/12 degree ice grid  |  likely used in multi_1  | unlikely   |
| ww3_grid.inp.mx025 |   GLO 1/4 deg tripole grid lat 85 |  Used for HR1  |  HR1 testing |
| ww3_grid.inp.mx025gefs |  GLO 1/4 deg tripole grid lat 85 with GEFS lat/lon frequency/directions  |   |  unlikely|
| ww3_grid.inp.mx050 |  GLO 1/2 deg tripole grid lat 85  |  intended to be used for lower resolution testing that hasn't been set up yet, regular grid probably a better option  |  unlikely|
| ww3_grid.inp.mx100 |  GLO 1 deg tripole grid lat 85   |  intended to be used for lower resolution testing that hasn't been set up yet, regular grid probably a better option  | unlikely |
| ww3_grid.inp.points |  spectral resolution for points |  operational v16   |  unlikely |
| ww3_grid.inp.reg025 |  Global regular 1/4 extended grid  |  mx025s regular grid to interpolate to for output, used in HR1   |  HR1 experiements/unlikely for ops  |
| ww3_grid.inp.reg050 |  Global NAWES 30 min wave grid GWES v3.0.0  | original intent was to be mx050's regular counter part  | unlikely   |
| ww3_grid.inp.reg100 | GLOBAL 1 deg grid lat 85   |  original intent was to be mx100's regular counter part  |  unlikely  |
| ww3_grid.inp.rtofs_5m |  GFSv16-wave Global 1/12 degree ice grid  | v16 input  |  unlikley |
| ww3_grid.inp.so_20m |  SothrnOcean 0.25deg |  GEFSv13 operational computational grid | unlikely  |
| ww3_grid.inp.wc_10m |   West Coast 10 min wave grid |  Operational v16 output grid   |   likely v17 output grid |

Grids that are coming: 

Unstructured grids, regular lat/lon low resolution grids for quick testing for the C96/48 5Degree set-ups.  

Open questions: 
* What are the desired naming conventions to follow? 
* What grids do we keep?  Seems like some can be cleaned out.  Do we want to go ahead and move away from any v12/v16 computational or input grid that wont be used.   Do we want to clean out tripolar grids as regular lat/lon grids run faster and would be better suited for engineering testing.  

**Requirements**
Meets g-w CM naming conventions.  

**Acceptance Criteria (Definition of Done)**
PRs for new grids are accepted. 

**Dependencies**
Will likely require a new date for wave fix directory.

**Comment by JessicaMeixner-NOAA** [comment]
@aerorahul can you please provide information on naming formats.  I know @NeilBarton-NOAA and the GEFS group will need something for the GEFS grid sooner than later.   

Grids that we need to keep: 

| Current name in fix file |  keep/delete | 
| -----  | -----  | 
| ww3_grid.inp.at_10m |  keep |
| ww3_grid.inp.ep_10m |  keep  |
| ww3_grid.inp.glo_15mxt |  keep |
| ww3_grid.inp.glo_30m |   keep |
| ww3_grid.inp.wc_10m |   keep |
| ww3_grid.inp.gefsv13_025 |   keep   |

Grids that should be  kept for consistency with prototype testing (and current testing in workflow) : 
| Current name in fix file |  keep/delete | 
| -----  | -----  | 
| ww3_grid.inp.gwes_30m | possibly keep , P8 grid|
| ww3_grid.inp.mx025 |   keep, HR1 grid and default right now |
| ww3_grid.inp.reg025 |   keep,  HR1 grid and default right now  |

Current v12/v16 operational grids, that possibly need to be kept : 
Grids that we need to keep,: 
| Current name in fix file |  keep/delete | 
| -----  | -----  | 
| ww3_grid.inp.ak_10m |  possibly keep    | 
| ww3_grid.inp.ao_20m |  possibly keep  | 
| ww3_grid.inp.aoc_9km |  possibly keep  |
| ww3_grid.inp.glix_10m |  possibly keep  |
| ww3_grid.inp.glo_15m |  possibly keep: new name gnh_15m   |
| ww3_grid.inp.gnh_10m | possibly keep  |
| ww3_grid.inp.gsh_15m |  possibly keep  |
| ww3_grid.inp.points |  possibly keep  |
| ww3_grid.inp.rtofs_5m |  possibly keep  |
| ww3_grid.inp.so_20m |  possibly keep   |


Grids that can likely be deleted: 
| Current name in fix file |  keep/delete | 
| -----  | -----  | 
| ww3_grid.inp.ant_9km   |  delete    | 
| ww3_grid.inp.glo_10m |  delete  |
| ww3_grid.inp.glox_10m |  delete  |
| ww3_grid.inp.icean_5m |  delete    |
| ww3_grid.inp.mx025gefs |  delete |
| ww3_grid.inp.mx050 |  delete |
| ww3_grid.inp.mx100 |  delete  |
| ww3_grid.inp.reg050 |  delete    |
| ww3_grid.inp.reg100 | delete  |


If I look at the "keep" grids + a lot of the older grids, it's usually: 
"region/global/application"_"resolution" description.    Where the resolution is usuaally number of minutes (m) or km.  

The names that don't fit this are the tripolar grids (which were named to be a little closer to an ocean/ice file I believe and the reg* counterparts to those grids.  While these were used in HR1, they wont be used operationally so it might just be easier to remove the other resolutions but otherwise keep those as is and then  find a suitable name for the gefsv13 grid.

**Comment by JessicaMeixner-NOAA** [comment]
Also, all of these grids are either regular or tripolar. The "mx" in some way marks that it's tripolar.  We'll also have unstructured grids coming that will have global coverage with various resolutions that we'll need a naming convention/style for. 

Also the xt after a resolution notes that it's an "extended grid" which usually means this is a -90 to 90 lat for output.

**Comment by JessicaMeixner-NOAA** [comment]
@aerorahul @WalterKolczynski-NOAA @KateFriedman-NOAA  I have tried to provide enough additional explanation so that a convention and decision can be made.  Please let me know if there's any additional information you need from me.

**Comment by JessicaMeixner-NOAA** [comment]
For the gefsv13 grid, if we wanted to do glo_15m which would follow the above formats, we'd have to rename the existing glo_15m to gnh_15m (which is actually a better name for it).   

Note we have a glo_30m and a gwes_30m which is used to distinguish between the existing glo_30m and the newer grid that was made for GWES which was also 30m.  So maybe even gefs_15m isn't out of the question of the norm of conventions from before?

**Comment by aerorahul** [comment]
Referencing tables in https://github.com/NOAA-EMC/global-workflow/issues/1493#issuecomment-1516865280:

From table 1:
`ww3_grid.inp.gefsv13_025` is `quarter degree`. I assume it is also global.  So why not `ww3_grid.inp.glo_025`?

From table 2:
`ww3_grid.inp.gwes_30m`.  What is `gwes`? Is it a region or application?  

From table 3:
`ww3_grid.inp.glo_15m` should be renamed to `ww3_grid.inp.gnh_15m`?  Is this regions NH or global?
`ww3_grid.inp.points` Is this a grid?  
`ww3_grid.inp.glix_10m` What is `glix`?

From table 4:
Since we are deleting, there is no point in reviewing them.

We would also like to catalog the different short-names for the `region` e.g. `glo` is global, `gnh` is global NH(?), etc.
What is `ao` and `aoc`, etc.


The `fix/wave` directory also contains the following files: 
```
├── mesh.gefsv13_025.nc
├── mesh.gwes_30m.nc
├── rmp_src_to_dst_conserv_002_001.nc
├── rmp_src_to_dst_conserv_003_001.nc
├── weights_rtofs_to_r4320x2160.nc
├── WHTGRIDINT.bin.ak_10m
├── WHTGRIDINT.bin.glo_15mext
├── WHTGRIDINT.bin.glo_15mxt
├── WHTGRIDINT.bin.glo_30m
├── WHTGRIDINT.bin.reg025
```
What are these and do we need to keep them?

At the completion of this issue, only files mentioned in this issue will remain in the fix directory and will be catalogued.

**Comment by JessicaMeixner-NOAA** [comment]
> Referencing tables in [#1493 (comment)](https://github.com/NOAA-EMC/global-workflow/issues/1493#issuecomment-1516865280):
> 
> From table 1: `ww3_grid.inp.gefsv13_025` is `quarter degree`. I assume it is also global. So why not `ww3_grid.inp.glo_025`?

That's fine with me.  Most of the other wave grids use minutes instead of degrees, this would help distinguish between the existing 15m grid. 

> From table 2: `ww3_grid.inp.gwes_30m`. What is `gwes`? Is it a region or application?

GWES is Global Wave Ensemble System, so application. Region is global. (The differences between glo_30m and gwes_30m were partially in what is and is not masked out). 

> From table 3: `ww3_grid.inp.glo_15m` should be renamed to `ww3_grid.inp.gnh_15m`? Is this regions NH or global? `ww3_grid.inp.points` Is this a grid? `ww3_grid.inp.glix_10m` What is `glix`?

ww3_grid.inp.glo_15m is the middle 3rd region of the current GEFS 3 grid system.  

glix, if I'm guessing correctly based on the way it's used means something like global input exchange or ice exchange. 

> From table 4: Since we are deleting, there is no point in reviewing them.

> We would also like to catalog the different short-names for the `region` e.g. `glo` is global, `gnh` is global NH(?), etc. What is `ao` and `aoc`, etc.


glo - global 
gnh - global N Hemisphere 
ak - Alaska 
ant - Antarctic 
aoc - Arctic Ocean 
at - Atlantic (or NW Atlantic to be more specific) 
ep - East Pacific 
gsh - Global S Hemisphere 
gwes - global wave ensemble system 
so - Southern Ocean 
wc - West Coast 


> The `fix/wave` directory also contains the following files:
> What are these and do we need to keep them?

To be kept: 
These are used from the mediator.  There format is mesh.${gridname}.nc 

> ├── mesh.gefsv13_025.nc
> ├── mesh.gwes_30m.nc


Needs to be kept for a while: 
This is a ww3_gint weights file.  The g-w will run without this, but if anyone tries to run HR1 it will take a very long time to run the post without this file. 
> ├── WHTGRIDINT.bin.reg025 

Fixed Files used in v16, do not need for v17: 

These are weights used internally in WW3 for multi grid: 
> ├── rmp_src_to_dst_conserv_002_001.nc
> ├── rmp_src_to_dst_conserv_003_001.nc

Weights for remapping RTOFS current input: 
> ├── weights_rtofs_to_r4320x2160.nc

Weights for ww3_gint, will need to be remade for whatever final v17 configuration: 
> ├── WHTGRIDINT.bin.ak_10m
> ├── WHTGRIDINT.bin.glo_15mext
> ├── WHTGRIDINT.bin.glo_15mxt
> ├── WHTGRIDINT.bin.glo_30m

**Comment by aerorahul** [comment]
Thanks.

Table 3 has:
`ww3_grid.inp.ao_20m` and `ww3_grid.inp.aoc_9km`
Are `aoc` and `ao` the same for Arctic Ocean
Is `ww3_grid.inp.points` a grid?

Regarding `gefsv13_025`, do we expect a `gfsv17_025` as well?  If so, what would the difference in the data be?
If none, then would `glo_025` be more appropriate?

Should the `ww3_gint` weight files carry the prefix `ww3_gint` instead of `WHTGRIDINT` to be consistent w/ the `ww3_grid` files?

**Comment by JessicaMeixner-NOAA** [comment]
There is no anticipation that a gfsv17_025 grid will be created.  It likely will use the glo_15mxt for output though.  If there was one, it would potentially differ in what is masked out.  That being said, GFSv17 will be using an unstructured global grid of likely a varying resolution.  A naming convention for how unstructured grids need to be named for g-w would be helpful. 


WHTGRIDINT.bin is the name of the binary weight file that the file is then named to.  The counter part to a ww3_grid.inp file for ww3_gint.inp is actually g-w/parm/wave/${destinationgridname}_interp.inp.tmpl files. 

Aoc and oc do appear both for Arctic Ocean.  One is polar sterographic the other is not, however it's unclear if that was intended as part of the name.  Likely not. 

points is a grid, but in some sense it's a "dummy" grid in some sense for unified point output.  You don't really specify or define a region even, it's for defining the spectral point output grid. We will not have unified point output since moving away from the multi_grid set-up.

**Comment by JessicaMeixner-NOAA** [comment]
@aerorahul, want to confirm that the preferred name for the new GEFS grid is: ww3_grid.inp.glo_025 and that in general the naming convention for structured grids is ww3_grid.inp.gridname where gridname is region_resolution. 

It's unclear what this convention should be for variable resolution unstructured grids.   Note there will be ww3_grid.inp.gridname and gridname.msh files for unstructured grids as well. 

Do we want  WHTGRIDINT.bin.gridname to be changed to ww3_gint.WHTGRIDINT.bin.gridname or something similar? 

Any desire for other parm files to change?  

Once we've confirmed the path forward, I will make a new fix directory and PR that updates any needed scripting changes based on these name changes.

**Comment by WalterKolczynski-NOAA** [comment]
Dropping back into this conversation after being distracted with other stuff.

I'm not sure how to name unstructured grids sensibly. I guess they could still have a region identifier, but what to use in place of resolution? Just number sequentially? (i.e. `glo_unstr001`, `glo_unstr002`) Not sure there is a good answer here (or maybe I just can't think of one).

**Comment by JessicaMeixner-NOAA** [comment]
I'd  recommend having more than just 001, 002, etc to name unstructured grids.   Sometimes they have consistent resolution, other times not.  Hopefully we wont have too many available in the workflow and some sort of version might be needed.  

Still have open question son: 
* Confirm that the preferred name for the new GEFS grid is: ww3_grid.inp.glo_025
* Structured grid convention moving forward is: region_resolution
* Do we want WHTGRIDINT.bin.gridname to be changed to ww3_gint.WHTGRIDINT.bin.gridname or something similar?
* Any desire for other parm files to change?


The most important being the confirmation of ww3_grid.inp.glo_025

**Comment by aerorahul** [comment]
- `ww3_grid.inp.glo_025` makes sense to me.
- `region_resolution` makes sense.
- `ww3_gint.weights.bin.gridname` would this be ok as they are `weights` for `ww3_gint`.
- Haven't looked at the `parm` files.

**Comment by JessicaMeixner-NOAA** [comment]
Thanks for the feedback! I'll start on implementing this change (complete with new fix file descriptions).

**Comment by JessicaMeixner-NOAA** [comment]
The fix file spreadsheet has been updated with descriptions.  @aerorahul @KateFriedman-NOAA please let me know if you'd like any updates to what's there (I'll update it again with the smaller list of files when that's ready too)

**Comment by KateFriedman-NOAA** [comment]
@JessicaMeixner-NOAA Thanks for adding those wave fix file descriptions! I have removed the duplicate file in the list, thanks for catching that!

**Comment by KateFriedman-NOAA** [comment]
@JessicaMeixner-NOAA Checking in on this in case you're waiting on me...where are we on this? Is there an updated/renamed set to replace the current wave fix files or just do the renaming (need guidance)? Thanks!

**Comment by JessicaMeixner-NOAA** [comment]
I have been at a conference.  I should have something for you this afternoon.
