### ISSUE TITLE
Update ufs-weather-model (to EP4 tag)

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#1499]
**Description**
Update ufs-weather-model to EP4 tag (which is only a few commits behind the top of develop of ufs-weather-model and will be used by GEFS group for EP4).  

The updates of note for this include: 
- Updates to unified precip output types (will require diag_table update) 
- Bug fix for convection
- Bug fix for gravity wave drag that causes stochastic physics runs to crash (this is needed for ensemble runs)  

**Requirements**
- Update model tag

**Acceptance Criteria (Definition of Done)**
Using the new tag of ufs-weather-model in develop branch. 

**(Optional): Suggest A Solution**
Update ufs-weather-model to EP4 tag and make sure other files are up-to-date with new model version.

**Comment by WalterKolczynski-NOAA** [comment]
I'm already prepared an update that moves us one commit beyond the EP4 tag. I need to go back and make sure I incorporate the diag table updates though.

**Comment by JessicaMeixner-NOAA** [comment]
Thanks @WalterKolczynski-NOAA we can always make that as a separate PR after.  Thank you for updating this! This will be helpful for multiple groups.
