### ISSUE TITLE
Update ufs-weather-model hash to HR2 code tag

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#1500]
**Description**

This issue is for updating the ufs-weather-model hash to HR2 code tag.  This will make sure several physics changes and updates for the wave model (https://github.com/NOAA-EMC/global-workflow/issues/1547) code changes are included for HR2.  

**Requirements**
- Update to ufs-weather-model tag 

**Acceptance Criteria (Definition of Done)**
Be able to run HR2 from develop branch 

**Dependencies**
Multiple ufs-weather-model PRs will need to be created and merged before the HR2 tag is ready.

**Comment by HelinWei-NOAA** [comment]
We have the new soil texture data and the soil color data. They need to be put into the official fixed directory. Also we change the way the NoahMP reads the parameter table. Now the table is part of input as a file instead of the model as a program. So this table file has to be put into some place and we need to have a soft link in the running script to access.  So the first step is to create a global workflow issue to move those files and then I can update my workflow branch.

**Comment by WalterKolczynski-NOAA** [comment]
The new table would probably go into the workflow parm directory, though if it is added to UFS we can just copy it from there during build instead of carrying around our own copy. We're trying to reduce the redundancy with UFS.

**Comment by HelinWei-NOAA** [comment]
Also we found some fixed fields were created using the old grid files (many years ago). While some including oro were created by using the new grid files. There are some difference between them along the coastline. It is better to start over to create all fixed fields using the same grid files.

**Comment by HelinWei-NOAA** [comment]
I prefer the first approach. It is more straightforward to me.
> The new table would probably go into the workflow parm directory, though if it is added to UFS we can just copy it from there during build instead of carrying around our own copy. We're trying to reduce the redundancy with UFS.

**Comment by WalterKolczynski-NOAA** [comment]
Isn't UFS going to need the new table too, though?

**Comment by HelinWei-NOAA** [comment]
Actually only UFS needs this table. Like input.nml, it is an input for running UFS.
> Isn't UFS going to need the new table too, though?

**Comment by JessicaMeixner-NOAA** [comment]
@HelinWei-NOAA to make it more clear that this PR is only to update the ufs-weather-model tag, I have updated the title and contents of this PR.  If there are namelist, input file or other changes needed for an HR2 related update, please make a new issue and put the HR2 as the milestone.

**Comment by junwang-noaa** [comment]
@HelinWei-NOAA if I understand correctly, the model needs to be updated to read in the soil color, we can create a new model tag after the code is committed. Thanks
