### ISSUE TITLE
Rename parm_fv3diag

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#1510]
**Description**
We are trying to eliminate redundant naming throughout workflow (see previous effort to eliminate `fix_` from the fix directories). Most parm directories have already been updated, but this one has not.

**Requirements**
Remove 'parm_' from the directory name.

**Acceptance Criteria (Definition of Done)**
Forecast job runs properly for all configurations with the renamed parm directory.

**(Optional): Suggest A Solution**
'fv3_tables' would be a more appropriate name than 'fv3_tables', as there are more types of tables than just diag. Or we can just change it to 'fv3'.

**Comment by JessicaMeixner-NOAA** [comment]
The diag tables are for MOM6 as well, so even fms tables could be an option?
