### ISSUE TITLE
Concatenation of sst_drifter fails in JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP

### ISSUE THREAD

**Issue by ShastriPaturi** [NOAA-EMC/global-workflow#1525]
**As the title says**

**Comment by aerorahul** [comment]
@ShastriPaturi 
Thank you for opening an issue.

Just as an FYI, we do have a Bug Report template so details can be added in case someone needs to pick this issue to be worked on.  It also helps describe the problem and possible solutions.

Feel free to self assign.

**Comment by guillaumevernieres** [comment]
... Wrong repo @ShastriPaturi , and I'm not convinced the issue is in the scripting/code.
