### ISSUE TITLE
Update UFS_UTILS hash for gdas_init COM reorg

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#1527]
**Description**

The recent COM reorg in global-workflow requires some changes within the `gdas_init` utility scripts in UFS_UTILS to get generated ICs into the correct structure. This issue will change the UFS_UTILS hash after those updates are made via https://github.com/ufs-community/UFS_UTILS/issues/817.

**Requirements**

- [x] Updated UFS_UTILS hash (72a0471).

**Acceptance Criteria (Definition of Done)**

**Dependencies**

- [x] https://github.com/ufs-community/UFS_UTILS/issues/817
- [x] https://github.com/ufs-community/UFS_UTILS/pull/820

**Comment by KateFriedman-NOAA** [comment]
FYI @GeorgeGayno-NOAA ...are there any updates since https://github.com/ufs-community/UFS_UTILS/commit/4e673bf48b8655f69853e46292c5625cd2c55379 that we need to also be aware of when we move to a new hash? Thanks!

**Comment by GeorgeGayno-NOAA** [comment]
> FYI @GeorgeGayno-NOAA ...are there any updates since [ufs-community/UFS_UTILS@4e673bf](https://github.com/ufs-community/UFS_UTILS/commit/4e673bf48b8655f69853e46292c5625cd2c55379) that we need to also be aware of when we move to a new hash? Thanks!

Updates since that hash have been mostly small things like bug fixes. However, the w3nco library was replaced by the w3emc library at https://github.com/ufs-community/UFS_UTILS/commit/7efbe0fd2dd373ae54d6c2954ebd484e0a3aab48. I don't know if you need to adjust your build at all.
