### ISSUE TITLE
Bug in the staging of the initial MOM6 increment

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/global-workflow#1534]
Asking for forgiveness for not following the template.

There's a typo on [line  91 of setup_expt.py](https://github.com/NOAA-EMC/global-workflow/blob/1e4a24c35088a3db6348156c15bbc81b6f814e40/workflow/setup_expt.py#L91`)

it should be:
```python
    dst_ocn_anl_dir = os.path.join('analysis', 'ocean')
```
There might be more typos, but at least the forecast (S2S) runs to completion with @WalterKolczynski-NOAA 's fixes and the once mentioned above.

**Comment by WalterKolczynski-NOAA** [comment]
Will tackle this today
