### ISSUE TITLE
Update to use unstructured grids for waves

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#1547]
**Description**
The plan for HR2 is to switch from structured to unstructured grids.  

**Requirements**
* updated ufs-weather-model (PR to follow is here:  https://github.com/ufs-community/ufs-weather-model/pull/1730 ) 
* New fix file with undecided grid, mesh.nc file for that grid and ww3_gint weigths 
* SCOTCH scaling issues will have to be mitigated or solved. 
* New ICs.  

**Acceptance Criteria (Definition of Done)**
Be able to run HR2 like set-ups with unstructured grids.

**Comment by JessicaMeixner-NOAA** [comment]
The PR of ufs-weather-model has been merged to enable this capability.   Starting to work on this issue.

**Comment by WalterKolczynski-NOAA** [comment]
@JessicaMeixner-NOAA Is this issue still active? Thanks.

**Comment by JessicaMeixner-NOAA** [comment]
Yes - I aim to have a PR for this later this week.  HR2 -> HR3 though.
