### ISSUE TITLE
`enkfgdasechgres` fails in a single resolution hybrid experiment

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/global-workflow#1557]
**Expected behavior**
`enkfgdasechgres` should succeed when running an hybrid experiment at single resolution.

**Current behavior**
What the title says.

**Machines affected**
Likely all

**To Reproduce**
Setup a single resolution cycling experiment.

I setup a C48/C48 hybrid 3DEnVar experiment without IAU to test the coupled ensemble with only an atmosphere update on Hera.
The experiment directory is at:
```
/scratch1/NCEPDEV/stmp2/Rahul.Mahajan/EXPDIR/s2scyc_h3d
```

This functionality was likely lost when the DA capabilities were updated in previous upgrades.

**Context**
In order to develop cycled capabilities of the coupled model, the lowest available resolutions of the coupled model was used.  In this case, C48 atmosphere with a 5 degree ocean for both deterministic and ensemble.

**Possible Implementation**
Two possible implementations:
- Fix the issue when `CASE_ENKF == CASE` in `enkfgdasechgres` or
- provide a C96 atmosphere with 5-degree ocean for the deterministic member and ignore the failure problem in the previous solution.

Either way, this is a blocker for cycled WCDA.

**Comment by aerorahul** [comment]
@CatherineThomas-NOAA 
Please assign to the appropriate person to investigate.

**Comment by CatherineThomas-NOAA** [comment]
The failure of the C48/C48 test isn’t due to the single resolution.  Rather, it’s due to IAU being turned off.  A C48/C48 atmosphere-only hybrid 4DEnVar with IAU succeeds.  

The problematic line is Line 138 of `exgdas_atmos_chgres_forenkf.sh`:
```  nfhrs=$(echo $IAUFHRS_ENKF | sed 's/,/ /g')```

Even though `DOIAU=NO`, `IAUFHRS_ENKF` is still being set in `config.base`:
```export IAUFHRS_ENKF="3,6,9"```

And not being reset if `DOIAU=NO`:
```
if [[ "${MODE}" = "cycled" && "${SDATE}" = "${PDY}${cyc}" && ${EXP_WARM_START} = ".false." ]] || [[ "${DOIAU}" = "NO" ]] || [[ "${MODE}" = "forecast-only" && ${EXP_WARM_START} = ".false." ]] ; then
  export IAU_OFFSET=0
  export IAU_FHROT=0
fi
```

I also found similar `nfhrs` logic in the eupd step.  I am currently testing explicitly setting `IAUFHRS(_ENKF) = 6` in config.base if `DOIAU(_ENKF)=NO`.

@aerorahul, do you see any issues or blindspots with setting it this way in config.base?

**Comment by CatherineThomas-NOAA** [comment]
Confirming that my test completed several full cycles with no new errors.  A spot check of the ensres files and analysis files looks good.

Here’s the block I used in config.base:
```
# Check if cycle is cold starting, DOIAU off, or free-forecast mode
if [[ "${MODE}" = "cycled" && "${SDATE}" = "${PDY}${cyc}" && ${EXP_WARM_START} = ".false." ]] || [[ "${DOIAU}" = "NO" ]] || [[ "${MODE}" = "forecast-only" && ${EXP_WARM_START} = ".false." ]] ; then
  export IAU_OFFSET=0
  export IAU_FHROT=0
  export IAUFHRS="6"
fi

if [[ "$DOIAU_ENKF" = "NO" ]]; then export IAUFHRS_ENKF="6"; fi
```
I'll submit a PR for this change.
