### ISSUE TITLE
Some forecast resolutions fail on lower-mem HPC when using ESMF threading

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/global-workflow#1572]
**Expected behavior**
Forecasts should succeed.

**Current behavior**
They are not

**Machines affected**
Likely all, but seen on Hera.
**UPDATE: ** The same `P8` case runs fine on Orion.

Experiment directories with links to logs and build are in:
```
/scratch1/NCEPDEV/stmp2/Rahul.Mahajan/EXPDIR/p8
/scratch1/NCEPDEV/stmp2/Rahul.Mahajan/EXPDIR/atmC384
```
The errors are the usual ESMF blah blah blah errors, that are incomprehensible to a mere user of the model.

**To Reproduce**
Setup and run a P8 case or an atmosphere only case with threads from `develop` and try.

**Context**
Just want to get work done.

**Detailed Description**
The model does not even go past the first timestep.  It is impossible to find out where in the process it is with so much (irrelevant) output to `stdout`.

**Recommendation**
@junwang-noaa suggests using 1 write group totaling 60 tasks.
Update `config.ufs` in the `C384` case block to the following:
```bash
        export WRITE_GROUP_GFS=1
        export WRTTASK_PER_GROUP_PER_THREAD_PER_TILE_GFS=10
```
Note that this resolution is using 2 threads for the `_gfs` cycle.

**Comment by JessicaMeixner-NOAA** [comment]
Seems like a memory problem, especially given it ran on orion.  I also ran into a similar issue on hera yesterday for a coupled case and increasing compute tasks, threads and write tasks helped for the atm component.

**Comment by aerorahul** [comment]
Thanks @JessicaMeixner-NOAA 
That is likely true.  Which means we cannot test a coupled forecast on Hera until we know how much memory to increase by.
The P8 coupled case is already quite large (requiring 35 nodes or 1400 cores).  We will try and address that in the future.

Meanwhile, what do you recommend?

**Comment by JessicaMeixner-NOAA** [comment]
Not sure I'd say I'd "recommend" this as there might be something with less resources that would also work, but these changes allowed me to succeed for C384.  Note C768 tends to also need modifications (mostly in write tasks) to run out of the box as well in my recent experience.   

```
diff --git a/parm/config/config.ufs b/parm/config/config.ufs
index a96ba126..6211fca3 100644
--- a/parm/config/config.ufs
+++ b/parm/config/config.ufs
@@ -149,15 +149,15 @@ case "${fv3_res}" in
         export DELTIM=300
         export layout_x=6
         export layout_y=8
-        export layout_x_gfs=8
+        export layout_x_gfs=12
         export layout_y_gfs=8
-        export nthreads_fv3=1
+        export nthreads_fv3=2
         export nthreads_fv3_gfs=2
         export cdmbgwd="1.1,0.72,1.0,1.0"  # mountain blocking, ogwd, cgwd, cgwd src scaling
         export WRITE_GROUP=2
-        export WRTTASK_PER_GROUP_PER_THREAD_PER_TILE=8
+        export WRTTASK_PER_GROUP_PER_THREAD_PER_TILE=10
         export WRITE_GROUP_GFS=2
-        export WRTTASK_PER_GROUP_PER_THREAD_PER_TILE_GFS=4
+        export WRTTASK_PER_GROUP_PER_THREAD_PER_TILE_GFS=10
         ;;
     "C768")
         export DELTIM=150
```

**Comment by aerorahul** [comment]
oof. thats gonna cost a pretty penny.  This is the stock configuration every user runs with.
I'll update to these in the interest of ensuring the case runs, but will replace this configuration as default with a lighter one ASAP, even if that means we need to remove components for testing.

**Comment by JessicaMeixner-NOAA** [comment]
I didn't think you'd want to use those numbers, but if you want something to run right now, that'll do it.  Based on my experience with C768, it might just be write grid, so I'd try increasing that number first.   I think there's a regression test in the ufs-weather-model, maybe we could look at that configuration as another idea for a possibility.    There's likely a much lighter weight version that could be used.  Leveraging the scaling work might be possible for other ideas, but the focus there is more operational timings which isn't the same goal that you have here (or my assumption, which is you want reasonably fast, balanced, but less resources to get through queue faster).

**Comment by junwang-noaa** [comment]
I don't think we need to increase the atm layout for C384. I think the reason might be that the write tasks are not shared with other component in the coupled run, which alleviates the memory requirement on the write grid comp, while in the standalone run, it reaches the limit of the write grid comp. Do we know how many write tasks are used by C384 coupled run?

**Comment by junwang-noaa** [comment]
I set up an atmonly case from RT cpld_bmark_p8 case and was able to run the C384 case a coupled weekly ago. We are using 1 write group and 96 write tasks per node (cores) though. Again, FV3ATM scales well, we don't see issue there. I am not sure how that is connected here.

**Comment by JessicaMeixner-NOAA** [comment]
I ran a test just changing this: 

```
diff --git a/parm/config/config.ufs b/parm/config/config.ufs
index a96ba126..5dea425b 100644
--- a/parm/config/config.ufs
+++ b/parm/config/config.ufs
@@ -157,7 +157,7 @@ case "${fv3_res}" in
         export WRITE_GROUP=2
         export WRTTASK_PER_GROUP_PER_THREAD_PER_TILE=8
         export WRITE_GROUP_GFS=2
-        export WRTTASK_PER_GROUP_PER_THREAD_PER_TILE_GFS=4
+        export WRTTASK_PER_GROUP_PER_THREAD_PER_TILE_GFS=10
```


And the forecast for C384 coupled succeeded, if that helps at all.

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA Thanks, can you try if one write group is enough? I suspect we don't need two if we have 60 tasks for one write group. If  you have a run directory I can take a look too. My job stays in the queue for long time.

**Comment by JessicaMeixner-NOAA** [comment]
@junwang-noaa unfortunately I did not get to this today and will be out on travel at the beginning of next week.  My guess is someone else will be able to test this before I get a chance.  If this is still outstanding late next week I can test then.

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA no worries, thanks!

**Comment by aerorahul** [comment]
@JessicaMeixner-NOAA 
Did your update to the write grid component resources (`config.ufs`) in PR #1608 overcome the failure on Hera?
Can this issue be marked as resolved?

**Comment by JessicaMeixner-NOAA** [comment]
Oops that did get in there didn't it.  This change did allow me to run C384 tests.  Whether it's the "best" choice (ie can you succeed with fewer) I did not explore.  But things should now work.

**Comment by aerorahul** [comment]
Ok. @junwang-noaa suggests 1 group with 60 tasks, instead of 2 groups with 120 tasks total (currently).
We can test `(1, 10)` for C384 in `config.ufs` and dial this down in a upcoming PR.

I will leave this issue open till then with an action item.

**Comment by guillaumevernieres** [comment]
Bump and pinging @JessicaMeixner-NOAA and @NeilBarton-NOAA who were volunteered to help me out ;)
I'm having similar issues with the coupled model at `AC384/O025` . The first `gdasfcst` 1/2 cycle is running out of memory. 

It worked with 40 nodes and updates to the threading. That's a lot of nodes, but:
The last time we ran that resolution we were using 19 nodes on Hera and running the 9hr forecast in ~28 mn. It's taking 12mn for the same forecast on 40 nodes. Nice speedup, I'll take it! but the requested time needs to be updated.

**Comment by NeilBarton-NOAA** [comment]
Note, the number of threads FV3 needs is dependent on machine. Currently for C384, only one is used in g-w, which results in an out-of-memory error on hera. 

@aerorahul Is there an option to use different threads and tasks counts for different machine?

**Comment by aerorahul** [comment]
No.  This is currently not a configurable option.

**Comment by guillaumevernieres** [comment]
Is somebody working on properly resolving this issue?

**Comment by RussTreadon-NOAA** [comment]
As mentioned in g-w issue #1695, setting `nthreads_fv3=2` in the C384 section of `config.ufs` allows the FV3_GFS_v17_p8 `ufs_model.x` to run to completion on Hera.   The resulting xml file specifies
```
    <nodes>20:ppn=40:tpp=1</nodes>
```
gdasfcst runs ufs_model.x with

```
+ exglobal_forecast.sh[182]: srun -l --export=ALL -n 800 /scratch2/NCEPDEV/stmp1/role.jedipara/
```
I wouldn't call this a solution.   It's a sensitivity.  

The same case was rerun on Orion but with `nthreads_fv3=1`.  gdasfcst ran to completion.   Something strange is happening on Hera.

**Comment by JessicaMeixner-NOAA** [comment]
My guess is it's a memory issue on hera which I believe has quite a bit less than Orion or WCOSS2.

**Comment by aerorahul** [comment]
I would really like some resolution on this issue.  Our CI tests have shown that this is not an issue.  
If there is a test that is missing to catch this, please reach out to the global-workflow developer team and we can reopen this issue.

**Comment by CoryMartin-NOAA** [comment]
#1763 changed the thread count allowing the C384 forecast to run to completion.
