### ISSUE TITLE
chdir command is not working

### ISSUE THREAD

**Issue by jiaruidong2017** [NOAA-EMC/global-workflow#1574]
I tried to use `chdir` from `pygw.fsutils`, but the `chdir` command isn't working. My test code is below: 

```
from pygw.fsutils import chdir

        workdir = os.path.join(self.task_config.DATA, 'anl')
        print(f"workdir: {workdir}")
        cwd = os.getcwd()
        print(f"cwd1: {cwd}")
        chdir(workdir)
        cwd = os.getcwd()
        print(f"cwd2: {cwd}")
```

The output from logfile is below:

```
workdir: /scratch1/NCEPDEV/stmp2/Jiarui.Dong/RUNDIRS/landid88/gdaslandanl_06/anl
cwd1: /scratch1/NCEPDEV/stmp2/Jiarui.Dong/RUNDIRS/landid88/gdaslandanl_06
cwd2: /scratch1/NCEPDEV/stmp2/Jiarui.Dong/RUNDIRS/landid88/gdaslandanl_06
```
It didn't change the directory. @aerorahul Would you please help to investigate the issue? Thanks.

**Comment by WalterKolczynski-NOAA** [comment]
Has `$DATA/anl` been created, or just `$DATA`? Can't chdir into a directory that doesn't exist.

**Comment by jiaruidong2017** [comment]
@WalterKolczynski-NOAA The `$DATA/anl` has been created already. Thanks.

**Comment by HenryRWinterbottom** [comment]
@jiaruidong2017 `os.getcwd()` is going to return the path that you are executing your script from.

Can you run your test script in `$DATA/anl` and let us know what that returns?

**Comment by jiaruidong2017** [comment]
@HenryWinterbottom-NOAA When I used the `os.chdir(workdir)` to replace `chdir(workdir)`, it worked as below: 

```
workdir: /scratch1/NCEPDEV/stmp2/Jiarui.Dong/RUNDIRS/landid88/gdaslandanl_06/anl
cwd1: /scratch1/NCEPDEV/stmp2/Jiarui.Dong/RUNDIRS/landid88/gdaslandanl_06
cwd2: /scratch1/NCEPDEV/stmp2/Jiarui.Dong/RUNDIRS/landid88/gdaslandanl_06/anl
```

**Comment by WalterKolczynski-NOAA** [comment]
So is this resolved then?

**Comment by jiaruidong2017** [comment]
The `os.chdir()` is working, but the `chdir()` from `pygw.fsutils` to import `chdir` is not working yet.

**Comment by aerorahul** [comment]
@jiaruidong2017 I can reproduce this issue.

**Comment by aerorahul** [comment]
The `chdir` method in `fsutils` is not supposed to replicate `os.chdir`.

`pygw.fsutils.chdir` was written where someone is continuously changing directories to do local operations.  

Consider the use case:
```python3
cwd = os.getcwd()
os.chdir(dir_A)
do stuff in dir_A
os.chdir(cwd)
os.chdir(dir_B)
do_stuff in dir_B
```

The `pygw` rendition of `chdir` is to be used in a context manager sense.
It is supposed to be used as follows:

With `pygw.fsutils.chdir`, the above use case is reduced to:
```python3
with os.chdir(dir_A):
    do stuff in dir_A

with os.chdir(dir_B):
    do stuff in dir_B
```

So, this is not a bug in the code.  It is an improper use of the function `pygw.fsutils.chdir`.

**Comment by jiaruidong2017** [comment]
Thanks @aerorahul for the detailed explanations.

**Comment by CoryMartin-NOAA** [comment]
@aerorahul is there documentation on this? also based on this explanation I might suggest a different name than "change dir", something maybe like `pygw.fsutils.enterdir`? or is that too messy? I would think the average user would expect `pygw.fsutils.chdir` to work like `cd` and change the pwd.

**Comment by aerorahul** [comment]
@CoryMartin-NOAA 
I can add documentation. 
I can also name it `change_dir` to make it unambiguous to `os.chdir`.
The idea of keeping it close to `os.chdir` was to be able to emulate the property of `os.chdir`.  I am confident that naming it `change_dir` will not stop the average user from using it incorrectly.
Should I also rename `rmdir`, `mkdir` etc. to make them unambiguous?  One would loose the linux-like feel.

**Comment by CoryMartin-NOAA** [comment]
But `rmdir` and `mkdir` work as expected right? Or am I incorrect?

**Comment by aerorahul** [comment]
They do.  The question was to make them unambiguous.
I will add documentation.  It is missing in many places.
I would prefer to keep it `fsutils.chdir`.
