### ISSUE TITLE
Update MET+ job for COM refactor

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#1575]
**Expected behavior**
The MET+ job should use the new COM templates and locations.

**Current behavior**
The MET+ job (`jobs/rocoto/metp.sh`) still uses the old hard-coded directory path.

**Machines affected**
All

**To Reproduce**
Examine https://github.com/NOAA-EMC/global-workflow/blob/develop/jobs/rocoto/metp.sh

**Context**
I missed or skipped this one during the COM refactor because the job does not fail (at least after only 5 full cycles).

**Comment by malloryprow** [comment]
I have work done for updating metp for the COM refactor. Actually, the part that needed changing I could remove entirely due to the work in PR https://github.com/NOAA-EMC/global-workflow/pull/1900. I added a setting in config.metp and updated the commit checked out for EMC_verif-global. It is off the same branch that is being checked out now.

**Comment by malloryprow** [comment]
I don't see MET or METplus being loaded in https://github.com/NOAA-EMC/global-workflow/blob/develop/modulefiles/module_base.wcoss2.lua, https://github.com/NOAA-EMC/global-workflow/blob/develop/modulefiles/module_base.jet.lua, or https://github.com/NOAA-EMC/global-workflow/blob/develop/modulefiles/module_base.jet.lua.

**Comment by malloryprow** [comment]
> I don't see MET or METplus being loaded in https://github.com/NOAA-EMC/global-workflow/blob/develop/modulefiles/module_base.wcoss2.lua, https://github.com/NOAA-EMC/global-workflow/blob/develop/modulefiles/module_base.jet.lua, or https://github.com/NOAA-EMC/global-workflow/blob/develop/modulefiles/module_base.s4.lua.

@WalterKolczynski-NOAA @KateFriedman-NOAA Should I add METplus being loaded to these files?

**Comment by WalterKolczynski-NOAA** [comment]
@malloryprow if you know the correct ones, then please do

**Comment by malloryprow** [comment]
I think so. I'll give it a go.

**Comment by malloryprow** [comment]
@DavidHuber-NOAA This was also fixed in the work for spack-stack 1.6.0 in EMC_verif-global in the global-workflow

**Comment by DavidHuber-NOAA** [comment]
Great, I'll add it to the PR as well.  Thanks!

**Comment by malloryprow** [comment]
With https://github.com/NOAA-EMC/global-workflow/pull/2239 merged, this work has been done.
