### ISSUE TITLE
FV3PETS Calculation

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/global-workflow#1583]
**Description**
Is the FV3PETS calculation correct in [config.resources#L535](https://github.com/NOAA-EMC/global-workflow/blob/6838c0ba5a1dc9033c2e7488ab1a970f70fea506/parm/config/config.resources#L535)?  It seems like `nthreads_fv3` should not be used in the calculation of `PETS`.

**Machines affected**

All

**Context**

kjet was failing with out of memory errors for a C384 gdasfcst run, so I attempted to increase the number of threads 2, which quadrupled the number of cores needed, rather than doubled as expected.

**Possible Implementation**

Remove `nthreads_fv3` from the calculation.  Perhaps this would require `nthreads_fv3` in another location.

**Comment by WalterKolczynski-NOAA** [comment]
When we moved to ESMF-managed threading (#1371), the calculation changed to include the threads because ESMF sorts it all out.

Hera has also seen some memory issues lately, but it seems to be from the more recent UFS update (#1509) that added write quilting (see #1572).

**Comment by DavidHuber-NOAA** [comment]
@WalterKolczynski-NOAA Ah, that makes sense.  This is my first encounter playing with the threading after the ESMF managed threading and I tried editing config.ufs and the .xml myself instead of rerunning setup_xml.py.  I'll keep this in mind.  Thanks!
