### ISSUE TITLE
Move NEMS configure files to parm

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#1599]
**Description**
The nems.configure template files are currently located in `ush/`, but they are not scripts. These should be moved to a directory within `parm/`.

**Requirements**
nems.configure template reside in a `parm/` directory (likely `parm/ufs`)

**Acceptance Criteria (Definition of Done)**
All allowed values of APP work and use the correct nems.configure template in the new location.

**Dependencies**
None

**Comment by aerorahul** [comment]
Ideally, we should use the templates from the `ufs-weather-model` repo itself, if they are found there.
If not, this path can be the fallback.

**Comment by WalterKolczynski-NOAA** [comment]
Agreed, but even in that scenario, they would be linked/copied into `parm/ufs/` at build time and scripts would look for them there.

**Comment by HenryRWinterbottom** [comment]
Are these the same template files FROM the UFSWM that need to or the ones that currently in the GW but need to be moved? If so, this is low hanging fruit I can do quickly.
