### ISSUE TITLE
feature/coupled-crow: ww3 grib post processing producing empty grib files

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#161]
The WW3 grib2 files when using my branch from feature/coupled-crow 
https://github.com/JessicaMeixner-NOAA/global-workflow/tree/feature/p5ww3post
keeps having the following warning: 
warning: empty layer generated
and the resulting grib2 files are all zeros. When post processing with netcdf, the fields are not empty however. This is occurring on both Hera and orion.

**Comment by JessicaMeixner-NOAA** [comment]
A working directory on orion which shows the issue: 
/work/noaa/marine/jmeixner/p5ww3post/test1/DATAROOT/wavepostsbs.372101/output_20130401000000/done.gwes_30m_grib

@arunchawla-NOAA @RobertoPadilla-NOAA maybe there is something obviously wrong I'm missing here. 

log file: /work/noaa/marine/jmeixner/p5ww3post/test1/COMROOT/test01/logs/2013040100/gfs.wavepost.log

**Comment by JessicaMeixner-NOAA** [comment]
@RobertoPadilla-NOAA replicated the issue on hera, but also has not found a fix yet.  @RobertoPadilla-NOAA is working on moving the output to WCOSS to see if that helps.

**Comment by JessicaMeixner-NOAA** [comment]
@RobertoPadilla-NOAA  I made a PR (https://github.com/NOAA-EMC/global-workflow/pull/180) with the updates from the branch https://github.com/JessicaMeixner-NOAA/global-workflow/tree/feature/p5ww3post once it goes through we can use the feature/coupled-crow instead of my branch to continue to debug this issue.  Note that while this PR fixes some issues it does NOT fix the grib2 issue which remains a problem.

**Comment by JessicaMeixner-NOAA** [comment]
@RobertoPadilla-NOAA can you update the issue with what you have found?

**Comment by RobertoPadilla-NOAA** [comment]
@arunchawla-NOAA  @JessicaMeixner-NOAA The solution, on HERA, to the empty grib2 files from WW3 is  not to use the
 modulefiles/modulefile.ww3.hera which is based on hpc-stack, but to use the modulefiles/module_base.hera.
Using this last set of modules WW3 produce valid grib2 files in the coupled-system. 
It is not the case in Orion, for which the modulefiles/module_base.orion was not appropriately built.

**Comment by JessicaMeixner-NOAA** [comment]
The PR https://github.com/NOAA-EMC/global-workflow/pull/248 from @RobertoPadilla-NOAA fixed this issue in feature/coupled-crow.  The only remaining issue is to have non-empty grib2 files from WW3 while using hpc-stack which is being tracked on hpc-stack: https://github.com/NOAA-EMC/hpc-stack/issues/137

Unless someone objects I think we can close this issue.
