### ISSUE TITLE
adding the new soil color data and updating some of other LSC datasets

### ISSUE THREAD

**Issue by HelinWei-NOAA** [NOAA-EMC/global-workflow#1617]
**Description**
A new soil color dataset is introduced to Noah MP to reflect the right soil albedo to reduce the large warm bias found in the Sahel desert. The more-recent and higher resolution BNU soil texture data will be used to replace the old data. We are still working to create the dataset for all resolutions. We came across some inconsistence issues. The land-sea mask or the grid we are using now may not be the same as to the one used to create the current dataset. The optimal goal is to recreate all surface fixed fields. But they may not be ready for HR2.
 
**Requirements**
The new data has to be put into the official fixed directory for global workflow and the data repo for RTs
The flag to the soil color dataset has to be added to parsing_namelists_FV3.sh

**Tasks**
- [ ] Discuss needs with global-workflow developer assigned to request.
- [ ] Add/update/remove fix file(s) in fix sets on supported platforms (global-workflow assignee task).
- [ ] Update "Fix File Management" spreadsheet (https://docs.google.com/spreadsheets/d/1BeIvcz6TO3If4YCqkUK-oz_kGS9q2wTjwLS-BBemSEY/edit?usp=sharing).
- [ ] Make related workflow/component updates.

**Comment by HelinWei-NOAA** [comment]
The new dataset can be found from /scratch2/NCEPDEV/stmp1/Sanath.Kumar/repo_viirs30s_bnuv2 on hera. Can someone copy them to the authorized fixed directory? Then I can start to modify the workflow.

**Comment by WalterKolczynski-NOAA** [comment]
Data has been copied into the master fix on Hera as orog version 20230615. You can update the fix version in `versions/fix.ver`. I will mirror it to other machines once verified.

Note I've changed the sub-directory name for the surface files from `$RES/fix_sfc` to `$RES/sfc`, so when you update the version in workflow you will also need to update that path. I believe that is only in `ush/forecast_postdet.sh` and `parm/ufs/fix/gfs/land.fixed_files.yaml`.

**Comment by HelinWei-NOAA** [comment]
@WalterKolczynski-NOAA I just created a [PR 1696](https://github.com/NOAA-EMC/global-workflow/pull/1696). What tests do you want me to do? The ufs code related to this change hasn't been committed to the develop branch yet. I need to use my personal branch to do any tests.

**Comment by WalterKolczynski-NOAA** [comment]
I'm going to close that PR. Please open a new one and follow the PR template provided. Also, mark it as draft as we won't merge it until UFS has been updated.

For testing, we are starting to lean on CI testing a bit more. Run whatever tests you would normally run to make sure the changes are doing what you expect, and then we'll do additional testing with CI when everything is ready.
