### ISSUE TITLE
Allow user to optionally specify analysis resolution during experiment setup

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/global-workflow#1618]
**Description**
GSI-based EnVar DA assumes the analysis resolution is the same as the ensemble resolution, `CASE_ENS`.  This assumption is relaxed with UFS (JEDI) - based DA.  The analysis, `CASE_ANL`, and ensemble resolution, `CASE_ENS`, can differ.   This issue is opened to update `config.base.emc.dyn` and `setup_expt.py` such that users can optionally specify the EnVar analysis resolution when setting up an experiment.

**Requirements**
Allow users to optionally specify the EnVar analysis resolution via a new variable, `CASE_ANL`, added to `config.base.emc.dyn`.   If `CASE_ANL` is not specified, default `CASE_ANL` to `CASE_ENS`.  If `CASE_ENS` is not provided, default `CASE_ANL` to `CASE`.   Users set `CASE_ANL` via a new (optional) argument added to `setup_expt.py`.

**Acceptance Criteria (Definition of Done)**
Allow users to optionally specify the EnVar analysis resolution when setting up an experiment.

**(Optional): Suggest A Solution**
Add `CASE_ANL` to the following section of `config.base.emc.dyn`
```
# Resolution specific parameters
export LEVS=128
export CASE="@CASECTL@"
export CASE_ANL="@CASEANL@"
export CASE_ENS="@CASEENS@"
```
Scripting must be added to `workflow/setup_expt.py` to allow the user to define  `CASEANL`.   New scripting will be added in consultation with the g-w team.

**Comment by RussTreadon-NOAA** [comment]
Work for this issue will be done in [`RussTreadon-NOAA:feature/caseanl`](https://github.com/RussTreadon-NOAA/global-workflow/tree/feature/caseanl).

**Comment by aerorahul** [comment]
@RussTreadon-NOAA 
Thanks for opening this issue.
We do plan on replacing the word `CASE` with `ATMRES` to be consistent w/ the other coupled components sometime soon.
If you wish to use `ATMRES_ANL`, please feel free to make use of this change.
Would this change be limited to the JEDI Atmosphere DA jobs; namely `atmanl`, `init`, `run`, `finalize` or do you intend to make this generic for use in the GSI-based analysis as well?
I ask this because that will determine if this new variable should be defined in `config.base` or `config.aeroanl` as this is an internal analysis variable.

**Comment by RussTreadon-NOAA** [comment]
@aerorahul , thank for sharing g-w development plans.  Given your input, I'll use `ATMRES_ANL`.   

The scope of this issue is limited to JEDI Atmosphere DA jobs.  I do not know at present if `ATMRES_ANL` will only be used by `atmanl` jobs `init`, `run`, and `finalize`.  Other jobs might possibly need to know the atmospheric analysis resolution independent of querying an analysis (increment) file.  If true, `config.base` is the preferred file to hold `ATMRES_ANL`.   If the g-w team prefers `ATMRES_ANL` be in `config.atmanl`, I'll do so.  Let me know the g-w team's preference.

**Comment by aerorahul** [comment]
I won't worry about the other jobs that need to query the increment. They can get the dimensions from the increment file metadata. We can proceed w/ modifications in `config.atmanl`

Would you be willing to share what the use case is for this planned capability?
Is there some intuition that I am missing here when `CASE > CASE_ANL > CASE_ENS`?

**Comment by RussTreadon-NOAA** [comment]
The GDASApp changes associated with this g-w issue are documented in GDASApp issue [#475](https://github.com/NOAA-EMC/GDASApp/issues/475).

> I won't worry about the other jobs that need to query the increment. They can get the dimensions from the increment file metadata. We can proceed w/ modifications in `config.atmanl`
> 
> Would you be willing to share what the use case is for this planned capability? Is there some intuition that I am missing here when `CASE > CASE_ANL > CASE_ENS`?

Sorry, I don't understand your question.    I'm an simply trying to remove the GSI-based DA assumption that the resolution of an EnVar analysis, `CASE_ANL` must be `CASE_ENS`.

**Comment by RussTreadon-NOAA** [comment]
GDASApp ctests identified a problem with placing `ATMRES_ANL` in `config.atmanl`.   The analysis resolution is referenced in g-w `ush/python/pygfs/task/atmens_analysis.py`.    If we want to keep `ATMRES_ANL` in `config.atmanl`, UFSDA ATM Ens jobs need to source `config.atmanl` or we need to add `ATMRES_ANL` to `config.atmensanl`.    Neither option is ideal.   It's better at this define `ATMRES_ANL` in `config.base`.

**Comment by aerorahul** [comment]
I grepped for `npx_anl` and the places it is used are:
```
parm/atm/variational/3dvar_dripcg.yaml:      npx: $(npx_anl)
parm/atm/variational/3dvar_dripcg.yaml:      npx: $(npx_anl)
parm/atm/variational/3dvar_dripcg.yaml:      npx: $(npx_anl)
parm/aero/variational/3dvar_gfs_aero.yaml:      npx: $(npx_anl)
parm/aero/variational/3dvar_gfs_aero.yaml:      npx: $(npx_anl)
```

This suggests that they are not used in `atmens_analysis.py`.
I suggest correcting `atmens_analysis.py` to remove `_res_anl` from this python script.

Since the use of `CASE_ANL` is in the variational solver, it has no use in the ensemble solver which `atmens_analysis.py` is for.

**Comment by RussTreadon-NOAA** [comment]
Requested changes committed at [`3f1f06d`](https://github.com/RussTreadon-NOAA/global-workflow/commit/3f1f06d50d9fa2dfc39631ad339bb6650407577a).
- `config.atmanl` - add `ATMRES_ANL`
- `config.base.emc.dyn` - remove `ATMRES_ANL`
- `atmens_analysis.py` - remove `CASE_ANL`

**Comment by RussTreadon-NOAA** [comment]
@guillaumevernieres, @CoryMartin-NOAA , and @aerorahul , there is a typo in `develop` `workflow/setup_expt.py`.  The method `validate_user_request` incorrectly references `ensres`
```
def validate_user_request(host, inputs):
    supp_res = host.info['SUPPORTED_RESOLUTIONS']
    machine = host.machine
    for attr in ['resdet', 'ensres']:
```
This is not correct.  The script variable for the ensemble resolution is `resens` as shown below.
```
    # ensemble-only arguments
    for subp in [cycled, gefs]:
        subp.add_argument('--resens', help='resolution of the ensemble model forecast',
                          type=int, required=False, default=192)
```
and 
```
    if getattr(inputs, 'nens', 0) > 0:
        extend_dict = {
            "@CASEENS@": f'C{inputs.resens}',
            "@NMEM_ENS@": inputs.nens,
        }
```
 When I replace `ensres` with `resens`, GDASApp ctest `test_gdasapp_setup_cycled_exp` fails because  GDASApp `test/setup_workflow.exp.sh` specifies an ensemble resolution of 24
```
gfscyc='4'
resdet='48'
resens='24'
nens=0
pslot='gdas_test'
```

None of the host specific yamls in g-w `workflow/hosts` include `C24`.  The lowest supported resolution is `C48`.

We could add `C24` to the g-w` host yamls but I'm not sure this is the solution you want. 

This problem falls outside the UFSDA ATM specific scope of this issue.  Nonetheless, I wanted to bring it to your attention since I fixed the `ensres` typo in this issue.

**Comment by RussTreadon-NOAA** [comment]
As at test add `C24` to `SUPPORTED_RESOLUTIONS` in `workflow/hosts/hera.yaml` and `workflow/hosts/orion.yaml`.  Rerun GDASApp ctests.  All 49 tests pass on Hera and Orion.

Shall I commit the modified hera and orion yamls to `feature/caseanl`?  If "_yes_", I'll make the same change in the remaining yaml files in `workflow'hosts`.

**Comment by aerorahul** [comment]
The global-workflow does not support `C24`.  There are no fixed files or infrastructure for this resolution.

**Comment by RussTreadon-NOAA** [comment]
OK, @guillaumevernieres and @aerorahul need to figure out a solution.  GDASApp soca ctests use `C24` to keep the soca ctests small.

**Comment by RussTreadon-NOAA** [comment]
@aerorahul and @guillaumevernieres :  Look more closely at the GDASApp ctest failures
```
        1449 - test_gdasapp_setup_cycled_exp (Failed) 
        1463 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP (Failed)
        1464 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_BMAT (Failed)
        1465 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_BMAT_VRFY (Failed)
        1466 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_RUN (Failed)
        1467 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_CHKPT (Failed)
        1468 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_POST (Failed)
```
`test_gdasapp_setup_cycled_exp` and `test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP` fail because they pass an ensemble resolution of `resens=24` to `setup_expt.py`.   Interestingly in both cases an ensemble size of `nens=0` is passed to `setup_expt.py`.    Given this, remove `--resens $resens` from the `setup_expt.py` argument list.  With this change in place the failed tests pass
```
      Start 1449: test_gdasapp_setup_cycled_exp
11/49 Test #1449: test_gdasapp_setup_cycled_exp .............................   Passed    0.38 sec
      Start 1463: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP
25/49 Test #1463: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP ........   Passed   10.66 sec
      Start 1464: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_BMAT
26/49 Test #1464: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_BMAT ........   Passed   42.43 sec
      Start 1465: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_BMAT_VRFY
27/49 Test #1465: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_BMAT_VRFY ...   Passed   42.21 sec
      Start 1466: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_RUN
28/49 Test #1466: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_RUN .........   Passed   10.19 sec
      Start 1467: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_CHKPT
29/49 Test #1467: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_CHKPT .......   Passed   42.20 sec
      Start 1468: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_POST
30/49 Test #1468: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_POST ........   Passed   10.69 sec
```

**Comment by RussTreadon-NOAA** [comment]
While not mentioned above there is another motivation for this issue.

`config.base.emc.dyn` allows the user to set
```
export CASE="@CASECTL@"
export CASE_ENS="@CASEENS@"
```
In contrast, `ush/python/pygfs/task/atm_analysis.py` uses `CASE_ANL` to set the JEDI atmvar analysis resolution.   `CASE_ANL` is currently not defined in `config.base.emc.dyn` or `config.atmanl`.  Developers must manually add `CASE_ANL` to `config.base` or `config.atmanl` in their `EXPDIR`.  This is not a good approach.   

`CASE_ANL` should be included in a config file.    @aerorahul suggested adding `ATMRES_ANL` to `config.atmanl` as
```
export CASE_ANL="@ATMRES_ANL@"
```
This suggestion, a good one, has been implemented in fork `feature/caseanl`.

The **BUG** label is more appropriate for this issue.

**Comment by RussTreadon-NOAA** [comment]
After offline discussion with @aerorahul , reduce the scope of this issue.

Do not allow users to specify an analysis resolution via `setup_expt.py` when setting up an experiment.  Instead, default `CASE_ANL` to `CASE` in `config.atmanl`.  This is consistent with `config.aeroanl`.  If a user wants a different analysis resolution (for example setting `CASE_ANL` to `CASE_ENS` for EnVar DA), they can manually make this change in their EXPDIR copy of `config.atmanl`.

**Comment by aerorahul** [comment]
I don't think this workflow capable of doing Atmosphere EnVar DA with JEDI?
When it is indeed possible, we will introduce logic so no manual intervention is necessary.

Thanks for identifying and fixing the bugs in `atmens_analysis.py` and `setup_expt.py`.

**Comment by RussTreadon-NOAA** [comment]
It is possible to cycle the current g-w with JEDI ATM 3Dvar using `fv3jedi_var.x` concurrently with JEDI ATM local ensemble DA using `fv3jedi_letkf.x`.   This is how JEDI ATM cycling tests over the 20-31 December 2021 period have been run.  The ensemble is not yet allowed to fed back into the variational analysis via a hybrid background error but both gdas and enkfgdas  analyses are generated using JEDI apps.  

The ability to use the ensemble in a variational analysis exists in JEDI.  GMAO and EMC have tested the 3DEnVar capability using `fv3jedi_var.x`.  The GDASApp has a `test_gdasapp_run_jedi_exe_3denvar` ctest.   GMAO is currently working on JEDI 4DEnVar.   

The current g-w could run JEDI atmospheric 3DEnVar with changes to the SABER block processed by `fv3jedi_var.x`.    We have not yet done so because JEDI ATM 3Dvar needs to be scientifically validated.   It's possible that we will begin JEDI ATM 3DEnVar cycling before this validation is fully complete.   If GMAO's JEDI 4DEnVar development is complete we may even jump to this as our next step.
