### ISSUE TITLE
Investigate cloud portability for global-workflow

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/global-workflow#1638]
Investigating cloud properties for global-workflow.
- Software stack for ufs-weather-model and global-workflow in general in a persistent location
- A persistent location to clone and build global-workflow
- A persistent location to hold fix file (`FIX_DIR`) artifacts and observations (`DMPDIR`)
- A persistent location to setup experiment
- A persistent location for `COM`

**Comment by HenryRWinterbottom** [comment]
This has been completed. Closing.
