### ISSUE TITLE
Wave post fails for mx025 (and possibly others)

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#1658]
**Expected behavior**
Wave post should run for all supported wave grids.

**Current behavior**
Wave post fails for mx025 (and possibly other grids).

**Machines affected**
All

**To Reproduce**
1. Set up a C384 coupled experiment or manually change the `waveGRD` to 'mx025'
```
./setup_expt.py gfs forecast-only --app S2SWA --resdet 384 --comrot "${NOSCRUB}/global-workflow" --expdir "${SAVE}/global-workflow/expdir" --idate 2013040100 --edate 2013040100 --pslot "${pslot}"
```
2. Observe wave post failing

**Context**
This surfaced after the default wave grid was updated to `mx025`. The problem may be briefly hidden after PR #1653 is merged as it changes the default wave grid based on the atm resolution and `mx025` is only used for C768+, which is rarely used in workflow development.

**Detailed Description**
Running develop out-of-the-box at a resolution that uses 'mx025' (and quite possibly others) fails due to `GRDNAME` never being defined:

```
/work2/noaa/global/wkolczyn/save/global-workflow/develop/scripts/exgfs_wave_post_gridded_sbs.sh: line 405: GRDNAME: unbound variable
```

There appears to be two things going on:
- `mx025` is not in either of the `case` blocks that may define `GRDNAME`.
- Both of those case blocks are contained within both an if and a for loop of `$DOGRI_WAV`/`$waveinterpGRD` or `$DOGRB_WAV`/`$wavepostGRD`, but is being used outside of those blocks.

**Additional Information**

**Possible Implementation**

**Comment by JessicaMeixner-NOAA** [comment]
@WalterKolczynski-NOAA this is unexpected as this worked the last time I tested it.  I'll look into see what recent change caused this failure and provide a fix ASAP.

**Comment by JessicaMeixner-NOAA** [comment]
The lines here: 
https://github.com/NOAA-EMC/global-workflow/blob/develop/parm/config/gfs/config.wavepostsbs#L20-L24
are not performing as expected.   

mx025 is the only supported grid right now where we expect an interpolated grid output, so this should not be an issue for other girds.  I'll update this logic and make a PR asap.

**Comment by WalterKolczynski-NOAA** [comment]
Thanks @JessicaMeixner-NOAA

**Comment by JessicaMeixner-NOAA** [comment]
I need to finish my testing before making a PR,  but  preliminary testing shows this works: https://github.com/JessicaMeixner-NOAA/global-workflow/tree/bug/wavepostintp if you need an immediate fix @WalterKolczynski-NOAA
