### ISSUE TITLE
Remove data paths from lower level scripts

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#167]
Look through lower level scripts (e.g. ush) and remove path settings that should be in upper level scripts (e.g. JJOBs).

**Comment by WalterKolczynski-NOAA** [comment]
If these settings absolutely must not be changed, we should mark them `readonly` in the j-job. That will actually prevent any downstream script from altering them.

**Comment by WalterKolczynski-NOAA** [comment]
I think there is some overlap between this and #293. This might even be strictly a subset of that issue. Close as duplicate?

**Comment by KateFriedman-NOAA** [comment]
Yeah this overlaps with #293. Closing as duplicate.
