### ISSUE TITLE
Issue cloning on orion with latest g-w develop branch

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#1671]
**Expected behavior**
checkout.sh should work without error. 

**Current behavior**
```
Performing checkout of ufs_utils
|-- Cloning from https://github.com/ufs-community/UFS_UTILS.git into ufs_utils.fd
|-- Checking out 72a0471
|-- Updating submodules (if any)
    WARNING: Error while updating submodules of ufs_utils

```

In /work2/noaa/marine/jmeixner/Lapenta2023/global-workflow/sorc/logs/checkout_ufs_utils.log: 
```
Cloning into 'ufs_utils.fd'...
Note: checking out '72a0471'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 72a0471... Update GDAS INIT utility for GFS COM reorganization (#820)
Submodule 'ccpp-physics' (https://github.com/NCAR/ccpp-physics.git) registered for path 'ccpp-physics'
Cloning into 'ccpp-physics'...
Submodule path 'ccpp-physics': checked out '12c115e992d3a265eaaa67d72fcbdb3a6f21195f'
Submodule 'physics/rte-rrtmgp' (https://github.com/earth-system-radiation/rte-rrtmgp) registered for path 'physics/rte-rrtmgp'
Cloning into 'physics/rte-rrtmgp'...
fatal: reference is not a tree: 7f01618c92409658bddd3afa9acb004c608f6a0d
Unable to checkout '7f01618c92409658bddd3afa9acb004c608f6a0d' in submodule path 'ccpp-physics/physics/rte-rrtmgp'
Failed to recurse into submodule path 'ccpp-physics'

```

**Machines affected**
Orion --- oddly enough I didn't see this on hera? 
So maybe this is a git version issue? 

**To Reproduce**
git clone https://github.com/noaa-emc/global-workflow
cd global-workflow/
cd sorc/
sh checkout.sh 

**Context**
Could be a git verion issue, 

hera version: 
git --version 
git version 2.18.0

Orion version: 
git --version 
git version 1.8.3.1

**Detailed Description**

**Additional Information**

**Possible Implementation**

**Comment by TravisElless-NOAA** [comment]
@JessicaMeixner-NOAA if you run `module load git` before running the checkout script should allow a more recent version of git to be used and the g-w to clone successfully

**Comment by JessicaMeixner-NOAA** [comment]
It does seem like we need to do this, but its not in the instructions so perhaps this just needs to be an issue to update the documentation to ensure this requirement is noted.

**Comment by WalterKolczynski-NOAA** [comment]
The instructions haven't been updated yet (see #1677), but we now have a modulefile for hera and orion that can be loaded for all the setup stuff:
```
# From global-workflow root
module use modulefiles
module load module_gwsetup.[hera|orion]
```

**Comment by aerorahul** [comment]
#1706 resolved this issue. closing.
