### ISSUE TITLE
Permissions issue on Orion Module files used in Global-workflow 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#1679]
**Expected behavior**
Anyone should be able to load modules to run global-workflow. 

**Current behavior**

```
Orion-login-3:~$ module use /work2/noaa/global/wkolczyn/save/hpc-stack/modulefiles/stack
Orion-login-3:~$ module load hpc/1.2.0
Lmod has detected the following error:  Unable to load module because of error when evaluating modulefile:
     /work2/noaa/global/wkolczyn/save/hpc-stack/modulefiles/stack/hpc/1.2.0.lua: Empty or non-existant file
     Please check the modulefile and especially if there is a the line number specified in the above message 
While processing the following module(s):
    Module fullname  Module Filename
    ---------------  ---------------
    hpc/1.2.0        /work2/noaa/global/wkolczyn/save/hpc-stack/modulefiles/stack/hpc/1.2.0.lua
```

**Machines affected**
Orion 

**To Reproduce**
If you do not have global group on orion, try to load the set up modules. 

**Context**

**Detailed Description**
The permissions are set such that if you do not have the global group you cannot read the file: 

```
 ls -l /work2/noaa/global/wkolczyn/save/hpc-stack/modulefiles/stack/hpc/1.2.0.lua
-rw-r----- 1 wkolczyn global 587 May 24 18:21 /work2/noaa/global/wkolczyn/save/hpc-stack/modulefiles/stack/hpc/1.2.0.lua

```
**Additional Information**
This also effected Shan running P8 tag of global-workflow 

**Possible Implementation**
Need to open up permissions on module files.

**Comment by JessicaMeixner-NOAA** [comment]
Perhaps should be a new feature suggestion, but any chance modules like this could be added to a group account moving forward so if one person is on leave, someone else can make this change? I don't remember if orion has a group account capability yet, but we have them on hera where there's a similar module.

**Comment by WalterKolczynski-NOAA** [comment]
Permissions should be read-all now. Let me know if there are any further problems.

As for putting it under the group account:
- There is no such thing on Orion
- While it has lasted far longer than I wanted, this was only supposed to be a temporary hack until certain things were added to official stack installations. But, I think we are finally approaching the point where we won't need these at all.

**Comment by JessicaMeixner-NOAA** [comment]
Role accounts are now available on orion: https://oriondocs.rdhpcs.noaa.gov/wiki/index.php/Role_Accounts
