### ISSUE TITLE
feature/coupled-crow update reg2grb2.fd to be built with hpc-stack

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#169]
The ocean post in feature/coupled-crow, specifically  reg2grb2.fd  needs to be updated to use hpc-stack. 

The build script https://github.com/NOAA-EMC/global-workflow/blob/feature/coupled-crow/sorc/build_reg2grb2.sh uses the module files modulefiles/modulefile.reg2grb2.$target

**Comment by JessicaMeixner-NOAA** [comment]
hpc-stack wiki: https://github.com/NOAA-EMC/hpc-stack/wiki

**Comment by jiandewang** [comment]
modify modulefile.reg2grb2.orion, passed compiling, making testing run now

**Comment by jiandewang** [comment]
modify modulefile.reg2grb2.hera, test run successfully
