### ISSUE TITLE
Enable ensemble to run different coupled configuration

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#1692]
**Expected behavior**
`DO_OCN_ENKF` settings that control which coupled components run should properly set up a forecast run with the given settings, even if those settings are different from the deterministic model. (`DO_OCN` and `DO_OCN_ENKF` are used throughout this issue as a stand-in for all components.)

**Current behavior**
If the settings do not match the deterministic settings, the forecast directory will not be setup correctly.

**Machines affected**
All

**To Reproduce**
1. Create a warm-start cycled `S2S` experiment
2. Set `DO_OCN_ENKF` to `"NO"` (see Additional Information)
3. Observe the deterministic forecast succeed but the ensemble forecast fail

**Context**
`config.fcst` is setting several variables derived by `DO_OCN`, most notably the namelist variables (`cplflx`, `cplchm`, etc.). These are not then redefined after `config.efcs` modifies the `DO_OCN` variables to be the values determined by `DO_OCN_ENKF`.

Even before getting to the namelist, the derived values are used to determine which sections of the forecast script are executed, but _not_ what COM variables are set, so currently the job fails due to undefined COM variables before it even tries to run the forecast.

**Detailed Description**

**Additional Information**
As of bug submission time, all the `DO_OCN_ENKF` default to `"NO"` in `config.efcs`. However, I plan to comment out the overriding of `DO_OCN` in `config.efcs`, so the values of `config.fcst` are used until this is fixed.

Parts or all of this may be mooted by the refactor of the forecast job into python.

**Possible Implementation**
While we could just duplicate the definition of the derived variables, that seems like unnecessary code duplication. We need to rethink how we are doing this. The cleanest low-effort way would be to simply move the definitions out of the configs so they have the final settings before determining them.

Also, to update scripts to current workflow practices, the fortran booleans should not be used for logical branching within the shell scripts, instead using the `DO_OCN` variables.

**Comment by RussTreadon-NOAA** [comment]
Any updates on this issue and the related issue #1730?

**Comment by aerorahul** [comment]
To enable C384/C192 with coupled model, we need fix datasets with ocean at mx025 at C192.  As soon as those datasets are present, we should be able to remove the handicap in the workflow. 
There is no requirement or plans to run a dual resolution ocean in the global-workflow.  If that is a requirement, then we can open an issue and work on it separately.

**Comment by JessicaMeixner-NOAA** [comment]
Sanath has made the C192mx025. I'll post the location when I return from travel early next week.
