### ISSUE TITLE
RTDs for atmosphere-only AWS PW CSP

### ISSUE THREAD

**Issue by HenryRWinterbottom** [NOAA-EMC/global-workflow#1701]

**Comment by HenryRWinterbottom** [comment]
This will wait until after the GW presentation for configuring the NOAA CSPs for GW applications.

**Comment by WalterKolczynski-NOAA** [comment]
@HenryWinterbottom-NOAA I think this was completed. Would you please close if so?

**Comment by HenryRWinterbottom** [comment]
Closing as completed.
