### ISSUE TITLE
wrong directory name for ocean in archiving step 

### ISSUE THREAD

**Issue by jiandewang** [NOAA-EMC/global-workflow#1709]
**Expected behavior**
in coupled runs, ocean 2D, 3D and daily files should be archived to HPSS

**Current behavior**
they are not being saved to HPSS. 
**Machines affected**

**To Reproduce**
run current g-w in coupled mode

**Context**

**Detailed Description**
This is due to the wrong directory name in "hpssarch_gen.sh" script. See https://github.com/NOAA-EMC/global-workflow/blob/develop/ush/hpssarch_gen.sh#L262-L265
 I think this is because g-w had a major directories re-structure work couple of months ago. For ocean files they are catagoried as 

- model/ocean/history (where daily files are there)
- products/ocean/2D,  3D  (where 2D and 3D files are there)
but no corresponding modification were made in hpssarch_gen.sh

**Additional Information**

**Possible Implementation**

**Comment by WalterKolczynski-NOAA** [comment]
Daily files should be in `$COM_OCEAN_DAILY`, so the problem is where the files are generated, not in the archive script.

**Comment by jiandewang** [comment]
@WalterKolczynski-NOAA daily files are under model_data/ocean/history, they are from fcst step
