### ISSUE TITLE
missing several hours of output in ocean post

### ISSUE THREAD

**Issue by jiandewang** [NOAA-EMC/global-workflow#1710]
**Expected behavior**
Every 6hr ocean history files (or 3hr, depends on your output setting) should be processed by ocean post.

**Current behavior**
there are several being missed in the process

**Machines affected**

**To Reproduce**
run g-w under coupled mode

**Context**

**Detailed Description**
for example, if you set output frequency as 6, then hour 06, 12, 18, 24 ........ of output should be processed by ocean post. However, it always missed several of them. For my test case, it is missing hour 18, 48, 78, 84, 90 and 96. 

**Additional Information**
on HERA, 
cd /scratch1/NCEPDEV/stmp2/Jiande.Wang/S2S_RT/SW-problem/work-noWave-Fix/COMROOT/SW2013040100/logs/2013040100
grep great gfsocnpost_f000-f120.log
then you will see error like this:
jobs/rocoto/ocnpost.sh: line 59: ((: 018: value too great for base (error token is "018")

@JessicaMeixner-NOAA if you go to your ORION run log
/work2/noaa/marine/jmeixner/Lapenta2023/experiments/control/contorl2020091600/COMROOT/contorl2020091600/logs/2020091600
and do grep great *ocnpost*log, you will see the similar error (for your runs with 3hr output frequency)
**Possible Implementation**

**Comment by WalterKolczynski-NOAA** [comment]
This is a base error due to bash treating numbers with leading zeros as octals. Should be an easy fix. Will try to get to it by Monday.
