### ISSUE TITLE
PW_CSP host detection for global-workflow configuration.

### ISSUE THREAD

**Issue by HenryRWinterbottom** [NOAA-EMC/global-workflow#1713]
**Description**

The NOAA Cloud Service Providers (CSPs) are not detected automatically when configuring the workflow (via. `workflow/setup_expt.py`. 

**Requirements**

Determine if the respective NOAA CSP is a supported platform.

**Acceptance Criteria (Definition of Done)**

The respective NOAA CSP platform is detected.

**(Optional): Suggest A Solution**

Check whether the `PW_CSP` variable has been defined in the login environment and proceed accordingly.

**Comment by aerorahul** [comment]
closed via #1714
