### ISSUE TITLE
OCNRES incorrectly set for efcs when DO_OCN=NO

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/global-workflow#1730]
**Expected behavior**
The efcs jobs should run when submitted.

**Current behavior**
When cold starting a `DO_OCN=NO` parallel in which `CASE=C384` and `CASE_ENS=C192`, the initial efcs01 mem001 forecast aborts because the expected tiled orography files are not present in the run directory.   
```
133: FATAL from PE   133: MPP_OPEN:INPUT/C192_grid.tile1.nc does not exist.
 40: FATAL from PE    40: MPP_OPEN:INPUT/C192_grid.tile1.nc does not exist.
```
See log file `/scratch2/NCEPDEV/stmp1/role.jedipara/comrot/pratmos/logs/2021073106/enkfgdasefcs01.log.0`

**Machines affected**
Failure occurred on Hera but likely affects all machines.

**To Reproduce**
Cold start a `DO_OCN=NO` parallel with a C384 deterministic and C192 ensemble.

**Detailed Description**
`JGDAS_ENKF_FCST` sources `config.base`   Since `CASE=C384`, the following lines of `config.base` set `OCNRES=025`
```
    "C384")
        export OCNRES=025
        export waveGRD='glo_025'
```
While `config.efcs` contains 
```
if [[ ${DO_OCN} == "YES" ]]; then
  case "${CASE_ENS}" in
    "C48") export OCNRES=500;;
    "C96") export OCNRES=500;;
    "C192") export OCNRES=050;;
    "C384") export OCNRES=025;;
    "C768") export OCNRES=025;;
```
`OCNRES` is not reset to `050` because this parallel is running with `DO_OCN=NO`.   Thus, we retain the `config.base` setting of `OCNRES=025`

Later on `JGDAS_ENKF_FCST` resets `CASE` to `CASE_ENS`.   When `forecast_postdet.sh` is executed the following section
```
  OROFIX=${OROFIX:-"${FIX_DIR}/orog/${CASE}.mx${OCNRES}_frac"}
  FIX_SFC=${FIX_SFC:-"${OROFIX}/fix_sfc"}
  for n in $(seq 1 "${ntiles}"); do
    ${NLN} "${OROFIX}/oro_${CASE}.mx${OCNRES}.tile${n}.nc" "${DATA}/INPUT/oro_data.tile${n}.nc"
    ${NLN} "${OROFIX}/${CASE}_grid.tile${n}.nc"     "${DATA}/INPUT/${CASE}_grid.tile${n}.nc"
  done
```
sets `OROFIX` to `C192.mx025_frac`.   This directory does not exist in `FIX_DIR/orog`.   We have `C192` and `C192_mx050` in `fix/orog`.

**Possible Implementation**
As a kludge add the following to `JGDAS_ENKF_FCST`
```
 export CASE=${CASE_ENS}
+case "${CASE_ENS}" in
+    "C48") export OCNRES=500;;
+    "C96") export OCNRES=500;;
+    "C192") export OCNRES=050;;
+    "C384") export OCNRES=025;;
+    "C768") export OCNRES=025;;
+    *) export OCNRES=025;;
+esac
```

**This is NOT the long term solution.**  This is a temporary patch to run my parallel.

**Comment by RussTreadon-NOAA** [comment]
Tag @CoryMartin-NOAA, @andytangborn , and @jiaruidong2017 for awareness since they may run g-w with `DO_OCN=NO`.

**Comment by aerorahul** [comment]
@RussTreadon-NOAA 
We have been waiting for the necessary combinations (mappings) for the atmosphere-ocean grids.
Combine them with the lack of a proper configuration management, has lead to this.  
As you said, the kludge is not a long term solution, and so I don't think we will accept that in the `develop` branch.

**Comment by RussTreadon-NOAA** [comment]
@aerorahul , I definitely _**do not**_ want to see my kludge in `develop`.  It's a hokey patch to run my parallel configuration.  I opened the issue to report a bug and hopefully save others debug / troubleshooting time if they encounter the same problem.

Feel free to close or leave open this issue as you see fit.

**Comment by aerorahul** [comment]
@RussTreadon-NOAA 
Since we are not going to run with a different ocean and ice resolution in the ensemble for GFSv17, we could eliminate these:
https://github.com/NOAA-EMC/global-workflow/blob/develop/parm/config/gfs/config.efcs#L17C1-L28C52
I am not familiar about waves, but that is not working and will likely not be worked on for a while anyways.
I am fine with this as it restricts the configuration to one set between deterministic and ensemble for non-atmosphere (marine) components.
Would you be willing to try this?

**Comment by RussTreadon-NOAA** [comment]
I don't understand what you want me to try.   Do you want me to revert my local changes to `JGDAS_ENKF_FCST`, delete lines 17-28 of `config.efcs`, and rerun efcs?

**Comment by aerorahul** [comment]
Yes.

**Comment by RussTreadon-NOAA** [comment]
This doesn't work for my experiment.

When `JGDAS_ENKF_FCST` sources `config.base` it sets `OCNRES=025` for `CASE=C384`.   Later on `JGDAS_ENKF_FCST` resets `CASE=$CASE_ENS`.   Therefore, when `forecast_postdet.sh` runs it expands

`OROFIX=${OROFIX:-"${FIX_DIR}/orog/${CASE}.mx${OCNRES}_frac"}`

as

`OROFIX=${OROFIX:-"${FIX_DIR}/orog/C192.mx025_frac"}`

Directory `C192.mx025_frac` does not exist.   Directory `$OROFIX` currently contains

```
C1152             C192.mx050_frac  C384.mx025_frac  C768.mx025_frac  GlobalLakeDepth.dat                       thirty.second.antarctic.new.bin
C1152.mx025       C3072            C48              C96              GlobalLakeStatus.dat
C1152.mx025_frac  C3359            C48.mx500        C96.mx100        HGT.Beljaars_filtered.lat-lon.30s_res.nc
C128              C3445            C48.mx500_frac   C96.mx100_frac   geo_em.d01.lat-lon.2.5m.HGT_M.nc
C192              C384             C768             C96.mx500        gmted2010.30sec.int
C192.mx050        C384.mx025       C768.mx025       C96.mx500_frac   landcover30.fixed
```

**Comment by aerorahul** [comment]
Ok. Thanks.
We definitely need `C192.mx025` since the deterministic will be `C384.mx025` for "experimental" runs. 
For testing, the resolution pair is `C96.mx500` and `C48.mx500`.

I don't think this is a bug in the workflow, but rather a feature is being requested.  The workflow was never intended to support any random pair of resolutions in the coupled model.

**Comment by aerorahul** [comment]
@JessicaMeixner-NOAA @CatherineThomas-NOAA 
If the resolution pairs of `C384.mx025` and `C192.mx025` are to be supported for GFSv17 development, would it be possible to get the fixed files for the missing combinations?

**Comment by WalterKolczynski-NOAA** [comment]
Related: #1692

**Comment by RussTreadon-NOAA** [comment]
@CoryMartin-NOAA developed a different hack.   Instead of commenting [lines 17-27](https://github.com/NOAA-EMC/global-workflow/blob/develop/parm/config/gfs/config.efcs#L17-L27) of config.efcs, he only commented out the outer `if [[ ${DO_OCN} == "YES" ]]; then` block (lines 18 and 27).  This works and is preferable to my hack.

**Comment by JessicaMeixner-NOAA** [comment]
I believe we have all of the required fix file directories, including the C192mx025 which was mentioned as missing in an above commnet.  

The combinations we have in the orog are: 

5 deg ocean:  
C48.mx500    
C48.mx500_frac  
C96.mx500     
C96.mx500_frac        

1 deg ocean: 
C96.mx100     
 C96.mx100_frac   

1/4 deg ocean: 
C192.mx025   
C192.mx025_frac 
C384.mx025   
C384.mx025_frac  
C768.mx025_frac  
C768.mx025     
C1152.mx025  
C1152.mx025_frac  

And there are existing fix/cpl files for each of the above.  @aerorahul let me know if there are other things I need to check for.

**Comment by aerorahul** [comment]
@JessicaMeixner-NOAA 
In the above list, is 1 degree ocean with a C96 atmosphere.  
This is great, but it can't be used for cycling as we will need a C48 atmosphere with 1 deg. ocean as well.

C48.mx100 combination is not available to us and so the global-workflow cannot effectively support the 1 degree ocean resolution for cycling applications.  If 1 degree ocean applications are desired at C96/C48, we will need those fix files at C48.mx100.

**Comment by JessicaMeixner-NOAA** [comment]
@aerorahul thanks for this explanation.  It's my understanding that we were happy with having the 5deg ocean to support cycling development.  Please let me know if that's not the case and I can follow through with getting the C48.mx100

**Comment by aerorahul** [comment]
> @aerorahul thanks for this explanation. It's my understanding that we were happy with having the 5deg ocean to support cycling development. Please let me know if that's not the case and I can follow through with getting the C48.mx100

Just an update on this comment.
PSL is performing scout runs at `C96.mx100` with an atmosphere 3DVar and a coupled model (APP=S2S) at the moment.  They may update that to a 3DEnVar, for which they will need a `C48.mx100`.
