### ISSUE TITLE
Update gfs-land.yaml for snow DA cycling 

### ISSUE THREAD

**Issue by jiaruidong2017** [NOAA-EMC/global-workflow#1733]
To complete the PR #1687, the `gfs-land.yaml` in the fix `fv3jedi` directory need to be updated for the snow DA cycling in the global-workflow.

Please copy the file below:
`/scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.9/fv3-jedi/test/Data/fieldmetadata/gfs-land.yaml`
to replace:
`${FIX_DIR}/gdas/fv3jedi/20220805/fieldmetadata/gfs-land.yaml`

FIX_DIR can be found in sorc/link_workflow.sh for different platforms as below:

```
  "wcoss2")   FIX_DIR="/lfs/h2/emc/global/noscrub/emc.global/FIX/fix" ;;
  "hera")     FIX_DIR="/scratch1/NCEPDEV/global/glopara/fix" ;;
  "orion")    FIX_DIR="/work/noaa/global/glopara/fix" ;;
  "jet")      FIX_DIR="/lfs4/HFIP/hfv3gfs/glopara/git/fv3gfs/fix" ;;
  "s4")       FIX_DIR="/data/prod/glopara/fix" ;;
```
Since there are many changes in `fieldmetadata` and `fv3files`, you may want to update the `fv3jedi` link to a new date `yyyymmdd` by copy the following directories:

```
/scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.9/fv3-jedi/test/Data/fieldmetadata
/scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.9/fv3-jedi/test/Data/fv3files
```
to:
`${FIX_DIR}/gdas/fv3jedi/yyyymmdd/`

Please let me and @CoryMartin-NOAA know if you have any questions. Thanks.

**Tasks**

- [ ] Discuss needs with global-workflow developer assigned to request.
- [ ] Add/update/remove fix file(s) in fix sets on supported platforms (global-workflow assignee task).
- [ ] Update "Fix File Management" spreadsheet (https://docs.google.com/spreadsheets/d/1BeIvcz6TO3If4YCqkUK-oz_kGS9q2wTjwLS-BBemSEY/edit?usp=sharing).
- [ ] Make related workflow/component updates.

**Comment by CoryMartin-NOAA** [comment]
After talking with @aerorahul it seems that these should not be stored in the 'fix directory', but should be version controlled. This is a bigger issue than just `gfs-land`, so I'll close this and make a bigger PR to point to the repository instead soon.

@jiaruidong2017 this was updated in fv3-jedi, right? So I can pull from that for the GDASApp YAML PR that I will create.

**Comment by jiaruidong2017** [comment]
@CoryMartin-NOAA Yes, it was updated in fv3-jedi.

**Comment by jiaruidong2017** [comment]
The directory from global-workflow should be sorc/gdas.cd/fv3-jedi/test/Data/

**Comment by CoryMartin-NOAA** [comment]
@jiaruidong2017 are there any conflicts between gfs-land and gfs-restart? Meaning can we combine them? Or are there variables that are named differently depending on application?

**Comment by jiaruidong2017** [comment]
@CoryMartin-NOAA `gfs-land` was designed for land only DA and was separated from `gfs-restart`. I believe `gfs-land` and `gfs-restart` are not conflict. 

I checked the history and found the gfs-land were created from the [PR](https://github.com/JCSDA-internal/fv3-jedi/pull/480) on "Refactor the FieldMetadata class", in which the `FieldMetadata` class is significantly reorganized.
