### ISSUE TITLE
Metplus verification files not generated

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/global-workflow#1734]
**Expected behavior**
If `config.base` sets `DO_METP=YES`, gfs metplus jobs should create verification statistic files.

**Current behavior**
Metplus verification statistic files are not generated even though `DO_METP=YES` in `config.base`.

**Machines affected**
Found in a parallel running on Hera.  Likely impacts all machines.

**To Reproduce**
Install the global-workflow, set up a cycled experiment including 00Z gfs.   Start cycling.   00Z gfsmetp jobs will run and finish with error code 0 but no verification statistic files will be created.

**Detailed Description**
A global parallel on Hera was not creating metp verification files.  Investigation of the problem found that variable `FIXverif` was being incorrectly set by `ush/run_verif_global_in_global_workflow.sh`.   The script set 
```
export FIXverif_global=$FIXgfs/fix_verif
```
The `fix_verif` pathname is wrong.    global-workflow commit [`e7f72e8b`](https://github.com/NOAA-EMC/global-workflow/commit/e7f72e8b6e3f4244465bbfb077f00bc4d7610739#diff-d5dc1af75ff685072f5162e81440008320fe66bce26d17bd5e143ce2d3a0aa7a) removed the `fix_` prefix from the pathname in `sorc/link_workflow.sh`.    The link script now links verification fix files to `FIXgfs/verif`.

The `FIXverif_global` path in `ush/run_verif_global_in_global_workflow.sh` was updated in `EMC_verif-global` at [`670d692`](https://github.com/NOAA-EMC/EMC_verif-global/commit/670d6929faaeb237a7a49875acb2ba76781a04f5).   This hash was committed February 27, 2023.

The current head of global-workflow `develop` ([`84842f4`](https://github.com/NOAA-EMC/global-workflow/commit/84842f455da5dfc976eda21336ae383616ac96d0)) checks out `EMC_verif-global` at  [`c267780`](https://github.com/NOAA-EMC/EMC_verif-global/commit/c267780a1255fa7db052c745cf9c78b7dc6a2695).   This hash is dated April 25, 2022.   

**Possible Implementation**
Update `sorc/checkout.sh` to checkout a snapshot of `EMC_verif-global` which includes the correct `FIXverif_global` path in `ush/run_verif_global_in_global_workflow.sh`.    For example, update `sorc/checkout` to check out [`670d692`](https://github.com/NOAA-EMC/EMC_verif-global/commit/670d6929faaeb237a7a49875acb2ba76781a04f5) for `EMC_verif-global`.   Better yet, consult with @malloryprow to identify the correct `EMC_verif-global` hash or tag to checkout for use in the global workflow.

**Comment by kevindougherty-noaa** [comment]
Adding to this thread that the most current develop branch of `global-workflow` ([4b5cd0b](https://github.com/NOAA-EMC/global-workflow/commit/4b5cd0bc435fc158258ca38c3d5f44add6b60469)) still has this issue.

Output from a `gfsmetpg2g1.log` file shows:
```FIXverif_global=/scratch1/NCEPDEV/stmp2/Kevin.Dougherty/global-workflow-exp3/fix/fix_verif```

This creates issues which echo's @RussTreadon-NOAA statements above.

The current hash for EMC_verif-global is still [c267780](https://github.com/NOAA-EMC/EMC_verif-global/commit/c267780a1255fa7db052c745cf9c78b7dc6a2695) in `sorc/checkout.sh`.

**Comment by RussTreadon-NOAA** [comment]
Should or can we close this issue?

**Comment by DavidHuber-NOAA** [comment]
This will be fixed by https://github.com/NOAA-EMC/global-workflow/pull/2239.  I will add this issue to that PR's description.

**Comment by malloryprow** [comment]
Almost there to having the stats in the workflow again!! :D :D :D

**Comment by malloryprow** [comment]
Everything should be good to go with https://github.com/NOAA-EMC/global-workflow/pull/2239 merged.
