### ISSUE TITLE
Work with Walter Kolczynski to stage fixed files on NOAA CSPs

### ISSUE THREAD

**Issue by HenryRWinterbottom** [NOAA-EMC/global-workflow#1745]

**Comment by HenryRWinterbottom** [comment]
@WalterKolczynski-NOAA or @aerorahul Can you point me to where the default files that the global-workflow uses (are these the regression test files) are that need to be staged on the CSPs?

I have the fixed files in place. I still need to confirm with Unni whether what I am doing is usable by other groups (I think that it is).

**Comment by WalterKolczynski-NOAA** [comment]
```
/scratch1/NCEPDEV/global/glopara/data/ICSDIR
```

Note for aerosol experiments, you'll also need the other directory in `data` (`gocart_emissions`).

**Comment by HenryRWinterbottom** [comment]
@WalterKolczynski-NOAA OK, great and thank you.

I'll get these staged tomorrow so we can close this out.

**Comment by WalterKolczynski-NOAA** [comment]
Hold of on the emissions data. I think we need to go through it a bit to cut it down a little bit at least.

**Comment by HenryRWinterbottom** [comment]
@WalterKolczynski-NOAA OK, no problem. I will just copy the other files.

**Comment by HenryRWinterbottom** [comment]
@WalterKolczynski-NOAA I found the `AERO_DIR` in `parm/config` but I cannot find a similar directory for which to point to the files I staged to NOAA CSP AWS in `parm/config`, `workflow/hosts`, or in the `sorc/ufs_model.fd` tree. 

Where is the ICSDIR path and fixed-file path for the respective hosts defined?

**Comment by WalterKolczynski-NOAA** [comment]
`ICSDIR` is specified on the command line when you create an experiment, except for forecast-only, which is set by `BASE_CPLIC` in `workflow/hosts/<machine>.yaml`.

**Comment by HenryRWinterbottom** [comment]
All files are stages; will open a PR such that the GW knows where to find them.

**Comment by HenryRWinterbottom** [comment]
Completed.
