### ISSUE TITLE
SDATE_GFS written to xml using incorrect format

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/global-workflow#1748]
**Expected behavior**
The global-workflow generated rocoto xml should specify `SDATE_GFS` in the `gfsmetp` section as `YYYYMMDDHH`.  For example,
```
                <envar><name>DATAROOT</name><value>/scratch2/NCEPDEV/stmp1/role.jedipara/RUNDIRS/pratmos</value></envar>
                <envar><name>SDATE_GFS</name><value>2021080100</value></envar>
                <envar><name>METPCASE</name><value>#metpcase#</value></envar>
```

**Current behavior**
The global-workflow generated rocoto xml currently specifies `SDATE_GFS` in the `gfsmetp` section as `YYYY-MM-DD HH:mm:ss`.   For example,
```
                <envar><name>DATAROOT</name><value>/scratch2/NCEPDEV/stmp1/role.jedipara/RUNDIRS/pratmos</value></envar>
                <envar><name>SDATE_GFS</name><value>2021-08-01 00:00:00</value></envar>
                <envar><name>METPCASE</name><value>#metpcase#</value></envar>

```

**Machines affected**
Discovered on Hera.  Likely impacts all machines.

**To Reproduce**
Clone and install g-w `develop`.  Set up a cycled experiment including 00Z gfs.  Generate the experiment xml by executing g-w `workflow/setup_xml.py`.   Check `SDATE_GFS` in the `gfsmetp` section of the generated xml file. 

**Possible Implementation**
As a test, make the following change to g-w `workflow/rocoto/gfs_tasks.py`

```
diff --git a/workflow/rocoto/gfs_tasks.py b/workflow/rocoto/gfs_tasks.py
index 4d283ddf..ff973a68 100644
--- a/workflow/rocoto/gfs_tasks.py
+++ b/workflow/rocoto/gfs_tasks.py
@@ -890,7 +890,8 @@ class GFSTasks(Tasks):
         dependencies = rocoto.create_dependency(dep_condition='and', dep=deps)

         metpenvars = self.envars.copy()
-        metpenvar_dict = {'SDATE_GFS': self._base.get('SDATE_GFS'),
+        sdate_gfs = self._base.get('SDATE_GFS')
+        metpenvar_dict = {'SDATE_GFS': sdate_gfs.strftime("%Y%m%d%H"),
                           # TODO - in Forecast-only, this is `SDATE` on the RHS
                           'METPCASE': '#metpcase#'}
         for key, value in metpenvar_dict.items():
```

This change converts `SDATE_GFS` to `YYYYMMDDHH` format in the metp environment variable dictionary.

Tested this change in a Hera `EXPDIR` with the result being
```
                <envar><name>DATAROOT</name><value>/scratch2/NCEPDEV/stmp1/role.jedipara/RUNDIRS/prgsi</value></envar>
                <envar><name>SDATE_GFS</name><value>2021080100</value></envar>
                <envar><name>METPCASE</name><value>#metpcase#</value></envar>
```

**Comment by RussTreadon-NOAA** [comment]
Tagging @malloryprow for awareness.   We have two g-w metp bug issues.   This issue (#1748) and #1734.

**Comment by malloryprow** [comment]
Yes, thank you @RussTreadon-NOAA! I'm busy with EVS as we push through the Beta test, but hopefully the global workflow team and I can work through these issues. Could you comment as to the urgency/priority on them?

**Comment by RussTreadon-NOAA** [comment]
Issue #1734 is more serious.   The wrong `EMC_verif-global` hash is cloned by g-w `develop`.  As a result metp verification files are not created.

Issue #1748 generates run time errors when `run_verif_global_in_global_workflow.sh` is executed.   For example,
```
+ run_verif_global_in_global_workflow.sh[145]: '[' 2021080200 -le 2021-08-01 ']'
/scratch1/NCEPDEV/da/role.jedipara/git/global-workflow/test0/sorc/verif-global.fd/ush/run_verif_global_in_global_workflow.sh: line 145: [: 2021-08-01: integer expression expected
```
I didn't dig into the impact but it's disturbing seeing error messages which should not be present.
