### ISSUE TITLE
Typo in the cice history link

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/global-workflow#1760]
https://github.com/NOAA-EMC/global-workflow/blob/14cca3879ef6b3ec748d9bebefd9acbd68967d35/ush/forecast_postdet.sh#L958

**Comment by aerorahul** [comment]
@guillaumevernieres 
Can you highlight the typo so we can fix it. Is it the extra `-` after the `.` in the RHS filename?

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres Can you highlight the typo so we can fix it. Is it the extra `-` after the `.` in the RHS filename?

@aerorahul , you need to remove the `-`

**Comment by aerorahul** [comment]
Got it.
Thanks. Will remove `-` shortly.
Have you tested with this change and found the outcome acceptable; i.e. did you encounter any other issues related to this change?

**Comment by guillaumevernieres** [comment]
> Got it. Thanks. Will remove `-` shortly. Have you tested with this change and found the outcome acceptable; i.e. did you encounter any other issues related to this change?

The change fixes the issue, we've been running with it for a while now. Thanks for taking care of this and sorry for not submitting a bugfix!
