### ISSUE TITLE
Update global_cycle for fractional grid

### ISSUE THREAD

**Issue by CatherineThomas-NOAA** [NOAA-EMC/global-workflow#1775]
**Description**
Global_cycle within the global-workflow does not currently support fractional grids.  There is an issue ([#549](https://github.com/ufs-community/UFS_UTILS/issues/549)) and draft PR ([#815](https://github.com/ufs-community/UFS_UTILS/pull/815)) within UFS_UTILS to address this gap.  This issue is a placeholder for any needed global-workflow changes to accompany that PR.

**Requirements**
Must be able to run in the deterministic as well as the ensemble portion of cycled mode.

**Acceptance Criteria (Definition of Done)**
Being able to run global_cycle with frac grid on from within the global-workflow in cycled mode (ATM-only, hybrid 4DEnVar) without failure and using the scientifically correct fields in its computations.

**Comment by WalterKolczynski-NOAA** [comment]
I thought global_cycle wasn't being retired.

**Comment by CatherineThomas-NOAA** [comment]
Correct, global_cycle isn't being retired.  It currently runs without failure, but it's not running correctly when fractional grid is on.  The UFS_UTILS PR should fix that.  It's unclear (to me) at the moment whether there will need to be any additional changes in the workflow other than hash updates, which is what I'm hoping to capture with this issue.

**Comment by WalterKolczynski-NOAA** [comment]
Sorry, I meant I thought it _was_ being retired.

**Comment by CatherineThomas-NOAA** [comment]
@WalterKolczynski-NOAA  Are you thinking of GLDAS?  GLDAS will no longer be used in GFSv17, but global_cycle will still be needed to update the surface restarts.

**Comment by WalterKolczynski-NOAA** [comment]
Probably.

**Comment by aerorahul** [comment]
@CatherineThomas-NOAA @GeorgeGayno-NOAA 
I have started a test on Hera and Orion that checks out the branch in the ufs-utils PR 815.  
If there is any other customization needed, please let me know what needs to be changed and where.
This test will run the stock 3DVar and H4DEnVar cycled tests at C96 and C96/C48 resolutions.

**Comment by aerorahul** [comment]
@CatherineThomas-NOAA 
This was run in the CI in PR #1818 with the tests mentioned in the acceptance criteria on Hera. 
Both tests passed (as in there was no failure).
The science teams will need to verify the scientific validity of the results.
Please let me know if there is anything else I can do in this ticket, else I will close this ticket.
When the ufs-utils PR is merged into `develop`, please let us know and we can open an issue to update its hash in global-workflow.

**Comment by KateFriedman-NOAA** [comment]
@CatherineThomas-NOAA Is this complete and/or moot? We've moved to a new UFS_UTILS hash since this and the fix files were reorganized in such a way to (I think) make your changes (https://github.com/CatherineThomas-NOAA/global-workflow/commit/7ed8d0e848dd2245d8b3097cd597ed70d2839925) moot. Please confirm, thanks!

**Comment by CatherineThomas-NOAA** [comment]
@KateFriedman-NOAA 
This issue needs to stay open but is very close to complete.  You're right that most of the changes in that commit of the fork are no longer needed with the fix file reorg.  

We will still need an update to remove the hack to skip global_cycle ([ush/forecast_postdet.sh](https://github.com/NOAA-EMC/global-workflow/blob/3d44ff38c5c3324c22fc104fe3259b4ac864c6d6/ush/forecast_postdet.sh#L36)) as well as update to the latest UFS_UTILS hash.  While g-w did update the hash since this issue was created, we need the changes from PR [#815](https://github.com/ufs-community/UFS_UTILS/pull/815) and [#891](https://github.com/ufs-community/UFS_UTILS/pull/891), which are more recent.

I'm currently just waiting for one last check on my latest test and we'll be good to go.

**Comment by KateFriedman-NOAA** [comment]
Sounds good @CatherineThomas-NOAA ! Thanks for the status update! :)
