### ISSUE TITLE
Fix IC staging bug: should be `idatestr` not `rdatestr`

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/global-workflow#1783]
I think this was supposed to be `idatestr` not `rdatestr`. If you create cold start ICs from ufs_utils, there won't be a rdate directory.

_Originally posted by @CoryMartin-NOAA in https://github.com/NOAA-EMC/global-workflow/pull/1529#discussion_r1279629435_

**Comment by DavidHuber-NOAA** [comment]
For warm starts, atm data is linked from the previous cycle, so you would want `rdatestr` for those.  For cold starts, we should be looking at `idatestr`.  I have a branch with this fix in place.  So far I have only tested it for cold starts, but I will test it for warm starts as well before opening a PR.

**Comment by DavidHuber-NOAA** [comment]
While testing this for warm starts, I encountered errors for missing increment files (ensemble `ratmi*.nc` and deterministic `atmi*.nc` and `atminc.nc`).  Reading through the `setup_expt.py` script, only a handful of files are linked from the source ICs' `analysis/atmos/` directories (`abias`, `abias_pc`, `abias_air`, and `radstat`), but additional files are needed to support `IAU`.

@WalterKolczynski-NOAA Is there a reason I would not want to link in the entirety of the analysis/atmos/ directory from the warm start ICs (i.e. calling `link_files_from_src_to_dst`)?

**Comment by WalterKolczynski-NOAA** [comment]
I think we'd rather have an explicit list. That way you only copy what you need and also know if something is missing. @aerorahul?

**Comment by aerorahul** [comment]
There are 3 ways to start the atmosphere:
1. cold start
2. warm start w/o IAU
3. warm start w/ IAU

1 is the way most (99%) of developers start their experiment (generate cold start ICs offline from ops).

2 is also functional if someone wants to start from warm start ICs but no IAU.

For 3; I think there are blockers in the forecast scripts that will prevent doing this; i.e. IAU is turned off for the first half cycle (I will need to check to be sure)

Is 3 a mode we want to support?  Yes.  Is it high on the priority list?  Probably not worth the effort ATM.

**Comment by DavidHuber-NOAA** [comment]
@aerorahul Noted, thanks.  I will continue my warm-start testing with IAU turned off then.
