### ISSUE TITLE
Include Wave in CI testing for forecast only GFSv17 targeted tests 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#1794]
**Description**
Currently none of the CI tests include wave.  According to comment https://github.com/NOAA-EMC/global-workflow/pull/1653#issuecomment-1565098143 waves were going to be included in low resolution tests.  Details about ICs are in  https://github.com/NOAA-EMC/global-workflow/pull/1653 and if other dates are requested, that can be accommodated. 

**Requirements**
Waves should be included in CI testing for free forecasts (cycled will be separate issue after feature is working, unclear if it is at this time). 

**Acceptance Criteria (Definition of Done)**
Waves are included in CI tests targeted to test forecast only capabilities for GFSv17. 

**(Optional): Suggest A Solution**

**Comment by TerrenceMcGuinness-NOAA** [comment]
New case file [C48_S2SW.yaml](https://github.com/TerrenceMcGuinness-NOAA/global-workflow/blob/CI_C384_S2W_test/ci/cases/C48_S2SW.yaml) was introduced and tested, but more SME decisions need to be made on specifics regarding resolutions used.

**Comment by JessicaMeixner-NOAA** [comment]
@TerrenceMcGuinness-NOAA great news on C48_S2SW.  I provided information about C384 test in the PR that was [closed](https://github.com/NOAA-EMC/global-workflow/pull/1825#issuecomment-1699694024).    For general workflow testing the C48 resolution was provided.  I also provided the information for C384 using the glo_025 grid which GEFS will be using.  For GFS targeted operational resolution, that is in flux and will be moving to the unstructured grid which is not yet in the workflow.  Please let me know what other questions you have and I'd be happy to answer them and provide ICs for anything that is needed.  It takes me about 2 days to get the ICs ready (mostly just my time wise).

**Comment by JessicaMeixner-NOAA** [comment]
> New case file [C48_S2SW.yaml](https://github.com/TerrenceMcGuinness-NOAA/global-workflow/blob/CI_C384_S2W_test/ci/cases/C48_S2SW.yaml) was introduced and tested, but more SME decisions need to be made on specifics regarding resolutions used.

@TerrenceMcGuinness-NOAA   @aerorahul  Is the information I provided above sufficient or are there additional details you need from me?

**Comment by JessicaMeixner-NOAA** [comment]
> @TerrenceMcGuinness-NOAA great news on C48_S2SW. I provided information about C384 test in the PR that was [closed](https://github.com/NOAA-EMC/global-workflow/pull/1825#issuecomment-1699694024). For general workflow testing the C48 resolution was provided. I also provided the information for C384 using the glo_025 grid which GEFS will be using. For GFS targeted operational resolution, that is in flux and will be moving to the unstructured grid which is not yet in the workflow. Please let me know what other questions you have and I'd be happy to answer them and provide ICs for anything that is needed. It takes me about 2 days to get the ICs ready (mostly just my time wise).


Copying some information referenced above: 

two cases that will run out of the box on hera.  For orion you will have to move the IC created for the C384 case to the staged location.  This file is: 
/scratch1/NCEPDEV/climate/role.ufscpara/IC/GEFSwave20210528v2/2016070100/wav/glo_025/20160701.000000.restart.glo_025

I believe this becomes a yaml file /ci/cases/C48_S2SW.yaml as 
```
experiment:
  type: gfs
  mode: forecast-only

arguments:
  pslot: ${pslot}
  app: S2SW
  resdet: 48
  comrot: ${RUNTESTS}/COMROT
  expdir: ${RUNTESTS}/EXPDIR
  idate: 2021032312
  edate: 2021032312
  yaml: ${HOMEgfs_PR}/ci/platforms/gfs_defaults_ci-updates.yaml
```

and a file /ci/cases/C384_S2SWA.yaml as 
```
experiment:
  type: gfs
  mode: forecast-only

arguments:
  pslot: ${pslot}
  app: S2SWA
  resdet: 384
  comrot: ${RUNTESTS}/COMROT
  expdir: ${RUNTESTS}/EXPDIR
  idate: 2016070100
  edate: 2016070100
  yaml: ${HOMEgfs_PR}/ci/platforms/gfs_defaults_ci-updates.yaml
```

although I'm not sure about the yaml line. 

Tests were completed on hera (not via ci) and output can be seen here: 

**G-w clone:**(of develop): /scratch1/NCEPDEV/climate/Jessica.Meixner/gwtests/global-workflow
**C48 output:** /scratch1/NCEPDEV/climate/Jessica.Meixner/gwtests/s2swc48t02
**C48 helper script which contains exp setup info**:  /scratch1/NCEPDEV/climate/Jessica.Meixner/gwtests/global-workflow/workflow/coupled_48.sh
**C384 output**: /scratch1/NCEPDEV/climate/Jessica.Meixner/gwtests/s2swaC384
**C384 helper script which contains exp setup info**: /scratch1/NCEPDEV/climate/Jessica.Meixner/gwtests/global-workflow/workflow/coupled_384.sh

Copying some information from the helper scripts here:  
For the C48 test the commands I ran are: 

```
APP=S2SW
PSLOT=s2swc48t02
BASEDIR=/scratch1/NCEPDEV/climate/Jessica.Meixner/gwtests
CDUMP=gfs #gfs or gefs
CONFIGDIR=$BASEDIR/global-workflow/parm/config/${CDUMP}
IDATE=2021032312
EDATE=2021032312
RES=48
GFS_CYC=1
COMROT=$BASEDIR/$PSLOT/COMROOT
EXPDIR=$BASEDIR/$PSLOT/EXPDIR

echo "Hera modules:"
echo "module use ${BASEDIR}/global-workflow/modulefiles"
echo "module load module_gwsetup.hera"

echo " "
echo "Set up script"
echo ./setup_expt.py ${CDUMP} forecast-only --app $APP --pslot $PSLOT --configdir $CONFIGDIR --idate $IDATE --edate $EDATE --res $RES --gfs_cyc $GFS_CYC --comrot $COMROT --expdir $EXPDIR 

echo " "
echo "setup workflow after any changes:"
#echo ./setup_workflow_fcstonly.py --expdir $EXPDIR/$PSLOT
echo "./setup_xml.py $EXPDIR/$PSLOT"
```

and for C384: 
```
APP=S2SWA
PSLOT=s2swaC384
BASEDIR=/scratch1/NCEPDEV/climate/Jessica.Meixner/gwtests
CDUMP=gfs #gfs or gefs
CONFIGDIR=$BASEDIR/global-workflow/parm/config/${CDUMP}
IDATE=2016070100
EDATE=2016070100
RES=384
GFS_CYC=1
COMROT=$BASEDIR/$PSLOT/COMROOT
EXPDIR=$BASEDIR/$PSLOT/EXPDIR


echo " "
echo "Set up script"
echo ./setup_expt.py ${CDUMP} forecast-only --app $APP --pslot $PSLOT --configdir $CONFIGDIR --idate $IDATE --edate $EDATE --res $RES --gfs_cyc $GFS_CYC --comrot $COMROT --expdir $EXPDIR 

echo " "
echo "setup workflow after any changes:"
#echo ./setup_workflow_fcstonly.py --expdir $EXPDIR/$PSLOT
echo "./setup_xml.py $EXPDIR/$PSLOT"

echo " " 
echo "crontab:" 
echo $EXPDIR/$PSLOT/$PSLOT.crontab
```


Lastly the above work was done with the commit from August 28th, although I would not anticipate a reason this could not run with the latest develop.
