### ISSUE TITLE
Task gdafcst failed on C384 snow DA cycling run

### ISSUE THREAD

**Issue by jiaruidong2017** [NOAA-EMC/global-workflow#1796]
I'm running the C384 snow DA cycling tests, and the run starts at t18z 2011-10-30. When running to the t00z 2011-11-07, the task `gdasfcst` failed with the following error messages:

```
++ forecast_predet.sh[71]: date -d '20211107 00 + 6 hours' +%Y%m%d%H
+ forecast_predet.sh[71]: next_cycle=2021110705
++ forecast_predet.sh[72]: date -d '20211107 00 + 9 hours' +%Y%m%d%H
+ forecast_predet.sh[72]: forecast_end_cycle=2021110708
```
```
++ forecast_postdet.sh[508]: date -d '20211107 00 + 6 hours' +%Y%m%d%H
+ forecast_postdet.sh[508]: local idate=2021110705
```
It should produce the `local idate=2021110706`. All previous `gdasfcst` tasks work successfully. The log file is  at `/scratch1/NCEPDEV/ctb/Jiarui.Dong/ptmp/landid9/logs/2021110700/gdasfcst.log` on hera.

**Comment by aerorahul** [comment]
@jiaruidong2017 
I think I know this issue.
Nov 7 2021 is when the DST starts and as a result, you are noticing the hour lost when you cross 2 hours past midnight.

The fix to this is to use the `-u` with the `date` command.  Without the `-u`, the `date` command uses the local timezone.

This needs to be fixed everywhere the `date` command is being used.

**Comment by jiaruidong2017** [comment]
It makes sense. Thanks @aerorahul for the detailed explanation.
