### ISSUE TITLE
Add hybrid option to UFS-DA ATM variational analysis

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/global-workflow#1799]
**Description**
GSI based atmospheric DA can augment static B with an ensemble to produce a hybrid-variational (hybvar) analysis.  The same capability should exist for variational atmospheric UFS-DA.   Attempts to execute UFS-DA in hybvar mode failed.   The `gdasatmanlinit` job does not populate the run directory with ensemble members.   This option needs to be added to atmospheric analysis scripts in `ush/python/pygfs/task`.  

**Requirements**
Extend atmospheric analysis python scripts to include the option to copy specified ensemble members to the run directory when `gdasatmanlinit` is run.  Additional changes may also be needed to correctly construct a yaml file to run `fv3jedi_var.x` in hybvar mode.

**Acceptance Criteria (Definition of Done)**
`gdasatmanlrun` can run atmospheric UFS-DA in 3dvar (static-B only) or hybvar (static-B plus ensemble) mode.

**Comment by RussTreadon-NOAA** [comment]
`scripts/exgdas_global_atmos_analysis_run.sh` at [70a7d99b](https://github.com/NOAA-EMC/global-workflow/blob/70a7d99bb65fd7661d7d2bac10633c0dda5d39fd/scripts/exgdas_global_atmos_analysis_run.sh) included the following section to populate the run directory with ensemble members when running the variational analysis in hybrid mode

```
# optionally link ensemble backgrounds to $DATA
if [ $DOHYBVAR = "YES" ]; then
   mkdir -p $DATA/ens
   fhrs="06"
   if [ $l4densvar = ".true." ]; then
      fhrs="03 04 05 06 07 08 09"
   fi

   for imem in $(seq 1 $NMEM_ENKF); do
      memchar="mem"$(printf %03i $imem)
      for fhr in $fhrs; do
         $NLN ${COMIN_GES_ENS}/$memchar/atmos/RESTART $DATA/ens/$memchar
      done
   done

fi
```
A python equivalent needs to be added to atmospheric scripts in `ush/python/pygfs/task`

**Comment by aerorahul** [comment]
@RussTreadon-NOAA 
Please consider a yaml-approach in addition to updates in the python.
If you have questions, please coordinate with me.

**Comment by RussTreadon-NOAA** [comment]
@aerorahul , not sure what you mean by a _yaml approach_.   The config files already contain switches to turn on/off the hybvar option.   My simple minded approach was to have the python scripts query these variables and act accordingly.

**Comment by aerorahul** [comment]
The basic requirement is to copy a set of ensemble members for various times within the window from `COM` into `DATA`.

Consider defining this `dict` in the yaml using jinja-based templating.
The python code would then read and load this templated yaml, resolve it with `parse_j2tmpl`, and call `FileHandler.sync()`.
I think the python code does this already to some degree.

**Comment by RussTreadon-NOAA** [comment]
OK.  I was thinking of adding a hybrid option to method `get_berror_dict` in `atm_analysis.py`.   I'm hoping that if I properly construct the dictionary the following section of `initialize` 
```
        # stage berror files
        # copy static background error files, otherwise it will assume ID matrix
        logger.debug(f"Stage files for STATICB_TYPE {self.task_config.STATICB_TYPE}")
        FileHandler(self.get_berror_dict(self.task_config)).sync()
```
will create and populate `ens/mem*` directories with the correct files.

**Comment by RussTreadon-NOAA** [comment]
Create forked branch `[feature/ufsda_hybvar](https://github.com/RussTreadon-NOAA/global-workflow/tree/feature/ufsda_hybvar)` as a copy of `develop` at [`8b19f42`](https://github.com/RussTreadon-NOAA/global-workflow/commit/8b19f4217e2b200b3ea3995d0038acdce19e6a6b).

Updates required to stage ensemble members for use in hybrid background error will be committed to `feature/ufsda_hybvar`.
