### ISSUE TITLE
Orion staged IC does not match hera 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#1800]
**Description**

 While not a "fix" file, I believe g-w team members manage the staged ICs on orion.  

The file /work/noaa/global/glopara/data/ICSDIR/prototype_ICs/HR1/2019120300/wav/mx025/20191203.000000.restart.mx025 
does not match the file on hera: 
/scratch1/NCEPDEV/climate/role.ufscpara/IC/HR1/2019120300/wav/mx025/20191203.000000.restart.mx025 

(This was copied to orion here: /work2/noaa/marine/jmeixner/hr2/IC/HR1/2019120300/wav/mx025/20191203.000000.restart.mx025 if that's helpful).  

Can this be updated? It's low priority but would be helpful at some point.  If this is the incorrect place to report this, please let me know. 

**Tasks**

- [ ] Discuss needs with global-workflow developer assigned to request.
- [ ] Add/update/remove fix file(s) in fix sets on supported platforms (global-workflow assignee task).
- [ ] Update "Fix File Management" spreadsheet (https://docs.google.com/spreadsheets/d/1BeIvcz6TO3If4YCqkUK-oz_kGS9q2wTjwLS-BBemSEY/edit?usp=sharing).
- [ ] Make related workflow/component updates.

**Comment by WalterKolczynski-NOAA** [comment]
HR1 20191203 should be synchronized now.

**Comment by JessicaMeixner-NOAA** [comment]
Thanks @WalterKolczynski-NOAA I see no diffs now!
