### ISSUE TITLE
namelist updates for CICE and CMEPS required from UFS-WM

### ISSUE THREAD

**Issue by DeniseWorthen** [NOAA-EMC/global-workflow#1810]
**Description**

Changes  from UWM PR [1752](https://github.com/ufs-community/ufs-weather-model/pull/1752) and PR [1842](https://github.com/ufs-community/ufs-weather-model/pull/1842) need corresponding updates in the G-W.

1. In ``ice_in``, a variable is add to control the diagnostic output recorded by CICE in the ``ice_diag.d`` file. The value is expressed  in number of timesteps, and will therefore depend on the the CICE timestep. In UWM, it is set to the timestep equivalent of ``fhmax``.

-  [ice_in_template](https://github.com/ufs-community/ufs-weather-model/blob/0eee0a8017517de0455d7e75ae14b11d43ff857d/tests/parm/ice_in_template#L28)

2. Settings used to set the mediator history file options are removed from the ``nems.configure`` file for the global coupled applications. These settings are only used if a specific phase (``med_phases_history_write``) is present in the run sequence. This phase was used only for diagnostic and debugging and has in any case been super-ceded by the ability to write mediator history files (if desired) via a configuration variable and not an additional run phase. In ``nems.confgure``, two changes are required:

- Any instance of ``med_phases_history_write`` should be removed

- The following variables can be removed

```
      history_n = 1
      history_option = nhours
      history_ymd = -999
```

3. In ``nems.configure``, an new parameter is needed to control the PIO settings used by CMEPS. This is required because the default settings within CMEPS were changed.  The ``pio_rearranger`` setting should be set to ``box``:

- [nems.configure.cpld](https://github.com/ufs-community/ufs-weather-model/blob/0eee0a8017517de0455d7e75ae14b11d43ff857d/tests/parm/nems.configure.cpld.IN#L127)

4. A feature was added to CMEPS to optionally check for NaNs in export field bundles. This behaviour is controlled via namelist (not enabled currently) and requires the addition of the following to the CMEPS ``CMakeList.txt``

- [CMakeList.txt](https://github.com/ufs-community/ufs-weather-model/blob/251ec56df56d987fe3a2ba900d9a22b95e2058de/CMEPS-interface/CMakeLists.txt#L34)

**Requirements**

**Acceptance Criteria (Definition of Done)**

**Dependencies**

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen thank you for posting this.  I looked through a few of these items and found: 

1 https://github.com/NOAA-EMC/global-workflow/blob/develop/ush/parsing_namelists_CICE.sh#L75 looks like diagfreq is hard coded to 6, which doesn't seem to be a correct value if this depends on the ice timestep.    Where is the calculation of diag_freq in rt.sh? 

2 is partially addressed as there are not instances of med_phases_history_write in nems.configure files used in global-workflow but the history_* options do still exist 

3 is addressed in https://github.com/NOAA-EMC/global-workflow/pull/1805

**Comment by DeniseWorthen** [comment]
In rt.sh, we use ``export DIAG_FREQ=`expr $FHMAX \* 3600 / $DT_CICE``. I would suggest setting it in the G-W to the equivalent of 1x/day. That way, assuming anyone ever wants to look at the file, it would contain useful information. The diagnostics contain values such as the hemispheric ice volume etc.

**Comment by aerorahul** [comment]
I think we got this in multiple places; most recently from using the ice_in.IN template.

**Comment by JessicaMeixner-NOAA** [comment]
Actually @aerorahul the comment from Denise answers our question from Friday that we should update DIAG_FREQ to be 1x per day!  I will put this in a PR I am working on to update the model.    Just need to figure out what the correct expression would be to be the equivalent of 1x per day.
