### ISSUE TITLE
Test cases for JEDI DA configurations

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/global-workflow#1821]
**Description**
A lot of new and exciting JEDI DA features have been added in the past few months.
JEDI-based DA for atmosphere with and without ensemble
JEDI-based DA for snow updates
JEDI-based DA for aerosol updates
JEDI-based DA for ocean and sea-ice

We would like to ensure that these capabilities are tested regularly with every update of the system where relevant.  For e.g. an update in the ufs-weather-model hash would trigger all tests, but a change in the land_analysis will only likely impact snow DA, but that will be deferred to the SME.

**Requirements**
The developers of these systems should provide and maintain a cycled test case for each of these individual configurations.  At an appropriate time, a weakly coupled test will be added combining these configurations based on the needs of the science teams.

**Acceptance Criteria (Definition of Done)**
- configuration for each update mentioned above
- data for supporting and running the above configurations in the global-workflow for atleast 1 and 1/2 cycled test at maximum of C96/5-deg resolution.

**(Optional): Suggest A Solution**

**Comment by AndrewEichmann-NOAA** [comment]
@guillaumevernieres should I be in on this?

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres should I be in on this?

probably @AndrewEichmann-NOAA , we'll figure it out internally.

**Comment by CoryMartin-NOAA** [comment]
@aerorahul if it's okay with you, I will wait to prepare the aerosol case once I've been able to implement and test FGAT as described in https://github.com/NOAA-EMC/global-workflow/issues/1930 as that will be our target configuration (assuming the atm has IAU on). I expect to test/debug this early next week.

**Comment by RussTreadon-NOAA** [comment]
PR #2199 adds `C96_atmsnowDA.yaml`.  PR #1963 adds `C48mx500_3DVarAOWCDA.yaml`.  Might either of these be leveraged to create cases `CXX_atmUFSDA` or `CXXCYY_hybatmUFSDA`.  These cases would be JEDI-based DA for atmosphere without and with ensemble, respectively.

**Comment by RussTreadon-NOAA** [comment]
@jiaruidong2017 , where may I find the staged ICs used to run the Hera tests reported in PR #2287?.  This PR ran `C96_atmsnowDA` with, I presume, an ensemble.  If true, it seems the same ICs could be used to create `C96_atmUFSDA` and `C96_hybatmUFSDA` CI cases.

**Comment by jiaruidong2017** [comment]
@RussTreadon-NOAA you can find the ICs used in PR #2287 as below:

```
/scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdas.init/landid9/C96C48/output/gdas.20211220/
/scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdas.init/landid9/C96C48/output/enkfgdas.20211220/
```

**Comment by RussTreadon-NOAA** [comment]
Thank you @jiaruidong2017 .   These ICs work with the GFS v17 UFS weather model using the fractional grid global_cycle changes in PR #2262.  Is this correct?

**Comment by jiaruidong2017** [comment]
@RussTreadon-NOAA Yes, it is correct.

**Comment by RussTreadon-NOAA** [comment]
g-w issue #2294 provides the _JEDI-based DA for atmosphere with and without ensemble_ test requested by this issue.

**Comment by WalterKolczynski-NOAA** [comment]
We have all the named tests above. If more tests are to be added, we can open new issues.
