### ISSUE TITLE
Unassigned env variables in ocean jjob scripts

### ISSUE THREAD

**Issue by AndrewEichmann-NOAA** [NOAA-EMC/global-workflow#1837]
### What is wrong?

Ocean tasks fail in GDASApp ctests because of unassigned environment variables unless `STRICT="NO"`. Currently they fail on either of two variables:

```
++ jjob_header.sh[81]: setpdy.sh
/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/prod_util/1.2.2/bin/setpdy.sh: line 46: COMROOT: parameter null or not set
+ jjob_header.sh[1]: postamble JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP 1694098698 1
+ preamble.sh[68]: set +x
```
or

```
++ jjob_header.sh[61]: [[ -z ocnanalprepobs ]]
/scratch1/NCEPDEV/da/Andrew.Eichmann/fv3gfs/prepocniodaobs/global-workflow/sorc/gdas.cd/../../ush/jjob_header.sh: line 69: jobid: unbound variable
```

### What should have happened?

Tasks should complete with strict checking, presumably unless there a good reason to do otherwise.

### What machines are impacted?

Hera

### Steps to reproduce

1. Checkout and build GDASApp as configured to cycle WCDA and ctest global-workflow tasks
2. comment out line `export STRICT="NO"` in `*OCEAN*` jjobs
3. run GDASApp ctests in build/test/soca/gw

### Additional information

Since a global-workflow cycling experiment sets the variables in question, the issue may be related to the variables not being set or used in the GDASApp ctests, and may be addressed by setting them to dummy values within those ctests.

This issue supercedes the GDASApp issue https://github.com/NOAA-EMC/GDASApp/issues/605 as it relates to the jjob scripts

### Do you have a proposed solution?

Adding dummy variables to the GDASApp ctests should allow removal of the `STRICT="NO"` lines from the jjobs.

**Comment by AndrewEichmann-NOAA** [comment]
FYI @guillaumevernieres

**Comment by aerorahul** [comment]
ok. so it seems to be a bug in the GDASApp ctests framework.
good spotting @AndrewEichmann-NOAA

**Comment by AndrewEichmann-NOAA** [comment]
@aerorahul The bug is there, but fixing it will allow beneficial modifications to global-workflow. A feature?

**Comment by aerorahul** [comment]
@AndrewEichmann-NOAA not sure I follow

**Comment by AndrewEichmann-NOAA** [comment]
@aerorahul `STRICT` is turned off in the ocean jjobs apparently because there are unused environment variables set by global-workflow that are not set in the GDASApp ctests. I am working on fixing this in GDASApp, which should allow removing the line from the ocean jjob scripts.
