### ISSUE TITLE
Add ldebug flag and cmdaccel module for wave post jobs on WCOSS2

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#1854]
### What new functionality do you need?

Add a new rocoto native flag for `ldebug=true` on WCOSS2 to resolve long runtime issues (observed in production and development runs). See PR for ops ARFC GFSv16.3.8: https://github.com/NOAA-EMC/global-workflow/pull/1848

FYI @JessicaMeixner-NOAA 

### What are the requirements for the new functionality?

The `ldebug=true` PBS statement is included when wave post jobs submit to scheduler on WCOSS2.

### Acceptance Criteria

`ldebug=true` flag is set and jobs run in acceptable amount of time

**Comment by KateFriedman-NOAA** [comment]
Added additional native tag to all jobs in test xml on WCOSS2 (Cactus): `<native>-l ldebug=true</native>`

Ran four 1.5 cycle atmos-only cycled tests on WCOSS2 to check impact to full system:
1) control 1 with `develop`
2) duplicate of test 1
3) same as control but with `ldebug` native tag
4) duplicate of test 3

Control tests reproduced each other and ldebug tests reproduced each other.

Differences were found between control and ldebug test outputs from the analysis in the first full cycle. The initial half cycle outputs matched between runs. Here are the diffs using `nccmp` comparing outputs pulled off tape onto Hera:

```
-bash-4.2$ pwd
/scratch1/NCEPDEV/stmp4/Kate.Friedman/comrot/WCOSS2_test_output/devcycctrl
-bash-4.2$ nccmp -dgB ../testldebug/gdas.20211221/00/analysis/atmos/gdas.t00z.atmanl.nc gdas.20211221/00/analysis/atmos/gdas.t00z.atmanl.nc
DIFFER : VARIABLE : delz : POSITION : [0,0,0,0] : VALUES : -2541.77 <> -2541.77
-bash-4.2$ nccmp -dgB ../testldebug/gdas.20211221/00/analysis/atmos/gdas.t00z.atma003.ensres.nc gdas.20211221/00/analysis/atmos/gdas.t00z.atma003.ensres.nc
DIFFER : VARIABLE : delz : POSITION : [0,0,0,2] : VALUES : -2543.62 <> -2543.62
-bash-4.2$ nccmp -dgB ../testldebug/gdas.20211221/00/analysis/atmos/gdas.t00z.atmanl.ensres.nc gdas.20211221/00/analysis/atmos/gdas.t00z.atmanl.ensres.nc
DIFFER : VARIABLE : delz : POSITION : [0,0,0,0] : VALUES : -2546.48 <> -2546.48
-bash-4.2$ nccmp -dgB ../testldebug/gdas.20211221/00/analysis/atmos/gdas.t00z.atma009.ensres.nc gdas.20211221/00/analysis/atmos/gdas.t00z.atma009.ensres.nc
DIFFER : VARIABLE : delz : POSITION : [0,0,0,0] : VALUES : -2549.01 <> -2549.01
-bash-4.2$ nccmp -dgB ../testldebug/gdas.20211221/00/analysis/atmos/gdas.t00z.sfcanl.nc gdas.20211221/00/analysis/atmos/gdas.t00z.sfcanl.nc
DIFFER : VARIABLE : tref : POSITION : [0,15,43] : VALUES : 272.927 <> 272.927
```

Run output and logs here on WCOSS2:
Control: /lfs/h2/emc/ptmp/kate.friedman/comrot/devcycctrl
Test: /lfs/h2/emc/ptmp/kate.friedman/comrot/testldebug

EXPDIRs on WCOSS2:
Control: /lfs/h2/emc/global/noscrub/kate.friedman/expdir/devcycctrl
Test: /lfs/h2/emc/global/noscrub/kate.friedman/expdir/testldebug

Need to run forecast-only coupled H2 test next to check diffs and impact on wave post runtimes (purpose of using `ldebug` tag).

**Comment by KateFriedman-NOAA** [comment]
I spoke with Marty Bullock from GDIT about the new flag he created. Here is some info on it from him:

----------------------------------------
it's not official but does provide relief until we nail down a permanent solution.
There are two things I'm currently testing:
1. add the "#PBS -l ldebug=true" flag to your job script (this will force a clean remount of /apps before the job starts
2. load the cmdaccel module to clear or reset LD_LIBRARY_PATH before executing frequently used commands from /usr/bin (eliminates searching through /apps paths for system selected commands)

- There are two versions of this module: 1.0 and 1.1 (default)
  - 1.0 simply creates command functions (or aliases for csh/tcsh) to clear LD_LIBRARY_PATH before calling the target command
  - 1.1 resets LD_LIBRARY_PATH to a minimal system default for those binaries
- In my testing so far, I've seen 1.0 perform better but 1.1 is safer, so it's the default.

Option 1 appears to work every time, but is the big hammer approach and only works for that single run.

Option 2 has produced better results, with significant speedups of the test jobs (50% or better), but I've seen about 10% of the jobs have a slowdown (back to normal rates) without the remount.  I'm still trying to understand what's causing this but suspect it might be related to other load on the system.

**Comment by KateFriedman-NOAA** [comment]
@CatherineThomas-NOAA @DavidHuber-NOAA Please see the [comment above](https://github.com/NOAA-EMC/global-workflow/issues/1854#issuecomment-1731628700). I am testing a new homegrown PBS flag (`ldebug`) which was implemented into operations to assist with wavepost runtimes. I used it for all jobs in a short atmos-only low res cycled test on WCOSS2 to see if there was any impact to other jobs (informational test). I encountered differences with the first analysis to run. The `ldebug` flag isn't intended for anything but the wavepost jobs right now but since it's new and not a standard PBS flag I wanted to check how it performed for other jobs. My output is still on Cactus if you wouldn't mind taking a quick look. I also archived output to HPSS (`/NCEPDEV/emc-global/1year/kate.friedman/WCOSS2/scratch/devcycctrl` and `/NCEPDEV/emc-global/1year/kate.friedman/WCOSS2/scratch/testldebug`) and pulled some down onto Hera for comparing with `nccmp` (`/scratch1/NCEPDEV/stmp4/Kate.Friedman/comrot/WCOSS2_test_output/`). I touched my output on Cactus to keep it from being scrubbed, if you happen to notice the timestamps are the same. I saved the timestamp information of the files in `ll_*.out` files in each COMROT. Thanks for any feedback!

**Comment by KateFriedman-NOAA** [comment]
## Forecast-only coupled C768 wavepostpnt test

I added the flag to just the wavepost*pnt* jobs that got the flag in ops, to see if there would be a timing impact. I have run three forecast-only cycles in a control and a test to compare. I only used the `ldebug` PBS flag during submission of the wavepost*pnt* jobs, no others in this test. The gfsfcst job in the 2nd test series is encountering hangs so I have one cycle that isn't complete yet. From the other two forecast-only cycles that did complete, I am only seeing a slight speedup, if at all. Down below are the timings (in seconds) that I've gotten so far from rocotostat output (last column). 

### wavepostbndpnt job

control:
202010070000       gfswavepostbndpnt                    82882061           SUCCEEDED                   0         1        8675.0
202010080000       gfswavepostbndpnt                    82982061           SUCCEEDED                   0         1       10075.0
202010090000       gfswavepostbndpnt                    82980116           SUCCEEDED                   0         1        8880.0

test:
202010070000       gfswavepostbndpnt                    82979937           SUCCEEDED                   0         1        8884.0
202010080000       gfswavepostbndpnt                           -                   -                   -         -             -
202010090000       gfswavepostbndpnt                    82980128           SUCCEEDED                   0         1        8794.0

### wavepostbntpntbll job

control:
202010070000    gfswavepostbndpntbll                    82891295           SUCCEEDED                   0         1        7199.0
202010080000    gfswavepostbndpntbll                    82969747           SUCCEEDED                   0         1        7112.0
202010090000    gfswavepostbndpntbll                    82967599           SUCCEEDED                   0         1        6892.0

test:
202010070000    gfswavepostbndpntbll                    82967379           SUCCEEDED                   0         1        6945.0
202010080000    gfswavepostbndpntbll                           -                   -                   -         -             -
202010090000    gfswavepostbndpntbll                    82967603           SUCCEEDED                   0         1        6878.0

### wavepostpnt job:

control:
202010070000          gfswavepostpnt                    82898347           SUCCEEDED                   0         1       13399.0
202010080000          gfswavepostpnt                    82982062           SUCCEEDED                   0         1       12977.0
202010090000          gfswavepostpnt                    82980117           SUCCEEDED                   0         1       13568.0

test:
202010070000          gfswavepostpnt                    82979938           SUCCEEDED                   0         1       13152.0
202010080000          gfswavepostpnt                           -                   -                   -         -             -
202010090000          gfswavepostpnt                    82980131           SUCCEEDED                   0         1       12579.0

#### EXPDIRs and COMROTs on Cactus:
control:
/lfs/h2/emc/global/noscrub/kate.friedman/expdir/testh2ctrl
/lfs/h2/emc/ptmp/kate.friedman/comrot/testh2ctrl

test:
/lfs/h2/emc/global/noscrub/kate.friedman/expdir/testh2ldebug
/lfs/h2/emc/ptmp/kate.friedman/comrot/testh2ldebug

**Comment by KateFriedman-NOAA** [comment]
Spot check between forecast-only runs to check reproducibility (they reproduce):
```
kate.friedman@clogin07:/lfs/h2/emc/ptmp/kate.friedman/comrot/testh2ldebug> cmp ../testh2ctrl/gfs.20201007/00/products/atmos/grib2/0p25/gfs.t00z.pgrb2.0p25.f384 gfs.20201007/00/products/atmos/grib2/0p25/gfs.t00z.pgrb2.0p25.f384
kate.friedman@clogin07:/lfs/h2/emc/ptmp/kate.friedman/comrot/testh2ldebug> cmp ../testh2ctrl/gfs.20201009/00/products/atmos/grib2/0p25/gfs.t00z.pgrb2.0p25.f384 gfs.20201009/00/products/atmos/grib2/0p25/gfs.t00z.pgrb2.0p25.f384          
kate.friedman@clogin07:/lfs/h2/emc/ptmp/kate.friedman/comrot/testh2ldebug> cmp ../testh2ctrl/gfs.20201007/00/products/wave/gridded/gfswave.t00z.global.0p25.f384.grib2 gfs.20201007/00/products/wave/gridded/gfswave.t00z.global.0p25.f384.grib2                                                                                                         
kate.friedman@clogin07:/lfs/h2/emc/ptmp/kate.friedman/comrot/testh2ldebug>
```
```
-bash-4.2$ pwd
/scratch1/NCEPDEV/stmp4/Kate.Friedman/comrot/WCOSS2_test_output/testh2ldebug
-bash-4.2$ nccmp -dgB ../testh2ctrl/gfs.20201007/00/model_data/ice/history/ice2020102300.000.2020100700.nc gfs.20201007/00/model_data/ice/history/ice2020102300.000.2020100700.nc
-bash-4.2$ nccmp -dgB ../testh2ctrl/gfs.20201007/00/products/ocean/3D/ocn_3D_2020102200.000.2020100700.nc gfs.20201007/00/products/ocean/3D/ocn_3D_2020102200.000.2020100700.nc
-bash-4.2$
```

**Comment by DavidHuber-NOAA** [comment]
@KateFriedman-NOAA I don't have access to WCOSS2 yet, so I don't think I can be of much help here.  It does seem very odd that just remounting /apps would cause such an issue.  Does /apps contain libraries used by the wave post executables outside of the Intel libraries?  Could it be some sort of phantom image?  I seem to recall something similar to this when working on the GCP, though I can't recall what exactly.

**Comment by KateFriedman-NOAA** [comment]
@DavidHuber-NOAA No worries! I forget who has access to what hehe! I'm going to put the analysis diffs aside for the moment and focus on seeing if the PBS flag helps the wavepost jobs at all.

**Comment by KateFriedman-NOAA** [comment]
Unable to get the 2nd forecast-only cycle's fcst job in the test series on WCOSS2 to complete and run the wavepost jobs. Only have the two cycles for timing comparisons at the moment and I don't see an improvement. Have opened a ticket with GDIT (Marty Bullock) to share results thus far.

@JessicaMeixner-NOAA and I chatted offline. Not seeing promised speedup yet and may not be worth it to work on this much more, especially since the wavepost jobs are being rewritten soon and GDIT is working on a more permanent solution for the jobs in ops. Will hold onto changes for now, see what GDIT says, and will send them into `develop` if users desire.

Here are the changes to add the `ldebug` flag into the rocoto xml on WCOSS2 (PBS) job-by-job: https://github.com/NOAA-EMC/global-workflow/compare/develop...KateFriedman-NOAA:global-workflow:feature/ldebug

```
kate.friedman@clogin07:/lfs/h2/emc/global/noscrub/kate.friedman/git/feature-ldebug> git diff
diff --git a/parm/config/gfs/config.resources b/parm/config/gfs/config.resources
index a73d702e..d83e7446 100644
--- a/parm/config/gfs/config.resources
+++ b/parm/config/gfs/config.resources
@@ -136,6 +136,7 @@ elif [[ ${step} = "wavepostbndpnt" ]]; then
     export npe_node_wavepostbndpnt
     export NTASKS=${npe_wavepostbndpnt}
     export is_exclusive=True
+    export ldebug=True
 
 elif [[ ${step} = "wavepostbndpntbll" ]]; then
 
@@ -146,6 +147,7 @@ elif [[ ${step} = "wavepostbndpntbll" ]]; then
     export npe_node_wavepostbndpntbll
     export NTASKS=${npe_wavepostbndpntbll}
     export is_exclusive=True
+    export ldebug=True
 
 elif [[ ${step} = "wavepostpnt" ]]; then
 
@@ -156,6 +158,7 @@ elif [[ ${step} = "wavepostpnt" ]]; then
     export npe_node_wavepostpnt
     export NTASKS=${npe_wavepostpnt}
     export is_exclusive=True
+    export ldebug=True
 
 elif [[ ${step} = "wavegempak" ]]; then
 
diff --git a/workflow/rocoto/rocoto.py b/workflow/rocoto/rocoto.py
index b3f88f01..c8f96c65 100644
--- a/workflow/rocoto/rocoto.py
+++ b/workflow/rocoto/rocoto.py
@@ -72,6 +72,7 @@ def create_task(task_dict: Dict[str, Any]) -> List[str]:
     partition = resources_dict.get('partition', None)
     walltime = resources_dict.get('walltime', '00:01:00')
     native = resources_dict.get('native', None)
+    native2 = resources_dict.get('native2', None)
     memory = resources_dict.get('memory', None)
     nodes = resources_dict.get('nodes', 1)
     ppn = resources_dict.get('ppn', 1)
@@ -100,6 +101,8 @@ def create_task(task_dict: Dict[str, Any]) -> List[str]:
         strings.append(f'\t<memory>{memory}</memory>\n')
     if native is not None:
         strings.append(f'\t<native>{native}</native>\n')
+    if native2 is not None:
+        strings.append(f'\t<native>{native2}</native>\n')
     strings.append('\n')
     strings.append(f'\t<join><cyclestr>{log}</cyclestr></join>\n')
     strings.append('\n')
diff --git a/workflow/rocoto/tasks.py b/workflow/rocoto/tasks.py
index b9716c93..c209833d 100644
--- a/workflow/rocoto/tasks.py
+++ b/workflow/rocoto/tasks.py
@@ -113,7 +113,7 @@ class Tasks:
         Given a task name (task_name) and its configuration (task_names),
         return a dictionary of resources (task_resource) used by the task.
         Task resource dictionary includes:
-        account, walltime, cores, nodes, ppn, threads, memory, queue, partition, native
+        account, walltime, cores, nodes, ppn, threads, memory, queue, partition, native[2]
         """
 
         scheduler = self.app_config.scheduler
@@ -143,10 +143,13 @@ class Tasks:
         memory = task_config.get(f'memory_{task_name}', None)
 
         native = None
+        native2 = None
         if scheduler in ['pbspro']:
             native = '-l debug=true,place=vscatter'
             if task_config.get('is_exclusive', False):
                 native += ':exclhost'
+            if task_config.get('ldebug', False):
+                native2 = '-l ldebug=true'
         elif scheduler in ['slurm']:
             native = '--export=NONE'
 
@@ -165,6 +168,7 @@ class Tasks:
                          'threads': threads,
                          'memory': memory,
                          'native': native,
+                         'native2': native2,
                          'queue': queue,
                          'partition': partition}
```

**Comment by KateFriedman-NOAA** [comment]
Reply from GDIT:
```
Thanks, Kate.  Unfortunately, this has probably been a bad week to troubleshoot job performance issues due to all 
of the other activity and issues we've been experiencing on h2.  We had a few slow disks to replace, a controller 
failover, and an influx of new jobs that appear to be contributing to a significant load on the filesystem.  The disks 
are still rebuilding and should be back to 100% by next week.

I'm not saying those issues contributed to your job failures or slowness, but it does impact the data we collect and 
makes it extremely difficult to separate the chaff from the wheat.  If the -l ldebug=true flag didn't help normalize 
your runtimes, I suspect, as did you, that you might be seeing the impact from some of the additional h2 load or 
issues.

In the gfswave test case that I've been using, the execution process creates a LOT of needless activity in the /apps 
filesystem (a subdir of /lfs/f2).  The purpose of the f2 remount was to reset counters and clear any stale information 
from the local node. 
One of the other things I suggested was to load the cmdaccel module, it doesn't really matter which version you use 
but I saw better performance with 1.0 in my limited testing (~30-40 jobs).  It would be helpful to know if you see 
similar results.

I'll do my best to take a closer look into what you've provided over the next few days.

Thanks!

--Marty
```

**Comment by KateFriedman-NOAA** [comment]
Took a few days to get enough cycles to run on WCOSS2 due to hanging fcst jobs. Finally got a few to compare against control runs of the same cycles for timing.

Timings (tests used ldebug flag and cmdaccel module at runtime):

### wavepostbndpnt

control:
```
202010070000       gfswavepostbndpnt                    8675.0
202010080000       gfswavepostbndpnt                    10075.0
202010090000       gfswavepostbndpnt                    8880.0
```
test:
```
202010070000       gfswavepostbndpnt                    8676.0
202010080000       gfswavepostbndpnt                    9063.0
202010090000       gfswavepostbndpnt                    8266.0
202010100000       gfswavepostbndpnt                    8598.0
202010110000       gfswavepostbndpnt                    8436.0
202010120000       gfswavepostbndpnt                    8207.0
```

### wavepostbndpntbll

control:
```
202010070000    gfswavepostbndpntbll                    7199.0
202010080000    gfswavepostbndpntbll                    7112.0
202010090000    gfswavepostbndpntbll                    6892.0
```
test:
```
202010070000    gfswavepostbndpntbll                    6213.0
202010080000    gfswavepostbndpntbll                    6102.0
202010090000    gfswavepostbndpntbll                    5989.0
202010100000    gfswavepostbndpntbll                    6059.0
202010110000    gfswavepostbndpntbll                    6067.0
202010120000    gfswavepostbndpntbll                    6127.0
```

### wavepostpnt

control:
```
202010070000          gfswavepostpnt                    13399.0
202010080000          gfswavepostpnt                    12977.0
202010090000          gfswavepostpnt                    13568.0
```
test:
```
202010070000          gfswavepostpnt                    11610.0
202010080000          gfswavepostpnt                    11760.0
202010090000          gfswavepostpnt                    11760.0
202010100000          gfswavepostpnt                    11247.0
202010110000          gfswavepostpnt                    11281.0
202010120000          gfswavepostpnt                    11530.0
```

Observed slight speedup for test wavepost jobs but will want to rerun control and test runs again since both were impacted by /h2 slowness the past couple weeks.

**Comment by KateFriedman-NOAA** [comment]
Will not complete at this time. Reworking of wave post jobs should make this moot. Closing issue.

**Comment by KateFriedman-NOAA** [comment]
Related update from Marty Bullock from WCOSS2:
```
The recent lustre upgrade showed some significant improvements in gfswave runtimes and we are planning to
remove the temporary remount functionality that the ldebug=true flag is performing.  If you are using that flag,
I would recommend removing it (since the original purpose of this flag is probably not something you want for
your regular job execution).
```

FYI @JessicaMeixner-NOAA
