### ISSUE TITLE
Update gsi fix files for gfs.v16.3.9

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/global-workflow#1856]
### Target fix directory

gsi

### Type of change

- [X] Update existing files

### Any workflow changes needed?

Fix version only

### Related issues

NOAA-EMC/GSI-fix issue [#9](https://github.com/NOAA-EMC/GSI-fix/issues/9)
 - global_convinfo.txt - assimilate PlanetIQ gpsro
 - global_ozinfo.txt - assimilate NOAA-20 OMPS, adjust OMP observation errors (all satellite platforms)
 
NOAA-EMC/global-workflow issue #1813

### Pickup location

Hera /scratch2/NCEPDEV/stmp1/Russ.Treadon/fix/gsi/20230911

### Size

0.043 Mb smaller.  20230601 at 2333.973 Mb vs 20230911 at 2333.930 Mb

*** To Do

- [x] Pull new GSI fix folder into primary fix location (@KateFriedman-NOAA @WalterKolczynski-NOAA )
- [ ] Update `gsi_ver` in `versions/fix.ver`
- [x] Update timestamp for gsi subfolder in fix spreadsheet

**Comment by RussTreadon-NOAA** [comment]
@KateFriedman-NOAA and @WalterKolczynski-NOAA , do I update google sheet [Fix File Management](https://docs.google.com/spreadsheets/d/1BeIvcz6TO3If4YCqkUK-oz_kGS9q2wTjwLS-BBemSEY/edit?pli=1#gid=526608225) or do you take care of this?

Same question for g-w `versions/fix.ver`? Who is responsible for updating `gsi_ver` from 20230601 to 20230911?

**Comment by KateFriedman-NOAA** [comment]
> do I update google sheet [Fix File Management](https://docs.google.com/spreadsheets/d/1BeIvcz6TO3If4YCqkUK-oz_kGS9q2wTjwLS-BBemSEY/edit?pli=1#gid=526608225) or do you take care of this?

I think it's just updating the timestamp for the gsi subfolder on the first sheet so I can do that. Let me know if not.

In general, if there are more updates to be made in the spreadsheet (e.g. updating the gsi subsheet contents) that requires knowledge from a SME then we'd prefer the SME make the update but let us know they have done so.

> Same question for g-w versions/fix.ver? Who is responsible for updating gsi_ver from 20230601 to 20230911?

@RussTreadon-NOAA In this situation, please include the update to `versions/fix.ver` with whatever PR you send to `develop` for issue #1857 changes. That PR can close both that issue and this one. Thanks!

FYI, I have updated the main issue comment to reflect a To Do list.

Question...will the ops changes for GFSv16.3.10 (issue #1356) undo these fix/script changes?

**Comment by RussTreadon-NOAA** [comment]
Yes, this issue only requires updating the gsi timestamp (cell B-17) on the MAIN SHEET tab of [Fix File Management](https://docs.google.com/spreadsheets/d/1BeIvcz6TO3If4YCqkUK-oz_kGS9q2wTjwLS-BBemSEY/edit?pli=1#gid=526608225).

GFS v16.3.10 will not undo changes to fix files `global_convinfo.txt` and `global_ozinfo.txt`.   Based on what I see in issue #1356, GFS v16.3.10 will likely require updates to `global_convinfo.txt` and `global_satinfo.txt`.  

If GFS v16.3.10 does indeed turn on assimilation of NOAA-21 ATMS and/or CrIS, we will need to add the lines

```
    atmsbufr       atms        n21         atms_n21            0.0     1     1
    crisfsbufr     cris-fsr    n21         cris-fsr_n21        0.0     1     0
```

back to `exglobal_atmos_analysis.sh`.

**Comment by KateFriedman-NOAA** [comment]
> Yes, this issue only requires updating the gsi timestamp (cell B-17) on the MAIN SHEET tab of [Fix File Management](https://docs.google.com/spreadsheets/d/1BeIvcz6TO3If4YCqkUK-oz_kGS9q2wTjwLS-BBemSEY/edit?pli=1#gid=526608225).
> 
> GFS v16.3.10 will not undo changes to fix files `global_convinfo.txt` and `global_ozinfo.txt`.

Thanks @RussTreadon-NOAA for confirming those details. I have pulled the new GSI fix set into the primary fix location on Hera (`/scratch1/NCEPDEV/global/glopara/fix/gsi/20230911`) and we'll sync them to the other platforms next. I have also updated the timestamp in the fix spreadsheet.

@WalterKolczynski-NOAA please sync the fix set on Orion with the update in the Hera set, thanks!

**Comment by KateFriedman-NOAA** [comment]
The new GSI `20230911` fix set is now sync'd into the primary fix sets on Jet and WCOSS2 (Cactus and Dogwood).

**Comment by WalterKolczynski-NOAA** [comment]
Fix files have been synchronized to Orion
