### ISSUE TITLE
Update exglobal_atmos_analysis.sh with gfs.v16.3.9 changes

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/global-workflow#1857]
### What new functionality do you need?

This issue is not requesting a new functionality.  It is opened instead to update `exglobal_atmos_analysis.sh` with changes from gfs.v16.3.9.   

One of the changes in gfs.v16.3.9 was to turn off ingest of NOAA-21 radiances in the GSI.  This was achieved by removing the following lines 
```
    atmsbufr       atms        n21         atms_n21            0.0     1     1
    crisfsbufr     cris-fsr    n21         cris-fsr_n21        0.0     1     0
```
from the `OBS_INPUT` section of the GSI namelist in `exglobal_atmos_analysis.sh`

While operational GSI still maintains `exglobal_atmos_analysis.sh` in the GSI repository, this is not true for the development GSI.   g-w maintains `exglobal_atmos_analysis.sh` for the development GSI.   As such, this issue is opened to get the above two line change into g-w `exglobal_atmos_analysis.sh`.

### What are the requirements for the new functionality?

The updated `exglobal_atmos_analysis.sh` script will not process NOAA-21 radiances.

### Acceptance Criteria

The updated `exglobal_atmos_analysis.sh` script does not process NOAA-21 radiances.

### Suggest a solution (optional)

As with GFS v16.3.9, remove the two NOAA-21 lines noted above from the `OBS_INPUT` namelist in `exglobal_atmos_analysis.sh`.

**Comment by RussTreadon-NOAA** [comment]
@KateFriedman-NOAA brought to my attention issue #1356, GFS v16.3.10. Part of this planned implementation is to turn on assimilation of NOAA-21 radiances.  If this occurs, GFS v16.3.10 will need to add the lines
```
    atmsbufr       atms        n21         atms_n21            0.0     1     1
    crisfsbufr     cris-fsr    n21         cris-fsr_n21        0.0     1     0
```
back to `exglobal_atmos_analysis.sh`.

**Comment by KateFriedman-NOAA** [comment]
Thanks for that note @RussTreadon-NOAA ! I updated the checklist in issue #1356 to reflect that potential change to-do.

**Comment by RussTreadon-NOAA** [comment]
Create [feature/update_gfsv1639](https://github.com/RussTreadon-NOAA/global-workflow/tree/feature/update_gfsv1639) for work to be done in this issue.
