### ISSUE TITLE
New BNU soil type and VIIRS vegetation type data

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/global-workflow#1884]
### Target fix directory

sfc_climo

### Type of change

- [ ] Update existing files
- [ ] Remove files
- [ ] Add new files to existing directory
- [X] Add new fix directory

### Any workflow changes needed?

No change needed

### Related issues

https://github.com/ufs-community/UFS_UTILS/pull/843
https://github.com/ufs-community/UFS_UTILS/issues/821

### Pickup location

/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS/fix/sfc_climo.test/

### Size

A few MB smaller than the latest version of the sfc_climo directory.

**Comment by GeorgeGayno-NOAA** [comment]
I suggest copying my directory as a new version of sfc_climo.

**Comment by KateFriedman-NOAA** [comment]
@GeorgeGayno-NOAA can you adjust permissions on this file? The initial owner w is missing.
```
-r--r--r-- 1 George.Gayno da    1067244 Sep 25 17:52 substrate_temperature.gfs.0.5.nc
```

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA can you adjust permissions on this file? The initial owner w is missing.
> 
> ```
> -r--r--r-- 1 George.Gayno da    1067244 Sep 25 17:52 substrate_temperature.gfs.0.5.nc
> ```

Try it now.

**Comment by KateFriedman-NOAA** [comment]
> Try it now.

Perfect, thanks!

**Comment by KateFriedman-NOAA** [comment]
Rsync'd @GeorgeGayno-NOAA 's new sfc_climo.test folder contents into a new timestamp folder in primary fix set sfc_climo subfolder (`20230925`):

```
[role.glopara@hfe03 20230925]$ pwd
/scratch1/NCEPDEV/global/glopara/fix/sfc_climo/20230925
[role.glopara@hfe03 20230925]$ ll
total 10944284
-rw-rw-rw- 1 role.glopara global     279733 Sep 25 17:42 facsf.1.0.nc
-rw-rw-rw- 1 role.glopara global 4769464869 Sep 25 17:42 leaf_area_index.0.05.nc
-rw-rw-rw- 1 role.glopara global  103864687 Sep 25 17:42 maximum_snow_albedo.0.05.nc
-rw-rw-rw- 1 role.glopara global     279733 Sep 25 17:42 slope_type.1.0.nc
-rw-rw-rw- 1 role.glopara global 4976826419 Sep 25 17:43 snowfree_albedo.4comp.0.05.nc
-rw-rw-rw- 1 role.glopara global  103865024 Sep 25 17:43 soil_color.clm.0.05.nc
-rw-rw-rw- 1 role.glopara global  155080845 Sep 25 17:49 soil_type.bnu.v3.30s.nc
-rw-rw-rw- 1 role.glopara global  288305040 Sep 25 17:43 soil_type.statsgo.0.03.nc
-rw-rw-rw- 1 role.glopara global  103869840 Sep 25 17:43 soil_type.statsgo.0.05.nc
-rw-rw-rw- 1 role.glopara global   12726747 Sep 25 17:43 soil_type.statsgo.30s.nc
-rw-rw-rw- 1 role.glopara global    2542805 Sep 25 17:43 soil_type.statsgo.conus.30s.nc
-rw-rw-rw- 1 role.glopara global    9080720 Sep 25 17:43 soil_type.statsgo.nh.30s.nc
-rw-rw-rw- 1 role.glopara global     279733 Sep 25 17:43 substrate_temperature.1.0.nc
-rw-rw-rw- 1 role.glopara global    1067244 Sep 25 17:52 substrate_temperature.gfs.0.5.nc
-rw-rw-rw- 1 role.glopara global  150071935 Sep 25 17:43 vegetation_greenness.0.144.nc
lrwxrwxrwx 1 role.glopara global         34 Sep 26 15:56 vegetation_type.igbp.0.05.nc -> vegetation_type.modis.igbp.0.05.nc
-rw-rw-rw- 1 role.glopara global  288305066 Sep 25 17:43 vegetation_type.modis.igbp.0.03.nc
-rw-rw-rw- 1 role.glopara global  103869866 Sep 25 17:43 vegetation_type.modis.igbp.0.05.nc
-rw-rw-rw- 1 role.glopara global   51742123 Sep 25 17:43 vegetation_type.modis.igbp.30s.nc
-rw-rw-rw- 1 role.glopara global    7768256 Sep 25 17:43 vegetation_type.modis.igbp.conus.30s.nc
-rw-rw-rw- 1 role.glopara global   39219215 Sep 25 17:43 vegetation_type.modis.igbp.nh.30s.nc
-rw-rw-rw- 1 role.glopara global   38276427 Sep 25 17:50 vegetation_type.viirs.v3.igbp.30s.nc
```

Will sync other platforms next.

Will need to update the `sfc_climo_ver=20230925` value when we update to the UFS_UTILS hash that needs it. This line: https://github.com/NOAA-EMC/global-workflow/blob/develop/versions/fix.ver#L19

**Comment by GeorgeGayno-NOAA** [comment]
> Rsync'd @GeorgeGayno-NOAA 's new sfc_climo.test folder contents into a new timestamp folder in primary fix set sfc_climo subfolder (`20230925`):
> 
> ```
> [role.glopara@hfe03 20230925]$ pwd
> /scratch1/NCEPDEV/global/glopara/fix/sfc_climo/20230925
> [role.glopara@hfe03 20230925]$ ll
> total 10944284
> -rw-rw-rw- 1 role.glopara global     279733 Sep 25 17:42 facsf.1.0.nc
> -rw-rw-rw- 1 role.glopara global 4769464869 Sep 25 17:42 leaf_area_index.0.05.nc
> -rw-rw-rw- 1 role.glopara global  103864687 Sep 25 17:42 maximum_snow_albedo.0.05.nc
> -rw-rw-rw- 1 role.glopara global     279733 Sep 25 17:42 slope_type.1.0.nc
> -rw-rw-rw- 1 role.glopara global 4976826419 Sep 25 17:43 snowfree_albedo.4comp.0.05.nc
> -rw-rw-rw- 1 role.glopara global  103865024 Sep 25 17:43 soil_color.clm.0.05.nc
> -rw-rw-rw- 1 role.glopara global  155080845 Sep 25 17:49 soil_type.bnu.v3.30s.nc
> -rw-rw-rw- 1 role.glopara global  288305040 Sep 25 17:43 soil_type.statsgo.0.03.nc
> -rw-rw-rw- 1 role.glopara global  103869840 Sep 25 17:43 soil_type.statsgo.0.05.nc
> -rw-rw-rw- 1 role.glopara global   12726747 Sep 25 17:43 soil_type.statsgo.30s.nc
> -rw-rw-rw- 1 role.glopara global    2542805 Sep 25 17:43 soil_type.statsgo.conus.30s.nc
> -rw-rw-rw- 1 role.glopara global    9080720 Sep 25 17:43 soil_type.statsgo.nh.30s.nc
> -rw-rw-rw- 1 role.glopara global     279733 Sep 25 17:43 substrate_temperature.1.0.nc
> -rw-rw-rw- 1 role.glopara global    1067244 Sep 25 17:52 substrate_temperature.gfs.0.5.nc
> -rw-rw-rw- 1 role.glopara global  150071935 Sep 25 17:43 vegetation_greenness.0.144.nc
> lrwxrwxrwx 1 role.glopara global         34 Sep 26 15:56 vegetation_type.igbp.0.05.nc -> vegetation_type.modis.igbp.0.05.nc
> -rw-rw-rw- 1 role.glopara global  288305066 Sep 25 17:43 vegetation_type.modis.igbp.0.03.nc
> -rw-rw-rw- 1 role.glopara global  103869866 Sep 25 17:43 vegetation_type.modis.igbp.0.05.nc
> -rw-rw-rw- 1 role.glopara global   51742123 Sep 25 17:43 vegetation_type.modis.igbp.30s.nc
> -rw-rw-rw- 1 role.glopara global    7768256 Sep 25 17:43 vegetation_type.modis.igbp.conus.30s.nc
> -rw-rw-rw- 1 role.glopara global   39219215 Sep 25 17:43 vegetation_type.modis.igbp.nh.30s.nc
> -rw-rw-rw- 1 role.glopara global   38276427 Sep 25 17:50 vegetation_type.viirs.v3.igbp.30s.nc
> ```
> 
> Will sync other platforms next.
> 
> Will need to update the `sfc_climo_ver=20230925` value when we update to the UFS_UTILS hash that needs it. This line: https://github.com/NOAA-EMC/global-workflow/blob/develop/versions/fix.ver#L19

Thanks. I will run a quick test on Hera.

**Comment by KateFriedman-NOAA** [comment]
New sfc_climo has been synced to both WCOSS2s, Orion and Jet.

**Comment by KateFriedman-NOAA** [comment]
@GeorgeGayno-NOAA Test go ok? I saw the related UFS_UTILS PRs were completed.

Shall we close this as completed? Can open a new issue to update the UFS_UTILS hash and `sfc_climo_ver` when we make that move.

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA Test go ok? I saw the related UFS_UTILS PRs were completed.
> 
> Shall we close this as completed? Can open a new issue to update the UFS_UTILS hash and `sfc_climo_ver` when we make that move.

Yes, you can close this.
