### ISSUE TITLE
Data dependency for wavepostbndpntbll job incorrect

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#1887]
### What is wrong?

The gfspostwavebndpntbll job would not fire off because the dependency was not satisfied:
```
  dependencies
    /lfs/h2/emc/ptmp/kate.friedman/comrot/testh2ctrl/gfs.20201007/00//model_data/wave/history/gfs.t00z.atm.logf180.txt does not exist
```
The atm.logf files don't live in the `wave/history` folder.

### What should have happened?

The dependency should use `atmos/history` in the path, be satisfied, and fire off the job:
```
  dependencies
    /lfs/h2/emc/ptmp/kate.friedman/comrot/testh2ctrl/gfs.20201007/00/model_data/atmos/history/gfs.t00z.atm.logf180.txt is available
```

### What machines are impacted?

All or N/A

### Steps to reproduce

Run a coupled forecast-only run with waves and the wavepostbndpntbll job turned on.

### Additional information

Likely not observed sooner since this job has been turned off by default for a bit.

### Do you have a proposed solution?

Fix the data dependency path in `workflow/rocoto/gfs_tasks.py`:
https://github.com/NOAA-EMC/global-workflow/blob/develop/workflow/rocoto/gfs_tasks.py#L661:L662
```
diff --git a/workflow/rocoto/gfs_tasks.py b/workflow/rocoto/gfs_tasks.py
index 726f7e67..37aa872e 100644
--- a/workflow/rocoto/gfs_tasks.py
+++ b/workflow/rocoto/gfs_tasks.py
@@ -646,8 +646,8 @@ class GFSTasks(Tasks):
 
     def wavepostbndpntbll(self):
         deps = []
-        wave_hist_path = self._template_to_rocoto_cycstring(self._base["COM_WAVE_HISTORY_TMPL"])
-        data = f'{wave_hist_path}/{self.cdump}.t@Hz.atm.logf180.txt'
+        atmos_hist_path = self._template_to_rocoto_cycstring(self._base["COM_ATMOS_HISTORY_TMPL"])
+        data = f'{atmos_hist_path}/{self.cdump}.t@Hz.atm.logf180.txt'
```

That gives the correct dependency:
```
        <dependency>
                <datadep><cyclestr>&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/history/gfs.t@Hz.atm.logf180.txt</cyclestr></datadep>
        </dependency>
```

**Comment by JessicaMeixner-NOAA** [comment]
Thanks for finding this @KateFriedman-NOAA !
