### ISSUE TITLE
Using inline atm post in feature/coupled-crow

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#190]
Merge develop branch into feature/coupled-crow to allow next prototype to use GFSv16 updates including inline post.

**Comment by JessicaMeixner-NOAA** [comment]
Merging develop into this branch should also restructure the atm com directory. This PR: https://github.com/NOAA-EMC/global-workflow/pull/180 which is in feature/coupled-crow now should be helpful as it restructured the wave com directory.  

@JianKuang-NOAA  I didn't see another issue, so I made this one.

**Comment by jkuang-exploro** [comment]
Thanks. feature/gfsv16intocoupledcrow is the branch that I am working with.

**Comment by jkuang-exploro** [comment]
I have deleted the branch and restarted from feature/coupled-crow.

**Comment by jkuang-exploro** [comment]
@JessicaMeixner-NOAA I finished the script update. Now working on namelists update. I would like to mention that the ROTDIR structure of feature/coupled-crow (especially, IC) is still not compatible with gfsv16 (ie, they have one extra level named /atmos/; a parallel top-level dir called gfswave.YYYYMMDD). So as a result, after this prospective PR, feature/coupled-crow will be able to include physics in gfsv16 (namelists, parameters), but still won't be able to run gfsv16 cycled experiment, unless we, the coupling team, would like to adopt their ROTDIR structure.

**Comment by JessicaMeixner-NOAA** [comment]
@JianKuang-NOAA we do need to update to the v16 directory structure for COMROT with the /atmos /wave etc structure as this is the agreed upon structure with NCO.  The PR #180  which is already in feature/coupled crow, changed the gfswave.YYYYMMDD to gfs.YYYYMMDD/cc/wave/ structure and we should keep that.   In merging in the develop branch, this should also change the atmosphere to follow the /atmos/ directory structure.  We don't want to undo those changes.    The ice & ocn can be dealt with separately (there is an issue already made for that here: https://github.com/NOAA-EMC/global-workflow/issues/191).

**Comment by jkuang-exploro** [comment]
@JessicaMeixner-NOAA OK I agree that's the optimal path forward. Only that all case IC files would need to be updated correspondingly, before I can test running this PR. May I know how could we, the coupling team, facilitate this transition?

**Comment by JessicaMeixner-NOAA** [comment]
I can help make that update @JianKuang-NOAA  just point me to which branch you have the merge in and I can update the IC script for you.

**Comment by jkuang-exploro** [comment]
@JessicaMeixner-NOAA It's feature/gfsv16intocoupled. Is it the case that only the coupled_ic.sh needs to be updated? If that's true then I will do it. As long as the central-managed IC data doesn't need to be updated.

**Comment by JessicaMeixner-NOAA** [comment]
@JianKuang-NOAA  it would be awesome if you could update it. 

I think just this line: 
https://github.com/NOAA-EMC/global-workflow/blob/feature/coupled-crow/jobs/rocoto/coupled_ic.sh#L54 
needs to be changed 
cp -r $ORIGIN_ROOT/$CPL_ATMIC/$CDATE/$CDUMP  $ICSDIR/$CDATE/
to 
cp -r $ORIGIN_ROOT/$CPL_ATMIC/$CDATE/$CDUMP  $ICSDIR/$CDATE/atmos/

**Comment by jkuang-exploro** [comment]
OK. I thought the same. Will do.

**Comment by jkuang-exploro** [comment]
PR#194 is merged into feature/coupled-crow. Now closing this issue.

**Comment by JessicaMeixner-NOAA** [comment]
Is this issue closed?   This issue included using inline post.  If you want to keep this closed, can you open a new issue for inline post for feature/coupled-crow?

**Comment by jkuang-exploro** [comment]
@JessicaMeixner-NOAA I modified the title of this issue to better reflect the direction of our next efforts.

**Comment by JessicaMeixner-NOAA** [comment]
@JianKuang-NOAA is this completed now or are there still more checks that need to be done?

**Comment by jkuang-exploro** [comment]
@JessicaMeixner-NOAA To the best of my knowledge, this is completed. Further works may be required, however, to tune it up for a specific experiment.

**Comment by JessicaMeixner-NOAA** [comment]
So we can close the issue then?
