### ISSUE TITLE
Update ocn/ice com restructure

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#191]
At some point the ocean and ice com directories should be restructured to follow the NCO structure: 

<COM>/atmos
<COM>/wave 
<COM>/chem 

etc. 

One trick with this will be that the resulting grib files for ocean and ice are actually combined.  So I'm not sure how that should be handled.  Otherwise, it should be pretty straight froward.

**Comment by KateFriedman-NOAA** [comment]
@JessicaMeixner-NOAA Checking on status of this issue. Please update or close as needed, thanks!

**Comment by JessicaMeixner-NOAA** [comment]
The atmos/ and wave/ are using folders in the com directory and then ocean/ and ice/ are not.    I'm not actively working on this issue, however the need for this issue is still there.

**Comment by KateFriedman-NOAA** [comment]
Roger that, thanks for the update!

**Comment by JessicaMeixner-NOAA** [comment]
The title of this issue is for feature/coupled-crow, but it's still relevant after merging feature/coupled-crow->develop.
