### ISSUE TITLE
update clone-build script to take mutually exclusive switch for branch or PR number

### ISSUE THREAD

**Issue by TerrenceMcGuinness-NOAA** [NOAA-EMC/global-workflow#1913]
### What new functionality do you need?

As a workflow CI developer I need to update the supporting BASH script for clone-build to to take a mutually exclusive switch for build branch instead of just a PR number so we can use it to also support the functional test framework.

### What are the requirements for the new functionality?

The script will know if at least one of the options is used and complain if  neither are used for cloning a branch or from a PR.  And of course it will clone a branch or PR when asked to do so.

### Acceptance Criteria

The request branch is cloned as well if a PR number is used instead.

**Comment by WalterKolczynski-NOAA** [comment]
OBE
