### ISSUE TITLE
GEFS workflow development- configurations,  physics setting etc

### ISSUE THREAD

**Issue by AnilKumar-NOAA** [NOAA-EMC/global-workflow#1921]
### What new functionality do you need?

1. Adding 5-scale configurations to global workflow for ATM-SPPT, OCN-SPPT, OCN-EPBL
2. Adding correct stochastic physics setting to global workflow for unperturbed members and perturbed members

### What are the requirements for the new functionality?

GEFS inputs and configurations

### Acceptance Criteria

Develop GEFS workflow

### Suggest a solution (optional)

Propose how this issues are resolved

 *  Adding 5-scale configurations to global workflow for ATM-SPPT, OCN-SPPT, OCN-EPBL
 * Adding correct stochastic physics setting to global workflow for unperturbed members and perturbed members
 * Adding prdgen jobs for ensemble in global workflow

**Comment by HenryRWinterbottom** [comment]
@AnilKumar-NOAA You may want to check with @guillaumevernieres regarding the status of the OCN-SPPT and OCN-EPBL.

**Comment by AnilKumar-NOAA** [comment]
> @AnilKumar-NOAA You may want to check with @guillaumevernieres regarding the status of the OCN-SPPT and OCN-EPBL.
Thanks and will check. 
I think we need to start with ATM. Later OCN. Bing added this tasks to me.

**Comment by aerorahul** [comment]
@NeilBarton-NOAA did a lot of the legwork.  His branch is at:
https://github.com/NOAA-EMC/global-workflow/compare/develop...NeilBarton-NOAA:global-workflow:EP5dtest

**Comment by HenryWinterbottom-NOAA** [comment]
Thanks, @aerorahul. I will take a look.

**Comment by NeilBarton-NOAA** [comment]
I'm working on some other stuff this week (so far), but I'm happy to split these edits up for concise commits.

**Comment by WalterKolczynski-NOAA** [comment]
@NeilBarton-NOAA was this satisfied by #2392, or is there more that needs to be done?

**Comment by NeilBarton-NOAA** [comment]
@WalterKolczynski-NOAA This can be closed in my opinion
