### ISSUE TITLE
New MOM6 vertical geometry file 

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/global-workflow#1923]
### Target fix directory

mom6

### Type of change

- [ ] Update existing files
- [ ] Remove files
- [X] Add new files to existing directory
- [ ] Add new fix directory

### Any workflow changes needed?

No change needed

### Adding notes here
I need to add 2 `fix files` for MOM6:

For the 1/4 deg resolution:
```/scratch2/NCEPDEV/ocean/Guillaume.Vernieres/prs/global-workflow/fix/mom6/025/oceanda_zgrid_75L.nc```

and the 5.00 deg resolution:
```/scratch2/NCEPDEV/ocean/Guillaume.Vernieres/prs/global-workflow/fix/mom6/500/oceanda_zgrid_25L.nc```

### Pickup location

/scratch2/NCEPDEV/ocean/Guillaume.Vernieres/prs/global-workflow/fix/mom6/025/

### Size

4.0KB

**Comment by pjpegion** [comment]
Will this affect running MOM6 with restarts generated with the old vertical levels?

**Comment by guillaumevernieres** [comment]
> Will this affect running MOM6 with restarts generated with the old vertical levels?

@pjpegion , these new files are only used to produce history files for the marine DA.

**Comment by pjpegion** [comment]
ok, thanks

**Comment by WalterKolczynski-NOAA** [comment]
- [x] Copied to glopara fix on Hera
- [x] Synchronized to Orion
- [x] Synchronized to Cactus
- [x] Synchronized to Dogwood
- [x] New tarball archived to HPSS

**Comment by WalterKolczynski-NOAA** [comment]
@guillaumevernieres please confirm the fix files are in place, then we will close the issue as completed.

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres please confirm the fix files are in place, then we will close the issue as completed.

They are. Thanks @WalterKolczynski-NOAA .
