### ISSUE TITLE
changes required for switching instances of "nems"  to "ufs"

### ISSUE THREAD

**Issue by DeniseWorthen** [NOAA-EMC/global-workflow#1942]
### What new functionality do you need?

In PR ufs-community/ufs-weather-model/pull/1948, the ``coupling_mode`` options have been renamed and the ``nems.configure`` file is replaced with ``ufs.configure``. 

In the RTs, the ``coupling_mode`` is determined with the CPLMODE variable. The names have changed as follows

```
nems_orig --> ufs.nfrac
nems_orig_data --> ufs.nfrac.aoflux
nems_frac --> ufs.frac
nems_frac_aoflux and nems_frac_aoflux_sbs --> ufs.frac.aoflux
```

### What are the requirements for the new functionality?

NA

### Acceptance Criteria

The GW will need to recognize and use the new coupling mode definitions and configure file.

**Comment by JessicaMeixner-NOAA** [comment]
First attempt at this is here: https://github.com/JessicaMeixner-NOAA/global-workflow/tree/feature/updatemod1114

**Comment by JessicaMeixner-NOAA** [comment]
The PR has been merged into ufs-waether-model so I thik this can be un-blocked.
