### ISSUE TITLE
Enable different coupled options (NSST on/off) and output frequencies in coupled models

### ISSUE THREAD

**Issue by JoshuaFu-NOAA** [NOAA-EMC/global-workflow#196]

**Comment by JessicaMeixner-NOAA** [comment]
@jiandewang isn't this already there in the feature/coupled-crow branch?

**Comment by jiandewang** [comment]
@JessicaMeixner-NOAA no

**Comment by JoshuaFu-NOAA** [comment]
c 

> 
> 
> @JessicaMeixner-NOAA no



> 
> 
> @jiandewang isn't this already there in the feature/coupled-crow branch?

better to make three flexible output frequency options, respectively, for atmosphere, ocean and ice components,  which can be modified from case yaml files?

**Comment by JoshuaFu-NOAA** [comment]
need to add three one-stop control parameters.

**Comment by KateFriedman-NOAA** [comment]
Please update issue, thanks!

**Comment by WalterKolczynski-NOAA** [comment]
Closed as duplicate of #230
