### ISSUE TITLE
bring NCO's updates back to branch release/gfsv16.0.0

### ISSUE THREAD

**Issue by yangfanglin** [NOAA-EMC/global-workflow#197]
NCO's SPA  has made numerous local  changes to release/gfsv16.0.0 installed at /gpfs/dell1/nco/ops/nwpara/gfs.v16.0.1.  EMC and NCO worked together to confirm  the changes  and planed to bring them back to release/gfsv16.0.0 and its associated repos.   Details of the changes are documented in 
https://docs.google.com/document/d/1hPMKOQeqaHlBHusCsPLhyz8FYo-dQ64YuwosOvLocY4/edit
https://docs.google.com/document/d/1KSFZThJkB_2ZJrSEQRbyfcDDvPufPrRkg7FhWQF4Cd4/edit

All changes have now been merged to  https://github.com/NOAA-EMC/global-workflow/tree/release/gfsv16.0.0.nco, which needs to be tested for running EMC parallels

**Comment by yangfanglin** [comment]
A test showed that jobid is not defined in  JGLOBAL_FORECAST running in the Rocoto environment.   jobid is defined in ./env files.  Defining DATA without sourcing ./env/$nachine.env caused the the script to fail.

**Comment by KateFriedman-NOAA** [comment]
This work is completed and merged into release/gfsv16.0.0. Have since removed the release/gfsv16.0.0.nco branch. Closing this issue now. Thanks all!
