### ISSUE TITLE
add support for C96/1deg coupled UFS for WCDA

### ISSUE THREAD

**Issue by jswhit** [NOAA-EMC/global-workflow#1990]
### What new functionality do you need?

support for weakly coupled DA with C96 atmosphere, 1 deg ocean (currently C384/0.25deg and C48/5deg are supported)

### What are the requirements for the new functionality?

able to cycle weakly coupled 3dvar so it can be used for SFSv1 reanalysis scout run

### Acceptance Criteria

has all the same capabilities as the the other supported resolutions

### Suggest a solution (optional)

I am working on adding this (see https://github.com/NOAA-EMC/global-workflow/pull/1991).

**Comment by WalterKolczynski-NOAA** [comment]
@jswhit What additional work is needed within workflow for this? Is it more than just changing the OCNRES associated with C96 (currently 500)?

**Comment by jswhit** [comment]
> @jswhit What additional work is needed within workflow for this? Is it more than just changing the OCNRES associated with C96 (currently 500)?

a bit more than that - see https://github.com/NOAA-EMC/global-workflow/pull/1991
