### ISSUE TITLE
Create & Add additional cpl fix files for additional resolutions being supported 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#1993]
### Target fix directory

cpl

### Type of change

- [ ] Update existing files
- [ ] Remove files
- [X] Add new files to existing directory
- [ ] Add new fix directory

### Any workflow changes needed?

No change needed

### Related issues

https://github.com/NOAA-EMC/global-workflow/issues/1981 https://github.com/NOAA-EMC/global-workflow/issues/1990 

Current resolutions: 
aC1152o025  aC192o050  aC384o025  aC48o500  aC768o025  aC96o100  aC96o500

Fix files to be created: 

aC48o100 
aC96o025
aC192o025

+ All other resolutions to so all combinations of C48, 192, 384, 768, 3072 with mx 025, 050, 100, 500. 

Please let me know if others are needed.  Should have a location with fix files later today. 

### Pickup location

Updated 12/15/23: 
/scratch1/NCEPDEV/climate/Jessica.Meixner/makegridspec/output/

### Size

780K

**Comment by JessicaMeixner-NOAA** [comment]
Correction, I need the files in #1981 to be in place (either in temporary space or final location) before I can create the grid_spec file.  @sanatcumar @barlage - can you ping me when the new resolutions are in /scratch2/NCEPDEV/stmp1/Sanath.Kumar/HR3_EP5 and I'll make the grid_spec files.

**Comment by JessicaMeixner-NOAA** [comment]
@sanatcumar @barlage @KateFriedman-NOAA I'm going to start making these fix files now that we have staged data here: /scratch1/NCEPDEV/global/glopara/fix/orog/20231027 for the added resolutions.  It seems like there are now pretty much every combination for  atm (48, 96,192, 384, 768, 1152, 3072) ocn (025,050,100,500).  Do we want cplfix files for every possible combination or just the previously desired additions: aC48o100 aC96o025  aC192o025

**Comment by aerorahul** [comment]
@JessicaMeixner-NOAA 
If it is easy enough to make, all possible combinations would be great.  If this recipe can be publicly shared, please consider adding it to ufs-utils.
Thanks!

**Comment by JessicaMeixner-NOAA** [comment]
@aerorahul  the instructions on how to make these files can be found here: https://github.com/NOAA-EMC/global-workflow/issues/1645 and are repeated here: 
These files were made following instructions from @bingfu-NOAA . This uses the make_coupler_mosaic from https://github.com/NOAA-GFDL/FRE-NCtools  

I'll do my best to fill out the matrix of files and share. I'll start with aC48o100 aC96o025 aC192o025 and go from there

**Comment by JessicaMeixner-NOAA** [comment]
@aerorahul not sure what should really be added to ufs-utils since it's in https://github.com/NOAA-GFDL/FRE-NCtools ?

**Comment by aerorahul** [comment]
Yes.  That jogs my memory.  `make_coupler_mosaic` is the command and it has a description on how to use it to create these `grid_specs`.  So nothing really. 

Just for making this self-documenting:
```bash
./make_coupler_mosaic --atmos_mosaic C96_mosaic.nc \
                      --ocean_mosaic ocean_mosaic.nc \
                      --ocean_topog ocean_topog.nc \
                      --mosaic_name grid_spec
```

**Comment by JessicaMeixner-NOAA** [comment]
New cplfix files have been generated and can be found on hera at: 

/scratch1/NCEPDEV/climate/Jessica.Meixner/makegridspec/output/ 

These add the grid_spec files for all of the various atm and ocean combinations that did not already exist.

**Comment by JessicaMeixner-NOAA** [comment]
Pinging  @KateFriedman-NOAA and @WalterKolczynski-NOAA  as I saw that the https://github.com/NOAA-EMC/global-workflow/issues/1981 has just been closed.  To support the various resolutions that the orog was added for, the cpl fix files also need to be updated now.  Please let me know if there is any additional information that you need from me for the new fix files to be resolved.

**Comment by KateFriedman-NOAA** [comment]
@JessicaMeixner-NOAA I have pulled the new cpl fix files into the `cpl/20230526` set on Hera (see listing below). Let me know the update looks good and I'll sync it to the other supported platform fix sets and close this issue as complete. Thanks!

```
[role.glopara@hfe04 20230526]$ pwd
/scratch1/NCEPDEV/global/glopara/fix/cpl/20230526
[role.glopara@hfe04 20230526]$ ll
total 112
drwxr-sr-x 2 role.glopara global 4096 May 25  2023 aC1152o025
drwxr-sr-x 2 role.glopara global 4096 Dec 15 17:33 aC1152o050
drwxr-sr-x 2 role.glopara global 4096 Dec 15 17:33 aC1152o100
drwxr-sr-x 2 role.glopara global 4096 Dec 15 17:33 aC1152o500
drwxr-sr-x 2 role.glopara global 4096 Dec 15 17:32 aC192o025
drwxr-sr-x 2 role.glopara global 4096 May 25  2023 aC192o050
drwxr-sr-x 2 role.glopara global 4096 Dec 14 21:23 aC192o100
drwxr-sr-x 2 role.glopara global 4096 Dec 14 21:17 aC192o500
drwxr-sr-x 2 role.glopara global 4096 Dec 15 18:32 aC3072o025
drwxr-sr-x 2 role.glopara global 4096 Dec 15 18:32 aC3072o050
drwxr-sr-x 2 role.glopara global 4096 Dec 15 18:32 aC3072o100
drwxr-sr-x 2 role.glopara global 4096 Dec 15 18:32 aC3072o500
drwxr-sr-x 2 role.glopara global 4096 May 25  2023 aC384o025
drwxr-sr-x 2 role.glopara global 4096 Dec 14 22:49 aC384o050
drwxr-sr-x 2 role.glopara global 4096 Dec 14 21:58 aC384o100
drwxr-sr-x 2 role.glopara global 4096 Dec 14 21:37 aC384o500
drwxr-sr-x 2 role.glopara global 4096 Dec 14 21:14 aC48o025
drwxr-sr-x 2 role.glopara global 4096 Dec 14 21:11 aC48o050
drwxr-sr-x 2 role.glopara global 4096 Dec 14 20:09 aC48o100
drwxr-sr-x 2 role.glopara global 4096 May 25  2023 aC48o500
drwxr-sr-x 2 role.glopara global 4096 May 25  2023 aC768o025
drwxr-sr-x 2 role.glopara global 4096 Dec 15 17:33 aC768o050
drwxr-sr-x 2 role.glopara global 4096 Dec 15 17:33 aC768o100
drwxr-sr-x 2 role.glopara global 4096 Dec 15 17:33 aC768o500
drwxr-sr-x 2 role.glopara global 4096 Dec 14 21:28 aC96o025
drwxr-sr-x 2 role.glopara global 4096 Dec 14 21:20 aC96o050
drwxr-sr-x 2 role.glopara global 4096 May 25  2023 aC96o100
drwxr-sr-x 2 role.glopara global 4096 May 25  2023 aC96o500
```

**Comment by JessicaMeixner-NOAA** [comment]
Spot check looks good.  Thanks @KateFriedman-NOAA !

**Comment by KateFriedman-NOAA** [comment]
Have rsync'd the new cpl fix files to Jet and submitted the rsync job on WCOSS2-Cactus. Will update WCOSS2-Dogwood when it's back from maintenance. @WalterKolczynski-NOAA please update the fix set on Orion, thanks!

**Comment by WalterKolczynski-NOAA** [comment]
Orion fix has been updated, as has Dogwood.

**Comment by KateFriedman-NOAA** [comment]
Thanks @WalterKolczynski-NOAA ! This issue is complete now. Closing.
