### ISSUE TITLE
Add C96/1 deg coupled model fix files for MOM6 and CICE6

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/global-workflow#2004]
### Target fix directory

cice, mom6

### Type of change

- [x] Update existing files
- [ ] Remove files
- [X] Add new files to existing directory
- [ ] Add new fix directory

### Any workflow changes needed?

Fix version only

### Related issues

As part of #1991 

Fix files for CICE and MOM6 at 1 deg need to be updated.

For `fix/cice/100` use:
`/scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/input-data-20221101/CICE_FIX/100` (from the ufs-weather-model regression test).

For `fix/mom6/100` use:
`/scratch1/NCEPDEV/global/glopara/fix/mom6/20220805/100` with `ufs.topo_edits_011818.nc` added from `/scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/input-data-20221101/MOM6_FIX/100`

`runoff.daitren.clim.1deg.nc plus oceanda_zgrid_75L.nc` added from `/scratch2/BMC/gsienkf/whitaker/global-workflow-jswhit/fix/mom6/100`

@jswhit; FYI

### Pickup location

See description above as there are several paths

### Size

Bigger than 0.

**Comment by WalterKolczynski-NOAA** [comment]
cice is going to need a new version since these are replacement files. Given that, I have questions about why 1º needs to change but none of the other resolutions do.

For mom6, adding new files is easy, but we already have a `topo_edits_011818.nc` (it differs from this `ufs.topo_edits_011818.nc`). Should the existing one just be replaced instead?

**Comment by WalterKolczynski-NOAA** [comment]
@jswhit looking for answers to a couple questions before I proceed on updating the fix files.

**Comment by jswhit** [comment]
@WalterKolczynski-NOAA, regarding the topo_edits question, I would suggest replacing the existing file.  For the cice question, I would defer to @guillaumevernieres (all I know is that I had to use the fix files from the regression test to make it work)

**Comment by WalterKolczynski-NOAA** [comment]
Thanks @jswhit, that helps.
