### ISSUE TITLE
[GOCART] Update fix file for dust for EP experiments 

### ISSUE THREAD

**Issue by bbakernoaa** [NOAA-EMC/global-workflow#2005]
### Target fix directory

aer

### Type of change

- [X] Update existing files
- [ ] Remove files
- [X] Add new files to existing directory
- [ ] Add new fix directory

### Any workflow changes needed?

Fix version only

### Related issues

#

### Pickup location

/scratch1/RDARCH/rda-arl-gpu/Barry.Baker/emissions/nexus/FENGSHA/FENGSHA_2022_NESDIS_inputs_10km_v3.2.nc

### Size

57

**Comment by WalterKolczynski-NOAA** [comment]
Just the one file?

And you want this in fix/aer and not just synchronize the (separate) gocart_emissions directory?

**Comment by bbakernoaa** [comment]
Yea we just need to move the one file.  It doesn't need to be completely resynced

**Comment by WalterKolczynski-NOAA** [comment]
Okay, but do you want it in `fix/aer` or in `AERO_INPUTS_DIR` (what gets linked as `ExtData`)?

**Comment by JessicaMeixner-NOAA** [comment]
@bbakernoaa should confirm, but I believe it's this directory on hera for the destination /scratch1/NCEPDEV/global/glopara/data/gocart_emissions/nexus/FENGSHA

But Barry should confirm before it's moved

**Comment by bbakernoaa** [comment]
@JessicaMeixner-NOAA should be good

**Comment by WalterKolczynski-NOAA** [comment]
Synchronized on Hera, Orion, and Dogwood. Cactus is running.

**Comment by WalterKolczynski-NOAA** [comment]
Synchronization to Cactus finally completed (it must've been behind).
