### ISSUE TITLE
Update to ufs-weather-model hash utilizing spack 1.5 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#2006]
### What new functionality do you need?

Routine update of ufs-weather-model, this is of particular interest as it updates scotch to 7.0.4 for RDHCPS.  It also includes an update of spack-stack to 1.5.   

### What are the requirements for the new functionality?

Using latest ufs-wather-model https://github.com/ufs-community/ufs-weather-model/commit/812aac58be7f7e737d2194f1431954ea3fdd9d60 from 10/30 (or later) 

### Acceptance Criteria

All tests pass

### Suggest a solution (optional)

I ran a quick test with this and here's two changes I've noticed, which is why I wanted to make the issue: 

1. in ush/load_ufswm_modules.sh   prod-util -> prod_util 
2. For hera there is a section: 

```
if [[ "${MACHINE_ID}" = "hera" ]]; then
  module use "/scratch2/NCEPDEV/ensemble/save/Walter.Kolczynski/modulefiles/core"
  module load "miniconda3/4.6.14"
  module load "gfs_workflow/1.0.0"
fi
```
which I had to comment out to get things to work, because there was an error when trying to load this module.  I'm not sure if someone knows if I'm going to run into another issue by commenting this out, but I at least now have the forecast job in the queue.

**Comment by DavidHuber-NOAA** [comment]
This was resolved with PR #2071.  Closing.
