### ISSUE TITLE
add Wave init job to GEFS free forecast

### ISSUE THREAD

**Issue by NeilBarton-NOAA** [NOAA-EMC/global-workflow#2017]
### What new functionality do you need?

Add the wave prep job that creates the mod def file (inp2moddef) to the GEFS free forecasting g-w configuration 

### What are the requirements for the new functionality?

a new task dependency in the GEFS g-w configuration 

### Acceptance Criteria

wave mod def file will be created at the beginning of a g-w GEFS suite to be used for the free forecasts

### Suggest a solution (optional)

- Hopefully existing scripts for GFS g-w can be re-used.

**Comment by JessicaMeixner-NOAA** [comment]
@NeilBarton-NOAA What you are describing is called  WAVE_INIT and we do have a job: https://github.com/NOAA-EMC/global-workflow/blob/develop/jobs/JGLOBAL_WAVE_INIT 
--- Note there is also a wave prep job, and while this was used in both GFSv16 and GEFSv12 to prepare ice and other non-coupled forcing, we do not need this for GEFSv13. 

The existing script should be sufficient, might need minor updates for CDUMP=GEFS   

FYI @sbanihash

**Comment by NeilBarton-NOAA** [comment]
Thanks @JessicaMeixner-NOAA. I updated the title to avoid confusion between these jobs

**Comment by NeilBarton-NOAA** [comment]
Could the mod_def file created from the wave init job just be treated as a fix file? 

This file only changes when the grid or the time steps changes in the wave model.

**Comment by JessicaMeixner-NOAA** [comment]
That is a larger change.  At this time, it's not being treated as a fix file.  What is the issue with this job? Is it that it's simply not added to the rocoto or is there some issue about how it's being generated or used when CDUMP=gefs?
