### ISSUE TITLE
Bug in hpssarch_gen.sh

### ISSUE THREAD

**Issue by kevindougherty-noaa** [NOAA-EMC/global-workflow#2022]
### What is wrong?

There is a missing `$` in `ush/hpssarch_gen.sh` causing errors and failure of jobs. The output of how the files are being read in from the log file is shown below:
```
+ hpssarch_gen.sh[168](gfs): echo 'gfs.20210801/18//products/atmos/grib2/1p00/{head}pgrb2b.1p00.f000'
+ hpssarch_gen.sh[169](gfs): echo 'gfs.20210801/18//products/atmos/grib2/1p00/{head}pgrb2b.1p00.f000.idx'
```

### What should have happened?

`{head}` should be `${head}` to provide the correct header.

### What machines are impacted?

All or N/A

### Steps to reproduce

Worked for a few cycles and failed on the 4th cycle.

### Additional information

N/A

### Do you have a proposed solution?

In lines 168-169 of `ush/hpssarch_gen.sh` should corrected as:

```
echo "${COM_ATMOS_GRIB_1p00/${ROTDIR}\//}/${head}pgrb2b.1p00.f${fhr}"
echo "${COM_ATMOS_GRIB_1p00/${ROTDIR}\//}/${head}pgrb2b.1p00.f${fhr}.idx"
```

**Comment by HenryRWinterbottom** [comment]
@kevindougherty-noaa Can you please try your experiment using my forked [branch](https://github.com/HenryWinterbottom-NOAA/global-workflow/tree/bug/gw_issue_2022) and let me know whether this resolves the issue that you raised. 

Thank you.

**Comment by kevindougherty-noaa** [comment]
@HenryWinterbottom-NOAA This worked for me, thank you for the quick fix.

**Comment by HenryRWinterbottom** [comment]
@kevindougherty-noaa No problem. Thank you for testing.
