### ISSUE TITLE
Orion GDASApp build fails with -j 16

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/global-workflow#2029]
### What is wrong?

`sorc/build_all.sh` specifies 16 threads to build GDASApp.
```
 # Optional DA builds
 if [[ -d gdas.cd ]]; then
   build_jobs["gdas"]=16
    big_jobs=$((big_jobs+1))
    build_opts["gdas"]="${_verbose_opt}"
 fi
```
Two attempts to build GDASApp on Orion with 16 threads failed with a compilation error.  

### What should have happened?

`build_all.sh` should run to completion with all apps successfully built.

### What machines are impacted?

Orion

### Steps to reproduce

1. clone g-w develop
2. execute `sorc/checkout.sh -u`
3. execute `sorc/build_all.sh`

### Additional information

`build_all.sh` successfully build GDASApp on Hera using 16 threads.

### Do you have a proposed solution?

I suspect the compilation failure highlights a problem in GDASApp build dependencies.   Correcting this may need to be done in consultation with the JCSDA JEDI core team.   For the interim propose the following simple fix.

Previously g-w `build_gdas.sh` defaulted to 8 threads to build GDASApp.   I changed the number of GDASApp threads in `build_all.sh` to 8

```
 # Optional DA builds
 if [[ -d gdas.cd ]]; then
   build_jobs["gdas"]=8
    big_jobs=$((big_jobs+1))
    build_opts["gdas"]="${_verbose_opt}"
 fi
```

With this change, the GDASApp build successfully completed.

**Comment by DavidHuber-NOAA** [comment]
Testing `./build_gdas.sh -j 16` reveals the same problem as found by @RussTreadon-NOAA with the following error reported:
```
icpc: error #10106: Fatal error in /apps/intel-2022.1.2/intel-2022.1.2/compiler/2022.0.2/linux/bin/intel64/../../bin/intel64/mcpcom, terminated by kill signal
compilation aborted for /work/noaa/global/dhuber/GW/gw_opt_build/sorc/gdas.cd/fv3-jedi/src/mains/fv3jediEDA.cc (code 1)
```

I'm guessing this is a memory issue.  I will take your suggestion and decrease the number of builds to 8 by default.
