### ISSUE TITLE
Upload grib2 template for gfs-utils/ush/nc2grb scripts

### ISSUE THREAD

**Issue by GwenChen-NOAA** [NOAA-EMC/global-workflow#2040]
### Target fix directory

NEW

### Type of change

- [ ] Update existing files
- [ ] Remove files
- [ ] Add new files to existing directory
- [X] Add new fix directory

### Any workflow changes needed?

No change needed

### Related issues

https://github.com/NOAA-EMC/gfs-utils/pull/32

### Pickup location

/lfs/h2/emc/vpppg/noscrub/Lichuan.Chen/nc2grb/template.global.0p25.gb2
/lfs/h2/emc/vpppg/noscrub/Lichuan.Chen/nc2grb/template.global.0p5.gb2
/lfs/h2/emc/vpppg/noscrub/Lichuan.Chen/nc2grb/template.global.1p0.gb2
/lfs/h2/emc/vpppg/noscrub/Lichuan.Chen/nc2grb/template.global.5p0.gb2

The instruction to create a template (such as above) is at:
https://www.cpc.ncep.noaa.gov/products/wesley/wgrib2/netcdf_2_grib_ostia.html

Or use [wgrib2 -new_grid option](https://www.cpc.ncep.noaa.gov/products/wesley/wgrib2/new_grid.html) to regrid a template. For example:

wgrib2 template.global.0p25.gb2 -set_grib_type same -new_grid_winds earth `\`
  -new_grid latlon 0:720:0.5 -90:361:0.5 template.global.0p5.gb2

### Size

2.6 MB

**Comment by aerorahul** [comment]
@GwenChen-NOAA 
I updated the issue to document instructions to create the template file being added in this PR.
For explictness, can you provide exactly what you ran to create this 0p25 global template?
The instructions on the wgrib2 site point to some `aec` file and I am not sure where that is.

**Comment by GwenChen-NOAA** [comment]
@aerorahul, I asked Wesley the same question when I first read the instructions. He said the gep19.aec file is a random GRIB2 file. You can use any GRIB2 file. Since I already have a GRIB2 template file, you can use it to create a new template file of a new grid using [wgrib2 -new_grid option](https://www.cpc.ncep.noaa.gov/products/wesley/wgrib2/new_grid.html). I used the following commands to create two new templates for 0.5 and 1.0 degree latlon grid, assuming that they have the same starting point (0, -90) as the 0.25 degree netCDF files from ocnicepost:

wgrib2 template.global.0p25.gb2 -set_grib_type same -new_grid_winds earth `\`
  -new_grid latlon 0:720:0.5 -90:361:0.5 template.global.0p5.gb2

wgrib2 template.global.0p25.gb2 -set_grib_type same -new_grid_winds earth `\`
  -new_grid latlon 0:360:1 -90:181:1 template.global.1p0.gb2

You can upload all 3 templates together. Let me know if more clarifications are needed. Thanks!

**Comment by WalterKolczynski-NOAA** [comment]
Since these are only 2.6 MB, should these just be `parm` files instead?

**Comment by aerorahul** [comment]
@WalterKolczynski-NOAA they are binary files.  They should not be in the repository.

**Comment by KateFriedman-NOAA** [comment]
The template files have been added to the `fix/mom6/20231219` set and synced to supported platforms:
```
[role.glopara@hfe02 fix]$ pwd
/scratch1/NCEPDEV/global/glopara/fix
[role.glopara@hfe02 fix]$ ll mom6/20231219/post/template.global.*
-rw-r--r-- 1 role.glopara global 2076659 Oct 10 20:23 mom6/20231219/post/template.global.0p25.gb2
-rw-r--r-- 1 role.glopara global  520019 Nov  7 16:45 mom6/20231219/post/template.global.0p50.gb2
-rw-r--r-- 1 role.glopara global  130499 Nov  7 16:47 mom6/20231219/post/template.global.1p00.gb2
-rw-r--r-- 1 role.glopara global    5363 Jan 31 19:01 mom6/20231219/post/template.global.5p00.gb2
```

**Comment by KateFriedman-NOAA** [comment]
@GwenChen-NOAA was there anything else needed for this issue or can we close it now? Thanks!

**Comment by KateFriedman-NOAA** [comment]
Sorry, closed it by accident.

**Comment by GwenChen-NOAA** [comment]
@Kate Friedman - NOAA Federal ***@***.***>, you got them all.
You may close this issue now. Thanks for your help!

**Comment by KateFriedman-NOAA** [comment]
Thanks for confirming @GwenChen-NOAA ! Closing this as complete.
