### ISSUE TITLE
UPP fails to build on orion 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#2041]
### What is wrong?

There's an issue with the jasper module when trying to build UPP on orion with develop.  See log: 

/work2/noaa/marine/jmeixner/HR3/develop/global-workflow/sorc/logs/build_upp.log
```
+ cd ufs_model.fd/FV3/upp/tests
+ ./compile_upp.sh
Machine:  orion
Building for machine orion, compiler intel
Lmod has detected the following error: These module(s) or extension(s) exist
but cannot be loaded as requested: "jasper/2.0.25"
   Try: "module spider jasper/2.0.25" to see how to load the module(s).

Executing this command requires loading "jasper/2.0.25" which failed while
processing the following module(s):

    Module fullname  Module Filename
    ---------------  ---------------
    orion            /work2/noaa/marine/jmeixner/HR3/develop/global-workflow/sorc/ufs_model.fd/FV3/upp/modulefiles/orion.lua

```

### What should have happened?

UPP should build successfully in develop on orion.   

Not sure if there's some new module issue as it says build completed on the last PR to g-w: 
https://github.com/NOAA-EMC/global-workflow/pull/1989#issuecomment-1796975381

### What machines are impacted?

Orion

### Steps to reproduce

git clone g-w 
cd g-w 
cd sorc 
sh checkout.sh 
sh build_all.sh 

### Additional information

```
$ module use /work2/noaa/marine/jmeixner/HR3/unstruc/global-workflow/sorc/ufs_model.fd/FV3/upp/modulefiles
$ module load orion
Lmod has detected the following error:  These module(s) or extension(s) exist but cannot be loaded as
requested: "jasper/2.0.25"
   Try: "module spider jasper/2.0.25" to see how to load the module(s).

Executing this command requires loading "jasper/2.0.25" which failed while processing the following module(s):

    Module fullname  Module Filename
    ---------------  ---------------
    orion            /work2/noaa/marine/jmeixner/HR3/unstruc/global-workflow/sorc/ufs_model.fd/FV3/upp/modulefiles/orion.lua


$ module spider jasper/2.0.25

----------------------------------------------------------------------------------------------------------------------
  jasper: jasper/2.0.25
----------------------------------------------------------------------------------------------------------------------

    You will need to load all module(s) on any one of the lines below before the "jasper/2.0.25" module is available to load.

      intel/2022.1.2
```

**Comment by aerorahul** [comment]
@JessicaMeixner-NOAA 
Someone moved the modules on Orion. 
There was no notification of this change.
We are trying to figure out who, when, why.

**Comment by DavidHuber-NOAA** [comment]
@JessicaMeixner-NOAA The hpc-stack that was under /work/noaa/epic-ps has been deleted.  In fact, the entire epic-ps parent directory has been removed.  IIRC, the epic-ps directory was not owned by EPIC, and the installation ended up there by accident.  The [orion.lua modulefile](https://github.com/NOAA-EMC/UPP/blob/7fbc41308cd7cea5d65dec3335c96ab2c5c1d7c3/modulefiles/orion.lua#L8) could probably be redirected to `/work/noaa/epic/role-epic/contrib/hpc-stack/intel-oneapi-2022.2.1`.

That said, I will be upgrading UPP modulefiles to spack-stack soon.

**Comment by WalterKolczynski-NOAA** [comment]
There's already a UPP PR open that looks almost done to move to spack-stack. But who knows how long it will then take to be picked up and merged by UFS.

**Comment by WalterKolczynski-NOAA** [comment]
Going to put in a work-around today.

**Comment by WalterKolczynski-NOAA** [comment]
Not quite working yet. Things build, but the job fails due to a missing library. Need to load the UPP modules for postanl as well.
