### ISSUE TITLE
Add --cpus-per-task to APRUN commands for Hera and Orion

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#2044]
### What new functionality do you need?

After update to SLURM version on Orion we need to now set the `--cpus-per-task` flag with the srun command.

Also add flag for srun commands on Hera for consistency even though workaround was implemented by sysadmins there.

Issue #1996 documents a slowdown in the analysis job (`gsi.x`), troubleshooting with Orion helpdesk, and resulting solution tested by @RussTreadon-NOAA . A hotfix is being made to add the flag for the analysis job. Now investigate adding the flag for all job srun commands on Orion.

Comments from helpdesk:
```
Russ, I've been digging into this, and I spotted something this time. You and another user who's been having a 
similar slowdown issue with a completely different package have the same sbatch directive:

#SBATCH --cpus-per-task=10

Per the slurm release page:

"NOTE: Beginning with 22.05, srun will not inherit the --cpus-per-task value requested by salloc or sbatch. It 
must be requested again with the call to srun or set with the SRUN_CPUS_PER_TASK environment variable if 
desired for the task(s). "

I have actually just been testing using

#SBATCH --ntasks=400

since this test is nodes=10, with 40 tasks per node, and it appears to be MUCH faster.

For your submission, you should use the same I believe, --ntasks=400.
```
```
The following change was implemented on NOAA's R&D HPC systems after upgrading
to version 22.05.6.

There has been a change of behavior in Slurm going from 21.08.8-2 to 22.05.6.
In 21, when srun was run from an sbatch-submitted job script, it inherited the
cpus-per-task from the sbatch environment. In 22, srun seems to default to
cpus-per-task=2 instead of inheriting from the sbatch environment. This causes
massive slowdowns in jobs which are expecting the 21.x inheritance behavior.

We are adding the following line to Hera's task prolog:
echo export SRUN_CPUS_PER_TASK=$SLURM_CPUS_PER_TASK

This line sets the contents of the SRUN_CPUS_PER_TASK variable (used by srun)
to whatever the existing contents of the SLURM_CPUS_PER_TASK were, thus
emulating the 21.x behavior.
```

### What are the requirements for the new functionality?

The new flag works on Hera and Orion.

### Acceptance Criteria

Jobs run at same speed (or faster). Evaluate speed.

### Suggest a solution (optional)

Add `--cpus-per-task $THREAD_VAR` to each job in `HERA.env` and `ORION.env`.

**Comment by KateFriedman-NOAA** [comment]
Tested against control run on both Hera and Orion. Ran 5.5 cycles on Orion and 1.5 on Hera. No noticeable speed-up of any jobs by having the `--cpus-per-task` flag added to all of the `APRUN` commands. Timings the same with the usual variations.

**Comment by KateFriedman-NOAA** [comment]
@RussTreadon-NOAA @CoryMartin-NOAA I'm looking to see if any of the CFP/multi-prog processes in the GSI/ENKF jobs need threading and therefore need the `--cpus-per-task` flag on Orion and Hera. In a short cycled atmos-only test I see the following instances of `--multi-prog` on Orion for GSI/ENKF jobs:

```
logs/2021122200/enkfgdasechgres.log:+ exgdas_atmos_chgres_forenkf.sh[177]: srun -l --export=ALL -n 3 --multi-prog --output=mpmd.%j.%t.out /work/noaa/stmp/kfriedma/RUNDIRS/testsruncpus/echgres.206341/mp_chgres.sh
logs/2021122200/enkfgdasediag.log:+ exglobal_diag.sh[230]: srun -l --export=ALL -n 34 --multi-prog --output=mpmd.%j.%t.out /work/noaa/stmp/kfriedma/RUNDIRS/testsruncpus/ediag.305871/mp_diag.sh
logs/2021122200/enkfgdaseupd.log:+ exgdas_enkf_update.sh[247]: srun -l --export=ALL -n 1 --multi-prog --output=mpmd.%j.%t.out /work/noaa/stmp/kfriedma/RUNDIRS/testsruncpus/eupd.342114/mp_untar.sh
logs/2021122200/gdasanaldiag.log:+ exglobal_diag.sh[230]: srun -l --export=ALL -n 84 --multi-prog --output=mpmd.%j.%t.out /work/noaa/stmp/kfriedma/RUNDIRS/testsruncpus/analdiag.142664/mp_diag.sh
logs/2021122200/gdasanal.log:+ exglobal_atmos_analysis.sh[667]: srun -l --export=ALL -n 27 --multi-prog --output=mpmd.%j.%t.out /work/noaa/stmp/kfriedma/RUNDIRS/testsruncpus/anal.283998/mp_unzip.sh
```

It doesn't seem like we need threading for these mpmd commands, based on what they are doing and how we treat them with CFP on WCOSS2...but I wanted to double check with you both. Thanks!

**Comment by RussTreadon-NOAA** [comment]
Without going through all the DA jobs, here's my two cents.  Let's follow what is done on WCOSS2.  If a DA job is not threaded on WCOSS2, let's keep it not threaded on other platforms until we find a reason / need to turn on threading.

**Comment by KateFriedman-NOAA** [comment]
> Let's follow what is done on WCOSS2. If a DA job is not threaded on WCOSS2, let's keep it not threaded on other platforms until we find a reason / need to turn on threading.

Sounds good to me! Thanks @RussTreadon-NOAA !
