### ISSUE TITLE
Archive job should wait for analysis post

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#2048]
### What is wrong?

When the analysis post was added as a separate job, it was not added to the list of jobs archive needs to wait for before launching. This can cause incomplete tarballs and (because cleanup follows arch) premature data removal.

### What should have happened?

The archive job should wait for postanl.

### What machines are impacted?

All or N/A

### Steps to reproduce

1. Setup a cycle experiment
2. Kill the postanl job
3. Watch the workflow proceed to archival despite the postanl job not completing successfully

### Additional information

None

**Comment by KateFriedman-NOAA** [comment]
Will fold changes to resolve this into branch for issue #1988 and PR #2058.

**Comment by KateFriedman-NOAA** [comment]
For this work I am also changing the archive job dependencies so the post metatask is always included, instead of only when there aren't other dependencies.

The updated archive job dependencies in the generated xmls will now be (with fit2obs/tracker/GSI monitor turned on):

gdasarch:
```
        <dependency>
                <and>
                        <taskdep task="gdasvrfy"/>
                        <metataskdep metatask="gdaspost"/>
                        <or>
                                <and>
                                        <taskdep task="gdaspostanl"/>
                                        <taskdep task="gdasfit2obs"/>
                                        <taskdep task="gdasverfozn"/>
                                        <taskdep task="gdasverfrad"/>
                                        <taskdep task="gdasvminmon"/>
                                </and>
                                <not><cycleexistdep cycle_offset="-06:00:00"/></not>
                        </or>
                </and>
        </dependency>
```
gfsarch:
```
        <dependency>
                <and>
                        <taskdep task="gfspostanl"/>
                        <taskdep task="gfsvminmon"/>
                        <taskdep task="gfstracker"/>
                        <taskdep task="gfsgenesis"/>
                        <taskdep task="gfsvrfy"/>
                        <metataskdep metatask="gfspost"/>
                </and>
        </dependency>
```
