### ISSUE TITLE
UFSWM compression configuration changes

### ISSUE THREAD

**Issue by DusanJovic-NOAA** [NOAA-EMC/global-workflow#2053]
### What new functionality do you need?

UFSWM lossy compression will be changed to use netcdf quantization routine instead of builtin routines currently used in the model.

The UFSWM PR that implements this change is https://github.com/ufs-community/ufs-weather-model/pull/1990

### What are the requirements for the new functionality?

 This requires the change in `model_configure` file. The two new options will be added:

- `quantize_mode:` character string. Possible values 'quantize_bitgroom', 'quantize_granularbr', 'quantize_bitround'
- `quantize_nsd:` integer, number of significant digits.

See documentation [here](https://docs.unidata.ucar.edu/netcdf-c/current/md__media_psf_Home_Desktop_netcdf_releases_v4_9_2_release_netcdf_c_docs_quantize.html).

Current option that controls the quantization `nbits:` will be removed. 

### Acceptance Criteria

`model_configure` file must be updated to use new configuration options.

**Comment by aerorahul** [comment]
@DusanJovic-NOAA I can take care of this via #2051

**Comment by WalterKolczynski-NOAA** [comment]
Completed by #2051
