### ISSUE TITLE
Add Kill Switch (Label) to CI

### ISSUE THREAD

**Issue by TerrenceMcGuinness-NOAA** [NOAA-EMC/global-workflow#2067]
### What new functionality do you need?

Add a new Label MACINE-Kill that Removes PR from the CI System entirely and does not restart it.

NOTE: All the functionality for this feature is already in place with [PR 2093](https://github.com/NOAA-EMC/global-workflow/pull/2093) and should not take much programming effort.

### What are the requirements for the new functionality?

When ever a previously issued Read label PR CI test is in progress this Label update by the user will:
- Have it removed from the test suite (and data base)
- Kill the all the build scripts the CI is currently building when the kill switch is issued
- Purge the test directories from the file system
- Remove all jobs in scheduler all running from that PR

### Acceptance Criteria

Test in CI cron development environment and above capabilities can be demonstrated.

### Suggest a solution (optional)

Update the check CI bash  script to read the db state record and include a time stamp to react to this case.
This can also be used for when ever PR is merged and there are labels other than **PASSED**

**Comment by WalterKolczynski-NOAA** [comment]
OBE
