### ISSUE TITLE
GOCART AOD files not copied properly

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/global-workflow#2072]
### What is wrong?

The GOCART instantaneous AOD is hard-coded to write out every 6 hours, but the copy routine at the end of the forecast job uses `${FV3_OUTPUT_FH}` to loop through the forecast hours to copy these diagnostic files.

### What should have happened?

These should be consistent. I know the `AERO_HISTORY.rc` file is not dynamic, so perhaps the simplest solution is to force the GOCART POSTDET routine to use 6 hour periods only, but Ideally the AERO_HISTORY file would be configurable.

### What machines are impacted?

All or N/A

### Steps to reproduce

Run the GDAS forecast in ATMA mode 

### Additional information

@andytangborn found the bug

**Comment by WalterKolczynski-NOAA** [comment]
Possibly related: #1629

**Comment by CoryMartin-NOAA** [comment]
This issue will be a blocker for an aerosol 3DVar test. @aerorahul there is a quick fix (not sure it is the best one) to hard code `forecast_postdet` to match the hard code in the fix file. Longer term, the fix file would probably be best generated, but that is non-trivial due to the format. To be honest, it would surprise me if these gocart diagnostic files see the light of day in ops, when we would have UPP computing AOD for products, so perhaps it's best to do the hard code to every 6 hours?

**Comment by CoryMartin-NOAA** [comment]
FYI @aerorahul this is still an issue that blocks adding an aerosol 3DVar test.
