### ISSUE TITLE
Wrong default permissions on jobs/rocoto/postsnd.sh script in new clones of develop

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#208]
Users are reporting failing gfspostsnd jobs. In all cases reported the jobs/rocoto/postsnd.sh script did not have execute permissions on it. A fresh clone of develop on Hera shows the problem:

```
-bash-4.2$ ll jobs/rocoto/
total 20
...
-rwxr-xr-x 1 Kate.Friedman global  1720 Dec  9 20:12 post.sh
-rw-r--r-- 1 Kate.Friedman global   339 Dec  9 20:12 postsnd.sh
-rwxr-xr-x 1 Kate.Friedman global  4340 Dec  9 20:12 prep.sh
...
```

Fix permissions to set executing "x" for that script.

**Comment by RussTreadon-NOAA** [comment]
This problem also exists in release/gfs.v16.0.0.  

 jobs/rocoto/postsnd.sh has file permissions **-rw-r--r--**.

**Comment by KateFriedman-NOAA** [comment]
Corrected in release/gfsv16.0.0 at 7c7482d.

**Comment by RussTreadon-NOAA** [comment]
Thanks, Kate.   We now have

.../noscrub/emc.glopara/git/global-workflow/release_gfsv16> ls -l
> jobs/rocoto/postsnd.sh
> -rwxr-xr-x 1 emc.glopara emcmodel 339 Dec 10 14:40 jobs/rocoto/postsnd.sh
>

Russ
