### ISSUE TITLE
feature/coupled-crow: add resources for wave post jobs

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#209]
The wave post jobs wavepost and wavepostpnt should have their own resource settings.  Right now they are just using 
      resources: !calc partition.resources.run_fv3ic

When looking into the file workflow/defaults/default_resources.yaml
`# !!! Model developers should NOT changing these !!!
`
so it's unclear to me if this should be changed by a CROW expert (such as @JianKuang-NOAA) or if it's okay to go ahead and add these myself.

**Comment by jkuang-exploro** [comment]
You should be able to add them to default_resources.yaml, if you want these resource settings to be individually configured.

Just copy/paste and modify run_fv3ic

**Comment by JessicaMeixner-NOAA** [comment]
@JianKuang-NOAA  thanks I'll add these myself then

**Comment by JessicaMeixner-NOAA** [comment]
@JianKuang-NOAA my test on orion also succeeded.  I started with a fresh clone and build so it's taking a little longer on hera.  

@LydiaStefanova-NOAA and @jiandewang could you help check output   Lydia note that atm files are now in the "atmos" subfolder 
The test on orion output is here: /work/noaa/marine/jmeixner/p6pr194update/test02/COMROOT/test02/gfs.20130401/00 I'll post the hera test as soon as it's available.

**Comment by JianKuang-NOAA** [comment]
@JessicaMeixner-NOAA Cool. Thanks. I don't think the results could be bit-reproducible with feature/coupled-crow. Since some default values of name list variables are modified to match develop branch. Actually that's the reason why I didn't match them at the first attempts.

**Comment by JessicaMeixner-NOAA** [comment]
@JianKuang-NOAA I seem to have written on the wrong github issue.  the above comment should be for the PR.. I'm going to move this conversation to the PR and remove it from this issue.

**Comment by LydiaStefanova-NOAA** [comment]
In atmos/ the grib2 files look ok to me. 

In wave/ the gfswave.t00z.global.0p50.fXXX.grib2 files all fields I checked are constant (i.e. identical value at any lat/lon)

Two other things I noticed, that may or may not be relevant here, mentioning them in case they are: 
(a) The variable called "la_mod" in the waveocn_*nc files has possibly strange values (e.g the max is 5.37e+34 in wavocn_2013_04_01_03.nc, 8.9301E+08 in wavocn_2013_04_02_21.nc). I haven't looked at this type of files before, so I don't know if this is normal. 
(b) the archlist contents (now under atmos/archlist) are different from what we had for P5. I can describe the differences in more detail if this is relevant now.

**Comment by JessicaMeixner-NOAA** [comment]
@LydiaStefanova-NOAA thank you so much for your thorough review of all of these things.  We know that the arch list is not perfect and will take care of that later.  The bad wave grib files is another known issue that this PR is not supposed to address.   the la_mod does have very large values at times.  That was there before.

**Comment by jiandewang** [comment]
checking ocean outputs show reasonable value (both orion and hera), but confirmed with Lydia's point about LA_MOD

**Comment by JessicaMeixner-NOAA** [comment]
Completed in PR#255
