### ISSUE TITLE
add tob in ocean output

### ISSUE THREAD

**Issue by jiandewang** [NOAA-EMC/global-workflow#2104]
### What new functionality do you need?

@pjpegion informed to Gwen and me that fisheries are working on marine heatwaves, and they need the bottom temperature from the ocean, which is a variable available in MOM6 (tob).

### What are the requirements for the new functionality?

add variable "tob" in diag_table so that this variable will be in ocean output file

### Acceptance Criteria

variable "tob" be in ocean output file. To make it consistency between g-w and rt.sh, I will also add this variable in rt.sh through a mini PR (https://github.com/ufs-community/ufs-weather-model/issues/2019)

**Comment by WalterKolczynski-NOAA** [comment]
Resolved by #2105
