### ISSUE TITLE
Update wave fix file in the workflow based on an updated parameter value (Betamax) in WAVEWATCH III

### ISSUE THREAD

**Issue by sbanihash** [NOAA-EMC/global-workflow#2107]
### Target fix directory

wave

### Type of change

- [x] Update existing files
- [ ] Remove files
- [ ] Add new files to existing directory
- [ ] Add new fix directory

### Any workflow changes needed?

Fix version only

### Pickup location

/lfs/h2/emc/couple/noscrub/saeideh.banihashemi/git/fv3gfs/fix/fix_wave_gefs_bm1p5

### Size

0

**Comment by sbanihash** [comment]
The pickup location is on Dogwood.

**Comment by JessicaMeixner-NOAA** [comment]
@sbanihash Its my understanding that they type of change is an update to existing files, not adding a new file.  Moreover, it's just changing 1 of the fix files, not all of them, perhaps it'd be good to specify that here so we have a record of exactly what is being changed.

**Comment by sbanihash** [comment]
@JessicaMeixner-NOAA I updated the Type of change. The file being changed is ww3_grid.inp.

**Comment by JessicaMeixner-NOAA** [comment]
@sbanihash it's changing the value to BETAMAX = 1.5 in just the single file ww3_grid.inp.glo_025 correct?

**Comment by sbanihash** [comment]
@JessicaMeixner-NOAA Yes you are correct. Sorry I thought I edited the previous comment to include that. 

I can confirm that this is only changing the BETAMAX value to 1.5 in the ww3_grid.inp.glo_025 file

**Comment by JessicaMeixner-NOAA** [comment]
I added this to the "GEFSv13" Project as this will be needed for EP5/GEFS and tagging @bingfu-NOAA @NeilBarton-NOAA for their awareness

**Comment by sbanihash** [comment]
@WalterKolczynski-NOAA following up on this issue since it is needed for EP4 experiments. Please let me know if any additional information is needed at this stage.

**Comment by WalterKolczynski-NOAA** [comment]
New wave fix version added as `20240105`. I'll take care of updating the version in workflow, as I'll package it with a few other fix version updates.
