### ISSUE TITLE
filename incorrect in forecast_det.sh when restart directory exists

### ISSUE THREAD

**Issue by jkhender** [NOAA-EMC/global-workflow#2108]
### What is wrong?

Filenames are incorrect at line 70. They are missing the extra '0000' after ${cycs} as in line 69:

 68       # Check for availability of FV3 restarts
 69       if [[ -f "${COM_ATMOS_RESTART}/${PDYS}.${cycs}0000.coupler.res" ]]; then
 70         mv "${COM_ATMOS_RESTART}/${PDYS}.${cycs}.coupler.res" "${COM_ATMOS_RESTART}/${PDYS}.${cycs}.coupler.res.old"
 71       else
 72         local fv3_rst_ok="NO"
 73       fi

### What should have happened?

The file would be renamed.

### What machines are impacted?

All or N/A

### Steps to reproduce

1) run free forecast
2) rerun cycle which should have restart directory created from previous run

### Additional information

none

**Comment by aerorahul** [comment]
@jkhender 
Thanks for reporting this bug.
The development team is in the process of revamping the rerun on failure capability for the coupled model and will prioritize the work in the next few months.

**Comment by KateFriedman-NOAA** [comment]
This has been fixed in PR #2210. Closing.
