### ISSUE TITLE
No Build Restart

### ISSUE THREAD

**Issue by TerrenceMcGuinness-NOAA** [NOAA-EMC/global-workflow#2120]
### What new functionality do you need?

Once CI launches are done using GitHub Actions Dispatch, have one selection for restarting a PR that has been built once already and just do a Pull, and run setup_expt.py on RUNDIR/EXDIR and then start over all the CI Tests.

### What are the requirements for the new functionality?

Once moved away from Launching from READY labels we can have a drop down selector from the Dispatch Action to do the above.

### Acceptance Criteria

The functionality described above can work end-to-end from within GitHub.

**Comment by WalterKolczynski-NOAA** [comment]
This looks like a duplicate of #1980
