### ISSUE TITLE
Eliminate all machine detection outside of detect_machine.sh

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#2129]
### What new functionality do you need?

`ush/detect_machine.sh` should be the only place where the machine is identified.

### What are the requirements for the new functionality?

Only `detect_machine.sh` should be looking at paths or hostnames for the purpose of determining what machine the script is being run on. All others scripts with machine-specific code should use the `${MACHINE_ID}` variable set by that script to determine branching paths.

This may require expansion of `detect_machine.sh` to handle compute nodes.

### Acceptance Criteria

- [ ] All scripts with machine-dependent code use `${MACHINE_ID}` to determine which code to run
- [x] `detect_machine.sh` functions on both login and compute nodes of all supported machines
- [ ] Results unchanged

**Comment by HenryRWinterbottom** [comment]
@WalterKolczynski-NOAA So, can this be closed also?

**Comment by aerorahul** [comment]
@HenryWinterbottom-NOAA What needs to be done further on this issue?

**Comment by HenryRWinterbottom** [comment]
I thought this was done.
