### ISSUE TITLE
Add secondary products to at least one CI test case

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#2132]
### What new functionality do you need?

There are a number of secondary products that are off by default with their own jobs that should be tested by the CI in at least one CI test.

### What are the requirements for the new functionality?

Products for the following should be turned on for at least one CI test:
- bufr
- gempak
- awips
- goes

AWIPS will need to wait until those scripts function without failure. With the addition of the missing gempak jobs, that may also need to wait until the new jobs are corrected.

### Acceptance Criteria

- [ ] At least one CI test runs postbufr
- [ ] At least one CI test runs gempak jobs (can be the same test)
- [ ] At least one CI test runs awips jobs (can be the same test)
- [ ] At least one CI test creates GOES post files (can be the same test)

### Suggest a solution (optional)

The associated `DO_*` settings in config.base will need to be updated to use the @ templates with the associated defaults added to `workflow/hosts/*`.

**Comment by GwenChen-NOAA** [comment]
The npoess products should be included in this function as well with `DO_NPOESS` is turned on.
