### ISSUE TITLE
Newly added downstream jobs do not run

### ISSUE THREAD

**Issue by GwenChen-NOAA** [NOAA-EMC/global-workflow#2151]
### What is wrong?

The newly added downstream jobs:

gfsgempakmeta
gfsgempakncdcupapgif
gfsgempakpgrb2spec
gfsawips_g2_f*
gfsfbwinds

do not run and generate downstream products.

### What should have happened?

They should run successfully and generate downstream products.

### What machines are impacted?

WCOSS2

### Steps to reproduce

 Run the following experiment on WCOSS2:

./setup_expt.py gfs forecast-only --app ATM --resdet 384 --start cold --comrot $COMROT --expdir $EXPDIR --idate 2016070100 --edate 2016070100 --pslot test

with DO_GOES, DO_NPOESS, DO_GEMPAK and DO_AWIPS set to "YES" in config.base

### Additional information

       CYCLE                    TASK                       JOBID               STATE         EXIT STATUS     TRIES      DURATION
================================================================================================================================
201607010000             gfsstage_ic                   120693163           SUCCEEDED                   0         1          38.0
201607010000                 gfsfcst                   120693756                DEAD                   1         2          38.0
201607010000    gfsatmprod_f000-f012                   120693164           SUCCEEDED                   0         1         204.0
201607010000    gfsatmprod_f018-f030                   120696620           SUCCEEDED                   0         1         222.0
201607010000    gfsatmprod_f036-f048                   120696621           SUCCEEDED                   0         1         222.0
201607010000    gfsatmprod_f054-f066                   120696622           SUCCEEDED                   0         1         216.0
201607010000    gfsatmprod_f072-f084                   120696623           SUCCEEDED                   0         1         216.0
201607010000    gfsatmprod_f090-f102                   120696624           SUCCEEDED                   0         1         217.0
201607010000    gfsatmprod_f108-f120                   120696625           SUCCEEDED                   0         1         218.0
201607010000               gfsgempak                   120696792           SUCCEEDED                   0         1         236.0
201607010000           gfsgempakmeta                   120697216                DEAD                   1         2          14.0
201607010000    gfsgempakncdcupapgif                   120697217                DEAD                   1         2          17.0
201607010000      gfsgempakpgrb2spec                   120693442                DEAD                   1         2          16.0
201607010000    gfsawips_20km_1p0deg_f000-f000                   120696794           SUCCEEDED                   0         1          94.0
201607010000    gfsawips_20km_1p0deg_f006-f006                   120696796           SUCCEEDED                   0         1         100.0
201607010000    gfsawips_20km_1p0deg_f012-f012                   120696799           SUCCEEDED                   0         1         101.0
201607010000    gfsawips_20km_1p0deg_f018-f018                   120696800           SUCCEEDED                   0         1         102.0
201607010000    gfsawips_20km_1p0deg_f024-f024                   120696801           SUCCEEDED                   0         1         105.0
201607010000    gfsawips_20km_1p0deg_f030-f030                   120696802           SUCCEEDED                   0         1         103.0
201607010000    gfsawips_20km_1p0deg_f036-f036                   120696803           SUCCEEDED                   0         1         102.0
201607010000    gfsawips_20km_1p0deg_f042-f042                   120696804           SUCCEEDED                   0         1         102.0
201607010000    gfsawips_20km_1p0deg_f048-f048                   120696805           SUCCEEDED                   0         1         103.0
201607010000    gfsawips_20km_1p0deg_f054-f054                   120696806           SUCCEEDED                   0         1         105.0
201607010000    gfsawips_20km_1p0deg_f060-f060                   120696807           SUCCEEDED                   0         1         102.0
201607010000    gfsawips_20km_1p0deg_f066-f066                   120696808           SUCCEEDED                   0         1         102.0
201607010000    gfsawips_20km_1p0deg_f072-f072                   120696809           SUCCEEDED                   0         1         102.0
201607010000    gfsawips_20km_1p0deg_f078-f078                   120696810           SUCCEEDED                   0         1         103.0
201607010000    gfsawips_20km_1p0deg_f084-f084                   120696811           SUCCEEDED                   0         1         103.0
201607010000    gfsawips_20km_1p0deg_f090-f090                   120696812           SUCCEEDED                   0         1         102.0
201607010000    gfsawips_20km_1p0deg_f096-f096                   120696813           SUCCEEDED                   0         1         103.0
201607010000    gfsawips_20km_1p0deg_f102-f102                   120696814           SUCCEEDED                   0         1         102.0
201607010000    gfsawips_20km_1p0deg_f108-f108                   120696815           SUCCEEDED                   0         1         103.0
201607010000    gfsawips_20km_1p0deg_f114-f114                   120696816           SUCCEEDED                   0         1         102.0
201607010000    gfsawips_20km_1p0deg_f120-f120                   120696817           SUCCEEDED                   0         1         102.0
201607010000    gfsawips_g2_f000-f000                   120697218                DEAD                   1         2          17.0
201607010000    gfsawips_g2_f006-f006                   120697476                DEAD                   1         2          17.0
201607010000    gfsawips_g2_f012-f012                   120697477                DEAD                   1         2          18.0
201607010000    gfsawips_g2_f018-f018                   120697478                DEAD                   1         2          18.0
201607010000    gfsawips_g2_f024-f024                   120697479                DEAD                   1         2          18.0
201607010000    gfsawips_g2_f030-f030                   120697480                DEAD                   1         2          17.0
201607010000    gfsawips_g2_f036-f036                   120697481                DEAD                   1         2          17.0
201607010000    gfsawips_g2_f042-f042                   120697482                DEAD                   1         2          17.0
201607010000    gfsawips_g2_f048-f048                   120697483                DEAD                   1         2          16.0
201607010000    gfsawips_g2_f054-f054                   120697484                DEAD                   1         2          16.0
201607010000    gfsawips_g2_f060-f060                   120697485                DEAD                   1         2          17.0
201607010000    gfsawips_g2_f066-f066                   120697486                DEAD                   1         2          18.0
201607010000    gfsawips_g2_f072-f072                   120697487                DEAD                   1         2          18.0
201607010000    gfsawips_g2_f078-f078                   120697488                DEAD                   1         2          18.0
201607010000    gfsawips_g2_f084-f084                   120697489                DEAD                   1         2          18.0
201607010000    gfsawips_g2_f090-f090                   120697490                DEAD                   1         2          18.0
201607010000    gfsawips_g2_f096-f096                   120697491                DEAD                   1         2          18.0
201607010000    gfsawips_g2_f102-f102                   120697492                DEAD                   1         2          16.0
201607010000    gfsawips_g2_f108-f108                   120697493                DEAD                   1         2          17.0
201607010000    gfsawips_g2_f114-f114                   120697494                DEAD                   1         2          17.0
201607010000    gfsawips_g2_f120-f120                   120697495                DEAD                   1         2          16.0
201607010000              gfsfbwinds                   120697725                DEAD                 127         2          15.0
201607010000                 gfsarch                   120697250           SUCCEEDED                   0         1         114.0
201607010000              gfscleanup                   120697497           SUCCEEDED                   0         1          15.0

**Comment by HenryRWinterbottom** [comment]
@GwenChen-NOAA Can you please also run these jobs on RDHPCS Hera as well?

**Comment by GwenChen-NOAA** [comment]
Will do.

**Comment by WalterKolczynski-NOAA** [comment]
@GwenChen-NOAA if you look at the changes I made to the awips/gempak scripts that _were_ in #1421, that should give you a good idea of what needs to be done for each of these to get started.

**Comment by GwenChen-NOAA** [comment]
@HenryWinterbottom-NOAA, I test ran the downstream jobs on Hera. Same errors and same results, except that the gfsfcst task ran successfully on Hera.

**Comment by HenryRWinterbottom** [comment]
@GwenChen-NOAA @aerorahul Added a hot fix yesterday, 14 December 2023. 

Can you do a fresh checkout of the `develop` branch and please try again on RDHPCS Hera? I am hoping that it gets a bit further. This might wind up being an iterative process.

**Comment by GwenChen-NOAA** [comment]
I cloned the repo this morning using:

> git clone --recursive https://github.com/NOAA-EMC/global-workflow

It should include Rahul's hot fix yesterday.

**Comment by HenryRWinterbottom** [comment]
@GwenChen-NOAA OK, can you point me to your logs/run directory on RDHPCS Hera?

**Comment by GwenChen-NOAA** [comment]
@HenryWinterbottom-NOAA, it's /scratch2/NCEPDEV/ovp/Lichuan.Chen/gwDev/COMROT/test.

**Comment by HenryRWinterbottom** [comment]
@GwenChen-NOAA Myself, @WalterKolczynski-NOAA, and @aerorahul will work on this. Please stay tuned.
