### ISSUE TITLE
Newly added gfsgempakmeta job fails to run

### ISSUE THREAD

**Issue by GwenChen-NOAA** [NOAA-EMC/global-workflow#2152]
### What is wrong?

Newly added gfsgempakmeta job fails to run and generate gempak meta files.

### What should have happened?

gfsgempakmeta job should run successfully and generate gempak meta files.

### What machines are impacted?

WCOSS2

### Steps to reproduce

Run the following experiment on WCOSS2:

./setup_expt.py gfs forecast-only --app ATM --resdet 384 --start cold --comrot $COMROT --expdir $EXPDIR --idate 2016070100 --edate 2016070100 --pslot test

with DO_GEMPAK set to "YES" in config.base

### Additional information

Per Rahul's request, this issue is opened for each of the jobs in Issue #2151 with relevant details.

Error messages in the log file indicate that config files are not sourced properly:

++ jjob_header.sh[97]: for config in "${configs[@]:-''}"
++ jjob_header.sh[98]: source '/lfs/h2/emc/vpppg/noscrub/Lichuan.Chen/gwDev/EXPDIR/test/config.'\'''\'''
/lfs/h2/emc/vpppg/noscrub/Lichuan.Chen/gwDev/global-workflow/ush/jjob_header.sh: line 98: /lfs/h2/emc/vpppg/noscrub/Lichuan.Chen/gwDev/EXPDIR/test/config.'': No such file or directory+++ jjob_header.sh[1]: postamble JGFS_ATMOS_GEMPAK_META 1702070116 1
+++ preamble.sh[68]: set +xEnd JGFS_ATMOS_GEMPAK_META at 21:15:16 with error code 1 (time elapsed: 00:00:00)

[gfsgempakmeta.log](https://github.com/NOAA-EMC/global-workflow/files/13675651/gfsgempakmeta.log)

**Comment by HenryRWinterbottom** [comment]
@GwenChen-NOAA Can you please run this job on RDHPCS Hera? I don't have WCOSS access at the moment and Hera would allow me to debug further.

**Comment by GwenChen-NOAA** [comment]
Ok, I will try it.
