### ISSUE TITLE
Newly added gfsgempakncdcupapgif job fails to run

### ISSUE THREAD

**Issue by GwenChen-NOAA** [NOAA-EMC/global-workflow#2157]
### What is wrong?

Newly added gfsgempakncdcupapgif job fails to run and generate gempak *.gif files and skew_t files.

### What should have happened?

gfsgempakncdcupapgif job should run successfully and generate gempak *.gif files and skew_t files.

### What machines are impacted?

WCOSS2

### Steps to reproduce

Run the following experiment on WCOSS2:

./setup_expt.py gfs forecast-only --app ATM --resdet 384 --start cold --comrot $COMROT --expdir $EXPDIR --idate 2016070100 --edate 2016070100 --pslot test

with DO_GEMPAK set to "YES" in config.base

### Additional information

Per Rahul's request, this issue is opened for each of the jobs in Issue #2151 with relevant details.

Error messages in the log file indicate that directory paths are not set up correctly:

+ JGFS_ATMOS_GEMPAK_NCDC_UPAPGIF[62]: mkdir -m 775 -p /lfs/h1/ops/prod/com/gfs/v16.3/gfs.20160701/00/atmos /lfs/h1/ops/prod/com/gfs/v16.3/gfs.20160701/00/atmos/wmo
mkdir: cannot create directory â/lfs/h1/ops/prod/com/gfs/v16.3/gfs.20160701â: Permission denied
mkdir: cannot create directory â/lfs/h1/ops/prod/com/gfs/v16.3/gfs.20160701â: Permission denied
+ JGFS_ATMOS_GEMPAK_NCDC_UPAPGIF[1]: postamble JGFS_ATMOS_GEMPAK_NCDC_UPAPGIF 1702070116 1
+ preamble.sh[68]: set +x
End JGFS_ATMOS_GEMPAK_NCDC_UPAPGIF at 21:15:19 with error code 1 (time elapsed: 00:00:03)

[gfsgempakncdcupapgif.log](https://github.com/NOAA-EMC/global-workflow/files/13677112/gfsgempakncdcupapgif.log)

**Comment by aerorahul** [comment]
@GwenChen-NOAA 
looks to me that there are operational paths in the jobs and scripts.  This is probably the reason why they were not included in the development suite as these jobs have not been built for development use by the authors.

**Comment by GwenChen-NOAA** [comment]
> @GwenChen-NOAA looks to me that there are operational paths in the jobs and scripts. This is probably the reason why they were not included in the development suite as these jobs have not been built for development use by the authors.

@aerorahul, these lines of code in JGFS_ATMOS_GEMPAK_NCDC_UPAPGIF is to create output directories:

export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${gfs_ver}/${RUN}.${PDY})/${cyc}/${COMPONENT}}
export COMOUTwmo=${COMOUTwmo:-${COMOUT}/wmo}
...
mkdir -m 775 -p ${COMOUT} ${COMOUTwmo}

It should be redirected to $COMROT.

**Comment by WalterKolczynski-NOAA** [comment]
We knew all these jobs wouldn't work when we added them. They've never been in development before and most of them have not been updated for the COM refactor. Getting them in the rocoto mesh was only the first step.

**Comment by GwenChen-NOAA** [comment]
This issue can be closed with PR #2374 merged.
