### ISSUE TITLE
Newly added gfsfbwinds job fails to run

### ISSUE THREAD

**Issue by GwenChen-NOAA** [NOAA-EMC/global-workflow#2160]
### What is wrong?

Newly added gfsfbwinds job fails to run and create a bulletin for Pacific region.

### What should have happened?

gfsfbwinds job should run successfully and create a bulletin for Pacific region.

### What machines are impacted?

WCOSS2

### Steps to reproduce

Run the following experiment on WCOSS2:

./setup_expt.py gfs forecast-only --app ATM --resdet 384 --start cold --comrot $COMROT --expdir $EXPDIR --idate 2016070100 --edate 2016070100 --pslot test

with DO_AWIPS set to "YES" in config.base

### Additional information

Per Rahul's request, this issue is opened for each of the jobs in Issue #2151 with relevant details.

Error messages in the log file indicate that output directory paths are not set up correctly:

+ JGFS_ATMOS_FBWIND[38]: mkdir -m 775 -p /lfs/h1/ops/prod/com/gfs/v16.3/gfs.20160701/00/atmos /lfs/h1/ops/prod/com/gfs/v16.3/gfs.20160701/00/atmos/wmo
mkdir: cannot create directory â /lfs/h1/ops/prod/com/gfs/v16.3/gfs.20160701â : Permission denied
mkdir: cannot create directory â /lfs/h1/ops/prod/com/gfs/v16.3/gfs.20160701â : Permission denied
+ JGFS_ATMOS_FBWIND[1]: postamble JGFS_ATMOS_FBWIND 1702585814 1
+ preamble.sh[68]: set +x
End JGFS_ATMOS_FBWIND at 20:30:16 with error code 1 (time elapsed: 00:00:02)

[gfsfbwinds.log](https://github.com/NOAA-EMC/global-workflow/files/13687657/gfsfbwinds.log)

**Comment by JessicaMeixner-NOAA** [comment]
@GwenChen-NOAA this seems like a simple typo that https://github.com/NOAA-EMC/global-workflow/blob/develop/jobs/rocoto/fbwinds.sh#L14 should change from: 
"${HOMEgfs}/jobs/JGFS_ATMOS_FBWINDS"
 to 
"${HOMEgfs}/jobs/JGFS_ATMOS_FBWIND"

Or https://github.com/NOAA-EMC/global-workflow/blob/develop/jobs/JGFS_ATMOS_FBWIND should be renamed to JGFS_ATMOS_FBWINDS

**Comment by GwenChen-NOAA** [comment]
Good catch, @JessicaMeixner-NOAA! I changed "${HOMEgfs}/jobs/JGFS_ATMOS_FBWINDS" to "${HOMEgfs}/jobs/JGFS_ATMOS_FBWIND" in fbwinds.sh, and rerun the task. It runs but not successful with the error messages below:

+ JGFS_ATMOS_FBWIND[38]: mkdir -m 775 -p /lfs/h1/ops/prod/com/gfs/v16.3/gfs.20160701/00/atmos /lfs/h1/ops/prod/com/gfs/v16.3/gfs.20160701/00/atmos/wmomkdir: cannot create directory â/lfs/h1/ops/prod/com/gfs/v16.3/gfs.20160701â: Permission deniedmkdir: cannot create directory â/lfs/h1/ops/prod/com/gfs/v16.3/gfs.20160701â: Permission denied+ JGFS_ATMOS_FBWIND[1]: postamble JGFS_ATMOS_FBWIND 1702585814 1
+ preamble.sh[68]: set +xEnd JGFS_ATMOS_FBWIND at 20:30:16 with error code 1 (time elapsed: 00:00:02)

Same error as the gfsgempakncdcupapgif job (https://github.com/NOAA-EMC/global-workflow/issues/2157#issuecomment-1856565764). The output directory should be redirected to $COMROT.

**Comment by aerorahul** [comment]
@GwenChen-NOAA 
Again, it is not surprising that the job is trying to create and write to operational space.  This job and its scripts (like the others) need to be examined, and updated to be able to be run in development mode.

**Comment by GwenChen-NOAA** [comment]
@aerorahul, do you want to reopen this issue since the job still not running?  Or should I open a new issue for it?

**Comment by aerorahul** [comment]
I can reopen, but please update the issue to bring to the front the problem.
