### ISSUE TITLE
Standardize fix directory variables

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#2175]
### What new functionality do you need?

Consistency and correctness with the various variables that define fix file subdirectories.

Example problems: `OROFIX` should be `FIX_orog` and `FIXgsm` should be `FIXam`

### What are the requirements for the new functionality?

Standard naming convention for fix directory variables.

### Acceptance Criteria

Fix directory variables are updated, standardized and tests work with updates.

**Comment by KateFriedman-NOAA** [comment]
@CoryMartin-NOAA @RussTreadon-NOAA I'd like to change `FV3JEDI_FIX` to `FIXgdas` to match the other fix file directory variable names I am consolidating around in this issue. Any objections?

The following shows where `FV3JEDI_FIX` appears when I search for it. The last two lines show instances within the GDASApp repo and which would also need to be updated:
```
parm/config/gfs/config.aeroanl:export FV3JEDI_FIX=${HOMEgfs}/fix/gdas
parm/config/gfs/config.aeroanl:export BERROR_DATA_DIR=${FV3JEDI_FIX}/bump/aero/${CASE_ANL}/
parm/gdas/aero_jedi_fix.yaml:- - !ENV ${FV3JEDI_FIX}/fv3jedi/fv3files/akbk$(npz).nc4
parm/gdas/aero_jedi_fix.yaml:- - !ENV ${FV3JEDI_FIX}/fv3jedi/fv3files/fmsmpp.nml
parm/gdas/aero_jedi_fix.yaml:- - !ENV ${FV3JEDI_FIX}/fv3jedi/fv3files/field_table_gfdl
sorc/gdas.cd/test/aero/global-workflow/config.aeroanl:export FV3JEDI_FIX=${HOMEgfs}/fix/gdas
sorc/gdas.cd/test/aero/global-workflow/config.aeroanl:export BERROR_DATA_DIR=${FV3JEDI_FIX}/bump/aero/${CASE_ANL}/
```

**Comment by CoryMartin-NOAA** [comment]
No objection from me, and those last 2 lines are just from a slightly modified version of the file that the first 2 lines are from, so we can easily update that in parallel.

**Comment by KateFriedman-NOAA** [comment]
Great! I'll proceed with changing `FV3JEDI_FIX` to `FIXgdas` in my branch. Thanks @CoryMartin-NOAA !
