### ISSUE TITLE
Aerosol cycling in forecast-only mode broken 

### ISSUE THREAD

**Issue by bbakernoaa** [NOAA-EMC/global-workflow#2176]
### What is wrong?

Right now cycling without DA in `forecast-only` mode the aerosol model is broken.  This is because the data structure under COMROT has changed.  Specifically the `scripts/exgfs_aero_init_aerosol.py` wasn't updated to account for this.  You can see the changes necessary to be made [here](https://github.com/bbakernoaa/global-workflow/commit/9e6d3dc00b01fc216bb2a42f06c270ef045be687).  

However, even after correcting these directory paths in this file there is another error as the ak values do not appear to be the same between the restart and the gfs_ctrl file for the next cycle.  This occurs during the execution of `ufs/merge_fv3_aerosol_tile.py`.  You can find the log file here: 

`/scratch1/NCEPDEV/stmp2/Barry.Baker/testing/COMROOT/testing/logs/2020051600/gfsaerosol_init.log`

I have an example test setup on hera here: `/scratch1/NCEPDEV/stmp2/Barry.Baker/testing/EXPDIR/testing`

### What should have happened?

cycling use to work in the forecast-only mode.  Now it seems that this is broken for aerosols. 

### What machines are impacted?

All or N/A

### Steps to reproduce

Setup forecast-only experiment for ATMA 

This was my configuration that I used to set it up.

```APP=ATMA
PSLOT=testing
BASEDIR=/scratch2/NCEPDEV/naqfc/Barry.Baker/workfow/global/gwdev
CDUMP=gfs #gfs or gefs
CONFIGDIR=$BASEDIR/parm/config/${CDUMP}
IDATE=2020051500
EDATE=2020051600
#IDATE=2021032312
#EDATE=2021032312
RES=96
GFS_CYC=1
STMP=/scratch1/NCEPDEV/stmp2/Barry.Baker #/work/noaa/stmp/${USER}
COMROT=${STMP}/$PSLOT/COMROOT
EXPDIR=${STMP}/$PSLOT/EXPDIR
RUNTYPE='forecast-only'

echo "source module setup:"
echo "source gw_setup.sh"

echo " "
echo "Set up script"
echo "./setup_expt.py ${CDUMP} ${RUNTYPE} --app $APP --pslot $PSLOT --configdir $CONFIGDIR --idate $IDATE --edate $EDATE --resdet $RES --gfs_cyc $GFS_CYC --comrot $COMROT --expdir $EXPDIR"

echo " "
echo "setup workflow after any changes:"
echo "./setup_xml.py $EXPDIR/$PSLOT"

echo " "
echo "cat $EXPDIR/$PSLOT/$PSLOT.crontab"

```

### Additional information

Error output from log file listed above 

```Merging tracers
        Merging tracers from /scratch1/NCEPDEV/stmp2/Barry.Baker/testing/COMROOT/testing/gfs.20200515/00/model_data/atmos/restart/fv_tracer.res.tile1.nc into /scratch1/NCE\
PDEV/stmp2/Barry.Baker/testing/COMROOT/testing/gfs.20200516/00/model_data/atmos/input/gfs_data.tile1.nc
WARNING: Specified out file /scratch1/NCEPDEV/stmp2/Barry.Baker/testing/COMROOT/testing/gfs.20200516/00/model_data/atmos/input/gfs_data.tile1.nc.tmp exists and will be ove\
rwritten
FATAL ERROR: A(k) coefficients must be identical
Traceback (most recent call last):
  File "/scratch2/NCEPDEV/naqfc/Barry.Baker/workfow/global/gwdev/scripts/exgfs_aero_init_aerosol.py", line 291, in <module>
    main()
  File "/scratch2/NCEPDEV/naqfc/Barry.Baker/workfow/global/gwdev/scripts/exgfs_aero_init_aerosol.py", line 92, in main
    merge_tracers(merge_script, atm_files, tracer_files, rest_files, core_files[0], ctrl_files[0], tracer_list_file)
  File "/scratch2/NCEPDEV/naqfc/Barry.Baker/workfow/global/gwdev/scripts/exgfs_aero_init_aerosol.py", line 286, in merge_tracers
    subprocess.run([merge_script, atm_file, tracer_file, core_file, ctrl_file, rest_file, tracer_list_file, temp_file], check=True)
  File "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.5.1/envs/unified-env/install/intel/2021.5.0/python-3.10.8-oqvn6sa/lib/python3.10/subprocess.py", line 52\
6, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/scratch2/NCEPDEV/naqfc/Barry.Baker/workfow/global/gwdev/ush/merge_fv3_aerosol_tile.py', '/scratch1/NCEPDEV/stmp2/Barry.Baker/tes\
ting/COMROOT/testing/gfs.20200516/00/model_data/atmos/input/gfs_data.tile1.nc', '/scratch1/NCEPDEV/stmp2/Barry.Baker/testing/COMROOT/testing/gfs.20200515/00/model_data/atm\
os/restart/fv_tracer.res.tile1.nc', '/scratch1/NCEPDEV/stmp2/Barry.Baker/testing/COMROOT/testing/gfs.20200515/00/model_data/atmos/restart/fv_core.res.nc', '/scratch1/NCEPD\
EV/stmp2/Barry.Baker/testing/COMROOT/testing/gfs.20200516/00/model_data/atmos/input/gfs_ctrl.nc', '/scratch1/NCEPDEV/stmp2/Barry.Baker/testing/COMROOT/testing/gfs.20200515\
/00/model_data/atmos/restart/fv_core.res.tile1.nc', '/scratch2/NCEPDEV/naqfc/Barry.Baker/workfow/global/gwdev/parm/ufs/gocart/gocart_tracer.list', '/scratch1/NCEPDEV/stmp2\
/Barry.Baker/testing/COMROOT/testing/gfs.20200516/00/model_data/atmos/input/gfs_data.tile1.nc.tmp']' returned non-zero exit status 109.
+ aerosol_init.sh[1]: postamble aerosol_init.sh 1703098378 1
+ preamble.sh[68]: set +x
End aerosol_init.sh at 18:53:08 with error code 1 (time elapsed: 00:00:10)
_______________________________________________________________
Start Epilog on node h9c45 for job 53159862 :: Wed Dec 20 18:53:09 UTC 2023
Job 53159862 finished for user Barry.Baker in partition hera with exit code 1:0
_______________________________________________________________
End Epilogue Wed Dec 20 18:53:09 UTC 2023```

### Do you have a proposed solution?

began working on this in my fork of the [global-workflow](https://github.com/bbakernoaa/global-workflow/tree/feature/gocart_fixes)

**Comment by aerorahul** [comment]
@bbakernoaa 
looking at the files; 3rd and 4th argument to the script `merge_fv3_aerosol_tile.py`
```
/scratch1/NCEPDEV/stmp2/Barry.Baker/testing/COMROOT/testing/gfs.20200515/00/model_data/atmos/restart/fv_core.res.nc
/scratch1/NCEPDEV/stmp2/Barry.Baker/testing/COMROOT/testing/gfs.20200516/00/model_data/atmos/input/gfs_ctrl.nc
```
I note the following.

By doing a `ncdump` on these files, the variables `ak` and `vcoord`, I notice one is a `float` and the other is a `double`.
Is it appropriate to compare these two variables of different data type and expect them to be equal?  
Is this particular check necessary?

`fv_core.res.nc` comes from the model. 
I assume `gfs_ctrl.nc` is generated from some version of `chgres_cube`.  

When was this feature last exercised and found to be functioning as expected?  Was it before or after the migration to compiling the model with mixed-mode FMS? 
I am speculating that when the model is compiled and run in 64-bit precision, the restarts are also 64-bit and hence the `double ak, bk` in `fv_core.res.nc`.  I may be wrong to assume that.

Either way, I would recommend eliminating the section of code between lines 91-97 of `merge_fv3_aerosol_tile.py` and try again.

**Comment by bbakernoaa** [comment]
@aerorahul I'm not sure I didn't originally create this bit.  I had printed out the values and they are very very close so maybe this is just splitting hairs. 

Yes I had generated the `gfs_ctrl.nc` by using `chgres_cube`.  

We had used this all for the the development of the aerosol component. The last I remember it working was perhaps late summer.  I have been a little negligent in exercising research runs in preparation for GEFSv13 and the EP4+ experiments. 

I'll give it a shot and let you know.

**Comment by bbakernoaa** [comment]
@aerorahul I was able to get it to go through with commenting out https://github.com/bbakernoaa/global-workflow/blob/feature/gocart_fixes/ush/merge_fv3_aerosol_tile.py#L91-L97

However, I had to manually boot the job after I did a `rocotorewind`.  Seems something is broken in the logic for the gfsaerosol_init task within the xml.  The datadep is never satisfied for the restart files even though I can confirm the conditions as far as I can tell is met.  I'm still looking into it but maybe you have a better idea.

**Comment by bbakernoaa** [comment]
@aerorahul helped me out. In the xml generation there is a missing / at the end of the end of the restart path.  

example after generation
### before:

<pre>
                       <datadep><cyclestr>&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/input/gfs_ctrl.nc</cyclestr></datadep>
                        <datadep><cyclestr>&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/input/gfs_data.tile1.nc</cyclestr></datadep>
                        <datadep><cyclestr>&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/input/gfs_data.tile2.nc</cyclestr></datadep>
			<datadep><cyclestr>&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/input/gfs_data.tile3.nc</cyclestr></datadep>
                        <datadep><cyclestr>&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/input/gfs_data.tile4.nc</cyclestr></datadep>
			<datadep><cyclestr>&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/input/gfs_data.tile5.nc</cyclestr></datadep>
                        <datadep><cyclestr>&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/input/gfs_data.tile6.nc</cyclestr></datadep>
			<datadep><cyclestr offset="-24:00:00">&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/restart</cyclestr><cyclestr>@Y@m@d.@H0000.fv_core.res.nc</cyclestr></datadep>
                        <datadep><cyclestr offset="-24:00:00">&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/restart</cyclestr><cyclestr>@Y@m@d.@H0000.fv_core.res.tile1.nc</cyclestr></datadep>
                        <datadep><cyclestr offset="-24:00:00">&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/restart</cyclestr><cyclestr>@Y@m@d.@H0000.fv_core.res.tile2.nc</cyclestr></datadep>
                        <datadep><cyclestr offset="-24:00:00">&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/restart</cyclestr><cyclestr>@Y@m@d.@H0000.fv_core.res.tile3.nc</cyclestr></datadep>
			<datadep><cyclestr offset="-24:00:00">&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/restart</cyclestr><cyclestr>@Y@m@d.@H0000.fv_core.res.tile4.nc</cyclestr></datadep>
                        <datadep><cyclestr offset="-24:00:00">&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/restart</cyclestr><cyclestr>@Y@m@d.@H0000.fv_core.res.tile5.nc</cyclestr></datadep>
			<datadep><cyclestr offset="-24:00:00">&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/restart</cyclestr><cyclestr>@Y@m@d.@H0000.fv_core.res.tile6.nc</cyclestr></datadep>
                        <datadep><cyclestr offset="-24:00:00">&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/restart</cyclestr><cyclestr>@Y@m@d.@H0000.fv_tracer.res.tile1.nc</cyclestr></datadep>
			<datadep><cyclestr offset="-24:00:00">&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/restart</cyclestr><cyclestr>@Y@m@d.@H0000.fv_tracer.res.tile2.nc</cyclestr></datadep>
                        <datadep><cyclestr offset="-24:00:00">&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/restart</cyclestr><cyclestr>@Y@m@d.@H0000.fv_tracer.res.tile3.nc</cyclestr></datadep>
                        <datadep><cyclestr offset="-24:00:00">&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/restart</cyclestr><cyclestr>@Y@m@d.@H0000.fv_tracer.res.tile4.nc</cyclestr></datadep>
                        <datadep><cyclestr offset="-24:00:00">&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/restart</cyclestr><cyclestr>@Y@m@d.@H0000.fv_tracer.res.tile5.nc</cyclestr></datadep>
                        <datadep><cyclestr offset="-24:00:00">&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/restart</cyclestr><cyclestr>@Y@m@d.@H0000.fv_tracer.res.tile6.nc</cyclestr></datadep>
</pre>

### fixed
<pre>
                        <datadep><cyclestr>&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/input/gfs_ctrl.nc</cyclestr></datadep>
                        <datadep><cyclestr>&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/input/gfs_data.tile1.nc</cyclestr></datadep>
                        <datadep><cyclestr>&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/input/gfs_data.tile2.nc</cyclestr></datadep>
			<datadep><cyclestr>&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/input/gfs_data.tile3.nc</cyclestr></datadep>
                        <datadep><cyclestr>&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/input/gfs_data.tile4.nc</cyclestr></datadep>
			<datadep><cyclestr>&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/input/gfs_data.tile5.nc</cyclestr></datadep>
                        <datadep><cyclestr>&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/input/gfs_data.tile6.nc</cyclestr></datadep>
			<datadep><cyclestr offset="-24:00:00">&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/restart/</cyclestr><cyclestr>@Y@m@d.@H0000.fv_core.res.nc</cyclestr></datadep>
                        <datadep><cyclestr offset="-24:00:00">&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/restart/</cyclestr><cyclestr>@Y@m@d.@H0000.fv_core.res.tile1.nc</cyclestr></datadep>
                        <datadep><cyclestr offset="-24:00:00">&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/restart/</cyclestr><cyclestr>@Y@m@d.@H0000.fv_core.res.tile2.nc</cyclestr></datadep>
                        <datadep><cyclestr offset="-24:00:00">&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/restart/</cyclestr><cyclestr>@Y@m@d.@H0000.fv_core.res.tile3.nc</cyclestr></datadep>
			<datadep><cyclestr offset="-24:00:00">&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/restart/</cyclestr><cyclestr>@Y@m@d.@H0000.fv_core.res.tile4.nc</cyclestr></datadep>
                        <datadep><cyclestr offset="-24:00:00">&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/restart/</cyclestr><cyclestr>@Y@m@d.@H0000.fv_core.res.tile5.nc</cyclestr></datadep>
			<datadep><cyclestr offset="-24:00:00">&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/restart/</cyclestr><cyclestr>@Y@m@d.@H0000.fv_core.res.tile6.nc</cyclestr></datadep>
                        <datadep><cyclestr offset="-24:00:00">&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/restart/</cyclestr><cyclestr>@Y@m@d.@H0000.fv_tracer.res.tile1.nc</cyclestr></datadep>
			<datadep><cyclestr offset="-24:00:00">&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/restart/</cyclestr><cyclestr>@Y@m@d.@H0000.fv_tracer.res.tile2.nc</cyclestr></datadep>
                        <datadep><cyclestr offset="-24:00:00">&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/restart/</cyclestr><cyclestr>@Y@m@d.@H0000.fv_tracer.res.tile3.nc</cyclestr></datadep>
                        <datadep><cyclestr offset="-24:00:00">&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/restart/</cyclestr><cyclestr>@Y@m@d.@H0000.fv_tracer.res.tile4.nc</cyclestr></datadep>
                        <datadep><cyclestr offset="-24:00:00">&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/restart/</cyclestr><cyclestr>@Y@m@d.@H0000.fv_tracer.res.tile5.nc</cyclestr></datadep>
                        <datadep><cyclestr offset="-24:00:00">&ROTDIR;/gfs.@Y@m@d/@H//model_data/atmos/restart/</cyclestr><cyclestr>@Y@m@d.@H0000.fv_tracer.res.tile6.nc</cyclestr></datadep>```
