### ISSUE TITLE
The marine DA jobs are running out of memory ... again

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/global-workflow#2178]
### What is wrong?

We're having issues properly setting the number of nodes, which is linked to the cpu counts and the number of threads. 
For example, in the c384 case, we need 40 nodes on hera but only want to run on 480 cores and 1 thread per core. Before this PR:
https://github.com/NOAA-EMC/global-workflow/pull/2077/files we would set the number of thread to 2 and get the proper number of nodes, while not using the 2 threads per core. That does not work anymore.

We need to be able to control the number of nodes without going through that clunky calculation.

### What should have happened?

... 

### What machines are impacted?

All or N/A

### Steps to reproduce

...

### Additional information

...

**Comment by CoryMartin-NOAA** [comment]
Please note this blurb from the Hera docs: https://rdhpcs-common-docs.rdhpcs.noaa.gov/wiki/index.php?title=Running_and_Monitoring_Jobs#Hera_Partitions




Please keep in mind that when you specify "--cpus-per-task" option on sbatch, each job-step only gets its proportional share of memory! If you leave that option out, or if you specify "--mem=0" then each of the job-steps will be able to use all the available memory.

So please do not specify this option unless it is needed. More specifically, if the job is going to share the nodes with other users, "--cpus-per-task" will have a default memory limit for each process (a proportional share of memory). The user can use "--mem" to request a big memory limit. If the job does not share nodes with other users, do not use "--cpus-per-task", and add "--exclusive" to your batch file. The "--exclusive" option means that the process memory limit can be up to the total available node memory. However, when "--cpus-per-task" is there, the "--exclusive" will not work.
