### ISSUE TITLE
Remove FIX* directory variables

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#2184]
### What new functionality do you need?

Replace the use of `FIX*` directory variables with the full path and `FIXgfs`. Example: `FIXam` -> `FIXgfs/am`

Variables to target include:

- `FIXam`
- `FIXaer`
- `FIXgdas`
- `FIXgempak`
- `FIXlut`
- `FIXorog`
- `FIXcpl`
- etc?

### What are the requirements for the new functionality?

Reduced variable settings and continued functionality of system.

- [ ] Updated UFS_UTILS hash with `FIX*` variables removed/updated - https://github.com/ufs-community/UFS_UTILS/pull/899
- [ ] Updated GDASAPP hash with `FIX*` variables removed/updated - https://github.com/NOAA-EMC/GDASApp/pull/932

### Acceptance Criteria

`FIX*` variables are removed and system still works.

**Comment by KateFriedman-NOAA** [comment]
@GeorgeGayno-NOAA There are some changes needed to UFS_UTILS scripts for this cleanup effort. Please see the git diff here on Hera for changes to please pull into UFS_UTILS: `/scratch1/NCEPDEV/global/Kate.Friedman/git/feature-remove_FIX_dir_vars/sorc/ufs_utils.fd`. Thanks!

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA There are some changes needed to UFS_UTILS scripts for this cleanup effort. Please see the git diff here on Hera for changes to please pull into UFS_UTILS: `/scratch1/NCEPDEV/global/Kate.Friedman/git/feature-remove_FIX_dir_vars/sorc/ufs_utils.fd`. Thanks!

Ok. I can open an issue and branch.

**Comment by KateFriedman-NOAA** [comment]
> Ok. I can open an issue and branch.

Thanks @GeorgeGayno-NOAA !

**Comment by KateFriedman-NOAA** [comment]
@CoryMartin-NOAA @aerorahul Need guidance on how best to replace the following `FIX*` variables with their respective `${FIXgfs}/type` versions in two python scripts.

1) `FIXam` in `calcanl_gfs.py`:
```
FixDir = os.getenv('FIXam', './')
```
https://github.com/NOAA-EMC/global-workflow/blob/develop/ush/calcanl_gfs.py#L349

Would this be appropriate to get `${FIXgfs}/am`:
```
FixDir = os.getenv('FIXgfs', './') + 'am'
```

2) `FIXgdas` in this list of `keys` in `land_analysis.py`:
```
keys = ['DATA', 'current_cycle', 'COM_OBS', 'COM_ATMOS_RESTART_PREV',
                'OPREFIX', 'CASE', 'OCNRES', 'ntiles', 'FIXgdas']
```
https://github.com/NOAA-EMC/global-workflow/blob/develop/ush/python/pygfs/task/land_analysis.py#L155:L156

Not sure how to best replace `FIXgdas` with `${FIXgfs}/gdas`.

**Comment by CoryMartin-NOAA** [comment]
For the first one, I think you want `FixDir = os.path.join(os.getenc('FIXgfs', './'), 'am')`

For the second, I think this means that we have to change all of our GDASApp templates that use FIXgdas to use FIXgfs/gdas. I'll need to double check this.

**Comment by KateFriedman-NOAA** [comment]
> For the first one, I think you want FixDir = os.path.join(os.getenc('FIXgfs', './'), 'am')

Gotcha. I'm assuming that's a typo and `getenc` should be `getenv` with a `v`? Please confirm, thanks!

> For the second, I think this means that we have to change all of our GDASApp templates that use FIXgdas to use FIXgfs/gdas. I'll need to double check this.

Yes please also update those `FIX*` variables in the GDASApp. Similar updates are also happening in the UFS_UTILS repo. Sorry, I should have checked the GDASApp as well.

**Comment by CoryMartin-NOAA** [comment]
Yes, getenv :-)

And ok, let me take a look later today and draft a PR.

**Comment by KateFriedman-NOAA** [comment]
Sounds great, thanks @CoryMartin-NOAA ! I'm happy to be a reviewer on that PR, just let me know.

**Comment by CoryMartin-NOAA** [comment]
@KateFriedman-NOAA GDASApp PR issued. For the workflow change, just replace `FIXgdas` with `FIXgfs` in that list you showed above, and that should do the trick!

**Comment by KateFriedman-NOAA** [comment]
> @KateFriedman-NOAA GDASApp PR issued.

PR reviewed! Thanks for the quick work!

> For the workflow change, just replace `FIXgdas` with `FIXgfs` in that list you showed above, and that should do the trick!

Will do, thanks!

**Comment by KateFriedman-NOAA** [comment]
Changeset as of now: https://github.com/NOAA-EMC/global-workflow/compare/develop...KateFriedman-NOAA:global-workflow:feature/remove_FIX_dir_vars

Awaiting updates to UFS_UTILS and GDASApp before initiating PR into `develop`. Will test again with new hashes when they are ready.

**Comment by KateFriedman-NOAA** [comment]
Testing updated hashes in fork branch on WCOSS2.
