### ISSUE TITLE
Analysis post products not generated properly

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/global-workflow#2185]
### What is wrong?

The gdasatmanlprod and gfsatmanlprod jobs are failing with the error messages
```
+ atmos_products.sh[16]: jobid=atmos_products.307715
basename: extra operand ‘products.sh’
Try 'basename --help' for more information.
+ [20]: IFS=_
basename: extra operand ‘products.sh’
Try 'basename --help' for more information.
+ [20]: read -ra fhrs
+ atmos_products.sh[24]: for fhr in "${fhrs[@]}"
<path/to/global-workflow>/jobs/rocoto/atmos_products.sh: line 25: 10#: invalid integer constant (error token is "10#")
+ atmos_products.sh[27]: exit 0
+ atmos_products.sh[1]: postamble atmos_products.sh 1703188983 0
+ preamble.sh[68]: set +x
End atmos_products.sh at 20:03:04 with error code 0 (time elapsed: 00:00:01)
```

This traces back to the way `$FHRLST` is defined in gfs_tasks.py:
https://github.com/NOAA-EMC/global-workflow/blob/d1251360325faf75af9df0608557fcd10202a883/workflow/rocoto/gfs_tasks.py#L582

This turns into a silent failure due to the following line in atmos_products.sh:
https://github.com/NOAA-EMC/global-workflow/blob/d1251360325faf75af9df0608557fcd10202a883/jobs/rocoto/atmos_products.sh#L28

### What should have happened?

The analysis products should be generated based off of the analysis master PGB.

### What machines are impacted?

All or N/A

### Steps to reproduce

Run a cycled experiment through the first full cycle then check gdasatmanlprod.log.

### Additional information

Found during cycle testing on Hercules.

### Do you have a proposed solution?

Replace `-f001` with `anl` in gfs_tasks.py, though this does not solve other potential silent `basename` failures in `atmos_products`.
Appended:
This doesn't fix the issue by itself as the `10#` operator causes a failure on `anl`.  Will need to wrap it in an if.

**Comment by WalterKolczynski-NOAA** [comment]
The underlying cause of this is that underscore is used as the delimiting character to separate forecast hours in the post groups. Short-term solution would be to remove the underscore from the job name. Long-term we are considering eliminating the groups, as they make the code needlessly complex (and ops does not run post in groups). Failing that, we could just use a different delimiter.

**Comment by DavidHuber-NOAA** [comment]
The `basename` error is coming from `preamble.sh`, so it's a different issue and doesn't affect the final result.  I found a solution to the negative, 0-padded integer problem and will submit a PR shortly.
