### ISSUE TITLE
GFS job JGLOBAL_ATMOS_PRODUCTS failed at finding master and flux files

### ISSUE THREAD

**Issue by WenMeng-NOAA** [NOAA-EMC/global-workflow#2191]
### What is wrong?

The new gfs job 'JGLOBAL_ATMOS_UPP' changed master and flux file names as  gfs.tCCz.masterfHHH.grib2 and gfs.tCCz.sfluxfHHH.grb2.  The downstream job 'JGLOBAL_ATMOS_PRODUCTS' failed at looking for master and flux files as gfs.tCCz.master.grb2fHHH and gfs.tCCz.sfluxgrbfHHH.grib2. 

### What should have happened?

The job 'JGLOBAL_ATMOS_PRODUCTS' should generate pgrb2/pgrb2b files.

### What machines are impacted?

All or N/A

### Steps to reproduce

Run job 'JGLOBAL_ATMOS_PRODUCTS'.

### Additional information

none.

### Do you have a proposed solution?

Update job 'JGLOBAL_ATMOS_PRODUCTS' with new master and flux file names.
In https://github.com/NOAA-EMC/global-workflow/blob/develop/scripts/exglobal_atmos_products.sh#L41
Change 
  master.grb2${fhr3}
into
  master${fhr3}.grb2

In https://github.com/NOAA-EMC/global-workflow/blob/develop/scripts/exglobal_atmos_products.sh#L176
Change
   sfluxgrb${fhr3}.grib2
into
  sflux${fhr3}.grb2

**Comment by GwenChen-NOAA** [comment]
This job should also generate GFS special files (gfs.txxz.special.grb2fhhh) for downstream jobs. Please see comment at https://github.com/NOAA-EMC/global-workflow/issues/2158#issuecomment-1858477059.

**Comment by WenMeng-NOAA** [comment]
From GFS HR3 at /scratch1/NCEPDEV/climate/Jessica.Meixner/HR3/scoutruns/scouthr3t01/COMROOT/scouthr3t01/logs/2020091300, the inline post generate master and flux files as 'gfs.t{CC}z.master.grb2f{FFF}', gfs.t{CC}z.sfluxgrbf{FFF}.grib2
From my inline post test, master and flux files are named as 'gfs.t{CC}z.masterf{FFF}.grb2' and 'gfs.t{CC}z.sfluxf{FFF}.grb2'

**Comment by WenMeng-NOAA** [comment]
> From GFS HR3 at /scratch1/NCEPDEV/climate/Jessica.Meixner/HR3/scoutruns/scouthr3t01/COMROOT/scouthr3t01/logs/2020091300, the inline post generate master and flux files as 'gfs.t{CC}z.master.grb2f{FFF}', gfs.t{CC}z.sfluxgrbf{FFF}.grib2 From my inline post test, master and flux files are named as 'gfs.t{CC}z.masterf{FFF}.grb2' and 'gfs.t{CC}z.sfluxf{FFF}.grb2'

May I get an update on the progress in addressing this issue? It seems the master and flux files generated from in-line post and off-line post have different naming conventions. @aerorahul @WalterKolczynski-NOAA
