### ISSUE TITLE
need to fix a directory name mismatch in chgres process

### ISSUE THREAD

**Issue by hyunchul386** [NOAA-EMC/global-workflow#2192]
### What is wrong?

In the script of sorc/ufs_utils.fd/util/gdas_init/run_v16.chgres.sh, fix_dir_target_grid is defined as "/fix_sfc", like
fix_dir_target_grid="${FIX_ORO}/${ORO_DIR}/fix_sfc"
but the directory name is not "/fix_sfc", but "/sfc", like as
/global-workflow_NS/sorc/ufs_utils.fd/fix/orog/C48/sfc

There are the same mismatches in the following scripts in /global-workflow_NS/sorc/ufs_utils.fd/util/gdas_init/
run_pre-v14.chgres.sh
run_v14.chgres.sh
run_v15.chgres.sh
run_v16.chgres.sh
run_v16retro.chgres.sh

### What should have happened?

The files in the $fix_dir_target_grid should be found, but it is broken by the mismatch in the directory name, currently.

### What machines are impacted?

All or N/A

### Steps to reproduce

1. clone build the develop branch of global-workflow
2. run the chgres scripts with extracting GFSv16 data into C48 

### Additional information

 In the run log,
   8321  FATAL ERROR:
   8322  OPENING: /scratch1/NCEPDEV/climate/Hyun-Chul.Lee/global-workflow_NS/sorc/ufs_ut
   8323  ils.fd/util/gdas_init/../../fix/orog/C48/fix_sfc/C48.slope_type.tile
   8324  1.nc: No such file or directory
   8325  STOP.

### Do you have a proposed solution?

In my try, it worked by a change in the script of "~sorc/ufs_utils.fd/util/gdas_init/run_v16.chgres.sh"
from:  fix_dir_target_grid="${FIX_ORO}/${ORO_DIR}/fix_sfc"
to: fix_dir_target_grid="${FIX_ORO}/${ORO_DIR}/sfc"
May be it need to be applied to other scripts of run_*.chgres.sh in the directory

**Comment by WalterKolczynski-NOAA** [comment]
These scripts are not used directly by global-workflow, only for offline IC generation. If you clone ufs-utils independently (as recommended in the [documentation for manually creating ICs](https://global-workflow.readthedocs.io/en/latest/init.html#manual-generation)) and run its own link script, it should link an older version of the fix directories which uses the old paths and file names. ufs-utils will eventually be updated to the new fix directories.

Closing as invalid. If you have any further issues, you likely need to open an issue with ufs-utils. If you believe this is in error, please reopen.
