### ISSUE TITLE
GFS restart paths are incorrect

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/global-workflow#2205]
### What is wrong?

`{cycs}` should be `{cycs}0000` on the referenced line I think

### What should have happened?

@kevindougherty-noaa was encountering errors

### What machines are impacted?

All or N/A

### Steps to reproduce

Run the GFS cycle after it crashed previously?

### Additional information

None

### Do you have a proposed solution?

Change the referenced line?

**Comment by CoryMartin-NOAA** [comment]
Sorry the line did not get carried through (probably because of the issue templates...)

https://github.com/NOAA-EMC/global-workflow/blame/c15875b6dbf685327af9316ee43b3d01f0fc815e/ush/forecast_det.sh#L69-L70

      if [[ -f "${COM_ATMOS_RESTART}/${PDYS}.${cycs}0000.coupler.res" ]]; then
        mv "${COM_ATMOS_RESTART}/${PDYS}.${cycs}.coupler.res" "${COM_ATMOS_RESTART}/${PDYS}.${cycs}.coupler.res.old"

**Comment by aerorahul** [comment]
@CoryMartin-NOAA 
Thanks for opening the issue.  Does the proposed solution resolve the issue?

**Comment by CoryMartin-NOAA** [comment]
@kevindougherty-noaa 's test seems to have just completed successfully, so I think so!

**Comment by kevindougherty-noaa** [comment]
@aerorahul Yes, the tests successfully succeeded with that one line change after failing before @CoryMartin-NOAA's suggestion.

**Comment by aerorahul** [comment]
Thanks @kevindougherty-noaa @CoryMartin-NOAA 
I'll include this in an upcoming PR or if you wish, you could issue a hotfix PR.

**Comment by CoryMartin-NOAA** [comment]
It can wait, it's a pretty specific situation where this bug is found (the gfs fcst is re-run but there are some restarts already written). Of course, that is very important for ops!
