### ISSUE TITLE
`FHMAX_GFS_${cyc}` has no relevance in the global-workflow anymore

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/global-workflow#2218]
### What new functionality do you need?

In past GFS implementations, the GFS forecast lengths varied between cycles; e.g. 00z and 06z forecasts would have been different lengths.
A search for `FHMAX_GFS_` results in no hits beyond `config.base` and some places in the workflow generation.
They can be simplified to key on `FHMAX_GFS`
Running different forecast lengths for different cycles is no longer supported in the global-workflow.

### What are the requirements for the new functionality?

Existing functionality and operation should not be impacted.

### Acceptance Criteria

Requirements are met following the suggested changes in functionality.

### Suggest a solution (optional)

Eliminate `FHMAX_GFS_00` etc and consolidate around `FHMAX_GFS`.

**Comment by KateFriedman-NOAA** [comment]
Will also be updating `FHMAX_GFS` to be populated via yaml and user inputs instead of being hardcoded.
