### ISSUE TITLE
Add wgne dataset generation in GFS ATMOS_PRODUCT process

### ISSUE THREAD

**Issue by WenMeng-NOAA** [NOAA-EMC/global-workflow#2226]
### What new functionality do you need?

The ops. GFS v16 has been generating wgne dataset which include continuous accumulated precipitation at 0.25 deg. from  F003 to F180. This process should be added in the ATMOS_PRODUCT for GFS v17.

### What are the requirements for the new functionality?

The wgne data files will be generated from F003 to F180 in 0.25 deg..

### Acceptance Criteria

The sample wgne data files from GFS V16.3 at /lfs/h1/ops/prod/com/gfs/v16.3/gfs.20240116/00/atmos:
```
wen.meng@dlogin03 atmos$ wgrib2 gfs.t00z.wgne.f138 -V
1:0:vt=2024012118:surface:0-138 hour acc fcst:APCP Total Precipitation [kg/m^2]:
    ndata=1038240:undef=0:mean=14.4991:min=0:max=783.25
    grid_template=0:winds(N/S):
        lat-lon grid:(1440 x 721) units 1e-06 input WE:NS output WE:SN res 48
        lat 90.000000 to -90.000000 by 0.250000
        lon 0.000000 to 359.750000 by 0.250000 #points=1038240
```

### Suggest a solution (optional)

See https://github.com/NOAA-EMC/UPP/blob/release/gfs_v16/ush/fv3gfs_downstream_nems.sh#L269

**Comment by aerorahul** [comment]
Thanks @WenMeng-NOAA 
This should be easy enough to add back.
