### ISSUE TITLE
Add new files for unstructured grid support

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#2229]
### Target fix directory

wave

### Type of change

- [ ] Update existing files
- [ ] Remove files
- [X] Add new files to existing directory
- [ ] Add new fix directory

### Any workflow changes needed?

No change needed

### Related issues

https://github.com/NOAA-EMC/global-workflow/issues/1547

There are no immediate workflow changes, however this will be required for an upcomming PR.  

### Pickup location

/scratch1/NCEPDEV/climate/Jessica.Meixner/NewFixForWave20240116

### Size

531 MB

**Comment by WalterKolczynski-NOAA** [comment]
Added on Hera and synchronized to Orion

**Comment by KateFriedman-NOAA** [comment]
Synced to WCOSS2-Dogwood and Jet. Will sync to WCOSS2-Cactus when it's back from its maintenance outage.

**Comment by JessicaMeixner-NOAA** [comment]
@KateFriedman-NOAA and @WalterKolczynski-NOAA  I just discovered I left off two input files that are needed: 
ww3_grid.inp.uglo_100km
ww3_grid.inp.uglo_m1g16
I have put them in: 
/scratch1/NCEPDEV/climate/Jessica.Meixner/NewFixForWave20240116

Please let me know if you'd like a separate issue or new source location.

**Comment by KateFriedman-NOAA** [comment]
@JessicaMeixner-NOAA All good, I'll pull them into the new `wave/20140105` set on Hera and then we'll sync them to the other platforms.

**Comment by KateFriedman-NOAA** [comment]
Pulled two wave fix files into new `wave/20240105` set on Hera:
```
[role.glopara@hfe10 20240105]$ pwd
/scratch1/NCEPDEV/global/glopara/fix/wave/20240105
[role.glopara@hfe10 20240105]$ ll ww3_grid.inp.uglo_100km ww3_grid.inp.uglo_m1g16
-rw-r--r-- 1 role.glopara global 6338 Jan 18 16:27 ww3_grid.inp.uglo_100km
-rw-r--r-- 1 role.glopara global 6391 Jan 18 16:27 ww3_grid.inp.uglo_m1g16
```

Proceeding to sync to other platform fix copies...

**Comment by KateFriedman-NOAA** [comment]
Have synced those two additional wave fix files to WCOSS2-Dogwood and Jet. Still awaiting the return of WCOSS2-Cactus to sync the new `wave/20240105` set there.

**Comment by JessicaMeixner-NOAA** [comment]
Thank you @KateFriedman-NOAA !

**Comment by WalterKolczynski-NOAA** [comment]
Synced to Orion

**Comment by KateFriedman-NOAA** [comment]
Synced to WCOSS2-Cactus. Closing this as complete.

**Comment by KateFriedman-NOAA** [comment]
@JessicaMeixner-NOAA Would you mind adding details about the new wave fix files in the fix file spreadsheet? I have added the new files to the wave subsheet, just need descriptions of them. Thanks!

https://docs.google.com/spreadsheets/d/1BeIvcz6TO3If4YCqkUK-oz_kGS9q2wTjwLS-BBemSEY/edit?pli=1#gid=755156989

**Comment by JessicaMeixner-NOAA** [comment]
@KateFriedman-NOAA spreadsheet has been updated.  Please let me know if I can provide any additional details.

**Comment by KateFriedman-NOAA** [comment]
Awesome, thanks @JessicaMeixner-NOAA !
