### ISSUE TITLE
Update link_workflow.sh with UPP relevant parm files 

### ISSUE THREAD

**Issue by WenMeng-NOAA** [NOAA-EMC/global-workflow#2241]
### What new functionality do you need?

The UPP repository has updated with control files for GFS, GEFS and some aerosol parm files. These changes should be implemented in linking UPP relevant parm files in link_workflow.sh.

### What are the requirements for the new functionality?

Linking some GFS and GEFS control files from UPP/parm, and aerosol parm files from UPP/fix/chem.

### Acceptance Criteria

All symbolic links under global-workflow/parm/post are valid.

### Suggest a solution (optional)

Please refer to the changes at
https://github.com/WenMeng-NOAA/global-workflow/commit/269af9e4c2515eda2753859da508b66e0d312360#diff-d5dc1af75ff685072f5162e81440008320fe66bce26d17bd5e143ce2d3a0aa7a

**Comment by KateFriedman-NOAA** [comment]
Resolved by https://github.com/NOAA-EMC/global-workflow/pull/2243. Closing.
