### ISSUE TITLE
archive job succeeds despite HTAR failure 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#2242]
### What is wrong?

I forgot to change my HPSS directory, however despite clear messages in the log file that the HTAR failed, the job is recorded as "SUCCEED" in rocoto stat.    /scratch1/NCEPDEV/climate/Jessica.Meixner/HR3/scoutruns/scouthr3t01/COMROOT/scouthr3t01/logs/2020091300/gfsarch.log 
```

ERROR: /apps/hpss/bin/htar: error -1 stat-ing "gfs.20200913/00/products/atmos/grib2/0p50/gfs.t00z.pgrb2.0p50.anl"
*** Warning: No matching names located for 'gfs.20200913/00/products/atmos/grib2/0p50/gfs.t00z.pgrb2.0p50.anl'
ERROR: /apps/hpss/bin/htar: error -1 stat-ing "gfs.20200913/00/products/atmos/grib2/0p50/gfs.t00z.pgrb2.0p50.anl.idx"
*** Warning: No matching names located for 'gfs.20200913/00/products/atmos/grib2/0p50/gfs.t00z.pgrb2.0p50.anl.idx'
ERROR: /apps/hpss/bin/htar: error -1 stat-ing "gfs.20200913/00/products/atmos/grib2/1p00/gfs.t00z.pgrb2.1p00.anl"
*** Warning: No matching names located for 'gfs.20200913/00/products/atmos/grib2/1p00/gfs.t00z.pgrb2.1p00.anl'
ERROR: /apps/hpss/bin/htar: error -1 stat-ing "gfs.20200913/00/products/atmos/grib2/1p00/gfs.t00z.pgrb2.1p00.anl.idx"
*** Warning: No matching names located for 'gfs.20200913/00/products/atmos/grib2/1p00/gfs.t00z.pgrb2.1p00.anl.idx'
ERROR: htar_MakeAllSubdirs: Permission error creating intermediate HPSS subdirectory: /NCEPDEV/emc-global/1year/Jessica.Meixner
HTAR: HTAR FAILED
###WARNING  htar returned non-zero exit status.
```

then later on: 

`End arch.sh at 00:17:49 with error code 0 (time elapsed: 00:12:40)
`

### What should have happened?

If HTAR fails, shouldn't the job fail? 

### What machines are impacted?

All or N/A

### Steps to reproduce

Try running an archive but to an hpss area you do not have access to.  

### Additional information

None. 

### Do you have a proposed solution?

not yet

**Comment by WalterKolczynski-NOAA** [comment]
@DavidHuber-NOAA can you pick this up, since you were recently making fixes for this?

**Comment by DavidHuber-NOAA** [comment]
@WalterKolczynski-NOAA Sure, I'll take a look.

**Comment by DavidHuber-NOAA** [comment]
This should expand to a larger effort to correctly identify all expected files for each cycle rather than assuming any missing files in the first few cycles are intentional.  There are already some places in `hpssarch_gen.sh` where file existence tests are done before adding them to archive lists.  This should probably be moved out to a standard set of (`yaml`?) lists based on cycle and workflow options and expanded upon, then perform status checks on every `htar`/`tar` command.  I'll have to tackle this in a later sprint.

**Comment by WalterKolczynski-NOAA** [comment]
Subsumed by #2345

**Comment by JessicaMeixner-NOAA** [comment]
@WalterKolczynski-NOAA Issue 2345 is about missing data, this issue is the fact that I was trying to write into an HPSS directory I did not have access to.  If this issue remains closed, can 2345 be updated to address more general HTAR failures beyond just missing files?

**Comment by WalterKolczynski-NOAA** [comment]
#2345 has been updated to explicitly mention other htar failures.
