### ISSUE TITLE
Merge NCO's gfs.v16.0.4 and gfs.v16.0.5 updates into release/gfsv16.0.0

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/global-workflow#226]
NCO updated the wall time in numerous ecflow scripts prior to the start of the 30-day parallel test.  These updates need to be captured in release/gfsv16.0.0.    A new UPP tag has also been created and pulled into NCO's v16 package.   This issue is opened to capture these updates in release/gfsv16.0.0

**Comment by KateFriedman-NOAA** [comment]
SPA Jen sent a list of the changes for v16.0.4:

> 1. change from Boi for reducing WMO files size:
/gpfs/dell1/nco/ops/nwpara/gfs-v16/gfs.v16.0.4
scripts/exgfs_atmos_awips_20km_1p0deg.sh
scripts/exgfs_atmos_grib_awips.sh
ush/scale_dec.sh
>
> 2. Change from Wen to add the missing alert for special file (tag: upp_gfsv16_release.v1.1.2)
/gpfs/dell1/nco/ops/nwpara/gfs-v16/gfs.v16.0.3/scripts/exgfs_atmos_nceppost.sh
>
> 3. ecflow scripts
I compared the wall clock and runtime for the gfs and gdas jobs,  and updated a lot of gfs and gdas ecflow scripts to adjust the wall clock to be more close to the runtime range.
 /gpfs/dell1/nco/ops/nwpara/gfs-v16/gfs.v16.0.4/ecflow/ecf/scripts/
gfs/
gdas/

1. Taken care of by Boi and Fanglin's commits into release/gfsv16.0.0 at 47efddf and 3a955b4
2. Taken care of by Russ's commit into release/gfsv16.0.0 at 104328a
3. Also taken care of by commit at 104328a

Merge of changes for v16.0.4 in release/gfsv16.0.0 appears complete. Will now do a diff between a fresh clone of release/gfsv16.0.0 and nwpara gfsv16.0.4 to confirm all diffs are in.

**Comment by KateFriedman-NOAA** [comment]
Two remaining diffs from v16.0.4 need to get pulled into release/gfsv16.0.0, awaiting confirmation from SPA Jen and then will commit to release/gfsv16.0.0. 

For v16.0.4 tag...since v16.0.5 changes are already in release/gfsv16.0.0 as of 3a955b4 I have created the v16.0.4 tag from the commit prior to the v16.0.5 commits (104328a). New tag: [EMC-v16.0.4](https://github.com/NOAA-EMC/global-workflow/releases/tag/EMC-v16.0.4)

Will commit remaining v16.0.4 diffs to release/gfsv16.0.0 and then tag branch for v16.0.5.

**Comment by KateFriedman-NOAA** [comment]
Issue #227 discusses the diffs for v16.0.5.

**Comment by KateFriedman-NOAA** [comment]
Committed remaining diffs to exgfs_atmos_grib2_special_npoess.sh at 91597f5. Created new tag of release/gfsv16.0.0 for v16.0.5: [EMC-v16.0.5](https://github.com/NOAA-EMC/global-workflow/releases/tag/EMC-v16.0.5)

**Comment by KateFriedman-NOAA** [comment]
Work for this issue completed, now closing. Will reopen if needed.

**Comment by KateFriedman-NOAA** [comment]
New UPP tag being made by Wen. Reopening issue.

**Comment by KateFriedman-NOAA** [comment]
Updated UPP tag to [upp_gfsv16_release.v1.1.3](https://github.com/NOAA-EMC/EMC_post/releases/tag/upp_gfsv16_release.v1.1.3). Recut EMC-v16.0.5 tag.

**Comment by RussTreadon-NOAA** [comment]
For consistency should the EMC_post tag in Externals.cfg also be updated
from upp_gfsv16_release.v1.1.2 to upp_gfsv16_release.v1.1.3?

**Comment by KateFriedman-NOAA** [comment]
> For consistency should the EMC_post tag in Externals.cfg also be updated from upp_gfsv16_release.v1.1.2 to upp_gfsv16_release.v1.1.3?

@RussTreadon-NOAA Yes, just committed that too, thanks for checking! Recutting tag once more now.

**Comment by KateFriedman-NOAA** [comment]
Got update into Externals.cfg and recut EMC-v16.0.5 again, hopefully last time for this version. Will now close this issue and reopen as needed. Further version changes will be documented in new issues.
