### ISSUE TITLE
Reducing bufr sounding postsnd output volume

### ISSUE THREAD

**Issue by GuangPingLou-NOAA** [NOAA-EMC/global-workflow#227]
Per new request from NCO, the output disk sizes from bufr sounding postsnd need to be reduced to the level similar to that of GFS v15.

**Comment by GuangPingLou-NOAA** [comment]
Working on reducing the vertical levels from 127 to 64 in the output. The 64-level output will contain every other levels of 127.

**Comment by GuangPingLou-NOAA** [comment]
The changes were committed to the github and merged into the authoritative branch. The issue is closed.

**Comment by GuangPingLou-NOAA** [comment]
Checked out NCO test run for the modified version (gfs v16.0.5) the results looked good and files sizes are all reduced by about half. But the wall time was 55 minutes which was longer than 27 minutes in my tests.

**Comment by KateFriedman-NOAA** [comment]
@GuangPingLou-NOAA I think this work is complete, please confirm that and close this issue if so. Thanks!

**Comment by GuangPingLou-NOAA** [comment]
@KateFriedman-NOAA, yes, NCO has pulled the changes. Thanks.
