### ISSUE TITLE
GFSv16.3.15 - Update to obsproc.v1.2

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#2291]
### What new functionality do you need?

Update to `obsproc.v1.2` when it is introduced in operations. Also make related GSI change to turn GMI back on.

### What are the requirements for the new functionality?

- [x] Update `obsproc_ver` in version files in `dev/gfs.v16`
- [ ] Update `obsproc_ver` in version files in `develop`
- [x] Install `obsproc.v1.2` on R&D machines
- [ ] Uncomment GMI line `scripts/exglobal_atmos_analysis.sh` (commented out in https://github.com/NOAA-EMC/global-workflow/pull/1404).
- [x] Update ops version in RTD

### Acceptance Criteria

New version works everywhere.

**Comment by KateFriedman-NOAA** [comment]
Update from @ilianagenkova - implementation date next Wednesday May 8th during the 12z cycle:
```
Hello users,

Following a successful PPT in early April, and should there be no CWD or anything else unexpected, 
NCO is targeting to implement obsporc v1.2  on May 8th 12z .

This update will:
- add high-vertical resolution radiosonde profiles (up to 255 pressure levels) to the global and RAP prepbufr files;
- add high-vertical resolution radiosonde profiles (full profiles) to the newly established global and RAP *uprair* bufr dump files;
- add high-spatial and temporal resolution hurricane tailored winds for the HAFS model in the *satwhr* buff dump files;
- increase the amount of msonet observations across all regional models 

Expect larger prepbufr  and msonet bufr dump files and allow for longer run times reading/processing these.

Also, more obs data will be shared via NOMADS -
  - GFS gfs.tCCz.TYPE.tm00.bufr_d

Where TYPE is BUFR formatted files *ahicsr*, *crisf4*, *crsfdb*, *gsrasr*, *gsrcsr*, *omi*, *ompslp*, *ompsn8*, *ompst8*, *satwhr*, *sevasr*, *uprair*

  - GDAS gdas.tCCz.TYPE.tm00.bufr_d

Where TYPE is BUFR formatted files *ahicsr*, *avcsam*, *avcspm*, *crsfdb*, *gsrasr*, *gsrcsr*, *omi*, *ompslp*, *ompsn8*, *ompst8*, *satwhr*, *sevasr*, *uprair*

 - RAP rap.tCCz.TYPE.tm00.bufr_d

Where TYPE is BUFR formatted files *gsrasr*, *gsrcsr*, and *uprair*

See the [SCN ](https://docs.google.com/document/d/1qRUw5xO4zKJSedNMNp555tpjfw1h87XOK2-wdTEHlP8/edit)for details.

Feel free to forward this to anyone who might benefit from the heads up.

Thanks, 
iliana
```

**Comment by KateFriedman-NOAA** [comment]
From May 3rd RFC memo:
```
RFC 12604 - On WCOSS2, implement the OBSPROC v1.2.0 upgrade along
with downstream models' updates. This upgrade will:

● Expand the global observation datasets (gfs and gdas) with high vertical
resolution radiosonde profiles, and high spatial and temporal resolution
satellite winds tailored for hurricane events
● Expand the rap observation dataset with high vertical resolution
radiosonde profiles. It will also increase the volume of msonet
observations across all regional networks and expand the capacity of
SDMEDIT list entries per observation type.
● Several internal BUFR-lib related arrays were increased to accommodate
increasing obs data volumes.
● A number of obs data sets were added to NOMADS (see SCN).
● Turn off the obsproc_air_now job since the EPA AirNow data was
stopped.

To be implemented on May 8, 1100Z to 1800Z and May 9, 1400Z to 1800Z.
```

**Comment by ilianagenkova** [comment]
SPA update: Due to ECE/CWD, the OBSPROC upgrade is postponed to May 09 2024 12z .

**Comment by KateFriedman-NOAA** [comment]
Update from @ilianagenkova and NCO: `Due to Enhanced Caution remaining in effect until 1200Z Fri May 10 2024 SPAs  will implement obsproc v1.2 on Monday 5/13 12z.`

**Comment by KateFriedman-NOAA** [comment]
Delayed to May 16th due to continued EC. From last Friday's RFC memo (date now changed):
```
RFC 12604 - On WCOSS2, implement the OBSPROC v1.2.0 upgrade along
with downstream models' updates. This upgrade will:
● Expand the global observation datasets (gfs and gdas) with high vertical
resolution radiosonde profiles, and high spatial and temporal resolution
satellite winds tailored for hurricane events
● Expand the rap observation dataset with high vertical resolution
radiosonde profiles. It will also increase the volume of msonet
observations across all regional networks and expand the capacity of
SDMEDIT list entries per observation type.
● Several internal BUFR-lib related arrays were increased to accommodate
increasing obs data volumes.
● A number of obs data sets were added to NOMADS (see SCN).
● Turn off the obsproc_air_now job since the EPA AirNow data was
stopped.
Was to be implemented on May 8, 1100Z to 1800Z and May 9, 1400Z to 1800Z;
postponed due to ECE/CWD; new dates are May 13 (1100Z to 1800Z) and May
14 (1500Z to 1800Z.
```

**Comment by KateFriedman-NOAA** [comment]
Release created and announced to users: https://github.com/NOAA-EMC/global-workflow/releases/tag/gfs.v16.3.15

**Comment by KateFriedman-NOAA** [comment]
@WalterKolczynski-NOAA Please install the new `obsproc/v1.2.0` on Orion and Hercules:
```
git clone -b obsproc.v1.2.0-rd-gfsv17 https://github.com/NOAA-EMC/obsproc.git ./v1.2.0
cd v1.2.0
INSTALL_TARGET=orion[hercules] INSTALL_PREFIX=path_to_install ./ush/build.sh
```

**Comment by WalterKolczynski-NOAA** [comment]
Installed in `/work/noaa/global/glopara/git_rocky9/obsproc/v1.2.0`. Since Orion is now also Rocky 9, should we just switch Orion to use that location as well?

**Comment by KateFriedman-NOAA** [comment]
> Installed in `/work/noaa/global/glopara/git_rocky9/obsproc/v1.2.0`. Since Orion is now also Rocky 9, should we just switch Orion to use that location as well?

Yeah, good idea. That would mean changing [`BASE_GIT` in `workflow/hosts/orion.yaml`](https://github.com/NOAA-EMC/global-workflow/blob/develop/workflow/hosts/orion.yaml#L1). I can do that in my branch that updates the obsproc/prepobs versions. Need to make sure all other external packages are installed and good-to-go in the `git_rocky9` folder. I'll have a request for you to install a new prepobs version on MSU soon, so that can just go to `git_rocky9` as well.

**Comment by KateFriedman-NOAA** [comment]
Updated `BASE_GIT` in my branch @ https://github.com/KateFriedman-NOAA/global-workflow/commit/f36c3294ec9603d4c0eba0f9210a1134ba05c095

**Comment by KateFriedman-NOAA** [comment]
> Uncomment GMI line scripts/exglobal_atmos_analysis.sh (commented out in https://github.com/NOAA-EMC/global-workflow/pull/1404

@ADCollard Are we able to uncomment the GMI lines in `scripts/exglobal_atmos_analysis.sh` yet or need to wait still? I see it is still commented out in ops:
```
kate.friedman@clogin03:/lfs/h1/ops/prod/packages/gfs.v16.3.18> grep GMI scripts/exglobal_atmos_analysis.sh
#GMI1CRBF=${GMI1CRBF:-${COMIN_OBS}/${OPREFIX}gmi1cr.tm00.bufr_d${OSUFFIX}} # GMI temporarily disabled due to array overflow.
#$NLN $GMI1CRBF         gmibufr   # GMI temporarily disabled due to array overflow.
```

**Comment by ADCollard** [comment]
> > Uncomment GMI line scripts/exglobal_atmos_analysis.sh (commented out in #1404
> 
> @ADCollard Are we able to uncomment the GMI lines in `scripts/exglobal_atmos_analysis.sh` yet or need to wait still? I see it is still commented out in ops:
> 
> ```
> kate.friedman@clogin03:/lfs/h1/ops/prod/packages/gfs.v16.3.18> grep GMI scripts/exglobal_atmos_analysis.sh
> #GMI1CRBF=${GMI1CRBF:-${COMIN_OBS}/${OPREFIX}gmi1cr.tm00.bufr_d${OSUFFIX}} # GMI temporarily disabled due to array overflow.
> #$NLN $GMI1CRBF         gmibufr   # GMI temporarily disabled due to array overflow.
> ```

@KateFriedman-NOAA This can now be uncommented.

**Comment by KateFriedman-NOAA** [comment]
> @KateFriedman-NOAA This can now be uncommented.

Great, thanks for confirming @ADCollard ! I will open a separate issue/PR to take care of that. I'll ask you to be a reviewer.
