### ISSUE TITLE
JEDI-DA atmosphere only CI case

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/global-workflow#2294]
### What new functionality do you need?

Add JEDI-DA atmosphere only case to `ci`.  This is a requested test case listed in issue #1821.

### What are the requirements for the new functionality?

Cycle g-w in atmosphere only mode using UFS-DA applications for the variational and local ensemble analyses.

### Acceptance Criteria

JEDI-DA atmosphere only CI test passes

**Comment by RussTreadon-NOAA** [comment]
Work for this issue will be done in [RussTreadon-NOAA:feature/jedi_atm_ci](https://github.com/RussTreadon-NOAA/global-workflow/tree/feature/jedi_atm_ci)

**Comment by RussTreadon-NOAA** [comment]
@WalterKolczynski-NOAA and @aerorahul , how do I go about testing CI for JEDI 3denvar?  

I anticipate work on this issue being an iterative cycle of _add, test, debug, fix, & repeat_. I'd like to do as much of this development myself and not burden the g-w team.

**Comment by aerorahul** [comment]
@RussTreadon-NOAA 
I normally do the following:
```bash
pslot="expt_name" RUNTESTS="/some/large/space/for/COM" SLURM_ACCOUNT="da-cpu" ./workflow/create_experiment.py --yaml ci/cases/pr/TEST_YAML.yaml
```
This creates:
```
EXPDIR: /some/large/space/for/COM/EXPDIR/expt_name
ROTDIR: /some/large/space/for/COM/COMROOT/expt_name
```

The experiment directory is now ready for setting the crontab and the test to run without any manual intervention.

**Comment by RussTreadon-NOAA** [comment]
Thank you @aerorahul .  Let me give this a try.

**Comment by RussTreadon-NOAA** [comment]
**JEDI ATM DA quirks**

Several changes were committed at a41a0dba.  These changes require explanation.

JEDI ATM DA does not support NSST.  However, the GFS v17 UFS weather model requires NSST be on.  The hack to get things working is as follows:
- set `DONST=NO` in `config.sfcanl` when `DO_JEDIATMVAR=YES` 
- set `DONST=NO` in `config.esfc` when `DO_JEDIATMENS=YES`
- set `NST_MODEL=1` in when `DO_JEDIATMVAR=YES` or `DO_JEDIATMENS=YES` 

Line 222 of `workflow/setup_expt.py` is currently hardwired to copy `abias`, `abias_pc`, `radstat`, and `abias_air`.  The JEDI ATM variational solver does not yet fully support variational bias correction of aircraft data.  Variational bias correction of radiance observations is avaiable but JEDI does not use the `abias`, `abias_pc`, and `radstat` files.  

As currently coded JEDI reads two netcdf files and one ascii file for each _sensor_satellite_ processed.   The C48 JEDI ATM 3denvar case assimilates _atms_n20_ radiances.   The bias correction files JEDI expects are 
1. `$(GPREFIX)atms_n20.satbias.nc4`
2. `$(GPREFIX)atms_n20.satbias_cov.nc4`
3. `$(GPREFIX)atms_n20.tlapse.txt`

So as to get the CI test to work, the following clunky change was made to `workflow/setup_expt.py`
```
-    for ftype in ['abias', 'abias_pc', 'abias_air', 'radstat']:
+    for ftype in ['abias', 'abias_pc', 'abias_air', 'radstat', 'atms_n20.satbias.nc4', 'atms_n20.satbias_cov.nc4', 'atms_n20.tlapse.txt' ]:
```
This is not acceptable.  How would we like to handle this long term?

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA I'm wondering if we want to place our satbias, etc. files in a tarball so that only one (or a few) files need to be pulled when staging ICs, and then the workflow extracts them in the `anlinit` job?

**Comment by RussTreadon-NOAA** [comment]
**GDASApp blocker:  bufr2ioda converters**

The prepatmiodaobs job aborts because expected bufr dump files are not present in the GDA.   This is a know issue and has been reported via GDASApp issues 

- [#897](https://github.com/NOAA-EMC/GDASApp/issues/897):  marine bufr2ioda converters fail in prepatmiodaobs
- [#898](https://github.com/NOAA-EMC/GDASApp/issues/898):  bufr2ioda_satwind_amv_goes fails when expected subset not found
- [#907](https://github.com/NOAA-EMC/GDASApp/issues/907):  bufr2ioda_snocvr_bufr fails because expected input not present

The current solution is to move or rename failing bufr2ioda converters so prepatmiodaobs does not attempt to execute the converters in question.  This is not an acceptable solution.

The C48C48_ufs_hybatmDA case was set up using the procedure @aerorahul outlined.  The first half gdas cycle successfully ran.  

The 2021032318 gdasprepatmiodaobs failed while attempting to process marine data because the GDA does not contain marine bufr dump files.  The solution in JEDI cycling tests is to move the marine converters into a sub-directory name `marine`.  

The satwind_amv_goes and snocvr converters fail due to missing expected input data.  The prefix `skip_` is added to each converter thereby bypassing each converter when prepatmiodaobs runs.  These changes were made in a working copy of `feature/jedi_atm_ci` to allow prepatmiodaobs to successfully run to completion. 

GDASApp resolution of the bufr2ioda converter issue is necessary before a JEDI-DA atmosphere CI case can be added to g-w.

**Comment by RussTreadon-NOAA** [comment]
> @RussTreadon-NOAA I'm wondering if we want to place our satbias, etc. files in a tarball so that only one (or a few) files need to be pulled when staging ICs, and then the workflow extracts them in the `anlinit` job?

This is an option.  We'll need to add scripting to the init jobs to untar the bias correction tarballs.

**Comment by RussTreadon-NOAA** [comment]
Question for @CatherineThomas-NOAA , @CoryMartin-NOAA , @WalterKolczynski-NOAA , and @aerorahul 

`ush/python/pygfs/task/atm_analysis.py` uses the following to stage ensemble backgrounds for EnVar 
```
        # stage ensemble files for use in hybrid background error
        if self.task_config.DOHYBVAR:
            logger.debug(f"Stage ensemble files for DOHYBVAR {self.task_config.DOHYBVAR}")
            localconf = AttrDict()
            keys = ['COM_ATMOS_RESTART_TMPL', 'previous_cycle', 'ROTDIR', 'RUN',
                    'NMEM_ENS', 'DATA', 'current_cycle', 'ntiles']
            for key in keys:
                localconf[key] = self.task_config[key]
            localconf.RUN = 'enkf' + self.task_config.RUN
            localconf.dirname = 'ens'
            FileHandler(self.get_fv3ens_dict(localconf)).sync()
```
When running the early cycle `self.task_config.RUN` is `gfs`.  Thus, `FileHandler` copies from `enkfgfs`.  When running the late cycle, `self.task_config.RUN` is `gdas`.  Thus, `FileHandler` copies from `enkfgdas`.  

**Whether we are running the `gfs` or `gdas` cycle don't we want the ensemble members for EnVar to be copied from `enkfgdas`?**

**Comment by CoryMartin-NOAA** [comment]
I think so, yes, to mirror how we grab the backgrounds from `gdas` regardless of if it is `gfs` or `gdas` for the deterministic run

**Comment by RussTreadon-NOAA** [comment]
Thanks @CoryMartin-NOAA .   This is my thinking, too.   In this case, we can't use
```
localconf.RUN = 'enkf' + self.task_config.RUN
```
Either we hardwire 
```
localconf.RUN = 'enkf' + 'gdas'
```
or
```
localconf.RUN = 'enkfgdas`
```

Alternatively, we export `GDUMP` or `GDUMP_ENS` from `JGLOBAL_ATM_ANALYSIS_INITIALIZE`.  Currently the j-job sets
```
GDUMP="gdas"
GDUMP_ENS="enkf${GDUMP}"
```
but since these variables are not exported they are not accessible from `self.task_config.   

If we export `GDUMP_ENS` we could set
```
localconf.RUN = self.task_config.GDAS_ENS
```

What does the g-w team prefer?

**Comment by RussTreadon-NOAA** [comment]
**Hera test**

The following was done on Hera

1. Clone `feature/jedi_atm_ci` at [`91b9308`](https://github.com/RussTreadon-NOAA/global-workflow/commit/91b930886e332e53e98f5c281447a65cf89d30f0) in /scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/jedi_atm_ci.  Execute `build_all.sh` and `link_workflow.sh` in `sorc`.

2. Edit `workflow/hosts/hera.yaml` as follows
```
-BASE_CPLIC: '/scratch1/NCEPDEV/global/glopara/data/ICSDIR/prototype_ICs'
+BASE_CPLIC: '/scratch1/NCEPDEV/stmp2/Russ.Treadon/ICS'
```
to pick up ICs for C48C48 JEDI-DA atmosphere case.

3. Create `setup.sh` which contains
```
#!/bin/bash
set -x

HOMEgfs=/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/jedi_atm_ci

cd $HOMEgfs

set +x
source ./workflow/gw_setup.sh
set -x

export pslot="prci"
export RUNTESTS="/scratch1/NCEPDEV/stmp2/Russ.Treadon"
export SLURM_ACCOUNT="da-cpu"
./workflow/create_experiment.py --yaml ./ci/cases/pr/C48C48_ufs_hybatmDA.yaml
```

4. Execute `setup.sh`.  This created `EXPDIR=/scratch1/NCEPDEV/stmp2/Russ.Treadon/EXPDIR/prci` and `ROTDIR="/scratch1/NCEPDEV/stmp2/Russ.Treadon/COMROOT/prci`.

5. cd EXPDIR.  Execute "rocotorun -d prci.db -w prci.xml`.  This launched 2021032312 gdasstage_ic.   Job `gdasstage_ic` populated ROTDIR with the files needed to run a JEDI-DA atmosphere only parallel

6. Set up cron to automatically execute `rocotorun -d prci.db -w prci.xml`.

7. Let cron drive prci to EDATE=2021032400.  All jobs for all cycles ran to completion
```
Hera(hfe07):/scratch1/NCEPDEV/stmp2/Russ.Treadon/EXPDIR/prci$ rocotostat -d prci.db -w prci.xml -c all -s
   CYCLE         STATE           ACTIVATED              DEACTIVATED
202103231200        Done    Feb 13 2024 15:44:59    Feb 13 2024 16:05:12
202103231800        Done    Feb 13 2024 15:44:59    Feb 13 2024 17:10:08
202103240000        Done    Feb 13 2024 15:44:59    Feb 13 2024 18:51:55
```

**Comment by RussTreadon-NOAA** [comment]
Since PR #2309 has been completed, shall we close this issue?   

PR #2309 brought into g-w the config and yaml changes needed to add a JEDI-DA atmosphere only CI case to g-w.  What remains is to add changes to stage the ICs required by this test.  It was agreed that g-w updates related to staging will be the subject of a new PR and, presumably, a new issue.  Hence this question - _may this issue be closed_?

**Comment by aerorahul** [comment]
@RussTreadon-NOAA 
I don't think this issue can be closed as we don't have the ability to run this test yet.
As you note, further work is needed in the staging to complete this issue.  
I am fine with continuing that work in this issue or opening a new issue an linking it to this one as a prerequisite.

**Comment by RussTreadon-NOAA** [comment]
@aerorahul , since I probably won't be the one doing the staging work a new issue referencing this issue seems more appropriate.  But I'm fine with others documenting the staging work in this issue if they prefer doing so.

**Comment by RussTreadon-NOAA** [comment]
Create [`RussTreadon-NOAA:feature/ufsda_atm_ci`](https://github.com/RussTreadon-NOAA/global-workflow/tree/feature/ufsda_atm_ci) for minimal set of changes to invoke UFS-DA (aka JEDI-DA) atmosphere only CI case.

**Comment by RussTreadon-NOAA** [comment]
**Hera JEDI ATM only CI test**

Perform the following test on Hera

1. Install [`RussTreadon-NOAA:feature/ufsda_atm_ci`](https://github.com/RussTreadon-NOAA/global-workflow/tree/feature/ufsda_atm_ci) at [`907e475`](https://github.com/RussTreadon-NOAA/global-workflow/commit/907e475cc0a9881f8f2ab9e8b176572ec4ce66be).  
2. Install [`RussTreadon-NOAA:feature/bufr2ioda`](https://github.com/RussTreadon-NOAA/GDASApp/tree/feature/bufr2ioda) at [`ed7d147`](https://github.com/RussTreadon-NOAA/GDASApp/commit/ed7d14736a12e90fe47a4b331b333a65478f11b2) inside `gdas.cd`.
3. execute `setup.sh` to create and populate `EXPDIR` and `COMROOT`.  Below are the contents of `setup.sh`
```
#!/bin/bash
set -x

HOMEgfs=/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/work

cd $HOMEgfs

set +x
source ./workflow/gw_setup.sh
set -x

export pslot="prci"
export RUNTESTS="/scratch1/NCEPDEV/stmp2/Russ.Treadon"
export SLURM_ACCOUNT="da-cpu"
export ICSDIR_ROOT="/scratch1/NCEPDEV/da/Russ.Treadon/CASES/gfs/prod"
./workflow/create_experiment.py --yaml ./ci/cases/pr/C48C48_ufs_hybatmDA.yaml
```

4. Execute `rocotorun -d prci.db -w prci.xml` from `EXPDIR`.   This launched 2021032312 gdasfcst, enkfgdasfcst_mem001, and enkfgdasfcst_mem002.
5. Once forecast jobs complete, set up crontab to cycle prci to `EDATE=2021032400`.
```
exp=prci
cd /scratch1/NCEPDEV/stmp2/Russ.Treadon/EXPDIR/$exp
/apps/rocoto/1.3.6/bin/rocotorun -v 10 -d ${exp}.db -w ${exp}.xml
```

prci successfully completed 2021032312 and now cycling through 2021032318.  This issue will be updated once the prci completes 2021032400.
