### ISSUE TITLE
Add mapping files from IMS snow cover grid to the atm/ocn cube sphere tiles

### ISSUE THREAD

**Issue by jiaruidong2017** [NOAA-EMC/global-workflow#2298]
### Target fix directory

NEW

### Type of change

- [ ] Update existing files
- [ ] Remove files
- [ ] Add new files to existing directory
- [X] Add new fix directory

### Any workflow changes needed?

Fix version only

### Pickup location

/scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GlobalWorkflow/para_gfs/glopara_dump/ims_index/

### Size

4042

**Comment by CoryMartin-NOAA** [comment]
I suggest we put them in `fix/gdas/ims` or something like that.

**Comment by jiaruidong2017** [comment]
@CoryMartin-NOAA do you think which is better: either `fix/gdas/obs/ims` or `fix/gdas/ims`?

**Comment by CoryMartin-NOAA** [comment]
good question, I like your suggestion of adding `obs`

**Comment by KateFriedman-NOAA** [comment]
@CoryMartin-NOAA @jiaruidong2017 We're talking about a new timestamped fix subfolder (everything under `fix/gdas/` has it's own versioning). Based on the comments above it looks like you want the following new fix subfolder for the new files: `../fix/gdas/obs/YYYYMMDD/ims` and we'll then need a new version variable in `versions/fix.ver` for this new subset (e.g. `gdas_obs_ver`). Is that correct and/or sound good? Are you anticipating additional subfolders at the same level as `ims`?

I'll make the `YYYYMMDD` timestamp the date I create the folder and pull the files in...if that works for you guys. Let me know and I'll pull the files in. Thanks!

**Comment by CoryMartin-NOAA** [comment]
Works for me, @KateFriedman-NOAA thanks! and yes I think we envision some other mapping files for other observation types (such as VIIRS land products) in the future (not in this immediate version)

**Comment by KateFriedman-NOAA** [comment]
@CoryMartin-NOAA Sounds good!

I have created the discussed new subfolder structure and copied the files into it. Please see here on Hera:
```
[role.glopara@hfe08 ims]$ pwd
/scratch1/NCEPDEV/global/glopara/fix/gdas/obs/20240213/ims
[role.glopara@hfe08 ims]$ ll
total 4133444
-rw-r--r-- 1 role.glopara global 548537160 Jan 26 17:04 IMS_4km_to_C1152.mx025.nc
-rw-r--r-- 1 role.glopara global 455639880 Feb  7 21:37 IMS_4km_to_C192.mx025.nc
-rw-r--r-- 1 role.glopara global 455639880 Feb  7 21:38 IMS_4km_to_C192.mx100.nc
-rw-r--r-- 1 role.glopara global 463602504 Feb 13 21:02 IMS_4km_to_C384.mx025.nc
-rw-r--r-- 1 role.glopara global 453151560 Jan 26 19:27 IMS_4km_to_C48.mx100.nc
-rw-r--r-- 1 role.glopara global 453151560 Jan 26 17:04 IMS_4km_to_C48.mx500.nc
-rw-r--r-- 1 role.glopara global 495453000 Jan 26 17:04 IMS_4km_to_C768.mx025.nc
-rw-r--r-- 1 role.glopara global 453649224 Jan 26 17:04 IMS_4km_to_C96.mx100.nc
-rw-r--r-- 1 role.glopara global 453649224 Feb  7 21:39 IMS_4km_to_C96.mx500.nc
```

Please confirm it looks good and we'll sync it to the other platform fix sets.

We now need to add `export gdas_obs_ver=20240213` to `versions/fix.ver`. Do you have a branch you're planning to send that update in? If not, we'll want to submit a separate PR to add it.

**Comment by CoryMartin-NOAA** [comment]
Is it okay if that is included in the PR that will include changes to workflow scripts to grab these files from that location? Or would you prefer separate PRs?

**Comment by KateFriedman-NOAA** [comment]
Absolutely! Including in such a PR would be perfect. Make sure to have that PR close this issue too. Thanks!

**Comment by jiaruidong2017** [comment]
Thanks @KateFriedman-NOAA for your efforts.

**Comment by KateFriedman-NOAA** [comment]
FYI, the new files have now been synced to both WCOSS2s and Jet. Orion/Hercules will be synced shortly.

**Comment by CoryMartin-NOAA** [comment]
Thanks Kate, I'm working on the PR I mentioned today.
