### ISSUE TITLE
Permissions issue for file causes failure in gdasanal 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#2301]
### What is wrong?

I got a failure in gdasanal (see: /scratch1/NCEPDEV/climate/Jessica.Meixner/cycling/develop/test02/COMROOT/testci01/logs/2021032418/gdasanal.log.0) because of: 

```
++ exglobal_atmos_analysis.sh[638]: tar xvf radstat.gdas
++ exglobal_atmos_analysis.sh[638]: grep _ges
tar: radstat.gdas: Cannot open: Permission denied
```

and  ls -l /scratch1/NCEPDEV/global/glopara/data/ICSDIR/C48mx500/gdas.20210324/12/analysis/atmos/gdas.t12z.radstat : 
`-rw-r----- 1 role.glopara da 2360483840 Nov 17 18:37 /scratch1/NCEPDEV/global/glopara/data/ICSDIR/C48mx500/gdas.20210324/12/analysis/atmos/gdas.t12z.radstat
`
I do not have da group access so therefore this seems to fail. 

### What should have happened?

I should be able to run gdasanal despite not having da group access. 

### What machines are impacted?

Hera

### Steps to reproduce

Don't have da group access, try running the new ci test in C48mx500_3DVarAOWCDA.yaml test 

### Additional information

non

### Do you have a proposed solution?

Add less restrictive access to files.

**Comment by WalterKolczynski-NOAA** [comment]
This should be fixed now. I made everything global and added read-all, except the stuff that should be rstprod.

**Comment by JessicaMeixner-NOAA** [comment]
My job now ran to completion.  Thanks for quickly addressing this issue @WalterKolczynski-NOAA !
