### ISSUE TITLE
Link new ICs to glopara areas for HR3

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#2314]
### What new functionality do you need?

HR3 ICs linked in official spaces. 

The ICs are staged on hera, orion/hercules and WCOSS2 in the role.ufscpara, my space and @jiandewang respectively. Note that for WCOSS2, we sometimes cannot stage all ICs due to current space issues, but if we link to the full folders from Jiande hopefully this will not be too impactful.  These ICs are on HPSS for long term storage and there are no plans to remove these from disk on hera anytime soon. We have staged the HR3 ICs in the "new" format so we should be able to point to entire directories. 

### What are the requirements for the new functionality?

Be able to run HR3 ICs without having to change BASE_CPLIC manually. 

### Acceptance Criteria

IC files are accessible from official BASE_CPLIC area. 

### Suggest a solution (optional)

Hera folders that need to be linked to: /scratch1/NCEPDEV/global/glopara/data/ICSDIR/prototype_ICs

/scratch1/NCEPDEV/climate/role.ufscpara/IC/HR3C1152
/scratch1/NCEPDEV/climate/role.ufscpara/IC/HR3C768
/scratch1/NCEPDEV/climate/role.ufscpara/IC/HR3marine

Orion folders that need to be linked to: /work/noaa/global/glopara/data/ICSDIR/prototype_ICs
/work/noaa/marine/jmeixner/IC/HR3C1152
/work/noaa/marine/jmeixner/IC/HR3C768
/work/noaa/marine/jmeixner/IC/HR3marine

WCOSS2 folders that need to be linked to: /lfs/h2/emc/global/noscrub/emc.global/data/ICSDIR/prototype_ICs
/lfs/h2/emc/couple/noscrub/Jiande.Wang/IC/HR3C1152
/lfs/h2/emc/couple/noscrub/Jiande.Wang/IC/HR3C768
/lfs/h2/emc/couple/noscrub/Jiande.Wang/IC/HR3marine

* note it's recommended on WCOSS2 to link to these folders and not individual files/dates as space issues might require not all ICs are staged at all times.  ICs for all dates will always be available on hera or HPSS.

**Comment by WalterKolczynski-NOAA** [comment]
All links have been created.
