### ISSUE TITLE
Update UGWD files for new grid files and new orography statistics method

### ISSUE THREAD

**Issue by barlage** [NOAA-EMC/global-workflow#2316]
### Target fix directory

ugwd

### Type of change

- [X] Update existing files
- [ ] Remove files
- [ ] Add new files to existing directory
- [x] Add new fix directory

### Any workflow changes needed?

Fix version only

### Related issues

The ugwd files are updated in two ways:
- the new grid/orog files generated by #1981 and https://github.com/ufs-community/UFS_UTILS/pull/830
- the new orography statistics method from https://github.com/ufs-community/UFS_UTILS/pull/718

Using the same directory timestamp (pickup location below) as #1981 

### Pickup location

/scratch2/NCEPDEV/land/data/fix/ugwd/20231027

### Size

0

**Comment by KateFriedman-NOAA** [comment]
@barlage I have copied the provided files to a new `20231027` timestamp subfolder of `fix/ugwd`. Please see here on Hera and confirm this is in line with your request: `/scratch1/NCEPDEV/global/glopara/fix/ugwd/20231027`

**Comment by JessicaMeixner-NOAA** [comment]
I've added this to my PR: https://github.com/NOAA-EMC/global-workflow/pull/2230 

I did a quick diff between @barlage directory and the glopara, and while i'm not the expert, I at least can independently confirm there are no differences between /scratch1/NCEPDEV/global/glopara/fix/ugwd/20231027 and /scratch2/NCEPDEV/land/data/fix/ugwd/20231027

**Comment by JessicaMeixner-NOAA** [comment]
> @barlage I have copied the provided files to a new `20231027` timestamp subfolder of `fix/ugwd`. Please see here on Hera and confirm this is in line with your request: `/scratch1/NCEPDEV/global/glopara/fix/ugwd/20231027`

@KateFriedman-NOAA  I see that @barlage  is in meetings all day.  I'm unsure how much effort it is to sync across platforms.  However, we need to get new fix files to run the last set of high resolution tests for https://github.com/NOAA-EMC/global-workflow/pull/2230 to then start the last set of CI tests for that.  If it's not too much work can we just sync these to other machines?  If it's a lot of work, I am 100% in favor of waiting for the green light from Mike, just thought I'd ask.

**Comment by WalterKolczynski-NOAA** [comment]
I'm synchronizing to Orion now so we can get tests rolling on the assumption it is correct.

**Comment by JessicaMeixner-NOAA** [comment]
> I'm synchronizing to Orion now so we can get tests rolling on the assumption it is correct.

Thanks @WalterKolczynski-NOAA !

**Comment by KateFriedman-NOAA** [comment]
I'm syncing to the WCOSS2s right now (Dogwood first).

**Comment by JessicaMeixner-NOAA** [comment]
Thank you @KateFriedman-NOAA !

**Comment by KateFriedman-NOAA** [comment]
The new `20231027` UGWD fix files are now available on both WCOSS2s.

**Comment by barlage** [comment]
Thanks for starting without me, haven't had much time to check email today. I did some quick checks and everything looks good to me. Thanks @JessicaMeixner-NOAA for doing some independent checks.

**Comment by KateFriedman-NOAA** [comment]
Is this issue now complete or will an upcoming PR close it? Thanks!

**Comment by JessicaMeixner-NOAA** [comment]
This was updated with https://github.com/NOAA-EMC/global-workflow/pull/2230 which was merged last night.  I think this issue can be closed. (I forgot to add this issue to that PR so it did not automatically close).

**Comment by KateFriedman-NOAA** [comment]
Great, thanks for confirming! Closing as complete.
