### ISSUE TITLE
48-day forecast capability

### ISSUE THREAD

**Issue by NeilBarton-NOAA** [NOAA-EMC/global-workflow#2325]
**Description** 

Filenames currently with forecast length appended will run out of digits with the 48 forecast hours used for GEFSv13. Suggestion is to change filename based on ISO timestamp YYYY-MM-DDTHH:MM:SSZ with initialization and valid time instead of forecast hour in HHH.

**Comment by WalterKolczynski-NOAA** [comment]
In the short-term, it looks like we will just be expanding the forecast hour field.

**Comment by WalterKolczynski-NOAA** [comment]
The capability for 48-day forecast should be there with segments. The forecast hours will still be padded only to three digits though. We will handle the padding as part of #1522
