### ISSUE TITLE
create a tag for hr3 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#2331]
### What new functionality do you need?

Create a tag  prototype/hr3 from develop hash      https://github.com/NOAA-EMC/global-workflow/commit/6f9afff073dd589096f992a3448fb7f0e62c9804

### What are the requirements for the new functionality?

Tag for indicating HR3

### Acceptance Criteria

A tag  prototype/hr3

**Comment by JessicaMeixner-NOAA** [comment]
Request for UFS model tag here issue is here: https://github.com/ufs-community/ufs-weather-model/issues/2144

**Comment by WalterKolczynski-NOAA** [comment]
Tag prototype/hr3 created: https://github.com/NOAA-EMC/global-workflow/releases/tag/prototype%2Fhr3
