### ISSUE TITLE
Archive Jobs Fail Due to Missing RadMon File "low_counts.yyyymmddhh"

### ISSUE THREAD

**Issue by azadeh-gh** [NOAA-EMC/global-workflow#2340]
### What is wrong?

The archive jobs are failing due to the absence of the RadMon file "low_counts.yyyymmddhh". This file is expected to log instances where a specific sensor or channel exhibits lower than anticipated counts. Consequently, there are periods where this file is not generated. This absence causes the archive step to fail, disrupting the workflow.

### What should have happened?

The archive jobs should be able to handle the absence of the "low_counts.yyyymmddhh" file without causing the entire workflow to fail.

### What machines are impacted?

Hera

### Steps to reproduce

1. Trigger the global workflow that includes RadMon in the archive step.
2. During periods when the RadMon file "low_counts.yyyymmddhh" is not generated, observe the archive job failures due to the absence of this file.

### Additional information

- The issue arises due to the archive step attempting to archive the "low_counts.yyyymmddhh" file even when it's not consistently present.

- The script `hpssarch_gen.sh` in the global workflow is responsible for handling the archiving process and needed modification to address this issue.

### Do you have a proposed solution?

Yes, the proposed solution involves modifying the `hpssarch_gen.sh` script to include a check for the existence and non-empty status of the "low_counts.yyyymmddhh" file before attempting to archive it. This ensures that the archive job proceeds only when the file is present and contains data, preventing failures due to its absence.

**Comment by WalterKolczynski-NOAA** [comment]
@DavidHuber-NOAA This is related to the larger issue also encompassing #2242. I think we should make another issue encompassing the full scope of the work and then close these individual ones.

**Comment by WalterKolczynski-NOAA** [comment]
Subsumed by #2345
