### ISSUE TITLE
link_workflow does not link ufs_utils fix files

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/global-workflow#2352]
### What is wrong?

I thought at one point, the link_workflow script would run the ufs_utils fix file linking script, but that seems to no longer be the case. Is this the desired behavior?

### What should have happened?

ufs_utils should be able to generate ICs

### What machines are impacted?

All or N/A

### Steps to reproduce

Clone workflow, build workflow, link workflow, try using ufs_utils to generate ICs

### Additional information

Documentation suggests a user has to do no linking when building as part of the workflow

**Comment by CoryMartin-NOAA** [comment]
Apparently this was by design in #2172 ...

**Comment by aerorahul** [comment]
@CoryMartin-NOAA 
At some point we will resurrect the capability of generating ICs as part of the workflow, but for now, its out of scope due to priorities and resources.

**Comment by CatherineThomas-NOAA** [comment]
@aerorahul: Would it be possible to at least have the RTD updated to reflect this?  Either say you can't use what's built in the workflow or specify that you need to run the linking separately?  We have many more DA people trying to run with develop now and this has already been an issue.

**Comment by aerorahul** [comment]
https://global-workflow.readthedocs.io/en/latest/init.html#cycled-mode
![Screenshot 2024-03-13 at 11 35 44 AM](https://github.com/NOAA-EMC/global-workflow/assets/11394126/ce5c5482-6778-4fbd-85d8-2c366b8658e5)

In [Manual Generation](https://global-workflow.readthedocs.io/en/latest/init.html#manual-generation) there are instructions on how to clone and build ufs-utils separately.
We can update this to point the users to ufs-utils documentation on generating ICs

For [forecast-only mode](https://global-workflow.readthedocs.io/en/latest/init.html#forecast-only-mode-atm-only), the instructions state that the ICs are pre-generated offline, 
![Screenshot 2024-03-13 at 11 37 27 AM](https://github.com/NOAA-EMC/global-workflow/assets/11394126/b3a6eb92-459f-4fb6-8c47-248489361057)

**Comment by JessicaMeixner-NOAA** [comment]
In the manual generation section it says: 

"Users can use the copy of UFS_UTILS that is already cloned and built within their global-workflow clone or clone/build it separately:" 

I think this is the text @CatherineThomas-NOAA  is referring to that would be helpful to have updated to specify that right now, you cannot use the build from the global-workflow as files are not linked.

**Comment by aerorahul** [comment]
#2397 will reflect the changes
