### ISSUE TITLE
Update gsd_prep_chem tag to gefs_v12.3.9 in release/gefs_v12

### ISSUE THREAD

**Issue by EricSinsky-NOAA** [NOAA-EMC/global-workflow#2361]
### What is wrong?

The gsd_prep_chem tag is currently gefs_v12.3.8. 

### What should have happened?

The gsd_prep_chem tag should be changed to gefs_v12.3.9. 

### What machines are impacted?

WCOSS2

### Steps to reproduce

When `sorc/checkout.sh` is executed, an outdated gsd_prep_chem tag is checked out. 

### Additional information

The gsd_prep_chem in release/gefs_v12 needs to be changed from gefs_v12.3.8 to gefs_v12.3.9 in `sorc/checkout.sh`. This version change addresses the upcoming GBBEPx upgrade. More details on this issue can be found in GSL-prep-chem [issue 12](https://github.com/NOAA-GSL/GSL-prep-chem/issues/12). 

### Do you have a proposed solution?

An upcoming PR that updates the version to gefs_v12.3.9 in `sorc/checkout.sh` will resolve this issue.

**Comment by WalterKolczynski-NOAA** [comment]
Resolved by #2362
