### ISSUE TITLE
HR3 and HR4: Add log files to netcdfb tarball when saved to HPSS

### ISSUE THREAD

**Issue by BoCui-NOAA** [NOAA-EMC/global-workflow#2368]
### What is wrong?

When creating the netnetcdfb tarball file to HPSS , please include all the gfs.*.atm.logf*.txt files saved at the directory gfs.PDY/CYC/model_data/atmos/history. The burf sounding job check these txt files to continue its running. The total size of the txt files is about 600K.

### What should have happened?

netcdfb tarball should contains all logf files in addition to atmf and sfcf files.

### What machines are impacted?

WCOSS2

### Steps to reproduce

N/A

### Additional information

N/A

### Do you have a proposed solution?

Please consider to modify the archive script and add the logf files. @JessicaMeixner-NOAA @jiand

**Comment by aerorahul** [comment]
Sorry, why do these files need to be in the HPSS tarball?
The bufr sounding job checks for these files when the application is running.  Once the application is done running, and bufr sounding is finished, is there a case when bufr sounding job is being tried to be executed outside of the workflow environment?

**Comment by BoCui-NOAA** [comment]
@aerorahul  The current HR3 runs switch off the bufr sounding running.  I am testing the bufr sounding package only and need the atmf, sfcf and log files.

**Comment by WalterKolczynski-NOAA** [comment]
These are dummy files and can be regenerated easily using `touch`:
```
for hist in gfs*.atmf*.nc; do
  logname="${hist/atmf/atm.logf}"
  logname="${logname/.nc/.txt}"
  touch ${logname}
done
```

**Comment by BoCui-NOAA** [comment]
@WalterKolczynski-NOAA  This is a good solution. I use your script and generate the logf files. The bufr sounding job can continue and complete successfully.  I will close this ticket. Thanks!
