### ISSUE TITLE
New UFS_UTILS orography and landmask data

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/global-workflow#2378]
### Target fix directory

raw

### Type of change

- [ ] Update existing files
- [ ] Remove files
- [X] Add new files to existing directory
- [ ] Add new fix directory

### Any workflow changes needed?

No change needed

### Related issues

https://github.com/ufs-community/UFS_UTILS/pull/900

### Pickup location

/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS/fix/orog_raw.test

### Size

3.3 Gb

**Comment by GeorgeGayno-NOAA** [comment]
There are three new files:

- landcover.umd.30s.nc
- topography.gmted2010.30s.nc
- topography.antarctica.ramp.30s.nc

The above files are NetCDF versions of the following existing files in the 'raw' directory:

- landcover30.fixed
- gmted2010.30sec.int
- thirty.second.antarctic.new.bin

The old versions will need to be retained so older versions of the UFS_UTILS orography code will still work.

**Comment by KateFriedman-NOAA** [comment]
@GeorgeGayno-NOAA I have copied the three provided files into the `fix/raw` folder on Hera:
```
[role.glopara@hfe02 orog]$ pwd
/scratch1/NCEPDEV/global/glopara/fix/raw/orog
[role.glopara@hfe02 orog]$ ll landcover.umd.30s.nc 
-rw-r--r-- 1 role.glopara global 934169721 Mar  6 19:02 landcover.umd.30s.nc
[role.glopara@hfe02 orog]$ ll topography.*
-rw-r--r-- 1 role.glopara global  623028926 Mar  4 20:44 topography.antarctica.ramp.30s.nc
-rw-r--r-- 1 role.glopara global 1867289572 Mar  4 20:45 topography.gmted2010.30s.nc
```

I am syncing them to the other platforms now. @WalterKolczynski-NOAA please sync the Orion fix set, thanks!

**Comment by WalterKolczynski-NOAA** [comment]
Orion synchronized

**Comment by WalterKolczynski-NOAA** [comment]
We should establish a sunset date for the old files so they can be removed.

**Comment by KateFriedman-NOAA** [comment]
Files have been added to the fix sets on Hera, Orion, Jet, and both WCOSS2s.

**Comment by GeorgeGayno-NOAA** [comment]
Thanks for your quick response.

**Comment by GeorgeGayno-NOAA** [comment]
> We should establish a sunset date for the old files so they can be removed.

I agree. Six months? 12 months?

**Comment by KateFriedman-NOAA** [comment]
If you're good with six months I think we'd want to do it sooner rather than later. Let us know if that works, thanks!

**Comment by GeorgeGayno-NOAA** [comment]
> If you're good with six months I think we'd want to do it sooner rather than later. Let us know if that works, thanks!

Ok. Let's do six months.

**Comment by KateFriedman-NOAA** [comment]
@GeorgeGayno-NOAA Sounds good! I'll make a reminder for 6 months from now (early September) to retire the old files. @WalterKolczynski-NOAA and I will check in with you beforehand to make sure we're good-to-go.

Closing this issue as complete now.
