### ISSUE TITLE
Ensemble archive step is not archiving the last set of members

### ISSUE THREAD

**Issue by CatherineThomas-NOAA** [NOAA-EMC/global-workflow#2390]
### What is wrong?

The ensemble archive step `earc` is split into groups based on the variable `NMEM_EARCGRP`, which is currently set to 10.  For 80 members, this should result in 8 tasks + 1 task for the ensemble stats (ensmean/spread).  

The script gfs_tasks.py uses the range function to define the groups:
```
n_groups = -(self.nmem // -self._configs['earc']['NMEM_EARCGRP'])
groups = ' '.join([f'{grp:02d}' for grp in range(0, n_groups]])
```
The range function is not inclusive so it creates groups 0 to 7.  Task 0 handles the stats/logs, task 1 handles members 1-10, task 2 members 11-20, etc.  This results in members 71-80 not being archived.

### What should have happened?

All members should have been archived.

### What machines are impacted?

All or N/A

### Steps to reproduce

Run setup_xml.py and check the xml file for what earc groups are listed.

### Additional information

The incorrect archiving was reported by @XuanliLi-NOAA 

### Do you have a proposed solution?

Adding `+1` to n_groups produced the correct number of groups, but I'm not sure if this is the preferred way to handle such things in python.
```
groups = ' '.join([f'{grp:02d}' for grp in range(0, n_groups+1)])
```

**Comment by DavidHuber-NOAA** [comment]
There is an additional bug in `hpss_archgen.sh` that attempts to archive too many members if the number of members is not a multiple of 10.  Reopening.
