### ISSUE TITLE
Regular RTD documentation update

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#2395]
### What new functionality do you need?

Updated RTD documentation that now includes recent additions to staged IC sets and new platforms (AWS). Also make some additional general updates.

### What are the requirements for the new functionality?

Up-to-date documentation.

### Acceptance Criteria

Updated documentation includes recent changes.

**Comment by HenryRWinterbottom** [comment]
Kate, you may have already been planning to do so, but it might be worth adding some verbage re: how to use the AWS CLI commands. Further, I could add the AWS CLI to the GW stack. 

Obviously, your call. Just something crossing my mind while I drink  my (first) cup of coffee...

**Comment by KateFriedman-NOAA** [comment]
@HenryWinterbottom-NOAA Good idea, I'll look at including that for this issue. Thanks!

**Comment by WalterKolczynski-NOAA** [comment]
Other doc updates on my to-do pile:
- Specify the minimum git version (v2)
- Note that sourcing `gw_setup.sh` requires using bash
~~- Update IC creation to use stand-alone UFS_Utils~~

**Comment by HenryRWinterbottom** [comment]
@aerorahul @WalterKolczynski-NOAA Is there a preferred place to install the AWS CLI for the GW supported platforms? @KateFriedman-NOAA had been using a stack that I built for UFS-RNR.

**Comment by WalterKolczynski-NOAA** [comment]
We already host all the needed files on supported platforms. AFAIK the Amazon CLI instructions are for people trying to stand up workflow on other machines.

**Comment by KateFriedman-NOAA** [comment]
Perhaps we can install AWS CLI under our global group space on each supported platform? The installs would be for our groups needs (e.g. managing staged data on AWS).

**Comment by HenryRWinterbottom** [comment]
It's your call. I can handle Orion, Hercules, and Hera if we proceed that way. I would need others to handle the others.

**Comment by KateFriedman-NOAA** [comment]
Will also add link to new UFS_UTILS RTD documentation on using gdas_init once https://github.com/ufs-community/UFS_UTILS/pull/920 goes in.

Current UFS_UTILS RTD: https://noaa-emcufs-utils.readthedocs.io/en/latest/
