### ISSUE TITLE
# of nodes for default configurations produces error

### ISSUE THREAD

**Issue by jkhender** [NOAA-EMC/global-workflow#2406]
### What is wrong?

I'm testing Henry's branch for Rocky8, https://github.com/HenryWinterbottom-NOAA/global-workflow/tree/feature/gwdev_issue_2329. When I try to run a C384 or C768 gfsfcst, I get the following error 

2673: FATAL from PE  2673: mpp_domains_define.inc: At least one pe in pelist is not used by any tile in the mosaic

I have not changed the default configurations. For C384 (8x8, 2th, 4wg/10wt), the XML file uses 32 nodes.  For C768 (12x16, 4th, 4wg/20wt), the XML file uses 164 nodes.  On the CentOS7 OS, I can run the default C768 configuration without any errors. 

logfile:  /scratch1/BMC/gsd-fv3-dev/Judy.K.Henderson/test/test_rocky8/FV3GFSrun/test384/logs/2024031100/gfsfcst.log

### What should have happened?

gfsfcst task will run with specified number of nodes

### What machines are impacted?

Hera

### Steps to reproduce

1. Create C384 experiment
2. Run gfsfcst task

### Additional information

I'm using Henry's workflow from 13Mar24, 33a3553

**Comment by aerorahul** [comment]
This was resolved with #2421
