### ISSUE TITLE
diag_table issue due to atparse.sh in parsing_namelists_FV3.sh 

### ISSUE THREAD

**Issue by zhanglikate** [NOAA-EMC/global-workflow#2407]
### What is wrong?

It seems there's a mistake in the atparse script. The issue lies in how the while loop is structured within the atparse function. Specifically, the loop termination condition [[ "$__after" == "$__text" ]] may not always work as expected, leading to premature termination of the loop and missing the last line. So the last line in the file of diag_table_aod is always missing in the finale diag_table, which results in the missing of sea salt AOD in the diagnostic output. 

### What should have happened?

In the atparse script, I've changed the while loop condition to while IFS= read -r __text || [ -n "$__text" ], which ensures that the loop continues until the input is fully consumed, even if the last line doesn't end with a newline character. It works well to solve the issue.

### What machines are impacted?

All or N/A

### Steps to reproduce

In the run directory, you can see that the last line of diag_table is always missing compared to the diag_table_template 

### Additional information

"gfs_phys",  "DU_AOD_550",      "du_aod550",     "fv3_history2d",  "all",  .false.,  "none",  2
"gfs_phys",  "SU_AOD_550",      "su_aod550",     "fv3_history2d",  "all",  .false.,  "none",  2
"gfs_phys",  "BC_AOD_550",      "bc_aod550",     "fv3_history2d",  "all",  .false.,  "none",  2
"gfs_phys",  "OC_AOD_550",      "oc_aod550",     "fv3_history2d",  "all",  .false.,  "none",  2
"gfs_phys",  "SS_AOD_550",      "ss_aod550",     "fv3_history2d",  "all",  .false.,  "none",  2

The last line is always missing in the diag_table

**Comment by aerorahul** [comment]
@zhanglikate 
Would you be willing to add an extra blank like to [`diag_table_aod`](https://github.com/NOAA-EMC/global-workflow/blob/develop/parm/ufs/fv3/diag_table_aod) and give it a try again?
Something like adding 
```
###
```
might do the trick.


Also, the `atparse.sh` script comes from the ufs-weather-model, so this bug report for `atparse.sh` should be opened in the ufs-weather-model.  

Meanwhile, if the above solution gets around the problem, we can commit that in the workflow.

**Comment by aerorahul** [comment]
@DusanJovic-NOAA FYI

**Comment by zhanglikate** [comment]
> @zhanglikate Would you be willing to add an extra blank like to [`diag_table_aod`](https://github.com/NOAA-EMC/global-workflow/blob/develop/parm/ufs/fv3/diag_table_aod) and give it a try again? Something like adding
> 
> ```
> ###
> ```
> 
> might do the trick.
> 
> Also, the `atparse.sh` script comes from the ufs-weather-model, so this bug report for `atparse.sh` should be opened in the ufs-weather-model.
> 
> Meanwhile, if the above solution gets around the problem, we can commit that in the workflow.

You meant add one more line after "gfs_phys", "SS_AOD_550", "ss_aod550", "fv3_history2d", "all", .false., "none", 2 , without modifying the atparse.sh?

**Comment by aerorahul** [comment]
> > @zhanglikate Would you be willing to add an extra blank like to [`diag_table_aod`](https://github.com/NOAA-EMC/global-workflow/blob/develop/parm/ufs/fv3/diag_table_aod) and give it a try again? Something like adding
> > ```
> > ###
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > might do the trick.
> > Also, the `atparse.sh` script comes from the ufs-weather-model, so this bug report for `atparse.sh` should be opened in the ufs-weather-model.
> > Meanwhile, if the above solution gets around the problem, we can commit that in the workflow.
> 
> You meant add one more line after "gfs_phys", "SS_AOD_550", "ss_aod550", "fv3_history2d", "all", .false., "none", 2 , without modifying the atparse.sh?

Yes.

**Comment by zhanglikate** [comment]
But if there are other traces following the ss_aod550, it will case issue again. I would recommend to update the atparse.sh to permanently fix it. Thanks.

Kate

**Comment by aerorahul** [comment]
I agree a permanent fix is required.
Please open an issue in the ufs-weather-model.
