### ISSUE TITLE
GFS Off-line post failed on WCOSS2

### ISSUE THREAD

**Issue by WenMeng-NOAA** [NOAA-EMC/global-workflow#2408]
### What is wrong?

The GFS C768 case failed at off-line post on WCOSS2.

### What should have happened?

The job 'JGLOBAL_ATMOS_UPP' should have capacity to process high resolution model output with off-line post.

### What machines are impacted?

WCOSS2

### Steps to reproduce

Here are errors from my runtime log:
```
^[[38;5;196m2024-03-18 17:12:57,639 - ERROR    - upp         : FATAL ERROR: Error occurred during execution of mpiexec -l -n 120 -ppn 120 --cpu-bind depth --depth 1 /u/wen.meng/ptmp/gw_test/RUNDIR/upp.231494/upp.x^[[0m
Traceback (most recent call last):
  File "/u/wen.meng/noscrub/ncep_post/gw_v17/global-workflow/ush/python/pygfs/task/upp.py", line 239, in _call_executable
    exec_cmd()
  File "/u/wen.meng/noscrub/ncep_post/gw_v17/global-workflow/ush/python/wxflow/executable.py", line 230, in __call__
    raise ProcessError(f"Command exited with status {proc.returncode}:", long_msg)
wxflow.executable.ProcessError: Command exited with status 137:
'mpiexec' '-l' '-n' '120' '-ppn' '120' '--cpu-bind' 'depth' '--depth' '1' '/u/wen.meng/ptmp/gw_test/RUNDIR/upp.231494/upp.x'
^[[38;5;196m2024-03-18 17:12:57,639 - ERROR    - upp         : FATAL ERROR: Error occurred during execution of mpiexec -l -n 120 -ppn 120 --cpu-bind depth --depth 1 /u/wen.meng/ptmp/gw_test/RUNDIR/upp.231494/upp.x^[
```

### Additional information

The log file 'gfs_upp.o121904081-failture' can be found at /u/wen.meng/noscrub/ncep_post/gw_v17/driver on Cactus.

### Do you have a proposed solution?

Yes. It appears all tasks allocated in one node cause the failure on WCOSS2 as:
Executing mpiexec -l -n 120 -ppn 120 --cpu-bind depth --depth 1 /u/wen.meng/ptmp/gw_test/RUNDIR/upp.231494/upp.x

My proposed solution would be in global-workflow/parm/config/gfs/config.resources:
change
   export npe_node_upp=${npe_upp}
into 
   export npe_node_upp=40

In that way, 120 tasks will be allocated in 3 or more nodes.

**Comment by aerorahul** [comment]
@WenMeng-NOAA 
I think the `upp.x` is running out of memory.
The job is requesting `48GB` of memory as seen on [this](https://github.com/NOAA-EMC/global-workflow/blob/e9700d84b521907ee23e1584712f80e25e60f08e/parm/config/gfs/config.resources#L697)
For `120` tasks, we should request at least `480GB` of memory on `WCOSS2`.

First please test with `480GB` on WCOSS2.
On Hera/Orion, we will need to work it a little differently since they do not have that much memory per node.

**Comment by WenMeng-NOAA** [comment]
@aerorahul From my tests, 480GB memory works for C768 case but not C1152 case.

**Comment by aerorahul** [comment]
Great.  What about 512GB?

**Comment by aerorahul** [comment]
Also, what is the total memory used at C1152?

**Comment by WenMeng-NOAA** [comment]
> Also, what is the total memory used at C1152?

@aerorahul Over 504 GB memory.

**Comment by aerorahul** [comment]
> > Also, what is the total memory used at C1152?
> 
> 
> 
> @aerorahul Over 504 GB memory.

Ok. How much over?

**Comment by WenMeng-NOAA** [comment]
@aerorahul I have to give up the job with 512 GB memory setting after waiting in the job queue a couple hours. You may check the runtime log 'gfs_post.o121999041' at /u/wen.meng/noscrub/ncep_post/gfsv17/UPP on Cactus for memory usage related to the C1152 case, which configured with 3 nodes, 40 tasks/node and 480 GB memory.

**Comment by WenMeng-NOAA** [comment]
@aerorahul I tested the case C768 with setting 'memory_upp="480GB" ' in config.resources. The off-line post successfully generated GFS master, flux, goes files.

**Comment by aerorahul** [comment]
> @aerorahul I tested the case C768 with setting 'memory_upp="480GB" ' in config.resources. The off-line post successfully generated GFS master, flux, goes files.

I will work this update through one of our existing PRs.
