### ISSUE TITLE
incorrect GDASApp paths

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/global-workflow#2434]
### What is wrong?

GDASApp issue [#991](https://github.com/NOAA-EMC/GDASApp/issues/991) documents incorrect paths in GDASApp g-w jobs.  The incorrect paths fall into two categories:
1. change in GDASApp directory structure not reflected in g-w job.  For example, `jobs/rocoto/prepsnowobs.sh` contains `${HOMEgfs}/sorc/gdas.cd/iodaconv/src`.   The correct path to `iodaconv` is now `gdas.cd/sorc/iodaconv`.
2. use different python versions on different machines.  For example, `jobs/rocoto/prepsnowobs.sh` references `python3.7` but the Hera Rocky 8 build uses `python3.10`.

### What should have happened?

g-w jobs should use the correct path to GDASApp components and python.

### What machines are impacted?

Hera, Orion, Hercules

### Steps to reproduce

1. Clone g-w `develop`. 
2. Compare GDASApp directory structure with assumed paths in `jobs/rocoto`
3. Build GDASApp
4. Compare GDASApp path to python in `build/lib` with assumed path in `jobs/rocoto`

### Additional information

Rahul identified this problem.

### Do you have a proposed solution?

Need to go through g-w `develop` and identify all the places where GDASApp paths are referenced.  Ensure paths are correct and GDASApp jobs run on Hera, Orion, and Hercules.   These three machine are, at present, the only machines on which GDASApp can be built and run.  

WCOSS2 Acorn has a build capability but this is a test system.  GDASApp can not yet be built on Cactus or Dogwood due to required libraries not being available.

**Comment by RussTreadon-NOAA** [comment]
Confirm that `gdasprepatmiodaobs` fails on Hera Rocky 8 due to
```
PYIODALIB="${HOMEgfs}/sorc/gdas.cd/build/lib/python3.7"
```
in `jobs/rocoto/prepatmiodaobs.sh`

Replacing `python3.7` with `python3.10` allows `gdasprepatmiodaobs` to successfully run to completion.

Not sure how best to generalized the `3.7` part of the path.  Any suggestions @aerorahul , @CoryMartin-NOAA , @guillaumevernieres ?

**Comment by RussTreadon-NOAA** [comment]
The following hack to `jobs/rocoto/prepatmiodaobs.sh` allows `gdasprepatmiodaobs` to run to completion on Hera Rocky 8
```
@@ -14,7 +14,8 @@ export jobid="${job}.$$"
 ###############################################################
 # setup python path for workflow and ioda utilities
 wxflowPATH="${HOMEgfs}/ush/python:${HOMEgfs}/ush/python/wxflow/src"
-PYIODALIB="${HOMEgfs}/sorc/gdas.cd/build/lib/python3.7"
+pythonver=$(echo $(basename $(echo "${HOMEgfs}/sorc/gdas.cd/build/lib/python*")))
+PYIODALIB="${HOMEgfs}/sorc/gdas.cd/build/lib/${pythonver}"
 PYTHONPATH="${PYIODALIB}:${wxflowPATH}:${PYTHONPATH}"
 export PYTHONPATH
```
I do not advocate this as _the_ fix, but it's functional.  What's the preferred solution?

**Comment by RussTreadon-NOAA** [comment]
FYI, the gdasatmanl `init`, `run`, and `final` jobs ran OK on Hera Rocky 8 after executing `gdasprepatmiodaobs` with the above change to `prepatmiodaobs.sh`.

**Comment by WalterKolczynski-NOAA** [comment]
> Confirm that `gdasprepatmiodaobs` fails on Hera Rocky 8 due to
> 
> ```
> PYIODALIB="${HOMEgfs}/sorc/gdas.cd/build/lib/python3.7"
> ```
> 
> in `jobs/rocoto/prepatmiodaobs.sh`
> 
> Replacing `python3.7` with `python3.10` allows `gdasprepatmiodaobs` to successfully run to completion.
> 
> Not sure how best to generalized the `3.7` part of the path. Any suggestions @aerorahul , @CoryMartin-NOAA , @guillaumevernieres ?

I have longer-term questions about exactly what is being created in that directory rather than loading a module, but short-term the python version should be extracted from the environment:
```
py_ver=$(regex="Python ([0-9]+\.[0-9]+)"; if [[ $(python --version) =~ ${regex} ]]; then echo "${BASH_REMATCH[1]}"; fi)
```

**Comment by RussTreadon-NOAA** [comment]
Tagging @emilyhcliu to provide a more detailed response to your question @WalterKolczynski-NOAA .  

My understanding as a high-level user is that `pyiodaconv` contains the bufr engine used by python scripts executed by prepatmiodaobs to convert GDA bufr dump files to JEDI IODA format.

I replace my hack with your suggestion.  
```
@@ -14,7 +14,8 @@ export jobid="${job}.$$"
 ###############################################################
 # setup python path for workflow and ioda utilities
 wxflowPATH="${HOMEgfs}/ush/python:${HOMEgfs}/ush/python/wxflow/src"
-PYIODALIB="${HOMEgfs}/sorc/gdas.cd/build/lib/python3.7"
+py_ver=$(regex="[0-9]+\.[0-9]+"; if [[ $(python --version) =~ ${regex} ]]; then echo "${BASH_REMATCH[0]}"; fi)
+PYIODALIB="${HOMEgfs}/sorc/gdas.cd/build/lib/python${py_ver}"
 PYTHONPATH="${PYIODALIB}:${wxflowPATH}:${PYTHONPATH}"
 export PYTHONPATH
```

This works!  `gdasprepatmiodaobs` successfully ran to completion.

**Comment by RussTreadon-NOAA** [comment]
Create [`RussTreadon-NOAA:feature/gdasapp_paths`](https://github.com/RussTreadon-NOAA/global-workflow/tree/feature/gdasapp_paths) in which to address problems identified by this issue.

**Comment by CoryMartin-NOAA** [comment]
@WalterKolczynski-NOAA it's using pybind11 to interface with C++ code in python that is compiled as part of JEDI/IODA. So while we may be able to install it as a library, as it stands now, it gets compiled when you compile the rest of `gdas.cd`

**Comment by emilyhcliu** [comment]
@WalterKolczynski-NOAA @RussTreadon-NOAA @CoryMartin-NOAA 
Sorry about the late reply.  
I totally agree that it is not good to have a hard-coded Python version number in the code.  It should be controlled by the workflow.  

Thanks for fixing this!
