### ISSUE TITLE
Reenable minimization monitor on Hera

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#2439]
### What new functionality do you need?

The Rocky 8 PR (#2421) disabled minmon on Hera as needed Perl libraries are missing on Rocky 8. Once the appropriate perl modules are in place, it should be reenabled.

### What are the requirements for the new functionality?

MinMon works on Hera.

### Acceptance Criteria

- [ ] Update workflow Perl version to one with the necessary libraries
- [ ] Remove section from `config.base` that turns off minmon on Hera

**Comment by RussTreadon-NOAA** [comment]
@WalterKolczynski-NOAA , what exactly is the problem with MinMon on Hera Rocky 8 nodes?

Is @EdwardSafford-NOAA aware of this?

**Comment by EdwardSafford-NOAA** [comment]
I hadn't heard about this but if I were to guess a cause it would be a missing perl lib on the Rocky 8 nodes.

**Comment by RussTreadon-NOAA** [comment]
Thank you @EdwardSafford-NOAA for your quick reply.  @WalterKolczynski-NOAA , will the g-w team resolve this issue?

**Comment by RussTreadon-NOAA** [comment]
I set `HOMEgfs` to a point at a local clone of g-w `develop` at d6be3b5c and executed `ush/load_fv3gfs_modules.sh`.  The base system `perl` is available: `/usr/bin/perl`.   `module spider perl` returns
```
-----------------------------------------------------------------------------------------------------------------------
  perl: perl/5.38.0
-----------------------------------------------------------------------------------------------------------------------

    This module can be loaded directly: module load perl/5.38.0

    Help:
      Name   : perl
      Version: 5.38.0
      Target : x86_64

      Perl 5 is a highly capable, feature-rich programming language with over
      27 years of development.
```
Is resolving the Hera MinMon issue as simple as loading `perl/5.38.0` in g-w `modulefiles/module_base.hera.lua`?

**Comment by EdwardSafford-NOAA** [comment]
@RussTreadon-NOAA without looking at g-w logs I'm still guessing, but in the past the problem has been that `global-workflow/ush/minmon_xtrct_gnorms.pl` uses `List::MoreUtils`.  When first porting MinMon to hera, MoreUtils perl lib wasn't available and I had to ask for it to be added.  I suspect `MoreUtils `is again missing on Rocky 8 nodes.

**Comment by RussTreadon-NOAA** [comment]
@EdwardSafford-NOAA, I have not yet tried running MinMon on Rocky 8 nodes so I also don't have a log file to look at.  The following test echoes your hypothesis.

- `module load perl/5.38.0`
- `./minmon_xtrct_gnorms.pl`
```
Hera(hfe09):/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/test/ush$ ./minmon_xtrct_gnorms.pl
Can't locate List/MoreUtils.pm in @INC (you may need to install the List::MoreUtils module) (@INC entries checked: /apps/spack/linux-rocky8-x86_64/gcc-13.2.0/perl-xml-libxml-2.0201-ieap64ggc6erk4kmavvmx26ouz37qcth/lib/perl5/x86_64-linux-thread-multi /apps/spack/linux-rocky8-x86_64/gcc-13.2.0/perl-xml-sax-1.02-7mtjnrdbi26m5hl2o3pqc6is67nccupf/lib/perl5/x86_64-linux-thread-multi /apps/spack/linux-rocky8-x86_64/gcc-13.2.0/perl-xml-sax-1.02-7mtjnrdbi26m5hl2o3pqc6is67nccupf/lib/perl5 ./ /apps/spack/linux-rocky8-x86_64/gcc-13.2.0/perl-5.38.0-yl7cdgbmiic3h7gbvdthgequuixjvuja/lib/perl5 /apps/spack/linux-rocky8-x86_64/gcc-13.2.0/perl-5.38.0-yl7cdgbmiic3h7gbvdthgequuixjvuja/lib/site_perl/5.38.0/x86_64-linux-thread-multi /apps/spack/linux-rocky8-x86_64/gcc-13.2.0/perl-5.38.0-yl7cdgbmiic3h7gbvdthgequuixjvuja/lib/site_perl/5.38.0 /apps/spack/linux-rocky8-x86_64/gcc-13.2.0/perl-5.38.0-yl7cdgbmiic3h7gbvdthgequuixjvuja/lib/5.38.0/x86_64-linux-thread-multi /apps/spack/linux-rocky8-x86_64/gcc-13.2.0/perl-5.38.0-yl7cdgbmiic3h7gbvdthgequuixjvuja/lib/5.38.0) at ./minmon_xtrct_gnorms.pl line 5.
BEGIN failed--compilation aborted at ./minmon_xtrct_gnorms.pl line 5.
```
@WalterKolczynski-NOAA , what's the process to get `MoreUtils` into Rocky-8 `perl/5.38.0`?

**Comment by WalterKolczynski-NOAA** [comment]
I do not know anything about the issues at play here. I just created this issue in response to #2421, which disabled minmon on Hera. That's @HenryWinterbottom-NOAA 's PR, so hopefully he can provide info.

**Comment by RussTreadon-NOAA** [comment]
Confirm that vminmon job fails on Hera Rocky 8 as @EdwardSafford-NOAA suspected.  Log file contains
```
+ exglobal_atmos_vminmon.sh[51]: /scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/test/ush/minmon_xtrct_gnorms.pl gfs 20211221 00 /scratch1/NCEPDEV/stmp2/Russ.Treadon/COMROOT/prgsi/gdas.20211221/00//analysis/atmos/gdas.t00z.gsistat
Can't locate List/MoreUtils.pm in @INC (you may need to install the List::MoreUtils module) (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at /scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/test/ush/minmon_xtrct_gnorms.pl line 5.
BEGIN failed--compilation aborted at /scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/test/ush/minmon_xtrct_gnorms.pl line 5.
+ exglobal_atmos_vminmon.sh[1]: postamble exglobal_atmos_vminmon.sh 1711637927 2
```

The vminmon job is an important tool in monitoring the health GSI-based parallels.  vminmon alerts staff to minimization problems which, in turn, can impact the quality of the cycled analysis-forecast system.  We should restore vminmon functionality on Hera sooner rather than later.

**Comment by HenryRWinterbottom** [comment]
That's a question for @DavidHuber-NOAA . However, I think he is on leave this week.

**Comment by aerorahul** [comment]
@RussTreadon-NOAA 
Rocky 8 has a missing List/MoreUtils Perl module.
A helpdesk ticket has been opened and being followed up.

**Comment by RussTreadon-NOAA** [comment]
Thank you @aerorahul for letting us know.  We'll just sit tight and wait.

**Comment by WalterKolczynski-NOAA** [comment]
I've updated the issue to reflect it being a perl lib issue rather than a gsi_monitor issue.

**Comment by DavidHuber-NOAA** [comment]
The new Perl module was installed on Friday on Rocky 8, so we should be able to test this now.
