### ISSUE TITLE
Retire AWIPS GRIB1 products

### ISSUE THREAD

**Issue by GwenChen-NOAA** [NOAA-EMC/global-workflow#2445]
### What new functionality do you need?

AWIPS GRIB1 products (xtrn.awpgfsFFF.211.gfs_awips_fFFF_CC) will be retired in GFSv17, and thus its associated j-job JGFS_ATMOS_AWIPS_G2 and scripts can be removed.

### What are the requirements for the new functionality?

None.

### Acceptance Criteria

The xtrn.awpgfsFFF.211.gfs_awips_fFFF_CC files are no longer generated under gfs.YYYYMMDD/CC/products/atmos/wmo.

### Suggest a solution (optional)

Please let me know the process of retiring old products in the workflow. Thanks!

**Comment by aerorahul** [comment]
@GwenChen-NOAA 
I would suggest starting with identifying the script that is generating this product and start eliminating its generation and traces from the script and go up the chain to alter the job and so on.
If the script in question does not produce any other product, the entire script can be removed.
Investigate if that script is the only one being called by its parent j-job. If yes, then eliminate the j-job and the rocoto job.
If that is the case, then let us know and we can help identifying th workflow XML components that need to be removed and can provide further assistance.

**Comment by GwenChen-NOAA** [comment]
@aerorahul, the AWIPS GRIB1 products are generated by one job and I tracked down all the scripts and parm files it used.  They are:

global-workflow/ecf/scripts/gfs/atmos/post_processing/awips_g2/jgfs_atmos_awips_g2_master.ecf
global-workflow/jobs/JGFS_ATMOS_AWIPS_G2
global-workflow/jobs/rocoto/awips_g2.sh
global-workflow/scripts/exgfs_atmos_grib_awips.sh
global-workflow/parm/wmo/grib_awpgfs${fcsthrs}.211

I think this job can be retired by deleting these files. The associated rocoto job is awips_g2.sh. Will need your help to remove it from the rocoto task list. This job uses two gfs-utils: overgridid.fd and mkgfsawps.fd. It may be better to leave them in the gfs-utils repo in case that other jobs are calling them. If you agree, I will do a test run and open a PR for it. Thanks!

**Comment by GwenChen-NOAA** [comment]
@aerorahul, I opened a PR (#2547) to delete the files. Please remove the awips_g2 tasks from rocoto task list after the PR is merged. Your help is greatly appreciated!
