### ISSUE TITLE
Integrate WAFS into GFSv17 global-workflow

### ISSUE THREAD

**Issue by YaliMao-NOAA** [NOAA-EMC/global-workflow#2452]
### What new functionality do you need?

WAFS used to be a standalone package as a UPP WAFS downstream, which includes 5 jobs in GFSv16.3.13:
JGFS_ATMOS_WAFS
JGFS_ATMOS_WAFS_BLENDING_0P25
JGFS_ATMOS_WAFS_GCIP
JGFS_ATMOS_WAFS_GRIB2
JGFS_ATMOS_WAFS_GRIB2_0P25

For GFSv17, WAFS is going to transition jobs/scripts/ush to global workflow while keeping its own sorc/parm/fix/modulefiles. WAFS standalone package will be a CMake version, and provide a revision number update when making a pull request to global workflow.

### What are the requirements for the new functionality?

Offline UPP needs to be implemented in GFSv17 global-workflow to generate inputs for WAFS.

### Acceptance Criteria

Regression tests against operational WAFS products.

### Suggest a solution (optional)

EIB integrates one of the 5 WAFS jobs into global-workflow. Yali will follow the similar procedure to do the left 4 jobs.

**Comment by YaliMao-NOAA** [comment]
At the primitive step as in PR #2412, WAFS jobs/scripts/ush were simply copied to GFS v17 workflow repository

**Comment by YaliMao-NOAA** [comment]
As a requirement, offline UPP needs to be implemented in GFSv17 global-workflow to generate inputs for WAFS, which is going to be solved as in issue #2417

**Comment by WalterKolczynski-NOAA** [comment]
WAFS is no longer planned to be added back into the GFS suite and global workflow.
