### ISSUE TITLE
gdaseupd memory issues on Hera

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/global-workflow#2454]
### What is wrong?

Periodically, the gdaseupd job fails on Hera with memory issues when run at C384.  The job usually runs successfully on the second iteration.  Reported by @wx20jjung @CatherineThomas-NOAA.

### What should have happened?

The job should have enough memory to complete successfully.

### What machines are impacted?

Hera

### Steps to reproduce

Run a C384 experiment with 80 members.  Eventually, an eupd job will fail.

### Additional information

N/A

### Do you have a proposed solution?

@wx20jjung found a solution to be to change the runtime layout to 5 PEs per node with 8 threads (instead of 8 PEs/5 threads) and 80 PEs total (instead of 270).  This resulted in much shorter wait times and only about 5 minutes longer run time.

**Comment by HenryRWinterbottom** [comment]
@wx20jjung Can you please share the configuration that you used for `workflow/setup_expt.py`? I would like to test your configuration before submitting a PR to address this issue. Thank you.

**Comment by wx20jjung** [comment]
I changed my configuration after setup_expt.py.  I changed my configuration
directly within the config files and the *.xml.

**Comment by HenryRWinterbottom** [comment]
@wx20jjung Can you please provide me the commands that you passed to `setup_expt.py` before you changed the XML? I want to run your configuration to make sure the processor topology is not a red herring. Thank you.

**Comment by wx20jjung** [comment]
Henry, all of my edits came after running setup_expt.py and setup_xml.py.
Here is what I used on hera:

setup_expt.py gfs cycled --idate 2024013118 --edate 2024040518 --app ATM
--gfs_cyc 1 --resdetatmos 384 --resensatmos 192 --nens 80 --cdump GDAS
--pslot test --comroot /scratch1/NCEPDEV/stmp2/Jim.Jung --expdir
/home/Jim.Jung/para --icsdir
/scratch1/NCEPDEV/jcsda/Jim.Jung/scrub/gdas_init/output

setup_xml.py /home/Jim.Jung/para/test

I then edited cofig.resources to 80 cores (tasks)
<         export npe_eupd=80
---
>         export npe_eupd=270

and test.xml  to 16 nodes and switched the task/thread ratio
<       <nodes>16:ppn=5:tpp=8</nodes>
---
>       <nodes>54:ppn=8:tpp=5</nodes>

There are no openmp statements in the eupd code, so the task/thread ratio
just limits the number of tasks on a node.

**Comment by HenryRWinterbottom** [comment]
@wx20jjung Can you please open `/home/Jim.Jung/para` or move your `EXPDIR` somewhere that I can read it?

**Comment by wx20jjung** [comment]
All of my para directory is copied to
/scratch1/NCEPDEV/jcsda/Jim.Jung/save/para

**Comment by guoqing-noaa** [comment]
Not sure whether it is related, but issue #https://github.com/NOAA-EMC/global-workflow/issues/2506 also reported enkfgdaseupd task crashes.

**Comment by HenryRWinterbottom** [comment]
@wx20jjung I have been unable to get the configuration that you passed me [here](https://github.com/NOAA-EMC/global-workflow/issues/2454#issuecomment-2123731785) to work. 

Instead I created a [branch](https://github.com/HenryWinterbottom-NOAA/global-workflow/tree/feature/gwdev_issue_2454) where I applied your suggested fix. In addition, I have built the branch on RDHPCS and that can be found at `/scratch1/NCEPDEV/da/Henry.Winterbottom/trunk/global-workflow.gwdev_issue_2454`. Please try to use either the repo or the compiled G-W to test the configuration that I linked below.

Once you do, please pass me the path to your Rocoto files. Thank  you in advance.

**Comment by wx20jjung** [comment]
@Henry Winterbottom - NOAA Affiliate ***@***.***>
Is there a reason you did not flip the task/thread ratio?  This is the most
important change.
In config.resources, at line 1033 try changing export nth_eupd=5 to export
nth_eupd=8
This allows more memory per task, which is needed.

**Comment by HenryRWinterbottom** [comment]
@wx20jjung Thank you. That was a typo/oversight on my part. 

Please try again.

**Comment by wx20jjung** [comment]
@HenryWinterbottom-NOAA I ran both python setup scripts from your /scratch1/NCEPDEV/da/Henry.Winterbottom/trunk/global-workflow.gwdev_issue_2454.  I had to change the nth_eupd=5 to nth_eupd=8 and change the task/thread ratio in the *.xml file from <nodes>16:ppn=8:tpp=5</nodes> to <nodes>16:ppn=5:tpp=8</nodes>.  These changes would not be necessary if the appropriate change were made in the global-workflow/parm/config/gfs/config.resources file.  

As you requested, I started a cycling experiment. This is using your /scratch1/NCEPDEV/da/Henry.Winterbottom/trunk/global-workiflow.gwdev_issue2454.  The comroot directory is /scratch1/NCEPDEV/stmp2/Jim.Jung/scrub/HW_test.  I have successfully run through 2 cycles of *eupd*.  The run time log files are in the appropriate directory under $comroot/log.

**Comment by HenryRWinterbottom** [comment]
@wx20jjung Can you please point me to your Rocoto xml file?

**Comment by wx20jjung** [comment]
@HenryWinterbottom-NOAA  I put the file here:  /scratch1/NCEPDEV/jcsda/Jim.Jung/noscrub/HW_test.xml
