### ISSUE TITLE
Turn off reducedgrid in the EnKF

### ISSUE THREAD

**Issue by CatherineThomas-NOAA** [NOAA-EMC/global-workflow#2455]
### What new functionality do you need?

The “reducedgrid” feature has been in use in the EnKF for several GDAS implementations as a way to reduce computation/run time by interpolating to a reduced grid.  This feature was reevaluated in the context of soil DA since the reducedgrid transform cannot handle masked fields.  

Timings consistently showed that using reducedgrid=.true. no longer results in a reduced runtime.  Full resolution EnKF on WCOSS2:
```
 TRUE      FALSE
1522.97   1313.58
1481.85   1312.23
1474.18   1318.42
1474.25   1319.89
```
The differences in increments are very small, ~10^-4 m/s for wind speed and ~10^-5K for temperature.  

This feature should be turned off for v17.

### What are the requirements for the new functionality?

`reducedgrid` should be `.false.` by default in the EnKF

### Acceptance Criteria

`reducedgrid` should be `.false.` by default in the EnKF

### Suggest a solution (optional)

Edit `scripts/exgdas_enkf_update.sh`

**Comment by guoqing-noaa** [comment]
I am curious whether the timing results shown above are from WCOSS2 nodes with fast disks? 
Will the runtimes also be similar when running on other platforms such as Hera or Orion? Thanks!

**Comment by CatherineThomas-NOAA** [comment]
@guoqing-noaa Those timings were not using the flash disks.  I will also run some quick standalone tests on Hera to make sure there's no severe degradation on that machine.

**Comment by guoqing-noaa** [comment]
That's great! Thanks, @CatherineThomas-NOAA

**Comment by CatherineThomas-NOAA** [comment]
@guoqing-noaa I ran two additional sets of reducedgrid EnKF tests: C384/C192 on Hera and C384/C192 on WCOSS2.

Hera
```
 TRUE  |  FALSE
736.18 | 837.79
729.55 | 822.93
736.64 | 885.51
751.97 | 832.56
784.69 | 839.52
```

WCOSS2
```
 TRUE  |  FALSE
419.12 | 408.29
419.09 | 407.04
418.09 | 409.55
419.77 | 421.55
420.82 | 420.6
```

So you can see that there is some slowdown on Hera when removing this option.  And the C384/C192 WCOSS2 tests show that the slowdown on Hera was not only due to the reduced resolution.  

We will soon be turning on the soil DA in the global EnKF, which will not be able to use the reducedgrid option at all.  For testing without soil DA, this option can always be modified in the configs, this PR only changes the default.  Thank you for asking @guoqing-noaa, these were good tests to run.

**Comment by guoqing-noaa** [comment]
@CatherineThomas-NOAA Thanks a lot for the tests and results!
