### ISSUE TITLE
Archive Jobs Fail 

### ISSUE THREAD

**Issue by azadeh-gh** [NOAA-EMC/global-workflow#2469]
### What is wrong?

gdasarch jobs fails on Hera due to:

ERROR: matchdir:  opendir error 2 opening directory gdas.20230403/00/analysis/snow/
*** Warning: No matching names located for 'gdas.20230403/00/analysis/snow/*[0000.sfc_data.tile1.nc](http://0000.sfc_data.tile1.nc/)'

 

### What should have happened?

It seems like the failure is due to the exglobal_archive.sh script attempting to copy files from ${COM_SNOW_ANALYSIS} directory to ${ARCDIR}, but the ${COM_SNOW_ANALYSIS} directory not exist. 

### What machines are impacted?

Hera

### Steps to reproduce

Run global workflow v17 archive jobs on Hera.
Global workflow commit:  59cdc0ee81926ee8dc7b8e544337bfc85130ad18

### Additional information

log file:  /scratch2/NCEPDEV/stmp3/Azadeh.Gholoubi/TestExperiment/MonthThompsonMP/logs/2023040218/gdasarch.log

**Comment by aerorahul** [comment]
@azadeh-gh 
The source of this bug is identified [here](https://github.com/NOAA-EMC/global-workflow/pull/2414/files#r1556446225)
