### ISSUE TITLE
Stage initial conditions for cycled and forecast-only via stage_ic job.

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/global-workflow#2475]
### What new functionality do you need?

Presently, the cycled initial conditions are staged by `setup_expt.py`.
The initial conditions for forecast-only are staged by a job `stage_ic`.

This feature requests development of the `stage_ic` job to stage cycled initial conditions in addition to the ones for forecast-only.

### What are the requirements for the new functionality?

The new `stage_ic` job should be able to handle both `cycled` and `forecast-only` modes as well as for `gfs` and `gefs` systems.  
Extra points for making the job generic to allow users to provide (files) initial conditions of their choosing from arbitrary locations and structure.

### Acceptance Criteria

Add the `stage_ic` job to the first half-cycle of the cycled mode.

**Comment by WalterKolczynski-NOAA** [comment]
@KateFriedman-NOAA See #2559 for changes relevant to this issue

**Comment by WalterKolczynski-NOAA** [comment]
@KateFriedman-NOAA #2545 is also adding options to stage_ic you'll have to handle
