### ISSUE TITLE
CICE fix files at 1deg are not present in fix file directory

### ISSUE THREAD

**Issue by DeniseWorthen** [NOAA-EMC/global-workflow#2480]
### What is wrong?

On Hera (and maybe other platforms), the directory ``/scratch1/NCEPDEV/global/glopara/fix/cice/20231219/100`` does not contain the fix files for this CICE resolution. It contains the MOM6 files instead.

The directory ``/scratch1/NCEPDEV/global/glopara/fix/20220805/100`` does contain the correct files

```
-rw-r--r-- 1 role.glopara global 5069840 Oct 15  2021 grid_cice_NEMS_mx100.nc
-rw-r--r-- 1 role.glopara global  461520 Oct 15  2021 kmtu_cice_NEMS_mx100.nc
-rw-r--r-- 1 role.glopara global 6464858 Oct 15  2021 mesh.mx100.nc
```

### What should have happened?

The MOM6 files should not be present, and the correct CICE files should be in place.

### What machines are impacted?

All or N/A, Hera

### Steps to reproduce

List the file contents in /scratch1/NCEPDEV/global/glopara/fix/cice/20231219/100
```
-rw-r--r-- 1 role.glopara global  2341588 Oct 15  2021 atmos_mosaic_tile1Xland_mosaic_tile1.nc
-rw-r--r-- 1 role.glopara global  4145236 Oct 15  2021 atmos_mosaic_tile1Xocean_mosaic_tile1.nc
-rw-r--r-- 1 role.glopara global     1544 Oct 15  2021 hycom1_75_800m.nc
-rw-r--r-- 1 role.glopara global      984 Oct 15  2021 interpolate_zgrid_40L.nc
-rw-r--r-- 1 role.glopara global   466796 Oct 15  2021 KH_background_2d.nc
-rw-r--r-- 1 role.glopara global   938352 Oct 15  2021 land_mask.nc
-rw-r--r-- 1 role.glopara global  4145236 Oct 15  2021 land_mosaic_tile1Xocean_mosaic_tile1.nc
-rw-r--r-- 1 role.glopara global      772 Oct 15  2021 layer_coord.nc
-rw-r--r-- 1 role.glopara global     4388 Oct 15  2021 MOM_channels_SPEAR
-rw-r--r-- 1 role.glopara global      113 Oct 15  2021 MOM_override
-rw-r--r-- 1 role.glopara global 22162740 Oct 15  2021 ocean_hgrid.nc
-rw-r--r-- 1 role.glopara global   938352 Oct 15  2021 ocean_mask.nc
-rw-r--r-- 1 role.glopara global    18928 Oct 15  2021 ocean_mosaic.nc
-rw-r--r-- 1 role.glopara global  5535716 Oct 15  2021 seawifs_1998-2006_smoothed_2X.nc
-rw-r--r-- 1 role.glopara global   466632 Oct 15  2021 tidal_amplitude.nc
-rw-r--r-- 1 role.glopara global     1476 Oct 15  2021 topo_edits_011818.nc
-rw-r--r-- 1 role.glopara global  1845348 Oct 15  2021 topog.nc
-rw-r--r-- 1 role.glopara global     2232 Apr 13  2022 ufs.topo_edits_011818.nc
-rw-r--r-- 1 role.glopara global      792 Oct 15  2021 vgrid_75_2m.nc
```

### Additional information

none

**Comment by KateFriedman-NOAA** [comment]
@DeniseWorthen Is this issue taken care of via the files I pulled in for issue #2483? Let me know if not. Thanks!

**Comment by DeniseWorthen** [comment]
The new (``20240416``) directories contain the correct files. The files in the older ``cice/20231219/100`` are still incorrect. It may be that it has no impact, if the G-W doesn't point to those files for any reason.

**Comment by KateFriedman-NOAA** [comment]
@DeniseWorthen Great, I'll mark this issue for closure when we complete issue #2483. Thanks for confirming!

**Comment by KateFriedman-NOAA** [comment]
Work is done but awaiting updates to relevant `fix.ver` versions. Will do this and close issue as complete when we update to a UWM hash at or beyond the result of https://github.com/ufs-community/ufs-weather-model/pull/2235.
