### ISSUE TITLE
update fix files for CICE and MOM6/post

### ISSUE THREAD

**Issue by DeniseWorthen** [NOAA-EMC/global-workflow#2483]
### Target fix directory

cice, mom6

### Type of change

- [X] Update existing files
- [ ] Remove files
- [ ] Add new files to existing directory
- [ ] Add new fix directory

### Any workflow changes needed?

No change needed

### Related issues

The cice grid files (/glopara/fix/cice) need to be updated after a fix for the incorrect rotation angle for CICE was merged in UFS-UTILS/cpld_gridgen. The 4deg (400) can be removed. This was actually the 5-deg resolution which was initially incorrectly named ``400`` instead of ``500`` in UWM.

The mom6 post files also need updating. 

As part of https://github.com/ufs-community/UFS_UTILS/issues/929, I also require an two additional files be added:

 - tripole.mx[].nc file for each resolution 
 - tripole.mx[].Ct.to.Bu.bilinear.nc for each resolution
- mesh.mx[].nc

These can be added to the existing mom6/post directories. Note this directory already contains files used for ice post-processing as well as ocean post. 

Associated issues:

https://github.com/ufs-community/UFS_UTILS/issues/921
https://github.com/ufs-community/ufs-weather-model/issues/2228

The PR to update the files for use by UWM is https://github.com/ufs-community/ufs-weather-model/pull/2235

### Pickup location

/scratch1/NCEPDEV/nems/role.ufsutils/ufs_utils/reg_tests/cpld_gridgen/baseline_data

### Size

~1000 MB for the 025 resolution

**Comment by KateFriedman-NOAA** [comment]
@DeniseWorthen I have made a copy of the latest `20231219` cice timestamp subfolder to make the updates within. I have copied `20231219` to `20240416` and removed the `400` folder within the new `20240416` set. Since you have the new mom6/post files within your `025/050/100/500` folders, which files do you want me to copy into the new `cice/20240416`? Similarly, are there files that can/should be removed within the `20240416` copy?

> As part of https://github.com/ufs-community/UFS_UTILS/issues/929, I also require an two additional files be added:

I think I'm clear on the mom6/post files to pull into the existing `20231219` set. Will do that now.

**Comment by DeniseWorthen** [comment]
@KateFriedman-NOAA In the ``20240416/cice`` directories, there should be the three files, each w/ a resolution identifier, where ``[]`` = 025,050,100,500

```
grid_cice_NEMS_mx[].nc
kmtu_cice_NEMS_mx[].nc
mesh.mx[].nc
```

The cice/100 directory still contain the mom6 fix files by mistake (issue #2480). 

In the mom6/post subdirectories I need any file containing "tripole" in the file name.

**Comment by KateFriedman-NOAA** [comment]
@DeniseWorthen Thanks for the clarification! How does the updated `cice/20240416` look?

```
[role.glopara@hfe08 20240416]$ pwd
/scratch1/NCEPDEV/global/glopara/fix/cice/20240416
[role.glopara@hfe08 20240416]$ ll *
025:
total 157972
-r--r--r-- 1 role.glopara global 68429828 Apr  3 18:09 grid_cice_NEMS_mx025.nc
-r--r--r-- 1 role.glopara global  6221520 Apr  3 18:09 kmtu_cice_NEMS_mx025.nc
-r--r--r-- 1 role.glopara global 87107397 Apr  3 18:09 mesh.mx025.nc

050:
total 42144
-r--r--r-- 1 role.glopara global 18248708 Apr  3 18:10 grid_cice_NEMS_mx050.nc
-r--r--r-- 1 role.glopara global  1659600 Apr  3 18:10 kmtu_cice_NEMS_mx050.nc
-r--r--r-- 1 role.glopara global 23238629 Apr  3 18:10 mesh.mx050.nc

100:
total 5660
-r--r--r-- 1 role.glopara global 5069828 Apr  3 18:10 grid_cice_NEMS_mx100.nc
-r--r--r-- 1 role.glopara global  461520 Apr  3 18:10 kmtu_cice_NEMS_mx100.nc
-r--r--r-- 1 role.glopara global 6463973 Apr  3 18:10 mesh.mx100.nc

500:
total 276
-r--r--r-- 1 role.glopara global 111908 Apr  3 18:10 grid_cice_NEMS_mx500.nc
-r--r--r-- 1 role.glopara global  10800 Apr  3 18:10 kmtu_cice_NEMS_mx500.nc
-rw-r--r-- 1 role.glopara global 154762 Jul 14  2022 mesh.mx500.nc
```

**Comment by DeniseWorthen** [comment]
@KateFriedman-NOAA Those are the correct files for the fix/cice subdirectory. Thanks.

**Comment by KateFriedman-NOAA** [comment]
@DeniseWorthen Thanks for confirming the new `cice` timestamp copy is good.

Since we're overwriting existing files in the `mom6/post` folder, I also created a copy of the current `20231219` `mom6` and placed the updated files within it. I also removed some symlinks in the new copy that redirected folks to updated naming conventions, since we shouldn't need them in the new copy anymore. The other resolution folders/files at the same level as the `post` folder are untouched and simply copied from the `20231219` set. 

Please see the new `mom6/20240416/post` copy: `/scratch1/NCEPDEV/global/glopara/fix/mom6/20240416/post`.

Let me know if the new `mom6/20240416/post` is as requested. Thanks!

**Comment by DeniseWorthen** [comment]
@KateFriedman-NOAA This all seems correct. Thanks!

**Comment by KateFriedman-NOAA** [comment]
@DeniseWorthen Great, thanks for confirming! I will sync these updates to the fix sets on the other platforms. I am doing a similar fix update in issue #2493, so will wait for confirmation from that user before doing the syncs. Will confirm when the syncs are complete.

We will now need to update `mom6_ver=20240416` in [`versions/fix.ver`](https://github.com/NOAA-EMC/global-workflow/blob/develop/versions/fix.ver#L17) to use the updated files. Do you have plans to do so in an upcoming PR, perhaps with related script updates?

**Comment by DeniseWorthen** [comment]
The new CICE fix files will be switched over to in an upcoming UFS PR (https://github.com/ufs-community/ufs-weather-model/pull/2235). As for how the post files are used, I don't really know anything about the versioning in G-W or even where I would make that change.

**Comment by KateFriedman-NOAA** [comment]
Oh right, we'll need to update both `cice_ver ` and `mom6_ver` in `versions/fix.ver`. Noted about the UFS PR. We'll need to update to `cice_ver=20240416` when we move to the hash associated with that PR.

Whenever users want to start using the updated `mom6/20240416/post` files the `mom6_ver` setting in `versions/fix.ver` will need to be updated in global-workflow.

**Comment by KateFriedman-NOAA** [comment]
The CICE and MOM6/post fix updates have now been synced to both WCOSS2, Orion, and Jet.

**Comment by KateFriedman-NOAA** [comment]
The CICE and MOM6/post fix updates are also now synced to our global AWS bucket.

**Comment by KateFriedman-NOAA** [comment]
Work is done but awaiting updates to relevant `fix.ver` versions. Will do this and close issue as complete when we update to a UWM hash at or beyond the result of https://github.com/ufs-community/ufs-weather-model/pull/2235.

**Comment by KateFriedman-NOAA** [comment]
@DeniseWorthen Shall we also update to the newer `mom6/20240416` version when we update to the newer `cice/20240416`? Or do we need to wait for a component update?

**Comment by DeniseWorthen** [comment]
@KateFriedman-NOAA Yes, the mom6/20240416 should be updated as well because that is where the post weights, which would have been updated, reside.

**Comment by KateFriedman-NOAA** [comment]
> Yes, the mom6/20240416 should be updated as well

@DeniseWorthen got it, I will update that version in the same PR as the `cice_ver`.
