### ISSUE TITLE
Update ufs-weather-model hash in g-w

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#2490]
### What new functionality do you need?

Update of ufs-weather-model with recent bug-fixes for running C768 on hera. 

### What are the requirements for the new functionality?

Update ufs-weather-model hash

### Acceptance Criteria

Updated ufs-weather-model hash 

### Suggest a solution (optional)

Adding this issue here to see if anyone already had a PR in the works as to not duplicate efforts.

**Comment by HenryRWinterbottom** [comment]
C48 ATM forecast-only completes without issue.

Testing the C768 resolution now.

**Comment by HenryRWinterbottom** [comment]
@JessicaMeixner-NOAA Which tag is the new UFS hash?

I am testing against `281b32fb`. C48 passes the g-w CI C48 atmosphere only experiment. However, C768 fails with the following error:

```
2040:  warning: snow/ice temperature is too low:  -353.146085173361
2040:  fix snow/ice temperature: reset it to:   173.000000000000
2040:  warning: snow/ice temperature is too low:  -423.366140295302
.
.
.
```

The full log is at `/scratch1/NCEPDEV/da/Henry.Winterbottom/work/global-workflow/COMROOT/x003_gfsv17_issue_2490/logs/2020010200/gfsfcst.log`. In my experience, the above mentioned error is related to issues within either the ICs or a surface physical parameterization.

Which analysis dates has the above tag been tested for?

**Comment by JessicaMeixner-NOAA** [comment]
@HenryWinterbottom-NOAA see https://github.com/ufs-community/ufs-weather-model/issues/2227 and https://github.com/ufs-community/ufs-weather-model/pull/2201 for additional information about what others have tested.  

You did get the failure: 
4608: Abort(1007288322) on node 4608 (rank 4608 in comm 0): Fatal error in PMPI_Type_contiguous: Invalid count, error stack:
4608: PMPI_Type_contiguous(271): MPI_Type_contiguous(count=-2056673383, MPI_BYTE, new_type_p=0x7ffc47c61514) failed
4608: PMPI_Type_contiguous(238): Negative count, value is -2056673383
   0: slurmstepd: error: *** STEP 58305901.0 ON h2c01 CANCELLED AT 2024-04-16T19:56:58 ***

**Comment by JessicaMeixner-NOAA** [comment]
@HenryWinterbottom-NOAA I have started making a C768 test on my end and saw that we have some updates for CICE coming in this update of UFS: https://github.com/ufs-community/ufs-weather-model/compare/7fdb58cad0dad2f62ce7813c6719554d1c5a17af...4f32a4b5e6b17c85c6abf52ffd5b44a38d250c3b 

Do you have a branch with these updates already in there that I can try?

**Comment by JessicaMeixner-NOAA** [comment]
@HenryWinterbottom-NOAA I made a quick run with the new hash of ufs-weather-model, and it looks like either you were unintentionally running with an older version of ufs or you have the updates that correspond to CICE in your branch as I got an error that I had undefined variables with the updated ufs. So I'll pause until I hear from you where I can checkout your branch with the CICE updates or what the next steps are.

**Comment by HenryRWinterbottom** [comment]
> @HenryWinterbottom-NOAA see [ufs-community/ufs-weather-model#2227](https://github.com/ufs-community/ufs-weather-model/issues/2227) and [ufs-community/ufs-weather-model#2201](https://github.com/ufs-community/ufs-weather-model/pull/2201) for additional information about what others have tested.
> 
> You did get the failure: 4608: Abort(1007288322) on node 4608 (rank 4608 in comm 0): Fatal error in PMPI_Type_contiguous: Invalid count, error stack: 4608: PMPI_Type_contiguous(271): MPI_Type_contiguous(count=-2056673383, MPI_BYTE, new_type_p=0x7ffc47c61514) failed 4608: PMPI_Type_contiguous(238): Negative count, value is -2056673383 0: slurmstepd: error: *** STEP 58305901.0 ON h2c01 CANCELLED AT 2024-04-16T19:56:58 ***

@JessicaMeixner-NOAA Yes, this is similar to the error that I am getting. 

Can you please give me an analysis date for ICs on RDHPCS Hera that I can test this new hash against? The files in `/scratch1/NCEPDEV/global/glopara/data/ICSDIR/prototype_ICs/HR3C768` are incomplete (e.g., are missing the coupler files for the mediator).

**Comment by JessicaMeixner-NOAA** [comment]
@HenryWinterbottom-NOAA to clarify, that was what I copied form your log file.  The error I am getting is because the workflow has not been updated for the ice_in file.  Do you have those updates in a branch somewhere? 

The ICS in /scratch1/NCEPDEV/global/glopara/data/ICSDIR/prototype_ICs/HR3C768 are complete for a cold-start forecast only run, in which you do not need the coupler files for the mediator.

**Comment by HenryRWinterbottom** [comment]
@JessicaMeixner-NOAA Is the fix contained within the hash `4f32a4b5` only required for ATM forecast-only runs?

Further, if this is the incorrect hash, please provide for me the hash.

**Comment by JessicaMeixner-NOAA** [comment]
@HenryWinterbottom-NOAA I'm very confused, you do not need coupler restart files for forecast only runs.  The fixes are included in ufs-weather-model develop, so the hash you are pointing to is great as it's the top of the develop branch. 

If you update to the top of ufs-weather-model, we need to make updates for the forecast model (in this case for ice model) that correspond to updates made in ufs-weather-model in the global-workflow.  Are you planning to make these updates?  Have you already made these updates?

**Comment by HenryRWinterbottom** [comment]
@JessicaMeixner-NOAA OK, I am confused as well. Please see below.

> @HenryWinterbottom-NOAA to clarify, that was what I copied form your log file. The error I am getting is because the workflow has not been updated for the ice_in file. Do you have those updates in a branch somewhere?
> 

I do not have these changes. Can they picked up from `/scratch1/NCEPDEV/da/Henry.Winterbottom/trunk/global-workflow.gfsv17_issue_2490/sorc/ufs_model.fd/tests/parm/ice_in.IN`? 

If these are the changes, should they not be tested against a g-w S2S* configuration?

**Comment by aerorahul** [comment]
@HenryWinterbottom-NOAA 
Based on the diff provided in [this](https://github.com/NOAA-EMC/global-workflow/issues/2490#issuecomment-2061160996) comment, I believe changes are required in [parsing_namelists_CICE.sh](https://github.com/NOAA-EMC/global-workflow/blob/develop/ush/parsing_namelists_CICE.sh)

**Comment by WalterKolczynski-NOAA** [comment]
> @JessicaMeixner-NOAA OK, I am confused as well. Please see below.
> 
> > @HenryWinterbottom-NOAA to clarify, that was what I copied form your log file. The error I am getting is because the workflow has not been updated for the ice_in file. Do you have those updates in a branch somewhere?
> 
> I do not have these changes. Can they picked up from `/scratch1/NCEPDEV/da/Henry.Winterbottom/trunk/global-workflow.gfsv17_issue_2490/sorc/ufs_model.fd/tests/parm/ice_in.IN`?
> 
> If these are the changes, should they not be tested against a g-w S2S* configuration?

Yes, you want to look at the `ice_in.IN` changes in the diff above and make the necessary changes to `parsing_namelists_CICE.sh`.
