### ISSUE TITLE
update gdas/gsibec qoption

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/global-workflow#2493]
### Target fix directory

gdas/gsibec

### Type of change

- [X] Update existing files
- [ ] Remove files
- [ ] Add new files to existing directory
- [ ] Add new fix directory

### Any workflow changes needed?

No change needed

### Related issues

[GDASApp PR #1015](https://github.com/NOAA-EMC/GDASApp/pull/1015) updated the GSIBEC tag used by GDASApp.  A change to `qoption` associated with this change to GSIBEC is mentioned in [fv3-jedi PR #1173](https://github.com/JCSDA-internal/fv3-jedi/pull/1173).

### Pickup location

/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/jediinc2fv3/fix/gdas/gsibec

### Size

no change in size of `gfs_gsi_global.nml`

**Comment by KateFriedman-NOAA** [comment]
@RussTreadon-NOAA I have created a new `gdas/gsibec` timestamp (`20240416`) and copied the provided files within. Please confirm the following on Hera is as requested, thanks!

```
[role.glopara@hfe08 20240416]$ pwd
/scratch1/NCEPDEV/global/glopara/fix/gdas/gsibec/20240416
[role.glopara@hfe08 20240416]$ ll *
C192:
total 30828
-rw-r--r-- 1 role.glopara global     3593 Apr 15 19:25 gfs_gsi_global.nml
-rw-r--r-- 1 role.glopara global 15183556 Nov  2  2022 global_berror.f77
-rw-r--r-- 1 role.glopara global 16375984 Nov  2  2022 gsi-coeffs-gfs-global.nc4

C384:
total 63640
-rw-r--r-- 1 role.glopara global     3595 Apr 15 19:25 gfs_gsi_global.nml
-rw-r--r-- 1 role.glopara global 31396036 Nov  2  2022 global_berror.f77
-rw-r--r-- 1 role.glopara global 33761200 Nov  2  2022 gsi-coeffs-gfs-global.nc4

C48:
total 15284
-rw-r--r-- 1 role.glopara global    3592 Apr 15 18:03 gfs_gsi_global.nml
-rw-r--r-- 1 role.glopara global 7519684 Nov  2  2022 global_berror.f77
-rw-r--r-- 1 role.glopara global 8125744 Nov  2  2022 gsi-coeffs-gfs-global.nc4

C768:
total 136172
-rw-r--r-- 1 role.glopara global     3596 Apr 15 19:24 gfs_gsi_global.nml
-rw-r--r-- 1 role.glopara global 67359940 Nov  2  2022 global_berror.f77
-rw-r--r-- 1 role.glopara global 72070576 Nov  2  2022 gsi-coeffs-gfs-global.nc4

C96:
total 15284
-rw-r--r-- 1 role.glopara global    3592 Apr 15 19:24 gfs_gsi_global.nml
-rw-r--r-- 1 role.glopara global 7519684 Nov  2  2022 global_berror.f77
-rw-r--r-- 1 role.glopara global 8125744 Nov  2  2022 gsi-coeffs-gfs-global.nc4
```

**Comment by RussTreadon-NOAA** [comment]
@KateFriedman-NOAA .  A diff of the gsibec files in `20221031/` and `20240416/` shows the correct difference.
```
Hera(hfe03):~$ diff -r /scratch1/NCEPDEV/global/glopara/fix/gdas/gsibec/20221031 /scratch1/NCEPDEV/global/glopara/fix/gdas/gsibec/20240416
diff -r /scratch1/NCEPDEV/global/glopara/fix/gdas/gsibec/20221031/C192/gfs_gsi_global.nml /scratch1/NCEPDEV/global/glopara/fix/gdas/gsibec/20240416/C192/gfs_gsi_global.nml
2c2
<    qoption=2,
---
> !  qoption=2,
diff -r /scratch1/NCEPDEV/global/glopara/fix/gdas/gsibec/20221031/C384/gfs_gsi_global.nml /scratch1/NCEPDEV/global/glopara/fix/gdas/gsibec/20240416/C384/gfs_gsi_global.nml
2c2
<    qoption=2,
---
> !  qoption=2,
diff -r /scratch1/NCEPDEV/global/glopara/fix/gdas/gsibec/20221031/C48/gfs_gsi_global.nml /scratch1/NCEPDEV/global/glopara/fix/gdas/gsibec/20240416/C48/gfs_gsi_global.nml
2c2
<    qoption=2,
---
> !  qoption=2,
diff -r /scratch1/NCEPDEV/global/glopara/fix/gdas/gsibec/20221031/C768/gfs_gsi_global.nml /scratch1/NCEPDEV/global/glopara/fix/gdas/gsibec/20240416/C768/gfs_gsi_global.nml
2c2
<    qoption=2,
---
> !  qoption=2,
diff -r /scratch1/NCEPDEV/global/glopara/fix/gdas/gsibec/20221031/C96/gfs_gsi_global.nml /scratch1/NCEPDEV/global/glopara/fix/gdas/gsibec/20240416/C96/gfs_gsi_global.nml
2c2
<    qoption=2,
---
> !  qoption=2,
```
The gsibec namelist in `20240416/` comments out `qoption=2`, thereby defaulting the gsibec code to `qoption=1`.  This is correct.

**Comment by KateFriedman-NOAA** [comment]
@RussTreadon-NOAA Great, thanks for confirming! I will proceed with syncing this update to the fix sets on the other supported platforms.

The [fix version variable](https://github.com/NOAA-EMC/global-workflow/blob/develop/versions/fix.ver#L12) will need to be updated to `gdas_gsibec_ver=20240416`. Do you have plans to make that update within a future PR?

**Comment by RussTreadon-NOAA** [comment]
I did not plan on opening an issue and PR to update `gdas_gsibec_ver` to `20240416`.  I thought this would be accomplished via this issue.  Your question suggests otherwise.  I'll go ahead and open an issue and PR right now.

**Comment by KateFriedman-NOAA** [comment]
> I'll go ahead and open an issue and PR right now.

Thanks @RussTreadon-NOAA ! If you didn't already have plans, I was going to offer to make the change but I'm happy to let you open a PR. Make me the reviewer and I'll get it approved and merged. We'll close this issue via that PR. Thanks!

**Comment by RussTreadon-NOAA** [comment]
@KateFriedman-NOAA 
- g-w issue #2496 has been created to document the change to `gdas_gsibec_ver`.
- g-w PR #2497 has been opened to merge this change into `develop`.

**Comment by KateFriedman-NOAA** [comment]
New `gsibec` copy is now synced to both WCOSS2s, Orion, and Jet.

**Comment by RussTreadon-NOAA** [comment]
Thank you @KateFriedman-NOAA

**Comment by KateFriedman-NOAA** [comment]
This is also now synced to our fix set on AWS.
