### ISSUE TITLE
feature/coupled-crow: moving to netcdf (parallel) output for atm model

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#250]
To move to using netcdf output for the atm model in the feature/coupled-crow branch, we need to change: 
workflow/defaults/output_settings.yaml from: 
OUTPUT_FILE_TYPE: nemsio
to: 
OUTPUT_FILE_TYPE: "'netcdf_parallel' 'netcdf'"

The model will run, however the post jobs are not getting triggered, which can be seen from doing a rocotocheck on the post jobs: 

```
  dependencies
    OR is not satisfied
      /scratch2/NCEPDEV/climate/Jessica.Meixner/p6v16opt02/test01/COMROOT/nowave01/gfs.20130401/00/atmos/gfs.t00z.logf000.nemsio does not exist
      SOME is not satisfied
        gfs.forecast.highres of cycle 201304010000 is not SUCCEEDED
```

What should the dependency for the post jobs when using netcdf be?  And how can we change those in feature/coupled-crow?

**Comment by WalterKolczynski-NOAA** [comment]
In workflow/layout/*.yaml, update the release settings under post to the correct filenames:

```
post: !TaskArray
      RUN: !calc up.RUN
      Dimensions:
        fhr: !calc doc.output_settings.gfs_forecast_hours
      jgfs_post_manager_el: !TaskElement
        <<: *exclusive_task_template
        RUN: !calc up.RUN
        Disable: !calc metasched.type == 'rocoto'
        Trigger: !FirstTrue
          - when: !calc not doc.settings.dev_safeguards
            take: !Depend ( up.forecast.is_running() )
          - otherwise: !Depend "up.forecast.is_running() | up.forecast"
        Foreach: [ ]
        J_JOB: JGLOBAL_POST_MANAGER
        Name: jgfs_post_manager
        resources: !calc partition.resources.run_gfs_post_manager
        release_postanl: !DataEvent
          file: !expand >-
            {metasched.varref("COM")}/gfs.{metasched.datestring("%Y%m%d/%H/")}atmos/gfs.t{metasched.datestring("%H")}z.logf000.nemsio
        release_post_fhr: !DataEventElement
          Name: !expand "release_post{dimval.fhr:03d}"
          Foreach: [ fhr ]
          file: !expand >-
            {metasched.varref("COM")}/gfs.{metasched.datestring("%Y%m%d/%H/")}atmos/gfs.t{metasched.datestring("%H")}z.logf{dimval.fhr:03d}.nemsio
        # NOTE: the above files must match post_manager.yaml
```

As a temporary measure, you can modify the workflow.xml of an existing expdir directly to change the datadep for post to the correct file.

**Comment by WalterKolczynski-NOAA** [comment]
workflow/runtime/post_manager.yaml also has to be updated to match.

**Comment by JessicaMeixner-NOAA** [comment]
What would the correct files be for netcdf?   gfs.t{metasched.datestring("%H")}z.master.grb2f{dimval.fhr:03d}  instead of  gfs.t{metasched.datestring("%H")}z.logf{dimval.fhr:03d}.nemsio?

**Comment by WalterKolczynski-NOAA** [comment]
Yes, although there would also need to be a check to make sure the file is complete.

@KateFriedman-NOAA are there still plans to add the logfiles to inline post so we know when each file is complete?

The post job will also need to be modified to no longer produce the master files, since they are now being produced inline. This may be as simple as cherry-picking the file from GFS v16.

**Comment by JessicaMeixner-NOAA** [comment]
@WalterKolczynski-NOAA the develop branch was recently merged into the feature/coupled-crow branch.  I'm assuming the updates for file dependency needs are known, because we just have to make the crow do what the develop branch is already doing.

**Comment by KateFriedman-NOAA** [comment]
> @KateFriedman-NOAA are there still plans to add the logfiles to inline post so we know when each file is complete?

@WalterKolczynski-NOAA The logf###.txt files get produced from the fcst job (when inline post is turned on or off). Is that what you need? Here are the files that come out of the fcst job for f009 (inline post turned on in this example):

```
[Kate.Friedman@m72a1 ffchgrestest]$ ls -ltr gfs.20210124/06/atmos/*f009*
-rw-r--r-- 1 Kate.Friedman g01 243244122 Jan 27 20:54 gfs.20210124/06/atmos/gfs.t06z.master.grb2f009
-rw-r--r-- 1 Kate.Friedman g01  22976533 Jan 27 20:54 gfs.20210124/06/atmos/gfs.t06z.sfluxgrbf009.grib2
-rw-r--r-- 1 Kate.Friedman g01 506979545 Jan 27 20:54 gfs.20210124/06/atmos/gfs.t06z.atmf009.nc
-rw-r--r-- 1 Kate.Friedman g01  74230227 Jan 27 20:54 gfs.20210124/06/atmos/gfs.t06z.sfcf009.nc
-rw-r--r-- 1 Kate.Friedman g01        71 Jan 27 20:54 gfs.20210124/06/atmos/gfs.t06z.logf009.txt
```

**Comment by WalterKolczynski-NOAA** [comment]
> > @KateFriedman-NOAA are there still plans to add the logfiles to inline post so we know when each file is complete?
> 
> @WalterKolczynski-NOAA The logf###.txt files get produced from the fcst job (when inline post is turned on or off). Is that what you need? Here are the files that come out of the fcst job for f009 (inline post turned on in this example):
> 
> ```
> [Kate.Friedman@m72a1 ffchgrestest]$ ls -ltr gfs.20210124/06/atmos/*f009*
> -rw-r--r-- 1 Kate.Friedman g01 243244122 Jan 27 20:54 gfs.20210124/06/atmos/gfs.t06z.master.grb2f009
> -rw-r--r-- 1 Kate.Friedman g01  22976533 Jan 27 20:54 gfs.20210124/06/atmos/gfs.t06z.sfluxgrbf009.grib2
> -rw-r--r-- 1 Kate.Friedman g01 506979545 Jan 27 20:54 gfs.20210124/06/atmos/gfs.t06z.atmf009.nc
> -rw-r--r-- 1 Kate.Friedman g01  74230227 Jan 27 20:54 gfs.20210124/06/atmos/gfs.t06z.sfcf009.nc
> -rw-r--r-- 1 Kate.Friedman g01        71 Jan 27 20:54 gfs.20210124/06/atmos/gfs.t06z.logf009.txt
> ```

Yes, that would do it. I do not see those files in the directory Jessica was using:
![image](https://user-images.githubusercontent.com/28147896/106194478-e4f48080-617c-11eb-9e43-9e1cdd319bc2.png)

@JessicaMeixner-NOAA The logfile Kate mentioned should be the new trigger, if we can figure out why you don't have it.

**Comment by JessicaMeixner-NOAA** [comment]
in the run dir they are there: 
$ ls *f006*
atmf006.nc  logf006  sfcf006.nc

**Comment by KateFriedman-NOAA** [comment]
FYI, the global-workflow (develop/v16) sets this dependency for each gfspost### job ("#dep#" is an forecast hr chosen to kick off this post job):

```
                <dependency>
                        <datadep><cyclestr>&ROTDIR;/gfs.@Y@m@d/@H/atmos/gfs.t@Hz.log#dep#.txt</cyclestr></datadep>
                </dependency>
```

**Comment by JessicaMeixner-NOAA** [comment]
In the develop branch the section of code that should make those linked files are: https://github.com/NOAA-EMC/global-workflow/blob/develop/scripts/exglobal_forecast.sh#L1315-L1344 which I believe are also in feature/coupled-crow here: https://github.com/NOAA-EMC/global-workflow/blob/feature/coupled-crow/ush/forecast_postdet.sh#L441-L477 however it's behind a : 
```
if [ $inistep = 'cold' ]; then
          echo "Not making links of output for mediator cold start" 
        else 
```
which was supposed to not link anything if we were doing a mediator cold start, which we don't really use anymore and perhaps is not correctly getting to this second part of the code.   Maybe that's the first issue of why things are not being linked correctly.   Once we get those linking correctly, we can workin on fixing the workflow dependency.  Sound reasonable?

**Comment by JessicaMeixner-NOAA** [comment]
So the netcdf part still isn't working, my latest attempt using the same as develop: 
exgfs_atmos_nceppost.sh -> ../sorc/gfs_post.fd/scripts/exgfs_atmos_nceppost.sh
instead of linking to what we had been before: 
https://github.com/NOAA-EMC/global-workflow/blob/feature/coupled-crow/scripts/exgfs_nceppost_cpl.sh.ecf
This test has output here: 
/scratch2/NCEPDEV/climate/Jessica.Meixner/p6workflow/test04/COMROOT/test04/gfs.20130401/00/atmos
which: 
1.8G	gfs.t00z.atmf006.nc
4.0K	gfs.t00z.logf006.txt
714M	gfs.t00z.master.grb2f006
0	gfs.t00z.pgrb.1p00.f006
0	gfs.t00z.pgrb2.0p25.f006
0	gfs.t00z.pgrb2.0p25.f006.idx
0	gfs.t00z.pgrb2.1p00.f006
0	gfs.t00z.pgrb2.1p00.f006.idx
0	gfs.t00z.pgrb2b.0p25.f006
0	gfs.t00z.pgrb2b.0p25.f006.idx
0	gfs.t00z.pgrb2b.1p00.f006
0	gfs.t00z.pgrb2b.1p00.f006.idx
255M	gfs.t00z.sfcf006.nc
78M	gfs.t00z.sfluxgrbf006.grib2
8.0K	gfs.t00z.sfluxgrbf006.grib2.idx

has a lot of size 0 files. 

When I look at log files, for example 
/scratch2/NCEPDEV/climate/Jessica.Meixner/p6workflow/test04/COMROOT/test04/logs/2013040100/gfs.post.p_006.log
we have the following: 
3.384 + OUTPUT_FILE=$'\'netcdf_parallel\' \'netcdf\''
3.385 + [ $'\'netcdf_parallel\'' $'\'netcdf\'' '=' netcdf ]
/scratch2/NCEPDEV/climate/Jessica.Meixner/p6workflow/global-workflow/scripts/exgfs_atmos_nceppost.sh[65]: [: 'netcdf': unknown operator
3.385 + SUFFIX=.nemsio
loganl=/scratch2/NCEPDEV/climate/Jessica.Meixner/p6workflow/test04/COMROOT/test04/gfs.20130401/00/atmos/gfs.t00z.atmanl.nemsio


So we're still trying to get nemsio to the post and not netcdf.   I'm not sure if other parameter files needs to be changed or if we still need to have a seperate  "coupled" exgfs_atmos_nceppost.sh  -- if that was added when we added the additional 1 deg output, or if something else needs to be changed when converting to nemsio to netcdf. 

Any insight @jiandewang @JianKuang-NOAA @LydiaStefanova-NOAA ?

**Comment by JessicaMeixner-NOAA** [comment]
Okay.. I think one issue is in develop there are two variables: 
OUTPUT_FILE and OUTPUT_FILETYPES 
and 
OUTPUT_FILETYPES should be "''netcdf_parallel' 'netcdf_parallel' 
and used in model_configure 
while OUTPUT_FILE='netcdf' and used elsewhere.   I'll implement this and hopefully this will fix the issues we're currently having.

**Comment by LydiaStefanova-NOAA** [comment]
@JessicaMeixner-NOAA Also I noticed that the *flux.1p00* grib2 files are missing from the output - hopefully the change you are implementing will fix that too

**Comment by JessicaMeixner-NOAA** [comment]
@LydiaStefanova-NOAA can you please check: 
/scratch2/NCEPDEV/climate/Jessica.Meixner/p6workflow/test05/COMROOT/test05/gfs.20130401/00/atmos 
to see if the files look okay now for f000 and f006.  They at least have non-zero size.  We have gfs.t00z.sfluxgrbf006.grib2 but is there another surface flux file that's missing? 

I think the files are being produced now, but it carefully checking the log INLINE_POST gets set from true at the first to false somewhere in the script so, I'm going to attempt to track that down now.  Any advice/thoughts/help would be appreciated.

**Comment by LydiaStefanova-NOAA** [comment]
@JessicaMeixner-NOAA The pgrb2.0p25, pgrb2b.0p25, pgrb2.1p00, pgrb2b.1p00, and sfluxgrbf grib2 files are looking good. We should also have a flux.1p00 that's missing. In case this makes a difference: the flux.1p00 files are something that we had added for the coupled model (not part of the standalone output).

**Comment by JessicaMeixner-NOAA** [comment]
Okay.. so I found the variable that wasn't in the right config file to get called that was turning off inline post.  This was fixed for f012 post in the same COMDIR: 
/scratch2/NCEPDEV/climate/Jessica.Meixner/p6workflow/test05/COMROOT/test05/gfs.20130401/00/atmos
log file: /scratch2/NCEPDEV/climate/Jessica.Meixner/p6workflow/test05/COMROOT/test05/logs/2013040100/gfs.post.p_012.log 

Please let me know if these files look okay.   

Looking more into the *flux.1p00* files, the only mention I can find of these is in https://github.com/NOAA-EMC/global-workflow/blob/feature/coupled-crow/ush/inter_flux.sh which appears to be part of what was potentially added before just for the coupled atm post.  Can anyone (@LydiaStefanova-NOAA @binli2337 @jiandewang) confirm if this is true?

**Comment by JessicaMeixner-NOAA** [comment]
> @JessicaMeixner-NOAA The pgrb2.0p25, pgrb2b.0p25, pgrb2.1p00, pgrb2b.1p00, and sfluxgrbf grib2 files are looking good. We should also have a flux.1p00 that's missing. In case this makes a difference: the flux.1p00 files are something that we had added for the coupled model (not part of the standalone output).

Yes that does make a difference, how to add this back in needs to be figured out.  Otherwise it seems that the post is now working again.

**Comment by JessicaMeixner-NOAA** [comment]
@LydiaStefanova-NOAA does the availability of the netcdf files, for example: 
gfs.t00z.atmf012.nc  gfs.t00z.sfcf012.nc
negate the need for the extra 1 degree flux grib files?

**Comment by LydiaStefanova-NOAA** [comment]
@JessicaMeixner-NOAA Not really, because the netcdfs are high res. The 1p00 grib files are convenient because they are much smaller and easier/faster to upload/process.

**Comment by JessicaMeixner-NOAA** [comment]
Completed in PR#255
