### ISSUE TITLE
Add yaml to CI for high resolution tests to enable easy testing 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#2502]
### What new functionality do you need?

Add 2 yamls for C768 and C1152 forecast-only tests using HR3a/b ICs.  

This will not be a test for every PR per-say but will allow for easier testing. 

### What are the requirements for the new functionality?

yamls for C768 and C1152 S2SW forecast-only test cases 

### Acceptance Criteria

Others can run the CI tests

**Comment by JessicaMeixner-NOAA** [comment]
Okay apologies for perhaps a silly question, but where do the ICs for https://github.com/NOAA-EMC/global-workflow/blob/develop/ci/cases/weekly/C384_S2SWA.yaml come from?  (I'm using this as a template to create the C768/C1152). Thanks in advance for the pointer.

**Comment by WalterKolczynski-NOAA** [comment]
@JessicaMeixner-NOAA For forecast-only, it is going to be whatever subdirectory of `$BASE_CPLIC` is specified in [config.stage_ic](https://github.com/NOAA-EMC/global-workflow/blob/develop/parm/config/gfs/config.stage_ic).  For C384, that is the old P8c data; for C768 and C1152, that is HR3 data.

`$BASE_CPLIC` is set in [workflow/hosts](https://github.com/NOAA-EMC/global-workflow/tree/develop/workflow/hosts)/\<machine\>.yaml

**Comment by JessicaMeixner-NOAA** [comment]
Perfect!  Thanks @WalterKolczynski-NOAA !

**Comment by JessicaMeixner-NOAA** [comment]
I've build off the existing PR to update ufs-weather-model and added the two yaml files: 
ci/cases/weekly/C1152_S2SW.yaml
ci/cases/weekly/C768_S2SW.yaml
in a branch here: 
https://github.com/JessicaMeixner-NOAA/global-workflow/tree/feature/updateufs_20240419 

Just need to test before either combining with open PR or opening a new PR with just this change.
