### ISSUE TITLE
Update gempak version

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#2513]
### What new functionality do you need?

Need to update gempak version on Hera to `7.17.0` so `7.4.2` can be removed.

### What are the requirements for the new functionality?

Gempak on Hera runs when loading 7.17.0 version

### Acceptance Criteria

- [ ] Gempak runs loading 7.17.0 at runtime
- [ ] All products are produced as current (may not be bitwise compatible?)

### Dependencies
- [ ] https://github.com/NOAA-EMC/gfs-utils/issues/68

**Comment by aerorahul** [comment]
Also need to ensure gfs-utils builds with the new gempak

**Comment by WalterKolczynski-NOAA** [comment]
> Also need to ensure gfs-utils builds with the new gempak

Added an issue to gfs-utils.

**Comment by DavidHuber-NOAA** [comment]
FYI: at least a few of the gempak/7.4.2 executables do not work on Hera:

```console
> module load gempak/7.4.2
> xwp
xwp: error while loading shared libraries: libgfortran.so.3: cannot open shared object file: No such file or directory
> nagrib2
/apps/gempak/7.4.2/os/linux64/bin/nagrib2: error while loading shared libraries: libgfortran.so.3: cannot open shared object file: No such file or directory
```

The same executables do at least run under 7.17.0, though I have not tested their use.
