### ISSUE TITLE
update build_ufs.sh to include the "FV3_global_fv3_nest1" physics and use -DFASTER=ON in the compilation

### ISSUE THREAD

**Issue by guoqing-noaa** [NOAA-EMC/global-workflow#2520]
### What new functionality do you need?

1. include the "FV3_global_fv3_nest1" CCPP suite in the compilation
2. Be able to use the -DFASTER=ON compiling option

### What are the requirements for the new functionality?

These changes are required to reduce manual edits needed to run the "FV3_global_fv3_nest1" CCPP physics with the global nest experiments.

### Acceptance Criteria

The new changes work as expected.

**Comment by guoqing-noaa** [comment]
@SamuelTrahanNOAA Can you provide more information on the need of using `-DFASTER=ON`. Thanks!

**Comment by SamuelTrahanNOAA** [comment]
The 127-level nested C768 five-day forecast will not fit on Hera without -DFASTER=ON. Even 210 nodes for 8 hours isn't enough.

**Comment by SamuelTrahanNOAA** [comment]
Also, -DFASTER=ON should not be the default in the authoritative repository until all configurations have been tested that way. It should be enabled via a -f flag, similar to how -DDEBUG=ON is enabled by -d.

EDIT: I do think -DFASTER=ON should be the default for all configurations, but not as part of this request.

**Comment by WalterKolczynski-NOAA** [comment]
What does the `FASTER` flag do? Is it increasing the compiler optimization, or something else? Are results still bit-wise reproducible if we start using it?

**Comment by guoqing-noaa** [comment]
> What does the `FASTER` flag do? Is it increasing the compiler optimization, or something else? Are results still bit-wise reproducible if we start using it?

Per information from @SamuelTrahanNOAA , this flag will enable using higher but still safe optimization options to speed up the model run time for global nest runs. I would assume results will NOT be bit-wise reproducible. @SamuelTrahanNOAA correct me if I am wrong.

The linked PR will not change the default behavior but add an option "-f" if one wants to speed up the model run time.

**Comment by WalterKolczynski-NOAA** [comment]
Let me clarify quickly: I don't care if it is bit-wise reproducible with the executable without the flag, just whether it is bit-wise reproducible with itself if the forecast is re-run.

**Comment by guoqing-noaa** [comment]
> Let me clarify quickly: I don't care if it is bit-wise reproducible with the executable without the flag, just whether it is bit-wise reproducible with itself if the forecast is re-run.

Great question! @SamuelTrahanNOAA Could you provide more information on this topic? Thanks!

**Comment by WalterKolczynski-NOAA** [comment]
The attendant PR for this issue has been merged, but would still like to hear from @SamuelTrahanNOAA about whether results with FASTER are still bit-reproducible (with themselves, not with the lower optimization). @junwang-noaa may also know the answer. If so, we will look into making FASTER a standard and take the option back out.

**Comment by SamuelTrahanNOAA** [comment]
Results with `-DFASTER=ON` are bit-reproducible with themselves *within one site and build.* In other words, if you run the same executable on WCOSS2 fifty times with the same configuration, you'll get the same result each time.

Intel has a higher level of consistency that attempts to keep the same results across platforms; that is what FASTER disables. In theory, without FASTER, Hera and WCOSS2 might give the same result. In reality, OS and library differences often prevent that. This higher consistency mode disables many optimization options. Disabling those options slows down the model dramatically with some code on some processor types.

EDIT: I had a grammar error that changed the meaning of the last sentence. It is now corrected.

**Comment by SamuelTrahanNOAA** [comment]
The only place I can envision the currently-default compilation options being useful is on heterogeneous machines with the same OS and libraries across all nodes. That would be Jet and some cloud services.

An ideal solution would be to swap them.

1. Update ufs-weather-model so the options currently selected by FASTER=ON are now default (consistent results only with the same processor).
2. Add a new -DCONSISTENT=ON to ufs-weather-model's cmake which uses the currently-default "try to get the same results on all platforms" setting.

If people still want the slower options that are (sometimes) the same across multiple machines, they could then select it with -DCONSISTENT=ON.
