### ISSUE TITLE
COM_MED_RESTART_PREV is not defined

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#2528]
### What is wrong?

COM_MED_RESTART_PREV in ush/forecast_postdet.sh is not defined https://github.com/NOAA-EMC/global-workflow/blob/develop/ush/forecast_postdet.sh#L698.  This is only defined in scripts/exglobal_stage_ic.sh 

### What should have happened?

COM_MED_RESTART_PREV should be defined

### What machines are impacted?

All or N/A, Hera

### Steps to reproduce

Check out the develop branch, build, link and run the C48mx500_3DVarAOWCDA test, which have now work with updated GSI and GDAS app hashes updated.  I have a branch on hera with this but without some recent commits to develop that show that this test should work. 

### Additional information

This is required to turn back on C48mx500_3DVarAOWCDA

### Do you have a proposed solution?

Perhaps something like the definition in stage ic routine: 
RUN=${rCDUMP} YMD=${gPDY} HH=${gcyc} declare_from_tmpl COM_MED_RESTART_PREV:COM_MED_RESTART_TMP
is needed.

**Comment by JessicaMeixner-NOAA** [comment]
This appears to have fixed the issue: 

```
 git diff ush/forecast_postdet.sh
diff --git a/ush/forecast_postdet.sh b/ush/forecast_postdet.sh
index 1c0c50de..b3dc2672 100755
--- a/ush/forecast_postdet.sh
+++ b/ush/forecast_postdet.sh
@@ -695,6 +695,7 @@ CMEPS_postdet() {
       else
         restart_date="${current_cycle}"
       fi
+      RUN=${rCDUMP} YMD=${restart_date:0:8} HH=${restart_date:8:2} declare_from_tmpl COM_MED_RESTART_PREV:COM_MED_RESTART_TMPL
       cmeps_restart_file="${COM_MED_RESTART_PREV}/${restart_date:0:8}.${restart_date:8:2}0000.ufs.cpld.cpl.r.nc"
     fi
 

```

Tests are still running, but the forecast has at least started.

**Comment by JessicaMeixner-NOAA** [comment]
I can confirm that the gdasforecast job now runs successfully.  I'll make a PR with changes along with the changes to re-enable the C48mx500_3DVarAOWCDA test.

**Comment by aerorahul** [comment]
I experienced this yesterday when working on a bugfix.
The changes proposed should be in `JGLOBAL_FORECAST` and not in `forecast_postdet.sh`.

```diff
❯❯❯ git diff jobs/
diff --git i/jobs/JGLOBAL_FORECAST w/jobs/JGLOBAL_FORECAST
index 989f6975..6c4200dd 100755
--- i/jobs/JGLOBAL_FORECAST
+++ w/jobs/JGLOBAL_FORECAST
@@ -51,7 +51,8 @@ if [[ "${DO_OCN}" == "YES" ]]; then
   YMD="${PDY}" HH="${cyc}" declare_from_tmpl -rx COM_MED_RESTART COM_OCEAN_RESTART COM_OCEAN_INPUT \
     COM_OCEAN_HISTORY COM_OCEAN_ANALYSIS
   RUN="${rCDUMP}" YMD="${gPDY}" HH="${gcyc}" declare_from_tmpl -rx \
-    COM_OCEAN_RESTART_PREV:COM_OCEAN_RESTART_TMPL
+    COM_OCEAN_RESTART_PREV:COM_OCEAN_RESTART_TMPL \
+    COM_MED_RESTART_PREV:COM_MED_RESTART_TMPL
 fi

 if [[ "${DO_ICE}" == "YES" ]]; then
```

**Comment by JessicaMeixner-NOAA** [comment]
@aerorahul okay thank you for sharing the preferred fix.  Will you be making a  PR with this?

**Comment by aerorahul** [comment]
> @aerorahul okay thank you for sharing the preferred fix. Will you be making a PR with this?

Yes. I can, as soon as I get some time.
