### ISSUE TITLE
Add new orog and ugwd fix files for global nest

### ISSUE THREAD

**Issue by guoqing-noaa** [NOAA-EMC/global-workflow#2529]
### Target fix directory

orog
ugwd

### Type of change

- [ ] Update existing files
- [ ] Remove files
- [x] Add new files to existing directory
- [ ] Add new fix directory

### Any workflow changes needed?

Fix version + additional changes

### Related issues

https://github.com/NOAA-EMC/global-workflow/issues/2530

### Pickup location

/scratch2/BMC/wrfruc/Guoqing.Ge/fix/orog/global-nest.20240419
/scratch2/BMC/wrfruc/Guoqing.Ge/fix/ugwd/global-nest.20240419

### Size

8GB + 1.3 G

**Comment by guoqing-noaa** [comment]
Only the files under CXXX/CXX subdirectories are new fix files.

Those files directly under orog/global-nest.20240419 and ugwd/global-nest.20240419 (i.e. not under any further subdirectories) are copies of current GFS fix files. If disk space is a concern, we can do links instead of copies for those files.

**Comment by KateFriedman-NOAA** [comment]
@guoqing-noaa I have made the requested new folders under orog/ugwd and copied the provided CXXX files within. See here on Hera:
```
/scratch1/NCEPDEV/global/glopara/fix/orog/global-nest.20240419
/scratch1/NCEPDEV/global/glopara/fix/ugwd/global-nest.20240419
```

Let me know if this fulfills your request. Do you need copies of any of the other orog/ugwd files from their most recent timestamp copies? Let me know, thanks!

**Comment by guoqing-noaa** [comment]
@KateFriedman-NOAA Thanks a lot for your help!

Yes, we will need copies of any of the other org/ugwd files just above the CXXX subdirectories from their most recent timestamp copies. Either copies or links work for us.  Thanks!

**Comment by KateFriedman-NOAA** [comment]
> Yes, we will need copies of any of the other org/ugwd files just above the CXXX subdirectories from their most recent timestamp copies. Either copies or links work for us. Thanks!

@guoqing-noaa Okie dokie, please check the new folders again and let me know if I've now brought in everything you need in them from the prior `20231027` timestamps versions (same timestamp for both orog and ugwd). I retained the orog links to the raw files but copied everything else that wasn't a symlink.

**Comment by guoqing-noaa** [comment]
@KateFriedman-NOAA Thanks a lot! Yes, everything we need is copied! 👍

**Comment by KateFriedman-NOAA** [comment]
@guoqing-noaa Great, thanks for confirming! @WalterKolczynski-NOAA and I will now sync these new orog and ugwd global nest fix sets to the other supported platforms.

Please update the description of PR #2532 to also resolve this issue when that PR gets merged. Thanks!

**Comment by guoqing-noaa** [comment]
@KateFriedman-NOAA That's great! Thanks for syncing new fix files to other platforms. 
Just updated PR #2532

**Comment by KateFriedman-NOAA** [comment]
> Just updated PR https://github.com/NOAA-EMC/global-workflow/pull/2532

Great, thanks!

The new fix files have now been synced from Hera to AWS, Jet, and both WCOSS2s. Orion will get synced once it's back.

**Comment by guoqing-noaa** [comment]
> The new fix files have now been synced from Hera to AWS, Jet, and both WCOSS2s. Orion will get synced once it's back.

Great! Thanks!
