### ISSUE TITLE
Add the ascii namelist files the infrared cloud and aerosol detection software uses.

### ISSUE THREAD

**Issue by wx20jjung** [NOAA-EMC/global-workflow#2537]
### Target fix directory

gsi

### Type of change

- [ ] Update existing files
- [ ] Remove files
- [X] Add new files to existing directory
- [ ] Add new fix directory

### Any workflow changes needed?

No change needed

### Related issues

NOAA-EMC/GSI-fix #19

New files are now in the GSI-fix develop branch

### Pickup location

Hera:/scratch1/NCEPDEV/jcsda/Jim.Jung/noscrub/GSI-fix

### Size

less than 1MB total

**Comment by KateFriedman-NOAA** [comment]
@wx20jjung For clarification, you're requesting the three new fix files shown below get pulled into the current `fix/gsi/20240208` timestamp copy, correct? I took a look at the GSI-fix PR you referenced. Want to make sure it's just these three files. Thanks!

```
[role.glopara@hfe02 gsi]$ ll /scratch1/NCEPDEV/jcsda/Jim.Jung/noscrub/GSI-fix/*NL
-rwxr-xr-x 1 Jim.Jung jcsda 1088 Apr 25 16:08 /scratch1/NCEPDEV/jcsda/Jim.Jung/noscrub/GSI-fix/AIRS_CLDDET.NL
-rwxr-xr-x 1 Jim.Jung jcsda 2514 Apr 25 16:08 /scratch1/NCEPDEV/jcsda/Jim.Jung/noscrub/GSI-fix/CRIS_CLDDET.NL
-rwxr-xr-x 1 Jim.Jung jcsda 1627 Apr 25 16:08 /scratch1/NCEPDEV/jcsda/Jim.Jung/noscrub/GSI-fix/IASI_CLDDET.NL
```

**Comment by wx20jjung** [comment]
Kate,

Yes, my change is only to add these 3 files.

**Comment by KateFriedman-NOAA** [comment]
@WalterKolczynski-NOAA Please sync the `fix/gsi/20240208` folder onto Orion, thanks!

I have pulled the three requested new files into the `fix/gsi/20240208` timestamp on Hera. I have synced the update to AWS, Jet, and both WCOSS2s.

**Comment by RussTreadon-NOAA** [comment]
Thank you @KateFriedman-NOAA for adding these three new files to the existing `gsi/20240208` directory.  This greatly simplifies things on the GSI side.  We do not need to update `GSI_BINARY_SOURCE_DIR` in GSI `modulefiles/gsi_$machine.$compiler.lua`.  Yeah!

@wx20jjung , all we need to do is open a [GSI](https://github.com/NOAA-EMC/GSI) issue and PR to update the `fix` submodule to point at GSI-fix at [a801d5c](https://github.com/NOAA-EMC/GSI-fix/commit/a801d5cf07c3955e71258a0c8e9b074bb0f03fe4)

**Comment by KateFriedman-NOAA** [comment]
@RussTreadon-NOAA @wx20jjung Checking in on this issue. Is there anything else needed for this? I believe the fix file request has been completed so if you're ok with it I will close this issue as complete. Let me know, thanks!

**Comment by KateFriedman-NOAA** [comment]
Reopening, hit the wrong button, sorry!

**Comment by RussTreadon-NOAA** [comment]
I confirmed that the three `NL` files are present in the Hera, Orion/Hercules, and WCOSS2 `gsi/20240208/`.

@wx20jjung , can you check jet and s4?
```
  "jet")      FIX_DIR="/lfs4/HFIP/hfv3gfs/glopara/git/fv3gfs/fix" ;;
  "s4")       FIX_DIR="/data/prod/glopara/fix" ;;
```

**Comment by KateFriedman-NOAA** [comment]
We didn't update S4 (neither myself or Walter have access). If needed on S4 I believe we'll need @DavidHuber-NOAA to sync them over.

**Comment by wx20jjung** [comment]
Files exist on Jet.
Jim

**Comment by wx20jjung** [comment]
Files exist on S4
Jim

**Comment by KateFriedman-NOAA** [comment]
> Files exist on Jet.
> Files exist on S4

Excellent, thanks for checking and confirming @wx20jjung ! The requested fix files have been put and confirmed in place so I will now close this as complete.
