### ISSUE TITLE
GFSv16.3.20 - Annual CO2 update for 2025 and turn on assimilation of PlanetiQ GPS Radio Occultation (GPS-RO) data

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#2558]
### Description

The annual update to CO2 fix files, as well as updates to storm names for the 2025, 2026, and 2027 hurricane seasons.

Updated fix files will be provided by @Qingfu-Liu .

This issue is on hold until fall 2024 for the regular annual update time.

Document from @Qingfu-Liu : https://docs.google.com/document/d/1sWaex-8cfETPajB7DKfG-fN_TK5WK_et/edit#heading=h.gjdgxs

### Target version

v16.3.20

### Expected workflow changes

None

**Comment by KateFriedman-NOAA** [comment]
The new CO2 files have been pulled into the para install for `gfs.v16.3.20` by @DianeStokes-NCO . This issue will close when #2913 is completed.

**Comment by KateFriedman-NOAA** [comment]
> as well as updates to storm names for the 2025, 2026, and 2027 hurricane seasons.

@Qingfu-Liu were the storm name updates included in the files you provided recently?

**Comment by KateFriedman-NOAA** [comment]
Files copied into GFSv16 fix set on WCOSS2 for pickup by NCO:
```
WCOSS2 (PRIMARYSYS-D) fix_am> pwd
/lfs/h2/emc/global/save/emc.global/FIX/fix_nco_gfsv16.3.0/fix_am
WCOSS2 (PRIMARYSYS-D) fix_am> ll co2dat_4a/global_co2historicaldata_2023.txt co2dat_4a/global_co2historicaldata_2024.txt_proj_u co2dat_4a/global_co2historicaldata_2025.txt_proj fix_co2_proj/global_co2historicaldata_2025.txt fix_co2_update/global_co2historicaldata_2024.txt
-rw-r--r-- 1 emc.global global 24484 Oct  7 20:55 co2dat_4a/global_co2historicaldata_2023.txt
-rw-r--r-- 1 emc.global global 24484 Oct  7 20:55 co2dat_4a/global_co2historicaldata_2024.txt_proj_u
-rw-r--r-- 1 emc.global global 24484 Oct  7 20:55 co2dat_4a/global_co2historicaldata_2025.txt_proj
-rw-r--r-- 1 emc.global global 24484 Oct  7 20:55 fix_co2_proj/global_co2historicaldata_2025.txt
-rw-r--r-- 1 emc.global global 24484 Oct  7 20:55 fix_co2_update/global_co2historicaldata_2024.txt
```

**Comment by KateFriedman-NOAA** [comment]
Rsync'd the new fix files to the developmental fix sets on WCOSS2 and then to Hera and Jet:
```
+ cd /lfs/h2/emc/global/noscrub/emc.global/FIX/fix/am/
+ rsync -azv 20220805 role.glopara@dtn-hera.fairmont.rdhpcs.noaa.gov:/scratch1/NCEPDEV/global/glopara/fix/am/
sending incremental file list
20220805/co2dat_4a/
20220805/co2dat_4a/global_co2historicaldata_2023.txt
20220805/co2dat_4a/global_co2historicaldata_2024.txt_proj_u
20220805/co2dat_4a/global_co2historicaldata_2025.txt_proj
20220805/fix_co2_proj/
20220805/fix_co2_proj/global_co2historicaldata_2025.txt
20220805/fix_co2_update/
20220805/fix_co2_update/global_co2historicaldata_2024.txt

sent 57,889 bytes  received 134 bytes  6,826.24 bytes/sec
total size is 6,912,953,183  speedup is 119,141.60
```

Also synced to AWS:
```
[role.glopara@hfe02 AWS]$ sh copy_fix_aws_bucket.sh am/20220805
+ aws s3 sync am/20220805/ s3://noaa-nws-global-pds/fix/am/20220805/
upload: am/20220805/co2dat_4a/global_co2historicaldata_2023.txt to s3://noaa-nws-global-pds/fix/am/20220805/co2dat_4a/global_co2historicaldata_2023.txt
upload: am/20220805/co2dat_4a/global_co2historicaldata_2025.txt_proj to s3://noaa-nws-global-pds/fix/am/20220805/co2dat_4a/global_co2historicaldata_2025.txt_proj
upload: am/20220805/co2dat_4a/global_co2historicaldata_2024.txt_proj_u to s3://noaa-nws-global-pds/fix/am/20220805/co2dat_4a/global_co2historicaldata_2024.txt_proj_u
upload: am/20220805/fix_co2_update/global_co2historicaldata_2024.txt to s3://noaa-nws-global-pds/fix/am/20220805/fix_co2_update/global_co2historicaldata_2024.txt
upload: am/20220805/fix_co2_proj/global_co2historicaldata_2025.txt to s3://noaa-nws-global-pds/fix/am/20220805/fix_co2_proj/global_co2historicaldata_2025.txt
```
@WalterKolczynski-NOAA please sync the `fix/am/20220805` subset to MSU, thanks!

**Comment by Qingfu-Liu** [comment]
Hi Kate,
   No storm name updated for 2024 hurricane seasons (so no new fixed files
for 2024 hurricane season), I have not checked the 2025 hurricane season
yet. We will wait until March 2025 for the hurricane name updates in case
the hurricane name changes between now (Oct. 2024) and March 2025.
Qingfu

**Comment by KateFriedman-NOAA** [comment]
@Qingfu-Liu Understood, thanks for that info!

**Comment by KateFriedman-NOAA** [comment]
From the October 25th RFC memo:
```
RFC 13371 - On WCOSS2, install 2025 carbon dioxide (CO2) fix file updates for
several model packages. The GEFS, NAM, SREF, HIRESW, HMON, HAFS,
CFS, and CFS_HUR models rely on the historical/projected global CO2
abundance data in their forecasts. To be implemented on October 29 from 1145Z
to 1930Z. The GFS uses CO2 but is not being updated at this time. A GFS
update is coming before the end of the year which will include the code to read
the 2025 CO2 input.
```

**Comment by EricSinsky-NOAA** [comment]
@KateFriedman-NOAA Can you also add the new CO2 files to the following directory on WCOSS2? `/lfs/h2/emc/global/save/emc.global/FIX/fix_nco_gfsv15/fix_am/`

This fix directory is copied during the production GEFSv12 build process.

**Comment by KateFriedman-NOAA** [comment]
@EricSinsky-NOAA Certainly! Done, copied into the `fix_nco_gfsv15` sets on both sides of WCOSS2:
```
WCOSS2 (BACKUPSYS-C) fix_am> ll co2dat_4a/global_co2historicaldata_2023.txt co2dat_4a/global_co2historicaldata_2024.txt_proj_u co2dat_4a/global_co2historicaldata_2025.txt_proj fix_co2_proj/global_co2historicaldata_2025.txt fix_co2_update/global_co2historicaldata_2024.txt                                                                       
-rw-r--r-- 1 emc.global global 24484 Oct  7 20:55 co2dat_4a/global_co2historicaldata_2023.txt
-rw-r--r-- 1 emc.global global 24484 Oct  7 20:55 co2dat_4a/global_co2historicaldata_2024.txt_proj_u
-rw-r--r-- 1 emc.global global 24484 Oct  7 20:55 co2dat_4a/global_co2historicaldata_2025.txt_proj
-rw-r--r-- 1 emc.global global 24484 Oct  7 20:55 fix_co2_proj/global_co2historicaldata_2025.txt
-rw-r--r-- 1 emc.global global 24484 Oct  7 20:55 fix_co2_update/global_co2historicaldata_2024.txt
```

**Comment by EricSinsky-NOAA** [comment]
> @EricSinsky-NOAA Certainly! Done, copied into the `fix_nco_gfsv15` sets on both sides of WCOSS2:
> 
> ```
> WCOSS2 (BACKUPSYS-C) fix_am> ll co2dat_4a/global_co2historicaldata_2023.txt co2dat_4a/global_co2historicaldata_2024.txt_proj_u co2dat_4a/global_co2historicaldata_2025.txt_proj fix_co2_proj/global_co2historicaldata_2025.txt fix_co2_update/global_co2historicaldata_2024.txt                                                                       
> -rw-r--r-- 1 emc.global global 24484 Oct  7 20:55 co2dat_4a/global_co2historicaldata_2023.txt
> -rw-r--r-- 1 emc.global global 24484 Oct  7 20:55 co2dat_4a/global_co2historicaldata_2024.txt_proj_u
> -rw-r--r-- 1 emc.global global 24484 Oct  7 20:55 co2dat_4a/global_co2historicaldata_2025.txt_proj
> -rw-r--r-- 1 emc.global global 24484 Oct  7 20:55 fix_co2_proj/global_co2historicaldata_2025.txt
> -rw-r--r-- 1 emc.global global 24484 Oct  7 20:55 fix_co2_update/global_co2historicaldata_2024.txt
> ```

Thank you, @KateFriedman-NOAA. All looks good.

**Comment by KateFriedman-NOAA** [comment]
NCO pulled the updated fix files into the GFSv16.3.20 install. This issue will be resolved alongside issue #2913.

**Comment by KateFriedman-NOAA** [comment]
From the 12/6/24 RFC memo:
```
RFC 13485 - On WCOSS2, upgrade the GFS to v16.3.20. This includes the
following changes:
● install 2025 carbon dioxide (CO2) fix file updates before the start of the
new year;
● turn on assimilation of PlanetiQ GPS Radio Occultation (GPS-RO) data;
● load the cmdaccel module at the start of wave point postprocessor jobs to
stabilize runtime.
To be implemented on December 9 from 1330Z to 2000Z.
```

**Comment by KateFriedman-NOAA** [comment]
This operational update is complete, it has been tagged and released to users. Closing as complete.
