### ISSUE TITLE
tocgrib2 fails in AWIPS job

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#2566]
### What is wrong?

The awips job uses `tocgrib2` to add the WMO header to grib files. The executable is currently failing due to missing records.

### What should have happened?

`tocgrib2` should run successfully, allowing the AWIPS job to do the same and produce the associated products.

When this is fixed, `DO_AWIPS` should be able to be turned for the `C96_atm3DVar_extended` test and the test still pass on WCOSS.

### What machines are impacted?

WCOSS2

### Steps to reproduce

1. Check out and build develop on WCOSS
2. Create an experiment with AWIPS on
3. Observe (almost) all of the AWIPS jobs (`gfsawips_20km_1p0deg_*`) failing in the first full cycle

### Additional information

The records tocgrib2 is having issue with are the four convective precip fields (`CRAIN`, `CFRZR`, `CICEP`, `CSNOW`).
```
*******************************************************************************
 Start new record no. =  254
 DESC= CRAIN    Surface                                                        
 WMOHEAD=ZMNB98 KWBC
 GRIB2 DISCIPLINE= -1
 Section 1= -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999
 PDT 4. 8 = 1 192 2 0 96 0 0 1 0 1 0 0 255 0 0 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999
 GETGB2P: ERROR REQUEST NOT FOUND

*******************************************************************************
 Start new record no. =  255
 DESC= CFRZR    Surface                                                        
 WMOHEAD=ZMNB98 KWBC
 GRIB2 DISCIPLINE= -1
 Section 1= -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999
 PDT 4. 8 = 1 193 2 0 96 0 0 1 0 1 0 0 255 0 0 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999
 GETGB2P: ERROR REQUEST NOT FOUND

*******************************************************************************
 Start new record no. =  256
 DESC= CICEP    Surface                                                        
 WMOHEAD=ZMNB98 KWBC
 GRIB2 DISCIPLINE= -1
 Section 1= -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999
 PDT 4. 8 = 1 194 2 0 96 0 0 1 0 1 0 0 255 0 0 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999
 GETGB2P: ERROR REQUEST NOT FOUND

*******************************************************************************
 Start new record no. =  257
 DESC= CSNOW    Surface                                                        
 WMOHEAD=ZMNB98 KWBC
 GRIB2 DISCIPLINE= -1
 Section 1= -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999
 PDT 4. 8 = 1 195 2 0 96 0 0 1 0 1 0 0 255 0 0 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999
 GETGB2P: ERROR REQUEST NOT FOUND


 ******** RECAP OF THIS EXECUTION ********
     READ     257 INDIVIDUAL IDS
     WROTE    253 BULLETINS OUT FOR TRANSMISSION


 BULLETINS MISSING =  4
```

The grib file being supplied to `tocgrib2` does have those fields:
```
WCOSS2 (BACKUPSYS) awips_20km_1p0deg.119475> $WGRIB2 awps_file_f003_conus | egrep '(CRAIN|CFRZR|CICEP|CSNOW)'
172:10840359:d=2021122100:CSNOW:surface:3 hour fcst:
173:10843301:d=2021122100:CICEP:surface:3 hour fcst:
174:10843489:d=2021122100:CFRZR:surface:3 hour fcst:
175:10843823:d=2021122100:CRAIN:surface:3 hour fcst:
```

### Do you have a proposed solution?

I wonder if something needs to be updated in the [20km WMO parm files](https://github.com/NOAA-EMC/global-workflow/tree/develop/parm/wmo).

**Comment by GwenChen-NOAA** [comment]
@WalterKolczynski-NOAA, could you provide the experiment setup to run the `C96_atm3DVar_extended` test? For example,

 ./setup_expt.py gfs cycled --app ATM --start cold --resdetatmos 96 --resensatmos 96 --nens 80 --gfs_cyc 4 --idate 2021122018 --edate 2021122018 --comroot $COMROOT --expdir $EXPDIR --pslot test

**Comment by edwardhartnett** [comment]
@WalterKolczynski-NOAA can you provide on of the GRIB2 files which are not working on hera somewhere and let me know where it is?

We will then build a test for it and make sure it works.

**Comment by GwenChen-NOAA** [comment]
> @WalterKolczynski-NOAA can you provide on of the GRIB2 files which are not working on hera somewhere and let me know where it is?
> 
> We will then build a test for it and make sure it works.

@edwardhartnett, you can find some sample input files (gfs.tCCz.pgrb2.0p25.fFFF and gfs.tCCz.pgrb2b.0p25.fFFF) on WCOSS2 at /lfs/h2/emc/vpppg/noscrub/Lichuan.Chen/gwDev/COMROOT/test/gfs.20160701/00/products/atmos/grib2/0p25.  The CRAIN, CFRZR, CICEP, and CSNOW fields are generated for forecast lead time >= 003. The JGFS_ATMOS_AWIPS_20KM_1P0DEG job ran successfully for f000 and generated AWIPS products. The f000 awips files do not output the CRAIN, CFRZR, CICEP, and CSNOW fields.
