### ISSUE TITLE
detect_machine.sh identifies Frontera as Hera

### ISSUE THREAD

**Issue by benjamin-cash** [NOAA-EMC/global-workflow#2570]
### What is wrong?

The $SCRATCH system on Frontera uses /scratch1, as (apparently) does Hera. -d /scratch1 is not sufficient to uniquely identify Hera, and as a result Frontera is incorrectly identified as Hera by detect_machine.sh

### What should have happened?

When the script failed to identify Frontera from the case $(hostname -f) check, it should have reported MACHINE_ID as UNKNOWN. Instead, because Frontera shares a naming convention with Hera, the script identified the machine as Hera.

### What machines are impacted?

All or N/A

### Steps to reproduce

1. Log in on any system that uses /scratch1 for its scratch directory
2. ./detect_machine.sh

### Additional information

This step is only reached because login[1-4].frontera.tacc.utexas.edu is not checked for in the list of hostnames, which is trivial to add and I will do so. But as g-w is used on more machines the directory check will become increasingly less reliable -  directory paths do not tend towards the creative. ;)

**Comment by aerorahul** [comment]
Thanks @benjamin-cash 
The `detect_machine.sh` here is a copy from the ufs-weather-model. The ufs-weather-model retains the authoritative copy of this script [here](https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/detect_machine.sh).
Could you please open an issue in the ufs-weather-model?  We can open an issue in the global-workflow to bring that copy in when it is updated there.

**Comment by benjamin-cash** [comment]
@aerorahul - Thanks for untangling the provenance of that for me. It's a simple fix, so I will go ahead and create a pull request on ufs-weather-model to add in Frontera.
