### ISSUE TITLE
MOM_override file needed in mom6 100 directories 

### ISSUE THREAD

**Issue by NeilBarton-NOAA** [NOAA-EMC/global-workflow#2578]
### Target fix directory

mom6

### Type of change

- [ ] Update existing files
- [ ] Remove files
- [X] Add new files to existing directory
- [ ] Add new fix directory

### Any workflow changes needed?

Fix version only

### Related issues

no related issue. currently working on a 1 degree SFS PR

### Pickup location

hera:/scratch1/NCEPDEV/global/glopara/fix/mom6/20231219/025/MOM_override

### Size

1

**Comment by KateFriedman-NOAA** [comment]
@NeilBarton-NOAA Please clarify the request here. The pickup location is an existing file in the fix set. Did you mean to provide a different pick location? Let us know, thanks!

**Comment by NeilBarton-NOAA** [comment]
@KateFriedman-NOAA 

This file is needed in **100** directory
hera:/scratch1/NCEPDEV/global/glopara/fix/mom6/20231219/100/MOM_override

you can use the same file that is in **025** directory 
hera:/scratch1/NCEPDEV/global/glopara/fix/mom6/20231219/025/MOM_override

**Comment by KateFriedman-NOAA** [comment]
@NeilBarton-NOAA Done, see on Hera:
```
[role.glopara@hfe11 20231219]$ pwd
/scratch1/NCEPDEV/global/glopara/fix/mom6/20231219
[role.glopara@hfe11 20240416]$ ll */MOM_override
-rw-r--r-- 1 role.glopara global 113 May 15  2020 025/MOM_override
-rw-r--r-- 1 role.glopara global 113 May 15  2020 050/MOM_override
-rw-r--r-- 1 role.glopara global 113 Jul 14  2022 500/MOM_override
[role.glopara@hfe11 20231219]$ rsync -azv 025/MOM_override 100/
sending incremental file list
MOM_override

sent 194 bytes  received 35 bytes  458.00 bytes/sec
total size is 113  speedup is 0.49
[role.glopara@hfe11 20231219]$ ll */MOM_override
-rw-r--r-- 1 role.glopara global 113 May 15  2020 025/MOM_override
-rw-r--r-- 1 role.glopara global 113 May 15  2020 050/MOM_override
-rw-r--r-- 1 role.glopara global 113 May 15  2020 100/MOM_override
-rw-r--r-- 1 role.glopara global 113 Jul 14  2022 500/MOM_override
```
Note, I did the same copy within the newer `20240416` mom6 fix timestamp. We have not yet moved to use this newer timestamp.

Let me know I have fulfilled the request for this issue and if so, we will proceed with syncing the update to the other supported platform fix sets. Thanks!

**Comment by NeilBarton-NOAA** [comment]
@KateFriedman-NOAA 

I tested a 100 case on hera and it passed.

**Comment by KateFriedman-NOAA** [comment]
@NeilBarton-NOAA Great! I have synced the update to both WCOSS2s, Jet, and AWS. @WalterKolczynski-NOAA please sync the fix (two latest mom6 timestamps) to Orion, thanks!

**Comment by KateFriedman-NOAA** [comment]
Syncs completed. Closing as complete.
