### ISSUE TITLE
Implementing global-workflow on AWS

### ISSUE THREAD

**Issue by weihuang-jedi** [NOAA-EMC/global-workflow#2583]
### What new functionality do you need?

Implementing global-workflow on AWS

### What are the requirements for the new functionality?

1. Create  cluster(s) on parallelworks
2. Compile on AWS
3. Run on AWS

### Acceptance Criteria

Been able to compile and run global-workflow on AWS

**Comment by HenryRWinterbottom** [comment]
@weihuang-jedi From what I recall from a prior G-W team meeting, you have accomplished the following:

- Created a parallel cluster for AWS;
- Compiled for the respective AWS parallel cluster;
- Ran an experiment on the respective AWS parallel cluster.

What remains to be addressed for this issue?

**Comment by weihuang-jedi** [comment]
This is resolved with PR #2711.
