### ISSUE TITLE
Add wave resolution flexibility/support

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#259]
Add support for different wave grids for lower resolutions.

**Comment by JessicaMeixner-NOAA** [comment]
For the develop branch, my recommendation would be for: 

C768 -- Use the v16 operational grid set-up 
C384 -- Use the GEFSv12 operational multi grid set-up ~ 1/4deg resolution (For coupled-crow branch use what is set-up for coupled -- single grid 1/2 deg) 
C192 -- Use 1/2 degree, 1 grid 
C96 -- Use 1 deg, 1 grid
C48 -- Use 2 deg, 1 grid 

Everything but the 2 deg grid already have grids that exist, the fix files just need to be copied over for them to be in the fix directory.    Time steps for the wave model and coupling time step should also be checked to make sure they are consistent.   

The variables here: https://github.com/NOAA-EMC/global-workflow/blob/develop/parm/config/config.wave#L24-L26 need to then be resolution dependent and based on atm resolution, choose a different wave grid set.  Also, we might not want all of the output wave grids for the different resolutions specified here: https://github.com/NOAA-EMC/global-workflow/blob/develop/parm/config/config.wave#L41-L44

**Comment by arunchawla-NOAA** [comment]
@JessicaMeixner-NOAA and @BrianCurtis-NOAA is there a simple way to switch between different resolution grids in the global workflow?

**Comment by arunchawla-NOAA** [comment]
this requires a smart way to identify the grids and the way ww3_multi.inp is set up.

**Comment by JessicaMeixner-NOAA** [comment]
> this requires a smart way to identify the grids and the way ww3_multi.inp is set up.

This part of it should already be there but you'd have to set up all the parameters correctly.  So waveGRD, waveGRDN, and waveGRDG would all have to be set for a different resolution set.  So it's not completely automated but some what automated... It probably could be a lot simpler but?  Right now either in the develop branch or in feature/coupled-crow there's not a way to set which grids the wave model is using based on atm or other model resolution.  In feature/coupled-crow you'd likely have different case files for each resolution and so you could just specify them there.  Right now in feature/coupled-crow the OCN/ICE are by default the same resolutions, but you choose both that and the atm resolution in the case file.  I don't know if @BrianCurtis-NOAA has changed any of that though for the work he's doing

**Comment by arunchawla-NOAA** [comment]
@BrianCurtis-NOAA @WalterKolczynski-NOAA and @KateFriedman-NOAA can we review with @JessicaMeixner-NOAA how easy it is right now to set up multiple different configurations for the wave model in the global workflow? How easy is it to do this for the ocean and ice?

**Comment by BrianCurtis-NOAA** [comment]
I haven't changed anything yet in coupled-crow. Choosing a resolution is all in the case files for coupled-crow.

**Comment by JessicaMeixner-NOAA** [comment]
Recent updates to the global-workflow including: https://github.com/NOAA-EMC/global-workflow/pull/1608 and the draft https://github.com/NOAA-EMC/global-workflow/pull/1653  adds a lot more flexibility and could be enough to close this issue.  By changing the wave grid in config.base we have all other settings set based on that wave grid in config.wave which means a user just has to change a single variable instead of multiple.  I would consider this issue at this time complete, but f there are other needed features @aerorahul @WalterKolczynski-NOAA let me know and we can address that before closing this issue as well.

**Comment by JessicaMeixner-NOAA** [comment]
@aerorahul are there any other needed features required to close this issue?

**Comment by KateFriedman-NOAA** [comment]
We're good. Closing!
