### ISSUE TITLE
Missing CICE analysis restart for the WCDA ci test

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/global-workflow#2590]
### Target fix directory

NEW

### Type of change

- [ ] Update existing files
- [ ] Remove files
- [X] Add new files to existing directory
- [ ] Add new fix directory

### Any workflow changes needed?

No change needed

### Related issues

[NOAA-EMC/global-workflow/pull/2584](https://github.com/NOAA-EMC/global-workflow/pull/2584)

No place to write comments, so using this space:
We need to create a symlink to this file
```
/scratch1/NCEPDEV/global/glopara/data/ICSDIR/C48mx500/gdas.20210324/06/model_data/ice/restart/20210324.090000.cice_model.res.nc
```

with the target name:
```
/scratch1/NCEPDEV/global/glopara/data/ICSDIR/C48mx500/gdas.20210324/12/analysis/ice/restart/20210324.090000.cice_model_anl.res.nc
```

### Pickup location

/scratch1/NCEPDEV/global/glopara/data/ICSDIR/C48mx500/gdas.20210324/06/model_data/ice/restart/20210324.090000.cice_model.res.nc

### Size

3.1M

**Comment by WalterKolczynski-NOAA** [comment]
Why is the same file needed in both the 06z and 12z directories?

**Comment by guillaumevernieres** [comment]
> Why is the same file needed in both the 06z and 12z directories?

@WalterKolczynski-NOAA , it corresponds to an analysis with a zero increment. It sounds silly, but the choice that was made was to impose the model to start the 1/2 cycle fcst from an analysis. If the model can do `iau` that means that an increment needs to be staged, if the model cannot do iau, the case for CICE, an analysis restart needs to be provided. 

It probably should just be a sym link in glopara.

**Comment by WalterKolczynski-NOAA** [comment]
Link created on all the tier-1 machines.
