### ISSUE TITLE
Connect Multiselect Parameter tool to run job parameter interface in Jenkins Controller

### ISSUE THREAD

**Issue by TerrenceMcGuinness-NOAA** [NOAA-EMC/global-workflow#2599]
### What new functionality do you need?

The ability of users with access to the Jenkins Controller  to have a more fine grain tunable interface for specific features such as #1980 (Restarting #Experiment without Rebuilding) and #1969 (Build Only) for relaunching a CI test on a PR.

### What are the requirements for the new functionality?

The [Multi Parameter Plugin](https://plugins.jenkins.io/multiselect-parameter/) can have value parameters selected and realized in the Jenkins pipeline.

### Acceptance Criteria

Any selectable option that presented to the user when a PR is relaunched _from parameters_ are realized in the re-run.

### Suggest a solution

- We can start with an option to not build when issuing a re-run.
- Add an option to find tune which experiments to re-run.
- Add an option to resume (not overwrite) any experiment on re-run.

**Comment by TerrenceMcGuinness-NOAA** [comment]
The Jenkins Pipeline is set up for rebuiding With Parameters for Node Names: 


![Image](https://github.com/user-attachments/assets/13bdbb52-4ff5-477c-ab6c-34b6ba5c6455)

A Remote API call was made from Hera what is  equivalent of selecting one of these boxes for fine-grain control and a job was launched successfully from the linux prompt:

Example Prototype Script:

```
#!/usr/bin/env bash
  
set -x

controller_url="https://jenkins.epic.oarcloud.noaa.gov"
api_token=112991ee61d29bdf912525a4815a7cc97e
project_name=global-workflow
job_name=EMC-Pipelines
username=terry.mcguinness
pr_number=PR-292
node=Hera-EMC
machine_name=hera

build_url="${controller_url}/job/${project_name}/job/${job_name}/job/${pr_number}/buildWithParameters?delay=0sec"

echo ""
echo $build_url
echo ""

curl -X POST ${build_url} --user $username:$api_token ${build_url} --data-urlencode "Node=${node}" --data-urlencode "machine=${machine_name}"
```

Successfully launched job from Hera prompt:

```
Terry.McGuinness (hfe05) utils (ci_launch_parameters) $ ./launch_job.sh 
+ controller_url=https://jenkins.epic.oarcloud.noaa.gov
+ api_token=112991ee61d29bdf912525a4815a7cc97e
+ project_name=global-workflow
+ job_name=EMC-Pipelines
+ username=terry.mcguinness
+ pr_number=PR-292
+ node=Hera-EMC
+ machine_name=hera
+ build_url='https://jenkins.epic.oarcloud.noaa.gov/job/global-workflow/job/EMC-Pipelines/job/PR-292/buildWithParameters?delay=0sec'
+ echo ''

+ echo 'https://jenkins.epic.oarcloud.noaa.gov/job/global-workflow/job/EMC-Pipelines/job/PR-292/buildWithParameters?delay=0sec'
https://jenkins.epic.oarcloud.noaa.gov/job/global-workflow/job/EMC-Pipelines/job/PR-292/buildWithParameters?delay=0sec
+ echo ''

+ curl -X POST 'https://jenkins.epic.oarcloud.noaa.gov/job/global-workflow/job/EMC-Pipelines/job/PR-292/buildWithParameters?delay=0sec' --user terry.mcguinness:112991ee61d29bdf912525a4815a7cc97e 'https://jenkins.epic.oarcloud.noaa.gov/job/global-workflow/job/EMC-Pipelines/job/PR-292/buildWithParameters?delay=0sec' --data-urlencode Node=Hera-EMC --data-urlencode machine=hera
```

**Comment by WalterKolczynski-NOAA** [comment]
Closing as completed
