### ISSUE TITLE
port reg2grb2 to cmake

### ISSUE THREAD

**Issue by BrianCurtis-NOAA** [NOAA-EMC/global-workflow#263]
Once the global-workflow is done porting to CMake and that work is copied over to coupled-crow, the reg2grb2 utility will need to be ported to CMake.

**Comment by BrianCurtis-NOAA** [comment]
Once the CMake work for develop branch is done, we can move reg2grb2 to develop

**Comment by JessicaMeixner-NOAA** [comment]
Is there a reason to move reg2grb2 to develop before the whole feature/coupled-crow gets moved to develop? Is that going to happen in stages?

**Comment by BrianCurtis-NOAA** [comment]
I wasn't sure when/if it was moving to develop. Yes it can wait for the whole thing going. Thanks!
