### ISSUE TITLE
Convert setup scripts to python 3

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#265]
Setup scripts are currently python 2, which is at end of life. Convert setup scripts to python 3.

Scripts under ush/rocoto.

**Comment by BrianCurtis-NOAA** [comment]
i can assist/review PR if needed.

**Comment by WalterKolczynski-NOAA** [comment]
@BrianCurtis-NOAA I'm perfectly happy to let you do it if you are willing.

**Comment by BrianCurtis-NOAA** [comment]
Sure. I can work on it here and there.

**Comment by BrianCurtis-NOAA** [comment]
I think we're currently using python 3.8 on machines that aren't WCOSS? I'll gear towards that unless told otherwise.

**Comment by KateFriedman-NOAA** [comment]
WCOSS: python/3.6.3
Hera: intelpython/3.6.8
Orion: python/3.7.5
Jet: intelpython/3.6.5

Thanks @BrianCurtis-NOAA !

**Comment by BrianCurtis-NOAA** [comment]
```
Python 3.6.8 |Intel Corporation| (default, Apr 12 2019, 17:34:58) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
Intel(R) Distribution for Python is brought to you by Intel Corporation.
Please check out: https://software.intel.com/en-us/python-distribution
>>> import numpy as np
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/apps/intel/intelpython3/lib/python3.6/site-packages/numpy/__init__.py", line 156, in <module>
    from . import _distributor_init
  File "/apps/intel/intelpython3/lib/python3.6/site-packages/numpy/_distributor_init.py", line 34, in <module>
    from . import _mklinit
ImportError: libmkl_rt.so: cannot open shared object file: No such file or directory
```
I'm assuming this is a numpy build issue on the intel python distribution on HERA? How/where do I go about resolving this?

**Comment by BrianCurtis-NOAA** [comment]
I've sent an e-mail off to the helpdesk for now.

**Comment by BrianCurtis-NOAA** [comment]
> The system group does not formally support the python related libraries or utilities. However I will bring the issue to the group meeting next Monday. At the same time, you can check the user managed software /contrib/anaconda or /contrib/miniconda3, and see whether those can solve your problem.

**Comment by WalterKolczynski-NOAA** [comment]
I'll make sure Kate and I also bring it up in the next HUG meeting. Commonly used packages like numpy need to be supported by RDHPCS.

**Comment by BrianCurtis-NOAA** [comment]
Seems `File "/scratch1/NCEPDEV/global/glopara/svn/nceplibs/produtil/trunk/ush/produtil/fileop.py"` needs to be updated as well. What repo is this file stored in? Should I ask a specific group to edit it?

```
./rocoto_viewer.py -d /scratch1/NCEPDEV/stmp2/Brian.Curtis/expdir/gwtest/gwtest.db -w /scratch1/NCEPDEV/stmp2/Brian.Curtis/expdir/gwtest/gwtest.xml 
Traceback (most recent call last):
  File "./rocoto_viewer.py", line 2374, in <module>
    from produtil.fileop import remove_file
  File "/scratch1/NCEPDEV/global/glopara/svn/nceplibs/produtil/trunk/ush/produtil/fileop.py", line 345
    tempprefix=None,permmask=002,removefailed=True,
                               ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
```

**Comment by WalterKolczynski-NOAA** [comment]
prod_util has been added to hpc-stack, though as of right now we would also need to get NCO to update for production. I don't know if the plan is for us to take that over with hpc-stack or not. @arunchawla-NOAA may know more.

**Comment by BrianCurtis-NOAA** [comment]
@WalterKolczynski-NOAA with the move of prod_util to hpc-stack, where would I find the new location of fileop.py?

**Comment by WalterKolczynski-NOAA** [comment]
I don't believe the scripts were included, just the executables.

That said, fileop.py is not a part of any of the official prod_util installations even on WCOSS as far as I can tell, so I don't know where that file actually comes from. Just switch to using native python commands.

**Comment by aerorahul** [comment]
@BrianCurtis-NOAA 
What is the status of this work?
We need a time estimate on when this will be complete.

**Comment by BrianCurtis-NOAA** [comment]
@KateFriedman-NOAA @aerorahul I merged from develop and made any additional changes to get it working with py3. I will get a draft PR out in a minute.

There is one issue (maybe similar issue on other systems): the hera intelpython distribution has numpy but numpy is broken in that install, I don't know if that is something we can get fixed easily. I worked around it using a miniconda installation from the UFS for now.

The rocoto viewer is doing some extra magic that doesn't work in my testing, yet. I am going to work on that next.

Since I do not use the global workflow that often I am hoping you can test the PR branch in a number of ways. I'm assuming there are sections of code that are only triggered on occasion, and we may catch some bugs in those parts. If there are issues please bring them up in the PR so I can get them fixed ASAP.

I've tested using the setup expt and setup workflows for fcst and non fcst scripts and they generate the files and have started using rocoto, one of them needed it twice so there's some investigating to do there. This is going to be a draft PR for this reason.

I hope that with the help on the testing front this can be done soon. Apologies for the delay thus far.

**Comment by aerorahul** [comment]
@BrianCurtis-NOAA 

UPDATED:

The `intelpython/3.6.8` module does work.  It needs the `intel` module loaded.

As a test, can you create the xml with python2 version of the scripts and compare it with the python3 version of the setup scripts?
They should be largely identical.

**Comment by WalterKolczynski-NOAA** [comment]
> 
> The rocoto viewer is doing some extra magic that doesn't work in my testing, yet. I am going to work on that next.
> 
I've already done the conversion necessary for rocoto viewer. See NOAA-EMC/CROW/pull/16. It could use more testing though.

**Comment by BrianCurtis-NOAA** [comment]
@aerorahul Yes, i wanted to make sure they ran without error and at least started with rocoto. Next step is comparisons between develop output and this output as well as meeting PEP8 standards.

**Comment by BrianCurtis-NOAA** [comment]
> 
> 
> > The rocoto viewer is doing some extra magic that doesn't work in my testing, yet. I am going to work on that next.
> 
> I've already done the conversion necessary for rocoto viewer. See [NOAA-EMC/CROW/pull/16](https://github.com/NOAA-EMC/CROW/pull/16). It could use more testing though.

Great, I will not touch that file any more. Once I get towards the finishing touches on the PR I can try that code out.

**Comment by aerorahul** [comment]
> ```
> Python 3.6.8 |Intel Corporation| (default, Apr 12 2019, 17:34:58) 
> [GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> Intel(R) Distribution for Python is brought to you by Intel Corporation.
> Please check out: https://software.intel.com/en-us/python-distribution
> >>> import numpy as np
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/apps/intel/intelpython3/lib/python3.6/site-packages/numpy/__init__.py", line 156, in <module>
>     from . import _distributor_init
>   File "/apps/intel/intelpython3/lib/python3.6/site-packages/numpy/_distributor_init.py", line 34, in <module>
>     from . import _mklinit
> ImportError: libmkl_rt.so: cannot open shared object file: No such file or directory
> ```
> 
> I'm assuming this is a numpy build issue on the intel python distribution on HERA? How/where do I go about resolving this?

@BrianCurtis-NOAA 
You will need to load the `intel` module with the `intelpython` module for using `numpy`.
That is the error here, not with the `intelpython` module.

**Comment by BrianCurtis-NOAA** [comment]
@aerorahul Thanks. Noted.

**Comment by KateFriedman-NOAA** [comment]
Thanks all!
