### ISSUE TITLE
Create CI/CD framework

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#267]
Create CI/CD test framework:

* Define E2E testing requirements; e.g. forecast only configurations, cycled configurations, etc.
* stage initial conditions on RDHPCS (Hera and Orion)
* Leverage CI/CD w/ github triggers/automation from GDASApp
* create framework to automate `clone`, `setup_expt.py`, `setup_xml.py` for each testing configuration
* run each configuration and report status on GH

**Comment by WalterKolczynski-NOAA** [comment]
Completed
