### ISSUE TITLE
wxflow not found in marine da jobs on wcoss2

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/global-workflow#2682]
### What is wrong?

g-w CI C48mx500_3DVarAOWCDA fails on Cactus because module `wxflow` is not found.  For example,

_gdasprepoceanobs_
```
+ JGLOBAL_PREP_OCEAN_OBS[21]: /lfs/h2/emc/da/noscrub/russ.treadon/git/global-workflow/pr2641/scripts/exglobal_prep_ocean_obs.py
Traceback (most recent call last):
  File "/lfs/h2/emc/da/noscrub/russ.treadon/git/global-workflow/pr2641/scripts/exglobal_prep_ocean_obs.py", line 7, in <module>
    from wxflow import Logger, cast_strdict_as_dtypedict
ModuleNotFoundError: No module named 'wxflow'
+
```

_gdasocnanalprep_
```
+ JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP[46]: /lfs/h2/emc/da/noscrub/russ.treadon/git/global-workflow/pr2641/sorc/gdas.cd/scripts/exgdas_global_marine_analysis_prep.py
Traceback (most recent call last):
  File "/lfs/h2/emc/da/noscrub/russ.treadon/git/global-workflow/pr2641/sorc/gdas.cd/scripts/exgdas_global_marine_analysis_prep.py", line 10, in <module>
    from soca import bkg_utils
  File "/lfs/h2/emc/da/noscrub/russ.treadon/git/global-workflow/pr2641/sorc/gdas.cd/ush/soca/bkg_utils.py", line 11, in <module>
    from wxflow import (Logger, FileHandler)
ModuleNotFoundError: No module named 'wxflow'
```
### What should have happened?

Marine DA jobs should successfully run to completion on wcoss2

### What machines are impacted?

WCOSS2

### Steps to reproduce

1. clone and install g-w `develop`
2. enable C48mx500_3DVarAOWCDA CI on wcoss2
3. set up and run C48mx500_3DVarAOWCDA CI

20210324 18Z  gdasprepoceanobs fails as noted above    

### Additional information

C48mx500_3DVarAOWCDA runs to completion on Hera but `gdas.cd/modulefiles/GDAS/hera.intel.lua` contains
```
-- hack for wxflow
prepend_path("PYTHONPATH", "/scratch1/NCEPDEV/da/python/gdasapp/wxflow/20240307/src")
```

### Do you have a proposed solution?

Adding `wxflow` to the `PYTHONPATH` defined in `jobs/rocoto/prepoceanobs.sh` allows _gdasprepoceanobs_  to run to completion
```
-PYTHONPATH="${PYTHONPATH:+${PYTHONPATH}:}${HOMEgfs}/ush"
+wxflowPATH="${HOMEgfs}/ush/python:${HOMEgfs}/ush/python/wxflow/src"
+PYTHONPATH="${PYTHONPATH:+${PYTHONPATH}:}${HOMEgfs}/ush:${wxflowPATH}"
```
Not sure if this is an acceptable solution.   

An alternative would be to add something to GDASApp `modulefiles/GDAS/wcoss2.intel.lua` .

**Comment by RussTreadon-NOAA** [comment]
FYI @guillaumevernieres & @AndrewEichmann-NOAA

**Comment by RussTreadon-NOAA** [comment]
Tried another approach:  Add `wxflow` to `PYTHONPATH` in `ush/load_ufsda_modules.sh`
```
@@ -48,6 +48,9 @@ case "${MACHINE_ID}" in
     ;;
 esac
 
+wxflowPATH="${HOMEgfs}/ush/python:${HOMEgfs}/ush/python/wxflow/src"
+PYTHONPATH="${PYTHONPATH:+${PYTHONPATH}:}${HOMEgfs}/ush:${wxflowPATH}"
+
```

This change impacts all g-w jobs which execute `ush/load_ufsda_modules.sh` so extensive testing is required if this is deemed an acceptable solution.

**Comment by guillaumevernieres** [comment]
I have a fix for this @RussTreadon-NOAA , just a copy/paste of what you did in the rocoto bash script. I'm not quite sure why it worked before.

**Comment by aerorahul** [comment]
@RussTreadon-NOAA @guillaumevernieres Is this issue still an issue?

**Comment by RussTreadon-NOAA** [comment]
g-w PR #2875 attempted to run C48mx500_3DVarAOWCDA on Cactus.  The test died with 20210324 18Z gdasmarinebmat.  The marine DA jobs before gdasmarinebmat ran. Given this, it's possible that the problem reported in this issue has been resolved.  I can not confirm this because output from my WCOSS2 test has been scrubbed.

We can confirm that this issue can be closed by running CI-wcoss2 with C48mx500_3DVarAOWCDA enabled.

**Comment by aerorahul** [comment]
> g-w PR #2875 attempted to run C48mx500_3DVarAOWCDA on Cactus. The test died with 20210324 18Z gdasmarinebmat. The marine DA jobs before gdasmarinebmat ran. Given this, it's possible that the problem reported in this issue has been resolved. I can not confirm this because output from my WCOSS2 test has been scrubbed.
> 
> We can confirm that this issue can be closed by running CI-wcoss2 with C48mx500_3DVarAOWCDA enabled.

Marine DA has not been ported onto WCOSS2.  There are some issues other than wxflow that are causing this work to be taking a while.
I will close this issue as running marine DA jobs on WCOSS2 is not supported, yet.  Once that support is enabled, if this issue occurs, we can reopen this or a new issue.
