### ISSUE TITLE
Streamline module files

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#269]
With the move to hpc-stack, module lists are becoming uniform across machines and can be condensed into a single module for each build that covers all machines. The only machine-dependent portion is the use statement with the location of each stack and the compilation environment, which should be the same for all builds and loaded first. Furthermore, the module version can be determined via a versions file, so all modules are guaranteed to use the same version. These two steps will make porting and maintenance much easier, as changes will only need to be made in one location.

**Comment by aerorahul** [comment]
This depends on the availability of spack-stack on RDHPCS

**Comment by WalterKolczynski-NOAA** [comment]
OBE, we are moving to loading only the needed modules for each individual job (see #1521).
