### ISSUE TITLE
Add archive task to GEFS workflow

### ISSUE THREAD

**Issue by AntonMFernando-NOAA** [NOAA-EMC/global-workflow#2698]
### What new functionality do you need?

Add a rocoto task for GEFS system
This task will run in the service queue with a single processor 

### What are the requirements for the new functionality?

The task should be added to the rocoto mesh and execute with success
Archiving of actual data will be done in a separate PR

### Acceptance Criteria

job runs with success

**Comment by EricSinsky-NOAA** [comment]
Thank you @AntonMFernando-NOAA for opening an issue for this. Referencing issue #832 here since they are related.
