### ISSUE TITLE
Hercules rocoto version 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#2703]
### What is wrong?

https://github.com/NOAA-EMC/global-workflow/blob/develop/modulefiles/module_gwsetup.hercules.lua#L6 is pointing to an old version of rocoto 

### What should have happened?

Use latest version or no-version

### What machines are impacted?

Hercules

### Steps to reproduce

source gw_setup in workflow, you get the old rocoto version 

### Additional information

This is a small thing, so perhaps this can be included in an open PR? 

### Do you have a proposed solution?

Either use a specific 1.3.7 version or no version.

**Comment by DavidHuber-NOAA** [comment]
I will tackle this as part of #2672.

**Comment by aerorahul** [comment]
@DavidHuber-NOAA Did #2672 resolve this issue?  I see it updated the version for Rocoto from 1.3.3 to 1.3.7

**Comment by aerorahul** [comment]
I see that Rocoto on hercules is 1.3.7 as requested on the issue.
So, closing.
