### ISSUE TITLE
Staging the fix file for SOCA

### ISSUE THREAD

**Issue by apchoiCMD** [NOAA-EMC/global-workflow#2707]
### Target fix directory

NEW

### Type of change

- [ ] Update existing files
- [ ] Remove files
- [X] Add new files to existing directory
- [ ] Add new fix directory

### Any workflow changes needed?

No change needed

### Related issues

https://github.com/NOAA-EMC/GDASApp/issues/1120

`bkgerr` folder should NOT be included from pickup location

### Pickup location

/work/noaa/da/marineda/gfs-marine/data/static

### Size

0

**Comment by WalterKolczynski-NOAA** [comment]
```
ls: cannot access '/work/noaa/da/marineda/gfs-marine/data/static': Permission denied
```

**Comment by apchoiCMD** [comment]
@WalterKolczynski-NOAA Sorry for your inconvenience- I've changed the permissions so you will be able to access the folders/files

**Comment by WalterKolczynski-NOAA** [comment]
Are these going in a new directory or an existing one? The issue description is contradictory.

**Comment by apchoiCMD** [comment]
Those fix files with various resolutions are needed to copy into/under `fix/gdas/soca`, this is probably new folder and also ask you not to copy `bkferr` folder from each resolutions.

**Comment by guillaumevernieres** [comment]
@WalterKolczynski-NOAA 
We keep our fix files here:
```
/work/noaa/da/marineda/gfs-marine/data/static/
```
under the above directory, we need to copy the following, preserving the symlink if possible:
```
1440x1080x75
360x320x75
4500x3297x75
72x35x25
common
```
to glopara:
```
global/glopara/fix/soca/20240624
```
So yes, we're creating a new directory.

**Comment by aerorahul** [comment]
@WalterKolczynski-NOAA @KateFriedman-NOAA 
Please add this dataset and information to the Fix File Management spreadsheet [here](https://docs.google.com/spreadsheets/d/1BeIvcz6TO3If4YCqkUK-oz_kGS9q2wTjwLS-BBemSEY/edit?gid=526608225#gid=526608225)

@guillaumevernieres @apchoiCMD 
Please help fill out the details of the shared dataset as best as possible to help manage and document it when external users request them.

**Comment by KateFriedman-NOAA** [comment]
@guillaumevernieres @apchoiCMD Please confirm that the `bkgerr` files should not be included. @apchoiCMD said not to but @guillaumevernieres did not mention them so I'm double checking. Thanks!

**Comment by apchoiCMD** [comment]
Thanks for your comment @KateFriedman-NOAA , @guillaumevernieres didn't mention it but `bkgerr` should not included in process of copying the fix files-

**Comment by KateFriedman-NOAA** [comment]
> `bkgerr` should not included in process of copying the fix files

Great, thanks for the quick reply and confirmation @apchoiCMD ! I am working to pull these new fix files into the primary fix set now.

**Comment by KateFriedman-NOAA** [comment]
@apchoiCMD I have copied the requested fix files to the fix set on Hera: `/scratch1/NCEPDEV/global/glopara/fix/gdas/soca/20240624`

Please take a look and confirm they look good in place. Once confirmed, we will sync them to the other supported platforms.

**Comment by KateFriedman-NOAA** [comment]
@apchoiCMD @guillaumevernieres A new fix version variable will need to be added to `versions/fix.ver` in global-workflow to use this new fix set. It would be:
```
export gdas_soca_ver=20240624
```
Do you have an upcoming PR that you can include this update within? Let me know, thanks!

**Comment by apchoiCMD** [comment]
> @apchoiCMD I have copied the requested fix files to the fix set on Hera: `/scratch1/NCEPDEV/global/glopara/fix/gdas/soca/20240624`
> 
> Please take a look and confirm they look good in place. Once confirmed, we will sync them to the other supported platforms.

Thanks for your work and let me check them out quick-

**Comment by apchoiCMD** [comment]
@KateFriedman-NOAA I have completed to check the fix files you copied in the new place.
```
/scratch1/NCEPDEV/global/glopara/fix/gdas/soca/20240624
```
They look like what they suppose to be- Thanks and sorry for late response to you.

Regarding to an additional `PR` you mentioned, I think @guillaumevernieres will do with something else or ask me to do-

**Comment by apchoiCMD** [comment]
> @apchoiCMD I have copied the requested fix files to the fix set on Hera: `/scratch1/NCEPDEV/global/glopara/fix/gdas/soca/20240624`
> 
> Please take a look and confirm they look good in place. Once confirmed, we will sync them to the other supported platforms.

@KateFriedman-NOAA Are you going to copy them to Orion machine as well?
under `/work/noaa/global/glopara/fix/gdas/soca` something like this?

**Comment by KateFriedman-NOAA** [comment]
> They look like what they suppose to be
> Are you going to copy them to Orion machine as well?

Great, thanks for confirming! We'll now sync the new `fix/gdas/soca/20240624` to the other platforms. @WalterKolczynski-NOAA please sync to Orion, thanks!

> Regarding to an additional PR you mentioned, I think @guillaumevernieres will do with something else or ask me to do-

Ok great!

**Comment by KateFriedman-NOAA** [comment]
The new `gdas/soca/20240624` fix files have been synced to both WCOSS2s, Jet, and AWS. Working on HPSS still.

**Comment by apchoiCMD** [comment]
> The new `gdas/soca/20240624` fix files have been synced to both WCOSS2s, Jet, and AWS. Working on HPSS still.

Thanks for letting us know @KateFriedman-NOAA , I will take a look at least on WCOSS2-

**Comment by KateFriedman-NOAA** [comment]
The new `gdas/soca/20240624` fix set is also now saved on HPSS:
`/5year/NCEPDEV/emc-global/emc.glopara/fix/fix.gdas.soca.20240624.tar.xz`

**Comment by KateFriedman-NOAA** [comment]
@apchoiCMD FYI, I have put a copy of the new soca fix files here on Orion: `/work/noaa/global/kfriedma/glopara/fix/gdas/soca/20240624`

We may move global-workflow to temporarily use the mock fix that I set up under `/work/noaa/global/kfriedma/glopara/fix` in the next week before Walter returns from leave and can sync to the official location. For now, a copy is under my account.

**Comment by guillaumevernieres** [comment]
@KateFriedman-NOAA , @WalterKolczynski-NOAA any idea when the fixed files will be copied to glopara on Orion/Hercules?

**Comment by KateFriedman-NOAA** [comment]
> @KateFriedman-NOAA , @WalterKolczynski-NOAA any idea when the fixed files will be copied to glopara on Orion/Hercules?

@guillaumevernieres We had an issue with some of the fix files changing ownership erroneously on Orion last Friday. We're waiting on the MSU sysadmins to resolve the issue. Walter is back from leave but we can't sync the soca fix files into the primary set until this is resolved.

I pushed a second copy here on Orion `/work/noaa/global/kfriedma/glopara/fix`. If you need to test on Orion/Hercules right now, set your `FIX_DIR` variable in `sorc/link_workflow.sh` to that and rerun the link script to point your fix directories there.

**Comment by KateFriedman-NOAA** [comment]
Files have been synced to Orion/Hercules now. Closing this as complete.
