### ISSUE TITLE
New ugwd fix files for HR4

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#2716]
### Target fix directory

ugwd

### Type of change

- [x] Update existing files
- [ ] Remove files
- [ ] Add new files to existing directory
- [ ] Add new fix directory

### Any workflow changes needed?

Fix version + additional changes

### Related issues

Additional updates here: https://github.com/NOAA-EMC/global-workflow/pull/2670 

### Pickup location

/scratch1/NCEPDEV/global/Qingfu.Liu/git/GWD_SHong/APR2023_SSO

### Size

6.2 GB

**Comment by WalterKolczynski-NOAA** [comment]
New ugwd version created on Hera as `20240624`. Will synchronize to other machines once it is validated.

Does the AR nest version need to be updated as well with the accompanying setting changes?

**Comment by JessicaMeixner-NOAA** [comment]
@yangfanglin @Qingfu-Liu  can you answer Walter's question: 
> Does the AR nest version need to be updated as well with the accompanying setting changes?


Walter - the fix files look good to me.

**Comment by yangfanglin** [comment]
> Does the AR nest version need to be updated as well with the accompanying setting changes?

@WalterKolczynski-NOAA  My understanding is no.   Bring in @SamuelTrahanNOAA to get a definite answer .

**Comment by WalterKolczynski-NOAA** [comment]
`ugwd/20240624` has been synchronized to MSU and Dogwood.

@KateFriedman-NOAA would you please handle the other machines/AWS/tape when you are able?

**Comment by KateFriedman-NOAA** [comment]
The new `ugwd/20240624` has been synced to Jet, AWS, and HPSS.

**Comment by yangfanglin** [comment]
> > Does the AR nest version need to be updated as well with the accompanying setting changes?
> 
> @WalterKolczynski-NOAA My understanding is no. Bring in @SamuelTrahanNOAA to get a definite answer .

Per our latest communication with the GWD parameterization developers this new dataset should be applied to all UFS applications.   This should make it easier to update the workflow and RTs

**Comment by WalterKolczynski-NOAA** [comment]
@yangfanglin Okay, then we are going to need a new set for the AR grid to become `global-nest.20240624`. I'm not sure who would provide them.

CC: @guoqing-noaa

**Comment by aerorahul** [comment]
@guoqing-noaa 
If there are updates for global-nest following this, please let us know.  

These action for this issue has been performed.  Closing.
