### ISSUE TITLE
Restartb files missing from previous cycle HPSS archive

### ISSUE THREAD

**Issue by TravisElless-NOAA** [NOAA-EMC/global-workflow#2722]
### What is wrong?

In order to restart (warm start) an experiment using data stored on the HPSS archive, restarta files from the current cycle and restartb files from the previous cycle are needed. Currently restarta and restartb files are being written for 00z cycles and using only 00z cycle data. 

### What should have happened?

Restartb files should be populated in the HPSS archive for the previous cycle (18z), and restarta files for the current cycle (00z)

### What machines are impacted?

All or N/A, Hera

### Steps to reproduce

1. Clone and build develop workflow
2. Change `ARCH_WARMICFREQ=1` in config.base in order to archive restartb files in first 00z cycle (default of `ARCH_WARMICFREQ=4` is only saving restartb files every 4th day)
3. Run a simulation that archives data to HPSS at 18z and 00z cycles 
4. Check what restart files are present for the 18z and 00z cycles

### Additional information

Tests identifying the bug were run on HERA:
EXPDIR: /scratch1/NCEPDEV/da/Travis.J.Elless/exp/test_new_develop
COMROOT: /scratch2/NCEPDEV/stmp3/Travis.J.Elless/comrot/test_new_develop

**Comment by DavidHuber-NOAA** [comment]
This can probably follow the same method as used for the enkf restarts:
https://github.com/NOAA-EMC/global-workflow/blob/7706760bb8adbdf78cb640b02739023c886e7699/parm/archive/master_enkf.yaml.j2#L102-L110

I will give this a try and open a PR if it works.
