### ISSUE TITLE
feature/coupled-crow update input.nml

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#277]
feature/coupled-crow in prep for prototype 6 needs to update the hash of ufs-weather-model  and update some of the input.nml namelist values (details will be added).

**Comment by JessicaMeixner-NOAA** [comment]
A tag will be created for ufs-weather-model, so we should point to that instead of a hash. 

The time steps will be: 
dt (atm, ice, wave, fast cpl) =225, dt_slow=dt_dyn(ocn)=900,  dt_therm(ocn)=1800

The input.nml options should be updated to match: /scratch2/BMC/gsd-hpcs/Shan.Sun/FV3_RT/v16_35d_8cases_feb20/cpld_bmarkfrac_wave_v16_35d_2012010100_prod/input.nml 
(there will be some diffs because the workflow version sets more parameters than the rt-test does)

 Fix files with the newest oro data and ICs (atm & wave) need to be updated. 

After wave model ICs are made, the lines copying in the ww3 ICs needs to be uncommented.

**Comment by JessicaMeixner-NOAA** [comment]
For prototype 5, we made a case file for the prototype with the balanced layout (which should be updated in all the case files) and correct forecast length.  We should probably do that for p6 as well.

**Comment by arunchawla-NOAA** [comment]
@WalterKolczynski-NOAA can you take a look at this ? It should be fairly straight forward. @JessicaMeixner-NOAA is trying to solve an MPI bug for WW3 in prep for prototype 6

**Comment by JessicaMeixner-NOAA** [comment]
@WalterKolczynski-NOAA there are enough WW3 ICs made that I'm going to go ahead and stage them in the climpara area and then copy over the last bit.  Which means we should be okay to un-comment the copying of the WW3 restart files.  Do you have a branch with changes that I can push these changes to along with these others or would you prefer it go in as a separate PR?

**Comment by WalterKolczynski-NOAA** [comment]
It can be a separate PR. My branch doesn't even have commits yet, since I'm still waiting to confirm the changes work.

**Comment by JessicaMeixner-NOAA** [comment]
The tag for the weather-model as of now: https://github.com/ufs-community/ufs-weather-model/tree/Prototype-6.0beta

**Comment by WalterKolczynski-NOAA** [comment]
Sample namelist: https://gist.github.com/WalterKolczynski-NOAA/e52fbb33180ef9dcc82cc714bdedd0b2
