### ISSUE TITLE
land surface upgrades for HR4

### ISSUE THREAD

**Issue by HelinWei-NOAA** [NOAA-EMC/global-workflow#2786]
### What new functionality do you need?

opt_diag needs to be set to 2 corresponding to the land surface upgrades for HR4

### What are the requirements for the new functionality?

the default value of opt_diag should be changed to 2 from 1

### Acceptance Criteria

change the default value of opt_diag to 2 in parsing_namelists_FV3.sh and parsing_namelists_FV3_nest.sh

**Comment by JessicaMeixner-NOAA** [comment]
@HelinWei-NOAA - we need the GFSv17 tests in the ufs-weather-model to be using whatever settings we are setting here.  This means we need another PR to ufs-weather-model with the changes you are proposing here, for example https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/tests/cpld_control_gfsv17#L126

**Comment by HelinWei-NOAA** [comment]
@JessicaMeixner-NOAA Yes. I should catch and include it in this PR.
> @HelinWei-NOAA - we need the GFSv17 tests in the ufs-weather-model to be using whatever settings we are setting here. This means we need another PR to ufs-weather-model with the changes you are proposing here, for example https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/tests/cpld_control_gfsv17#L126

**Comment by yangfanglin** [comment]
@HelinWei-NOAA  Has an ufs-weather-model PR been created to update the RTs to use opt_diag=2 ?   I saw this PR https://github.com/ufs-community/ufs-weather-model/pull/2373 mentioned land changes.  Does it mean RT update for land has been rolled into this PR ?

**Comment by HelinWei-NOAA** [comment]
@yangfanglin Yes. As @JessicaMeixner-NOAA suggested and with Daniel's agreement and assistance.
> @HelinWei-NOAA Has an ufs-weather-model PR been created to update the RTs to use opt_diag=2 ? I saw this PR [ufs-community/ufs-weather-model#2373](https://github.com/ufs-community/ufs-weather-model/pull/2373) mentioned land changes. Does it mean RT update for land has been rolled into this PR ?
