### ISSUE TITLE
Update MOM_input for the marine DA

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/global-workflow#2797]
### Target fix directory

gldas

### Type of change

- [X] Update existing files
- [ ] Remove files
- [ ] Add new files to existing directory
- [ ] Add new fix directory

### Any workflow changes needed?

No change needed

### Related issues

Should replace 
```
/scratch1/NCEPDEV/global/glopara/fix/gdas/soca/20240624/1440x1080x75/soca/MOM_input
```
on hera, same changes are requiered on other HPC.

### Pickup location

/scratch2/NCEPDEV/ocean/Guillaume.Vernieres/data/static/1440x1080x75/soca/MOM_input

### Size

68K

**Comment by jiandewang** [comment]
@guillaumevernieres I don't know what version of MOM6 you are using here, but DEFAULT_2018_ANSWERS has been obsolated. Instead you need to use DEFAULT_ANSWER_DATE=20181231. 
see https://github.com/jiandewang/ufs-weather-model/blob/develop/tests/parm/MOM_input_025.IN#L94
If your run didn't stop while using DEFAULT_2018_ANSWERS , that means you are using an old version of MOM6

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres I don't know what version of MOM6 you are using here, but DEFAULT_2018_ANSWERS has been obsolated. Instead you need to use DEFAULT_ANSWER_DATE=20181231. see https://github.com/jiandewang/ufs-weather-model/blob/develop/tests/parm/MOM_input_025.IN#L94 If your run didn't stop while using DEFAULT_2018_ANSWERS , that means you are using an old version of MOM6

@jiandewang , yes, we were building soca (marine JEDI) with an older version of MOM6. This was just recently updated. Note that this has nothing to do with running the model.

**Comment by KateFriedman-NOAA** [comment]
@guillaumevernieres Given you're asking to update an existing file, I have created a new timestamp (`20240802`) and replaced the requested `1440x1080x75/soca/MOM_input` file within. See the new timestamp here on Hera:
```
[role.glopara@hfe06 soca]$ pwd
/scratch1/NCEPDEV/global/glopara/fix/gdas/soca/20240802/1440x1080x75/soca
[role.glopara@hfe06 soca]$ ll MOM_input
-rw-r--r-- 1 role.glopara global 66755 Jul 26 17:24 MOM_input
```
Please confirm it's good and we will sync this new timestamp to the other platforms. Thanks!

**Comment by guillaumevernieres** [comment]
Just checked, changes look good @KateFriedman-NOAA . Thanks.

**Comment by KateFriedman-NOAA** [comment]
Have synced to both WCOSS2s, AWS, and Jet. @WalterKolczynski-NOAA Please sync the new `gdas/soca/20240802` timestamp to Orion, thanks!

**Comment by CatherineThomas-NOAA** [comment]
@KateFriedman-NOAA @WalterKolczynski-NOAA
Have the fix files been synced to Orion yet?

**Comment by WalterKolczynski-NOAA** [comment]
> @KateFriedman-NOAA @WalterKolczynski-NOAA Have the fix files been synced to Orion yet?

@CatherineThomas-NOAA Yes

**Comment by guillaumevernieres** [comment]
> > @KateFriedman-NOAA @WalterKolczynski-NOAA Have the fix files been synced to Orion yet?
> 
> @CatherineThomas-NOAA Yes

~it doesn't look like it @WalterKolczynski-NOAA , where did you put the updated file?~ 
You probably did but the linking script is still pointing to @KateFriedman-NOAA 's temporary fix dir.

**Comment by KateFriedman-NOAA** [comment]
> You probably did but the linking script is still pointing to @KateFriedman-NOAA 's temporary fix dir.

@guillaumevernieres We have now reverted it back in PR #2811. Please check now, thanks!
