### ISSUE TITLE
Climatological standard deviation for aerosol DA

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/global-workflow#2806]
### Target fix directory

NEW

### Type of change

- [ ] Update existing files
- [ ] Remove files
- [ ] Add new files to existing directory
- [X] Add new fix directory

### Any workflow changes needed?

Fix version + additional changes

### Related issues

Needed for #2738 

Workflow expects that global-workflow/fix/gdas/aero has the contents in it of the pickup location (meaning the subdirectory clim_b)

### Pickup location

/scratch1/NCEPDEV/da/Cory.R.Martin/work_aug2024/fix_aero_gw/

### Size

751MB

**Comment by WalterKolczynski-NOAA** [comment]
New fix directory gdas/aero created with timestamp 20240806:
```
$ tree gdas/aero
gdas/aero
`-- 20240806
    `-- clim_b
        |-- stddev.fv_tracer.res.tile1.nc
        |-- stddev.fv_tracer.res.tile2.nc
        |-- stddev.fv_tracer.res.tile3.nc
        |-- stddev.fv_tracer.res.tile4.nc
        |-- stddev.fv_tracer.res.tile5.nc
        `-- stddev.fv_tracer.res.tile6.nc

2 directories, 6 files
```

Synchronized to MSU, and Cactus, and Dogwood.

@KateFriedman-NOAA please sync to AWS, Jet, and archive the tarball.

**Comment by CoryMartin-NOAA** [comment]
thanks @WalterKolczynski-NOAA and @KateFriedman-NOAA !!!

**Comment by KateFriedman-NOAA** [comment]
Synced to AWS and Jet. Working on HPSS archive.

**Comment by WalterKolczynski-NOAA** [comment]
@KateFriedman-NOAA did you finish the HPSS archival?

**Comment by KateFriedman-NOAA** [comment]
It is now saved on HPSS as well: `/5year/NCEPDEV/emc-global/emc.glopara/fix/fix.gdas.aero.20240806.tar.xz`

**Comment by WalterKolczynski-NOAA** [comment]
Complete
