### ISSUE TITLE
Add observation files from new bufr dump files for the CI snow DA test

### ISSUE THREAD

**Issue by jiaruidong2017** [NOAA-EMC/global-workflow#2810]
### Target fix directory

gdas/fv3jedi

### Type of change

- [ ] Update existing files
- [ ] Remove files
- [X] Add new files to existing directory
- [ ] Add new fix directory

### Any workflow changes needed?

No change needed

### Related issues

This will provide the required observation files for G-W's CI test when https://github.com/NOAA-EMC/GDASApp/pull/1245 is merged. 

### Pickup location

/scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GlobalWorkflow/para_gfs/glopara_dump/sfcsno/

### Size

82

**Comment by KateFriedman-NOAA** [comment]
@jiaruidong2017 I have copied the provided `sfcsno` dump files into the GDA on Hera:

```
[role.glopara@hfe05 dump]$ pwd
/scratch1/NCEPDEV/global/glopara/dump
[role.glopara@hfe05 dump]$ ll g*2021122*/*/atmos/*sfcsno*
-rw-r--r-- 1 role.glopara global 28629184 Aug  6 22:54 gdas.20211220/18/atmos/gdas.t18z.sfcsno.tm00.bufr_d
-rw-r--r-- 1 role.glopara global 27916712 Aug  6 22:55 gdas.20211221/00/atmos/gdas.t00z.sfcsno.tm00.bufr_d
-rw-r--r-- 1 role.glopara global 27916712 Aug  6 22:55 gfs.20211221/00/atmos/gfs.t00z.sfcsno.tm00.bufr_d
```

I synced the files to the GDA on WCOSS2 as well. @WalterKolczynski-NOAA please sync these dates/files to the GDA on Orion, thanks!

**Comment by WalterKolczynski-NOAA** [comment]
Synchronized to MSU

**Comment by jiaruidong2017** [comment]
Thanks @KateFriedman-NOAA and @WalterKolczynski-NOAA
