### ISSUE TITLE
Update Rocoto Checking in CI to fix false negative STALLS due UNAVAIBLE status

### ISSUE THREAD

**Issue by TerrenceMcGuinness-NOAA** [NOAA-EMC/global-workflow#2822]
### What is wrong?

Rocoto is tagging jobs as UNAVAIBLE or UNKNON.  From empirical observation just timing out might not be the root cause.  But as a result, the rocoto-checking mechanism flags the cases as stalled.  We need to handle that more effectively on the CI side in tandem with WCOSS "fixing" the issue.

### What should have happened?

The rocoto-checking needs to not rush at flagging STALLED and use some better logic to allow the system to self-correct during UNAVAILBLE and/or UNKNOWN responses.

### What machines are impacted?

WCOSS2

### Steps to reproduce

Use **roctorun** and observe jobs states on running cases on WCOSS and notice UNKNOW comes in fast and can linger between **rocotoruns** and can update and show RUNNING again

### Additional information

Test this out on empirical cases

### Do you have a proposed solution?

Have the python code react to UNKOWN and/or UNAVAILBLE states with some logic in attempts to allow the system to self correct before flagging as STALLED tested on empirical cases.

**Comment by DavidHuber-NOAA** [comment]
I believe this was fixed by #2842.
