### ISSUE TITLE
Update atmos upp job to use COMIN/COMOUT

### ISSUE THREAD

**Issue by mingshichen-noaa** [NOAA-EMC/global-workflow#2823]
###  Description

NCO has requested that each COM variable specify whether it is an input or an output. This completes that process for the global-workflow atmos upp job.

Refs#2451

### Type of change

- Maintenance (code refactor, clean-up, new CI test, etc.)

### Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO
 
### How has this been tested?
- C48_ATM experiment on RDHPCS Hecules/Hera
- CI/CD will test the additional applications

### Pickup location

/work2/noaa/global/mchen/global-workflow

### Size

300

**Comment by mingshichen-noaa** [comment]
Walter, Kate,
Just now I created an issue #2823 refer to #2451. But I have some questions about selections: 

- pickup location: I picked up my local repo path, wasn't I?
- size: I gave an estimate value: 300 MB, is it enough?

**Comment by WalterKolczynski-NOAA** [comment]
> Walter, Kate, Just now I created an issue #2823 refer to #2451. But I have some questions about selections:
> 
> * pickup location: I picked up my local repo path, wasn't I?
> * size: I gave an estimate value: 300 MB, is it enough?

You opened the wrong kind of issue. Your work has nothing to do with fix files (files in the `fix/` directory that we don't keep in the repo). Recommend closing this issue and reopening as the correct type (Feature Request).

**Comment by mingshichen-noaa** [comment]
Walter,
Thank you for your response. I will close it and reopen the Feather Request.
