### ISSUE TITLE
Update gsi_enkf and gsi_utils hashes

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/global-workflow#2825]
### What new functionality do you need?

[GSI](https://github.com/NOAA-EMC/GSI) and [GSI_utils](https://github.com/NOAA-EMC/GSI-utils) `develop` have been updated with changes required by GFS v17.  These changes need to be pulled into g-w.

### What are the requirements for the new functionality?

Update `gsi_enkf.fd` and `gsi_utils.fd` hashes in g-w `sorc/`

### Acceptance Criteria

`sorc/gsi_enkf.fd` and `sorc/gsi_utils.fd` hashes are updated.

**Comment by RussTreadon-NOAA** [comment]
@CatherineThomas-NOAA , @CoryMartin-NOAA , @emilyhcliu :  The `develop` branches of GSI and GSI-utils contain recent commits which we want to exercise in GFS v17.  Three questions
1. Are there any other GFS v17 changes we want in GSI or GSI-utils?   For example, I think we should get Xin's bug fix in GSI issue [#778](https://github.com/NOAA-EMC/GSI/issues/778) into GSI `develop`.  Any other changes to either repo?
2. Are any GFS v17 updates to [GSI-Monitor](https://github.com/NOAA-EMC/GSI-Monitor)?
3. To whom can we assign this g-w issue?

**Comment by CoryMartin-NOAA** [comment]
I plan to update GSI-utils for aerosol analysis capabilities

**Comment by DavidHuber-NOAA** [comment]
I also have a gsi-utils PR ([49](https://github.com/NOAA-EMC/GSI-utils/pull/49)) open that will allow C768 to run on Hera.

**Comment by CatherineThomas-NOAA** [comment]
1. I agree that Xin's fix should also get in.  I believe the changes for turning on the ensemble spread tapering would only be on the workflow side, but I'm not sure if CRTMv3 would require any changes? 
2. @EdwardSafford-NOAA was planning on looking at whether the monitors needed any changes. @EdwardSafford-NOAA Any update on this?
3. Since the main changes are Thompson related, maybe someone from the all-sky side to make sure all the new defaults are set properly?  @emilyhcliu @azadeh-gh @ADCollard @xincjin-NOAA?  I can do it if need be.

**Comment by EdwardSafford-NOAA** [comment]
@CatherineThomas-NOAA I've tested monitor plotting on hera and that works using my test data.  However the workflow monitor data output location has changed and I'll need to update the monitors to account for that.  Do you have an experiment running (or recently run) on hera that I could use for monitor test data?

**Comment by CatherineThomas-NOAA** [comment]
@EdwardSafford-NOAA
I ran an experiment recently that has a couple cycles on disk:
`/scratch1/NCEPDEV/stmp2/Catherine.Thomas/ROTDIRS/physics_taper`

For example, see: 
`/scratch1/NCEPDEV/stmp2/Catherine.Thomas/ROTDIRS/physics_taper/gdas.20230429/18/products/atmos/radmon`

All the monitor data is also saved on HPSS:
`/NCEPDEV/emc-da/1year/Catherine.Thomas/HERA/scratch/physics_taper`
under `gdas.tar`.

**Comment by EdwardSafford-NOAA** [comment]
@CatherineThomas-NOAA Thanks.  I have a PR set now to update the monitor utility scripts:  [GSI-Monitor 142](https://github.com/NOAA-EMC/GSI-Monitor/pull/142).

**Comment by RussTreadon-NOAA** [comment]
@CatherineThomas-NOAA , @EdwardSafford-NOAA 's GSI-Monitor PR [#142](https://github.com/NOAA-EMC/GSI-Monitor/pull/142) has been merged into GSI-Monitor [`develop`](https://github.com/NOAA-EMC/GSI-Monitor/tree/develop).  Done at [`4e5feb7`](https://github.com/NOAA-EMC/GSI-Monitor/commit/4e5feb730b3401009322b1b50998cb3617c9e277)

**Comment by RussTreadon-NOAA** [comment]
We now have g-w issue #3027 to update the GSI hash.  Can this issue be closed?

**Comment by DavidHuber-NOAA** [comment]
Yes, I think so.
