### ISSUE TITLE
coupled: setting the correct npe_node_fcst 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#283]
In the feature/coupled-crow branch, the variable npe_node_fcst is set to the maximum pets per node, even when threads are requested.  This means that when the env/${MACHINE}.env file is sourced, that the requested threads gets set back to 1 because npe_node_max=npe_node_fcst

```
    nth_max=$(($npe_node_max / $npe_node_fcst))

    export NTHREADS_FV3=${nth_fv3:-$nth_max}
    [[ $NTHREADS_FV3 -gt $nth_max ]] && export NTHREADS_FV3=$nth_max
```

I have added a workaround in my branch for now, that in ush/forecast_predet.sh I have commented out: 
NTHREADS_FV3=${NTHREADS_FV3:-${NTHREADS_FCST:-${nth_fv3:-1}}}
and replaced it with: 
NTHREADS_FV3=${nth_fv3:-1}

But that is not the correct way to fix this.   I tried a couple of ways of changing the definition of npe_node_fcst but failed to get the correct output for threading.

**Comment by JessicaMeixner-NOAA** [comment]
@WalterKolczynski-NOAA @KateFriedman-NOAA I think this issue can be closed, but wanted to confirm with you first.  This is specific to feature/coupled-crow, and since we are moving forward to using the develop branch it's no longer relevant. Although it might be a good to note somewhere if CROW is being considered for the future workflow.

**Comment by KateFriedman-NOAA** [comment]
I'm good to close this if @WalterKolczynski-NOAA is. Thanks!
