### ISSUE TITLE
Update to prepobs/v1.1.0

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#2840]
### What new functionality do you need?

Need `develop` to run with the new prepobs/1.1.0 version that was implemented into operations this past May.

Will need to update prepobs in conjunction with new obsproc version (issue #2291).

Operations issue #2837 will be taken care of first due to urgency.

### What are the requirements for the new functionality?

That the prepbufr file is produced without error.

### Acceptance Criteria

Invoking the prepobs/1.1.0 module works and the prepbufr file is generated successfully while also using the newer obsproc/v1.2.

**Comment by KateFriedman-NOAA** [comment]
@WalterKolczynski-NOAA Please install `prepobs/v1.1.0` on MSU, thanks!
```
git clone -b prepobs.v1.1.0-rd-gfsv17 https://github.com/NOAA-EMC/prepobs.git ./v1.1.0
cd v1.1.0
INSTALL_TARGET=orion[hercules] INSTALL_PREFIX=PATH_TO_v1.1.0_INSTALL ./ush/build.sh
```

**Comment by WalterKolczynski-NOAA** [comment]
Installed on MSU
