### ISSUE TITLE
Leaf Area Index Climatology fix file

### ISSUE THREAD

**Issue by sanatcumar** [NOAA-EMC/global-workflow#2843]
### Target fix directory

sfc_climo

### Type of change

- [ ] Update existing files
- [ ] Remove files
- [X] Add new files to existing directory
- [ ] Add new fix directory

### Any workflow changes needed?

No change needed

### Related issues

https://github.com/ufs-community/UFS_UTILS/pull/958

### Pickup location

/scratch2/NCEPDEV/land/Sanath.Kumar/ufs/lai/LAI_climo_pnnl.nc

### Size

11 GB

**Comment by KateFriedman-NOAA** [comment]
@sanatcumar I have copied the `LAI_climo_pnnl.nc` file into the lastest sfc_climo fix timestamp folder (`sfc_climo/20230925`). See here on Hera:
```
[role.glopara@hfe07 20230925]$ pwd
/scratch1/NCEPDEV/global/glopara/fix/sfc_climo/20230925
[role.glopara@hfe07 20230925]$ ll LAI_climo_pnnl.nc 
-rw-r--r-- 1 role.glopara global 11198491446 Apr 16 12:39 LAI_climo_pnnl.nc
```
Please confirm this is as requested and we'll sync the file to the fix sets on the other supported platforms. Thanks!

**Comment by sanatcumar** [comment]
@KateFriedman-NOAA I can confirm this is as expected. Thanks. @WalterKolczynski-NOAA thanks for fixing the title

**Comment by KateFriedman-NOAA** [comment]
I have synced the new fix file to both WCOSS2s, Jet, AWS, and HPSS. @WalterKolczynski-NOAA please sync to Orion and then close the issue, thanks!

**Comment by WalterKolczynski-NOAA** [comment]
Synchronized to MSU

**Comment by DavidHuber-NOAA** [comment]
@sanatcumar was there a PR required in the global workflow for this? We are still using the older surface fix files at this time.
