### ISSUE TITLE
Add bufr ocean observation files for testing to experimental_obs

### ISSUE THREAD

**Issue by AndrewEichmann-NOAA** [NOAA-EMC/global-workflow#2847]
### Target fix directory

NEW

### Type of change

- [ ] Update existing files
- [ ] Remove files
- [ ] Add new files to existing directory
- [X] Add new fix directory

### Any workflow changes needed?

No change needed

### Related issues

https://github.com/NOAA-EMC/GDASApp/pull/1244

### Pickup location

/scratch1/NCEPDEV/da/common/ci/bufr/

### Size

3.0M

**Comment by KateFriedman-NOAA** [comment]
@AndrewEichmann-NOAA I have copied them into the `experimental_obs` folder on Hera. I created a new `ci/bufr` subfolder to house them:
```
[role.glopara@hfe03 bufr]$ pwd
/scratch1/NCEPDEV/global/glopara/data/experimental_obs/ci/bufr
[role.glopara@hfe03 bufr]$ ll
total 2980
-rw-r--r-- 1 role.glopara global   59336 Aug 19 17:35 2021063006-gdas.t06z.altkob.tm00.bufr_d
-rw-r--r-- 1 role.glopara global   85416 Aug 19 17:35 2021063006-gdas.t06z.bathy.tm00.bufr_d
-rw-r--r-- 1 role.glopara global 1536440 Aug 19 17:35 2021063006-gdas.t06z.subpfl.tm00.bufr_d
-rw-r--r-- 1 role.glopara global  971024 Aug 19 17:35 2021063006-gdas.t06z.tesac.tm00.bufr_d
-rw-r--r-- 1 role.glopara global  222080 Aug 19 17:35 2021063006-gdas.t06z.trkob.tm00.bufr_d
-rw-r--r-- 1 role.glopara global  160432 Aug 19 17:35 2021063006-gdas.t06z.xbtctd.tm00.bufr_d
```
Question, do you want me to remove the "2021063006-" part from the filenames so they look like the dump filenames?

**Comment by AndrewEichmann-NOAA** [comment]
@givelberg Do you have any position on what these should look like?

**Comment by KateFriedman-NOAA** [comment]
@AndrewEichmann-NOAA @givelberg checking in on this, thanks!

**Comment by AndrewEichmann-NOAA** [comment]
@givelberg Ed do we still need this?

**Comment by AndrewEichmann-NOAA** [comment]
@guillaumevernieres too, sorry

**Comment by givelberg** [comment]
@AndrewEichmann-NOAA  I asked for files to be placed somewhere on orion and hera, so that I could test the b2i converters. The files are needed for the PR.

**Comment by guillaumevernieres** [comment]
@AndrewEichmann-NOAA , @givelberg, @apchoiCMD : I don't understand the point of this issue. The obs that @givelberg needs for his testing should be in `glopara` already, under `experimental_obs`.
For example, I see insitu obs under ```:/work/noaa/global/glopara/data/experimental_obs```:

```
 gdas.20210701/12/
├── atmos
│   ├── gdas.t12z.altkob.tm00.bufr_d
│   ├── gdas.t12z.axbt.tm00.bufr_d
│   ├── gdas.t12z.bathy.tm00.bufr_d
│   ├── gdas.t12z.cmanb.tm00.bufr_d
│   ├── gdas.t12z.cstgd.tm00.bufr_d
│   ├── gdas.t12z.dbuoyb.tm00.bufr_d
│   ├── gdas.t12z.dbuoy.tm00.bufr_d
│   ├── gdas.t12z.lcman.tm00.bufr_d
│   ├── gdas.t12z.mbuoyb.tm00.bufr_d
│   ├── gdas.t12z.mbuoy.tm00.bufr_d
│   ├── gdas.t12z.saldrn.tm00.bufr_d
│   ├── gdas.t12z.shipsb.tm00.bufr_d
│   ├── gdas.t12z.ships.tm00.bufr_d
│   ├── gdas.t12z.shipsu.tm00.bufr_d
│   ├── gdas.t12z.shipub.tm00.bufr_d
│   ├── gdas.t12z.subpfl.tm00.bufr_d
│   ├── gdas.t12z.tesac.tm00.bufr_d
│   ├── gdas.t12z.trkob.tm00.bufr_d
│   └── gdas.t12z.xbtctd.tm00.bufr_d
└── ocean
...
```
Is that not sufficient?

**Comment by guillaumevernieres** [comment]
We have all the obs that we need, closing this and apologies for the unnecessary overheads @KateFriedman-NOAA

**Comment by KateFriedman-NOAA** [comment]
All good @guillaumevernieres !

Walter, please sync the `data/experimental_obs/ci` folder to MSU. I will sync to WCOSS2 and Jet. Thanks!

**Comment by guillaumevernieres** [comment]
> All good @guillaumevernieres !
> 
> Walter, please sync the `data/experimental_obs/ci` folder to MSU. I will sync to WCOSS2 and Jet. Thanks!

My point @KateFriedman-NOAA is that this new `data/experimental_obs/ci` folder isn't needed, thus the apology for the unnecessary work we asked from you ...

**Comment by KateFriedman-NOAA** [comment]
@guillaumevernieres Oh, I understand now, I will remove the new `ci/bufr` folder from the `experimental_obs` folder on Hera. Thanks for clarifying!
