### ISSUE TITLE
The DATAROOT is not setup correctly while running setup_xml.py

### ISSUE THREAD

**Issue by emilyhcliu** [NOAA-EMC/global-workflow#2850]
### What is wrong?

The DATAROOT is not set up correctly while running setup_xml.py
https://github.com/NOAA-EMC/global-workflow/blob/1b18f2f97eec24a8b3f817b7ef1b4caa2be24937/workflow/rocoto/tasks.py#L64-L75

The `self._base.get('STMP')` is returned as `NONE` from line #65
The conf.base does have the environmental variable defined.  However, the self._base dictory does not contain `STMP` 

### What should have happened?

The `self._base.get('STMP')` is returned as `NONE` from line #65
It should return the STMP string defined in the config.base

### Steps to reproduce

1. Get a set  of ICs for GFS
2. Setup the experiment using setup_expt.py
3. Configure the expdir using setup_xml.py
4. Check the `DATAROOT` in the XML file and the `STMP` directory is `NONE`

### Additional information

None

### Do you have a proposed solution?

Option - 1. In tasks.py make sure `self._base` contains `STMP`
Option - 2. Users need to manually define `DATAROOT` in config.base

**Comment by emilyhcliu** [comment]
@KateFriedman-NOAA  I'm not sure who I should assign this issue to.

**Comment by WalterKolczynski-NOAA** [comment]
Do you have an example experiment directory? I haven't seen this problem before.

**Comment by emilyhcliu** [comment]
Yes. on Orion.
```
/work2/noaa/da/eliu/ORION/para/expdir/gdas_eval_2024_iasi_JEDI  
```
This is the `expdir`I created from the global-workflow develop using setup_xml.sh (original, without any changes from me)
Please look at the `gdas_eval_2024_iasi_JEDI.xml` in expdir
The DATAROOT supposes to point to $STMP, but it is `NONE`

```
        <envar><name>DATAROOT</name><value>None/RUNDIRS/gdas_eval_2024_iasi_JEDI/gdas.<cyclestr>@Y@m@d@H</cyclestr></value></envar>

```

**Comment by WalterKolczynski-NOAA** [comment]
@emilyhcliu Can you make that directory readable?
```
>ls /work2/noaa/da/eliu/ORION/para/expdir/gdas_eval_2024_iasi_JEDI
ls: cannot access '/work2/noaa/da/eliu/ORION/para/expdir/gdas_eval_2024_iasi_JEDI': Permission denied
```

**Comment by emilyhcliu** [comment]
> @emilyhcliu Can you make that directory readable?
> 
> ```
> >ls /work2/noaa/da/eliu/ORION/para/expdir/gdas_eval_2024_iasi_JEDI
> ls: cannot access '/work2/noaa/da/eliu/ORION/para/expdir/gdas_eval_2024_iasi_JEDI': Permission denied
> ```

Oh, odd.   I just changed the permission.
Thanks for looking into this issue.

**Comment by WalterKolczynski-NOAA** [comment]
Still no go.

**Comment by emilyhcliu** [comment]
> Still no go.

Please try again. 
Should be good now.
``` 
 -rwxr-xr-x 1 eliu da 25980 Aug 21 15:55 gdas_eval_2024_iasi_JEDI.xml
orion-login-2[668] eliu$ pwd
/work2/noaa/da/eliu/ORION/para/expdir/gdas_eval_2024_iasi_JEDI
```

**Comment by WalterKolczynski-NOAA** [comment]
Nope. I think you need to make the parents readable too:
```
>ls /work2/noaa/da/eliu -l
ls: cannot open directory '/work2/noaa/da/eliu': Permission denied
```

**Comment by emilyhcliu** [comment]
> Nope. I think you need to make the parents readable too:
> 
> ```
> >ls /work2/noaa/da/eliu -l
> ls: cannot open directory '/work2/noaa/da/eliu': Permission denied
> ```

OK.  I make the parents readable, too.

**Comment by WalterKolczynski-NOAA** [comment]
I can't duplicate this. Also can't read the `HOMEgfs` directory. Please double-check that all of your submodules are updated if this isn't a fresh clone and start again from scratch saving the output from setup_exp and setup_xml.

**Comment by emilyhcliu** [comment]
> I can't duplicate this. Also can't read the `HOMEgfs` directory. Please double-check that all of your submodules are updated if this isn't a fresh clone and start again from scratch saving the output from setup_exp and setup_xml.

Got it.  I will do a fresh clone and set up a new one to run.
Thanks.

**Comment by emilyhcliu** [comment]
> > I can't duplicate this. Also can't read the `HOMEgfs` directory. Please double-check that all of your submodules are updated if this isn't a fresh clone and start again from scratch saving the output from setup_exp and setup_xml.
> 
> Got it. I will do a fresh clone and set up a new one to run. Thanks.

I started with a fresh cloned global-workflow.  
I still got the same results  :-(

**Comment by RuiyuSun** [comment]
@WalterKolczynski-NOAA @emilyhcliu I had the same issue. I had to make the change to the RUNDIRS manually in the xml file. I forgot to mention this at the last global workflow meeting.

**Comment by emilyhcliu** [comment]
> @WalterKolczynski-NOAA @emilyhcliu I had the same issue. I had to make the change to the RUNDIRS manually in the xml file. I forgot to mention this at the last global workflow meeting.

@RuiyuSun Thanks for confirming the RUNDIR issue I observed.

**Comment by DavidHuber-NOAA** [comment]
I am able to set `STMP` in `config.base` and the resulting XML updates to the new location.  Here is the step-by-step I used:

```bash
git clone git@github.com:NOAA-EMC/global-workflow --recurse-submodules && cd global-workflow
. ci/platform/config.hera
export RUNTESTS=/scratch1/NCEPDEV/global/David.Huber/para && module use modulefiles && module load module_gwsetup.hera && cd workflow
pslot=test_rundirs ./create_experiment -y ../ci/cases/pr/C96C48_hybatmDA.yaml
cp /scratch1/NCEPDEV/global/David.Huber/para/EXPDIR/test_rundirs/config.base /scratch1/NCEPDEV/global/David.Huber/para/EXPDIR/test_rundirs/config.base.orig
cp /scratch1/NCEPDEV/global/David.Huber/para/EXPDIR/test_rundirs/test_rundirs.xml /scratch1/NCEPDEV/global/David.Huber/para/EXPDIR/test_rundirs/test_rundirs.orig.xml
# Change
# export STMP="/scratch1/NCEPDEV/stmp2/${USER}"
# to
# export STMP="/scratch1/NCEPDEV/global/${USER}/para/stmp"
vim /scratch1/NCEPDEV/global/David.Huber/para/EXPDIR/test_rundirs/config.base
# Shows that DATAROOT now resides in /scratch1/NCEPDEV/global/David.Huber/para/stmp/RUNDIRS/test_rundirs
diff /scratch1/NCEPDEV/global/David.Huber/para/EXPDIR/test_rundirs/test_rundirs.*xml
```

**Comment by emilyhcliu** [comment]
> I am able to set `STMP` in `config.base` and the resulting XML updates to the new location. Here is the step-by-step I used:
> 
> ```shell
> git clone git@github.com:NOAA-EMC/global-workflow --recurse-submodules && cd global-workflow
> . ci/platform/config.hera
> export RUNTESTS=/scratch1/NCEPDEV/global/David.Huber/para && module use modulefiles && module load module_gwsetup.hera && cd workflow
> pslot=test_rundirs ./create_experiment -y ../ci/cases/pr/C96C48_hybatmDA.yaml
> cp /scratch1/NCEPDEV/global/David.Huber/para/EXPDIR/test_rundirs/config.base /scratch1/NCEPDEV/global/David.Huber/para/EXPDIR/test_rundirs/config.base.orig
> cp /scratch1/NCEPDEV/global/David.Huber/para/EXPDIR/test_rundirs/test_rundirs.xml /scratch1/NCEPDEV/global/David.Huber/para/EXPDIR/test_rundirs/test_rundirs.orig.xml
> # Change
> # export STMP="/scratch1/NCEPDEV/stmp2/${USER}"
> # to
> # export STMP="/scratch1/NCEPDEV/global/${USER}/para/stmp"
> vim /scratch1/NCEPDEV/global/David.Huber/para/EXPDIR/test_rundirs/config.base
> # Shows that DATAROOT now resides in /scratch1/NCEPDEV/global/David.Huber/para/stmp/RUNDIRS/test_rundirs
> diff /scratch1/NCEPDEV/global/David.Huber/para/EXPDIR/test_rundirs/test_rundirs.*xml
> ```

@DavidHuber-NOAA My config.base has "STMP" defined as the following:
```
export STMP="/work/noaa/stmp/${USER}/ORION"
```

The problem is that the following python script does not recognise "STMP"
https://github.com/NOAA-EMC/global-workflow/blob/1b18f2f97eec24a8b3f817b7ef1b4caa2be24937/workflow/rocoto/tasks.py#L64-L75

The `self._base.get('STMP')` is returned as `NONE` from line #65

I checked `self._base` which is a Python dictionary of variables from config.base.  The dictionary does not contain STMP.  (It has HOMEgfs, COMROOT, ROTDIR, ....etc).

**Comment by DavidHuber-NOAA** [comment]
@emilyhcliu Switching to Orion, I performed similar operations as above and added the line
```python
print(self._base.get("STMP"))
```
below line 65.  This time, I modified config.base in the workflow itself:
```diff
diff --git a/parm/config/gfs/config.base b/parm/config/gfs/config.base
index 544113f9..f60f3aef 100644
--- a/parm/config/gfs/config.base
+++ b/parm/config/gfs/config.base
@@ -56,7 +56,7 @@ export COMINukmet=@COMINukmet@
 
 # USER specific paths
 export HOMEDIR="@HOMEDIR@"
-export STMP="@STMP@"
+export STMP=/work/noaa/global/dhuber/para/stmp
 export PTMP="@PTMP@"
 export NOSCRUB="@NOSCRUB@"
```

Executing `create_experiment` yielded
```console
Finalizing initialize
sourcing config.prep
... more sourcings ...
sourcing config.metp
Source configs with RUN=gdas
/work/noaa/global/dhuber/para/stmp
Source configs with RUN=enkfgdas
/work/noaa/global/dhuber/para/stmp
Source configs with RUN=gfs
/work/noaa/global/dhuber/para/stmp
```

**Comment by DavidHuber-NOAA** [comment]
May I take a look at your experiment directory and your global-workflow directory?  You may need to run

```bash
chmod -R o+r /work2/noaa/da/eliu/ORION/para
find /work2/noaa/da/eliu/ORION/para -type d -exec  chmod o+x {} +;
```

A similar pair of commands would need to be run on your global-workflow directory.

**Comment by emilyhcliu** [comment]
> May I take a look at your experiment directory and your global-workflow directory? You may need to run
> 
> ```shell
> chmod -R o+r /work2/noaa/da/eliu/ORION/para
> find /work2/noaa/da/eliu/ORION/para -type d -exec  chmod o+x {} +;
> ```
> 
> A similar pair of commands would need to be run on your global-workflow directory.

@DavidHuber-NOAA Thanks for the tips and looking into this.
I performed the commands you suggested for my para and global-workflow directory.  They should be good to check now.

global-workflow: `/work/noaa/da/eliu/ORION/Global-Workflow/global-workflow`
expdir: `/work2/noaa/da/eliu/ORION/para/expdir/gdas_eval_2024_conv_ps_JEDI`

**Comment by DavidHuber-NOAA** [comment]
@emilyhcliu Thank you for running those commands.  Unfortunately, I am still not able to access your global-workflow.  Could you try running the following:

```bash log
chmod -R o+r /work/noaa/da/eliu/ORION/Global-Workflow
find /work/noaa/da/eliu/ORION/Global-Workflow -type d -exec chmod o+x {} +;
```

**Comment by DavidHuber-NOAA** [comment]
Also, as a side note, if you would like to allow all of your created files to have `o+r` and directories `o+rx`, you can add the following line to your `.bashrc`:
```.bashrc
umask 022
```
This will give write permissions to only you and read permissions to everyone.

EDIT: updated `umask` command

**Comment by DavidHuber-NOAA** [comment]
Apologies, that should be `umask 022`.

**Comment by emilyhcliu** [comment]
> ```shell
> find /work/noaa/da/eliu/ORION/Global-Workflow -type d -exec chmod o+x {} +;
> ```

OK.  The commands are running now.

**Comment by CoryMartin-NOAA** [comment]
Any update on this? I just tried an experiment on Orion from @DavidHuber-NOAA 's branch that should work on orion and got the same issue:
```
echo 'None/RUNDIRS/snowjcbtest/gdas.2021122012 does not exist. ABORT!' 
```

**Comment by ADCollard** [comment]
The issue appears to be related to variables that are already assigned in the user's .bashrc.  We all probably have $STMP set as an environment variable.

In [wxflow/configuration.py](https://github.com/NOAA-EMC/wxflow/blob/e1ef697430c09d2b1a0560f21f11c7a32ed5f3e2/src/wxflow/configuration.py) there is the following section:

```
   @classmethod
    def _get_script_env(cls, scripts: List, **envvars) -> Dict[str, Any]:
        default_env = cls._get_shell_env([])
        and_script_env = cls._get_shell_env(scripts, **envvars)
        vars_just_in_script = set(and_script_env) - set(default_env)
        union_env = dict(default_env)
        union_env.update(and_script_env)
        return dict([(v, union_env[v]) for v in vars_just_in_script])
```
The 5th line explicitly removes existing shell environment variables.

If I `unset STMP` the code completes successfully.

I assume this is designed to stop duplicate assignments?   Can this line be removed?

**Comment by CoryMartin-NOAA** [comment]
@ADCollard genius detective work! Indeed I have `$STMP` set on Orion but on Hera I have `$STMP(1-4)` set

**Comment by aerorahul** [comment]
@ADCollard 
If we remove this line, then every variable declared in the user environment will enter the global-workflow runtime environment.  It gets extremely difficult to identify the origin of variable declaration.
Unfortunately, there is no `purge` of the user shell environment equivalent like `module purge` as we do need some reserved variables.

I would recommend either removing `STMP` or declaring as `mySTMP` or `stmp` (lowercase).

**Comment by DavidHuber-NOAA** [comment]
Perhaps we can add an `Exception` in `setup_xml.py` for variables that should not be set at runtime.  This will help prevent these sort of issues.  Here are a few of the common culprits:

```
HOMEgfs
STMP
PTMP
HOMEDIR
PSLOT
```

**Comment by ADCollard** [comment]
> Perhaps we can add an `Exception` in `setup_xml.py` for variables that should not be set at runtime. This will help prevent these sort of issues. Here are a few of the common culprits:
> 
> ```
> HOMEgfs
> STMP
> PTMP
> HOMEDIR
> PSLOT
> ```

@DavidHuber-NOAA That sounds like a good idea to me as I think this is going to happen all the time.  And/or add a note to readthedocs?

**Comment by aerorahul** [comment]
This is not an issue just in `setup_xml.py`.  It will also be encountered when running jobs.
It is not sufficient to just check for reserved variables at setup time.

**Comment by ADCollard** [comment]
Can we at least put a check in `gw_setup.sh` to either unset these variables or to alert the user if these variables are already set through `.bashrc`?   I can just see this issue arising again and again unless we have something to alert users.

**Comment by aerorahul** [comment]
`gw_setup.sh` is just to detect the machine and load the modules.
One can load the modules for any number of reasons.  It is not in the scope of `gw_setup.sh` to check a users environment.

Also, how many variables should be wired in `gw_setup.sh`?  `HOMEgfs`, `STMP`, `PTMP`, `ACCOUNT`, `machine`, etc. 
It is not tractable to do so.

**Comment by CoryMartin-NOAA** [comment]
If this is going to stay as-is, with this requirement that a user's environment not have any variables set that are used in the g-w, then the documentation needs to be updated as such, with a warning that this could occur, to save future debugging troubles. I would suggest a list of 'commonly set ones' like @DavidHuber-NOAA mentioned but add some language about how this could be problematic for any variable and to just ensure your env is as clean as possible.

**Comment by aerorahul** [comment]
One cannot stop people from declaring their favorite variables in login scripts, just like we cannot prevent them from loading modules at login (a practice that every system administrator frowns upon).  It makes interacting with applications complicated.  
Documenting every variable used in the global-workflow is an impossible task (I hope that is not an exaggeration).  
Documenting a set of usual suspects is a start, but it won't be comprehensive.  We can add it to the documentation.

**Comment by aerorahul** [comment]
See 
https://global-workflow--2898.org.readthedocs.build/en/2898/errors_faq.html#error-reserved-variables-causing-workflow-issues
