### ISSUE TITLE
The IC files are not copyied from its source location to target location

### ISSUE THREAD

**Issue by emilyhcliu** [NOAA-EMC/global-workflow#2852]
### What is wrong?

The IC files are not copied from their source location to the target location while running the setup script - setup_expt.py
The COMROT is created, but it is empty.  

```
HOMEgfs=/work/noaa/da/eliu/ORION/Global-Workflow/global-workflow
workdir=/work2/noaa/da/eliu/ORION/para
ICSDIRBase=/work2/noaa/da/eliu/ICs/UFO_eval/data/para
ICSDIR=/work2/noaa/da/acollard/UFO_eval/data/para/output_ufo_eval_feb2024_9Aug
IDATE=2024021900
EDATE=2024021906
RESDETATMOS=768
CDUMP=gdas
PSLOTBase=gdas_eval_2024
PSLOT=${PSLOTBase}_conv_ps_JEDI
PSLOT=${PSLOTBase}_iasi_JEDI
CONFIGDIR=$HOMEgfs/parm/config/gfs
COMROOT=$workdir/comroot
EXPDIR=$workdir//expdir
```

```
$HOMEgfs/workflow/setup_expt.py gfs cycled --idate $IDATE --edate $EDATE --app ATM \
    --start warm --gfs_cyc 0  --resdetatmos $RESDETATMOS  --nens 0 \
    --run gdas --pslot ${PSLOT} --configdir $CONFIGDIR \
    --comroot $COMROOT --expdir $EXPDIR --icsdir $ICSDIR
```

### What should have happened?

The IC files should be copied over to the target location (ROTDIR) from the source location (ICSDIR)

### Steps to reproduce

1. Get a set of ICs for GFS (define and create your ICSDIR for step 2)
2. run the setup script - setup_expt.sh with the input arguments (see example above)
3. check the ROTDIR 

### Additional information

Nonw

### Do you have a proposed solution?

Not yet.  There are new updates related to the stage of initial conditions, but I have not looked at them in detail.

**Comment by emilyhcliu** [comment]
@KateFriedman-NOAA  I'm not sure who I should assign this issue to.

**Comment by RussTreadon-NOAA** [comment]
@emilyhcliu , I believe the behavior you are observing is due to PR #2651.  This PR was merged into `develop` yesterday.  @KateFriedman-NOAA sent an email with the subject line _[Global Workflow] Initial conditions staging job refactor_.

**Comment by KateFriedman-NOAA** [comment]
@emilyhcliu To add to @RussTreadon-NOAA 's comment, the PR that went into `develop` yesterday to refactor the staging job for ICs removed the IC staging/linking from the `setup_expt.py` step. So what you are seeing is intentional. When you set up a new experiment you should now see one or more `stage_ic` jobs in your xml which will either run in the first half cycle (e.g. `gdasstage_ic` and `enkfgdasstage_ic`) or at the beginning of each forecast-only cycle (e.g. `gfsstage_ic` or `stage_ic` for gefs). The new `stage_ic` jobs will run first and pull staged ICs into your `COMROT`. If you encounter any issues with the refactored `stage_ic` jobs, please open an issue to let us know, thanks!

**Comment by KateFriedman-NOAA** [comment]
@emilyhcliu Also, I see you are setting `ICSDIR` in your setup: `ICSDIR=/work2/noaa/da/acollard/UFO_eval/data/para/output_ufo_eval_feb2024_9Aug`
That path should land in your EXPDIR's `config.stage_ic` and the `stage_ic` job will pick them up from there. Ensure that your `ICSDIR` has the same folder structure as COM, the `stage_ic` job will expect that. Let me know if you have any questions.

**Comment by KateFriedman-NOAA** [comment]
Closing. Please feel free to open a new issue if you encounter any errors in the refactored `stage_ic` jobs. Thanks!

**Comment by emilyhcliu** [comment]
> @emilyhcliu Also, I see you are setting `ICSDIR` in your setup: `ICSDIR=/work2/noaa/da/acollard/UFO_eval/data/para/output_ufo_eval_feb2024_9Aug` That path should land in your EXPDIR's `config.stage_ic` and the `stage_ic` job will pick them up from there. Ensure that your `ICSDIR` has the same folder structure as COM, the `stage_ic` job will expect that. Let me know if you have any questions.

Yes, I do see that in my config.stage_ic.

**Comment by emilyhcliu** [comment]
> Closing. Please feel free to open a new issue if you encounter any errors in the refactored `stage_ic` jobs. Thanks!

@KateFriedman-NOAA  and @RussTreadon-NOAA  I got it.  I will look into the refactored way.  Thanks.
