### ISSUE TITLE
Explicitly disable hyper-threading on Hera, Hercules, and Orion

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/global-workflow#2863]
### What new functionality do you need?

Hera, Hercules, and Orion (and possibly Jet) enable hyper-threading by default.  This should be disabled explicitly by adding the `sbatch`/`srun` flag `--hint=nomultithread`.

### What are the requirements for the new functionality?

All jobs should run threaded tasks across cores, not within a single core's threads.

### Acceptance Criteria

Identical results without significant differences in run times.

### Suggest a solution (optional)

Add `--hint=nomultithread` to each `.env` file.

**Comment by guoqing-noaa** [comment]
Just curious, Will we run into any problems if we don't disable hyper-threading?

**Comment by DavidHuber-NOAA** [comment]
@guoqing-noaa Probably not.  There is only one case that I have been made aware of, but it does not affect the global application.  Regional apps (RRFS/HAFS) that read/write netCDF files in parallel within the GSI often experience errors while attempting to read and write from the same file when hyperthreading is enabled.  More details are available in https://github.com/NOAA-EMC/GSI/issues/694.
