### ISSUE TITLE
recent updates break ocean cycling at 0.25 degree resolution

### ISSUE THREAD

**Issue by jswhit** [NOAA-EMC/global-workflow#2864]
### What is wrong?

if `resdetocean=0.25` gdasstage_ic fails because of the logic in ocean.yaml.  This patch allows it to complete

```
diff --git a/parm/stage/ocean.yaml.j2 b/parm/stage/ocean.yaml.j2
index 75a472df..6dd9afcc 100644
--- a/parm/stage/ocean.yaml.j2
+++ b/parm/stage/ocean.yaml.j2
@@ -10,8 +10,8 @@ ocean:
         {% set imem = mem - first_mem %}
         {% set COMOUT_OCEAN_RESTART_PREV_MEM = COMOUT_OCEAN_RESTART_PREV_MEM_list[imem] %}
         - ["{{ ICSDIR }}/{{ COMOUT_OCEAN_RESTART_PREV_MEM | relpath(ROTDIR) }}/{{ m_prefix }}.[MOM.res.nc](http://mom.res.nc/)", "{{ COMOUT_OCEAN_RESTART_PREV_MEM }}"]
-        {% if OCNRES == "025" %}
-        {% for nn in range(1, 3) %}
+        {% if OCNRES == 25 or OCNRES == "025" %}
+        {% for nn in range(1, 4) %}
         - ["{{ ICSDIR }}/{{ COMOUT_OCEAN_RESTART_PREV_MEM | relpath(ROTDIR) }}/{{ m_prefix }}.MOM.res_{{ nn }}.nc", "{{ COMOUT_OCEAN_RESTART_PREV_MEM }}"]
         {% endfor %}
         {% endif %}
```

However, it seems like OCNRES should not be an integer (it should be converted to a string with a 0 prepended).  I believe there may be other places in the workflow where OCNRES is an integer but is treated as a string (and either used to build a filename, or is compared to a string '025')

### What should have happened?

the ocean restart files should have been staged to the COMROOT directory

### What machines are impacted?

All or N/A

### Steps to reproduce

run a cycling experiment with ocean DA enabled and resdetocean set to 0.25

### Additional information

N/A

### Do you have a proposed solution?

no

**Comment by KateFriedman-NOAA** [comment]
This was just reported to me via another user and I have the same fix. Will submit PR to `develop` to resolve. Thanks for opening this issue @jswhit !

**Comment by jswhit** [comment]
@KateFriedman-NOAA that's great - but I don't think using `{% if OCNRES == 25 or OCNRES == "025" %}` is the right fix. It's masking the underlying problem that OCNRES is sometimes an integer and sometimes a string with 0 prepended.

**Comment by jswhit** [comment]
I noticed that `pygfs.task.Analysis.__init__` has 
```python
        # fix ocnres
        self.task_config.OCNRES = f"{self.task_config.OCNRES :03d}"
```
This probably needs to be added to ush/python/pygfs/task/snow_analysis.py and snowens_analysis.py.

**Comment by KateFriedman-NOAA** [comment]
Thanks for finding that @jswhit ! That looks like what we'll need for this fix. Just got out of a meeting, gonna work on this and look at #2865 now.

**Comment by jswhit** [comment]
should probably replace `{%elif OCNRES == 25 or OCNRES == "025" %}` with `{% elif OCNRES == "025" %}` in `parm/archive/ocean_grib2.yaml.j2` once this is fixed

**Comment by KateFriedman-NOAA** [comment]
> should probably replace `{%elif OCNRES == 25 or OCNRES == "025" %}` with `{% elif OCNRES == "025" %}` in `parm/archive/ocean_grib2.yaml.j2` once this is fixed

Yep! I spoke with @DavidHuber-NOAA and he's going to make a similar update for the archive yaml. Thanks!
