### ISSUE TITLE
Add the snow observation files to global GDA for GFSv17 retrospective experiments

### ISSUE THREAD

**Issue by jiaruidong2017** [NOAA-EMC/global-workflow#2879]
### Target fix directory

DUMP

### Type of change

- [ ] Update existing files
- [ ] Remove files
- [X] Add new files to existing directory
- [ ] Add new fix directory

### Any workflow changes needed?

No change needed

### Related issues

This will provide the required observation files for fv3jedi snow DA in GFSv17 retrospective experiments. 

### Pickup location

/scratch1/NCEPDEV/stmp4/Jiarui.Dong/glopara/dump/

### Size

99G

**Comment by jiaruidong2017** [comment]
FYI @CoryMartin-NOAA @CatherineThomas-NOAA

**Comment by CoryMartin-NOAA** [comment]
This isn't a fix file addition but rather obs added to the dump archive, correct? (mainly asking for clarification)

**Comment by jiaruidong2017** [comment]
Yes. I didn't see the template for staging obs, thus I selected this one.

**Comment by WalterKolczynski-NOAA** [comment]
This is the closest issue type, so fine with that choice, though would be good in the future to be clear that it is for dump when specifying the target directory.

**Comment by KateFriedman-NOAA** [comment]
@jiaruidong2017 I am pulling these new dump files into the GDA on Hera now. Questions:

1. Do you need these files in the WCOSS2 GDA as well?
2. Do you have these files archived on HPSS?

**Comment by jiaruidong2017** [comment]
> @jiaruidong2017 I am pulling these new dump files into the GDA on Hera now. Questions:
> 
> 1. Do you need these files in the WCOSS2 GDA as well?
> 2. Do you have these files archived on HPSS?

Thanks @KateFriedman-NOAA for your efforts. These observation files just contribute to the retrospective experiments. Therefore, for your first question, I think @CatherineThomas-NOAA may answer you. For the second question, I didn't archive them into HPSS.

**Comment by KateFriedman-NOAA** [comment]
I have finished copying the provided dump files into the GDA on Hera. Here is a sample showing the files for a randomly selected date from the bunch (any file that has "sno" in the name, so previously existing files are also shown):
```
[role.glopara@hfe12 glopara]$ ll dump/gfs.20220507/00/atmos/*sno*                                                                                                         
-rw-r--r-- 1 role.glopara global 37756486 Aug 16 22:49 dump/gfs.20220507/00/atmos/gfs.t00z.imssnow96.asc
-rw-r--r-- 1 role.glopara global 10267267 May  7  2022 dump/gfs.20220507/00/atmos/gfs.t00z.imssnow96.grib2
-rw-r--r-- 1 role.glopara global 29752192 Aug 16 23:02 dump/gfs.20220507/00/atmos/gfs.t00z.sfcsno.tm00.bufr_d
-rw-r--r-- 1 role.glopara global   938487 Aug 16 22:55 dump/gfs.20220507/00/atmos/gfs.t00z.snocvr_snow.nc4
-rw-r--r-- 1 role.glopara global  5561592 May  7  2022 dump/gfs.20220507/00/atmos/gfs.t00z.snogrb_t1534.3072.1536
```
Will copy them to the GDA on WCOSS2 as well if needed.

**Comment by CatherineThomas-NOAA** [comment]
We're only setup to run the cycling prototypes on Hera at the moment.  If we want to run on WCOSS, we'll need to get other glopara obs synced as well, so we can handle that all together later.  No need to sync now.

**Comment by KateFriedman-NOAA** [comment]
> We're only setup to run the cycling prototypes on Hera at the moment. If we want to run on WCOSS, we'll need to get other glopara obs synced as well, so we can handle that all together later. No need to sync now.

Okie dokie, sounds good! Closing this as complete then.
