### ISSUE TITLE
Resources are not being properly set for analysis jobs (and possibly others)

### ISSUE THREAD

**Issue by TravisElless-NOAA** [NOAA-EMC/global-workflow#2916]
### What is wrong?

Setting up a cycled C384/C192 run on Hera using the default resource configs results in a analysis job resource of `<nodes>40:ppn=4:tpp=10</nodes`, which is the incorrect resource allocation needed for this job. 

### What should have happened?

The correct resource allocation for this job on Hera should be `<nodes>54:ppn=5:tpp=8</nodes>`.  

### What machines are impacted?

All or N/A, Hera

### Steps to reproduce

1. Create a C384 cycled experiment on Hera using the default config.resources
2. Check resource allocation for the analysis job

### Additional information

The difference for this case appears to stem from variables being incorrectly named in https://github.com/NOAA-EMC/global-workflow/blob/develop/parm/config/gfs/config.resources.HERA#L8C1-L10C73 where `ntasks` should be 2 different variables `ntasks_gdas` and `ntasks_gfs`, and `threads_per_task_anal` should be `threads_per_task`. 

Not sure if this inconsistency is specific to just this job or if other jobs could have similar inconsistencies.

**Comment by TravisElless-NOAA** [comment]
FYI @CatherineThomas-NOAA

**Comment by DavidHuber-NOAA** [comment]
@TravisElless-NOAA How many tasks should there be for the gdas and gfs analyses?  Or should they be the same?

**Comment by DavidHuber-NOAA** [comment]
I performed an inventory of all variables set and referenced in config.resources.* and found just one other incorrect instance in `config.resources.S4`.  I have made these changes and added them to #2819.  Would you mind testing this solution on Hera @TravisElless-NOAA?

**Comment by TravisElless-NOAA** [comment]
Thanks for reviewing the files and making these changes @DavidHuber-NOAA. The changes in #2819 allow for the correct resources to be set for the anal jobs on Hera.
