### ISSUE TITLE
Unexpected keyword error

### ISSUE THREAD

**Issue by benjamin-cash** [NOAA-EMC/global-workflow#2932]
### What is wrong?

```
[cash@hercules-login-3 workflow]$ ./setup_xml.py /work/noaa/nems/cash/UFS-coupled/C384mx025_19940501
Finalizing initialize
Traceback (most recent call last):
  File "/work/noaa/nems/cash/global-workflow/workflow/./setup_xml.py", line 79, in <module>
    main()
  File "/work/noaa/nems/cash/global-workflow/workflow/./setup_xml.py", line 70, in main
    app_config = app_config_factory.create(f'{net}_{mode}', cfg)
  File "/home/cash/.local/lib/python3.10/site-packages/wxflow/factory.py", line 71, in create
    return self._builders[key](*args, **kwargs)
  File "/work/noaa/nems/cash/global-workflow/workflow/applications/applications.py", line 22, in __call__
    obj._init_finalize(*args, **kwargs)
  File "/work/noaa/nems/cash/global-workflow/workflow/applications/applications.py", line 104, in _init_finalize
    self.configs = {'_no_run': self._source_configs(conf)}
  File "/work/noaa/nems/cash/global-workflow/workflow/applications/applications.py", line 158, in _source_configs
    configs['base'] = conf.parse_config('config.base', RUN=run)
TypeError: Configuration.parse_config() got an unexpected keyword argument 'RUN'
```

### What should have happened?

./setup_xml.py to run  to completion

### What machines are impacted?

Hercules

### Steps to reproduce

1. ./setup_expt.py gefs forecast-only --idate 1994050100 --edate 1994053100 --app S2S --start cold --gfs_cyc 1 --resdetatmos 384 --resdetocean 0.25 --comroot /work/noaa/nems/cash/UFS-coupled/comrot --expdir /work/noaa/nems/cash/UFS-coupled --pslot C384mx025_19940501
2. ./setup_xml.py /work/noaa/nems/cash/UFS-coupled/C384mx025_19940501

### Additional information

I have encountered this particular error on my local cluster as well.

**Comment by DavidHuber-NOAA** [comment]
@benjamin-cash I suspect that you are working with an older `wxflow` submodule.  Can you try updating wxflow to the what is currently in global-workflow develop ([e1ef697](https://github.com/NOAA-EMC/wxflow/tree/e1ef697430c09d2b1a0560f21f11c7a32ed5f3e2))?

**Comment by benjamin-cash** [comment]
Hi @DavidHuber-NOAA - I think it must have been a module issue of some kind. This also applies to #2930 (@WalterKolczynski-NOAA ). I pulled a clean copy of global-workflow from develop in a new session, sourced gw_setup.sh, and it ran without issue. I then went back to my fork, reloaded all of the modules, and it also ran without issue. I will close both issues now. :)

**Comment by benjamin-cash** [comment]
Closing
