### ISSUE TITLE
Updated aerosol climatology not reflected in fix files

### ISSUE THREAD

**Issue by benjamin-cash** [NOAA-EMC/global-workflow#2936]
### What is wrong?

My latest C96mx100 test failed with the following:

+ forecast_predet.sh[501]: /bin/cp -p /groups/BCASH/global-workflow/fix/aer/merra2.aerclim.2014-2023.m01.nc aeroclim.m01.nc
/bin/cp: cannot stat '/groups/BCASH/global-workflow/fix/aer/merra2.aerclim.2014-2023.m01.nc': No such file or directory

### What should have happened?

The updated climatology file that the workflow is looking for is not present in fix/aer/20220805, which is the version of aer/fix set in fix.ver. The updated climo files do not appear to be present in https://noaa-nws-global-pds.s3.amazonaws.com/index.html#fix/aer/ or /work/noaa/global/glopara/fix/aer on Hercules.

### What machines are impacted?

All or N/A

### Steps to reproduce

./link_workflow with aer.ver set to 20220805

### Additional information

Where can I find the updated climo files, and can the fix version be updated so that they can be located correctly?

**Comment by WalterKolczynski-NOAA** [comment]
The file is there:
```
>ls /work/noaa/global/glopara/fix/aer/20220805/merra2.aerclim.2014-2023.m01.nc
/work/noaa/global/glopara/fix/aer/20220805/merra2.aerclim.2014-2023.m01.nc
```

**Comment by benjamin-cash** [comment]
Thanks @WalterKolczynski-NOAA - that is really weird but you're 100% right. Looks like it is just the AWS bucket that needs to be updated.

**Comment by KateFriedman-NOAA** [comment]
> Looks like it is just the AWS bucket that needs to be updated.

I have synced the S3 copy, thanks for letting us know @benjamin-cash !

**Comment by WalterKolczynski-NOAA** [comment]
@KateFriedman-NOAA is working on synchronizing the bucket.
