### ISSUE TITLE
stage atm_stoch.res.nc and ocn_stoch.res.nc during segment forecasts

### ISSUE THREAD

**Issue by NeilBarton-NOAA** [NOAA-EMC/global-workflow#2937]
### What new functionality do you need?

When running ensembles in segments (i.e., restarting the model), the stoch restart files are needed to start the model with the same stochastic state. 

### What are the requirements for the new functionality?

atm_stoch.res.nc and ocn_stoch.res.nc files need to be used in a re-run or segment ensemble forecast 

### Acceptance Criteria

atm_stoch.res.nc and ocn_stoch.res.nc files are used in segment forecasts and forecasts that re-start

**Comment by WalterKolczynski-NOAA** [comment]
@pjpegion I've updated workflow so the `atm_stoch.res.nc` and `ocn_stoch.res.nc` files are copied into the INPUT directory, but they don't appear to be used when the model is initialized:
```
Initialize random pattern for SPPT
 0:  calling init         504         248          82
 0:  using seed -1792974973        20210323120003
 0:  using seed -1792974972        20210323120004
 0:  using seed -1792974971        20210323120005
 0:  using seed -1792974970        20210323120006
 0:  using seed -1792974969        20210323120007
 0:  Initialize random pattern for SKEB
 0:  using seed -1792974975        20210323120001
 0:  using kenorm    1.00000000000000       0.000000000000000E+000
```

Is there a namelist setting or something I need, or am I misinterpreting the log?
