### ISSUE TITLE
Add enkfgdas.20210324 to ICSDIR/C48mx500

### ISSUE THREAD

**Issue by AndrewEichmann-NOAA** [NOAA-EMC/global-workflow#2945]
### Target fix directory

NEW

### Type of change

- [ ] Update existing files
- [ ] Remove files
- [X] Add new files to existing directory
- [ ] Add new fix directory

### Any workflow changes needed?

No change needed

### Related issues

For the WCDA CI tests
Addresses: https://github.com/NOAA-EMC/GDASApp/issues/1091 and https://github.com/NOAA-EMC/GDASApp/issues/1251
Dependencies: https://github.com/NOAA-EMC/global-workflow/pull/2944 and https://github.com/NOAA-EMC/GDASApp/pull/1287

### Pickup location

/scratch1/NCEPDEV/da/Andrew.Eichmann/ICSDIR/C48mx500ens/enkfgdas.20210324

### Size

2.900 MB

**Comment by KateFriedman-NOAA** [comment]
@AndrewEichmann-NOAA I have rsync'd the new `enkfgdas.20210324` folder/files into the `../ICSDIR/C48mx500/20240610` IC folder on Hera. See here: `/scratch1/NCEPDEV/global/glopara/data/ICSDIR/C48mx500/20240610`

Please confirm I have copied them as requested and we'll sync them to the other supported platforms. Thanks!

**Comment by AndrewEichmann-NOAA** [comment]
They are indeed copied. Testing revealed that I neglected two more files: `gdas.t12z.atmi003.nc` and `gdas.t12z.atmi009.nc` in `/scratch1/NCEPDEV/da/Andrew.Eichmann/ICSDIR/C48mx500ens/gdas.20210324/12/analysis/atmos`, to be copied to `/scratch1/NCEPDEV/global/glopara/data/ICSDIR/C48mx500/20240610/gdas.20210324/12/analysis/atmos/`. Can this be done under this PR?

**Comment by KateFriedman-NOAA** [comment]
> They are indeed copied. Testing revealed that I neglected two more files: `gdas.t12z.atmi003.nc` and `gdas.t12z.atmi009.nc` in `/scratch1/NCEPDEV/da/Andrew.Eichmann/ICSDIR/C48mx500ens/gdas.20210324/12/analysis/atmos`, to be copied to `/scratch1/NCEPDEV/global/glopara/data/ICSDIR/C48mx500/20240610/gdas.20210324/12/analysis/atmos/`. Can this be done under this PR?

@AndrewEichmann-NOAA Certainly! I have pulled those two additional files into the `gdas.20210324` folder:
```
[role.glopara@hfe05 atmos]$ pwd
/scratch1/NCEPDEV/global/glopara/data/ICSDIR/C48mx500/20240610/gdas.20210324/12/analysis/atmos
[role.glopara@hfe05 atmos]$ ll
total 2556300
-rw-r--r-- 1 role.glopara global      972949 Nov 17  2023 gdas.t12z.abias
-rw-r--r-- 1 role.glopara global     1249677 Nov 17  2023 gdas.t12z.abias_air
-rw-r--r-- 1 role.glopara global      972949 Nov 17  2023 gdas.t12z.abias_int
-rw-r--r-- 1 role.glopara global     1038394 Nov 17  2023 gdas.t12z.abias_pc
-rw-r--r-- 1 role.glopara global    84290668 Sep 20 14:51 gdas.t12z.atmi003.nc
-rw-r--r-- 1 role.glopara global    84290668 Sep 20 15:34 gdas.t12z.atmi009.nc
-rw-r--r-- 1 role.glopara global    84290668 Nov 17  2023 gdas.t12z.atminc.nc
-rw-r----- 1 role.glopara rstprod 2360483840 Nov 17  2023 gdas.t12z.radstat
```

Let me know if that's it and we'll sync the new IC files to the other supported platforms. Thanks!

**Comment by AndrewEichmann-NOAA** [comment]
@KateFriedman-NOAA Thank you. I'll run a test with the default ICSDIR setting and sign off on it.

**Comment by AndrewEichmann-NOAA** [comment]
@KateFriedman-NOAA Ok, looks good. Thank you!

**Comment by KateFriedman-NOAA** [comment]
Thanks for checking and confirming @AndrewEichmann-NOAA !

We'll sync the files to the other supported platforms and then close this issue once complete.

@WalterKolczynski-NOAA please sync the following to MSU:
```
/scratch1/NCEPDEV/global/glopara/data/ICSDIR/C48mx500/20240610/enkfgdas.20210324
/scratch1/NCEPDEV/global/glopara/data/ICSDIR/C48mx500/gdas.20210324
```
You should just see two atmiFFF.nc files sync over with the 2nd folder. The first folder is brand new so you'll see many files sync with it.

**Comment by KateFriedman-NOAA** [comment]
I have synced the new ICs files to WCOSS2 and Jet.

**Comment by WalterKolczynski-NOAA** [comment]
Synchronized to MSU.

**Comment by KateFriedman-NOAA** [comment]
Also synced to AWS. Closing as complete.

**Comment by AndrewEichmann-NOAA** [comment]
Thank you @KateFriedman-NOAA and @WalterKolczynski-NOAA !
