### ISSUE TITLE
Make the marine_da_utils run method more flexible

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/global-workflow#2950]
### What new functionality do you need?

The `run` method should be able to take in both the `Executable` and the command line arguments as a list, following e.g. [wxflow's Htar class](https://github.com/NOAA-EMC/wxflow/blob/799d55b30ec75f6d8a3c39ec8281dc6b28069a07/src/wxflow/htar.py#L23-L55).

### What are the requirements for the new functionality?

Marine DA `Executable` instances should not specify `default_args` except when those executables are reused.

### Acceptance Criteria

DA job outputs are unchanged.

### Suggest a solution (optional)

Something like

 to something like

```python
    def run(self, arg_list: list, silent: bool = False) -> str:

        # Remove any empty arguments which can cause issues for running an Executable
        arg_list = [arg for arg in arg_list if arg != ""]

        if silent:
            output = self.exe(*arg_list, output=str, error=str)
        else:
            output = self.exe(*arg_list, output=str.split, error=str.split)

        return output
```

**Comment by DavidNew-NOAA** [comment]
When I incorporate the ```Jedi``` class into the marine jobs (see https://github.com/NOAA-EMC/global-workflow/issues/2931), it will be using the ```execute``` from that class for running JEDI-based applications. (see https://github.com/NOAA-EMC/global-workflow/blob/ec634926f3b1ba1984b0735e17b76869659ceabe/ush/python/pygfs/jedi/jedi.py#L101)

**Comment by DavidHuber-NOAA** [comment]
Good to know, thanks!  I will close this as not planned in favor of #2931 then.
