### ISSUE TITLE
[NCO Bug] GEFS - Remove WF_ABBA from chem_prep job

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#2975]
### What is wrong?

From NCO:
```
On WCOSS2, WF_ABBA data is discontinued and no longer being used in GEFS.

However, the chem_prep_emission job still checks for WF_ABBA and returns a warning message.

"WARNING: NO WF_ABBA DATA FOUND!"

Please remove the warning message and the check process in the future upgrade.
```

### What should have happened?

GEFS should not use WF_ABBA data and there should be no warning message about it.

### Steps to reproduce

-

### Bugzilla issue

1331

### Additional information

-

**Comment by WalterKolczynski-NOAA** [comment]
I think this issue is moot since the old emissions prep has been replaced.

**Comment by KateFriedman-NOAA** [comment]
> I think this issue is moot since the old emissions prep has been replaced.

Noted in the actual bugzilla and our tracking speadsheet. Closing this.
