### ISSUE TITLE
Remove Hera MOD_PATH from build scripts

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#298]
Jen Yang 2021-03-12 13:51:07 UTC
There are some hardcoded path refer to Hera location in gfs build scripts and some make files in gfs.v16.0.  Please clean them up. 
Here are some example, please check the other files that are not listed here as well.  

The following build scripts point the MOD_PATH to hera location as:
"export MOD_PATH=/scratch3/NCEPDEV/nwprod/lib/modulefiles"

build_enkf_chgres_recenter_nc.sh
build_enkf_chgres_recenter.sh
build_fv3nc2nemsio.sh
build_fv3.sh
build_gaussian_sfcanl.sh
build_gfs_bufrsnd.sh
build_gfs_fbwndgfs.sh
build_gfs_wafs.sh
build_gldas.sh
build_gsi.sh
build_ncep_post.sh
build_regrid_nemsio.sh
build_tropcy_NEMS.sh

The MOD_PATH (and USE_PREINST_LIBS ) is not used in the building process, but the messages in build log is comfusing, and it should be cleaned up in the build scripts.

The following makefiles also points to Hera area. Please fix it.

gsi.fd/util/Misc/Makefile:COREINC       = /scratch1/portfolios/NCEPDEV/da/save/Michael.Lueken/nwprod/incmod
gsi.fd/util/Misc/Makefile:CORELIB       = /scratch1/portfolios/NCEPDEV/da/save/Michael.Lueken/nwprod/lib

Also please notes that "No absolute paths to libraries in production makefiles and no hardcoded path point to development area in makefile or build scripts", please follow this rule in the source code packages.

Th above issues can be fixed in the next upgrade.

Refs: [Bugzilla #1222](http://www2.spa.ncep.noaa.gov/bugzilla/show_bug.cgi?id=1222)

**Comment by lgannoaa** [comment]
@RussTreadon-NOAA @MichaelLueken-NOAA , I applied a fix for this issue. The gsi build is completed. Executable are in Global Workflow develop branch (2adf12381) Hera:/scratch1/NCEPDEV/global/Lin.Gan/git/issue-298/sorc/gsi.fd/exec and build log is in: Hera:/scratch1/NCEPDEV/global/Lin.Gan/git/issue-298/sorc/gsi_build.log.
Would you please take a look to be sure the build does not have hidden failure? Thanks

**Comment by MichaelLueken** [comment]
@lgannoaa I have looked at the contents of /scratch1/NCEPDEV/global/Lin.Gan/git/issue-298/sorc/gsi_build.log and did not see any error messages.  Additionally, all of the expected executables are present in /scratch1/NCEPDEV/global/Lin.Gan/git/issue-298/sorc/gsi.fd/exec.  The fix works!
