### ISSUE TITLE
Makefiles need to support debug and clean

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#300]
This is a tracking issue to monitor the progress of updating makefiles from packages used by global-workflow. This issue should link to the corresponding GitHub issues in the offending packages to ensure all are addressing this issue.

Jen Yang 2021-03-12 06:46:05 UTC
Scanned the makefiles in gfs.v16.0 source code package, and found the following makefiles missing debug or clean target. Please update the makefiles to add the debug or clean target. This can be addressed in the next major upgrade.

## Missing debug target:

- [ ] **ufs-weather-model** - @junwang-noaa 
- [ ] **UPP** - @WenMeng-NOAA 
- [ ] **EMC_gfs_wafs** - @YaliMao-NOAA 
- [ ] **GLDAS** - @HelinWei-NOAA 
- [ ] **GSI** - @dtkleist 
- [ ] **GSI-util** - @dtkleist
- [ ] **GSI-monitor** - @dtkleist 
- [ ] **gfs-utils** - @KateFriedman-NOAA 
- [ ] **UFS_UTILS** - @GeorgeGayno-NOAA 

## Missing clean target:

- [ ] **GSI** - @dtkleist 
- [ ] **GSI-util** - @dtkleist
- [ ] **GSI-monitor** - @dtkleist 
- [ ] **UFS_UTILS** - @GeorgeGayno-NOAA 

Refs: [Bugzilla #1218](http://www2.spa.ncep.noaa.gov/bugzilla/show_bug.cgi?id=1218)

**Comment by WalterKolczynski-NOAA** [comment]
Assigned to Arun since this will require management of several projects.

**Comment by WalterKolczynski-NOAA** [comment]
I'm also fairly certain some of these makefiles are not used in production.

**Comment by JessicaMeixner-NOAA** [comment]
The following make files: 
fv3gfs.fd/WW3/regtests/ww3_tp2.14/input/toy/Makefile
fv3gfs.fd/WW3/regtests/ww3_tp2.14/input/oasis3-mct/lib/mct/mct/Makefile
fv3gfs.fd/WW3/regtests/ww3_tp2.14/input/oasis3-mct/lib/mct/mpeu/Makefile
fv3gfs.fd/WW3/regtests/ww3_tp2.14/input/oasis3-mct/lib/mct/doc/Makefile
fv3gfs.fd/WW3/regtests/ww3_tp2.14/input/oasis3-mct/lib/mct/doc/texsrc/Makefile
fv3gfs.fd/WW3/regtests/ww3_tp2.14/input/oasis3-mct/lib/mct/examples/climate_concur1/Makefile
fv3gfs.fd/WW3/regtests/ww3_tp2.14/input/oasis3-mct/lib/mct/examples/simple/Makefile
fv3gfs.fd/WW3/regtests/ww3_tp2.14/input/oasis3-mct/lib/mct/examples/climate_sequen1/Makefile
fv3gfs.fd/WW3/regtests/ww3_tp2.14/input/oasis3-mct/lib/scrip/src/Makefile
fv3gfs.fd/WW3/regtests/ww3_tp2.14/input/oasis3-mct/lib/psmile/src/Makefile

Are not used in production.  If having these makefiles in the source code are going to be an issue, we'll have to figure out something in the wave model repo to deal with this.

**Comment by aerorahul** [comment]
> 

@JessicaMeixner-NOAA 
These files listed above by you don't need to be included in the update.  We will communicate w/ NCO on further guidance.

**Comment by KateFriedman-NOAA** [comment]
Updated issue main comment to list component POCs and add checkmarks next to each file.

**Comment by WenMeng-NOAA** [comment]
>gfs_post.fd/parm/makefile
This makefile is used for converting UPP control file from xml to txt via Perl scripts. It is not the part of UPP source code.

**Comment by arunchawla-NOAA** [comment]
@WenMeng-NOAA why dont we just use a txt control file to begin with ?

**Comment by arunchawla-NOAA** [comment]
I would not like to remove a regression test system from a repository. Since these are not part of the UFS build system it should hopefully not be an issue for operations. @JessicaMeixner-NOAA just out of curiosity and perhaps an action item for future ww3, these tests should probably have a debug build option ( not an issue for NWS as we do not use OASIS)

**Comment by JessicaMeixner-NOAA** [comment]
@arunchawla-NOAA valid point, I added a WW3 issue https://github.com/NOAA-EMC/WW3/issues/635 I think this might become a moot point with the move to cmake, but I don't know the full details so I made an issue just incase.

**Comment by WenMeng-NOAA** [comment]
@arunchawla-NOAA The txt control is not in human-friendly format for defining variables output from UPP. The [parm/makefile](https://github.com/NOAA-EMC/UPP/blob/release/gfs_v16/parm/makefile) isn't in UPP source code part and isn't involved in  UPP build time and run time. It's not a traditional makefile for compiling fortran code. I would think no debug target needed.

**Comment by arunchawla-NOAA** [comment]
thanks @WenMeng-NOAA so this is not used in operations right ? You only need it to set the configuration for an operational system. Am I reading that correctly ? If that is the case then that is the reason we can use

**Comment by WenMeng-NOAA** [comment]
@arunchawla-NOAA That's right. This script is handy for updating operational UPP control files, e.g. GFS, GEFS, RRFS, HAFS.

**Comment by GeorgeGayno-NOAA** [comment]
Do I need to update the latest UFS_UTILS tag that supports GFS v16. I can do that under: https://github.com/ufs-community/UFS_UTILS/issues/629. Some of the programs listed are not used by global-workflow, so I can simply remove them.

The head of 'develop' uses CMake and includes a 'debug' option. So if this can wait until the "next major upgrade" do I need to do anything?

**Comment by WalterKolczynski-NOAA** [comment]
PR #905 adds a debug option at the gw-level for UFS via the UFS's build script. I assume that takes care of most of the UFS concerns (we build WW3 pre/post separately, so that may still need to be addressed).

**Comment by JessicaMeixner-NOAA** [comment]
@WalterKolczynski-NOAA yes, WW3 pre/post will need a debug type option built into the scripts.  It's capable of being built in debug mode, but needs the easy functionality like what was just added for UFS.

**Comment by aerorahul** [comment]
The only ones that don't have `clean` and `debug` are the ones w/o `CMake` 
Those would be:
EMC_gfs_wafs -  A PR is open [#NOAA-EMC/EMC_gfs_wafs](https://github.com/NOAA-EMC/EMC_gfs_wafs/pull/10) @YaliMao-NOAA 
GLDAS -- GLDAS will be retired in v17 (allegedly)

**Comment by WalterKolczynski-NOAA** [comment]
Even if the cmake builds support using debug, we need to make sure the individual `build_*.sh` scripts and `build_all.sh` accept a `-d` option to use it (some already do, but others don't).

**Comment by HenryRWinterbottom** [comment]
@WalterKolczynski-NOAA @aerorahul I checked that all `global-workflow/sorc/build_*.sh` now include the the `-d` option to turn on/off `BUILD_DEBUG` in the following offending scripts:

- `build_ufs_utils.sh`
- `build_ww3prepost.sh`

Is it safe to assume that the other sources listed [here](https://github.com/NOAA-EMC/global-workflow/issues/300#issue-830303388) are beyond the scope of this PR?

**Comment by WalterKolczynski-NOAA** [comment]
@KateFriedman-NOAA Would you please update the bugzilla spreadsheet and issue?

**Comment by KateFriedman-NOAA** [comment]
I have updated our bugzilla spreadsheet to mark it as RESOLVED. I have also updated the actual bugzilla to note our work, provide links to the associated global-workflow issue/PR, and change the status to RESOLVED/FIXED for NCO to review for closure when the time comes.
