### ISSUE TITLE
GFSv16.1 global-workflow changes

### ISSUE THREAD

**Issue by CatherineThomas-NOAA** [NOAA-EMC/global-workflow#301]
The GFSv16.1 implementation incorporates the newly purchased commercial GNSSRO data from Delivery Order 2 (DO-2).  This will require changes in the DA as well as changes to config files.

As of 3/16, the workflow package needs to be delivered by 4/27 with implementation scheduled for 5/18.  

Work will be done in release/gfsv16.1, which will be created once GFSv16 is implemented in operations and release/gfsv16.0.0 is merged back to the operations branch.

DA development is being captured in [GSI issue #120.](https://github.com/NOAA-EMC/GSI/issues/120)

**Comment by KateFriedman-NOAA** [comment]
Created branch release/gfsv16.1 for this work. Created from release/gfsv16.0.0_to_ops branch; will need to sync with operations branch once merge of release/gfsv16.0.0_to_ops into operations completes.

https://github.com/NOAA-EMC/global-workflow/tree/release/gfsv16.1

**Comment by RussTreadon-NOAA** [comment]
**Description of changes committed at 88c54d9**

Three files were changed at 88c54d9 as described below: 

**jobs/rocoto/arch.sh**
Fit2Obs needs a subset of gdas files.   Scripting is added to `arch.sh` to retain these files.   These changes represent option 1 discussed in workflow issue #311.   The section of `arch.sh` saving gfs files for Fit2Obs is cleaned up.   Scripting is added to completely remove `$ROTDIR/$CDUMP.$rPDY` where `rPDY` is the older of two dates derived from `RMOLDSTD` or `FHMAX_GFS`.
  
**jobs/rocoto/earc.sh**
 Scripting is added to completely remove `$ROTDIR/enkf$CDUMP.$rPDY` where `rPDY` is the older of two dates derived from `RMOLDSTD_ENKF` or `FHMAX_GFS`.

**sorc/build_gsi.sh**
The pruned option for the NCO install of GFS DA is added to `build_gsi.sh`   As committed at 88c54d9 this option remains commented out.   The pruned installation option is described in [NOAA-EMC/GSI issue #137](https://github.com/NOAA-EMC/GSI/issues/137).  [Click here](https://github.com/NOAA-EMC/GSI/issues/137#issuecomment-815107147) to directly jump to the pertinent section of this issue.

None of the above changes alter GFS v16.1 DA results.

**Comment by KateFriedman-NOAA** [comment]
From last Friday's RFC memo:

```
RFC 8196 - On WCOSS, implement the GFS v16.1.1 upgrade to begin assimilating GPS radio occultation (GPS-RO) data from
GeoOptics for all forecasts as long as the data are available. This upgrade also addresses several bugs from v16.0.0:
● 2021 tropical storm update
● Fixes the calculation of the layer height increment
● Includes RW-NH* boundary points in the wave component
● Fixes the East Pacific wave grid interpolation to include all American Samoa islands
● Unmasks the Gulf of California, Red Sea and Persian Gulf in 0p25 global interpolated wave output grids
● Fixes a bitmask issue in 0p25 deg blended WAFS icing and turbulence products below 500 hPa.

To be implemented on May 18 at 1415Z.
```

**Comment by KateFriedman-NOAA** [comment]
SCN: https://www.weather.gov/media/notification/pdf2/scn21-52_gfsv16.1.1.pdf
