### ISSUE TITLE
update fix/gdas/fv3files

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/global-workflow#3012]
### Type of static data

Fix

### Target directory

Fix: gdas/fv3jedi

### Type of change

- [X] Update existing files (Version update needed)
- [ ] Remove files (Version update needed)
- [ ] Add new files to existing directory
- [ ] Add new directory (Version update needed if fix)

### Any workflow changes needed?

Fix/IC version update only

### Please list all related issues. If this request requires a workflow update (including a fix version update), please open a *separate* global-workflow issue to track the change.

NOAA-EMC/global-workflow #2978

### Pickup location

Hera: `/scratch1/NCEPDEV/stmp2/Russ.Treadon/fv3jedi`

### Size

0.31 Mb

### Additional information

The contents of pickup location directories `fv3jedi/fieldmetadata` and `fv3jedi/fv3files` differ from the same-named directories in `fix/gdas/fv3jedi/20220805`.  Pickup location directory `fv3jedi/fieldsets` is identical to `fix/gdas/fv3jedi/20220805/fieldsets`.

**Comment by KateFriedman-NOAA** [comment]
@RussTreadon-NOAA I pulled the new `fv3jedi` fix files into the fix set on Hera. Please confirm this is as requested and then we'll sync to the other platforms, thanks!

See: `/scratch1/NCEPDEV/global/glopara/fix/gdas/fv3jedi/20241022`

**Comment by RussTreadon-NOAA** [comment]
@KateFriedman-NOAA .  Thank you for installing the updated fv3files on Hera.  

I rsync'd `/scratch1/NCEPDEV/global/glopara/fix/gdas/fv3jedi/20241022` to Cactus.  Comparision with the `fv3jedi` files I use in g-w PR [#2978](https://github.com/NOAA-EMC/global-workflow/pull/2978) testing shows the two directories to be identical.

```
russ.treadon@clogin05:/lfs/h2/emc/ptmp/russ.treadon> ls 20241022/ /lfs/h2/emc/da/noscrub/russ.treadon/git/global-workflow/pr2978/fix/gdas/fv3jedi          
20241022/:
fieldmetadata  fieldsets  fv3files

/lfs/h2/emc/da/noscrub/russ.treadon/git/global-workflow/pr2978/fix/gdas/fv3jedi:
fieldmetadata  fieldsets  fv3files
russ.treadon@clogin05:/lfs/h2/emc/ptmp/russ.treadon> diff -r 20241022/ /lfs/h2/emc/da/noscrub/russ.treadon/git/global-workflow/pr2978/fix/gdas/fv3jedi      
russ.treadon@clogin05:/lfs/h2/emc/ptmp/russ.treadon> 
```

You may sync the Hera update to other platforms.

**Comment by KateFriedman-NOAA** [comment]
Thanks for confirming @RussTreadon-NOAA ! We'll now sync the new `gdas/fv3jedi` fix timestamp to the other supported platforms.

**Comment by WalterKolczynski-NOAA** [comment]
Fix synchronized to MSU

**Comment by KateFriedman-NOAA** [comment]
Thanks @WalterKolczynski-NOAA ! Sync is complete. Closing as complete.
