### ISSUE TITLE
GSI fix

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/global-workflow#3026]
### Type of static data

Fix

### Target directory

Fix: gsi

### Type of change

- [X] Update existing files (Version update needed)
- [ ] Remove files (Version update needed)
- [X] Add new files to existing directory
- [ ] Add new directory (Version update needed if fix)

### Any workflow changes needed?

Fix/IC version update only

### Pickup location

Cactus: `/lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/develop/fix`

### Size

2325.25 Mb

**Comment by RussTreadon-NOAA** [comment]
Attention @CatherineThomas-NOAA, @emilyhcliu , and @ADCollard 

 g-w `develop` file `versions/fix.ver` currently sets `export gsi_ver=20240208`.  A comparison of `/lfs/h2/emc/global/noscrub/emc.global/FIX/fix/gsi/20240208` and the GSI `develop` fix (after compilation) shows several differences.

The g-w copy of `global_anavinfo.l127.txt` is missing 
```
   ni      127       1         cloud_ice conc       ni
   nr      127       1         rain conc            nr
```
in the `met_guess` section.

We need this section for GFS v17, right?

**Comment by KateFriedman-NOAA** [comment]
@RussTreadon-NOAA I copied the new GSI fix to the fix set on Hera. Please see it here and let me know if it's good to sync or if you're still waiting on clarification from others: `/scratch1/NCEPDEV/global/glopara/fix/gsi/20241022`

**Comment by RussTreadon-NOAA** [comment]
@KateFriedman-NOAA , comparison of Hera `/scratch1/NCEPDEV/global/glopara/fix/gsi/20241022` with `develop:fix` should the two directories to be identical apart from my copy of `develop` containing `.git` and `.gitignore`. 

Since the intention is to keep g-w `sorc/gsi_enkf.fd` in sync g-w `fix/gsi` we can sync the updated Hera gsi fix files to other platforms.  g-w will not use the updated fix files until `versions/fix.ver` is updated.

**Comment by KateFriedman-NOAA** [comment]
Thanks for confirming @RussTreadon-NOAA ! We'll sync the new GSI fix to the other supported platforms.

**Comment by WalterKolczynski-NOAA** [comment]
Fix synchronized to MSU

**Comment by KateFriedman-NOAA** [comment]
Thanks @WalterKolczynski-NOAA ! Closing this as complete.

**Comment by CatherineThomas-NOAA** [comment]
@RussTreadon-NOAA 
> We need this section for GFS v17, right?

Yes, this is needed for the GSI Thompson changes, which are already in the g-w develop GSI hash (though I see you're updating the hash further).  Thanks for finding this!
