### ISSUE TITLE
Stochastic physics restart file format change

### ISSUE THREAD

**Issue by pjpegion** [NOAA-EMC/global-workflow#303]
The update to the ufs-weather-model that went in on March 21 https://github.com/ufs-community/ufs-weather-model/commit/3e46f5b7050e18884a0bed13691823ad88d443c3 includes a change to the stochastic physics restarts.

They are now written in netCDF format, and the file names have changed.  

The new naming convention for the atmospheric stochastic restarts is
RESTART/YYYYMMDDHH.000000.atm_stoch.res.nc for intermediate restarts and RESTART/atm_stoch.res.nc for end of run restarts.

The restart will need to be put in the INPUT directory for the next run.  

FHSTOCH is no longer needed, but STOCHINI is still needed for a restarted run.

**Comment by KateFriedman-NOAA** [comment]
@pjpegion Is this still needed? If so, please update this, thanks!

**Comment by pjpegion** [comment]
I don't know. I don't use the workflow, so I am probably not the one who should make the change in there.

**Comment by KateFriedman-NOAA** [comment]
@yangfanglin Is this needed?

**Comment by JessicaMeixner-NOAA** [comment]
This is likely going to be needed at some point in feature/coupled-crow I would suspect.

**Comment by KateFriedman-NOAA** [comment]
Ok, thanks @JessicaMeixner-NOAA !

**Comment by WalterKolczynski-NOAA** [comment]
@XianwuXue-NOAA This may come in to play as we move forward with ensembles

**Comment by XianwuXue-NOAA** [comment]
OK. Thanks @WalterKolczynski-NOAA

**Comment by aerorahul** [comment]
I think this functionality will be needed in the segment 2 of the GEFS ensemble forecast.
I suggest we close this issue for now and create a more relevant and targeted one when we need it.
