### ISSUE TITLE
Switch to JCB for aerosol DA jobs

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/global-workflow#3035]
### What new functionality do you need?

Use JCB to generate YAMLs for all the JEDI-based aerosol DA tasks

### What are the requirements for the new functionality?

Use JCB to generate YAMLs for all the JEDI-based aerosol DA tasks

### Acceptance Criteria

- [ ] aerosol DA cycled CI tests pass

**Comment by CoryMartin-NOAA** [comment]
The PR that resolves this issue will also include the switch to the Jedi class and an additional rescaling factor for the aerosol B matrix

**Comment by CoryMartin-NOAA** [comment]
Work is progressing in [CoryMartin-NOAA:feature/aero-jcb](https://github.com/CoryMartin-NOAA/global-workflow/tree/feature/aero-jcb). This is nearing completion and a PR will be issued soon. We are mainly waiting for a science test from @andytangborn who will provide some updated fix files (and a fix file issue will be opened to copy those over) for the aerosol B matrix. Once that is complete, this branch will be tested, fix versions updated, and a PR issued.

**Comment by andytangborn** [comment]
> Work is progressing in [CoryMartin-NOAA:feature/aero-jcb](https://github.com/CoryMartin-NOAA/global-workflow/tree/feature/aero-jcb). This is nearing completion and a PR will be issued soon. We are mainly waiting for a science test from @andytangborn who will provide some updated fix files (and a fix file issue will be opened to copy those over) for the aerosol B matrix. Once that is complete, this branch will be tested, fix versions updated, and a PR issued.

I'm assuming that the rescale files are what you are referring to here, and that once we have a good candidate then they can be staged.

**Comment by CoryMartin-NOAA** [comment]
@andytangborn yes
