### ISSUE TITLE
GDA files required by C48mx500_3DVarAOWCDA missing on WCOSS2

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/global-workflow#3039]
### Type of static data

Experimental data

### Target directory

Exp Data: *NEW*

### Type of change

- [ ] Update existing files (Version update needed)
- [ ] Remove files (Version update needed)
- [X] Add new files to existing directory
- [ ] Add new directory (Version update needed if fix)

### Any workflow changes needed?

Non-version changes only

### Please list all related issues. If this request requires a workflow update (including a fix version update), please open a *separate* global-workflow issue to track the change.

NOAA-EMC/GDASApp [#1331](https://github.com/NOAA-EMC/GDASApp/issues/1331)

### Pickup location

Hera: `/scratch1/NCEPDEV/global/glopara/dump/*20210324*

### Size

63811.6875 Mb

### Additional information

The 63811.6875 Mb is the total for all `*20210324*` directories in Hera `/scratch1/NCEPDEV/global/glopara/dump`.
```
32222568        gdas.20210324
4372432 gdasx.20210324
120716  gdasy.20210324
12312952        gfs.20210324
5248480 gfsx.20210324
93808   gfsy.20210324
10972212        rtofs.20210324
```
The WCDA `config.base`
```
export SDATE=2021032412
export EDATE=2021032418
```
Thus, we do not need the 00Z directory.   We may also not need `gdasx`, `gdasy`, `gfsx`, and `gfsy` directories.

Tagging @guillaumevernieres and @AndrewEichmann-NOAA for guidance.

**Comment by RussTreadon-NOAA** [comment]
Setting **Target directory** to `Exp Data: New` is not correct.  This issue is not opened to add new data.  It is opened to populate the WCOSS2 GDA with the dump files needed to run g-w CI C48mx500_3DVarAOWCDA.

My current  C48mx500_3DVarAOWCDA test on Cactus is stuck at 20210324 18Z gdas_prep because the require GDA status file is not present

```
russ.treadon@clogin05:/lfs/h2/emc/ptmp/russ.treadon/EXPDIR/prwcda_pr2978> rocotocheck -d prwcda_pr2978.db -w prwcda_pr2978.xml -c 202103241800 -t gdas_prep

Task: gdas_prep
  account: GFS-DEV
  command: /lfs/h2/emc/da/noscrub/russ.treadon/git/global-workflow/pr2978/jobs/rocoto/prep.sh
  cores: 14
  cycledefs: gdas
  final: false
  jobname: prwcda_pr2978_gdas_prep_18
  join: /lfs/h2/emc/ptmp/russ.treadon/COMROOT/prwcda_pr2978/logs/2021032418/gdas_prep.log
  maxtries: 2
  memory: 480GB
  name: gdas_prep
  nodes: 1:ppn=14:tpp=1
  queue: dev
  throttle: 9999999
  walltime: 00:30:00
  environment
    CDATE ==> 2021032418
    COMROOT ==> /lfs/h2/emc/ptmp/russ.treadon/COMROOT
    DATAROOT ==> /lfs/h2/emc/stmp/russ.treadon/RUNDIRS/prwcda_pr2978/gdas.2021032418
    EXPDIR ==> /lfs/h2/emc/ptmp/russ.treadon/EXPDIR/prwcda_pr2978
    HOMEgfs ==> /lfs/h2/emc/da/noscrub/russ.treadon/git/global-workflow/pr2978
    NET ==> gfs
    PDY ==> 20210324
    RUN ==> gdas
    RUN_ENVIR ==> emc
    cyc ==> 18
  dependencies
    AND is not satisfied
      SOME is satisfied
        gdas_atmos_prod_f000 of cycle 202103241200 is SUCCEEDED
        gdas_atmos_prod_f003 of cycle 202103241200 is SUCCEEDED
        gdas_atmos_prod_f006 of cycle 202103241200 is SUCCEEDED
        gdas_atmos_prod_f009 of cycle 202103241200 is SUCCEEDED
      /lfs/h2/emc/ptmp/russ.treadon/COMROOT/prwcda_pr2978/gdas.20210324/12//model/atmos/history/gdas.t12z.atmf009.nc is available
      /lfs/h2/emc/dump/noscrub/dump/gdas.20210324/18/atmos/gdas.t18z.updated.status.tm00.bufr_d does not exist

Cycle: 202103241800
  Valid for this task: YES
  State: active
  Activated: 2024-10-28 17:22:03 UTC
  Completed: -
  Expired: -

Job: This task has not been submitted for this cycle

Task can not be submitted because:
  Dependencies are not satisfied
```

**Comment by KateFriedman-NOAA** [comment]
@RussTreadon-NOAA The 20210324 dump data is now also available on WCOSS2-Cactus. It was already on WCOSS2-Dogwood but wasn't synced to Cactus for some reason.

```
WCOSS2 (BACKUPSYS-C) dump> ll /lfs/h2/emc/dump/noscrub/dump/gdas.20210324/18/atmos/gdas.t18z.updated.status.tm00.bufr_d
-rw-r--r-- 1 emc.global global 12960 Mar 24  2021 /lfs/h2/emc/dump/noscrub/dump/gdas.20210324/18/atmos/gdas.t18z.updated.status.tm00.bufr_d
```

Closing this issue as complete.

**Comment by RussTreadon-NOAA** [comment]
Thank you @KateFriedman-NOAA for populating the Cactus GDA.  _C48mx500_3DVarAOWCDA_ successfully ran to completion.
```
/lfs/h2/emc/ptmp/russ.treadon/EXPDIR/prwcda_pr2978
   CYCLE         STATE           ACTIVATED              DEACTIVATED     
202103241200        Done    Oct 28 2024 17:22:03    Oct 28 2024 17:37:32
202103241800        Done    Oct 28 2024 17:22:03    Oct 29 2024 14:17:48
```
