### ISSUE TITLE
Bug fix for cleaning DATAROOT from failed CI cases

### ISSUE THREAD

**Issue by TerrenceMcGuinness-NOAA** [NOAA-EMC/global-workflow#3066]
### What new functionality do you need?

Currently we clear DATAROOT for each CI case on completion per its tagged hash label.  This needs to be extended to also preform the action on creation to cover for the corner cases when an experiment has failed and is being re-ran that still has the same hash label.

### What are the requirements for the new functionality?

Fix the above bug with updates to the pipeline

### Suggest a solution (optional)

Code the solution directly in the pipeline to delete the DATA_DIR before creation of the EXPDIR

**Comment by DavidHuber-NOAA** [comment]
@TerrenceMcGuinness-NOAA Could this be moved into the setup scripts?  Since this has been an issue for users as well, it might be good to have the option for them to delete `DATAROOT` along with `COMROOT` and `EXPDIR`.  See #3071.
