### ISSUE TITLE
GFSv16.3.21[2]? - Update WAFS GCIP for global mosaic satellite data update

### ISSUE THREAD

**Issue by YaliMao-NOAA** [NOAA-EMC/global-workflow#3082]
### Description

Global Mosaic of Geostationary Satellite Imagery (GMGSI) is going to update with filename changes. This update will impact WAFS GCIP.

### Target version

GFSv16.3.21

### Expected workflow changes

n/a

### Tasks

- [ ] Create release branch
- [ ] Make workflow changes for upgrade in release branch (add additional checklist items as needed)
- [ ] Create release notes
- [ ] Cut hand-off tag for CDF
- [ ] Submit CDF to NCO
- [ ] Implementation into operations complete
- [ ] Merge release branch into operational branch
- [ ] Cut version tag from operational branch
- [ ] Release new version tag
- [ ] Announce to users
- [ ] Update Read-The-Docs operations status version in develop

**Comment by KateFriedman-NOAA** [comment]
After renaming the WAFS removal release branch from `release/gfs.v16.3.21` to `release/gfs.v16.3.22` I cut a new [`release/gfs.v16.3.21`]([url](https://github.com/NOAA-EMC/global-workflow/tree/release/gfs.v16.3.21)) branch from the current `release/gfs.v16.3.20` branch so it has the changes that are about to go into ops.

**Comment by KateFriedman-NOAA** [comment]
@YaliMao-NOAA let me know when you have changes ready to put into the [`release/gfs.v16.3.21`](https://github.com/NOAA-EMC/global-workflow/tree/release/gfs.v16.3.21) branch. Depending on what they are, you can either submit a PR into the release branch or we can work together on the updates in the workflow. Let me know, thanks!

**Comment by YaliMao-NOAA** [comment]
Sure

**Comment by YaliMao-NOAA** [comment]
@KateFriedman-NOAA I've had a new WAFS tag gfs_wafs.v6.3.4 ready.
The changes are minor, as you can see https://github.com/NOAA-EMC/WAFS/commit/86aff3c7069930c0ec263f13118f5c7776139b01

I'm going to make a PR for global ecflow.

**Comment by KateFriedman-NOAA** [comment]
Thanks @YaliMao-NOAA ! Please put me as a reviewer and I'll review/approve/merge it.

**Comment by KateFriedman-NOAA** [comment]
This upgrade is cancelled due to the WAFS removal upgrade being moved up in the GFS implementation queue. This update will be included in the new WAFSv7 package. Closing this issue.
