### ISSUE TITLE
Update fix/gdas/fv3jedi

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/global-workflow#3104]
### Type of static data

Fix

### Target directory

Fix: gdas/fv3jedi

### Type of change

- [X] Update existing files (Version update needed)
- [ ] Remove files (Version update needed)
- [ ] Add new files to existing directory
- [ ] Add new directory (Version update needed if fix)

### Any workflow changes needed?

Fix/IC version update only

### Please list all related issues. If this request requires a workflow update (including a fix version update), please open a *separate* global-workflow issue to track the change.

NOAA-EMC/global-workflow #2992

### Pickup location

Hera: `/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/pr2992/fix/gdas/fv3jedi`

### Size

0.32 Mb

**Comment by KateFriedman-NOAA** [comment]
@RussTreadon-NOAA I have copied the new `gdas/fv3jedi` fix files to a new `20241115` timestamp here on Hera: `/scratch1/NCEPDEV/global/glopara/fix/gdas/fv3jedi/20241115`. Please confirm it's as requested and we'll sync the new timestamp to the other supported platforms.

**Comment by RussTreadon-NOAA** [comment]
Looks good to me @KateFriedman-NOAA .  `diff -r` found no differences.  `du -k` shows same sizes.
```
Hera(hfe02):/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/pr2992/fix/gdas$ diff -r fv3jedi /scratch1/NCEPDEV/global/glopara/fix/gdas/fv3jedi/20241115
Hera(hfe02):/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/pr2992/fix/gdas$ du -k fv3jedi /scratch1/NCEPDEV/global/glopara/fix/gdas/fv3jedi/20241115
56      fv3jedi/fieldmetadata
100     fv3jedi/fieldsets
164     fv3jedi/fv3files
324     fv3jedi
56      /scratch1/NCEPDEV/global/glopara/fix/gdas/fv3jedi/20241115/fieldmetadata
100     /scratch1/NCEPDEV/global/glopara/fix/gdas/fv3jedi/20241115/fieldsets
164     /scratch1/NCEPDEV/global/glopara/fix/gdas/fv3jedi/20241115/fv3files
324     /scratch1/NCEPDEV/global/glopara/fix/gdas/fv3jedi/20241115
```

**Comment by KateFriedman-NOAA** [comment]
Excellent, thanks for checking @RussTreadon-NOAA ! We'll sync this new timestamp to the other supported platforms now.

@WalterKolczynski-NOAA Please sync the new `gdas/fv3jedi/20241115` to MSU, thanks!

**Comment by WalterKolczynski-NOAA** [comment]
Sync'd to MSU.

**Comment by WalterKolczynski-NOAA** [comment]
Sync'd to dogwood

**Comment by KateFriedman-NOAA** [comment]
Synced to Cactus and Jet. Closing as complete.
