### ISSUE TITLE
Issue building pre/post wave jobs with latest ufs-weather-model

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#3110]
### What is wrong?

FYI - There is an issue (seen here: https://github.com/NOAA-EMC/global-workflow/pull/3106#issuecomment-2484169044) when building the wave model if you update to the latest ufs-weather-model.  Fix for this is being tracked here: https://github.com/ufs-community/ufs-weather-model/issues/2502 

Just posting here so others know about this problem. 

### What should have happened?

WW3 pre/post jobs should build. 

### What machines are impacted?

All or N/A

### What global-workflow hash are you using?

adding newest ufs-weather-model 

### Steps to reproduce

Update ufs-weather-model to latest PR and try to build ww3 pre/post.

**Comment by WalterKolczynski-NOAA** [comment]
g-w is not using a UFS hash with this issue and the issue looks to be contained within UFS. Is there a reason we need a g-w issue for this (e.g. some change to the build script will be needed)?

**Comment by JessicaMeixner-NOAA** [comment]
It's common for people to update the ufs-weather-model on their own - for example: https://github.com/NOAA-EMC/global-workflow/pull/3106 therefore, communicating that this will be an issue seems like a good idea for everyone's awareness.  Do you have a better method of communicating that this will be an issue?

**Comment by JessicaMeixner-NOAA** [comment]
PR to ufs-weather-model to address this issue is here: https://github.com/ufs-community/ufs-weather-model/pull/2512

Branch of g-w used to test is here: https://github.com/JessicaMeixner-NOAA/global-workflow/tree/bug/addPIOswitch 
Note this does not enable to the pio for WW3 yet, but confirms we can get past build issues to enable that feature in the global-workflow.
