### ISSUE TITLE
Warm coupled restarts for the GFSv17 test

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/global-workflow#3117]
### Type of static data

Initial conditions

### Target directory

ICs: C48/C48 mx500

### Type of change

- [ ] Update existing files (Version update needed)
- [ ] Remove files (Version update needed)
- [X] Add new files to existing directory
- [X] Add new directory (Version update needed if fix)

### Any workflow changes needed?

Fix/IC version update + additional changes

### Please list all related issues. If this request requires a workflow update (including a fix version update), please open a *separate* global-workflow issue to track the change.

Needed for #3041 

### Pickup location

/work/noaa/da/gvernier/ensda/ictest

### Size

~12GB

### Additional information

These are C48mx500 IC's

**Comment by guillaumevernieres** [comment]
@KateFriedman-NOAA , @WalterKolczynski-NOAA , any chance this could be looked at this week?

**Comment by WalterKolczynski-NOAA** [comment]
@guillaumevernieres What is this `1440x1080x75` directory?

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres What is this `1440x1080x75` directory?

Oops ... ignore that directory. Or I can move it elsewhere if that's easier for you.

**Comment by WalterKolczynski-NOAA** [comment]
@guillaumevernieres This directory also has a bunch of diags and bumps and stuff. Would you please trim it down to just what is needed to restart?

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres This directory also has a bunch of diags and bumps and stuff. Would you please trim it down to just what is needed to restart?

@WalterKolczynski-NOAA , I removed the ocean analysis files that are not used.

**Comment by WalterKolczynski-NOAA** [comment]
Staged on Hera, MSU, and Dogwood. A new IC version was not needed since the files to not collide with the existing files, though we may want to anyway in the near future since now we have ICs with different provenance in the same location now.

Will leave this issue open until ICs can get synchronized to the other locations.

**Comment by guillaumevernieres** [comment]
Thanks @WalterKolczynski-NOAA

**Comment by KateFriedman-NOAA** [comment]
ICs have also been synced to Cactus, Jet, and AWS.

**Comment by guillaumevernieres** [comment]
> ICs have also been synced to Cactus, Jet, and AWS.

Thanks @KateFriedman-NOAA
