### ISSUE TITLE
create_experiment HPC_ACCOUNT not working

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/global-workflow#3124]
### What is wrong?

One used to be able to do something like:
```
HPC_ACCOUNT=da-cpu ./create_experiment.py --yaml ci/cases/pr/C96C48_hybatmaerosnowDA.yaml
```
and it would replace all the ACCOUNT information with `da-cpu` that is no longer the case, it's instead `fv3-cpu`

### What should have happened?

`HPC_ACCOUNT=da-cpu` should fill in `da-cpu` where appropriate

### What machines are impacted?

All or N/A

### What global-workflow hash are you using?

1ba8985  

### Steps to reproduce

See above

**Comment by AndrewEichmann-NOAA** [comment]
Seconded, and same for the queue settings. At least they could be overridden in the yamls.

**Comment by DavidHuber-NOAA** [comment]
Yes, this does stem from #3053.  In that PR, I made it so whatever was in the CI YAML would be overridden by the workflow/hosts machine YAML.  This allowed for features that were not supported on a machine to be disabled, even if it is explicitly enabled in the CI test (such as METplus or the TC tracker).

I will need to think about how to reconcile this to allow users to influence assignments.
