### ISSUE TITLE
New GSI fix files:  netcdf global_berror and `l31` files

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/global-workflow#3128]
### Type of static data

Fix

### Target directory

Fix: gsi

### Type of change

- [ ] Update existing files (Version update needed)
- [ ] Remove files (Version update needed)
- [x] Add new files to existing directory

### Any workflow changes needed?

No change needed

### Please list all related issues. If this request requires a workflow update (including a fix version update), please open a *separate* global-workflow issue to track the change.

None

### Pickup location

Hera: `/scratch1/NCEPDEV/da/Russ.Treadon/git/gsi/20241127`

### Size

134.1 MB

### Additional information

The files in `/scratch1/NCEPDEV/da/Russ.Treadon/git/gsi/20241127` serve two purposes:
1. netcdf format global_berror files to be used for GSI -vs JEDI DA v18 DA validation.  The netcdf global_berror files may also be implemented as part of GFS v17
2. Fix files to run ultra low-resolution GSI with 31 levels

None of the files in `/scratch1/NCEPDEV/da/Russ.Treadon/git/gsi/20241127` are currently in `/scratch1/NCEPDEV/global/glopara/fix/gsi/20241022` so the files in `20241127` could be added to `/scratch1/NCEPDEV/global/glopara/fix/gsi/20241022` without changing the version number.   Of course, this is EIB's call.

**Comment by KateFriedman-NOAA** [comment]
> None of the files in /scratch1/NCEPDEV/da/Russ.Treadon/git/gsi/20241127 are currently in /scratch1/NCEPDEV/global/glopara/fix/gsi/20241022 so the files in 20241127 could be added to /scratch1/NCEPDEV/global/glopara/fix/gsi/20241022 without changing the version number. Of course, this is EIB's call.

@RussTreadon-NOAA Does this mean that the files that are in the current `20241022` set but not in the new `20241127` set are being retired and will not be used again? While combining would indeed spare us a new timestamp, I am inclined to do a new timestamp so we have a fresh set that doesn't contain files being retired (if they are being retired). Let me know, thanks!

**Comment by RussTreadon-NOAA** [comment]
@KateFriedman-NOAA , no GSI fix files are being retired.  We need to retain the binary global_berror files for the foreseeable future.  This request simply adds netcdf counterparts to some, not all, global_berrror files.  31 layer files are also added to support future ultra low resolution g-w CI.

**Comment by KateFriedman-NOAA** [comment]
@RussTreadon-NOAA Understood, thanks for explaining that the current files should remain. Given this, I will add the new files to the current timestamp. Stay tuned...

**Comment by KateFriedman-NOAA** [comment]
@RussTreadon-NOAA I have pulled the new GSI fix files into the `20241022` timestamp on Hera. Please confirm they are good in their new home and we will sync them to the other platforms. Thanks!
```
[role.glopara@hfe09 20241022]$ pwd
/scratch1/NCEPDEV/global/glopara/fix/gsi/20241022
[role.glopara@hfe09 20241022]$ rsync -azv /scratch1/NCEPDEV/da/Russ.Treadon/git/gsi/20241127/* .
sending incremental file list
global_anavinfo.l31.txt
global_berror.l127y194.nc
global_berror.l127y386.nc
global_berror.l127y770.nc
global_berror.l127y98.nc
global_berror.l31y26.nc
global_berror.l31y50.nc
global_hybens_info.l31.txt

sent 103,644,614 bytes  received 168 bytes  15,945,351.08 bytes/sec
total size is 132,374,049  speedup is 1.28
```

**Comment by RussTreadon-NOAA** [comment]
Thank you @KateFriedman-NOAA for installing the new fix files on Hera.  The fix files are in the correct location.  I built and ran the GSI global_4denvar ctest using a netcdf global_berror file copied from the g-w GSI fix directory.  Everything looks good!

**Comment by KateFriedman-NOAA** [comment]
Thanks for checking @RussTreadon-NOAA! I have synced the new gsi fix files to WCOSS2, Jet, and AWS. Working on HPSS now.

@WalterKolczynski-NOAA please sync `gsi/20241022` to MSU, thanks!

**Comment by KateFriedman-NOAA** [comment]
The `gsi/20241022` fix is now also archived to HPSS.

**Comment by RussTreadon-NOAA** [comment]
Thank you @KateFriedman-NOAA .  I built GSI on Dogwood using the updated fix and am now running ctests.  I'll do the same on Orion and Hercules after the updated GSI fix is in place.

**Comment by WalterKolczynski-NOAA** [comment]
MSU synchronized

**Comment by KateFriedman-NOAA** [comment]
@RussTreadon-NOAA Once you've tested and confirmed the files are good on MSU, please respond with that and feel free to close this issue. Thanks!

**Comment by RussTreadon-NOAA** [comment]
Thank you @WalterKolczynski-NOAA .  I see the files in the expected location.  Hercules and Orion builds are underway.

**Comment by RussTreadon-NOAA** [comment]
GSI ctests on Orion, Hera, and WCOSS2 completed with [acceptable results](https://github.com/NOAA-EMC/GSI/pull/810#issuecomment-2512987360).  Hercules jobs remain pending in the queue.  Hercules and Orion use the same g-w GSI fix so the Orion success is sufficient.

**Comment by RussTreadon-NOAA** [comment]
Thank you @KateFriedman-NOAA and @WalterKolczynski-NOAA for installing the new files.  I'm seeing acceptable behavior on several machines.  Closing this issue.
