### ISSUE TITLE
Two issues in the test runs for GFSv16.2

### ISSUE THREAD

**Issue by XuLi-NOAA** [NOAA-EMC/global-workflow#313]
There are a series of cycling runs to check the GSI updates for GFSv16.2.
There are two issues in all of the cycling runs:

dbuoyb and mbuoyb are not used before 2020102200
Before 2020102200 cycle, there are two separate data files, e.g., for 2020090100,

-rw-r--r-- 1 glopara global 1112592 Sep 1 2020 /scratch1/NCEPDEV/global/glopara/dump/gdas.20200901/00/gdas.t00z.mbuoyb.tm00.bufr_d
-rw-r--r-- 1 glopara global 2472584 Sep 1 2020 /scratch1/NCEPDEV/global/glopara/dump/gdas.20200901/00/gdas.t00z.dbuoyb.tm00.bufr_d

which are included into nsstbufr data file, after 2020102200, these two files don't exist anymore since they have been combined into sfcshp data file.

The solution to include dbuoyb and mbuoyb in the cycling run:

add

if [[ "$CDATE" -le "2020102200" ]]; then
export SCRIPTSobsproc_global=$EXPDIR
fi

in config.base

cp /scratch1/NCEPDEV/da/Xu.Li/para_gfs/rocoto_sh/exglobal_makeprepbufr.sh.ecf to $EXPDIR

Only one line change in this exglobal_makeprepbufr.sh.ecf

  DTYPS_nsst='sfcshp tesac bathy trkob'  ==>  DTYPS_nsst='sfcshp dbuoyb mbuoyb tesac bathy trkob'
the dmesh(i) needs to be set reasobally, when i > 2, in config.eobs
in config.eobs,

there is a line

export OBSINPUT_INVOBS="dmesh(1)=225.0,dmesh(2)=225.0,"

to set the thinning box size to be 225 km, for dmesh(1) and dmesh(2).

However, there are three data thinning is defined with dmesh(3), which is set to be 100 km in exglobal_atmos_analysis.sh, they are

amsr2_gcom-w1
gmi_gpm
saphir_methat

Currently, only saphir_methat of these three are used in GSI, and gmis_gpm will be used by plan. It is necessary to set dmesh(3) in config.eobs.

**Comment by XuLi-NOAA** [comment]
Russ suggested there should be a better way to include buoyb data into nsstbufr data file than what I described  above. I talked with Shelley and she pointed out that the data file, nsstbufr, is already available in the dump directory, e.g., for 2020092700, 

/scratch1/NCEPDEV/global/glopara/dump/gdas.20200927/00/gdas.t00z.nsstbufr

Therefore, no need to generate it by cat 6 or 4 files into a single one, in exglobal_makeprepbufr.sh.ecf, as I thought. 

Indeed, from the log file, 
/scratch2/NCEPDEV/stmp3/Xu.Li/ROTDIRS/v16nst/logs/2020092700/gdasprep.log

I can see (in the default setting), 

ln -fs /scratch1/NCEPDEV/global/glopara/dump/gdas.20200927/00/gdas.t00z.nsstbufr /scratch2/NCEPDEV/stmp3/Xu.Li/ROTDIRS/v16nst/gdas.20200927/00/atmos/gdas.t00z.nsstbufr

but it is deleted later

+ [[ YES == NO ]]
+ [ YES '=' YES ]
+ [ YES '=' YES ]
+ rm /scratch2/NCEPDEV/stmp3/Xu.Li/ROTDIRS/v16nst/gdas.20200927/00/atmos/gdas.t00z.prepbufr
+ rm /scratch2/NCEPDEV/stmp3/Xu.Li/ROTDIRS/v16nst/gdas.20200927/00/atmos/gdas.t00z.prepbufr.acft_profiles
+ rm /scratch2/NCEPDEV/stmp3/Xu.Li/ROTDIRS/v16nst/gdas.20200927/00/atmos/gdas.t00z.nsstbufr

To me, if nsstbufr data file is already available in the dump directory (which is true at least for the time around 202008), then, what need to be done is

add 

MAKE_NSSTBUFR="NO" in config.base

But I am not sure how to control the linked  nsstbufr will not be removed as shown in the cycling run with the default settings. 

Russ, 

Can you help me with this?

Another issue we should deal with:

If nsstbufr data has been available in the dump directory, then,  MAKE_NSSTBUFR should be "NO" all the time.

We just need to make sure nsstbufr contains all the data, including dbuoyb and mbuoyb, for the time period prior to 2020102200.

And anybody can tell where/when the nsstbufr is generated (clearly before prep step)?

**Comment by XuLi-NOAA** [comment]
Here is Russ' comment in his email:

Hi Xu,

Please update workflow issue #313 with the information you shared in your email.

The operational gfs and gdas nsstbufr files are created in job ${cdump}_atmos_prep_${cyc}.   For example, look at $COMROOTp3/output/prod/20210412/gdas_atmos_prep_12.o58840924 and search for the string nsstbufr.

global-workflow jobs/rocoto/prep.sh needs to be updated.   It does not check MAKE_NSSTBUFR.  This variable should be added to prep.sh.  If MAKE_NSSTBUFR=YES, prep.sh needs to remove the soft link to the DMPDIR nsstbufr since exglobal_makeprepbufr.sh.ecf will create its own nsstbufr.   If MAKE_NSSTBUFR=NO, exglobal_makeprepbufr.sh.ecf will not create nsstbufr.  Instead, we want to retain the soft link to the DMPDIR nsstbufr.  

The ROTDIR_DUMP=NO block of prep.sh should also be examined and updated accordingly.

Russ

**Comment by XuLi-NOAA** [comment]
Since it has been decided to keep it as is in the current cycling run, in order to be consistent with the control run, which has been done with the same buoyb issue. This will be handled a bit later.

**Comment by aerorahul** [comment]
@XuLi-NOAA @RussTreadon-NOAA 
Will adding 
```
 [[ -f $COMOUT/${RUN}.${cycle}.nsstbufr ]] && MAKE_NSSTBUFR=NO
```
on line 551 in https://github.com/NOAA-EMC/obsproc/blob/develop/scripts/exglobal_makeprepbufr.sh.ecf
resolve this issue (If I understand this particular problem)?

**Comment by RussTreadon-NOAA** [comment]
I'll let @XuLi-NOAA and @ShelleyMelchior-NOAA respond.   Good to see [ObsProc](https://github.com/NOAA-EMC/obsproc) in github.

**Comment by ShelleyMelchior-NOAA** [comment]
So in the context of obsproc **operations**, MAKE_NSSTBUFR's default setting is YES.  So again, in the context of real time operations, Rahul's suggested test will never pass b/c the test is performed prior to the creation of the nsstbufr file.  But for re-runs or when using com data that already exists for a given cycle, then yes, forcing MAKE_NSSTBUFR=NO upon the existence of the nsstbufr file should do what you need.

Thanks to @aerorahul for getting obsproc et al set up in github.  The repos are in the context of WCOSS2, however, not current obsproc operations, as we work to transition our code to cactus in a new configuration. Feel free to browse around, though, as a nice preview. ;-)

**Comment by XuLi-NOAA** [comment]
I am not sure to answer Rahul's question yet.

But I know what the problem is: 

In the cycling run (rerun, not operational), the nsstbufr data file is generated (always, because MAKE_NSSTBUFR is YES, as Shelley said it is the default setting), however, one line in exglobal_makeprepbufr.sh.ecf used is DTYPS_nsst='sfcshp tesac bathy trkob'  instead of  DTYPS_nsst='sfcshp dbuoyb mbuoyb tesac bathy trkob' as in the older version, it is understandable since dbuoyb and mbuoyb have been combined into sfcshp since 2020102200. Therefore, when doing cycling for the analysis cycles before 2020102200, the nsstbufr file is generated but without mbuoyb and dbuoyb (MAKE_NSSTBUFR is YES, and dbuoyb mbuoyb are not in that line anymore). 

To, it seems if MAKE_NSSTBUFR  is forced to NO should be OK, since nsstbufr is existing already (after the GFS operational cycling run) with job ${cdump}atmos_prep${cyc} (as pointed by Russ). However, as I pointed, I don't understand one logical, that is why the nsstbufr file is deleted, as I said earlier in this issue, see,


/scratch2/NCEPDEV/stmp3/Xu.Li/ROTDIRS/v16nst/logs/2020092700/gdasprep.log

I can see (in the default setting),

ln -fs /scratch1/NCEPDEV/global/glopara/dump/gdas.20200927/00/gdas.t00z.nsstbufr /scratch2/NCEPDEV/stmp3/Xu.Li/ROTDIRS/v16nst/gdas.20200927/00/atmos/gdas.t00z.nsstbufr

but it is deleted later

[[ YES == NO ]]
[ YES '=' YES ]
[ YES '=' YES ]
rm /scratch2/NCEPDEV/stmp3/Xu.Li/ROTDIRS/v16nst/gdas.20200927/00/atmos/gdas.t00z.prepbufr
rm /scratch2/NCEPDEV/stmp3/Xu.Li/ROTDIRS/v16nst/gdas.20200927/00/atmos/gdas.t00z.prepbufr.acft_profiles
rm /scratch2/NCEPDEV/stmp3/Xu.Li/ROTDIRS/v16nst/gdas.20200927/00/atmos/gdas.t00z.nsstbufr
To me, if nsstbufr data file is already available in the dump directory (which is true at least for the time around 202008), then, what need to be done is

add

MAKE_NSSTBUFR="NO" in config.base

But I am not sure how to control the linked nsstbufr will not be removed as shown in the cycling run with the default settings.



By the way, /scratch2/NCEPDEV/stmp3/Xu.Li/ROTDIRS/v16nst/logs/2020092700/gdasprep.log is not available anymore.

**Comment by aerorahul** [comment]
@XuLi-NOAA 
I can't understand what you are saying and I think this is possibly conflating 2 separate issues.
Can you please reformat the text in your [comment above](https://github.com/NOAA-EMC/global-workflow/issues/313#issuecomment-947683850) to make it clear?

I am reluctant to put a blanket statement such as below in `config.base` because that is hard-setting to not create the NSST bufr file.
```
MAKE_NSSTBUFR=NO
```

Instead would something like this work on line 104  of [prep.sh](https://github.com/NOAA-EMC/global-workflow/blob/develop/jobs/rocoto/prep.sh)
```
[[ -f $DMPDIR/${CDUMP}${DUMP_SUFFIX}.${PDY}/${cyc}/${OPREFIX}nsstbufr ]] && MAKE_NSSTBUFR=NO
```

I would imagine something like that logic would check for a nsstbufr file to be present in the `$DMPDIR` for the cycle under consideration and if so, the re-run will pick that file that was used/generated in operations.

I am not sure what the other issue about `DTYPS_NSST` is and how that can be tackled at this level without further clarifying information.

**Comment by ShelleyMelchior-NOAA** [comment]
I suppose some logic could be added in your workflow that tests on $PDY$cyc.  If the date is before 2020102200 then use `DTYPS_nsst='sfcshp dbuoyb mbuoyb tesac bathy trkob'`.  If the date is equal to after 2020102200 then use `DTYPS_nsst='sfcshp tesac bathy trkob'`

**Comment by aerorahul** [comment]
Thanks @ShelleyMelchior-NOAA 
Is that in addition to or instead of `MAKE_NSSTBUFR=NO` if `nsstbufr` file exists?

To paraphrase:
- should `MAKE_NSSTBUFR=NO` if the `nsstbufr` file is present in the `$DMPDIR` for a `$PDY$cyc` in our workflow?
- if `MAKE_NSSTBUFR=NO`, does setting `DTYPS_nsst` matter?

Or should it be something like:
```
if ( $PDY$cyc < 2020102200 ) then
    DTYPS_nsst='sfcshp dbuoyb mbuoyb tesac bathy trkob'
else
    DTYPS_nsst='sfcshp tesac bathy trkob'
endif
```
In this case `MAKE_NSSTBUFR` will be left to the default which is `YES`.

**Comment by ShelleyMelchior-NOAA** [comment]
In addition ... I think they are 2 independent problems.
The DTYPS_nsst settings only matter when you are going to generate the nsstbufr file.

**Comment by XuLi-NOAA** [comment]
Line 558 in exglobal_makeprepbufr.sh.ecf is

DTYPS_nsst='sfcshp tesac bathy trkob' now

And it used to be

DTYPS_nsst='sfcshp dbuoyb mbuoyb tesac bathy trkob'

This is the primary reason that the generated nsstbufr file with the new version of exglobal_makeprepbufr.sh.ecf doesn't contain mbuoyb and dbuoyb. 

Since nsstbufr file already exists (after the operational cycling of GFS), in rerun, nsstbufr file doesn't need to be generated again. But it is with MAKE_NSSTBUFR=YES. 

That is the problem, and it is a problem for the run before 2020102200 only. 

I am not providing solution, just describing the problem, as I said.

**Comment by aerorahul** [comment]
@XuLi-NOAA @ShelleyMelchior-NOAA @RussTreadon-NOAA 
Thanks.  I think I understand now and may have a potential solution.

In [config.prep](https://github.com/NOAA-EMC/global-workflow/blob/develop/parm/config/config.prep), we can introduce a variable `USE_OPS_NSSTBUFR` with valid options `YES|NO`.  Default would be to use operational NSST bufr file.

In [prep.sh](https://github.com/NOAA-EMC/global-workflow/blob/develop/jobs/rocoto/prep.sh), we can introduce logic such as this:
```
if (USE_OPS_NSSTBUFR = YES) then
    MAKE_NSSTBUFR=NO
else
    if ( $PDY$cyc < 2020102200 ) then
        DTYPS_nsst='sfcshp dbuoyb mbuoyb tesac bathy trkob'
    else
        DTYPS_nsst='sfcshp tesac bathy trkob'
    endif
endif
```

Would this be an acceptable solution?

**Comment by XuLi-NOAA** [comment]
@aerorahul : Yes, it makes sense to me. 

And can you tell why the three bufr files are deleted in the cycling run (rerun)? Because prep is executed? 
See what I showed above (from my cycling run log file):

[[ YES == NO ]]
[ YES '=' YES ]
[ YES '=' YES ]
rm /scratch2/NCEPDEV/stmp3/Xu.Li/ROTDIRS/v16nst/gdas.20200927/00/atmos/gdas.t00z.prepbufr
rm /scratch2/NCEPDEV/stmp3/Xu.Li/ROTDIRS/v16nst/gdas.20200927/00/atmos/gdas.t00z.prepbufr.acft_profiles
rm /scratch2/NCEPDEV/stmp3/Xu.Li/ROTDIRS/v16nst/gdas.20200927/00/atmos/gdas.t00z.nsstbufr

What I concern is that:

If the existing nsstbufr data file is deleted somewhere, then, MAKE_NSSTBUFR needs to be YES and also make sure mbuoyb and dbuoyb are included.

**Comment by aerorahul** [comment]
You have `ROTDIR_DUMP=YES` set and a value of `NO` currently is unsupported according to a comment in `config.base`
This is the section that is deleting these files.

```
    if [ $ROTDIR_DUMP = "YES" ]; then
	rm $COMOUT/${OPREFIX}prepbufr
	rm $COMOUT/${OPREFIX}prepbufr.acft_profiles
	rm $COMOUT/${OPREFIX}nsstbufr
    fi
```

Also, the purpose of that block is to generate these files, so this removes any stale files that may have been present.

**Comment by XuLi-NOAA** [comment]
@aerorahul 

Got it and thanks!

So, it is OK if these  removes are not done after the nsstbufr data file is linked or generated, then, what you suggested is enough to resolve the issue.

**Comment by aerorahul** [comment]
@XuLi-NOAA 
Can I create a branch from `develop` implementing the pseudo-code from https://github.com/NOAA-EMC/global-workflow/issues/313#issuecomment-947810350?  Would you be willing to test that branch and confirm it works as you would expect it to?

**Comment by XuLi-NOAA** [comment]
@aerorahul : Yes, I can do that. Let me know when it is ready.

**Comment by aerorahul** [comment]
@XuLi-NOAA 
Please test with branch [bugfix/issue_313](https://github.com/NOAA-EMC/global-workflow/tree/bugfix/issue_313)
I am not sure what version of `exglobal_makeprepbufr.sh.ecf` is using, but from looking at [this](https://github.com/NOAA-EMC/obsproc/blob/develop/scripts/exglobal_makeprepbufr.sh.ecf) on [line 558](https://github.com/NOAA-EMC/obsproc/blob/622bcff7d1df388be2cd8e65370bb43a88f25bf6/scripts/exglobal_makeprepbufr.sh.ecf#L558), `DTYPS_nsst` is hard wired in the obsproc repository.   Please verify all variants of this logic and let me know.

**Comment by XuLi-NOAA** [comment]
Set up a cycling run with the version for DA's evaluation for GFSv16.x (it is available and also needed to test the finalized GSI update for GFSv16.x) , but incorporating Rahual's changes in prep.sh and config.prep. Based on the check of the 1st prep and anal cycle, it works as expected (mbuoyb and dbuoyb are included as expected). See attached figure, which shows the drifting buoys distribution, v16nst2 without changes, v16nst3 with changes. 
![Insitu_DataCoverage_vomb1_stat1_v16nst2_v16nst2_v16nst3_190_ges_Global_all_used_06Z30Aug2020_06Z30Aug2020](https://user-images.githubusercontent.com/55100838/138464474-0cde0af5-1d67-4e46-9367-139e5fb7baf9.png)

**Comment by XuLi-NOAA** [comment]
Two issues were raised in this #313. 

1. The inclusion of dbuoyb and mbuoyb in the cycling run before 2020102200.
2.  The definition of dmesh(3), and actually dmesh(4) as well, in config.eobs, for EnKF thinning.

The item 1 has been resolved (see comments above). 
However, I am not sure item 2 (it seems not resolved yet). Anybody can confirm?

**Comment by aerorahul** [comment]
@XuLi-NOAA Please open a new issue.

**Comment by XuLi-NOAA** [comment]
A new one, https://github.com/NOAA-EMC/global-workflow/issues/595, has been opened. 
This one is closed.
