### ISSUE TITLE
Build using compute nodes

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#3131]
### What new functionality do you need?

The capability to build on compute nodes using the job scheduler

### What are the requirements for the new functionality?

Build all components using the system job scheduler, whether it be slurm or pbspro. Most programs should be able to build on compute nodes, but the GDASapp will need to build in the service queue for now as it (currently) contacts the outside world to build.

### Acceptance Criteria

- [ ] All components build without error using slurm
- [ ] All components build without error using pbspro
- [ ] Output unchanged (maybe, building on compute nodes may result in changes; at very least all programs should run successfully)

**Comment by CoryMartin-NOAA** [comment]
@WalterKolczynski-NOAA will this be an option or the only way to build?

**Comment by DavidHuber-NOAA** [comment]
@CoryMartin-NOAA I intend on making this an option.

**Comment by RussTreadon-NOAA** [comment]
@DavidHuber-NOAA and @WalterKolczynski-NOAA :  

GDASApp issue [#1328](https://github.com/NOAA-EMC/GDASApp/issues/1328) [documents](https://github.com/NOAA-EMC/GDASApp/issues/1328#issuecomment-2539894857) a successful compute node (e.g, batch job) build of GDASApp inside g-w `develop` on WCOSS2 (Dogwood), Hera, and Orion.

**Comment by DavidHuber-NOAA** [comment]
Fantastic, thanks @RussTreadon-NOAA!
