### ISSUE TITLE
The archive task failed in my HR4 test run ((48 hours forecasting)

### ISSUE THREAD

**Issue by XuLi-NOAA** [NOAA-EMC/global-workflow#3142]
### What is wrong?

I am running a test with HR4 configuration by setting th eforecast hours as 48. It went through but the archive task failed. From 
/lfs/h2/emc/ptmp/xu.li/work-hr4n/hr4n-20191203/COMROOT/2019120300/hr4n-20191203/logs/2019120300/gfsarch.log

It shows: 

Traceback (most recent call last): 
  File "/lfs/h2/emc/hur/noscrub/xu.li/hr4n/global-workflow/scripts/exglobal_archive.py", line 67, in <module>
    main()
  File "/lfs/h2/emc/hur/noscrub/xu.li/hr4n/global-workflow/ush/python/wxflow/logger.py", line 266, in wrapper
    retval = func(*args, **kwargs)
  File "/lfs/h2/emc/hur/noscrub/xu.li/hr4n/global-workflow/scripts/exglobal_archive.py", line 54, in main
    arcdir_set, atardir_sets = archive.configure(archive_dict)
  File "/lfs/h2/emc/hur/noscrub/xu.li/hr4n/global-workflow/ush/python/wxflow/logger.py", line 266, in wrapper
    retval = func(*args, **kwargs)
  File "/lfs/h2/emc/hur/noscrub/xu.li/hr4n/global-workflow/ush/python/pygfs/task/archive.py", line 130, in configure
    dataset["fileset"] = Archive._create_fileset(dataset)
  File "/lfs/h2/emc/hur/noscrub/xu.li/hr4n/global-workflow/ush/python/wxflow/logger.py", line 266, in wrapper
    retval = func(*args, **kwargs)
  File "/lfs/h2/emc/hur/noscrub/xu.li/hr4n/global-workflow/ush/python/pygfs/task/archive.py", line 211, in _create_fileset
    raise FileNotFoundError(f"FATAL ERROR: Required file, directory, or glob {item} not found!")
FileNotFoundError: FATAL ERROR: Required file, directory, or glob gfs.20191203/00/products/wave/gridded/gfswave.t00z.*.*.f049.grib2 not found!
+ JGLOBAL_ARCHIVE[1]: postamble JGLOBAL_ARCHIVE 1732907737 1
+ preamble.sh[70]: set +x
End JGLOBAL_ARCHIVE at 19:15:52 with error code 1 (time elapsed: 00:00:15)
+ arch.sh[1]: postamble arch.sh 1732907733 1
+ preamble.sh[70]: set +x
End arch.sh at 19:15:52 with error code 1 (time elapsed: 00:00:19)
PBS: Running epilogue on parent mom node: ddxfer01...
##### Job 207868014.dbqs01 - PBS Job Script:

I can see it is looking for gfswave.t00z.*.*.f049, which means the 49th hour forecasting which is unavailable since I am do 48-hour forecasting only (in fact, I can see it is trying to get gfswave file upto 120 hours). How to fix this problem to make the archive job work? Anybody can help? 

### What should have happened?

The arch task done smoothly

### Steps to reproduce

Setting the forecasting hour to be 48 with HR4 configuration. 

### Additional information

No

### Do you have a proposed solution?

Modify the scripts to be able to handle the fhour<120

**Comment by DavidHuber-NOAA** [comment]
I will take a look at this today.

**Comment by DavidHuber-NOAA** [comment]
As a quick fix for this one experiment, you could change line 298 of config.base from
```bash
export FHMAX_HF_WAV=120
```
to
```bash
export FHMAX_HF_WAV=48
```

I will be making a PR today to fix this in the archive yaml.

**Comment by DavidHuber-NOAA** [comment]
@XuLi-NOAA Actually, it looks like @AntonMFernando-NOAA fixed this issue last week.  Could you try adding these lines into your config.base and seeing if that resolves the issue for you:

https://github.com/NOAA-EMC/global-workflow/blob/bc618628c96583ef29e455d7dd50670e61e813f4/parm/config/gfs/config.base#L314-L317

I just ran a 48-hour S2SW forecast from develop and the gfswave.tar archive was created successfully.

**Comment by XuLi-NOAA** [comment]
> @XuLi-NOAA Actually, it looks like @AntonMFernando-NOAA fixed this issue last week. Could you try adding these lines into your config.base and seeing if that resolves the issue for you:
> 
> https://github.com/NOAA-EMC/global-workflow/blob/bc618628c96583ef29e455d7dd50670e61e813f4/parm/config/gfs/config.base#L314-L317
> 
> I just ran a 48-hour S2SW forecast from develop and the gfswave.tar archive was created successfully.

David,

Yes, it went through with your suggested modification of config.base.

Thanks!

Xu

**Comment by DavidHuber-NOAA** [comment]
Great, thanks for reporting back.  I'll go ahead and close this now.
