### ISSUE TITLE
Updates to config.metp and met.sh to support upcoming EMC_verif-global major release

### ISSUE THREAD

**Issue by malloryprow** [NOAA-EMC/global-workflow#315]
EMC_verif-global's next major release (slated as version 2.0.0) needs to be tested within the global workflow. This includes an upgrade to using MET version 9.1.3 and METplus version 3.1.1, as well as all the python scripts updated to using python3. Major work was done in renaming the config variables as well.

- config.metp and metp.sh needed to be updated to support new changes within EMC_verif-global.
- The new changes need to be tested in the workflow.
- checkout.sh updated to the new EMC_verif-global release tag number

**Comment by malloryprow** [comment]
Tested on WCOSS Dell, Hera, and Orion, and all ran gfsmetp tasks successfully. I'll put together the pull request.

**Comment by KateFriedman-NOAA** [comment]
Thanks @malloryprow !
