### ISSUE TITLE
GDA files for 20210325 00Z required for C48mx500_3DVarAOWCDA & C48mx500_hybAOWCDA missing on WCOSS2

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/global-workflow#3159]
### Type of static data

Experimental data

### Target directory

Exp Data: *NEW*

### Type of change

- [ ] Update existing files (Version update needed)
- [ ] Remove files (Version update needed)
- [X] Add new files to existing directory
- [ ] Add new directory (Version update needed if fix)

### Any workflow changes needed?

Non-version changes only

### Please list all related issues. If this request requires a workflow update (including a fix version update), please open a *separate* global-workflow issue to track the change.

g-w PR #3120

### Pickup location

Hera: /scratch1/NCEPDEV/global/glopara/dump/gdas.20210325

### Size

32172.34 Mb

### Additional information

The 20210325 00Z gdas_prep for both C48mx500_3DVarAOWCDA and C48mx500_hybAOWCDA can not run on WCOSS2 (Dogwood) because a GDA file dependency is not satisfied.  Specifically,
```
/lfs/h2/emc/dump/noscrub/dump/gdas.20210325/00/atmos/gdas.t00z.updated.status.tm00.bufr_d does not exist
```

g-w CI streams 48mx500_3DVarAOWCDA and C48mx500_hybAOWCDA successfully run to completion on Hera.  

The contents of Hera `/scratch1/NCEPDEV/global/glopara/dump/gdas.20210325/00` need to be copied to Dogwood & Cactus  `/lfs/h2/emc/dump/noscrub/dump/gdas.20210325/00`

**Comment by RussTreadon-NOAA** [comment]
Attention @guillaumevernieres

**Comment by RussTreadon-NOAA** [comment]
@KateFriedman-NOAA : I rsync Hera `/scratch1/NCEPDEV/global/glopara/dump/gdas.20210325/00` to Dogwood `/lfs/h2/emc/da/noscrub/russ.treadon/dump/gdas.20210325/00/atmos`.

We can `cp -rp /lfs/h2/emc/da/noscrub/russ.treadon/dump/gdas.20210325 /lfs/h2/emc/dump/noscrub/dump/gdas.20210325`.

I can access emc.global to complete this copy if doing so helps you.

**Comment by RussTreadon-NOAA** [comment]
@KateFriedman-NOAA :  In order to finish WCOSS2 (Dogwood) g-w CI for g-w PR #3125 before next week's outage, I populated `/lfs/h2/emc/dump/noscrub/dump/` with the Hera copy of `gdas.20210325/00`.  This allows the C48mx500_3DVarAOWCDA & C48mx500_hybAOWCDA CI streams to continue.  I did not update Cactus.

**Comment by KateFriedman-NOAA** [comment]
Thanks @RussTreadon-NOAA and sorry you needed to do it yourself. Just getting to this issue. I'll sync it to the other platforms and then close this. Thanks!

**Comment by RussTreadon-NOAA** [comment]
Thank you @KateFriedman-NOAA for syncing to other platforms .  I was able to complete g-w CI testing on Dogwood before it was taken down this morning.

**Comment by KateFriedman-NOAA** [comment]
Synced to Cactus. Do you need this on MSU as well?

**Comment by RussTreadon-NOAA** [comment]
Thank you for asking @KateFriedman-NOAA.  Interestingly, `/work/noaa/rstprod/dump/gdas.20210325/00` already exists on MSU.

**Comment by KateFriedman-NOAA** [comment]
Ok good, it was just missing on WCOSS2 then for CI tests. I will now close this as complete.
