### ISSUE TITLE
Add initial aerosol B rescaling files

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/global-workflow#3160]
### Type of static data

Fix

### Target directory

Fix: *NEW*

### Type of change

- [ ] Update existing files (Version update needed)
- [ ] Remove files (Version update needed)
- [X] Add new files to existing directory
- [ ] Add new directory (Version update needed if fix)

### Any workflow changes needed?

Fix/IC version update + additional changes

### Please list all related issues. If this request requires a workflow update (including a fix version update), please open a *separate* global-workflow issue to track the change.

#3125 
#3035 

### Pickup location

/scratch2/NCEPDEV/stmp1/Cory.R.Martin/dec2024/g-w_fix/gdas/aero/clim_b/rescale*

### Size

756

### Additional information

Note this is not 'new' but I could not find the entry for what I needed...

These files need added to `fix/gdas/aero/clim_b`

**Comment by WalterKolczynski-NOAA** [comment]
In place on Hera, MSU, and Dogwood. @KateFriedman-NOAA Please synchronize the others.

I will look into adding the missing directories to the issue template.

**Comment by RussTreadon-NOAA** [comment]
Thank you @WalterKolczynski-NOAA and @KateFriedman-NOAA .  

I can confirm that the 20211220 12Z gdas_aeroanlgenb job from g-w CI stream C96C48_hybatmaerosnowDA now successfully runs to completion on Dogwood, Hera, and Orion following the copying of the `rescale` files into the EIB staged location.

**Comment by KateFriedman-NOAA** [comment]
Synced to Cactus, Jet, AWS, and HPSS.

**Comment by KateFriedman-NOAA** [comment]
Closing as complete.
