### ISSUE TITLE
gdas_arch fails with division by 0

### ISSUE THREAD

**Issue by TravisElless-NOAA** [NOAA-EMC/global-workflow#3168]
### What is wrong?

2nd full cycle and beyond gdas_arch jobs are failing with a division by 0 error. Line where the error is occurring https://github.com/NOAA-EMC/global-workflow/blob/develop/ush/python/pygfs/task/archive.py#L490

### What should have happened?

gdas_arch should successfully complete for all cycles

### What machines are impacted?

All or N/A, Hera

### What global-workflow hash are you using?

6c5b9bb

### Steps to reproduce

1. Run global workflow for a 2.5 cycle or more case with ARCH_EXPDIR_FREQ=0
2. See gdas_arch failures

**Comment by jiaruidong2017** [comment]
You can do the following setup in the `config.base`:

`export ARCH_EXPDIR_FREQ=6    # How often to archive the EXPDIR in hours or 0 for first and last cycle only`
