### ISSUE TITLE
build_all.sh failed in gfs_utils.sh

### ISSUE THREAD

**Issue by dkokron** [NOAA-EMC/global-workflow#3194]
### What is wrong?

A fresh clone of the global-workflow fails to configure gfs_utils.fd

Excerpt from dogwood:/lfs/h2/hpc/support/daniel.kokron/Projects/GlobalWorkflow/global-workflow/sorc/logs/build_gfs_utils.log

-- Found OpenMP_Fortran: -qopenmp (found version "5.0")
-- Found OpenMP: TRUE (found version "5.0") found components: Fortran
-- Found bacio: /apps/ops/para/libs/intel/19.1.3.304/bacio/2.4.1/lib/libbacio_4.a (found version "2.4.0")
-- Found bacio: /apps/ops/para/libs/intel/19.1.3.304/bacio/2.4.1/lib/libbacio_4.a (found version "2.4.0")
-- Found w3emc: /apps/ops/para/libs/intel/19.1.3.304/w3emc/2.9.2/lib64/libw3emc_4.a (found version "2.9.2")
CMake Error at CMakeLists.txt:39 (find_package):
  By not providing "Findsp.cmake" in CMAKE_MODULE_PATH this project has asked
  CMake to find a package configuration file provided by "sp", but CMake did
  not find one.

  Could not find a package configuration file provided by "sp" with any of
  the following names:

    spConfig.cmake
    sp-config.cmake

  Add the installation prefix of "sp" to CMAKE_PREFIX_PATH or set "sp_DIR" to
  a directory containing one of the above files.  If "sp" provides a separate
  development package or SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!

### What should have happened?

Given that the appropriate sp module is loaded, I expected that configure would find what it needed

### What machines are impacted?

WCOSS2

### What global-workflow hash are you using?

1c37f907 (HEAD -> develop, origin/develop, origin/HEAD) HEAD@{0}: clone: from https://github.com/NOAA-EMC/global-workflow

### Steps to reproduce

git clone --recursive https://github.com/NOAA-EMC/global-workflow
cd global-workflow/sorc/gdas.cd
cp /lfs/h2/hpc/support/daniel.kokron/Projects/GDASApp/modulefiles/GDAS/wcoss2.intel.lua_spack-stack1.6.0 modulefiles/GDAS/wcoss2.intel.lua
cd ..
time ./build_all.sh gfs gdas >& build_all.log; rf
wait ~42 minutes

**Comment by DavidHuber-NOAA** [comment]
@dkokron I just followed these instructions on Dogwood:

```bash
cd /lfs/h2/emc/global/noscrub/David.Huber/GW
git clone --recursive git@github.com:noaa-emc/global-workflow gw_build_test
cd gw_build_test/sorc/gdas.cd/
cp /lfs/h2/hpc/support/daniel.kokron/Projects/GDASApp/modulefiles/GDAS/wcoss2.intel.lua_spack-stack1.6.0 modulefiles/GDAS/wcoss2.intel.lua
cd ..
./build_all.sh gfs gdas >& build_all.log
```

The build log for gfs_utils shows a successful build:
```console
> cat logs/build_gfs_utils.log
+ OPTIND=1
+ getopts :j:dvh option
+ case "${option}" in
+ BUILD_JOBS=1
+ getopts :j:dvh option
+ shift 2
+ BUILD_TYPE=Release
+ BUILD_VERBOSE=NO
+ BUILD_JOBS=1
+ ./gfs_utils.fd/ush/build.sh
Resetting modules to system default. Reseting $MODULEPATH back to system default. All extra directories will be removed from $MODULEPATH.

Currently Loaded Modules:
  1) craype-x86-rome    (H)   4) envvar/1.0           7) craype/2.7.10     10) jasper/2.0.25  13) sp/2.3.3      16) ncio/1.1.2             19) w3emc/2.9.2  22) sfcio/1.4.1  25) nemsio/2.5.2  28) landsfcutil/2.4.1
  2) libfabric/1.20.1         5) PrgEnv-intel/8.1.0   8) cray-mpich/8.1.9  11) zlib/1.2.11    14) hdf5/1.10.6   17) gfsutils_wcoss2.intel  20) ip/3.3.3     23) bacio/2.4.1  26) wrf_io/1.2.0  29) wgrib2/2.0.8
  3) craype-network-ofi (H)   6) intel/19.1.3.304     9) cmake/3.20.2      12) libpng/1.6.37  15) netcdf/4.7.4  18) bufr/11.7.0            21) sigio/2.3.2  24) w3nco/2.4.1  27) g2/3.4.5
... 
-- Found w3emc: /apps/ops/para/libs/intel/19.1.3.304/w3emc/2.9.2/lib64/libw3emc_4.a (found version "2.9.2")
-- Found OpenMP_Fortran: -qopenmp (found version "5.0") 
-- Found sp: /apps/ops/prod/libs/intel/19.1.3.304/sp/2.3.3/lib/libsp_4.a (found version "2.3.3")
-- Found OpenMP_Fortran: -qopenmp (found version "5.0") 
-- Found ip: /apps/ops/para/libs/intel/19.1.3.304/ip/3.3.3/lib/libip_4.a (found version "3.3.3")
-- Found ncio: /apps/ops/para/libs/intel/19.1.3.304/cray-mpich/8.1.7/ncio/1.1.2/lib64/libncio.a (found version "1.1.2")
-- Found bacio: /apps/ops/para/libs/intel/19.1.3.304/bacio/2.4.1/lib/libbacio_4.a (found version "2.4.0")
-- Found w3nco: /apps/ops/para/libs/intel/19.1.3.304/w3nco/2.4.1/lib/libw3nco_4.a (found version "2.4.0")
-- Found MPI: TRUE (found version "3.1") found components: Fortran 
-- Found nemsio: /apps/ops/para/libs/intel/19.1.3.304/cray-mpich/8.1.7/nemsio/2.5.2/lib/libnemsio.a (found version "2.5.1")
-- Found sigio: /apps/ops/para/libs/intel/19.1.3.304/sigio/2.3.2/lib/libsigio.a (found version "2.3.0")
-- Found ZLIB: /apps/spack/zlib/1.2.11/intel/19.1.3.304/hjotqkckeoyt6j6tibalwzrlfljcjtdh/lib/libz.so (found version "1.2.11") 
-- Found PNG: /apps/spack/libpng/1.6.37/intel/19.1.3.304/4ohkronuhlyherusoszzrmur5ewvlwzh/lib/libpng.so (found version "1.6.37") 
-- Found g2: /apps/ops/para/libs/intel/19.1.3.304/g2/3.4.5/lib64/libg2_4.a (found version "3.4.5")
-- Found bufr: /apps/ops/para/libs/intel/19.1.3.304/bufr/11.7.0/lib64/libbufr_4.a (found version "11.7.0")
-- Found landsfcutil: /apps/ops/para/libs/intel/19.1.3.304/landsfcutil/2.4.1/lib/liblandsfcutil_4.a (found version "2.4.0")
-- Found wgrib2: /apps/ops/para/libs/intel/19.1.3.304/wgrib2/2.0.8/lib/libwgrib2.a (found version "2.0.8") 
-- Findwgrib2:
--   - WGRIB2_INCLUDE_DIR: /apps/ops/para/libs/intel/19.1.3.304/wgrib2/2.0.8/include
--   - WGRIB2_LIBRARIES: /apps/ops/para/libs/intel/19.1.3.304/wgrib2/2.0.8/lib/libwgrib2.a
--   - WGRIB2_EXE: /apps/ops/para/libs/intel/19.1.3.304/wgrib2/2.0.8/bin/wgrib2
--   - WGRIB2_VERSION: 2.0.8
...
-- Configuring done
-- Generating done
-- Build files have been written to: /lfs/h2/emc/global/noscrub/David.Huber/GW/gw_build_test/sorc/gfs_utils.fd/build
+ make -j 1 VERBOSE=NO
...
make[2]: Entering directory '/lfs/h2/emc/global/noscrub/David.Huber/GW/gw_build_test/sorc/gfs_utils.fd/build'
[  1%] Building Fortran object src/enkf_chgres_recenter_nc.fd/CMakeFiles/enkf_chgres_recenter_nc.x.dir/setup.f90.o
cd /lfs/h2/emc/global/noscrub/David.Huber/GW/gw_build_test/sorc/gfs_utils.fd/build/src/enkf_chgres_recenter_nc.fd && /opt/cray/pe/craype/2.7.10/bin/ftn  -I/apps/prod/hpc-stack/intel-19.1.3.304/cray-mpich-8.1.4/netcdf/4.7.4/include -I/apps/ops/para/libs/intel/19.1.3.304/bacio/2.4.1/include_4 -I/apps/ops/para/libs/intel/19.1.3.304/ip/3.3.3/include_4 -I/apps/ops/prod/libs/intel/19.1.3.304/sp/2.3.3/include_4 -I/apps/ops/para/libs/intel/19.1.3.304/w3emc/2.9.2/include_4 -I/apps/ops/para/libs/intel/19.1.3.304/cray-mpich/8.1.7/ncio/1.1.2/include -g -traceback -fp-model precise -O3 -qopenmp -c /lfs/h2/emc/global/noscrub/David.Huber/GW/gw_build_test/sorc/gfs_utils.fd/src/enkf_chgres_recenter_nc.fd/setup.f90 -o CMakeFiles/enkf_chgres_recenter_nc.x.dir/setup.f90.o
/apps/spack/cmake/3.20.2/intel/19.1.3.304/utnbptm3hrf7gppztidueu4jogfgemut/bin/cmake -E cmake_copy_f90_mod src/enkf_chgres_recenter_nc.fd/setup.mod src/enkf_chgres_recenter_nc.fd/CMakeFiles/enkf_chgres_recenter_nc.x.dir/setup.mod.stamp Intel
...
Install the project...
-- Install configuration: "Release"
-- Installing: /lfs/h2/emc/global/noscrub/David.Huber/GW/gw_build_test/sorc/gfs_utils.fd/install/bin/enkf_chgres_recenter_nc.x
...
mv rdbfmsua.x /lfs/h2/emc/global/noscrub/David.Huber/GW/gw_build_test/sorc/gfs_utils.fd/install/bin/
+ exit
```

Comparing `/lfs/h2/hpc/support/daniel.kokron/Projects/GlobalWorkflow/global-workflow/sorc/logs/build_gfs_utils.log` and `/lfs/h2/emc/global/noscrub/David.Huber/GW/gw_build_test/sorc/logs/build_gfs_utils.log`, I believe I see the issue.  In my build, the `envvar` module is loaded, but in yours, it is not.  This module sets the variable `HPC_OPT` to the location of the hpc-stack-installed libraries.  This is required for several key libraries, including `sp`.

This module should be loaded by default, i.e. after any `module reset`, which the gfs_utils build script calls.  Could you check that the variable `LMOD_SYSTEM_DEFAULT_MODULES` is set to `envvar/1.0`?  If so, could you show the output of the following:

```
module reset
module avail
```

**Comment by dkokron** [comment]
Dave thanks for looking at this.  The system is configured to not load envvar automatically for GDIT folks.  I'll have to work around that feature.

**Comment by dkokron** [comment]
Adding "module load envvar/1.0" in a few places does resolve this issue.
