### ISSUE TITLE
coupled: add additional land outputs for prototypes

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#332]
Need to add additional land outputs for prototypes, from @barlage:
- there are three new accumulated fields we would need to fully close the land energy budget (could use at least one existing variable for these). Probably could remove a few others if adding is an issue.
- it would be good to know which grids have fractional outputs on the gaussian grid; I believe LAND could be used for this

**Comment by barlage** [comment]
@JessicaMeixner-NOAA: @HelinWei-NOAA and I have talked about this. You can assign the issue to us if you want.

**Comment by LydiaStefanova-NOAA** [comment]
About using LAND to store the fractional land mask: there was a discussion of that a while back, and I recall there being a concern that a number of downstream users expect only 1s and 0s in that variable, and the proposed solution at that time being the introduction of a new variable to store the fractional mask. Maybe @junwang-noaa or Shan Sun (I can't find her user name here) remember more about that?

**Comment by HelinWei-NOAA** [comment]
Five additional land fields have been added to the model native output (netcdf). If we want to have them included in the grib outputs, we need to add them to the grib table. Three of them are already in the table but with the different unit. I don't think they allow to have the same variable but with the different unit in the table. So we need to change the unit for them in the current table and make corresponding changes to the code. Also do we plan to have this change in p7c or p8? I think we can merger this change to the other PR.

**Comment by JessicaMeixner-NOAA** [comment]
@HelinWei-NOAA currently the plan is to have this in P7, the mini-prototypes use the rt.sh system not the workflow, so any workflow only updates are not used in p7c and would only be used for the full prototype.

**Comment by JessicaMeixner-NOAA** [comment]
FYI @shansun6

**Comment by barlage** [comment]
@HelinWei-NOAA what is the plan for land fraction? I do remember what @LydiaStefanova-NOAA mentioned earlier that perhaps there are downstream users that expect LAND to be exclusively 0/1 (and the grib description of LAND kinda says that parenthetically: https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table4-2-2-0.shtml). Do we need another new variable for true land fraction? There doesn't seem to be an appropriate GRIB variable for this either. @shansun6 @junwang-noaa

**Comment by HelinWei-NOAA** [comment]
@JessicaMeixner-NOAA Actually most of the changes are made to ccpp-physics. The only one related to workflow is the modification to diag_table.

> @HelinWei-NOAA currently the plan is to have this in P7, the mini-prototypes use the rt.sh system not the workflow, so any workflow only updates are not used in p7c and would only be used for the full prototype.

**Comment by JessicaMeixner-NOAA** [comment]
Are the changes to ccpp-physics already merged?

**Comment by HelinWei-NOAA** [comment]
No. These additional fields are not in the history output. We need to
modify the code to add them to the history output and then modify the
diag_table to have them in the model output.

**Comment by JessicaMeixner-NOAA** [comment]
@HelinWei-NOAA can you add the link to the ccpp/fv3atm/ufs issues here since this global-workflow task is dependent on those?

**Comment by HelinWei-NOAA** [comment]
@barlage I can add land fraction to the output without using LAND. It should be very straightfoward because we have landfrac in DDT Sfcprop. The only thing we need to deal with is its grib definition.

> @HelinWei-NOAA what is the plan for land fraction? I do remember what @LydiaStefanova-NOAA mentioned earlier that perhaps there are downstream users that expect LAND to be exclusively 0/1 (and the grib description of LAND kinda says that parenthetically: https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table4-2-2-0.shtml). Do we need another new variable for true land fraction? There doesn't seem to be an appropriate GRIB variable for this either. @shansun6 @junwang-noaa

**Comment by JessicaMeixner-NOAA** [comment]
Do we still need to do a test with this or did we complete this?

**Comment by HelinWei-NOAA** [comment]
We can close this topic.
