### ISSUE TITLE
Update feature/coupled-crow to use the latest coupled aerosols app

### ISSUE THREAD

**Issue by rmontuoro** [NOAA-EMC/global-workflow#336]
Branch `feature/coupled-crow` needs to be updated to run the latest ufs-weather-model app including prognostic aerosols.

**Comment by WalterKolczynski-NOAA** [comment]
If the app has been updated, we can probably add this into PR #334

**Comment by JessicaMeixner-NOAA** [comment]
There is issue #324 that is required for updating to the latest ufs-weather-model, I'm guessing that should be addressed before this is?
