### ISSUE TITLE
Port g-w for GEFS to WCOSS2/acorn

### ISSUE THREAD

**Issue by XianwuXue-NOAA** [NOAA-EMC/global-workflow#345]

**Comment by WalterKolczynski-NOAA** [comment]
This should be two separate issues.

**Comment by XianwuXue-NOAA** [comment]
Thanks. Walter, could you separate it two issues?

**Comment by arunchawla-NOAA** [comment]
@XianwuXue-NOAA is this issue complete ?

**Comment by XianwuXue-NOAA** [comment]
Almost done, since we have the MPI-allreduce issue in GSI, though this is a system issue, we can fix it, however, we need to work with Steven and George to finalize it next week. After this fix, I will close this issue.

**Comment by XianwuXue-NOAA** [comment]
@arunchawla-NOAA The issue I mentioned in the previous comment is https://github.com/NOAA-EMC/GSI/issues/289

**Comment by XianwuXue-NOAA** [comment]
@arunchawla-NOAA I will close this issue since NCO has updated the gsi code using our modified file. And I am merged my changes to the branch and update the tag.
