### ISSUE TITLE
Update Orion support to include rstprod

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#347]
A rstprod policy is now on Orion and access to the group is expanding. Update workflow and components that use rstprod to support rstprod on Orion now.

- [x] GDA
- [x] global-workflow flags/variables (e.g. CHGRP_RSTPROD)
- [x] EMC_verif-global (internal settings and on-disk data files)

Will need new tag from @malloryprow for EMC_verif-global.

**Comment by KateFriedman-NOAA** [comment]
@malloryprow Checking back with you on this. Do you have a new EMC_verif-global tag that supports rstprod on Orion? Is there anything you need from me for that? I'm going to make the workflow updates for this now. Thanks!

**Comment by KateFriedman-NOAA** [comment]
Created branch for workflow updates: [feature/rstprod-orion](https://github.com/KateFriedman-NOAA/global-workflow/tree/feature/rstprod-orion)

**Comment by malloryprow** [comment]
@KateFriedman-NOAA The tag verif_global_v2.2.1 has the rstprod support for Orion in it.

**Comment by KateFriedman-NOAA** [comment]
@malloryprow Thanks for the new tag! The global-workflow develop branch is currently using the verif_global_v2.0.2 tag. Can you give me a short summary of all changes from v2.0.2 to v2.2.1? Also, what platforms was this tag tested on? Thanks!

**Comment by malloryprow** [comment]
@KateFriedman-NOAA Yes!

- Support rstprod prepbufr files being used on Orion in grid-to-obs verification
- Support for running on S4 (stand alone and in global workflow)
- Enhancements and clean up of plotting scripts

**Comment by KateFriedman-NOAA** [comment]
> @KateFriedman-NOAA Yes!
> 
> * Support rstprod prepbufr files being used on Orion in grid-to-obs verification
> * Support for running on S4 (stand alone and in global workflow)
> * Enhancements and clean up of plotting scripts

Excellent, thanks @malloryprow for this!

**Comment by KateFriedman-NOAA** [comment]
@malloryprow I have run 4.5 cycles (C192C96L127) on WCOSS-Dell with the new EMC_verif-global tag. Please see my logs and output:

```
logs: /gpfs/dell3/ptmp/Kate.Friedman/comrot/issue347/logs/2020090*/gfsmetp*
output: /gpfs/dell2/emc/modeling/noscrub/Kate.Friedman/archive/metplus_data/by_VSDB/*/*/*/issue347
```

Note: this run was done without the race condition update

I'm also testing this branch on Orion to check my rstprod updates worked as intended. Thanks!

**Comment by malloryprow** [comment]
@KateFriedman-NOAA Output looks good! Let me know when you have output on Orion. It would be good to check that, and also see that it is correctly using the rstprod prepbufr files. The standalone testing ran fine, but always good to double check!

**Comment by KateFriedman-NOAA** [comment]
> @KateFriedman-NOAA Output looks good! Let me know when you have output on Orion. It would be good to check that, and also see that it is correctly using the rstprod prepbufr files. The standalone testing ran fine, but always good to double check!

@malloryprow Thanks for confirming the WCOSS-Dell run output looks good! I will share Orion output when available, possibly tomorrow at the rate it's going right now.

**Comment by KateFriedman-NOAA** [comment]
@malloryprow About to initiate the PR for this in anticipation of wrapping up the tests on Orion. I won't submit the PR until you've had a chance to look at output. Will ask for your review on the PR, thanks!

**Comment by KateFriedman-NOAA** [comment]
Thanks for updating EMC_verif-global for this task @malloryprow !
