### ISSUE TITLE
Output frequencies in coupled models

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#351]
The output frequencies of the different coupled components should be able to be controlled separately for each component.

**Comment by JessicaMeixner-NOAA** [comment]
For the most part, I think this already is the case.  It is for atm and wave.  I think there was an issue with MOM6 not having it set via configuration files and maybe the same for ice -- that it's set via it's own settings but not necessarily by top level configuration.
