### ISSUE TITLE
Add FMS domains_stack_size to set of configurable parameters

### ISSUE THREAD

**Issue by rmontuoro** [NOAA-EMC/global-workflow#352]
A default value for `domains_stack_size` is currently used in `ush/parsing_namelists_FV3.sh` since this parameter is not configurable by users:
```
&fms_nml
  clock_grain = 'ROUTINE'
  domains_stack_size = ${domains_stack_size:-3000000}
  print_memory_usage = ${print_memory_usage:-".false."}
  $fms_nml
/
```
This value, however, is too low if running FV3 with 127 vertical levels and prognostic aerosols.

The ability to set `domains_stack_size` externally needs to be added to branch `feature/coupled-crow`, perhaps introducing a new FMS schema (`workflow/schema/fms.yaml`).

**Comment by WalterKolczynski-NOAA** [comment]
With the move away from coupled-crow, this issue is moot. You should be able to export a domains_stack_size from config.fcst script.
