### ISSUE TITLE
Update MOM template files

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#355]
The MOM templates should be updated into a proper template file instead of something that relies on parsing with sed.

**Comment by JessicaMeixner-NOAA** [comment]
What's wrong with the MOM6 template files? I don't understand what is not proper about this?  This is also how we do wave template files.  This is easier to have connection with the rt.sh system which then makes everything simpler to maintain (unlike for atm and ice where it's harder).  I'd actually say we should update the ice template file to match closer to how MOM6 is doing than this way.   FYI: @jiandewang @DeniseWorthen

**Comment by jiandewang** [comment]
I also think using parsing and sed is the right way as we will rely on the template for different configurations such as including wave and non-wave. @WalterKolczynski-NOAA : what's your suggestions on the replacement ?

**Comment by WalterKolczynski-NOAA** [comment]
The sed method is clunky and difficult to maintain. There are any number of more modern approaches using tools designed to be templates, rather than using command line programs to fake it. But the most likely solution here as we push more and more things towards python would be to use the core [string.Template](https://docs.python.org/3/library/string.html#template-strings). Settings can be loaded from a yaml file directly into a dictionary and passed into the template.

**Comment by WalterKolczynski-NOAA** [comment]
And yes, ideally, the RT system would be modernized in the same way (see ufs-community/ufs-weather-model#656), which was opened independently within the past day.

**Comment by JessicaMeixner-NOAA** [comment]
So still having a template file (bonus/preferred if it is in sync or the same as what is used in ufs-weather-model) but a better method than sed for filling the template sounds like a good thing to me.
