### ISSUE TITLE
Archive fails when DO_MAKEPREPBUFR=NO

### ISSUE THREAD

**Issue by CatherineThomas-NOAA** [NOAA-EMC/global-workflow#361]
The current default in parm/config/config.prep is DO_MAKEPREPBUFR=YES.  If this option is set to NO, gdasarch and gfsarch will fail because the file $CDUMP.t$HHz.prepbufr_pre-qc is missing.  This file does not exist in the global dump archive and therefore is not copied over/linked to the ROTDIR during the prep step.

Looking through the log files when DO_MAKEPREPBURF=YES for a low resolution parallel, it seems that this prepbufr_pre-qc is not used anywhere in the workflow.  What is the purpose of this file? 

If this file is needed for HPSS when DO_MAKEPREPBUFR=YES, can an IF block be added to hpssarch_gen?

**Comment by lgannoaa** [comment]
@KateFriedman-NOAA prep step used ether obsproc file from production or from EMC dump. It does not download from hpss. Looks to me that the *prepbufr* files maybe no longer needed to be in archive.
Recommend to remove the *prepbufr* files from archive script.

**Comment by lgannoaa** [comment]
Here is the outcome of my research regarding the use of this file in EMC gfs cycled parallel:
A check on current wcoss2 production. The *prepbufr_pre-qc file in question is not found in GFS COM. It is now located in /lfs/h1/ops/prod/com/obsproc/v1.0 location.
A check on /lfs/h1/ops/prod/output/20220421 found "prepbufr_pre-qc" not exist in gdas or gfs log files.
/lfs/h1/ops/prod/output/20220421> grep "prepbufr_pre-qc" gdas*.o*|wc -l
0
/lfs/h1/ops/prod/output/20220421> grep "prepbufr_pre-qc" gfs*.o*|wc -l
0
I contacted Qingfu refer to this issue ticket. He reply my email and indicated this file can be removed from archive.

**Comment by lgannoaa** [comment]
In $HOMEgfs/ush/hpssarch_gen.sh file prepbufr_pre-qc will be removed from gdas_restarta and gfsa archive list.

**Comment by ilianagenkova** [comment]
@CatherineThomas-NOAA,
When DO_MAKEPREPBUFR=YES, a prepbufr file is generated. The *prepbufr_pre-qc  files are produced first and saved off as a separate file - they are the baseline upon which all the qc programs operate on. Then the final *prepbufr file is generated. I hope looking at  /lfs/h1/ops/prod/com/obsproc/v1.0 confirms that by comparing the files timestamps. (I am on leave and unable to get on WCOSS2)

I don't know what global-workflow you ran when you opened this issue, but as long as you see a *prepbufr file generated by the prep step, I think you could skip archiving this file.

**Comment by lgannoaa** [comment]
Thank you @ilianagenkova and @CatherineThomas-NOAA to join a short Google meeting. We have reached a conclusion that prepbufr_pre-qc file can be removed from EMC GFS cycled run archive jobs.
