### ISSUE TITLE
Add Orion support to operations branch

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#363]
Add Orion support changes to copy of operations branch for users to run GFSv16 on Orion.

Created branch off of operations (v16.1.2): feature/ops-orion

- [x] add Orion modulefiles/env
- [x] add Orion to machine-setup scripts/files
- [x] add Orion to builds
- [x] add Orion to setup scripts
- [x] update obsproc install on Orion (ops version)

**Comment by KateFriedman-NOAA** [comment]
Tested branch successfully on Orion (C192C96L127) and on WCOSS-Venus (C768C384L127). The WCOSS test reproduced operations.

Changes included in this branch cover:

1. support to run GFSv16 workflow on Orion (bulk of changes); also includes updates to support new rstprod policy
2. saved operational resource settings in new config.fv3.nco.static and config.resources.nco.static (what config.fv3 and config.resources had)
3. created new config.fv3.emc.dyn and config.resources.emc.dyn (renamed config.fv3 and config.resources) and updated them with resource settings taken from develop branch
4. updated link_fv3gfs.sh to grab appropriate version of config.fv3/config.resources based on mode (emc or nco)

Items 2-4 help prep this branch for inclusion in future ops updates...if this goes there.

**Comment by arunchawla-NOAA** [comment]
@KateFriedman-NOAA Is this issue resolved? Is there any further work that needs to be completed for this ?

**Comment by KateFriedman-NOAA** [comment]
@arunchawla-NOAA It is for the most part but I have a user on Hera right now (using feature/ops-orion) who has a failing efcs job that is being troubleshooted. I'd like to complete that troubleshooting and commit any needed updates before closing this issue.

**Comment by KateFriedman-NOAA** [comment]
Issue that user reported appears to have been resolved and doesn't require any changes to the feature/ops-orion branch. Will now close this issue.
