### ISSUE TITLE
modular exglobal in develop

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/global-workflow#365]
Bring in modular exglobal forecast script capabilities from `feature/coupled_crow` into `develop`

- This will be first tested in the free forecast mode where the current exglobal script is replaced with the modular one for atmosphere only free forecasts.  This should be a zero diff change and require minimal changes to the bash config files or setup scripts.
- Identify and bring the bash configuration files (@JessicaMeixner-NOAA will aid in identifying the config.bash scripts) for waves, ocean and ice, bring in these bash configuration scripts to `develop`.
- With these bash configuration files in place, update as required the modular exglobal script.  

Perform this development and testing in an interactive job without the use of the setup scripts infrastructure to the extent possible.

**Comment by jkuang-exploro** [comment]
This is under work in branch feature/script_update

**Comment by jkuang-exploro** [comment]
I created a tag named "coupled_sprint_start" pointing to the hash of coupled-crow when I initially started the merge.

**Comment by jkuang-exploro** [comment]
Another tag off the feature/coupled-crow branch named "coupled-sprint-0728" is created. This tag is intended to mark the state of the evolving feature/coupled-crow branch as of date 0728.

**Comment by jkuang-exploro** [comment]
PR#371 is updated for "coupled-sprint-0728" tag of feature/coupled-crow branch.

**Comment by jkuang-exploro** [comment]
All comments for my PR are addressed. Currently waiting for fixes for the base line(coupled-sprint), which isn't work right now.

**Comment by jkuang-exploro** [comment]
This issue should be closed @aerorahul

**Comment by aerorahul** [comment]
This work is completed and the modular exglobal forecast script has been tested with Atm-only configuration in `feature/coupled_sprint` branch via PR #371 
Closing issue.
