### ISSUE TITLE
Bring coupled model forecast capabilities into `develop`

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/global-workflow#366]
This epic will consolidate issues to bring in the capabilities of executing coupled model forecast from `feature/coupled_crow` (without CROW dependency) into `develop` to support coupled prototype efforts and eliminate duplication and redundancies.

Several accompanying issues will be handled in this epic as well:
- Python 2to3 updates for setup scripts. See issue #265
- Modularize exglobal forecast script. See issue #365

**Comment by jkuang-exploro** [comment]
I'm working under feature/script_update for this issue

**Comment by aerorahul** [comment]
I believe this Epic has been completed.
Reopen if not.

**Comment by WalterKolczynski-NOAA** [comment]
Still awaiting aerosol support.
