### ISSUE TITLE
Identify and bring waves, ocean, and ice pre and post processing scripts to develop

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/global-workflow#367]
Identity the pre and post processing scripts for waves, ocean and ice used in coupled prototypes and integrate with develop.

**Comment by JessicaMeixner-NOAA** [comment]
So in terms of ocean/ice pre-processing jobs, there is only the staging of the initial conditions.  The ocean/ice post job and the initial condition staging job have been described in detail in a comment on #369, which I am not repeating here for now. 


For waves, all jobs are in the develop branch for pre-and post-processing.  However, the develop branch and the feature/coupled-crow branch are out of sync and need to be reconciled. One of the bigger differences is in the fix file.  Recently in https://github.com/NOAA-EMC/global-workflow/pull/343 in feature/coupled-crow fix files that should actually be parm files were updated accordingly.  Most of this work cannot be done until we can either 1. run atm-ocn-ice-wav coupled in develop or 2. Issue #256 is resolved so we can run atm->wav in the v16 like configuration in develop.    In the meantime I can attempt to determine what I think should work but you can't test or confirm until we have 1 or 2.  Another major difference between the two branches is that in develop for v16 we process boundary points and we do not do those jobs for featue/coupled-crow for the prototypes.  This will be needed for a future GFS, so some sort of option to do or not needs to at some point be made.  Lastly another big difference is that the gridded post processing in develop runs side-by-side with the forecast job (which we would want in a future GFS scenario) but for the prototype runs in feature/coupled-crow this job is dependent on the forecast job completing.
