### ISSUE TITLE
Update free forecast setup for coupled model.

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/global-workflow#368]
Update free forecast setup scripts (experiment and workflow) to include coupled model mode.

Branch created for this effort: feature/coupled_sprint

**Comment by KateFriedman-NOAA** [comment]
Sync merged develop into feature/coupled_sprint @ 2d5a8ec

**Comment by aerorahul** [comment]
This was part of the 1st sprint and is now part of `feature/coupled_sprint`. 
Closing.
