### ISSUE TITLE
Setup test experiments using feature/coupled_crow

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/global-workflow#369]
Set up test experiment directories, configurations and workflow xml for a prototype coupled application on Orion.

This includes:
- final bash configuration scripts 
- workflow xml
- rotdir with initial conditions
- rundir for forecast
- document the steps for replicating the experiment setup (use `history` command and paste them somewhere so someone else can replicate)

Identify:
- script that does staging of initial conditions
- scripts in the workflow xml that are missing from develop (ocean, ice, waves etc)

**Comment by WalterKolczynski-NOAA** [comment]
### Steps to reproduce
```
git clone git@github.com:NOAA-EMC/global-workflow.git example
cd example
git checkout feature/coupled_old_setup
git submodule update --init
cd sorc
./checkout.sh -c
./build_all -c
./link_fv3gfs.sh emc orion coupled
cd ../workflow
cp user.yaml.default user.yaml
```
- edit user.yaml to set EXPROOT, COMROOT, DATAROOT, cpu_project, and hpss_project
- if you want to keep $DATA, also edit cases/coupled_free_forecast_wave.yaml and change KEEPDATA to YES
```
cd CROW
module load python/3.7.5
./setup_case.sh -p ORION ../cases/coupled_free_forecast_wave.yaml example
./make_rocoto_xml_for.sh $EXPROOT/example
cd $EXPROOT/example
rocotorun -d workflow.db -w workflow.xml
```
- do whatever you normally do to add rocoto to your crontab

### Output
expdir: /work/noaa/global/wkolczyn/save/global-workflow/expdir/example
ROTDIR: /work/noaa/global/wkolczyn/noscrub/global-workflow/example
Saved copy of PTMP: /work/noaa/global/wkolczyn/noscrub/global-workflow/example/ptmp_copy

### Notes
The python moduleload is necessary due to some issue with CROW not finding python with the default python/3.9.2 module on Orion.

I can provide an example if anyone is unfamiliar with adding rocoto to their crontab on Orion.

**Comment by aerorahul** [comment]
@WalterKolczynski-NOAA 
Thanks!  Can you please open up the permissions to those directories?

```
501 Orion-login-1 ~ ❯❯❯ ls /work/noaa/global/wkolczyn/save/global-workflow/expdir/example
/bin/ls: cannot access /work/noaa/global/wkolczyn/save/global-workflow/expdir/example: Permission denied
502 Orion-login-1 ~ ❯❯❯ ls  /work/noaa/global/wkolczyn/noscrub/global-workflow/example
/bin/ls: cannot access /work/noaa/global/wkolczyn/noscrub/global-workflow/example: Permission denied
503 Orion-login-1 ~ ❯❯❯ ls /work/noaa/global/wkolczyn/noscrub/global-workflow/example
/bin/ls: cannot access /work/noaa/global/wkolczyn/noscrub/global-workflow/example: Permission denied
```

**Comment by WalterKolczynski-NOAA** [comment]
Try now

**Comment by JessicaMeixner-NOAA** [comment]
The script that does the staging of initial conditions is feature/coupled-crow [jobs/rocoto/coupled_ic.sh](https://github.com/NOAA-EMC/global-workflow/blob/feature/coupled-crow/jobs/rocoto/coupled_ic.sh)
More info on this script/job: 
* It’s the first job that runs, and requires pre-staged ICs but there is no other job dependency, the forecast job is dependent on this job completing before it can start.  
* In crow the <walltime>00:30:00</walltime>  and  <nodes>1:ppn=24</nodes> however, we really just need one core as this is just copying things and takes significantly less than 30 minutes. 
* The configs are called in [L28](https://github.com/NOAA-EMC/global-workflow/blob/feature/coupled-crow/jobs/rocoto/coupled_ic.sh#L28)  and are: [base](https://github.com/NOAA-EMC/global-workflow/blob/feature/coupled-crow/workflow/config/base.yaml)  [fv3ic](https://github.com/NOAA-EMC/global-workflow/blob/feature/coupled-crow/workflow/config/fv3ic.yaml)  and [wave](https://github.com/NOAA-EMC/global-workflow/blob/feature/coupled-crow/workflow/config/wave.yaml).   Likely the missing/most important variables for this are those defined in fv3ic on [L23-27](https://github.com/NOAA-EMC/global-workflow/blob/feature/coupled-crow/workflow/config/fv3ic.yaml#L23-L27)

The other missing script in xml job is the ocean/ice post: 
* The ocean/ice post jobs are split into several jobs.  The number of those jobs is defined in the case file in CROW in the 
         output_settings:  
                  OCN_INTERVAL: 24
    If “24” is chosen like above, then the ocean/ice post (which is 6 hourly output, then will call many jobs defining OCN_FHRLST="[0, 6, 12, 18]" and then OCN_FHRLST="[24, 30, 36, 42] and so on before calling the main script. @JianKuang-UMD split this job, so questions about how the splitting works, probably would be best directed to him. 
* Currently the time per job is set as: <walltime>00:30:00</walltime>,  <nodes>1:ppn=1</nodes> which is a good estimate of time.  
* Dependency of this job as of now is for when the forecast finishes.  Theoretically, they could be when the interval of jobs has its required files, but that would be an “extra” and keeping it for the dependency as it is now is fine. 
* The main job script is in feature/couped-crow [jobs/rocoto/ocnpost.sh](https://github.com/NOAA-EMC/global-workflow/blob/feature/coupled-crow/jobs/rocoto/ocnpost.sh)  
* The main job script calls two other scripts: 
  -  [scripts/run_regrid.sh](https://github.com/NOAA-EMC/global-workflow/blob/feature/coupled-crow/scripts/run_regrid.sh) 
      - Which uses two ncl ush scripts  [ush/icepost.ncl](https://github.com/NOAA-EMC/global-workflow/blob/feature/coupled-crow/ush/icepost.ncl) and [ush/ocnpost.ncl](https://github.com/NOAA-EMC/global-workflow/blob/feature/coupled-crow/ush/ocnpost.ncl) and requires the ncl module to be loaded in module_base (see [link](https://github.com/NOAA-EMC/global-workflow/blob/feature/coupled-crow/modulefiles/module_base.orion#L13) for example). 
  -  [scripts/un_reg2grb2.sh](https://github.com/NOAA-EMC/global-workflow/blob/feature/coupled-crow/scripts/run_reg2grb2.sh) 
      - Which requires an executable to be built. 
      - Modules to build this exe are for example [modulefiles/modulefile.reg2grb2.orion](https://github.com/NOAA-EMC/global-workflow/blob/feature/coupled-crow/modulefiles/modulefile.reg2grb2.orion)
      - The sorc for this directory is the entire directory is [sorc/reg2grb2.fd](https://github.com/NOAA-EMC/global-workflow/tree/feature/coupled-crow/sorc/reg2grb2.fd) and according to the commit message [here](https://github.com/NOAA-EMC/global-workflow/commit/b4e6a5fa6d7b86fcfd6d120cd0d9ba1a66dca30c) this gets built as part of the workflow_utils cmake build
* [Configs](https://github.com/NOAA-EMC/global-workflow/blob/feature/coupled-crow/jobs/rocoto/ocnpost.sh#L18)  used are base and [ocnpost](https://github.com/NOAA-EMC/global-workflow/blob/feature/coupled-crow/workflow/config/ocnpost.yaml) 
* Fix files need to be added to the link script, see line [73](https://github.com/NOAA-EMC/global-workflow/blob/feature/coupled-crow/sorc/link_fv3gfs.sh#L73) 
  - The ones probably needed for this job are a subset of: fix_cice fix_mom6 fix_cpl fix_reg2grb2

**Comment by JessicaMeixner-NOAA** [comment]
So ignoring the differences in scripts/fix/etc for waves, when you set-up the jobs themselves, there's a couple of major differences (which are also described in  #367) for the post processing jobs themselves, which I will repeat here: 
* the develop branch runs jobs for boundary point post processing, which is not needed for the propototypes.  
* he gridded post processing in develop runs side-by-side with the forecast job (which we would want in a future GFS scenario) but for the prototype runs in feature/coupled-crow this job is dependent on the forecast job completing.

**Comment by JessicaMeixner-NOAA** [comment]
@KateFriedman-NOAA
