### ISSUE TITLE
Build issues related to Bash vs Dash

### ISSUE THREAD

**Issue by julien-faye** [NOAA-EMC/global-workflow#381]
Hello,

I am trying to build the project on Ubuntu 20.04.2, both x86_64 and aarch64.

Following the instructions in the README.md

```
While in /sorc folder:

$ sh checkout.sh
```

I face these errors::
```
 sh checkout.sh
+ getopts o option
+ pwd
+ topdir=/home/ubuntu/git/2021.H2/global-workflow/sorc
+ echo /home/ubuntu/git/2021.H2/global-workflow/sorc
/home/ubuntu/git/2021.H2/global-workflow/sorc
+ echo fv3gfs checkout ...
fv3gfs checkout ...
+ [[ ! -d fv3gfs.fd ]]
checkout.sh: 27: [[: not found
+ echo Skip.  Directory fv3gfs.fd already exists.
Skip.  Directory fv3gfs.fd already exists.
+ echo gsi checkout ...
gsi checkout ...
+ [[ ! -d gsi.fd ]]
checkout.sh: 39: [[: not found
+ echo Skip.  Directory gsi.fd already exists.
Skip.  Directory gsi.fd already exists.
+ echo gldas checkout ...
gldas checkout ...
+ [[ ! -d gldas.fd ]]
checkout.sh: 51: [[: not found
+ echo Skip.  Directory gldas.fd already exists.
Skip.  Directory gldas.fd already exists.
+ echo ufs_utils checkout ...
ufs_utils checkout ...
+ [[ ! -d ufs_utils.fd ]]
checkout.sh: 62: [[: not found
+ echo Skip.  Directory ufs_utils.fd already exists.
Skip.  Directory ufs_utils.fd already exists.
+ echo EMC_post checkout ...
EMC_post checkout ...
+ [[ ! -d gfs_post.fd ]]
checkout.sh: 73: [[: not found
+ echo Skip.  Directory gfs_post.fd already exists.
Skip.  Directory gfs_post.fd already exists.
+ checkout_wafs=NO
+ [[ NO == YES ]]
checkout.sh: 98: [[: not found
+ echo EMC_verif-global checkout ...
EMC_verif-global checkout ...
+ [[ ! -d verif-global.fd ]]
checkout.sh: 112: [[: not found
+ echo Skip. Directory verif-global.fd already exist.
Skip. Directory verif-global.fd already exist.
+ exit 0
```

The command works if I use `bash checkout.sh` instead. Note: `bash` versus `sh`. On my systems `/bin/sh` is a symlink to `/bin/dash`.

I used the word `works`, not `passes` because I see such lines:
```
+ git submodule update
Cloning into '/home/ubuntu/git/2021.H2/global-workflow/sorc/gsi.fd/fix'...
ssh: Could not resolve hostname gerrit: Temporary failure in name resolution
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'gerrit:GSI-fix' into submodule path '/home/ubuntu/git/2021.H2/global-workflow/sorc/gsi.fd/fix' failed
Failed to clone 'fix'. Retry scheduled
Cloning into '/home/ubuntu/git/2021.H2/global-workflow/sorc/gsi.fd/libsrc'...
ssh: Could not resolve hostname gerrit: Temporary failure in name resolution
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'gerrit:GSI-libsrc' into submodule path '/home/ubuntu/git/2021.H2/global-workflow/sorc/gsi.fd/libsrc' failed
Failed to clone 'libsrc'. Retry scheduled
Cloning into '/home/ubuntu/git/2021.H2/global-workflow/sorc/gsi.fd/fix'...
ssh: Could not resolve hostname gerrit: Temporary failure in name resolution
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'gerrit:GSI-fix' into submodule path '/home/ubuntu/git/2021.H2/global-workflow/sorc/gsi.fd/fix' failed
Failed to clone 'fix' a second time, aborting
+ cd /home/ubuntu/git/2021.H2/global-workflow/sorc
```

**Comment by KateFriedman-NOAA** [comment]
@julien-faye Thanks for letting us know about the issues with global-workflow checkout and dash. We don't support dash right now so I can't provide any feedback on the issue you see but I'm glad to hear that checkout.sh works when you use `bash` before it. The next version of the system (GFSv17/UFS) will replace checkout.sh with a more supported/robust checkout method.

> ssh: Could not resolve hostname gerrit: Temporary failure in name resolution
fatal: Could not read from remote repository.

The submodules for the GSI component still live in our internal git server (VLab) unfortunately but work is ongoing to get those pieces moved to GitHub as well as soon as possible. The internal server does not allow anonymous access however, so our NOAA users set up a gerrit alias in their .ssh/config files with the information needed to access the server (e.g. address and username). If you are a NOAA user (or an affiliate) and have access to VLab I can provide more details on that alias. Please pardon our dust while we're still in the process of migrating all our codes to GitHub. Thanks!

**Comment by julien-faye** [comment]
Thank you for your response, @KateFriedman-NOAA !

I am not a NOAA user or an affiliate, so I guess I will have to wait for now.

**Comment by julien-faye** [comment]
By the way, is global-workflow supported on Linux ARM64 ?

**Comment by KateFriedman-NOAA** [comment]
@julien-faye The global-workflow (and it's components) may work on Linux ARM64 but it is not supported there. The main concern would be the forecast model component which is more sensitive to the architecture. 

Note: by "supported" I mean someone at NOAA has tested the forecast system on that platform and is available for troubleshooting and to make updates to continue support for users there.

**Comment by julien-faye** [comment]
@KateFriedman-NOAA Sorry, I am not sure that I understood you.
You say ARM64 is **not** supported but then "... (someone at NOAA) is available for troubleshooting and to make updates to continue support for users there". 
That is, ARM64 is not officially supported by NOAA  but we still may get some help if we face issues ?

**Comment by KateFriedman-NOAA** [comment]
@julien-faye Apologies if there was confusion about my reply. I was letting you know what our definition of "supported" is and that we aren't supporting machines that we don't have a presence on at the moment. Due to resource constraints we can not currently provide support beyond our tier 1 NOAA platforms. We hope to make the system more generic to extend support in the future but we are still getting our feet wet in that arena.

**Comment by martin-g** [comment]
Hi @KateFriedman-NOAA !

I am also interested in seeing Global Workflow working on Linux ARM64!

I work for https://openlabtesting.org/. We provide ARM64 VMs to Open Source projects that they could use for testing and CI needs. Please let me know if you are interested!

Other providers of ARM64 hardware for OSS projects are:
* FOSSHOST - https://fosshost.org/apply
* WorksOnArm - https://github.com/WorksOnArm/cluster

**Comment by KateFriedman-NOAA** [comment]
@martin-g Thank you for this information. At this time we aren't yet able to extend support beyond our tier 1 NOAA platforms but should that change and we have an interest in an ARM64 VM we will let you know.

Closing this issue. Thanks!
