### ISSUE TITLE
P7: Update input nameless

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#386]
All namelist values need to be checked and confirmed that the correct options are being used for all components. 
Tracking some of this being done in the google doc [here](https://docs.google.com/document/d/1KxrmA74qqu6jMkjQqREbQfuApSksoSozSLKdlv_oGuE/edit?usp=sharing). 

The namelist that we know need updating for now are: 
* LANDICE should be false 
* Check uGWD settings 
* The following for 
ialb=2
iems=2
lsm=2 
iopt_dveg=4
iopt_crs=2
iopt_rad=3
iopt_alb=1
iopt_stc=3

* Use recommended CA settings from Lisa: These are the settings we recommend for the CA, under the namelist  block &gfs_physics_nml. Note that iseed_ca can be set to the ensemble member number if used in an ensemble forecast. 
  do_ca          = .True.
  ca_sgs         = .True.
  nca            = 1
  scells         = 2600
  tlives         = 1800
  nseed          = 1
  nfracseed      = 0.5
  rcell          = 0.72
  ca_trigger     = .True.
  nspinup        = 1
  iseed_ca       = 12345

There might be more as we continue to check the settings for the various different physics options and all components.

**Comment by yangfanglin** [comment]
Jessica, I have reviewed the namelist differences included in [here](https://docs.google.com/document/d/1KxrmA74qqu6jMkjQqREbQfuApSksoSozSLKdlv_oGuE/edit).   More changes are required for setting up p7c namelist options.  Please use the settings in https://www.emc.ncep.noaa.gov/gmb/wx24fy/misc/gfsv17/input.nml_C768L127_ColdStart_NoahMP_MERRA2_uGWDv1 except for those related to model resolution and cold/warm start ICs.

**Comment by JessicaMeixner-NOAA** [comment]
Thanks @yangfanglin

**Comment by WalterKolczynski-NOAA** [comment]
Do we need the cellular automata stuff if we're not running an ensemble?

**Comment by JessicaMeixner-NOAA** [comment]
Yes we need CA for P7c item 5 c) "c) "Stochastic parameterization of organized tropical convection using cellular automata"
listed in the document [here](https://docs.google.com/document/d/1KpQsnZclW3BBX4pZAKPV_c58XjHy3F_H_4jAEmrlpek/edit?usp=sharing)

**Comment by WalterKolczynski-NOAA** [comment]
I know LANDICE is tied to Noah-MP. Are any of the other changes tied to changes we recently made (or to each other)?

**Comment by JessicaMeixner-NOAA** [comment]
These are all NOAH-MP options that @HelinWei-NOAA said to use: 
Noah MP

  lsm          = 2
  iopt_dveg    = 4
  iopt_crs     = 2
  iopt_btr     = 1
  iopt_run     = 1
  iopt_sfc     = 1
  iopt_frz     = 1
  iopt_inf     = 1
  iopt_rad     = 3
  iopt_alb     = 1
  iopt_snf     = 4
  iopt_tbot    = 2
  iopt_stc     = 3
some of them are already being used, others are not.  

Not sure on some of the others, do we need to attempt to back-track this information out of the updates from regtests?   Is it a matter of what needs to be configured together? Or what's the need for knowing what's tied together?

**Comment by WalterKolczynski-NOAA** [comment]
Anything that is bundled together should be set based on the key value, i.e. if Noah-MP is active all of those settings will be set to those values (at least as a default).

**Comment by JessicaMeixner-NOAA** [comment]
@yangfanglin provided the [uGWD info](https://docs.google.com/document/d/1qfmP1CMIkVjLK_BBnmYAW0N1nXo5G9ezi3Qpux1QpVw/edit?usp=sharing) 
@AnningCheng-NOAA can help let you know about MERRA2 climatology settings, but I believe those are all okay now
@HelinWei-NOAA and @barlage can help identify the NOAH-MP namelist setting groupings 
Lisa Bengtsson can help with CA questions beyond the namelist values she's already provided. 
The [p7 mini prototype document](https://docs.google.com/document/d/1KpQsnZclW3BBX4pZAKPV_c58XjHy3F_H_4jAEmrlpek/edit?usp=sharing) has namelist information in it.  Additionally we can try to work it backwards from the rt.sh.  Please let me know which parameters you have specific questions on so I can help track down answers for you @WalterKolczynski-NOAA
