### ISSUE TITLE
BUG: Fix race condition between vrfy and metp jobs

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#401]
Discovered that when the vrfy and metp jobs are running at the same time and the metp jobs finish first (usually only during the first full cycle they are invoked) they remove a DATA folder that is incorrectly shared with the vrfy job. Only found because WCOSS-Dell was quiet enough to allow jobs to all start as soon as they were submitted, most users will not encounter this bug.

Easy fix is to change the metp jobs to not use "vrfy" in their DATA paths and instead use something else (e.g. "metp") in the DATA path. Change this line in jobs/rocoto/metp.sh:

from:
`export DATAROOT="$RUNDIR/$CDATE/$CDUMP/vrfy"`
to:
`export DATAROOT="$RUNDIR/$CDATE/$CDUMP/metp"`

https://github.com/NOAA-EMC/global-workflow/blob/develop/jobs/rocoto/metp.sh#L48

**Comment by WalterKolczynski-NOAA** [comment]
DATA directories should probably be using the pid like other jobs.

**Comment by malloryprow** [comment]
@KateFriedman-NOAA, Will you need any help from me on this bug?

**Comment by KateFriedman-NOAA** [comment]
@WalterKolczynski-NOAA Yeah, I think that's what I'm going to do, incorporate pid to further differentiate the jobs and metp metatasks.

@malloryprow I don't think so, this appears to just be a workflow layer issue. I'll let you know if I do need you though, thanks! :)

**Comment by KateFriedman-NOAA** [comment]
Created branch for this issue: https://github.com/KateFriedman-NOAA/global-workflow/tree/feature/issue401
