### ISSUE TITLE
Out of date modulefiles for stampede2

### ISSUE THREAD

**Issue by benjamin-cash** [NOAA-EMC/global-workflow#406]
module_base.stampede,  modulefile.reg2grb2.stampede, and  modulefile.ww3.stampede all point to a deprecated installation of hpc-stack on stampede2 and in some cases load older module versions than are currently in use. 

The current hpc-stack for stampede2 is here: 
module use /work/08048/hanglei/stampede2/NCEP/install/hpc-stack/modulefiles/stack/
module load hpc/1.1.0

**Comment by lgannoaa** [comment]
@benjamin-cash are you using the most current global workflow develop blench? Where is your HOMEgfs package located? I will evaluate to see if I can help.

**Comment by benjamin-cash** [comment]
I didn't realize this was still open, I think we can go ahead and close this. Sorry for the confusion!
