### ISSUE TITLE
rocoto_viewer.py on WCOSS not working now without Gyre

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/global-workflow#41]
CRITICAL ERROR: The produtil package could not be loaded from your system

Lines 194-199 of rocoto_viewer.py:
```
    PRODUTIL = collections.defaultdict(list)
    PRODUTIL['hera'] = '/scratch1/NCEPDEV/global/glopara/svn/nceplibs/produtil/trunk/ush'
    PRODUTIL['luna']  = '/gpfs/hps3/emc/global/noscrub/emc.glopara/svn/nceplibs/produtil/trunk/ush'
    PRODUTIL['tide']  = '/gpfs/td1/emc/global/save/emc.glopara/svn/nceplibs/produtil/trunk/ush'
    PRODUTIL['gyre']  = '/gpfs/gd1/emc/global/save/emc.glopara/svn/nceplibs/produtil/trunk/ush'
    try_clusters = ('hera','luna','tide','gyre')
```

**Comment by CoryMartin-NOAA** [comment]
Sorry, the issue is actually because surge is unmounted I believe.

**Comment by RussTreadon-NOAA** [comment]
Yes, you are correct.   Surge is offline today so we can't get to

/gpfs/hps3/emc/global/noscrub/emc.glopara/svn/nceplibs/produtil/trunk/ush

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA is there an equivalent directory on Venus somewhere? If so, I can modify the gfsv16b version of this file to support it working without the cray.

**Comment by KateFriedman-NOAA** [comment]
@CoryMartin-NOAA I can set up a Dell copy...stay tuned...

**Comment by RussTreadon-NOAA** [comment]
We could copy /gpfs/td1/emc/global/save/emc.glopara/svn/nceplibs/produtil
(Tide fileset) to Venus or Mars.  It's better to contact EIB workflow team
or nceplibs team to respond & correct.

**Comment by CoryMartin-NOAA** [comment]
Thanks @KateFriedman-NOAA, I cloned a local version of pyprodutil for me to use for now, but I'll switch to the permanent paths once they exist on Dell.

**Comment by KateFriedman-NOAA** [comment]
@CoryMartin-NOAA I pulled over the Luna copy to Mars and then Venus. Please try this and if it works I can update the paths in rocoto_viewer.py.

/gpfs/dell2/emc/modeling/noscrub/emc.glopara/svn/nceplibs/produtil

**Comment by KateFriedman-NOAA** [comment]
Created branch hotfix/viewer to update produtil paths on WCOSS.

**Comment by CoryMartin-NOAA** [comment]
@KateFriedman-NOAA Using that path (well after adding /trunk/ush) seems to work. It's a bit slow to respond but I don't know if that is because of the pyprodutil or because of the scheduler/filesystem.

**Comment by KateFriedman-NOAA** [comment]
@CoryMartin-NOAA The filesystem has been somewhat slow on WCOSS recently...was it faster using your local install of pyprodutil?

**Comment by CoryMartin-NOAA** [comment]
@KateFriedman-NOAA no I tried with both, seems to be similarly slow. I think it's safe to use:
/gpfs/dell2/emc/modeling/noscrub/emc.glopara/svn/nceplibs/produtil//trunk/ush

**Comment by KateFriedman-NOAA** [comment]
@CoryMartin-NOAA Ok great, thanks! I have made the path changes to the viewer in the hotfix branch. It is working on Venus. I'll initiate a PR shortly.

**Comment by KateFriedman-NOAA** [comment]
Initiated PR #42

**Comment by KateFriedman-NOAA** [comment]
Thank you @CoryMartin-NOAA for reporting this bug via a GitHub issue and for testing the fix!

PR has been completed and hotfix/viewer branch deleted. Closing issue and sending commit announcement.
