### ISSUE TITLE
GFSv16.1.4 - Operational Assimilation of Commercial GPS-RO in DO-3

### ISSUE THREAD

**Issue by CatherineThomas-NOAA** [NOAA-EMC/global-workflow#420]
Delivery Order 3 (DO-3) of the commercial GPS-RO data purchase was awarded to Spire only. Delivery runs from Sept 16, 2021 (11am ET, 1500 UTC) to March 16, 2022. On Sept 16, 2021, GeoOptics data will also stop flowing.

The implementation number is still unconfirmed by NCO. We will use v16.1.3 until we get confirmation.

The DA work associated with this implementation will be documented in [GSI Issue #200](https://github.com/NOAA-EMC/GSI/issues/200)

The anticipated workflow changes should be contained only in the new DA tag.

**Comment by KateFriedman-NOAA** [comment]
Created workflow branch off of `operations` branch for this release: `release/gfs.v16.1.3`

**Comment by KateFriedman-NOAA** [comment]
Tag for release to NCO cut from the release/gfsv16.1.3 branch: [EMC-v16.1.3](https://github.com/NOAA-EMC/global-workflow/releases/tag/EMC-v16.1.3)

**Comment by KateFriedman-NOAA** [comment]
Implementation date is tentatively the week of September 20th, no firm date/cycle yet.

**Comment by CatherineThomas-NOAA** [comment]
As a result of the obsproc implementation on Aug 18, a bug in the read_nsstbufr routine was discovered (described in GSI [#208](https://github.com/NOAA-EMC/GSI/issues/208)). It has been decided that this change will be included with the DO-3 GPSRO changes.

The gfsda.v16.1.3 tag was recreated.  No change to the workflow is needed.

The v16.1.3 implementation is planned for 9/20.

**Comment by CatherineThomas-NOAA** [comment]
Validation of the parallel production test on 9/16 at 18z was successful.  The DO-3 data was processed properly and results were as expected.

Implementation of v16.1.3 was pushed back to Monday 9/27 at 12z at NCO's request.

**Comment by KateFriedman-NOAA** [comment]
Emergency change in ops this week became the new v16.1.3. This change will now implement next week as GFSv16.1.4. Updating branch and tags accordingly.

**Comment by KateFriedman-NOAA** [comment]
Checked out `release/gfsv16.1.3` branch, created `release/gfsv16.1.4` from it and pushed it up to repo:

https://github.com/NOAA-EMC/global-workflow/tree/release/gfs.v16.1.4

Created new "hand-off" tag from `release/gfsv16.1.4`: 

https://github.com/NOAA-EMC/global-workflow/releases/tag/EMC-v16.1.4

Will now remove prior `EMC-v16.1.3` tag and recreate it from a new `release/gfsv16.1.3` branch that will be created to document the emergency change in operations.

**Comment by KateFriedman-NOAA** [comment]
@CatherineThomas-NOAA I just sync merged the recent update in the `operations` branch to change the `EMC_post` repo name to `UPP` into the newly named release/gfs.v16.1.4 branch, I'd forgotten to do so. NCO doesn't need the repo name update in ops, the old name still works. They'll get the repo name change in the next hand-off for v16.1.5. We can now update the release notes and the GSI tag in checkout.sh for the version change.

**Comment by KateFriedman-NOAA** [comment]
Recut `EMC-v16.1.4` tag after updating `release/gfs.v16.1.4` branch.

**Comment by KateFriedman-NOAA** [comment]
From the September 24th RFC memo:

```
RFC 8702 - On WCOSS, implement GFS v16.1.4. This update includes turning
on the active assimilation of Spire gpsro (GPS radio occultation) data and turning
off the active assimilation of GeoOptics gpsro data. In addition, this update will
fix a bug in the GFS/GSI where large errors are seen in SSTs. To be
implemented on September 27 at 1430Z.
```

**Comment by KateFriedman-NOAA** [comment]
SPA Simon Hsiao is implementing in 12z gfs today.

**Comment by KateFriedman-NOAA** [comment]
From this morning's SDM log:
```
1t. 1432Z - SPA Simon is starting work on RFC 8702 - WCOSS GFSv16.1.4 update. 1930Z - Complete.
```
