### ISSUE TITLE
Handling of joint ice-ocean settings

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#429]
Even though they are compartmentalized in different sections, a lot of the ocean and ice settings either should be shared or are shared but only set in one or the other blocks. A couple examples: (a) the resolutions are separate but always the same; (b) the mesh file is linked to the run directory in the ice section using the ice resolution. This allows the possibility of mismatches (like different resolutions being set) that cause the wrong fix files to be linked and possibly other, more fundamental incongruities within the model.

There's a need to determine how many degrees of freedom for OCN and ICE should be supported. Do they always run together? Do they have to be the same resolution? These questions will determine whether the settings should be merged, or kept separate, possibly with a third section executed when either are active.

**Comment by aerorahul** [comment]
@WalterKolczynski-NOAA 
Can we narrow down this issue to identifying actionable items that can be completed in a reasonable time/effort.  As it stands currently, this issue is very open ended without a clear definition of Done.

**Comment by WalterKolczynski-NOAA** [comment]
@aerorahul Left this open to eventually follow-through on your request, but after consideration I think we can just close it. We _could_ replace `$ICERES` with `$OCNRES`, but keeping a separate `$DO_ICE` and forecast functions is probably just cleaner than merging them.
