### ISSUE TITLE
Update post repository name from "EMC_post" to "UPP"

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#433]
The name of the [EMC_post](https://github.com/NOAA-EMC/EMC_post) repository on GitHub will be changing to `UPP` the week of September 6th. Email from @HuiyaChuang-NOAA : 

```
In an effort to unify naming conventions for UPP across the board, we are planning to change the name of UPP repository
on Github from "EMC_post" to "UPP" in the week of September 6.

If you currently have a UPP fork, you will need to manually change the name yourself.  If you have a script that checks
out UPP code from Github, please update your script to use the new name "UPP". More information on the impacts of
repository name change can be found in the Github documentation. 

Updates will be posted to the UPP Github Discussions board; questions may also be posted to the board and will be
answered by code managers.  

Please feel free to contact me or the other two UPP code managers with any questions:
Wen.Meng@noaa.gov
fossell@ucar.edu
```

Will need to update repo name for EMC_post in both Externals.cfg and checkout.sh. Will need to update the develop, operations, and GEFS branches. Most other branches can be updated via a sync merge from develop or operations. Thankfully GitHub will forward branches/tags that still point to "EMC_post" to the newly renamed "UPP" repo so no tags/branches should break from this change.

Tasks:

- [x] change repo name in develop branch
- [x] change repo name in operations branch
- [x] change repo name in release/gefs_v12 branch

**Comment by KateFriedman-NOAA** [comment]
ON HOLD pending actual name change.

**Comment by HuiyaChuang-NOAA** [comment]
@KateFriedman-NOAA 
Thank you for responding to this.  @WenMeng-NOAA and I will send out an announcement when the change is made.

**Comment by KateFriedman-NOAA** [comment]
Change to rename the `EMC_post` repo to `UPP` has occurred. Quickly testing checkout, build, and single free-forecast cycle on Hera to confirm no issues.

**Comment by WenMeng-NOAA** [comment]
@KateFriedman-NOAA Thanks for verifying.

**Comment by KateFriedman-NOAA** [comment]
Initiated PRs to update the EMC_post/UPP checkout in both the develop (#441) and operations (#442) branches. Added @WenMeng-NOAA as reviewer in both PRs to sign off on repo name change in checkout.

**Comment by KateFriedman-NOAA** [comment]
@WalterKolczynski-NOAA Last item for this issue is to update the repo name in the GEFS branch. Can close once complete.

**Comment by KateFriedman-NOAA** [comment]
@XianwuXue-NOAA updated the repo name in his fork branch which will come back to the auth repo later. See change here:

https://github.com/XianwuXue-NOAA/global-workflow/blob/feature/gefs_v12_github_port2acorn/sorc/checkout.sh

All done, closing issue.
