### ISSUE TITLE
Stop copying unnecessary files to forecast run directory

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#436]
There are a number of wave mod_def files that are currently copied to the forecast run directory in the sprint branch that are not present from coupled-crow in the same location. That indicates these files are unnecessary for the forecast, so they should not be copied into the run directory (do they need to be created at all)?

```
Only in RUNDIRS/add_coupled/2013040100/gfs/fcst.85503: mod_def.aoc_9km
Only in RUNDIRS/add_coupled/2013040100/gfs/fcst.85503: mod_def.at_10m
Only in RUNDIRS/add_coupled/2013040100/gfs/fcst.85503: mod_def.ep_10m
Only in RUNDIRS/add_coupled/2013040100/gfs/fcst.85503: mod_def.glix_10m
Only in RUNDIRS/add_coupled/2013040100/gfs/fcst.85503: mod_def.glo_15mxt
Only in RUNDIRS/add_coupled/2013040100/gfs/fcst.85503: mod_def.glo_30m
Only in RUNDIRS/add_coupled/2013040100/gfs/fcst.85503: mod_def.gnh_10m
Only in RUNDIRS/add_coupled/2013040100/gfs/fcst.85503: mod_def.gsh_15m
Only in RUNDIRS/add_coupled/2013040100/gfs/fcst.85503: mod_def.wc_10m
```

Additionally, the following files are also being copied to the forecast run directory that appear unnecessary (they aren't present in coupled-crow):
```
Only in RUNDIRS/add_coupled/2013040100/gfs/fcst.85503: rmp_src_to_dst_conserv_002_001.nc
Only in RUNDIRS/add_coupled/2013040100/gfs/fcst.85503: rmp_src_to_dst_conserv_003_001.nc
```

**Comment by JessicaMeixner-NOAA** [comment]
If mod_def files are being copied in, they are probably also being created when they shouldn't be.  This is likely an issue of parameter files being set incorrectly.  

For the rmp files, whether we need them or not should be a configurable variable and then control if you copy the files in or not.

**Comment by WalterKolczynski-NOAA** [comment]
After changing some additional WW3 grid lists, the extra grids are eliminated.
