### ISSUE TITLE
New EMC_verif-global tag: verif_global_v2.5.2

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#438]
Update to new EMC_verif-global tag: `verif_global_v2.5.2` 

New tag includes the hook of fit-to-obs plotting in EMC_verif-global, as well as the ability to produce scorecards with EMC_verif-global and not having to use METviewer AWS. New tag provided by @malloryprow 

Will run a low res cycled test with new tag to confirm functionality in global-workflow.

**Comment by malloryprow** [comment]
EMC_verif-global has moved ahead a couple tags

- verif_global_v2.4.0 now supports running on JET (both in the global workflow and standalone, I sent this tag to @DavidHuber-NOAA)
- verif_global_v2.5.0 includes a small update to the mediator script to the global workflow, where the default for DATAROOT was updated to match the new DATAROOT in jobs/rocoto/metp.sh, and an enhancement in the plotting scripts used to create the DA ensemble plots to support plotting when the comparing models are on different grid resolutions

verif_global_v2.5.0 is the latest tag now

**Comment by malloryprow** [comment]
verif_global_v2.5.1 is the latest tag now

I had to do a hot fix as the host name for METviewer AWS changed.

**Comment by KateFriedman-NOAA** [comment]
@malloryprow Thanks for the updated tags! Do you anticipate any other new tags in the next two weeks? If not, I'll proceed with updating the tag to `verif_global_v2.5.1` in develop later this week. Thanks!

**Comment by malloryprow** [comment]
I am not (fingers crossed for no more hot fixes!)

**Comment by KateFriedman-NOAA** [comment]
@malloryprow Thanks! I'll always take new tags for hotfixes whenever so never hesitate to send them my way when needed! :)

Has the `verif_global_v2.5.1` been tested in parallel by chance? If not, I'll need to run at least ~5 cycles somewhere to confirm no issues.

**Comment by malloryprow** [comment]
@KateFriedman-NOAA It has not run in parallel :(

**Comment by KateFriedman-NOAA** [comment]
> @KateFriedman-NOAA It has not run in parallel :(

Ok no worries! I'll run a 5 cycle low res test on WCOSS-Dell to confirm no issues at runtime. I'll share output with you to check when available, thanks!

**Comment by malloryprow** [comment]
@KateFriedman-NOAA All right, I'm gonna have another hotfix on the way. A user running on Hera ran into something. I truly feel that I manifested this, my goodness!

**Comment by KateFriedman-NOAA** [comment]
@malloryprow Got it, no worries! Best to fix things as they come up! I haven't started a cycled test yet so I'll wait for the new tag with the hotfix. Thanks!

**Comment by malloryprow** [comment]
verif_global_v2.5.2 had been created! :)

**Comment by KateFriedman-NOAA** [comment]
> verif_global_v2.5.2 had been created! :)

Ok, setting up test with new tag on Mars. Will share output when available, thanks!

**Comment by KateFriedman-NOAA** [comment]
@malloryprow Please see the following C192C96L127 METplus output on Mars:

```
/gpfs/dell2/emc/modeling/noscrub/Kate.Friedman/archive/metplus_data/by_VSDB/*/*/*/issue438
/gpfs/dell3/ptmp/Kate.Friedman/comrot/issue438/logs/*/gfsmetp*.log
```

Thanks!

**Comment by malloryprow** [comment]
@KateFriedman-NOAA Output looks good!

**Comment by KateFriedman-NOAA** [comment]
@malloryprow Awesome, thanks for checking and confirming! I am going to prep the PR into develop for this now. Since we'll be jumping over a few verif-global tags (v2.2.1 -> v2.5.2) could you please provide me a short bullet-point or paragraph summary of the changes between those versions? I'll include it in the commit details and the announcement email. Thanks!

**Comment by malloryprow** [comment]
Sure thing!

- Added capability to produce a scorecard (no need to use METviewer AWS to produce scorecards)
- Added capability to produce fit-to-obs plots
- Added support for Jet
- Updated DA ensemble plots graphics to support when models ensemble mean and spread output is on different
- Hot fix for new METviewer AWS host name
- Hot fix for reorganizing precipitation verification input files

**Comment by KateFriedman-NOAA** [comment]
@malloryprow Thanks for the bullet-list of updates relative to these tags! For the scorecard and fit-to-obs plots, do users need to do anything different/new or are they produced by default now when the new tag is used? Should I point users to the EMC_verif-global wiki for more details on those new features?

**Comment by malloryprow** [comment]
@KateFriedman-NOAA You can point them to the wiki. There were some new configuration settings added for them.

**Comment by KateFriedman-NOAA** [comment]
Will do, thanks @malloryprow! Just need your review on PR #450 and I'll commit the tag update into develop.

**Comment by KateFriedman-NOAA** [comment]
@malloryprow Question...is there text missing from this update bullet-point?

```
- Updated DA ensemble plots graphics to support when models ensemble mean and spread output is on different
```

It reads like it should end with "...on different grids" or something. Thanks!

**Comment by malloryprow** [comment]
@KateFriedman-NOAA It should! "Updated DA ensemble plots graphics to support when models ensemble mean and spread output is on different grids"

**Comment by KateFriedman-NOAA** [comment]
@malloryprow Great, thanks for confirming! Just need your approval on PR #450 and I'll get this update in and announced. Thanks!
