### ISSUE TITLE
GFSv16.1.5 - GSI update to include IASI Metop-C in operations

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#439]
Preparation for turning on CrIS NPP radiances and include IASI Metop-C in operational GFS system. Companion [GSI issue #186](https://github.com/NOAA-EMC/GSI/issues/186).

New version: v16.1.5

- [x] Update new GSI tag in checkout: `gfsda.v16.1.5`
- [x] Add release notes for v16.1.5
- [x] Cut EMC-v16.1.5 tag for hand-off
- [x] GFSv16.1.5 implemented into operations
- [x] Test release branch against ops after implementation (sanity reproducibility check)
- [x] Merge `release/gfs.v16.1.5` branch into `operations` branch

**Comment by KateFriedman-NOAA** [comment]
Created release branch for this work off of the `operations` branch: [`release/gfs.v16.1.5`](https://github.com/NOAA-EMC/global-workflow/tree/release/gfs.v16.1.5) [was release/gfsv16.1.4 at start of work]

Will sync branch with `operations` branch. Please update component tag versions as needed for this upgrade.

**Comment by KateFriedman-NOAA** [comment]
Sync merged branch with `operations` branch after updating `EMC_post` repo name to `UPP` in operations branch. Committed to release branch at 82d537e.

**Comment by KateFriedman-NOAA** [comment]
The emergency change in ops this week became v16.1.3. Therefore, the prior v16.1.3 is going into ops as v16.1.4 next week and this change becomes v16.1.5. Will update the release branch name.

**Comment by lgannoaa** [comment]
@KateFriedman-NOAA, I am in preparation for the v16iasicris2 parallel to switch to release/gfs.v16.1.5.
@HaixiaLiu-NOAA told us in an email on 9/24 that release/gfs.v16.1.5 should checkout release/gfsda.v16.1.5.
A check on this tag (release/gfs.v16.1.5), as of today (9/24 10:00a) it checkout git checkout gfsda.v16.1.1a.
Last commit was back in September 9th.

[Lin.Gan@m72z2 release_gfsv16.1.5]$ git branch -a
  develop
* release/gfs.v16.1.5
  remotes/origin/HEAD -> origin/develop
[Lin.Gan@m72z2 release_gfsv16.1.5]$ git log
commit 82d537e7e74c36b8247dae1a75b35a396b6a8e44 (HEAD -> release/gfs.v16.1.5, origin/release/gfs.v16.1.5, origin/operations)
Author: Kate Friedman <kate.friedman@noaa.gov>
Date:   Thu Sep 9 11:52:37 2021 -0400

May I know when are you plan to have this tag ready?

**Comment by KateFriedman-NOAA** [comment]
@lgannoaa I have updated the GSI tag in the `release/gfs.v16.1.5` branch to the new `gfsda.v16.1.5` tag. Will add the release notes to the branch next.

**Comment by lgannoaa** [comment]
@KateFriedman-NOAA, Please make the following fix to your origin/release/gfs.v16.1.5 tag:
- Fix the checkout.sh gldas checkout:
    git checkout gldas_gfsv16_release.v1.13.0
- Fix the checkout.sh EMC_verif-global checkout:
    git checkout verif_global_v2.3.0

**Comment by KateFriedman-NOAA** [comment]
@lgannoaa Did you get approval to update the GLDAS package too? I don't remember where that was left off. The v1.13.0 package isn't mentioned in the release notes.

**Comment by lgannoaa** [comment]
@RussTreadon-NOAA,
v16iasicris2 is using gldas_gfsv16_release.v1.13.0. Should origin/release/gfs.v16.1.5 tag using this version for gldas package?
Thank you for your clarification.

**Comment by lgannoaa** [comment]
@RussTreadon-NOAA, @KateFriedman-NOAA 
Let me take my comment out of this issue. The v16iasicris2 is NOT running with the gfs.v16.1.5 implementation tag. The different is locally modified GLDAS package and EMC verification package.

**Comment by RussTreadon-NOAA** [comment]
The reason for using `gldas_gfsv16_release.v1.13.0`  in the v16iasicris2 has been explained in a separate email thread.   The v16iasicris2 is using `gldas_gfsv16_release.v1.13.0` because this tag contains logic in `ush/gldas_forcing.sh`  that ensures the parallel uses the correct precipitation forcing file if it falls behind real time.   The logic is an `$RUN_ENVIR = "emc"` block so this section of the script will not be executed in operations.   

The v16iasicris2 is using `verif_global_v2.3.0` whereas tag gfs.v16.1.5 checks out `verif_global_v1.11.0`.  This was done for at least two reasons.  Operational METplus stat files have moved onto a newer version.  Plotting the v16iascris2 with operations requires v16iasicris2 METplus stat files be at a comparable version.  The v16iascris2 monitoring page needs Fit2Obs and Scorecard plots.   These are only generated by a newer version of verif-global.   

Neither the newer gldas nor verif-global tags are from the DA team.   Questions about the gldas tag should be directed to the land team.  Questions about verif-global should be directed to the verification group.  

GFS DA v16.1.5 does not require the newer gldas and verif-global tags.   The v16iaiscris2 requires these changes to ensure that it runs correctly and that we have a full suite of monitoring and evaluation plots.

**Comment by lgannoaa** [comment]
Thank you for your clarification, @RussTreadon-NOAA.

**Comment by KateFriedman-NOAA** [comment]
@lgannoaa We'll be updating the GLDAS and verif-global packages during the transition to WCOSS2 so we won't have to make local modifications like we've done for much longer thankfully.

**Comment by KateFriedman-NOAA** [comment]
Release notes provided by @HaixiaLiu-NOAA :

https://docs.google.com/document/d/19WSVMUh4hWS922isARpqgssZHpXKds-X8UaoJki9Fsc/edit

**Comment by HaixiaLiu-NOAA** [comment]
@KateFriedman-NOAA Thank you for changing the title.

**Comment by KateFriedman-NOAA** [comment]
@HaixiaLiu-NOAA I just sync merged the operations branch update for v16.1.4 into the release/gfs.v16.1.5 branch. The main updates are to parm/config/config.anal and the addition of the release notes for v16.1.4. See the changes @ https://github.com/NOAA-EMC/global-workflow/commit/8e52726b9cfd9887bb2e4df2aeed0c4663c676a0

**Comment by HaixiaLiu-NOAA** [comment]
@KateFriedman-NOAA I looked at the change [8e52726](https://github.com/NOAA-EMC/global-workflow/commit/8e52726b9cfd9887bb2e4df2aeed0c4663c676a0) and noticed that all changes are to the gfsv16_historical fix files which will not affect the operation. The changes will affect retrospective runs.

**Comment by KateFriedman-NOAA** [comment]
@HaixiaLiu-NOAA Yep, let me know if there are any similar config.anal updates needed for users running retrospective runs with the v16.1.5 updates. Thanks!

**Comment by KateFriedman-NOAA** [comment]
Cut hand-off tag [EMC-v16.1.5](https://github.com/NOAA-EMC/global-workflow/releases/tag/EMC-v16.1.5).

**Comment by KateFriedman-NOAA** [comment]
Recut EMC-v16.1.5 tag @ 5d1fe62 after adding mpirun prepend rank flag and updating release notes for the 2022 CO2 fix file bundling.

**Comment by KateFriedman-NOAA** [comment]
Recut EMC-v16.1.5 tag @ 0a5f1e9 after updating ufs-weather-model tag and updating the release notes to mention the new tag.

**Comment by KateFriedman-NOAA** [comment]
From Oct 22nd 2021 RFC memo:
```
RFC 8823 - On WCOSS, update GFS to v16.1.5 which includes:
● Turn on the active assimilation of Metop-C IASI (Infrared Atmospheric
Sounding Interferometer) data with correlated observation errors
● Update correlated observation errors for Metop-B IASI, N20 CrIS
(Cross-track Infrared Sounder), and NPP CrIS
● Put in a minimum threshold for saturation specific humidity to avoid
potential minimization issues.
● Add the 2022 CO2 projection files.

To be implemented on October 26 at 1430Z.
```

From SDM log Oct 26th:
```
1s. 1431Z - SPA Simon Hsiao; Notification: RFC 8823 - WCOSS: Upgrade to GFS v16.1.5 for
GSI changes ... @ Tue Oct 26, 2021 10:30 - 15:30 (EDT),  Start to implement this RFC. 
1930Z - This RFC is completed.
```

**Comment by KateFriedman-NOAA** [comment]
Test against operations was successful and reproduced. Complete PR #489 and cut new tag/release [NCO-v16.1.5](https://github.com/NOAA-EMC/global-workflow/releases/tag/NCO-v16.1.5). Thanks all!
