### ISSUE TITLE
 Change the XML to be homogeneous

### ISSUE THREAD

**Issue by zhanglikate** [NOAA-EMC/global-workflow#443]
When I use 12x16 for X and Y layout, then  workflow generated  <nodes>6:ppn=40+24:ppn=39</nodes>, that is the "old" Moab/Torque syntax that used to work before,  but  HERA has transitioned to Slurm.  So a warning always  come out  when I submit the  job and mentioned  it has been converted it into <nodes>30:ppn=40</nodes> .

**Comment by lgannoaa** [comment]
Hi @zhanglikate ,
Would you please show me your HOMEgfs and run log? I want to help you to find a solution.

Thanks,
Lin

**Comment by lgannoaa** [comment]
Some jobs are running on Hera using old job cards. It does not match the requested tasks with the number of requested nodes. This caused the Slurm task scheduler to issue a Warning message and ignored the setting. 
During a test using global-workflow develop on Hera I found the following jobs contain these bugs:
Job log directory:
/scratch1/NCEPDEV/stmp2/Lin.Gan/ptmp/com/naf19296/logs/2020090200
- gdasanaldiag.log (3936)
  7.794 + srun -l '--export=ALL' -n 90 --multi-prog /scratch1/NCEPDEV/stmp2/Lin.Gan/RUNDIRS/naf19296/2020090200/gdas/anal.311060/mp_diag.sh
  srun: Warning: can't honor --ntasks-per-node set to 40 which doesn't match the requested tasks 90 with the number of requested nodes 3. Ignoring --ntasks-per-node.
- gdasanalcalc.log (2181)
  0.075 + srun -l '--export=ALL' -n 1 /scratch1/NCEPDEV/global/Lin.Gan/git/gw-launcher-flag/exec/gaussian_sfcanl.exe
  srun: Warning: can't run 1 processes on 4 nodes, setting nnodes to 1
- gdasanal.log (7130, 8711)
  0 + srun -l --export=ALL -n 6 /scratch1/NCEPDEV/global/Lin.Gan/git/gw-launcher-flag/exec/global_cycle '1>OUTPUT.111018' '2>errfile'
  srun: Warning: can't run 6 processes on 11 nodes, setting nnodes to 6
- gdaseupd.log (2927)
  2.589 + srun -l '--export=ALL' -n 1 --multi-prog /scratch1/NCEPDEV/stmp2/Lin.Gan/RUNDIRS/naf19296/2020090200/gdas/eupd.305717/mp_untar.sh
  srun: Warning: can't run 1 processes on 40 nodes, setting nnodes to 1
- gdaspost001.log (3961,10545)
  25.797 + srun -l '--export=ALL' -n 24 --multi-prog /scratch1/NCEPDEV/stmp2/Lin.Gan/RUNDIRS/naf19296/2020090200/gdas/post.212378/poescript_srun
  srun: Warning: can't honor --ntasks-per-node set to 12 which doesn't match the requested tasks 24 with the number of requested nodes 10. Ignoring --ntasks-per-node.
- gfsanal.log (6668)
  0 + srun -l --export=ALL -n 6 /scratch1/NCEPDEV/global/Lin.Gan/git/gw-launcher-flag/exec/global_cycle '1>OUTPUT.94444' '2>errfile'
  srun: Warning: can't run 6 processes on 11 nodes, setting nnodes to 6
- gfsanalcalc.log (1735)
  0.067 + srun -l '--export=ALL' -n 1 /scratch1/NCEPDEV/global/Lin.Gan/git/gw-launcher-flag/exec/gaussian_sfcanl.exe
  srun: Warning: can't run 1 processes on 4 nodes, setting nnodes to 1
- gfspost001.log (3970,10554,18492,25264,33210,39982,47928,54700)
  4.319 + srun -l '--export=ALL' -n 24 --multi-prog /scratch1/NCEPDEV/stmp2/Lin.Gan/RUNDIRS/naf19296/2020090200/gfs/post.40235/poescript_srun
  srun: Warning: can't honor --ntasks-per-node set to 12 which doesn't match the requested tasks 24 with the number of requested nodes 10. Ignoring --ntasks-per-node.

**Comment by WalterKolczynski-NOAA** [comment]
> Some jobs are running on Hera using old job cards. It does not match the requested tasks with the number of requested nodes. This caused the Slurm task scheduler to issue a Warning message and ignored the setting. During a test using global-workflow develop on Hera I found the following jobs contain these bugs: Job log directory: /scratch1/NCEPDEV/stmp2/Lin.Gan/ptmp/com/naf19296/logs/2020090200
> 
> * gdasanaldiag.log (3936)
>     7.794 + srun -l '--export=ALL' -n 90 --multi-prog /scratch1/NCEPDEV/stmp2/Lin.Gan/RUNDIRS/naf19296/2020090200/gdas/anal.311060/mp_diag.sh
>     srun: Warning: can't honor --ntasks-per-node set to 40 which doesn't match the requested tasks 90 with the number of requested nodes 3. Ignoring --ntasks-per-node.
> * gdasanalcalc.log (2181)
>     0.075 + srun -l '--export=ALL' -n 1 /scratch1/NCEPDEV/global/Lin.Gan/git/gw-launcher-flag/exec/gaussian_sfcanl.exe
>     srun: Warning: can't run 1 processes on 4 nodes, setting nnodes to 1
> * gdasanal.log (7130, 8711)
>     0 + srun -l --export=ALL -n 6 /scratch1/NCEPDEV/global/Lin.Gan/git/gw-launcher-flag/exec/global_cycle '1>OUTPUT.111018' '2>errfile'
>     srun: Warning: can't run 6 processes on 11 nodes, setting nnodes to 6
> * gdaseupd.log (2927)
>     2.589 + srun -l '--export=ALL' -n 1 --multi-prog /scratch1/NCEPDEV/stmp2/Lin.Gan/RUNDIRS/naf19296/2020090200/gdas/eupd.305717/mp_untar.sh
>     srun: Warning: can't run 1 processes on 40 nodes, setting nnodes to 1
> * gdaspost001.log (3961,10545)
>     25.797 + srun -l '--export=ALL' -n 24 --multi-prog /scratch1/NCEPDEV/stmp2/Lin.Gan/RUNDIRS/naf19296/2020090200/gdas/post.212378/poescript_srun
>     srun: Warning: can't honor --ntasks-per-node set to 12 which doesn't match the requested tasks 24 with the number of requested nodes 10. Ignoring --ntasks-per-node.
> * gfsanal.log (6668)
>     0 + srun -l --export=ALL -n 6 /scratch1/NCEPDEV/global/Lin.Gan/git/gw-launcher-flag/exec/global_cycle '1>OUTPUT.94444' '2>errfile'
>     srun: Warning: can't run 6 processes on 11 nodes, setting nnodes to 6
> * gfsanalcalc.log (1735)
>     0.067 + srun -l '--export=ALL' -n 1 /scratch1/NCEPDEV/global/Lin.Gan/git/gw-launcher-flag/exec/gaussian_sfcanl.exe
>     srun: Warning: can't run 1 processes on 4 nodes, setting nnodes to 1
> * gfspost001.log (3970,10554,18492,25264,33210,39982,47928,54700)
>     4.319 + srun -l '--export=ALL' -n 24 --multi-prog /scratch1/NCEPDEV/stmp2/Lin.Gan/RUNDIRS/naf19296/2020090200/gfs/post.40235/poescript_srun
>     srun: Warning: can't honor --ntasks-per-node set to 12 which doesn't match the requested tasks 24 with the number of requested nodes 10. Ignoring --ntasks-per-node.

This is an unrelated issue, as they are all homogenous jobs.

**Comment by lgannoaa** [comment]
@WalterKolczynski-NOAA 
The issue found in Hera job card is related to issue found in this ticket and my tests.

**Comment by WalterKolczynski-NOAA** [comment]
It is not. This issue is specifically about heterogenous jobs. Any issues you encounter running a homogenous job would be a new issue, even if you find it while trying to fix this issue.

Incidentally, in my experience the errors you encountered don't really break anything, in contrast to this issue. The jobs still run fine.

**Comment by lgannoaa** [comment]
A heterogeneous job consists of several job components, all of which can have individual job options. In particular, the different components can request nodes from different partitions. That way, a heterogeneous job can for example be spawned across multiple modules of our supercomputers.
Homogenous is related to job's resource allocation.

The wrong job cards reported by slurm from what I noted above should not be considered as find or not break anything.

There is a fact that Hera job card need to be fixed on job assignment logic in global workflow.

@WalterKolczynski-NOAA , what action do you want to fix the wrong Hera job card issue I reported here?

**Comment by WalterKolczynski-NOAA** [comment]
Heterogeneous and homogenous are opposites, here referring to the CPU layout. There are not different things.

To fix *this* issue, the workflow needs to stop creating workflows that generate heterogenous node layouts.

To fix the issue you found (which, again, is a different issue, even though it is related), you need to reconcile the number of tasks with ntasks-per-node. Because the tasks have to be homogenous, that likely means them being divisible.

Either that, or update rocoto and adding the capability to make heterogenous CPU requests on slurm, which would moot this issue and make the second easier.

**Comment by lgannoaa** [comment]
Do you want me to create a different issue to fix the bug that reported?

**Comment by WalterKolczynski-NOAA** [comment]
Yes please

**Comment by lgannoaa** [comment]
Sure. I will remove all my comment from here. I will not taking this ticket for now.

**Comment by WalterKolczynski-NOAA** [comment]
I think this one is moot. We don't use heterogeneous jobs anymore.
