### ISSUE TITLE
GFSv16.1.3 - Emergency change in operations to turn off IASI from metop-a early

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#446]
An emergency change was made to the GFS in operations today to turn off the IASI from metop-a earlier than planned. This became GFSv16.1.3 in production. GSI issue https://github.com/NOAA-EMC/GSI/issues/216

From SDM log:

```
1ap. 1900Z - IDSB Chief Carissa requested an ARFC for the SPA
Team. The metopA "IASI" instrument is failing, so they need to
make a modification to dump jobs so models do not assimilate the
degraded data. They would like to make the change at 12Z
tomorrow. NCO Deputy Director and SDM approved. (MBG)
```

From @dtkleist email on September 22nd:

```
Phase one of our emergency fixes are going in this morning. We had to turn off IASI from metop-a earlier than we were
hoping as they have been doing some tests of the instrument as they begin plans for decommissioning the satellite in
the coming months. 
```

Changes to turn off IASI in the GSI global_satinfo.txt file occurred in operations during the 2021092206 gdas cycle. The updated fix file was also copied to the incoming install for what will be v16.1.4 (was v16.1.3 before this change).

The prior `release/gfsv16.1.3` branch was copied and made into a new `release/gfsv16.1.4` branch for the planned implementation next week (issue #420). Will create a new `release/gfsv16.1.3` branch off operations to update the GSI tag that @CatherineThomas-NOAA will create for the emergency change. Will also create a new EMC-v16.1.3 tag for documentation.

**Comment by CatherineThomas-NOAA** [comment]
The companion GSI issue on this fix is [#216](https://github.com/NOAA-EMC/GSI/issues/216).

**Comment by KateFriedman-NOAA** [comment]
Test of new `release/gfs.v16.1.3` package on WCOSS-Dell reproduces last night's 00z cycle. Will submit PR into `operations` branch shortly.

**Comment by KateFriedman-NOAA** [comment]
From September 24th RFC memo:

```
RFC 8691 - On WCOSS, turned off IASI (Infrared Atmospheric Sounding
Interferometer) on Metop-A in multiple models' ‘satinfo.txt’ files. This was done
because IASI on Metop-A has been significantly degraded since September 17. Since
the instrument is being decommissioned next month, NCO permanently removed this
instrument from assimilation. Implemented on September 22 at 1140Z.
```

**Comment by KateFriedman-NOAA** [comment]
New tag and release published: https://github.com/NOAA-EMC/global-workflow/releases/tag/NCO-v16.1.3
