### ISSUE TITLE
Add flag to launcher command to prepend task number to lines of stdout/err

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#454]
Based on outcomes from failures with the GFSv16 in operations (due to machine issues) folks have requested that we add the `-l` flag with the mpiexec launcher command on WCOSS2. This flag should also work with mpirun on WCOSS1 and with srun (as `-l` or `--label`) on the SLURM R&D machines.

Per SLURM documentation:
```
-l, --label
Prepend task number to lines of stdout/err. The --label option will prepend lines of output with the remote task id.
This option applies to step allocations.
```

Add flag to $launcher commands in each env file and test everywhere (with and without flag) to check for any runtime issues or timing impacts.

**Comment by lgannoaa** [comment]
Do you have an example that show how preferred solution/outcome? I can take a look.

**Comment by KateFriedman-NOAA** [comment]
See the change made to the operations branch for GFSv16.1.5:

```
export launcher="mpirun -l -n"
```

https://github.com/NOAA-EMC/global-workflow/blob/operations/env/WCOSS_DELL_P3.env#L17

**Comment by lgannoaa** [comment]
May I do the following to help on this task?
- Checkout global-workflow develop on Hera.
- Modify launcher with similar solution.
- Testing on cycled low resolution C192C96L127 on Dell and Hera for 2 and half cycle.
- PR solution back to global-workflow develop.
Thanks

**Comment by KateFriedman-NOAA** [comment]
Yes, please do that test on Hera. Please also run at least a few jobs on Orion with the same settings to confirm it also works there as intended. Thanks!

**Comment by lgannoaa** [comment]
Are you saying that I do not need to test it on dell wcoss? Just want to be sure.

**Comment by KateFriedman-NOAA** [comment]
A quick test on WCOSS would also be preferred. It was tested on the Dells for the operations branch but not in the develop branch so please also run a quick test on WCOSS. Thanks!

**Comment by lgannoaa** [comment]
PR submitted and approved:
https://github.com/NOAA-EMC/global-workflow/pull/493
