### ISSUE TITLE
ocnpost jobs time out on Orion

### ISSUE THREAD

**Issue by benwgreen** [NOAA-EMC/global-workflow#461]
When running feature/coupled-crow on Orion, the gfs.post.ocnpost tasks all time out (the time limit is set to 30 minutes). This started happening on Wednesday 6 October 2021, consistent with a change in Orion -- see the email below. Just by increasing the time limit, jobs finish anywhere from 45 to 75 minutes now; I have the time limit set to 90 minutes to be safe.

-------------------
_On Wednesday, October 6, beginning at 1:00pm CDT, changes to orion's slurm configuration will be made.
These changes will be completed live and a short window of service interruption for job submissions may occur while the scheduler is restarted._

_These changes should help with job throughput._

_Users should note a change to the default memory allocation.
The default memory allocation per core will be changed from using all available memory to being based on cores requested per node.
Standard compute nodes w/ 192GB will default to 4608 Mb per core
Big mem nodes w/ 384GB will default to 9472 Mb per core
Users can change these defaults by using the --mem or --exclusive options._

_Running jobs should not be affected, and queued jobs may have their priority/fairshare adjusted after the
reconfiguration._

**Comment by WalterKolczynski-NOAA** [comment]
This should have the same solution as #463.

**Comment by benwgreen** [comment]
> This should have the same solution as #463.

Agree. You'll probably have to look at all of the tasks just to make sure -- my guess is more than the two already identified will need to be tweaked.
