### ISSUE TITLE
Metplus and fit2obs verification job improvement in global workflow

### ISSUE THREAD

**Issue by lgannoaa** [NOAA-EMC/global-workflow#465]
Metplus and fit2obs verification runs on a 24 hour delay. The global workflow will only verify results to EDATE - $backup. For example, If EDATE is set to 2021101500. The 2021101406 through 2021101500 will be missing.
Current workaround is manually submitted metplus and fit2obs jobs for this period after the parallel is done.
A mechanism should be added to the workflow or a procedure outside the workflow developed to verify all output generated in a developer parallel.

**Comment by malloryprow** [comment]
For the METplus runs, if the job runs on 2021101500 the verification will run for all of 20211014. What will be missing is the verification for 20211015.

The stats can still be generated outside the workflow by running EMC_verif-global stand alone.

**Comment by lgannoaa** [comment]
Thank you for your feedback @malloryprow 
Is that a way you preferred to generate the last verification for 20211015? It can be a solution within the global workflow or an external process.

**Comment by malloryprow** [comment]
@lgannoaa I would say preferred solution for now would be an external process. We can look into addressing it though in the global workflow in the future.

**Comment by lgannoaa** [comment]
@RussTreadon-NOAA, we do not have a group consent to address this issue within the global workflow at this time. Looks like it will remain in the EXPDIR/scripts location on a running parallel for now.
I will close this issue by noon tomorrow.

**Comment by lgannoaa** [comment]
Close issue
