### ISSUE TITLE
New EMC_verif-global tag: verif_global_v2.8.0

### ISSUE THREAD

**Issue by malloryprow** [NOAA-EMC/global-workflow#472]
Update to new EMC_verif-global tag: verif_global_v2.6.10

Changes:

- Update TC verification to more closely follow NHC's practices

- Hotfix to add JET to tc_stat launcher in scripts/extropcyc.sh

- Fix num. processors in cfp commands

- Fix webpage template pop up information window

-  Fix tc_stat valid_beg and valid_end date and times

-  Fix global workflow forecast hour adjustment

- Run Cartopy scripts on S4

- Remove memory requirement for Slurm machines

- Fix maps2d cloud variable information

- Remove contour label color setting that caused problems in newer matplotlib versions

- Fix date tick label format for newer matplotlib versions

**Comment by KateFriedman-NOAA** [comment]
Updated to verif_global_v2.8.0. New summary of changes:

- Update TC verification to more closely follow NHC's practices
- Hotfix to add JET to tc_stat launcher in scripts/extropcyc.sh
- Fix num. processors in cfp commands
- Fix webpage template pop up information window
- Fix tc_stat valid_beg and valid_end date and times
- Fix global workflow forecast hour adjustment
- Run Cartopy scripts on S4
- Remove memory requirement for Slurm machines
- Fix maps2d cloud variable information
- Remove contour label color setting that caused problems in newer matplotlib versions
- Fix date tick label format for newer matplotlib versions
- Added more options for choosing gridded "truth" for grid-to-grid step 1
- Fix bug in grabbing machine hostname from running 'hostname'
