### ISSUE TITLE
Update checkout path for UFS_UTILS component post-move

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#476]
The UFS_UTILS repository has moved from under the [NOAA-EMC organization](https://github.com/NOAA-EMC) to under the [ufs-community organization](https://github.com/ufs-community). New home: https://github.com/ufs-community/UFS_UTILS

Will update the clone path in the checkout script to reflect the new home for the UFS_UTILS repository.

Thankfully GitHub automatically handles the location change when you attempt to clone from the prior NOAA-EMC org location so this move did not break anything for users cloning the full global-workflow package. This is a non-emergency change because of that.

- [ ] update path in develop branch
- [x] update path in operations branch

**Comment by WalterKolczynski-NOAA** [comment]
Operations was handled in PR #545
