### ISSUE TITLE
new config files for tasks in parallel GDAS workflow

### ISSUE THREAD

**Issue by AndrewEichmann-NOAA** [NOAA-EMC/global-workflow#478]
Tag as request for advice about new config files.

The EFSOI as implemented (primarily within GSI, with some changes to global-workflow) uses a separate workflow of tasks that largely mirror the ensemble portions of the GDAS cycling. They all have their own rocoto scripts and job scripts, the latter in the GSI repository. Where possible (all except the eupd and the end efsoi task) they call the standard scripts in scripts directory.  The differences in the job scripts usually reflect that they are pointing at a separate data subdirectory tree similar to that of the enkfgdas.YYYYMMDD directories, and are handling 30 hr ensemble forecasts.

Currently, each EFSOI specific task has its own dedicated config file that it references in place of the standard one for that task, even when it is largely the same to its regular GDAS equivalent. This adds to the proliferation of config files in the EXPDIR which will be of no interest to most users. Two alternate approaches have been discussed:

- Having all of the EFSOI job scripts invoke a single EFSOI-specific config file instead of the standard task config file, containing any EFSOI-specific settings for all of the tasks, with any necessary if-then cutouts for tasks
- Having all of the EFSOI job scripts invoke a single EFSOI-specific config file *after* it invokes the standard config file for that task, reassigning any variables as necessary, but avoiding code duplication

I would be interested in any comments or observations regarding these three approaches. 

Thank you!

**Comment by lgannoaa** [comment]
Looks like EFSOI specific task run as part of GSI repository. The $HOMEgfs/parm/config location contain three major configuration files. The general config.base, resource assignment config.resource, and job specific config.${job_name}.
May I see an sample workflow that you are running for this new setup? I want to evaluate which configuration should be in workflow level ($HOMEgfs/parm/config) or stay within GSI repository.

**Comment by AndrewEichmann-NOAA** [comment]
@lgannoaa 
The extra workflow tasks are as follows:
gdaseupdfsoi
gdasecenfsoi
gdasesfcfsoi
gdasefcsfsoi
gdaseposfsoi
gdasefsoi
Most are variations (sometimes minor variations) of their regular GSI counterparts, and all except gdaseupdfsoi and gdaseposfsoi use the same exgdas scripts.
I'm not sure what you mean by config files under GSI - as far as I know, all the config files for the GSI tasks are under $HOMEgfs/parm/config .

**Comment by AndrewEichmann-NOAA** [comment]
The current PR for this is in https://github.com/NOAA-EMC/global-workflow/pull/674

**Comment by lgannoaa** [comment]
Thank you for your information.

**Comment by AndrewEichmann-NOAA** [comment]
Folding into issue https://github.com/NOAA-EMC/global-workflow/issues/673 and closing
