### ISSUE TITLE
Module order and dependency check

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#479]
Review modules being loaded on each platform (e.g. via module_base.*) to check they are loading in the proper order and dependencies are being met correctly. Check for module swaps and resolve as needed to maintain the correct module loads.

Module loads should also follow this general order/grouping:

1. compilers
2. mpi
3. standard 3rd party e..g jasper, etc.
4. hdf5
5. netcdf
6. nceplibs

**Comment by lgannoaa** [comment]
Would you be more clear about this issue? What is the solution that you are looking for?

**Comment by WalterKolczynski-NOAA** [comment]
Some modules are currently unloading versions that have already been loaded and loading some new, different version, so that the versions specified in the module file are not the ones that are actually loaded by the end of it. We need to find all those and reorder the modules and/or update versions so that doesn't happen.

**Comment by KateFriedman-NOAA** [comment]
@lgannoaa I also added text to the first comment to show the order that modules should be loaded in the module_base files. Within the groups in that order the modules should load in order of their dependencies. Examples:

nemsio needs: bacio & w3nco modules loaded first
w3emc needs: sigio & nemsio modules loaded first
nemsiogfs needs: nemsio module loaded first
nco needs: intel or netcdf or udunits modules loaded first

Additionally, see the following new module_base.wcoss2 that I built for the WCOSS2 port. It has the modules in the right order as an example:
https://github.com/KateFriedman-NOAA/global-workflow/blob/feature/ops-wcoss2/modulefiles/module_base.wcoss2

**Comment by lgannoaa** [comment]
@WalterKolczynski-NOAA , @KateFriedman-NOAA 
I will review the Global-Workflow module_base files and modify them to be in-line with the order.
I will test in a C192C96L127 parallel for one full cycle on Dell wcoss and Orion.
Are we in agreement with this solution?

**Comment by WalterKolczynski-NOAA** [comment]
That won't work, because we hide the module output in g-w. Plus, you probably don't need to run the workflow at all. Just purge your modules, `module use` the module directory, then load a module file and watch the output. Then repeat.

**Comment by lgannoaa** [comment]
@WalterKolczynski-NOAA you purposed a different approach compare to @KateFriedman-NOAA .
I will wait for a consent on solution to take this ticket.

**Comment by WalterKolczynski-NOAA** [comment]
I don't see how my approach conflicts with what Kate has said

**Comment by KateFriedman-NOAA** [comment]
@lgannoaa Please do both in your testing:

1) On the command line: purge your modules, module use the module directory, then load a module file and watch the output. Then repeat. Module output goes to /dev/null at runtime so we don't see module swaps. Doing this should show module swaps and errors. You'll need to do this on each machine.
2) When happy with module_base updates please run at least one job (gdasfcst) on each supported platform to make sure updates work.

Thanks!

**Comment by WalterKolczynski-NOAA** [comment]
Not only module_base needs to be checked. The build modules (at least the ones under our control) should be tested as well, making sure build still works at the end.

**Comment by KateFriedman-NOAA** [comment]
Yes thanks for the reminder @WalterKolczynski-NOAA . @lgannoaa here are adjusted steps to take:

1. Update/check module_base files. On the command line: purge your modules, module use the module directory, then load a module file and watch the output. Then repeat. Module output goes to /dev/null at runtime so we don't see module swaps. Doing this should show module swaps and errors. You'll need to do this on each machine.
2. Also check modulefiles under /modulefiles that are used at buildtime (owned by g-w) and also update their order accordingly.
3. When happy with module_base/modulefile updates please a) test build_all.sh and b) run at least one job (gdasfcst) on each supported platform to make sure updates work.

**Comment by lgannoaa** [comment]
> Yes thanks for the reminder @WalterKolczynski-NOAA . @lgannoaa here are adjusted steps to take:
> 
> 1. Update/check module_base files. On the command line: purge your modules, module use the module directory, then load a module file and watch the output. Then repeat. Module output goes to /dev/null at runtime so we don't see module swaps. Doing this should show module swaps and errors. You'll need to do this on each machine.
> 2. Also check modulefiles under /modulefiles that are used at buildtime (owned by g-w) and also update their order accordingly.
> 3. When happy with module_base/modulefile updates please a) test build_all.sh and b) run at least one job (gdasfcst) on each supported platform to make sure updates work.

Agreed. Taking the ticket.
