### ISSUE TITLE
Hera job card issue with resource assignment

### ISSUE THREAD

**Issue by lgannoaa** [NOAA-EMC/global-workflow#495]
Some jobs are running on Hera using old job cards. It does not match the requested tasks with the number of requested nodes. This caused the Slurm task scheduler to issue a Warning message and ignored the setting.
During a test using global-workflow develop on Hera I found the following jobs contain these bugs:
Job log directory:
/scratch1/NCEPDEV/stmp2/Lin.Gan/ptmp/com/naf19296/logs/2020090200

gdasanaldiag.log (3936)
  7.794 + srun -l '--export=ALL' -n 90 --multi-prog /scratch1/NCEPDEV/stmp2/Lin.Gan/RUNDIRS/naf19296/2020090200/gdas/anal.311060/mp_diag.sh
  srun: Warning: can't honor --ntasks-per-node set to 40 which doesn't match the requested tasks 90 with the number of requested nodes 3. Ignoring --ntasks-per-node.
gdasanalcalc.log (2181)
  0.075 + srun -l '--export=ALL' -n 1 /scratch1/NCEPDEV/global/Lin.Gan/git/gw-launcher-flag/exec/gaussian_sfcanl.exe
  srun: Warning: can't run 1 processes on 4 nodes, setting nnodes to 1
gdasanal.log (7130, 8711)
  0 + srun -l --export=ALL -n 6 /scratch1/NCEPDEV/global/Lin.Gan/git/gw-launcher-flag/exec/global_cycle '1>OUTPUT.111018' '2>errfile'
  srun: Warning: can't run 6 processes on 11 nodes, setting nnodes to 6
gdaseupd.log (2927)
  2.589 + srun -l '--export=ALL' -n 1 --multi-prog /scratch1/NCEPDEV/stmp2/Lin.Gan/RUNDIRS/naf19296/2020090200/gdas/eupd.305717/mp_untar.sh
  srun: Warning: can't run 1 processes on 40 nodes, setting nnodes to 1
gdaspost001.log (3961,10545)
  25.797 + srun -l '--export=ALL' -n 24 --multi-prog /scratch1/NCEPDEV/stmp2/Lin.Gan/RUNDIRS/naf19296/2020090200/gdas/post.212378/poescript_srun
  srun: Warning: can't honor --ntasks-per-node set to 12 which doesn't match the requested tasks 24 with the number of requested nodes 10. Ignoring --ntasks-per-node.
gfsanal.log (6668)
  0 + srun -l --export=ALL -n 6 /scratch1/NCEPDEV/global/Lin.Gan/git/gw-launcher-flag/exec/global_cycle '1>OUTPUT.94444' '2>errfile'
  srun: Warning: can't run 6 processes on 11 nodes, setting nnodes to 6
gfsanalcalc.log (1735)
  0.067 + srun -l '--export=ALL' -n 1 /scratch1/NCEPDEV/global/Lin.Gan/git/gw-launcher-flag/exec/gaussian_sfcanl.exe
  srun: Warning: can't run 1 processes on 4 nodes, setting nnodes to 1
gfspost001.log (3970,10554,18492,25264,33210,39982,47928,54700)
  4.319 + srun -l '--export=ALL' -n 24 --multi-prog /scratch1/NCEPDEV/stmp2/Lin.Gan/RUNDIRS/naf19296/2020090200/gfs/post.40235/poescript_srun
  srun: Warning: can't honor --ntasks-per-node set to 12 which doesn't match the requested tasks 24 with the number of requested nodes 10. Ignoring --ntasks-per-node.

**Comment by WalterKolczynski-NOAA** [comment]
This is also an issue on Orion, and probably all slurm machines

**Comment by KateFriedman-NOAA** [comment]
> This is also an issue on Orion, and probably all slurm machines

I concur, I see this on Orion as well.

**Comment by lgannoaa** [comment]
Believe I got a solution to fix it.
A test in Hera GFS post 018 indicated this solution fixed the issue and reduced resource a single GFS post job from 10 nodes to 2 nodes. Gain around 17% faster in run time. That is a total of 344 nodes saving for all GFS post job (000-042) each cycle.

**Comment by lgannoaa** [comment]
Close this issue because post resource assignment has been changed. This issue is obsolete.
