### ISSUE TITLE
POST job resource assignment issue on production GFS/GDAS post jobs

### ISSUE THREAD

**Issue by lgannoaa** [NOAA-EMC/global-workflow#498]
It is discovered that the post jobs (including both gdas and gfs) are having wrong resource assignment. This fact exists on all platforms including NCO production.

For example, NCO production today 20211112 00Z gdas post log /gpfs/dell1/nco/ops/com/output/prod/today/gdas_atmos_post_f002_00.o73146807 
This job reserved:  
  98 tasks
  14 tasks/node
  7 nodes totalThe log file shown:  
---
export WRITE_DOPOST=.true. (used inline POST in line 1113)
nproc=28 (line 3321 and 11545)
  This statement is wired in 28 tasks for each post job. Such as gdas_atmos_post_f002_00 (post f002 on 00Z).
launcher='mpirun -l -n 28 cfp' (line 5015 and 12840)
mpirun -l -n 28 cfp /gpfs/dell1/nco/ops/tmpnwprd/jgdas_atmos_post_f002_00.73146807/poescript (5017, and 12842)---
The log indicated this post job is only used 28 tasks on 14 tasks/node resource reservation.
It is calculated as 2 nodes.

There are 219 post jobs for each cycle in production. 
 Each job claim resource as:
  98 tasks
  14 tasks/node
  7 nodes total
There are 5 unnecessary reserved nodes each post job or a total of 1095 unnecessary reserved nodes can be reclaimed for each cycle.

**Comment by aerorahul** [comment]
@lgannoaa 
Thanks for reporting the bug.
Question:
Should "in-line" post processing to create the master grib file be the only behavior supported by the workflow?
While the UFS currently does "in-line" post processing to generate the master grib file, should an option be preserved to do "off-line" post for researchers?

**Comment by lgannoaa** [comment]
Is the forecast team going to maintain support on both configuration?
Is the post team going to keep support backward compatibility on demand?

The global workflow handle a switch on configuration. The actual functionality is in forecast/post code level.

For someone to use global workflow, there is high probability they need to see PGB output. It is expensive to run global workflow to only see forecast output. Hence the forecast only/cycled mode all support post jobs.

**Comment by aerorahul** [comment]
That is a good question on supportability.
Before we eliminate it, we should atleast ask the relevant people.

**Comment by arunchawla-NOAA** [comment]
There has been no traffic on this for a while. Do we know where we stand with this ? @lgannoaa @aerorahul @KateFriedman-NOAA and @WalterKolczynski-NOAA

**Comment by lgannoaa** [comment]
@arunchawla-NOAA NCO modified the post resource assignment. I think we can close this ticket.
