### ISSUE TITLE
Update rocoto_viewer.py for python >= 3.8

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#522]
Test the updated python3 rocoto_viewer.py on WCOSS2 and resolve issues.

Initial test of the new copy coming in PR #500 shows it works to show the information but column alignment needs fixing and it segfaults as soon as I try to use it or navigate through the job list:

![image](https://user-images.githubusercontent.com/37624921/145252435-ceb59435-bf59-4a03-8232-2155f9dc1e3e.png)

Note: this is from within a Tectia terminal with TERM=xterm.

**Comment by KateFriedman-NOAA** [comment]
The viewer works on WCOSS2 if you unload `python/3.8.6` and use the stock system python (v2.7.18). There are some visual quirks if you leave it open for a while (not just on WCOSS2) but running rocotorun (`R`) via the viewer clears that. It doesn't core dump or mess up the terminal on WCOSS2 after unloading `python/3.8.6` and running the viewer, so I will close this issue.

**Comment by WalterKolczynski-NOAA** [comment]
> The viewer works on WCOSS2 if you unload `python/3.8.6` and use the stock system python (v2.7.18). There are some visual quirks if you leave it open for a while (not just on WCOSS2) but running rocotorun (`R`) via the viewer clears that. It doesn't core dump or mess up the terminal on WCOSS2 after unloading `python/3.8.6` and running the viewer, so I will close this issue.

When you unload the python module, rocoto_viewer uses the stock python3 installation (3.6.15), not python.

The issue with the module seems to be something incorrect with the curses installation (thought I had added that information here before).

**Comment by WalterKolczynski-NOAA** [comment]
Reopening this, because it seems it is not a WCOSS2-only issue. Orion added python 3.9.2. I tried that, and rocoto viewer exits immediately without displaying an error. After a couple quick debug prints, it fails on the following line:
`curses.wrapper(main)` without actually entering the rocoto viewer `main()` function. Since python 3.7.5 works but 3.8.6 does not, it seems there is some change to the `curses.wrapper()` function between python 3.7 and 3.8 (the version that fails on WCOSS2).

**Comment by TerrenceMcGuinness-NOAA** [comment]
I'll start on this now.

**Comment by HenryRWinterbottom** [comment]
@TerrenceMcGuinness-NOAA If you don't have any success or would be interested, we might be able to make use of the tools here https://github.com/HenryWinterbottom-NOAA/ufs_engines.
