### ISSUE TITLE
Omnibus issue to track 'parm' additions needed for UFSDA JEDI-based prototype cycling

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/global-workflow#532]
- [ ] `config.jedianal`
- [ ] `config.resources` updates
- [ ] `config.base` updates
- [ ] YAML templates (link to UFS-DA submodule or store here?)

**Comment by WalterKolczynski-NOAA** [comment]
Is this issue still active, or did it get subsumed by others?

**Comment by CoryMartin-NOAA** [comment]
Let's say subsumed/delayed. I'll close for now

**Comment by WalterKolczynski-NOAA** [comment]
It's fine to remain open if it is still something that needs to be done. I'm just trying to close out things that were already solved or absorbed by other issues without being closed.

**Comment by CoryMartin-NOAA** [comment]
It wont likely be anything in coming weeks/months, so we can reopen/open a new/more relevant issue when the time comes.
