### ISSUE TITLE
WCOSS2 transition issue - Update compath.py assignment in jobs

### ISSUE THREAD

**Issue by lgannoaa** [NOAA-EMC/global-workflow#533]
Need to double check on WCOSS2 transition jobs to ensure:
  $(compath.py ${NET}/${envir}/${RUN}.${PDY})/${cyc}/$COMPONENT - is no longer used. 

It should be replaced as: 
$(compath.py -o ${NET}/${gfs_ver}/${RUN}.${PDY})/${cyc}/$COMPONENT

**Comment by KateFriedman-NOAA** [comment]
Refs: #399

**Comment by KateFriedman-NOAA** [comment]
@lgannoaa I've submitted PR #543 with your compath.py updates and additional related updates. Thanks!

**Comment by KateFriedman-NOAA** [comment]
PR #543 resolved.
