### ISSUE TITLE
WCOSS2 transition issue - Hardwired DELL path util/ush/make_tif.sh

### ISSUE THREAD

**Issue by lgannoaa** [NOAA-EMC/global-workflow#534]
Line 14-16 contain hardwired dell PATH.

  export PATH=$PATH:/usrx/local/dev/packages/ImageMagick/6.9.9-25/bin:.
  export LIBPATH="$LIBPATH":/usrx/local/dev/packages/ImageMagick/6.9.9-25/lib
  export DELEGATE_PATH=/usrx/local/dev/packages/ImageMagick/6.9.9-25/share/ImageMagick-6

Need to be fixed to create tif product images.

**Comment by KateFriedman-NOAA** [comment]
@lgannoaa Do you have a solution for this?

**Comment by aerorahul** [comment]
These are products.  We have no idea who developed or maintains these utilities under `util/`
@arunchawla-NOAA These need a home not under the workflow.

**Comment by arunchawla-NOAA** [comment]
I will investigate the origin of this

**Comment by KateFriedman-NOAA** [comment]
Resolved. Closing now.
