### ISSUE TITLE
build of ufs_utils and gldas on hera failing from develop branch

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#561]
When building on hera, both ufs_utils and gldas is failing using the develop branch.  

The error for ufs_utils is: 
```
Lmod has detected the following error: The following module(s) are unknown: "esmf/8_1_0_beta_snapshot_27"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "esmf/8_1_0_beta_snapshot_27"

Also make sure that all modulefiles written in TCL start with the string #%Module

Executing this command requires loading "esmf/8_1_0_beta_snapshot_27" which failed while processing the following module(s):

    Module fullname   Module Filename
    ---------------   ---------------
    build.hera.intel  /scratch2/NCEPDEV/climate/Jessica.Meixner/p8a_uncoupled/global-workflow/sorc/ufs_utils.fd/modulefiles/build.hera.intel
```

which based on some comments on slack, I believe that esmf/8_1_0_beta_snapshot_27 has been removed for space reasons on hera.  The gldas log was not as informative, but I suspect it might be a similar/same issue?

**Comment by WalterKolczynski-NOAA** [comment]
These should be updated to use not a beta anyway, but I wish hpc-stack would inform us when they make changes to existing packages.

**Comment by edwardhartnett** [comment]
@kgerheiser @Hang-Lei-NOAA did we remove a beta version of ESMF?

**Comment by Hang-Lei-NOAA** [comment]
Hi, Ed

Yes, no space on hera library installations.
So, snapshot version are removed.
It was announced a month ago.
https://github.com/ufs-community/ufs-weather-model/wiki/News
Hang

**Comment by junwang-noaa** [comment]
I think we need to move to a later version of ESMF. The current ESMF
release is 8.2.0, while ESMF 810bs27 was coming out in April 2020, which
was more than 1.5 years ago. There are many beta snapshots coming out since
then, so it would be hard to keep so many versions of ESMF libraries.

**Comment by HenryRWinterbottom** [comment]
@WalterKolczynski-NOAA I ran into this issue a couple of weeks back while running a UFS cycle. The previous cycles had run without issue (using `8_1_0_beta_snapshot_27`) but suddenly failed when they removed/updated the stack.

Changing to `esmf/8_1_1` resolved the issue for me. This is admittedly a hack/workaround since I don't know when RDHPCS will change the stack again.

Hopefully this helps.

**Comment by WalterKolczynski-NOAA** [comment]
> @WalterKolczynski-NOAA I ran into this issue a couple of weeks back while running a UFS cycle. The previous cycles had run without issue (using `8_1_0_beta_snapshot_27`) but suddenly failed when they removed/updated the stack.
> 
> Changing to `esmf/8_1_1` resolved the issue for me. This is admittedly a hack/workaround since I don't know when RDHPCS will change the stack again.
> 
> Hopefully this helps.

As far as I know, hpc-stack is controlled by EMC. We're already discussing better communication with that team (see https://github.com/NOAA-EMC/hpc-stack/discussions/374).  Manually editing the modulefile is definitely the workaround for now.

**Comment by Hang-Lei-NOAA** [comment]
@Henry Winterbottom - NOAA Affiliate ***@***.***> Glad to
see that esmf/8_1_1 resolved the issue. In the future, please remember to
move to release versions, once it is available on the machine. Snapshots
were considered as developing/middle/incomplete/unreleased versions in the
development sequence. Limited by machine space, we will remove snapshot
versions as a regular operation in months after the release version is
installed in future.

**Comment by WalterKolczynski-NOAA** [comment]
> Glad to see that esmf/8_1_1 resolved the issue. In the future, please remember to move to release versions, once it is available on the machine. Snapshots were considered as developing/middle/incomplete/unreleased versions in the development sequence. Limited by machine space, we will remove snapshot versions as a regular operation in months after the release version is installed in future.

This isn't his problem as a user. It's up to repo code managers to update.

**Comment by Hang-Lei-NOAA** [comment]
Yes, I understand this. Just let users know that using the release version
is the correct choice. And the EIB has decided to remove the snapshot
version as a regular operation in future. Will post announcements and
inform major code managers for the changes in advance.

**Comment by WalterKolczynski-NOAA** [comment]
I've opened issues with the relevant repositories after some testing. This issue will be more easily fixed once everyone brings the update using version variables to all machines (we could just update our own versions file).

**Comment by HelinWei-NOAA** [comment]
> When building on hera, both ufs_utils and gldas is failing using the develop branch.
> 
> The error for ufs_utils is:
> 
> ```
> Lmod has detected the following error: The following module(s) are unknown: "esmf/8_1_0_beta_snapshot_27"
> 
> Please check the spelling or version number. Also try "module spider ..."
> It is also possible your cache file is out-of-date; it may help to try:
>   $ module --ignore_cache load "esmf/8_1_0_beta_snapshot_27"
> 
> Also make sure that all modulefiles written in TCL start with the string #%Module
> 
> Executing this command requires loading "esmf/8_1_0_beta_snapshot_27" which failed while processing the following module(s):
> 
>     Module fullname   Module Filename
>     ---------------   ---------------
>     build.hera.intel  /scratch2/NCEPDEV/climate/Jessica.Meixner/p8a_uncoupled/global-workflow/sorc/ufs_utils.fd/modulefiles/build.hera.intel
> ```
> 
> which based on some comments on slack, I believe that esmf/8_1_0_beta_snapshot_27 has been removed for space reasons on hera. The gldas log was not as informative, but I suspect it might be a similar/same issue?

Both gldas and ufs_utils have used the same file machine-setup.sh. It seems that some commends are no longer supported by hera.

source machine-setup.sh
__ms_function_name=setup__test_function__83289: Command not found.
__ms_function_name: Undefined variable.

@GeorgeGayno-NOAA I think this file was introduced by you to gldas. Any idea how to fix this issue? Thanks.

**Comment by WalterKolczynski-NOAA** [comment]
> > When building on hera, both ufs_utils and gldas is failing using the develop branch.
> > The error for ufs_utils is:
> > ```
> > Lmod has detected the following error: The following module(s) are unknown: "esmf/8_1_0_beta_snapshot_27"
> > 
> > Please check the spelling or version number. Also try "module spider ..."
> > It is also possible your cache file is out-of-date; it may help to try:
> >   $ module --ignore_cache load "esmf/8_1_0_beta_snapshot_27"
> > 
> > Also make sure that all modulefiles written in TCL start with the string #%Module
> > 
> > Executing this command requires loading "esmf/8_1_0_beta_snapshot_27" which failed while processing the following module(s):
> > 
> >     Module fullname   Module Filename
> >     ---------------   ---------------
> >     build.hera.intel  /scratch2/NCEPDEV/climate/Jessica.Meixner/p8a_uncoupled/global-workflow/sorc/ufs_utils.fd/modulefiles/build.hera.intel
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > which based on some comments on slack, I believe that esmf/8_1_0_beta_snapshot_27 has been removed for space reasons on hera. The gldas log was not as informative, but I suspect it might be a similar/same issue?
> 
> Both gldas and ufs_utils have used the same file machine-setup.sh. It seems that some commends are no longer supported by hera.
> 
> source machine-setup.sh __ms_function_name=setup__test_function__83289: Command not found. __ms_function_name: Undefined variable.
> 
> @GeorgeGayno-NOAA I think this file was introduced by you to gldas. Any idea how to fix this issue? Thanks.

ufs_utils has already been fixed when they converted the remaining modulefiles to lua. I don't think it is related to machine-setup.

**Comment by HelinWei-NOAA** [comment]
> > > When building on hera, both ufs_utils and gldas is failing using the develop branch.
> > > The error for ufs_utils is:
> > > ```
> > > Lmod has detected the following error: The following module(s) are unknown: "esmf/8_1_0_beta_snapshot_27"
> > > 
> > > Please check the spelling or version number. Also try "module spider ..."
> > > It is also possible your cache file is out-of-date; it may help to try:
> > >   $ module --ignore_cache load "esmf/8_1_0_beta_snapshot_27"
> > > 
> > > Also make sure that all modulefiles written in TCL start with the string #%Module
> > > 
> > > Executing this command requires loading "esmf/8_1_0_beta_snapshot_27" which failed while processing the following module(s):
> > > 
> > >     Module fullname   Module Filename
> > >     ---------------   ---------------
> > >     build.hera.intel  /scratch2/NCEPDEV/climate/Jessica.Meixner/p8a_uncoupled/global-workflow/sorc/ufs_utils.fd/modulefiles/build.hera.intel
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > which based on some comments on slack, I believe that esmf/8_1_0_beta_snapshot_27 has been removed for space reasons on hera. The gldas log was not as informative, but I suspect it might be a similar/same issue?
> > 
> > 
> > Both gldas and ufs_utils have used the same file machine-setup.sh. It seems that some commends are no longer supported by hera.
> > source machine-setup.sh __ms_function_name=setup__test_function__83289: Command not found. __ms_function_name: Undefined variable.
> > @GeorgeGayno-NOAA I think this file was introduced by you to gldas. Any idea how to fix this issue? Thanks.
> 
> ufs_utils has already been fixed when they converted the remaining modulefiles to lua. I don't think it is related to machine-setup.

Agreed. Those commands can only be run with bash.

**Comment by GeorgeGayno-NOAA** [comment]
> > When building on hera, both ufs_utils and gldas is failing using the develop branch.
> > The error for ufs_utils is:
> > ```
> > Lmod has detected the following error: The following module(s) are unknown: "esmf/8_1_0_beta_snapshot_27"
> > 
> > Please check the spelling or version number. Also try "module spider ..."
> > It is also possible your cache file is out-of-date; it may help to try:
> >   $ module --ignore_cache load "esmf/8_1_0_beta_snapshot_27"
> > 
> > Also make sure that all modulefiles written in TCL start with the string #%Module
> > 
> > Executing this command requires loading "esmf/8_1_0_beta_snapshot_27" which failed while processing the following module(s):
> > 
> >     Module fullname   Module Filename
> >     ---------------   ---------------
> >     build.hera.intel  /scratch2/NCEPDEV/climate/Jessica.Meixner/p8a_uncoupled/global-workflow/sorc/ufs_utils.fd/modulefiles/build.hera.intel
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > which based on some comments on slack, I believe that esmf/8_1_0_beta_snapshot_27 has been removed for space reasons on hera. The gldas log was not as informative, but I suspect it might be a similar/same issue?
> 
> Both gldas and ufs_utils have used the same file machine-setup.sh. It seems that some commends are no longer supported by hera.
> 
> source machine-setup.sh __ms_function_name=setup__test_function__83289: Command not found. __ms_function_name: Undefined variable.
> 
> @GeorgeGayno-NOAA I think this file was introduced by you to gldas. Any idea how to fix this issue? Thanks.

@HelinWei-NOAA Use the latest version of 'develop', which fixes this problem.

**Comment by Hang-Lei-NOAA** [comment]
@HelinWei-NOAA <https://github.com/HelinWei-NOAA>  From nceplibs side, we
did not change any other things except removing some snapshots
installations of ESMF due to the disk space limitation. The switch to the
release version of esmf can solve it.
