### ISSUE TITLE
Bug fix for lfrac in diag_table

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#562]
From @HelinWei-NOAA change this line in diag_table from: 

"gfs_phys",    "lfrac",         "lfrac",         "fv3_history2d",  "all",  .false.,  "none",  2

to 

"gfs_sfc",    "lfrac",         "lfrac",         "fv3_history2d",  "all",  .false.,  "none",  2 

so that lfrac is in the history output.

**Comment by WalterKolczynski-NOAA** [comment]
This field isn't in the coupled aerosol diag table at all. Should it be added there?

**Comment by JessicaMeixner-NOAA** [comment]
Remind me what the coupled aerosol diag table is?  It's just the coupled + added aerosols output?  If so, then yes, and there's probably a couple of other fields missing too.
