### ISSUE TITLE
Check FRAC_GRID for uncoupled runs

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#571]
In the creation of input.nml frac_grid is behind a if cpl switch, but it should be available for uncoupled runs as well (see: https://github.com/NOAA-EMC/global-workflow/blob/develop/ush/parsing_namelists_FV3.sh#L330).  Also need to double check that other uses of FRAC_GRID are not behind "if cpl" statements.

**Comment by lgannoaa** [comment]
@JessicaMeixner-NOAA 
Looks like config.fcst wired in export FRAC_GRID=".true."
ush/parsing_namelists_FV3.sh is the only script check in cpl is set to true before add frac_grid into input.nml.
Is moving frac_grid    = ${FRAC_GRID:-".true."} to the cat block above satisfy your request (parsing_namelists_FV3.sh line 325)?
cat >> input.nml <<EOF
  do_sppt      = ${do_sppt:-".false."}
  do_shum      = ${do_shum:-".false."}
  do_skeb      = ${do_skeb:-".false."}
  frac_grid    = ${FRAC_GRID:-".true."}
EOF

**Comment by JessicaMeixner-NOAA** [comment]
Yes, I actually just told @WalterKolczynski-NOAA that I have this update in a branch.

**Comment by lgannoaa** [comment]
Which branch should I do the PR in?

**Comment by JessicaMeixner-NOAA** [comment]
I already have the code I need.  I'll submit it with a PR to develop with the other changes I'm doing.

**Comment by lgannoaa** [comment]
Ok
