### ISSUE TITLE
Redundant gldas build toggle

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#578]
The cfg files that determine which components are built and the partial_build.sh script all have a redundant copy of the gldas build toggle. That means if the first one is changed, it does nothing.

**Comment by KateFriedman-NOAA** [comment]
Good catch! I [found and fixed](https://github.com/NOAA-EMC/global-workflow/commit/d98e40de652e2d8889c6fe3452bbf57042354599#diff-0c12b82e8a85c4622771f0b7c22d31b58da587751f7cc01e89de215655267d04) the same duplicate in the operations branch already (feature/ops-wcoss2).
