### ISSUE TITLE
Convert modulefiles to lua

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#582]
The remaining (non-WCOSS2) modulefiles need to be converted to from TCL to lua.

**Comment by GeorgeGayno-NOAA** [comment]
UFS_UTILS 'develop' was updated to be 'lua' compliant on all machines. See https://github.com/ufs-community/UFS_UTILS/pull/614 and https://github.com/ufs-community/UFS_UTILS/issues/613

**Comment by WalterKolczynski-NOAA** [comment]
Duplicate of #756, which was completed.
