### ISSUE TITLE
Model 'atm' output filetypes are always netcdf_parallel

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/global-workflow#588]
The `OUTPUT_FILETYPES` set in config.fcst are being overwritten by parsing_model_configure_FV3.sh.  This happens between [lines 15-18](https://github.com/NOAA-EMC/global-workflow/blob/86d4b305a070c080dcfd44a3f9a31ca2280759fa/ush/parsing_model_configure_FV3.sh#L15-L18).  For S4/ivy at all resolutions as well as Hera and Jet at C768, the `atm` files often fail to write in parallel and so this option should be preserved.

**Comment by aerorahul** [comment]
@DavidHuber-NOAA 
Do you know if this is a system issue or a model issue?
What is the frequency of the "often fail"?

**Comment by DavidHuber-NOAA** [comment]
@aerorahul
I believe this is a system issue.  I have yet to see it happen on the S4/S4 partition and rarely on Orion, but I have observed it on Hera and Jet and quite often on the S4/Ivy partition.  By 'often fail', I mean that with 80 ensemble members, Ivy will almost always have at least one bad netCDF write every cycle.  On xjet at C768, the parallel atm writes failed twice for me over six GFS forecasts.  @guoqing-noaa reported similar issues on kjet in September when writing atm and sfc files in parallel and again when only writing atm files in parallel.

**Comment by aerorahul** [comment]
@DavidHuber-NOAA Thanks for a detailed report.
This is useful information to us.
