### ISSUE TITLE
FV3 empty repository on gerrit

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/global-workflow#59]
I'm back to working with this and following along with along with the instructions. My initial gerrit issue is fixed, but the FV3 repository is empty?

`Cloning into '/scratch1/NCEPDEV/nems/Kyle.Gerheiser/new_global_workflow/global-workflow/sorc/fv3gfs.fd/FV3'...
warning: You appear to have cloned an empty repository.`

`Fetched in submodule path 'FV3', but it did not contain f4f8644fe73f10513bd318b01832c448f225c007. Direct fetching of that commit failed.`

Verified by checking the repository on gerrit here:

https://vlab.ncep.noaa.gov/code-review/admin/repos/FV3,tags

With some work I found the commit on the public repo here and used that https://github.com/NOAA-EMC/fv3atm/tree/f4f8644fe73f10513bd318b01832c448f225c007

**Comment by KateFriedman-NOAA** [comment]
Kyle,

When you are in the ../sorc/fv3gfs.fd folder and type the following what
happens?

$ git submodule update --init --recursive

You got access to the FV3 repo on VLab right? NEMS too? They are submodule
projects under the NEMSfv3gfs repo there.

Kate Friedman (formerly Howard)
NOAA/NWS/NCEP/EMC Engineering and Implementation Branch

**Comment by kgerheiser** [comment]
It checks out the repo just fine but it's empty (or so it seems). If you look at that Vlab link is it not empty for you? I am part of the NEMSfv3gfs, ProdGSI, and NEMS-developer groups.

**Comment by junwang-noaa** [comment]
Kyle,

Would you please try again, it looks to me you were not added to vlab fv3
repo.

**Comment by kgerheiser** [comment]
Yes, thank you @junwang-noaa and @KateFriedman-NOAA 

It's visible now
