### ISSUE TITLE
Thinning box size definition for EnKF in config.eobs

### ISSUE THREAD

**Issue by XuLi-NOAA** [NOAA-EMC/global-workflow#595]
In config.eobs,

there is a line

export OBSINPUT_INVOBS="dmesh(1)=225.0,dmesh(2)=225.0,"

to set the thinning box size to be 225 km, for dmesh(1) and dmesh(2).

However, there  will be four defined thinning box sizes, including dmesh(3)=100 (km) and dmesh(4)= 70  in exglobal_atmos_analysis.sh, 

dmesh(3) is applied to amsr2_gcom-w1, gmi_gpm and saphir_methat
dmesh(4) is applied to 4 avhrr and 2 viirs.

It is necessary to set dmesh(3) and dmesh(4) in config.eobs.

For demsh(4), avhrr & viirs, 100 km should be set. 
I don't know the value of dmesh(3) for amsr2_gcom-w1, gmi_gpm and saphir_methat.

**Comment by aerorahul** [comment]
@XuLi-NOAA 
What are the recommended default values that need to be set in `config.eobs` for the `dmesh` variable?

If you provide those values, we can update them. We will wait for your input.

**Comment by XuLi-NOAA** [comment]
@aerorahul : As I said above, 100 km is recommended for dmesh(4), for avhrr and viirs (surface channels only currently). 

However, I don't know about dmesh(3), which are used for amsr2_gcom-w1, gmi_gpm and saphir_methat. As I understand, at least two of them will be used in the coming GFSv16.x. I am not sure who is responsible for these three instruments. 
And as I understand, dmesh(3) and dmesh(4) will be set as 100 and 70 respectively in exglobal_atmos_analysis.shscripts in GSI in GFSv16.x. the values of 100 and 70 will be used if they are not reassigned in config.eobs.

**Comment by arunchawla-NOAA** [comment]
DA Group is investigating these. This will be put on hold till we get clarification for them. Referencing @ADCollard

**Comment by arunchawla-NOAA** [comment]
@MichaelLueken-NOAA the DA team decided that this issue must first be tackled under GSI. Do you mind opening this issue under GSI first. We will put this on hold here till we get recommendation from the DA team on how to proceed

**Comment by MichaelLueken** [comment]
@arunchawla-NOAA A new issue ([#296](https://github.com/NOAA-EMC/GSI/issues/296)) was created under the NOAA-EMC/GSI repository for this to be addressed.

**Comment by XuLi-NOAA** [comment]
Andrew said we set dmesh(3)=225 km and dmesh(4)=100 km in config.eobs

**Comment by XuLi-NOAA** [comment]
@aerorahul @arunchawla-NOAA : Any update?

**Comment by ADCollard** [comment]
> @aerorahul @arunchawla-NOAA : Any update?

@XuLi-NOAA I thought you were going to do this?

**Comment by arunchawla-NOAA** [comment]
@XuLi-NOAA this was put on hold as it was going to be handled on GSI side. See the comments above

**Comment by XuLi-NOAA** [comment]
@ADCollard 

I thought Mike will handle this.

Ok, I will do it.
