### ISSUE TITLE
[Bug] gfs_atmos_gempak_meta silent fail

### ISSUE THREAD

**Issue by lgannoaa** [NOAA-EMC/global-workflow#598]
Silent fail found in gfs gempak meta job. Here is the ecflow job log from NCO wcoss2 para:
    /lfs/h1/ops/para/output/20220116/gfs_atmos_gempak_meta_00.o526230 (line 2068)
      /lfs/h1/ops/para/packages/gfs.v16.2.0/scripts/exgfs_atmos_gempak_meta.sh[86]: [: argument expected
grep "argument expected" gfs_atmos_gempak_meta_00.o526230
/lfs/h1/ops/para/packages/gfs.v16.2.0/scripts/exgfs_atmos_gempak_meta.sh[86]: [: argument expected
/lfs/h1/ops/para/packages/gfs.v16.2.0/scripts/exgfs_atmos_gempak_meta.sh[111]: [: argument expected
/lfs/h1/ops/para/packages/gfs.v16.2.0/scripts/exgfs_atmos_gempak_meta.sh[130]: [: argument expected

This issue also exist in current operation:
[Lin.Gan@v71a1 today]$ pwd
/gpfs/dell1/nco/ops/com/output/prod/today
[Lin.Gan@v71a1 today]$ grep "argument expected" gfs_atmos_gempak_meta_*.o*
gfs_atmos_gempak_meta_00.o82082149:/gpfs/dell1/nco/ops/nwprod/gfs.v16.1.5/scripts/exgfs_atmos_gempak_meta.sh[88]: [: argument expected
gfs_atmos_gempak_meta_00.o82082149:/gpfs/dell1/nco/ops/nwprod/gfs.v16.1.5/scripts/exgfs_atmos_gempak_meta.sh[113]: [: argument expected
gfs_atmos_gempak_meta_00.o82082149:/gpfs/dell1/nco/ops/nwprod/gfs.v16.1.5/scripts/exgfs_atmos_gempak_meta.sh[134]: [: argument expected
gfs_atmos_gempak_meta_06.o82101027:/gpfs/dell1/nco/ops/nwprod/gfs.v16.1.5/scripts/exgfs_atmos_gempak_meta.sh[88]: [: argument expected
gfs_atmos_gempak_meta_06.o82101027:/gpfs/dell1/nco/ops/nwprod/gfs.v16.1.5/scripts/exgfs_atmos_gempak_meta.sh[113]: [: argument expected
gfs_atmos_gempak_meta_06.o82101027:/gpfs/dell1/nco/ops/nwprod/gfs.v16.1.5/scripts/exgfs_atmos_gempak_meta.sh[134]: [: argument expected
gfs_atmos_gempak_meta_12.o82121227:/gpfs/dell1/nco/ops/nwprod/gfs.v16.1.5/scripts/exgfs_atmos_gempak_meta.sh[88]: [: argument expected
gfs_atmos_gempak_meta_12.o82121227:/gpfs/dell1/nco/ops/nwprod/gfs.v16.1.5/scripts/exgfs_atmos_gempak_meta.sh[113]: [: argument expected
gfs_atmos_gempak_meta_12.o82121227:/gpfs/dell1/nco/ops/nwprod/gfs.v16.1.5/scripts/exgfs_atmos_gempak_meta.sh[134]: [: argument expected

gfs_atmos_gempak_meta code manager please take a look.

**Comment by aerorahul** [comment]
@lgannoaa Please use the Issue template provided.
