### ISSUE TITLE
Unable to generate initial conditions

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/global-workflow#60]
I was able to successfully build after fixing #59 but now I am unable to generate initial conditions (running on Hera).

First, the UFS_UTILS in `ufs_utils.fd` in the `sorc/` directory does not contain the `util/gdas_init` directory, so I cloned this repo https://github.com/NOAA-EMC/UFS_UTILS and used the develop branch because it does, and I build that.

Then, I edit `config` using the default date (https://github.com/NOAA-EMC/UFS_UTILS/blob/develop/util/gdas_init/config) and just changing `OUTPUT_DIR` and `EXTRACT_DIR` 

Then I run

 `./driver.hera.sh`

And that fails when I look at `log.data.hires` with 

`ERROR: [FATAL] no permission to open HPSS archive file: /NCEPPROD/hpssprod/runhistory/rh2017/201707/20170719/com2_gfs_prod_gdas.2017071918.tar`

The `log.data.enkf` completes successfully. 

Then, I change the year to 2019 with the same result.

I have HPSS access on the EMC-nems and EMC-global projects. Do I need some other permission? Is there a particular date I should try or maybe pre-generated initial conditions I could use?

Maybe @GeorgeGayno-NOAA can help?

**Comment by KateFriedman-NOAA** [comment]
Kyle, do you have rstprod access? You need that to access most of the GFS
tarballs on HPSS.

Kate Friedman (formerly Howard)
NOAA/NWS/NCEP/EMC Engineering and Implementation Branch

**Comment by kgerheiser** [comment]
I do not believe I do. Is that an HPSS project? 

I just got HPSS access the other day and I wasn't sure which projects to ask for access to.

**Comment by kgerheiser** [comment]
Found it on AIM

**Comment by KateFriedman-NOAA** [comment]
Ok cool, it may take a few days for that to go through. You will need to
make sure "rstprod" is added to your groups on Hera and HPSS. If you have
it appear in your groups on Hera but you still encounter an issue accessing
HPSS then send an email to the HPSS helpdesk to have them add it to your
groups there (rdhpcs.hpss.help@noaa.gov).

Kate Friedman (formerly Howard)
NOAA/NWS/NCEP/EMC Engineering and Implementation Branch

**Comment by kgerheiser** [comment]
Otherwise, what about choosing a start date? Does it matter if I leave it at the default at 2017 if I'm just trying to get it to run? I wasn't sure if it matters that it's gfs14 or 13.

And ufs_utils.fd `v1.1.0` missing `gdas_init/`? Is using the develop branch of UFS_UTILS the correct thing to do?

**Comment by GeorgeGayno-NOAA** [comment]
> Otherwise, what about choosing a start date? Does it matter if I leave it at the default at 2017 if I'm just trying to get it to run? I wasn't sure if it matters that it's gfs14 or 13.
> And ufs_utils.fd v1.1.0 missing gdas_init/? Is using the develop branch of UFS_UTILS the correct thing to do?

Yes, use 'develop'.  None of the tags or release branches contain this utility.

**Comment by GeorgeGayno-NOAA** [comment]
> Otherwise, what about choosing a start date? Does it matter if I leave it at the default at 2017 if I'm just trying to get it to run? I wasn't sure if it matters that it's gfs14 or 13.

If you just want to get it to run, then use the default date.  The scripts will work back to April 2012.

> And ufs_utils.fd v1.1.0 missing gdas_init/? Is using the develop branch of UFS_UTILS the correct thing to do?

**Comment by KateFriedman-NOAA** [comment]
Any update on this? Things ok?

**Comment by kgerheiser** [comment]
I just tried it again today after getting access to `rstprod`, but I still can't read those files.

`ERROR: [FATAL] no permission to open HPSS archive file: /NCEPPROD/hpssprod/runhistory/rh2017/201707/20170719/com2_gfs_prod_gdas.2017071918.tar`

So, I sent an email to HPSS and was waiting to hear back from them.

**Comment by KateFriedman-NOAA** [comment]
Okie dokie, you're on the right path. Thanks for the update!

**Comment by kgerheiser** [comment]
You have to be added to the group on HPSS after being granted access to the project. I was able to generate the initial conditions.
