### ISSUE TITLE
build_ncep_post.sh failing on Venus 3.5

### ISSUE THREAD

**Issue by AndrewEichmann-NOAA** [NOAA-EMC/global-workflow#604]
Hello,

I searched issues for ncep_post and didn't find anything obviously outstanding.

**Expected behavior**

Clean finish for build_ncep_post.sh during build_all.sh 

**Current behavior**
build_ncep_post.sh fails with the end of the log
/gpfs/dell2/emc/modeling/noscrub/Andrew.Eichmann/fv3gfs/global-workflow/sorc/logs/build_ncep_post.log
reading like so:

+ cmake -DCMAKE_INSTALL_PREFIX=../install -DBUILD_WITH_WRFIO=ON ../..
./compile_upp.sh: line 27: cmake: command not found
+ make -j6
make: *** No targets specified and no makefile found.  Stop.
+ make install
make: *** No rule to make target `install'.  Stop.
+ rm -rf /gpfs/dell2/emc/modeling/noscrub/Andrew.Eichmann/fv3gfs/global-workflow/sorc/gfs_post.fd/exec
+ mkdir /gpfs/dell2/emc/modeling/noscrub/Andrew.Eichmann/fv3gfs/global-workflow/sorc/gfs_post.fd/exec
+ cp /gpfs/dell2/emc/modeling/noscrub/Andrew.Eichmann/fv3gfs/global-workflow/sorc/gfs_post.fd/tests/install/bin/upp.x /gpfs/dell2/emc/modeling/noscrub/Andrew.Eichmann/fv3gfs/global-workflow/sorc/gfs_post.fd/exec/.
cp: cannot stat ‘/gpfs/dell2/emc/modeling/noscrub/Andrew.Eichmann/fv3gfs/global-workflow/sorc/gfs_post.fd/tests/install/bin/upp.x’: No such file or directory

**Machines affected**
Venus phase 3.5

**To Reproduce**
Build is under /gpfs/dell2/emc/modeling/noscrub/Andrew.Eichmann/fv3gfs/develop/global-workflow/sorc
Running sh build_ncep_post.sh produces this result

**Context**
This is in a newly revived WCOSS account, fresh clone of global_workflow

**Detailed Description**
It appears that cmake is not found on line 28 of gfs_post.fd/tests/compile_upp.sh . I tried adding the line 
module load cmake/3.20.2
at line 23, but that didn't seem to make any difference 

Thank you,
Andy Eichmann

**Comment by WalterKolczynski-NOAA** [comment]
Dell 3.5 isn't currently a supported machine. Please use Dell 3 instead.

**Comment by AndrewEichmann-NOAA** [comment]
whoops, sorry!
