### ISSUE TITLE
Add ensemble forecast support

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#613]
Skeleton EPIC to be filled in later with tasks that need to be completed to add ensemble support

**Comment by arunchawla-NOAA** [comment]
Hi

Just curious as to where we go from here ? It will be nice to see if we can create a series of issues that we can work with the ensemble team and transition them to the global workflow ?

**Comment by WalterKolczynski-NOAA** [comment]
@aerorahul with the new project-based stuff, do we need to have this EPIC?
