### ISSUE TITLE
Cleaning up utils directory

### ISSUE THREAD

**Issue by arunchawla-NOAA** [NOAA-EMC/global-workflow#618]
If this is a bug, please consider using the [Bug Report](./bug_report.md) template.
Your issue may already have been created!
Please search on the [Issue tracker](https://github.com/NOAA-EMC/global-workflow/issues) before creating one.

**Description**
The UTILS directory under global workflow contains a lot of code that may no longer be used. This issue is to track and identify all the codes that need to be removed from the repository

**Requirements**

**Acceptance Criteria (Definition of Done)**

Unused codes must be removed or moved elsewhere and should not hamper the end to end testing of the workflow

**Dependencies**

**Comment by arunchawla-NOAA** [comment]
There is a discussion happening here (https://github.com/NOAA-EMC/global-workflow/discussions/615) on utilities that should be part of GSM and not part of this repository

**Comment by arunchawla-NOAA** [comment]
@HelinWei-NOAA and @barlage there is a config.gldas in global workflow that sets FINDDATE to HOMEgfs/util/ush/findate.sh but I cannot see that being used anywhere. There is a call for a local version of finddate but that line is commented out

**Comment by arunchawla-NOAA** [comment]
I also cannot see verfdate.sh being used anywhere in the workflow

**Comment by arunchawla-NOAA** [comment]
The file make_ntcfile.pl is not used anywhere

**Comment by arunchawla-NOAA** [comment]
The script xlf_links.sh is also not used anywhere

**Comment by arunchawla-NOAA** [comment]
The scripts snd2forgn and snd2forgntbl are not being used anywhere

**Comment by HelinWei-NOAA** [comment]
> @HelinWei-NOAA and @barlage there is a config.gldas in global workflow that sets FINDDATE to HOMEgfs/util/ush/findate.sh but I cannot see that being used anywhere. There is a call for a local version of finddate but that line is commented out

It has been used by both gldas_forcing.sh and gldas_archive.sh.

**Comment by arunchawla-NOAA** [comment]
Those scripts are not part of global workflow right ?

**Comment by arunchawla-NOAA** [comment]
The script sndncdc is not used anywhere

**Comment by HelinWei-NOAA** [comment]
> Those scripts are not part of global workflow right ?

They are part of global workflow under ush
