### ISSUE TITLE
GFSv15.3.0 production updates

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#63]
Created release branch for hand-off to NCO: release/gfs.v15.30.0

Branch contains the following changes:

* ProdGSI tag update (from issue #37)
* bug fix to syndat_qctropcy.fd/qctropcy.f
* change to link_fv3gfs.sh to point to updated fix file set which contains updated syndat_stmnames file
* change to checkout.sh to update ProdGSI, EMC_post_gtg, and EMC_gfs_wafs tags to latest ops versions

--------------------------------------------------------------------

The syndat_stmnames fix file under fix_am subset is being updated to fix a storm name.

It was decided to establish a frozen copy of FIX_DIR on supported platforms for v15 fix files ("fix_nco_gfsv15"). Copy established by Fanglin Yang and copied to supported platforms by Kate Friedman.

Will update link script to point to frozen "fix_nco_gfsv15" copy on supported platforms. Will freeze and version FIX_DIR like this going forward.

**Comment by KateFriedman-NOAA** [comment]
Created release/gfs.v15.2.13 branch off operations branch for this work.

**Comment by KateFriedman-NOAA** [comment]
Created release tag for hand-off to NCO: RT-GFS-v15.2.13

Tag contains the following changes:
* bug fix to syndat_qctropcy.fd/qctropcy.f
* change to link_fv3gfs.sh to point to updated fix file set which contains updated syndat_stmnames file
* change to checkout.sh to update ProdGSI and EMC_post_gtg tags to latest ops versions

**Comment by KateFriedman-NOAA** [comment]
CDF drafted and sent to NCO.

**Comment by RussTreadon-NOAA** [comment]
NCO requested and EMC management agreed that GFS v15.2.13 and GFS v15.3.0 be merged into a single implementation package.  As such GFS v15.3 development is now being tracked in issued #63.   Commit c90ea4b updated sorc/checkout.sh in workflow branch [release/gfs.v15.2.13](https://github.com/NOAA-EMC/global-workflow/tree/release/gfs.v15.2.13) to point at the GFS v15.3.0 DA tag. 

GFS v15.3 issue #37 may be closed and workflow branch [feature/gfs.v15.3](https://github.com/NOAA-EMC/global-workflow/tree/feature/gfsv15.3) removed as both are now obsolete.

**Comment by KateFriedman-NOAA** [comment]
Created release/gfs.v15.3.0 off release/gfs.v15.2.13 for hand-off.

**Comment by KateFriedman-NOAA** [comment]
Tested implementation instructions for NCO on Venus (used VLab workarounds) and modified link_fv3gfs.sh to use rsync instead of cp to make the FIX_DIR pickup faster/safer.

Updated implementation instructions with workaround details.

**Comment by KateFriedman-NOAA** [comment]
Implementation instructions prepared and tested with final package. Handing off to NCO today.

**Comment by KateFriedman-NOAA** [comment]
From the May 22nd RFC memo:

> RFC 6893 – gfs v15.3.0 – On WCOSS, upgrade the GFS to v15.3.0. This new version implements the assimilation of COSMIC-2 GNSS-RO (Global Navigation Satellite System - Radio Occultation) data; fixes a bug in ‘sorc/syndat_qctropcy.fd/qctropcy.f’ which can cause bad tcvital records in the quality control step; updates ‘fix/fix_am/syndat_stmnames’, which is a fix file with updated tropical storm names; and enables alerting of GFS master files. To be implemented on May 26 at 1300Z.

**Comment by KateFriedman-NOAA** [comment]
Did comparison between release/gfs.v15.3.0 branch and the nwprod/gfs.v15.3.0 installation post-implementation on May 26th. Found final post-hand-off/pre-implementation changes and committed them to release/gfs.v15.3.0 branch at 737cfa8.

Will initiate PR to merge release/gfs.v15.3.0 into operations branch. Will run test on WCOSS to compare against ops before completing PR.

**Comment by KateFriedman-NOAA** [comment]
Reproduce test against ops successful, although I had to make local changes to handle the GDA structure change and point to updated obsproc versions. Performing PR to merge release/gfs.v15.3.0 branch into operations branch and then tag NCO-v15.3.0.

**Comment by KateFriedman-NOAA** [comment]
Submitted PR #79 and deleted release/gfs.v15.3.0 via PR. Created tag NCO-v15.3.0.
