### ISSUE TITLE
Issue about loading module (Lmod) in global-workflow on Hera

### ISSUE THREAD

**Issue by wzzheng90** [NOAA-EMC/global-workflow#632]
**Description**

I use the rocotorun to submit jobs with the old global-workflow after Raghu Reddy rolled back
the lmod change on Hera, but still have a problem about Lmod as follows:
 
      Lmod has detected the following error: Cannot load module
     "hpc-intel/18.0.5.274" without these module(s) loaded:
      intel/18.0.5.274

More detailed messages can be found in /scratch1/NCEPDEV/stmp2/Weizhong.Zheng/P8amini/COMROT/R_Diag3h_20120701/logs/2012070100/gfscoupled_ic.log.0

However, Raghu and I did a test if we just tried this command only under "bash -l":

% export HOMEgfs=/scratch2/NCEPDEV/land/Weizhong.Zheng/noscrub/git_UFS_P8amini/global-workflowDiag
%  .  /scratch2/NCEPDEV/land/Weizhong.Zheng/noscrub/git_UFS_P8amini/global-workflowDiag/ush/load_fv3gfs_modules.sh

It works without issue.   So, after Raghu and I took a look at the scripts, and confirmed that if we run the script interactively 
the modules load fine.  So it doesn't look like this is related to the lmod issue.

BTW, I did not have this kind of problem before Hera's maintenance.   Any suggestions about this problem? 

Thanks,

Weizhong

**Comment by aerorahul** [comment]
@wzzheng90 
A test was created on Hera to emulate the behavior of loading modules in the jobs.
The test is available at: `/home/Rahul.Mahajan/test`

Please do the following:
```
cd /home/Rahul.Mahajan/test
./test_modules.sh
./test_modules2.sh
```

Next, you can try submitting the `test_modules2.sh` to a compute node with something like this:
```
cd
sbatch --partition=hera --qos=debug --account=fv3-cpu --nodes=1 --ntasks-per-node=1 --time=00:01:00 /home/Rahul.Mahajan/test/test_modules2.sh
```

You should see a `slurm-*.out` file containing the output.

Tagging @RaghuReddy-NOAA

**Comment by wzzheng90** [comment]
@RaghuReddy-NOAA:  Thanks!  I did according to your instruction and the output can be found in "/home/Weizhong.Zheng/slurm-28207142.out".

**Comment by wzzheng90** [comment]
Sorry.  Should be to @Rahul.Mahajan

**Comment by WalterKolczynski-NOAA** [comment]
Looks like all the modules loaded fine in that test.

**Comment by WalterKolczynski-NOAA** [comment]
@wzzheng90 in the future, it is a good idea to dump logfiles into a GitHub gist so people don't have to access the HPC to see it: [Weizhong's module test log](https://gist.github.com/WalterKolczynski-NOAA/17515df495fe4b32f0b1a3eba920a41a)

**Comment by wzzheng90** [comment]
@WalterKolczynski-NOAA :  Thanks.

**Comment by arunchawla-NOAA** [comment]
If the modules are loading fine, is this still an issue @wzzheng90 ? Curious, when you say old global workflow what exactly do you mean ?

**Comment by wzzheng90** [comment]
@arunchawla-NOAA :  I tried several times, and I still have this issue when I used the rocoto to submit the jobs.    The global workflow version was cloned last month and used to run P8a.  
       As Kate mentioned from her email, the newer develop branch of global-workflow shouldn't be having issues since it already uses the new hpc-stack modules.  I am trying this new version, but I am wondering why the old version has this issue after Hera's maintenance.

**Comment by aerorahul** [comment]
@wzzheng90 
The test I constructed is using the HOMEgfs from your path and not the develop branch. 
It is loading exactly what your branch is loading.

**Comment by wzzheng90** [comment]
@aerorahul :    Yes, I tried your test without issue.  I am wondering if there is anything changed when "rocoto" submits jobs.
For example, the first script is "gfscoupled_ic" step.  The beginning from its output ("gfscoupled_ic.log") is as follows:

+ . /scratch2/NCEPDEV/land/Weizhong.Zheng/noscrub/git_UFS_P8amini/global-workflowDiag/ush/load_fv3gfs_modules.sh
+++ ulimit -S -s
++ ulimit_s=unlimited
++ set +x
Lmod has detected the following error: Cannot load module
"hpc-intel/18.0.5.274" without these module(s) loaded:
   intel/18.0.5.274

@KateFriedman-NOAA, @WalterKolczynski-NOAA :  Do you know anything changed (in global-workflow) with "rocoto"?  

Thanks,

Weizhong

**Comment by aerorahul** [comment]
@wzzheng90 

I recreated a test by submitting your experiment with `rocoto` version 1.3.3 and was unable to reproduce the error you report.

I copied your XML `/scratch1/NCEPDEV/stmp2/Weizhong.Zheng/P8amini/EXPDIR/R_Diag3h_20120701/R_Diag3h_20120701.xml` to `/home/Rahul.Mahajan/test/myR_Diag3h_20120701/R_Diag3h_20120701.xml` and am only running the first job `gfscoupled_ic`.

I also copied the job script `/scratch2/NCEPDEV/land/Weizhong.Zheng/noscrub/git_UFS_P8amini/global-workflowDiag/jobs/rocoto/coupled_ic.sh` to `/home/Rahul.Mahajan/test/mycoupled_ic.sh`.  I list the loaded modules and place an exit immediately after loading the modules for this test.

You can do a diff between the xml's
```
$>>> diff myR_Diag3h_20120701.xml /scratch1/NCEPDEV/stmp2/Weizhong.Zheng/P8amini/EXPDIR/R_Diag3h_20120701/R_Diag3h_20120701.xml
31d30
< 	<!ENTITY myEXPDIR "/home/Rahul.Mahajan/test">
33d31
< 	<!ENTITY myROTDIR "/home/Rahul.Mahajan/test">
39d36
< 	<!ENTITY myJOBS_DIR "/home/Rahul.Mahajan/test">
231c228
< 	<log verbosity="10"><cyclestr>&myEXPDIR;/logs/@Y@m@d@H.log</cyclestr></log>
---
> 	<log verbosity="10"><cyclestr>&EXPDIR;/logs/@Y@m@d@H.log</cyclestr></log>
238c235
< 	<command>&myJOBS_DIR;/mycoupled_ic.sh</command>
---
> 	<command>&JOBS_DIR;/coupled_ic.sh</command>
249c246
< 	<join><cyclestr>&myROTDIR;/logs/@Y@m@d@H/gfscoupled_ic.log</cyclestr></join>
---
> 	<join><cyclestr>&ROTDIR;/logs/@Y@m@d@H/gfscoupled_ic.log</cyclestr></join>
259,260d255
< </task>
< <!--
627c622
< -->
---
>
```

and the job scripts
```
$>>> diff mycoupled_ic.sh /scratch2/NCEPDEV/land/Weizhong.Zheng/noscrub/git_UFS_P8amini/global-workflowDiag/jobs/rocoto/coupled_ic.sh
23d22
< set +x
< module list
< exit 0
```

The output of my `rocotorun -v 10 -w myR_Diag3h_20120701.xml -d myR_Diag3h_20120701.db` and the job execution is in `/home/Rahul.Mahajan/test/logs` and is shown here:
```
$>>> cat logs/2012070100/gfscoupled_ic.log
+ . /scratch2/NCEPDEV/land/Weizhong.Zheng/noscrub/git_UFS_P8amini/global-workflowDiag/ush/load_fv3gfs_modules.sh
+++ ulimit -S -s
++ ulimit_s=unlimited
++ set +x
++ ulimit -S -s unlimited
++ unset ulimit_s
+ status=0
+ [[ 0 -ne 0 ]]
+ err=0
+ set +x

Currently Loaded Modules:
  1) hpc/1.1.0                    19) g2tmpl/1.10.0
  2) intel/18.0.5.274             20) ip/3.3.3
  3) hpc-intel/18.0.5.274         21) sp/2.3.3
  4) impi/2018.0.4                22) sigio/2.3.2
  5) hpc-impi/2018.0.4            23) bacio/2.4.1
  6) hpss/hpss                    24) w3nco/2.4.1
  7) nco/4.9.1                    25) nemsio/2.5.2
  8) gempak/7.4.2                 26) w3emc/2.9.0
  9) ncl/6.6.2                    27) crtm/2.4.0
 10) prod_util/1.2.2              28) upp/10.0.8
 11) grib_util/1.2.2              29) hdf5/1.10.6
 12) jasper/2.0.25                30) netcdf/4.7.4
 13) zlib/1.2.11                  31) wgrib2/2.0.8
 14) png/1.6.35                   32) anaconda/2.3.0
 15) pio/2.5.2                    33) grib_api/1.26.1
 16) esmf/8_2_0_beta_snapshot_14  34) cdo/1.9.5
 17) fms/2021.03                  35) module_base.hera
 18) g2/3.4.3



_______________________________________________________________
Start Epilog v20.08.28 on node h24c49 for job 28228330 :: Fri Feb 4 13:41:01 UTC 2022
Job 28228330 (not serial) finished for user Rahul.Mahajan in partition hera with exit code 0:0
_______________________________________________________________
End Epilogue v20.08.28 Fri Feb 4 13:41:01 UTC 2022
 ```

I do not spot the error you report.

If you spot anything incorrect in my test using your experiment xml and branch of the global-workflow, please let me know.

**Comment by wzzheng90** [comment]
@aerorahul :  Sounds good.  I am going to try this test and see if this kind of runs works under my environment.

**Comment by arunchawla-NOAA** [comment]
@wzzheng90 this sounds like an environment issue at your end. Are you loading modules in your environment somewhere ?

**Comment by wzzheng90** [comment]
@aerorahul   I load modules only from ".cshrc" under my home directory.   
BTW,   I got the same error when running the first job only:  
        rocotorun -v 10 -w R_Diag3h_20120701.xml -d R_Diag3h_20120701.db
So, most likely, it would be related the my environment setup.

**Comment by wzzheng90** [comment]
@aerorahul   It works with your suggestions (clear my home directory; modification of .bash_profile and .cshrc) and then I can successfully run a single job test.                                              
After successfully testing a single job, I am running the full global-workflow successfully too.    
Really appreciate you for time and efforts on my issue!!        

Also thanks a lot for Raghu, Kate and Walter for kindly helps!!   @RaghuReddy-NOAA @KateFriedman-NOAA @WalterKolczynski-NOAA

**Comment by KariA-Spire** [comment]
Hello:
I'm having a similar issue at **runtime**, but with global-workflow v16.2.1 on Hera.: 

/scratch2/AOML/aoml-osse/Karina.Apodaca/projects/aeolus/GitHub_global/rot/v16_CTL2/logs/2019091500/gdasfcst.log
displays this message: 

```
+ . /scratch2/AOML/aoml-osse/Karina.Apodaca/projects/aeolus/global-workflow_v16.2/ush/load_fv3gfs_modules.sh
+ ulimit -S -s
+ ulimit_s=unlimited
Lmod has detected the following error: Cannot load module "hpc-intel/2022.1.2"
without these module(s) loaded:
   intel/2022.1.2

While processing the following module(s):
    Module fullname     Module Filename
    ---------------     ---------------
    hpc-intel/2022.1.2  /scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack-gfsv16/modulefiles/core/hpc-intel/2022.1.2.lua
    module_base.hera    /scratch2/AOML/aoml-osse/Karina.Apodaca/projects/aeolus/global-workflow_v16.2/modulefiles/module_base.hera.lua

+ ulimit -S -s unlimited
+ unset ulimit_s
+ status=0
```

I'm not loading modules via my .cshrc or manually prior to setting up the workflow.

I tested @aerorahul test_modules3.sh and all modules are loaded correctly.

```
[Karina.Apodaca@hfe08 ~]$ sh test_modules3.sh
++ ulimit -S -s 300000
++ unset ulimit_s
+ set +x

Currently Loaded Modules:
  1) hpc/1.2.0              5) hpc-impi/2018.0.4   9) hpss/hpss     13) udunits/2.2.28   17) crtm/2.3.0     21) module_base.hera
  2) intel/18.0.5.274       6) esmf/8_0_1         10) cdo/1.9.8     14) nco/4.9.3        18) g2tmpl/1.9.1
  3) hpc-intel/18.0.5.274   7) anaconda/2.3.0     11) hdf5/1.10.6   15) prod_util/1.2.2  19) wgrib2/2.0.7
  4) impi/2018.0.4          8) gempak/7.4.2       12) netcdf/4.7.4  16) grib_util/1.2.3  20) prepobs/1.0.1
```

What was the solution in @wzzheng90 case? 
Does anyone have an idea on how to solve this? 

Thank you and have a nice evening.
