### ISSUE TITLE
Clean up the machine-setup script

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#635]
**Description**
The machine-setup script is a bit convoluted and is loading a bunch of modules that likely aren't needed because we already have module files that are loaded.

**Requirements**
- Determine whether the shell detection can just use $SHELL instead
- Use $SITE if available to determine machine, only fall back on other methods on machines that don't define it
- Remove unneeded module loads

**Acceptance Criteria (Definition of Done)**
A streamlined script that just determines the machine and sources the module init script for the appropriate shell. Functionality of the script may change (since modules are no longer being loaded), but overall functionality of global-workflow should remain unchanged.

**Dependencies**
None

**Comment by KateFriedman-NOAA** [comment]
The `machine-setup.sh` script was moved to the gfs-utils repo and then subsequent refactoring in gfs-utils removed it. Closing this issue as completed.
