### ISSUE TITLE
Building fails on Hera ("build_all.sh")

### ISSUE THREAD

**Issue by wzzheng90** [NOAA-EMC/global-workflow#636]
"build_all.sh" is not working on hera since last weekend.  Is anyone else having trouble compiling it?   Possibly related to "Disk quota exceeded"?

=====The error messages are as follows:
% build_all.sh -c
Received -c flag, building ufs-weather-model for S2SW app
skipping builds not needed for prototype runs
 .... Building WW3 pre and post execs ....
Fatal error in building WW3 pre/post processing.

====="~/logs/build_ww3_prepost.log" is as follows:
Processing ww3_grid
---------------------
ad3 : processing constants
ad3 : processing scrip_kindsmod [no w3adc]
      *** compile error ***
          file comp.stat.scrip_kindsmod not found
make: *** [/scratch2/NCEPDEV/land/Weizhong.Zheng/noscrub/git_UFS_P8amini/global-workflowDiag/sorc/ufs_model.fd/WW3/model/obj/scrip_kindsmod.o] Error 5
make: *** Waiting for unfinished jobs....
      *** compile error ***
          file comp.stat.constants not found
make: *** [/scratch2/NCEPDEV/land/Weizhong.Zheng/noscrub/git_UFS_P8amini/global-workflowDiag/sorc/ufs_model.fd/WW3/model/obj/constants.o] Error 5
+ rc=1
+ [[ 1 -ne 0 ]]
+ echo 'FATAL: Error building ww3_grid (Error code 1)'
FATAL: Error building ww3_grid (Error code 1)
+ exit 1

**Comment by WalterKolczynski-NOAA** [comment]
If you got "Disk quota exceeded" during checkout, it didn't finish cloning all the components. Delete the g-w clone and start over, then let us know if you still have issues.

**Comment by wzzheng90** [comment]
@WalterKolczynski-NOAA :  The code was checked out before and it worked last week.  Just modified something and would like to re-compile it again.   I tried again and got the similar problem.

**Comment by WalterKolczynski-NOAA** [comment]
I checked your log. I have no idea why you are getting a disk quota error there. All that is happening on that line is sorting a small file and writing it to a different small file:
```
sort -u filelist.tmp                            > filelist
```
The `filelist.tmp` exists (`/scratch2/NCEPDEV/land/Weizhong.Zheng/noscrub/git_UFS_P8amini/global-workflowDiag/sorc/ufs_model.fd/WW3/model/tmp/filelist.tmp`). I'm able to build successfully on Hera using the same version (a clean copy). This sounds like an RDHPCS problem, not a global-workflow problem. Contact the Hera helpdesk, and if Raghu needs g-w CM help, tell him to contact me.

Also, I will note that you are cloning Jessica's fork, not the authoritative repo, using a branch that doesn't exist in global-workflow (though the tag prototype/coupled_8a should be what you want).

**Comment by JessicaMeixner-NOAA** [comment]
@wzzheng90 as we discussed in emails with @KateFriedman-NOAA and @WalterKolczynski-NOAA said above, please switch to using the tag prototype/coupled_8a

**Comment by wzzheng90** [comment]
@WalterKolczynski-NOAA:  Thanks!!  I have contacted the Hera helpdesk and created a ticket.  
@JessicaMeixner-NOAA:   Yes, I am also working on the tag prototype/coupled_8a with your and Kate's suggestions.  
The similar problem happens on this version too.   As Walter mentioned, this sounds like an RDHPCS problem, for these g-workflow versions worked before.  Thanks.

**Comment by wzzheng90** [comment]
This issue is related to the project disk space problem (file count limit).  I tried it on different disk
and it is working without issue.  So, we need to remove as many files under the project as possible, or try to find a way to solve this problem if it happens again in future.
