### ISSUE TITLE
efcs failure "At least one pe in pelist is not used by any tile in the mosaic"

### ISSUE THREAD

**Issue by AndrewEichmann-NOAA** [NOAA-EMC/global-workflow#646]
**Description**

Short version: I have an ensemble forecast that ends with:

>   0: atmosphere_init: current_time_seconds =   10800.0
>   0: Using n_split from the namelist: 006
>   0:  Off center implicit scheme param=   1.00000000000000
>   0:   p_fac=  0.100000000000000
>   0: Using n_sponge : 042
>   0: Using non_ortho :       T
>   0:  Starting PEs :          160
>   0:  Starting Threads :            2
>  11:
>  11: FATAL from PE    11: mpp_domains_define.inc: At least one pe in pelist is not used by any tile in the mosaic
>  11:
>   0:
>   0: FATAL from PE     0: mpp_domains_define.inc: At least one pe in pelist is not used by any tile in the mosaic
>   0:

Long version:

The implementation of EFSOI runs a parallel GDAS workflow starting with gdaseupdfsoi, which closely resembles gdaseupd. It produces an alternate analysis which goes through tasks gdasecenfsoi, gdasesfcfsoi, and gdasefcsfsoi, all operating on a tree similar to the enkfgdas.YYYYMMDD but called efsoigdas.YYYYMMDD. gdaseupdfsoi has it's own /scripts script which is similar to that of   gdaseupd, and the rest of the tasks use scripts in /jobs to make the necessary changes in parameters, with an exception to follow. This has worked straighforwardly until the last merge to my fork from develop on Feb 2, the first since Nov 18. The only conflict with scripts was with scripts/exglobal_forecast.sh, where an if/then block that pointed to efsoigdas instead of enkfgdas was moved to ush/forecast_predet.sh. Now all instances of gdasefcsfsoi end with the above error. 

Would anybody have any hints for what to look at? I presume there is some problem with the initial conditions, but it's not obvious to me what to examine.

I should note that the ensemble update for EFSOI uses the serial filter instead of LETKF, but I have since run regular cycling with the serial filter without encountering this problem.

**Requirements**

To run the ensemble forecast with the alternate analysis, processes otherwise the same as the regular analysis

**Acceptance Criteria (Definition of Done)**

Able to run the ensemble forecast

**Dependencies**

This blocks progress on the development of EFSOI 

Directories on Orion
build: /work/noaa/da/aeichman/fv3gfs/EFSOI-merge-gw/global-workflow
expdir: /work/noaa/da/aeichman/para/toddler
comrot: /work2/noaa/stmp/aeichman/comrot/toddler
rundirs: /work/noaa/stmp/aeichman/RUNDIRS/toddler

**Comment by WalterKolczynski-NOAA** [comment]
Working backwards from what the model sees:

The atm PETs given in your `nems.configure` probably don't match the layout settings in your `input.nml`. The number of PETs needs to equal ```( layout_X * layout_y * 6 ) + ( write_groups * write_tasks_per_group )```

These are written by the [nems_configure.sh](../tree/develop/ush/nems_configure.sh) and [parsing_namelists_FV3.sh](../tree/ush/parsing_namelists_FV3.sh).

The math is done in the fcst section of [config.resources](../tree/parm/config/config.resources#L178). The `config.resources` file gets copied to your experiment directory when you run [setup_expt.py](../tree/ush/rocoto/setup_expt.py).

**Comment by WalterKolczynski-NOAA** [comment]
Slight correction: When running just with atmosphere, the pet bounds don't get written to `nems.configure`, because there's no need (the model gets all of them). So it would be make sure the number of ranks specified by srun match the above formula.

**Comment by AndrewEichmann-NOAA** [comment]
That cracked the problem. grepping the logs yielded the following difference:

> Orion-login-2[93] aeichman$ grep srun gdasefcs01.log 
> 0.149 + launcher='srun -l --export=ALL'
> 0.149 + APRUN_FV3='srun -l --export=ALL -n 184'
> ...
> 
> Orion-login-2[94] aeichman$ grep srun gdasefcsfsoi01.log
> 0.137 + launcher='srun -l --export=ALL'
> 0.137 + APRUN_FV3='srun -l --export=ALL'
> ...

which lead to making this change in my fork's global-workflow/env/ORION.env:

> elif [ $step = "efcsfsoi" ]; then
> 
>     nth_max=$(($npe_node_max / $npe_node_efcsfsoi))
> 
>     export NTHREADS_FV3=${nth_efcfsois:-$nth_max}
>     [[ $NTHREADS_FV3 -gt $nth_max ]] && export NTHREADS_FV3=$nth_max
>     export cores_per_node=$npe_node_max
>     #export APRUN_FV3="$launcher"
>     export APRUN_FV3="$launcher -n $npe_efcsfsoi"

This solved the immediate problem. Thank you, Walter!
