### ISSUE TITLE
GFSv15.3.1 - AWIPS data card update

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#65]
> Effective on about June 16, 2020, beginning with the 1200 Coordinated Universal Time (UTC) run, the National Centers for Environmental Prediction (NCEP) will upgrade the Global Forecast System. The upgrade will replace the variables for precipitation and vertical velocity for all World Meteorological Organization (WMO) headed data over NOAAPort and on the Global Telecommunications System (GTS).

https://www.weather.gov/media/notification/scn20-48gfs_noaaport.pdf

**Comment by KateFriedman-NOAA** [comment]
Created feature/gfsv15.3.1 branch for this work. Will make a release tag for hand-off.

**Comment by BoiVuong-NOAA** [comment]
All data cards for AWIPS have updated the vertical velocity variable (VVEL) to (DZDT) and the units will be changed from (pascal/s) to (m/s) and the total and convective precipitation variables (APCP, ACPCP) will be changed from total (3-hour or 6-hour) accumulation to continuous accumulation.

**Comment by BoiVuong-NOAA** [comment]
All data cards (301 files) for AWIPS  completed testing with data on 05/01/2020 and committed to the branch feature/gfsv15.3.1.

**Comment by KateFriedman-NOAA** [comment]
Switched branch name for hand-off to release/gfsv15.3.1 (created off feature/gfsv15.3.1). Given NCO is now accepting release branches from GitHub and I don't need to tag for hand-off I will name future ops hand-off branches like this (follows Gitflow):

release/gfsvX.Y.Z

...and after implementation of that version is complete (assumes operations branch has ingested release changes) I will tag the operations branch for the official tags:

NCO-vX.Y.Z

The feature branch naming convention will be used for the develop branch.

**Comment by BoiVuong-NOAA** [comment]
The CDF has submitted to NCO.

**Comment by KateFriedman-NOAA** [comment]
Committed a fix to link_fv3gfs.sh for emc mode (no impact to nco mode) which bettter handles the fix files in the new frozen format:

```
diff --git a/sorc/link_fv3gfs.sh b/sorc/link_fv3gfs.sh
index 4f41db4a..d70b76a0 100755
--- a/sorc/link_fv3gfs.sh
+++ b/sorc/link_fv3gfs.sh
@@ -38,10 +38,10 @@ elif [ $machine = "theia" ]; then
     FIX_DIR="/scratch4/NCEPDEV/global/save/glopara/git/fv3gfs/fix"
 fi
 cd ${pwd}/../fix                ||exit 8
-for dir in fix_am fix_fv3 fix_orog fix_fv3_gmted2010 ; do
+for dir in fix_am fix_chem fix_fv3 fix_fv3_gmted2010 fix_orog fix_sfc_climo fix_verif ; do
     [[ -d $dir ]] && rm -rf $dir
+    $LINK $FIX_DIR/$dir $dir
 done
-$LINK $FIX_DIR/* .
```

Will also commit to develop so the development branches get this fix.

**Comment by KateFriedman-NOAA** [comment]
Sync merged operations into release/gfsv15.3.1 branch after completing v15.3.0 commits.

**Comment by KateFriedman-NOAA** [comment]
From June 12th RFC memo:

> RFC 6963 - Update precipitation buckets and vertical velocity in GFS WMO headed output as advertised in SCN 20-48: https://www.weather.gov/media/notification/scn20-48gfs_noaaport.pdf. To be implemented on June 16 at 1430Z.

**Comment by KateFriedman-NOAA** [comment]
Tagged operations branch: NCO-v15.3.1
