### ISSUE TITLE
Create Free Forecast ECFLOW workflow

### ISSUE THREAD

**Issue by lgannoaa** [NOAA-EMC/global-workflow#654]
**Description**

This is to document the action and status of the Free Forecast ECFLOW workflow development.
@arunchawla-NOAA tasked @lgannoaa to create Free Forecast ECFLOW workflow. It will be used as a base line for @KyleNevins-NOAA to work on a software solution to dynamically generate this workflow.
**Requirements**

This version is C192 low resolution currently running on Hera. With the following steps:
_Workflow Manager:_
_-gfs_ic_manager:_ File based trigger job to turn on initial condition jobs or run forecast job if ICs found. It is the center of control job for free forecast workflow.
_-Initial condition jobs:_
_--gfs_getic:_ Get initial condition as needed.
_--gfs_init:_ Process initial condition and chgres as needed.
_Forecast/post jobs:_
_--gfs_forecast:_ Generate in-line post enabled product with wave turned off
_--post:_ Generate pgb files from master file created in fcst step.
_Run control task:_
_--next_run:_ Requote jobs after the current cycle completed.
**Acceptance Criteria (Definition of Done)**

All jobs run to complete in few PDYs.
**Dependencies**

To be identified...

**Comment by lgannoaa** [comment]
Git location for the most current version is located in:
https://github.com/lgannoaa/global-workflow/pull/new/feature/ecf-freefcst-hera

**Comment by lgannoaa** [comment]
**Step by step setup instruction:**

---

**(From Hera node to Hera ecflow server)**
module load ecflow;ssh -Y $USER@$ECF_HOST

**(Load ecflow module in Hera ecflow server)**
module load ecflow

**(Checkout Hera ECFLOW workflow enabled GFS package)**
mkdir -p /scratch1/NCEPDEV/global/$USER/git; cd /scratch1/NCEPDEV/global/$USER/git
git clone https://github.com/$GIT_USER_NAME-here/global-workflow global-workflow-develop
cd global-workflow-develop
git remote add upstream https://github.com/lgannoaa/global-workflow
git fetch upstream
git checkout upstream/feature/ecf-freefcst-hera
git checkout -b feature/$YOUR_GIT_BRANCH_NAME-here
git merge upstream/feature/ecf-freefcst-hera
HOMEgfs=$PWD
ECFDEF=$HOMEgfs/ecf/defs

**(Checkout, Build, and Link GFS package as needed -- see related document for steps)**

**(Start up ecflow server for the first time - ONLY for the first time Hera ecflow use)**
ecflow_start.sh

**(Shut down ecflow server for the first time - ONLY for the first time Hera ecflow use)**
ecflow_stop.sh

**(Move auto created ecflow server directory into manageable location)**
**(  ONLY for the first time Hera ecflow use  )**
mkdir -p /scratch1/NCEPDEV/global/$USER/ecflow
mv ecflow_server /scratch1/NCEPDEV/global/$USER/ecflow
ln -s /scratch1/NCEPDEV/global/$USER/ecflow/ecflow_server 

**(Start up ecflow server - ONLY for the first time Hera ecflow use)**
ecflow_start.sh

**(Configure Hera ecflow server - ONLY for the first time Hera ecflow use)**
ecflow_client --alter add variable 'ECF_JOB_CMD sbatch < %ECF_JOB% 1> %ECF_JOBOUT% 2>&1' /

**(Load free forecast ecflow workflow on Hera ecflow server)**
cd $ECFDEF
ecflow_client --load task_limit.def (This ecflow suite does the job to limit max concurrent jobs can be submitted)
ecflow_client --load 00_fcstonly.def (This is the free forecast ecflow workflow definition)
ecflow_client --begin=task_limit
ecflow_client --begin=fcstonly

---

**Comment by lgannoaa** [comment]
According on task_limit set to 12:
Average speed of each 00Z run 3 hours and 15 minutes
Average size of each cycle run is 375G

**Comment by WalterKolczynski-NOAA** [comment]
@lgannoaa I assume this was completed long ago and we can close this?

**Comment by lgannoaa** [comment]
Yes. Please close it.
