### ISSUE TITLE
DO-4 for commercial GPS-RO (Workflow)

### ISSUE THREAD

**Issue by CatherineThomas-NOAA** [NOAA-EMC/global-workflow#656]
Delivery Order 4 (DO-4) has been awarded to both GeoOptics and Spire, requiring a change in the GSI.  See GSI Issue [#305 ](https://github.com/NOAA-EMC/GSI/issues/305) for details.

CDF deadline: March 1
Data flow begins: March 16
Target implementation: ~March 23

Changes from the workflow side will be to update the DA tag number and update config.anal to add a new historical fix file.

These changes will also need to be incorporated into WCOSS2 transition branches/tags.

------------ For global-workflow CM ------------

- [x] Create release/gfs.v16.1.6 branch
- [x] Create hand-off tag (EMC-v16.1.6)
- [x] CDF submitted to NCO
- [x] Merge release/gfs.v16.1.6 branch into operations branch
- [x] Tag operations branch (NCO-v16.1.6): https://github.com/NOAA-EMC/global-workflow/releases/tag/NCO-v16.1.6
- [x] Release v16.1.6 tag in global-workflow: https://github.com/NOAA-EMC/global-workflow/releases/tag/NCO-v16.1.6
- [x] Announce implementation to glopara-announce listserv

**Comment by KateFriedman-NOAA** [comment]
From GSI issue:
```
CDF needs to be submitted by March 1st. Version number will likely be v16.1.6.
```

**Comment by KateFriedman-NOAA** [comment]
Created new branch `release/gfs.v16.1.6` off of `operations` branch for this update.

**Comment by KateFriedman-NOAA** [comment]
Release notes document created and ready for details to be added:
https://docs.google.com/document/d/1q3iIVO4c7dbOCbgRd5fjs6b84J8UJ9b-I1lY4XwDhbE/edit#

**Comment by CatherineThomas-NOAA** [comment]
The release branch release/gfs.v16.1.6 was updated to point to the v16.1.6 DA tag.  Note that the new DA tag has not been cut yet.

**Comment by CatherineThomas-NOAA** [comment]
The GSI release branch release/gfsda.v16.1.6 was tagged as [gfsda.v16.1.6](https://github.com/NOAA-EMC/GSI/releases/tag/gfsda.v16.1.6) at [7c0e408](https://github.com/NOAA-EMC/GSI/commit/7c0e40810a2405928912364a0c16232db78f2246).

**Comment by KateFriedman-NOAA** [comment]
Cut hand-off tag [EMC-v16.1.6](https://github.com/NOAA-EMC/global-workflow/releases/tag/EMC-v16.1.6).

**Comment by CatherineThomas-NOAA** [comment]
The [EMC-v16.1.6](https://github.com/NOAA-EMC/global-workflow/releases/tag/EMC-v16.1.6) tag has been delivered to NCO.

**Comment by WalterKolczynski-NOAA** [comment]
Is this still waiting on something?

**Comment by CatherineThomas-NOAA** [comment]
@WalterKolczynski-NOAA  Nothing from EIB at the moment.  I'm working with the SPA to schedule the parallel test and implementation date.  I'll update when I have that information.

After implementation, EIB will need to merge these changes back to the operations branch and create an NCO tag, as described in the checklist, but nothing to do for now.

**Comment by KateFriedman-NOAA** [comment]
@WalterKolczynski-NOAA What Cathy said...this issue will close with the PR that merges `release/gfs.v16.1.6` into the `operations` branch right after implementation. Will cut the `NCO-v16.1.6` off the operations branch as the last step.

**Comment by CatherineThomas-NOAA** [comment]
Data flow begins on March 16th.  A single cycle test for both GFS and GDAS will be run on March 17th at 12z.  Implementation is tentatively scheduled for March 29th 12z.

**Comment by WalterKolczynski-NOAA** [comment]
I just wanted to make sure we couldn't close it yet after I saw the merge.

**Comment by CatherineThomas-NOAA** [comment]
GFS v16.1.6 is getting an additional change to accompany a change in obsproc.  See GSI Issue [#333](https://github.com/NOAA-EMC/GSI/issues/333).

The release notes and a config.anal comment in release/gfs.v16.1.6 have been updated to reflect this change

**Comment by KateFriedman-NOAA** [comment]
New tag [EMC-v16.1.6.1](https://github.com/NOAA-EMC/global-workflow/releases/tag/EMC-v16.1.6.1) has been cut for hand-off to NCO.

**Comment by KateFriedman-NOAA** [comment]
New tag [EMC-v16.1.6.2](https://github.com/NOAA-EMC/global-workflow/releases/tag/EMC-v16.1.6.2) has been cut for hand-off to NCO. Includes release branch fix to GSI submodule command and associated release notes update for new tag name.

**Comment by CatherineThomas-NOAA** [comment]
Parallel tests for GFS v16.1.6 were run on 2022031618 - 2022031706 and 2022032112 - 2022032118.  The first test included the vadwnd changes and the increased Spire counts but the GeoOptics data were not available yet.  The second test included the GeoOptics in addition to the other changes.

Evaluation of the test can be found [here](https://docs.google.com/presentation/d/1lje5x6O-rogvNlcetLw82Hs3HZ-L726TLYUmCMfh8sQ/edit?usp=sharing).  Results are as expected with the new GeoOptics data being of similarly quality as DO-2.

**Comment by KateFriedman-NOAA** [comment]
From March 25th RFC memo:

```
RFC 9296 - On WCOSS, update the GFS to v16.1.6 to turn on the active assimilation of GeoOptics (radio occultation)
data. A change is also needed in the ‘global_convinfo.txt’ file to accompany a change in the observation processing
(obsproc_global.v3.4.3) for vadwnd data. To be implemented on March 29 at 1430Z.
```

**Comment by CatherineThomas-NOAA** [comment]
Implementation delayed due to CWD.  Currently planned for 12z April 4th.

**Comment by KateFriedman-NOAA** [comment]
CWD ended. Implementation moved up today (3/31) 12z.

**Comment by KateFriedman-NOAA** [comment]
GFSv16.1.6 implemented into operations on WCOSS-Dell yesterday during the 12z cycle. All stakeholders (including @CatherineThomas-NOAA) confirmed that 12z outputs looked good and the implementation occurred correctly.

**Comment by KateFriedman-NOAA** [comment]
New tag of `operations` branch after merging in v16.1.6 updates has been made: [NCO-v16.1.7](https://github.com/NOAA-EMC/global-workflow/releases/tag/NCO-v16.1.6)

The `release/gfs.v16.1.6` branch has been deleted post-PR.

**Comment by KateFriedman-NOAA** [comment]
Released tag via global-workflow: https://github.com/NOAA-EMC/global-workflow/releases/tag/NCO-v16.1.6

**Comment by KateFriedman-NOAA** [comment]
All tasks for this v16.1.6 upgrade have been completed. Many thanks to all involved!

Closing this issue.
