### ISSUE TITLE
Wired personal location for CPCGAUGE in exgdas_atmos_gldas.sh

### ISSUE THREAD

**Issue by lgannoaa** [NOAA-EMC/global-workflow#662]
In NCO wcoss2 log /lfs/h1/ops/prod/output/20220222/gdas_atmos_gldas shown 2 issues:
1. CPCGAUGE=/lfs/h2/emc/global/noscrub/Kate.Friedman/dump
2. [$HOMEgfs/ush/gldas_forcing.sh line (46-56)](https://github.com/NOAA-EMC/GLDAS/blob/master/ush/gldas_forcing.sh#L46-L56)

```
cpc_precip="PRCP_CU_GAUGE_V1.0GLB_0.125deg.lnx.$sdate.RT"
if [ $RUN_ENVIR = "emc" ] && [ $sdate -gt $bdate ]; then
    cpc_precip="PRCP_CU_GAUGE_V1.0GLB_0.125deg.lnx.$sdate.RT_early"
fi
cpc=$pathp1/$cpc_precip
if [ ! -s $cpc ]; then cpc=$pathp2/$cpc_precip ; fi
if [ $RUN_ENVIR = "nco" ]; then cpc=$pathp2/$cpc_precip ; fi
if [ ! -s $cpc ]; then
 echo "WARNING: GLDAS MISSING $cpc, WILL NOT RUN."
 exit 3
fi
```

Contain the following design issues:
1. cpc_precip should be configured from config file instead of gldas_forcing.sh script
2. `$RUN_ENVIR = "emc"` condition should be evaluated up on config file level.
3. `cpc_precip=PRCP_CU_GAUGE_V1.0GLB_0.125deg.lnx.$sdate.RT_early` was wired in without exception handling
    This file does not exist in that personal area on every PDY. Therefore, exception handling should be in place.
4. Line 51 should only evaluate file once based on both environment and file location.

**Expected behavior**

In NCO run, log file should not have personal location in default.

**Current behavior**

In NCO log file: `/lfs/h1/ops/prod/output/20220222/gdas_atmos_gldas_00.o2627060` line 11174

```0.079 + [ ! -s /lfs/h2/emc/global/noscrub/Kate.Friedman/dump/gdas.20220219/00/PRCP_CU_GAUGE_V1.0GLB_0.125deg.lnx.20220219.RT ]```

A production job should not have any action to evaluate a personal file.

**Machines affected**

**To Reproduce**

**Context**

**Detailed Description**

**Additional Information**

**Possible Implementation**

**Comment by WalterKolczynski-NOAA** [comment]
Since this script is controlled by gldas, an issue should be opened there as well.

**Comment by KateFriedman-NOAA** [comment]
@WeiWei-NCO FYI

**Comment by WalterKolczynski-NOAA** [comment]
This may need to be two separate issues, one for the CPCGAUGE issue and one for the error checking.

**Comment by KateFriedman-NOAA** [comment]
I also need to update the DMPDIR path for WCOSS2 to point to the group account and not my personal area (forgot to do). I could fold that into PR #663. I need to create the emc.global dump folder and symlink it to my space for now to not break things.

**Comment by KateFriedman-NOAA** [comment]
The CPCGAUGE file from the GDA isn't actually getting copied in (from what I see in the gldas logs on Dogwood) so this is just seeing the path setting that will be used for dev runs being observed but then overwritten by the ops path.

I don't think the GLDAS issue is about the wired personal location. Please update that issue to correct it @lgannoaa . The personal GDA path came from the workflow side and is getting fixed.

**Comment by lgannoaa** [comment]
@KateFriedman-NOAA 
The design issues session above has outlined issue with: 
1. Wire the cpc_precip 
2. Exception handling
3. Where the environment and assignment should be (in config file). 

Therefore, maybe the gldas package should be modified to fix the design issue. I also created a gldas issue for reference purpose.

**Comment by KateFriedman-NOAA** [comment]
> 1. CPCGAUGE=/lfs/h2/emc/global/noscrub/Kate.Friedman/dump

Have fixed this in PR #663. The dev paths for `BASE_GIT`, `BASE_SVN` and `DMPDIR` now point to the emc.global group account space on WCOSS2 (as it should) and not a personal account anymore.

**Comment by KateFriedman-NOAA** [comment]
> Therefore, maybe the gldas package should be modified to fix the design issue. I also created a gldas issue for reference purpose.

Not denying that...I said the wired path problem was not on GLDAS's end and doesn't need to be addressed by them. That is now fixed in `feature/ops-wcoss2` via PR #663 commits.

Please address any other relevant issues in this now with the GLDAS folks, thanks!

**Comment by lgannoaa** [comment]
I will be happy to work with GLDAS folks to address it.

**Comment by KateFriedman-NOAA** [comment]
@WeiWei-NCO is the noted error handling insufficiency something NCO would like fixed for GFSv16.2.0? If so, we'll need to get that sorted ASAP before I tag the GFS for you. From what I see in the GLDAS logs the correct CPCGAUGE file is being used (copied into rundir) so it's just a matter of beefing up the error handling (particularly for the dev side of things when we use the global dump archive "_early" version copy). 

The NCO-mode checks appear to be getting the correct copy of the file. Here is the actual copy command for the CPC GAUGE file from last night's 00z cycle gldas log:

```
> grep PRCP_CU_GAUGE /lfs/h1/ops/prod/output/20220222/gdas_atmos_gldas_00.o2627060 | 
grep "cp "
3.306 + cp /lfs/h1/ops/prod/dcom/20220219/wgrbbul/cpc_rcdas/PRCP_CU_GAUGE_V1.0GLB_0.125deg.lnx.20220219.RT /lfs/f1/ops/prod/tmp/gdas_atmos_gldas_00.2627060.dbqs01/force/cpc.20220219/.
11.520 + cp /lfs/h1/ops/prod/dcom/20220220/wgrbbul/cpc_rcdas/PRCP_CU_GAUGE_V1.0GLB_0.125deg.lnx.20220220.RT /lfs/f1/ops/prod/tmp/gdas_atmos_gldas_00.2627060.dbqs01/force/cpc.20220220/.
```

**Comment by WeiWei-NCO** [comment]
> @WeiWei-NCO is the noted error handling insufficiency something NCO would like fixed for GFSv16.2.0? If so, we'll need to get that sorted ASAP before I tag the GFS for you. From what I see in the GLDAS logs the correct CPCGAUGE file is being used (copied into rundir) so it's just a matter of beefing up the error handling (particularly for the dev side of things when we use the global dump archive "_early" version copy).
> 
> The NCO-mode checks appear to be getting the correct copy of the file. Here is the actual copy command for the CPC GAUGE file from last night's 00z cycle gldas log:
> 
> ```
> > grep PRCP_CU_GAUGE /lfs/h1/ops/prod/output/20220222/gdas_atmos_gldas_00.o2627060 | 
> grep "cp "
> 3.306 + cp /lfs/h1/ops/prod/dcom/20220219/wgrbbul/cpc_rcdas/PRCP_CU_GAUGE_V1.0GLB_0.125deg.lnx.20220219.RT /lfs/f1/ops/prod/tmp/gdas_atmos_gldas_00.2627060.dbqs01/force/cpc.20220219/.
> 11.520 + cp /lfs/h1/ops/prod/dcom/20220220/wgrbbul/cpc_rcdas/PRCP_CU_GAUGE_V1.0GLB_0.125deg.lnx.20220220.RT /lfs/f1/ops/prod/tmp/gdas_atmos_gldas_00.2627060.dbqs01/force/cpc.20220220/.
> ```


It looks to be an easy fix...just $CPCGAUGE in /scripts/exgdas_atmos_gldas.sh.  (?)

If so, we may want to fix this issue now in v16.2.0.

**Comment by HelinWei-NOAA** [comment]
> I will be happy to work with GLDAS folks to address it.

@lgannoaa Thanks. Can you provide me with your proposed modifications?

**Comment by KateFriedman-NOAA** [comment]
@lgannoaa My bad, you're right, I see the wired personal location in `exgdas_atmos_gldas.sh`. It was also set in our setup scripts so that's fixed now too. Thanks!

@HelinWei-NOAA Please [change line 31](https://github.com/NOAA-EMC/GLDAS/blob/master/scripts/exgdas_atmos_gldas.sh#L31) in `exgdas_atmos_gldas.sh` from:

```
  export CPCGAUGE=${CPCGAUGE:-/lfs/h2/emc/global/noscrub/Kate.Friedman/dump}
```

...to:
```
  export CPCGAUGE=${CPCGAUGE:-/lfs/h2/emc/global/noscrub/emc.global/dump}
```

The WCOSS-Dell version also pointed to the GDA there so this update will use the new WCOSS2 GDA path via a non-personal location (emc.global group account). This `CPCGAUGE` variable will never be used in ops though (only dev runs) because of [this line](https://github.com/NOAA-EMC/GLDAS/blob/master/ush/gldas_forcing.sh#L52):
```
if [ $RUN_ENVIR = "nco" ]; then cpc=$pathp2/$cpc_precip ; fi
```
...which uses [this version of the file from DCOM](https://github.com/NOAA-EMC/GLDAS/blob/master/ush/gldas_forcing.sh#L44) (correct):
```
pathp2=$DCOMIN/$sdate/wgrbbul/cpc_rcdas
```

@WeiWei-NCO Is updating the `CPCGAUGE` line identified above sufficient for v16.2.0? @lgannoaa can work with @HelinWei-NOAA to beef up the error-handling in this GLDAS script for future versions...I don't wanna delay the final GFS tag any further at this point since the correct `CPCGAUGE` file is being used in ops without issue currently. Let us know, thanks!

**Comment by WeiWei-NCO** [comment]
> @WeiWei-NCO Is updating the `CPCGAUGE` line identified above sufficient for v16.2.0? @lgannoaa can work with @HelinWei-NOAA to beef up the error-handling in this GLDAS script for future versions...I don't wanna delay the final GFS tag any further at this point since the correct `CPCGAUGE` file is being used in ops without issue currently. Let us know, thanks!

Yes, Kate. We are good with `CPCGAUGE` updated. Thank you all.

**Comment by KateFriedman-NOAA** [comment]
> Yes, Kate. We are good with CPCGAUGE updated. Thank you all.

Great, thanks @WeiWei-NCO !

@HelinWei-NOAA Please make the indicated `CPCGAUGE` default setting update and provide me a new tag for GFSv16.2.0. We need to cut the final GFS tag from global-workflow ASAP so please provide the tag today so we can proceed with that final tag. Thanks a bunch!

Please then work with @lgannoaa on beefing up the error-handling in those GLDAS scripts. Thanks!

**Comment by HelinWei-NOAA** [comment]
@KateFriedman-NOAA Here is the [new tag](https://github.com/NOAA-EMC/GLDAS/releases/tag/gldas_gfsv16_release.v.2.0.0)

Thanks.
> @HelinWei-NOAA Please make the indicated `CPCGAUGE` default setting update and provide me a new tag for GFSv16.2.0. We need to cut the final GFS tag from global-workflow ASAP so please provide the tag today so we can proceed with that final tag. Thanks a bunch!

**Comment by KateFriedman-NOAA** [comment]
> Here is the [new tag](https://github.com/NOAA-EMC/GLDAS/releases/tag/gldas_gfsv16_release.v.2.0.0)

Thanks for the quick action @HelinWei-NOAA !

**Comment by lgannoaa** [comment]
@HelinWei-NOAA 
Please take a look at my solution. 
File modified:
/lfs/h2/emc/global/noscrub/Lin.Gan/git/feature-ops-wcoss2/ush/gldas_forcing.sh (modify application logic for path assignment)
/lfs/h2/emc/global/noscrub/Lin.Gan/git/feature-ops-wcoss2/scripts/exgdas_atmos_gldas.sh (remove hardwired personal name for CPCGAUGE assignment)
/lfs/h2/emc/global/noscrub/Lin.Gan/git/feature-ops-wcoss2/parm/config/config.gldas (Fix CPCGAUGE assignment for NCO -- @WeiWei-NCO Please note that your config.base has no DMPDIR. Hence the need for this fix.)

Test log:
/lfs/h2/emc/ptmp/Lin.Gan/ecfops/com/output/prod/today/gdas_atmos_gldas_00.o2721243

**Comment by lgannoaa** [comment]
Closing the issue.

**Comment by WalterKolczynski-NOAA** [comment]
Please do not close issues while the PR fixing them is still pending.

**Comment by lgannoaa** [comment]
@WalterKolczynski-NOAA This issue is closed because PR and Tag is accepted by customer.
