### ISSUE TITLE
Do I need to use /scratch1/NCEPDEV/global?

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/global-workflow#67]
I generated an experiment and see that config.base sets several directories to ` /scratch1/NCEPDEV/global` like `DMPDIR`, `HOMEDIR`, `base_svn`, and `base_git`.

I don't have write access to `global`. Is that a problem? Should I just set `HOMEDIR` and `DMPDIR` to somewhere else?

**Comment by KateFriedman-NOAA** [comment]
For things like DMPDIR, BASE_GIT, and BASE_SVN you want to leave those as is. You should be able to read from those locations (regardless of group access) and those values shouldn't be changed as they are areas for all global users to read from (e.g. DMPDIR is the global dump archive which houses global observation data for cycling the FV3GFS and BASE_GIT[SVN] are for installations that users don't need to build themselves and which are provided in those group account installation areas).

> I don't have write access to global. Is that a problem? Should I just set HOMEDIR and DMPDIR to somewhere else?

HOMEDIR and the other variables under the "# USER specific paths" section are for you to change based on your group access. You should be a part of the global group, we need to get you added. @arunchawla-NOAA I think we need you for that. Kyle needs to be added to the global group on the RDHPCS systems. Thanks!

**Comment by KateFriedman-NOAA** [comment]
@kgerheiser Has this been resolved?

**Comment by kgerheiser** [comment]
I'll call it resolved. I haven't been added to the global group yet, but I was able to change the default directories

**Comment by KateFriedman-NOAA** [comment]
@kgerheiser Gotcha, ping @arunchawla-NOAA through email about global group access on Hera.

**Comment by arunchawla-NOAA** [comment]
global is a project on HERA. Open a request for access to that project on
AIM. It will get routed through to Vijay
---------------------------------------------------------------
Arun Chawla
Chief
Engineering & Implementation Branch
Room 2083
National Center for Weather & Climate Prediction
5830 University Research Court
College Park, MD 20740
Phone: 301-683-3740
Mobile: 240-564-5675
     Fax: 301-683-3703
------------------------------------------------------------

**Comment by kgerheiser** [comment]
@arunchawla-NOAA 

Gotcha
