### ISSUE TITLE
Implementation of EFSOI in global-workflow develop

### ISSUE THREAD

**Issue by AndrewEichmann-NOAA** [NOAA-EMC/global-workflow#673]
**Description**

This is an implementation in global-workflow of Ensemble Forecast Sensitivity to Observation Impacts (EFSOI), a method to determine the positive or negative impact of observations assimilated for the initial conditions for a forecast. 

At the time of this writing most of the necessary code is in the GSI master branch.

**Requirements**

When switched on at the time of workflow generation (running setup_workflow.py), the experiment will have the extra workflow components and tasks to apply the EFSOI calculation and generate a file with the sensitivities of the observations assimilated by GDAS, and run them all successfully.

The implementation has been developed with the global-workflow develop branch and kept up-do-date with the same, and so should requires UFS, GSI, and their dependencies. No additional modules are required. As it is in the current (as of this writing) hash of GSI, the GSI would require the checkout of the master branch, or at least a more recent hash than is currently used in global-workflow develop, before compiling it.

**Acceptance Criteria (Definition of Done)**

When a clone of global-workflow develop can run EFSOI successfully with minimal intervention (switching on before workflow generation, and at most the change of GSI hash).

**Dependencies**

Files to be added: 
config files in parm/config for additional tasks
rocoto scripts in jobs/rocoto for additional tasks

Files to be modified:
env/*env files for additional tasks
parm/config/config.resources for additional tasks
parm/config/config.base.emc.dyn for addition of EFSOI option
parm/config/config.earc for specification of time to sweep EFSOI files
sorc/link_workflow.sh to link additional files from GSI
ush/forecast_predet.sh for if/then block to work with efsoi directory tree instead of enkf
ush/hpssarch_gen.sh for saving EFSOI files
ush/rocoto/setup_workflow.py for generation workflow with EFSOI tasks 
and .gitignore for the files in jobs and scripts that are linked from GSI

These files are intended to be submitted piecewise in multiple pull requests to allow for relaxed review.

**Comment by AndrewEichmann-NOAA** [comment]
@CatherineThomas-NOAA and @KateFriedman-NOAA suggested for review

**Comment by AndrewEichmann-NOAA** [comment]
See also closed issues https://github.com/NOAA-EMC/global-workflow/issues/925 and https://github.com/NOAA-EMC/global-workflow/issues/478

**Comment by aerorahul** [comment]
This capability is now in a frozen branch in global-workflow https://github.com/NOAA-EMC/global-workflow/tree/feature/efsoi
