### ISSUE TITLE
undefined variable in ush/forecast_postdet.sh

### ISSUE THREAD

**Issue by jkhender** [NOAA-EMC/global-workflow#675]
In line 271 of forecast_postdet.sh, $FV3INP is undefined so the CCN_ACTIVATE.BIN file does not get copied to $RUNDIR. 

$NCP $FV3INP/CCN_ACTIVATE.BIN  CCN_ACTIVATE.BIN

**Expected behavior**

CCN_ACTIVATE.BIN file gets copied to $RUNDIR.

**Current behavior**

file does not get copied.

error message in gfsfcst.log:
/bin/cp: cannot stat '/CCN_ACTIVATE.BIN': No such file or directory

**Machines affected**

hera

**To Reproduce**

run gfsfcst task with Thompson microphysics  (imp_physics=8)

**Additional Information**

There are also 2 sections of code that do the same thing. Lines 269-277 copy the files to $RUNDIR.  Lines 528-533 make links to the files. They could be merged together since the GSD suites use Thompson microphysics. 

**lines 269-277** 
269   # copy CCN_ACTIVATE.BIN for Thompson microphysics
270   if [ $imp_physics -eq 8 ]; then
271     $NCP $FV3INP/CCN_ACTIVATE.BIN  CCN_ACTIVATE.BIN
272     ####
273     $NCP $FIX_AM/freezeH2O.dat .
274     $NCP $FIX_AM/qr_acr_qg.dat .
275     $NCP $FIX_AM/qr_acr_qs.dat .
276     sleep 60
277   fi

**lines 528-533**
528   if [ "$CCPP_SUITE" = 'FV3_GSD_v0' -o "$CCPP_SUITE" = 'FV3_GSD_noah' ]; then
529     $NLN $FIX_AM/CCN_ACTIVATE.BIN  CCN_ACTIVATE.BIN
530     $NLN $FIX_AM/freezeH2O.dat  freezeH2O.dat
531     $NLN $FIX_AM/qr_acr_qg.dat  qr_acr_qg.dat
532     $NLN $FIX_AM/qr_acr_qs.dat  qr_acr_qs.dat
533   fi

**Possible Implementation**

File is located in $FIX_AM, so copy/link the file from there.

$NCP $FIX_AM/CCN_ACTIVATE.BIN .

**Comment by lgannoaa** [comment]
Would you please update your copy of the global-workflow 9d002390. Run a test to confirm this issue still exist? Looking at this version of the code, the place for linking CCN_ACTIVATE.BIN exists. If your new test has the same error, please let me know where is your HOMEgfs, ecpdir, COM, and log. I will be happy to take a look.
Pending for reply from @jkhender to proceed.

**Comment by jkhender** [comment]
@lgannoaa  The updated workflow has corrected the issue.  There is still a duplicate section of the code (lines 507-512) that can be removed. 

  if [ "$CCPP_SUITE" = 'FV3_GSD_v0' -o "$CCPP_SUITE" = 'FV3_GSD_noah' ]; then
    $NLN $FIX_AM/CCN_ACTIVATE.BIN  CCN_ACTIVATE.BIN
    $NLN $FIX_AM/freezeH2O.dat  freezeH2O.dat
    $NLN $FIX_AM/qr_acr_qg.dat  qr_acr_qg.dat
    $NLN $FIX_AM/qr_acr_qs.dat  qr_acr_qs.dat
  fi
