### ISSUE TITLE
Update values in parm/parm_fv3diag/field_table_gsd and rename file

### ISSUE THREAD

**Issue by jkhender** [NOAA-EMC/global-workflow#676]
**Expected behavior**

Default values for ice_nc, rain_nc, water_nc, sgs_tke variables need to change to 0.0

**Current behavior**

Default values for ice_nc, rain_nc, water_nc, sgs_tke variables are set to 1.e30

**Machines affected**

hera

**To Reproduce**

run gfsfcst with GSL suite and old field_table values with UFS version newer than 19Oct2021

**Context**

the values in field_table_gsd were updated in ufs-community/ufs-model  PR 870 19Oct21
field_table_gsd was renamed to field_table_thompson_aero_tke in ufs-community/ufs-model PR 937  13Dec21

**Detailed Description**

rename parm/parm_fv3diag/field_table_gsd to parm/parm_fv3diag/field_table_thompson_aero_tke
update ice_nc, rain_nc, water_nc, sgs_tke default values to 0.0

**Comment by lgannoaa** [comment]
@jkhender I will do an update on Hera for you to test. After the successful testing, I will do the PR. Is that ok with you?

**Comment by jkhender** [comment]
@lgannoaa  Yes, that sounds fine with me.

**Comment by lgannoaa** [comment]
@jkhender, 
Please use the following as HOMEgfs and proceed with your test.
HOMEgfs:/scratch1/NCEPDEV/global/Lin.Gan/git/issue-676
git status
 deleted:    parm/parm_fv3diag/field_table_gsd
 new file:   parm/parm_fv3diag/field_table_thompson_aero_tke

**Comment by jkhender** [comment]
In ufs-community/ufs-model PR 937 (13Dec21), the GSD diag tables were also renamed. 

diag_table_gsd was renamed to diag_table_rap_noah
diag_table_gsd_ruc was renamed to diag_table_rap_ruc

They have also been updated, so if you could copy the new files from your checkout of ufs_model.fd to parm/parm_fv3diag?

1) in parm/parm_fv3diag, delete these files:
     diag_table_da_gsd
     diag_table_gsd
     diag_table_gsd_ruc

2) copy **diag_table_rap_noah** from /scratch1/NCEPDEV/global/Lin.Gan/git/issue-676/sorc/ufs_model.fd/tests/parm/diag_table

3) copy **diag_table_rap_ruc** from /scratch1/NCEPDEV/global/Lin.Gan/git/issue-676/sorc/ufs_model.fd/tests/parm/diag_table

4) in parm/parm_fv3diag, copy **diag_table_rap_noah** to **diag_table_da_rap_noah**

Let me know if you have any questions.

Thanks.

**Comment by jkhender** [comment]
I mistyped.  It should be this instead.

diag_table_gsd_ruc was renamed to diag_table_rap

3. copy **diag_table_rap** from /scratch1/NCEPDEV/global/Lin.Gan/git/issue-676/sorc/ufs_model.fd/tests/parm/diag_table

**Comment by jkhender** [comment]
@lgannoaa  I made the following tests on hera.

HOMEgfs:  /scratch1/BMC/gsd-fv3-dev/Judy.K.Henderson/test/issue676

(1)
EXPDIR:   /scratch1/BMC/gsd-fv3-dev/Judy.K.Henderson/test/issue676/FV3GFSwfm/old_gsd
ROTDIR:  /scratch1/BMC/gsd-fv3-dev/Judy.K.Henderson/test/issue676/FV3GFSrun/old_gsd

04/19/22 crashed using parm/parm_fv3diag/field_table_gsd

(2)
EXPDIR:   /scratch1/BMC/gsd-fv3-dev/Judy.K.Henderson/test/issue676/FV3GFSwfm/aero_tke
ROTDIR:  /scratch1/BMC/gsd-fv3-dev/Judy.K.Henderson/test/issue676/FV3GFSrun/aero_tke

04/19/22 ran successfully using  parm/parm_fv3diag/field_table_thompson_aero_tke

I used UFS branch from NOAA-GSL/ufs-weather-model, global-24Feb2022 tag, for experiments (1) and (2) using CCPP suite FV3_RAP_noah_sfcdiff_unified_ugwp.

I also did a 3rd experiment where I tried using tag Prototype-P8b for UFS with the updated field table, parm/parm_fv3diag/field_table_thompson_aero_tke, for 04/20/22, but the model crashed with a namelist issue.

1150: forrtl: severe (19): invalid reference to variable in NAMELIST input, unit -5, file Internal Formatted NML Read, line -1, position 21

**Comment by lgannoaa** [comment]
Thank you for let me know that your testing for this change is successful. I will create a PR for it.
