### ISSUE TITLE
build of March 10 develop hash failing in GSI

### ISSUE THREAD

**Issue by AndrewEichmann-NOAA** [NOAA-EMC/global-workflow#683]
**Expected behavior**

build_all.sh completes on dell with March 10 (hash d758e8b227fca7b5a3320adc43c29ba492c3bfe9) global-workflow develop

**Current behavior**

build_all.sh fails in GSI:

> [Andrew.Eichmann@v72a1 sorc]$ sh build_all.sh 
> Creating ../exec folder
>  .... Building WW3 pre and post execs .... 
>  .... Building forecast model .... 
>  .... Building gsi .... 
> Fatal error in building gsi.
> The log file is in /gpfs/dell2/emc/modeling/noscrub/Andrew.Eichmann/fv3gfs/develop/global-workflow/sorc/logs/build_gsi.log
>  .... Building ncep_post .... 
>  .... Building ufs_utils .... 
>  .... Building gldas .... 
>  .... Building workflow_utils .... 
>  .... Building gfs_util .... 
> FATAL BUILD ERROR: Please check the log file for detail, ABORT!
> [Andrew.Eichmann@v72a1 sorc]$

build_gsi.log ends with the following:

> Configuring utility in recentersigp.fd
> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> Please set them or make sure they are set and tested correctly in the CMake files:
> FRAMEMODULE
>     linked by target "global_gsi.x" in directory /gpfs/dell2/emc/modeling/noscrub/Andrew.Eichmann/fv3gfs/develop/global-workflow/sorc/gsi.fd/src/gsi
> FRAMEPACK
>     linked by target "global_gsi.x" in directory /gpfs/dell2/emc/modeling/noscrub/Andrew.Eichmann/fv3gfs/develop/global-workflow/sorc/gsi.fd/src/gsi
> IOINT_LIB
>     linked by target "global_gsi.x" in directory /gpfs/dell2/emc/modeling/noscrub/Andrew.Eichmann/fv3gfs/develop/global-workflow/sorc/gsi.fd/src/gsi
> WRFNETCDF_LIB
>     linked by target "global_gsi.x" in directory /gpfs/dell2/emc/modeling/noscrub/Andrew.Eichmann/fv3gfs/develop/global-workflow/sorc/gsi.fd/src/gsi
> 
> -- Configuring incomplete, errors occurred!
> See also "/gpfs/dell2/emc/modeling/noscrub/Andrew.Eichmann/fv3gfs/develop/global-workflow/sorc/gsi.fd/build/CMakeFiles/CMakeOutput.log".

**Machines affected**

WCOSS Venus

**To Reproduce**

I cloned this repo a couple of hours ago, ran checkout.sh and build_all.sh

**Context**

Clone is in /gpfs/dell2/emc/modeling/noscrub/Andrew.Eichmann/fv3gfs/develop/global-workflow

**Comment by KateFriedman-NOAA** [comment]
Your libsrc folder is empty:

```
[Kate.Friedman@v71a1 gsi.fd]$ ll /gpfs/dell2/emc/modeling/noscrub/Andrew.Eichmann/fv3gfs/develop/global-workflow/sorc/gsi.fd/libsrc/
total 0
```

@MichaelLueken-NOAA I was just informed that the libsrc repo was removed (?). How do we support the GSI versions that use libsrc to build? This is going to break most GSI builds now.

**Comment by KateFriedman-NOAA** [comment]
@AndrewEichmann-NOAA @MichaelLueken-NOAA I just cloned g-w develop on WCOSS-Dell and I have files in my gsi.fd/libsrc folder. It's the same version of develop as what Andrew has. @AndrewEichmann-NOAA did you notice any clone issues when checking out the components via checkout.sh?

**Comment by JessicaMeixner-NOAA** [comment]
This is the same issue I had yesterday.  My checkout.sh showed no issues, if I went into gsi itself and did another git submodule update then the libsrc was added and then I could build gsi successfully.

**Comment by RussTreadon-NOAA** [comment]
Make the following change in a Mars clone of global-workflow.    Add `git submodule init` to `sorc/checkout.sh` as shown below
```
     git clone --recursive https://github.com/NOAA-EMC/GSI.git gsi.fd >> ${logdir}/checkout-gsi.log 2>&1
     cd gsi.fd
     git checkout a62dec6
     git submodule init
     git submodule update
     cd ${topdir}
```
With this change, `sorc/gsi.fd/libsrc` is populated.  Subsequent execution of `build_all.sh` successfully built executables in `sorc/gsi.fd`.    

Interestingly, there is no need to add `git submodule init` on Orion.  A fresh clone of global-workflow followed by executing `checkout.sh`, yields a `gsi.fd/libsrc` that is populated with files.   The Orion test uses git version 2.28.0.    

Go back to Mars and note that git is version 1.8.3.1.   `module load git/2.14.3`, remove `gsi.fd`, revert change to `checkout.sh`, and execute `./checkout.sh`.   This time `gsi.fd/libsrc` is populated.    

Seems different versions of git treat submodules differently.

**Comment by KateFriedman-NOAA** [comment]
> Go back to Mars and note that git is version 1.8.3.1. `module load git/2.14.3`...Seems different versions of git treat submodules differently.

That explains why it worked ok for me, I use `git/2.14.3` on WCOSS-Dell. Thanks for sussing that out @RussTreadon-NOAA ! I will update the g-w wiki to advise users to use `git/2.14.3` on the Dells.

**Comment by KateFriedman-NOAA** [comment]
@AndrewEichmann-NOAA Please confirm that using the newer git version results in a complete GSI checkout for you. If so, we can close this. Thanks!

**Comment by RussTreadon-NOAA** [comment]
The default git version on Orion is also 1.8.3.1.    git/2.21.0 and git/2.28.0 are available.   The GSI clone and build were successfully tested with git/2.28.0

**Comment by KateFriedman-NOAA** [comment]
And on Hera the default is `2.18.0`. Good. Looks like we want to advise at least v2+ everywhere. I'll update the wiki to reflect that. Thanks!

**Comment by KateFriedman-NOAA** [comment]
The g-w wiki has been updated to reflect the recommended versions for each tier-1 platform: https://github.com/NOAA-EMC/global-workflow/wiki/HPC-Settings-&-Help#version

**Comment by AndrewEichmann-NOAA** [comment]
@KateFriedman-NOAA fixed! thank you!
