### ISSUE TITLE
Create WCOSS2 cycled ECFLOW workflow

### ISSUE THREAD

**Issue by lgannoaa** [NOAA-EMC/global-workflow#684]
**Description**

This is to document the action and status of the cycled ECFLOW workflow development.
Arun tasked @lgannoaa to create cycled ECFLOW workflow.

This version is ops resolution based on ops GFS currently running on WCOSS2. With the following steps:
- ops gfs,gdas,enkfgdas jobs
- EMC verification jobs
-   gfs vrfy, gdas vrfy, MetPlus jobs, gplots
- EMC archive jobs
-   EMC gfs arch, EMC gdas arch, EMC earc
- Cycle workflow management jobs
-    Manage cycle status and schedule
**Requirements**

Be able to use for running realtime and retro parallel.
**Acceptance Criteria (Definition of Done)**

**Dependencies**

**Comment by lgannoaa** [comment]
@arunchawla-NOAA requested in preparation to run parallel with the dev-v16 branch that includes end to end jobs.
Will commit this ecflow workflow as PRs into the dev-v16 branch

**Comment by lgannoaa** [comment]
Modify checkout and link script to checkout and install ecflow workflow for GFS cycled parallel on WCOSS2
git clone --branch feature/wcoss2_ecf_cycled https://github.com/lgannoaa/ecflow.git

**Comment by lgannoaa** [comment]
Fix config.gldas to allow up level assignment on CPCGAUGE
Add WCOSS2 support to config.metp and config.vrfy

**Comment by lgannoaa** [comment]
Modified JGFS_ATMOS_CYCLONE_TRACKER to enable it for WCOSS2
Add WCOSS2 support to verification and archive jobs arch.sh earc.sh metp.sh vrfy.sh
Modify hpssarch_gen.sh to take log file from jobs

**Comment by lgannoaa** [comment]
Commit to https://github.com/lgannoaa/global-workflow
feature/dev_v16 
92e0f67

**Comment by WalterKolczynski-NOAA** [comment]
Can we close this one?

**Comment by lgannoaa** [comment]
Closing the ticket.
