### ISSUE TITLE
module load failure on WCOSS dell

### ISSUE THREAD

**Issue by AndrewEichmann-NOAA** [NOAA-EMC/global-workflow#685]
**Expected behavior**

Modules load as normal

**Current behavior**

As of Friday, in an experiment that has been running for a couple weeks, all tasks for a particular build of global-workflow immediately encounter the following error: 

> + . /gpfs/dell2/emc/modeling/noscrub/Andrew.Eichmann/fv3gfs/EFSOI-rel/global-workflow/ush/load_fv3gfs_modules.sh
> + ulimit -S -s
> + ulimit_s=unlimited
> Lmod has detected the following error: Cannot load module "upp/10.0.8" without
> these module(s) loaded:
>    bacio w3nco
> 
> While processing the following module(s):
>     Module fullname            Module Filename
>     ---------------            ---------------
>     upp/10.0.8                 /gpfs/dell2/usrx/local/nceplibs/dev/hpc-stack/libs/hpc-stack/modulefiles/mpi/ips/18.0.1.163/impi/18.0.1/upp/10.0.8.lua
>     module_base.wcoss_dell_p3  /gpfs/dell2/emc/modeling/noscrub/Andrew.Eichmann/fv3gfs/EFSOI-rel/global-workflow/modulefiles/module_base.wcoss_dell_p3
> 
> + ulimit -S -s unlimited

**Machines affected**

WCOSS Venus

**To Reproduce**

The rotdir is 
/gpfs/dell1/ptmp/Andrew.Eichmann/baily
expdir:
/gpfs/dell2/emc/modeling/save/Andrew.Eichmann/para/baily
build directory:
/gpfs/dell2/emc/modeling/noscrub/Andrew.Eichmann/fv3gfs/EFSOI-rel/global-workflow

**Context**

The build is based on global-workflow develop from Feb 2 (d7319f19aceca6ae6d7ce9b06c6eb731832d1de1), and a build based on the March 10 update (d758e8b227fca7b5a3320adc43c29ba492c3bfe9) has been working since encountering this problem, but I find no diff between the two in the following files:

ush/load_fv3gfs_modules.sh
modulefiles/workflow_utils.wcoss_dell_p3
modulefiles/modulefile.ww3.wcoss_dell_p3 
modulefiles/module_base.wcoss_dell_p3
modulefiles/module-setup.sh.inc

**Comment by KateFriedman-NOAA** [comment]
@AndrewEichmann-NOAA Can you retry the failing jobs again and report if they still get that error on WCOSS-Dell? The hpc-stack folks found the cause of the issue and made a fix. See the most recent chatter in the #hpc-stack channel of the EMC slackspace for more details...and this hpc-stack issue: https://github.com/NOAA-EMC/hpc-stack/issues/410

**Comment by AndrewEichmann-NOAA** [comment]
@KateFriedman-NOAA Now it gets past that state and fails when it doesn't find setpdy.sh. [EDIT] scratch that - I misread a log file. Back up and running

Thank you for clearing that up - I kind of figured it would be something like this and not a global-workflow bug, and should have mentioned that.
