### ISSUE TITLE
DO_GLDAS=YES requires FHOUT=1

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/global-workflow#695]
GLDAS requires hourly forecast model output from the gdas cycle.   Checks to ensure FHOUT=1 when DO_GLDAS=YES are missing from g-w.     

**Expected behavior**
If FHOUT=1 is a requirement when DO_GLDAS=YES, logic in config.base or workflow generation scripts should ensure this condition is met.

**Current behavior**
FHOUT remains set to 3 if either DOHYBVAR="NO" or l4densvar=".false.".   The gdasgldas job fails because it can not find required hourly model output from the gdas cycle.

**Machines affected**
All platforms which g-w supports.

**To Reproduce**
Set DOHYBVAR="NO" or l4densvar=".false." along with DO_GLDAS="YES" and cycle sufficient days for the 00Z gdasgldas job run.   The job will fail with a message similar to the one below
```
0.022 + [ ! -s /work/noaa/stmp/rtreadon/comrot/prufsda/gdas.20211221/12/atmos/gdas.t12z.sfluxgrbf001.grib2 ]
0.023 + echo 'WARNING: GLDAS MISSING /work/noaa/stmp/rtreadon/comrot/prufsda/gdas.20211221/12/atmos/gdas.t12z.sfluxgrbf001.grib2, WILL NOT RUN.'
WARNING: GLDAS MISSING /work/noaa/stmp/rtreadon/comrot/prufsda/gdas.20211221/12/atmos/gdas.t12z.sfluxgrbf001.grib2, WILL NOT RUN.
0.023 + exit 2
0.104 + err=2
0.104 + export err
0.104 + eval '[[' '$err' '=' 0 ']]'
0.104 + [[ 2 == 0 ]]
0.104 + exit 2
0.711 + status=2
0.711 + [[ 2 -ne 0 ]]
0.711 + exit 2
+ status=2
+ exit 2
```

**Context**
Developers set FHOUT=3 to reduce disk usage unaware of the FHOUT=1 requirement for GLDAS.    This requirement becomes apparent after several days of cycling.   Developers then either need to set DO_GLDAS=NO or rerun gdasfcst and gdaspost for previous cycles with FHOUT=1.

**Detailed Description**
How best to resolve this issue is a question for the GLDAS and g-w teams.  Can GLDAS be generalized to work with forecast model of various intervals?  Given that GLDAS will be phased out in future operational realizations of the GFS this option may not be the best investment of resources.   This is a management question.   IF the FHOUT=1 requirement for DO_GLDAS=YES remains, logic should be added to g-w to ensure developers correctly configure their experiments.

**Additional Information**
None

**Possible Implementation**
The g-w asked that this issue be opened.   They can discuss implementation options with the GLDAS team and management and based on those discussions select a path foward.

**Comment by RussTreadon-NOAA** [comment]
Any updates on this issue?

The following was added to a working copy of `config.base` in a C96L127 parallel running on Orion

```
# run GLDAS to spin up land ICs
export DO_GLDAS="YES"
export gldas_cyc=00

if [ $DO_GLDAS = "YES" ]; then
    export FHOUT=1
fi
```
We also need to resolve g-w issues #622 and #711.

**Comment by KateFriedman-NOAA** [comment]
> Any updates on this issue?

@RussTreadon-NOAA The global-workflow team is oversubscribed right now and is prioritizing WCOSS2 ops and develop branch cycled capability tasks. I will try to take on this issue when able.

> We also need to resolve g-w issues https://github.com/NOAA-EMC/global-workflow/issues/622 and https://github.com/NOAA-EMC/global-workflow/issues/711.

@WalterKolczynski-NOAA is currently actively working on #711 and #622 requires resolution from forecast model developers (who appear to be discussing the issue). I will update fix files and/or scripts as needed when a resolution is determined.

**Comment by RussTreadon-NOAA** [comment]
Developers will need to be aware of these issues and manually patch when they set up experiments.   I set up a new experiment on Orion yesterday and was reminded that I need to add these patches.  

To minimize the number of developer inquiries the g-w team receives you could add the above mentioned issues to the [Common errors, known issues, and their solutions](https://github.com/NOAA-EMC/global-workflow/wiki/Common-errors,-known-issues,-and-their-solutions).   Developers will still contact the g-w team but your reply can be much simpler - refer them to the [wiki](https://github.com/NOAA-EMC/global-workflow/wiki).

**Comment by lgannoaa** [comment]
@RussTreadon-NOAA @KateFriedman-NOAA I will work on this issue and provide a PR with modification.

**Comment by lgannoaa** [comment]
The following exception handling script will be added to the config.base.emc.dyn. A PR will be submitted.

**Comment by WalterKolczynski-NOAA** [comment]
Is this something that is needed for all CDUMPs, or only gdas?

**Comment by RussTreadon-NOAA** [comment]
As currently configured the GLDAS only runs in the GDAS cycle.

**Comment by WalterKolczynski-NOAA** [comment]
But which output files is it using? Trying to determine whether FHOUT needs to be 1 for gfs forecasts.

**Comment by RussTreadon-NOAA** [comment]
A check of the WCOSS2 gdas_atmos_gldas job log files returns
```
Russ.Treadon@clogin04:/lfs/h1/ops/prod/output/20220420> grep "prod/com/gfs/v16.2/gfs" gdas_atmos_gldas_00.o2019502   | wc
      0       0       0
Russ.Treadon@clogin04:/lfs/h1/ops/prod/output/20220420> grep "prod/com/gfs/v16.2/gdas" gdas_atmos_gldas_00.o2019502   | wc                            
   3647   23907  768329
```

**Comment by KateFriedman-NOAA** [comment]
> But which output files is it using? Trying to determine whether FHOUT needs to be 1 for gfs forecasts.

@WalterKolczynski-NOAA The GLDAS ingests gdas outputs only and not gfs. So we only need this for CDUMP=GDAS, so FHOUT.

**Comment by KateFriedman-NOAA** [comment]
More specifically...these files (for 1, 5, 9, and 13 cycles ago):

/lfs/h1/ops/prod/com/gfs/v16.2/gdas.YYYYMMDD/CC/atmos/gdas.tCCz.sfluxgrbf00[1-6].grib2

```
> grep gdas.t18z.sfluxgrbf /lfs/h1/ops/prod/output/20220420/gdas_atmos_gldas_00.o2019502 | grep "gfs/v16
.2" | grep rflux
0.049 + rflux=/lfs/h1/ops/prod/com/gfs/v16.2/gdas.20220416/18/atmos/gdas.t18z.sfluxgrbf001.grib2
0.053 + rflux=/lfs/h1/ops/prod/com/gfs/v16.2/gdas.20220416/18/atmos/gdas.t18z.sfluxgrbf002.grib2
0.057 + rflux=/lfs/h1/ops/prod/com/gfs/v16.2/gdas.20220416/18/atmos/gdas.t18z.sfluxgrbf003.grib2
0.061 + rflux=/lfs/h1/ops/prod/com/gfs/v16.2/gdas.20220416/18/atmos/gdas.t18z.sfluxgrbf004.grib2
0.065 + rflux=/lfs/h1/ops/prod/com/gfs/v16.2/gdas.20220416/18/atmos/gdas.t18z.sfluxgrbf005.grib2
0.069 + rflux=/lfs/h1/ops/prod/com/gfs/v16.2/gdas.20220416/18/atmos/gdas.t18z.sfluxgrbf006.grib2
0.174 + rflux=/lfs/h1/ops/prod/com/gfs/v16.2/gdas.20220417/18/atmos/gdas.t18z.sfluxgrbf001.grib2
0.178 + rflux=/lfs/h1/ops/prod/com/gfs/v16.2/gdas.20220417/18/atmos/gdas.t18z.sfluxgrbf002.grib2
0.182 + rflux=/lfs/h1/ops/prod/com/gfs/v16.2/gdas.20220417/18/atmos/gdas.t18z.sfluxgrbf003.grib2
0.186 + rflux=/lfs/h1/ops/prod/com/gfs/v16.2/gdas.20220417/18/atmos/gdas.t18z.sfluxgrbf004.grib2
0.190 + rflux=/lfs/h1/ops/prod/com/gfs/v16.2/gdas.20220417/18/atmos/gdas.t18z.sfluxgrbf005.grib2
0.194 + rflux=/lfs/h1/ops/prod/com/gfs/v16.2/gdas.20220417/18/atmos/gdas.t18z.sfluxgrbf006.grib2
0.293 + rflux=/lfs/h1/ops/prod/com/gfs/v16.2/gdas.20220418/18/atmos/gdas.t18z.sfluxgrbf001.grib2
0.297 + rflux=/lfs/h1/ops/prod/com/gfs/v16.2/gdas.20220418/18/atmos/gdas.t18z.sfluxgrbf002.grib2
0.301 + rflux=/lfs/h1/ops/prod/com/gfs/v16.2/gdas.20220418/18/atmos/gdas.t18z.sfluxgrbf003.grib2
0.316 + rflux=/lfs/h1/ops/prod/com/gfs/v16.2/gdas.20220418/18/atmos/gdas.t18z.sfluxgrbf004.grib2
0.320 + rflux=/lfs/h1/ops/prod/com/gfs/v16.2/gdas.20220418/18/atmos/gdas.t18z.sfluxgrbf005.grib2
0.324 + rflux=/lfs/h1/ops/prod/com/gfs/v16.2/gdas.20220418/18/atmos/gdas.t18z.sfluxgrbf006.grib2
0.424 + rflux=/lfs/h1/ops/prod/com/gfs/v16.2/gdas.20220419/18/atmos/gdas.t18z.sfluxgrbf001.grib2
0.428 + rflux=/lfs/h1/ops/prod/com/gfs/v16.2/gdas.20220419/18/atmos/gdas.t18z.sfluxgrbf002.grib2
0.432 + rflux=/lfs/h1/ops/prod/com/gfs/v16.2/gdas.20220419/18/atmos/gdas.t18z.sfluxgrbf003.grib2
0.435 + rflux=/lfs/h1/ops/prod/com/gfs/v16.2/gdas.20220419/18/atmos/gdas.t18z.sfluxgrbf004.grib2
0.439 + rflux=/lfs/h1/ops/prod/com/gfs/v16.2/gdas.20220419/18/atmos/gdas.t18z.sfluxgrbf005.grib2
0.443 + rflux=/lfs/h1/ops/prod/com/gfs/v16.2/gdas.20220419/18/atmos/gdas.t18z.sfluxgrbf006.grib2
```
