### ISSUE TITLE
Update 2022 storm names in operations

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#698]
**Description**

Tropical cyclone storm names for the 2022 season are being updated:

1. fix file update: `fix_am/syndat_stmnames`
2. source code update: `sorc/syndat_getjtbul.fd/getjtbul.f`

Version update to v16.1.7. Implementation date TBD.

To-be-done (by @KateFriedman-NOAA if not otherwise noted):

- [x] pull fix file updates into GFSv16 fix set
- [x] create `release/gfs.v16.1.7` branch off `operations` branch (possibly `release/gfs.v16.1.6` branch depending on timing)
- [x] add source code update into `release/gfs.v16.1.7` branch (PR #699)
- [x] test source code update (build) on WCOSS-Dell
- [x] test source code update (build) on WCOSS2
- [x] add release notes to `release/gfs.v16.1.7` branch (@Qingfu-Liu)
- [x] cut `EMC-v16.1.7` tag for CDF
- [x] submit CDF to NCO (@Qingfu-Liu)
- [x] fold updates into `feature/ops-wcoss2` for GFSv16.2.0 WCOSS2 package
- [x] update GFSv16.2.0 install in WCOSS2 ops with v16.1.7 updates (coordinate with @WeiWei-NCO)
- [x] merge `release/gfs.v16.1.7` branch into `operations` branch after implementation (PR #741)
- [x] tag `operations` branch [NCO-v16.1.7](https://github.com/NOAA-EMC/global-workflow/releases/tag/NCO-v16.1.7)
- [x] release v16.1.7 tag via global-workflow
- [x] announce v16.1.7 implementation via glopara-announce listserv

**Comment by KateFriedman-NOAA** [comment]
The GFSv16.1.6 implementation was moved to 3/31 due to CWD so I have cut the new `release/gfs.v16.1.7` branch for this upgrade from the `release/gfs.v16.1.6` soon-to-be-ops branch instead of the `operations` branch.
Will commit changes to this branch: https://github.com/NOAA-EMC/global-workflow/tree/release/gfs.v16.1.7

**Comment by KateFriedman-NOAA** [comment]
@Qingfu-Liu Please prepare release notes for this update and commit them to the `release/gfs.v16.1.7` branch /docs folder via a PR from your fork copy of the branch. You can use the v16.1.6 release notes as the base and then edit it. Thanks!

**Comment by KateFriedman-NOAA** [comment]
Pulled updated code from @Qingfu-Liu into clone of `release/gfs.v16.1.7`:
```
[Kate.Friedman@v71a1 syndat_getjtbul.fd]$ pwd
/gpfs/dell2/emc/modeling/save/Kate.Friedman/git/global-workflow/release-gfs.v16.1.7/sorc/syndat_getjtbul.fd
[Kate.Friedman@v71a1 syndat_getjtbul.fd]$ rsync -azv /gpfs/dell2/emc/modeling/noscrub/Qingfu.Liu/gfs.v16.1.5/sorc/syndat_getjtbul.fd/getjtbul.f .
```
Ran build_tropcy_NEMS.sh on WCOSS-Dell (Venus); here is the snippet for building the `syndat_getjtbul.fd` code:
```
+ cd syndat_getjtbul.fd
+ make clean
rm -f getjtbul.o
+ make -f makefile
ifort    -O3 -g -traceback -assume noold_ldout_format   -c -o getjtbul.o getjtbul.f
ifort     -o syndat_getjtbul getjtbul.o /gpfs/dell1/nco/ops/nwprod/lib/w3nco/v2.0.6/ips/18.0.1/libw3nco_v2.0.6_4.a
+ make install
mv syndat_getjtbul ../../exec/syndat_getjtbul
+ make clean
rm -f getjtbul.o
```

```
[Kate.Friedman@v71a1 release-gfs.v16.1.7]$ pwd
/gpfs/dell2/emc/modeling/save/Kate.Friedman/git/global-workflow/release-gfs.v16.1.7
[Kate.Friedman@v71a1 release-gfs.v16.1.7]$ ll exec/
total 12800
-rwxr-xr-x 1 Kate.Friedman emcmodel 1106528 Mar 29 15:28 supvit
-rwxr-xr-x 1 Kate.Friedman emcmodel  911032 Mar 29 15:28 syndat_getjtbul
-rwxr-xr-x 1 Kate.Friedman emcmodel  977464 Mar 29 15:28 syndat_maksynrc
-rwxr-xr-x 1 Kate.Friedman emcmodel 1867248 Mar 29 15:28 syndat_qctropcy
-rwxr-xr-x 1 Kate.Friedman emcmodel 3556640 Mar 29 15:28 tave.x
-rwxr-xr-x 1 Kate.Friedman emcmodel 3603896 Mar 29 15:28 vint.x
```

**Comment by KateFriedman-NOAA** [comment]
@Qingfu-Liu PR #699 to send in the code update has been initiated. Please review/approve and I'll submit the merge into the auth branch. Thanks!

**Comment by Qingfu-Liu** [comment]
Approved. Two updates: 1) update the tropical storm names for the 2022
hurricane season, 2) update the FORTRAN code to read the new JTWC data
correctly (data format changed).

**Comment by KateFriedman-NOAA** [comment]
@Qingfu-Liu I need you to review and approve the PR, not the issue. Please see https://github.com/NOAA-EMC/global-workflow/pull/699. Thanks! :)

**Comment by Qingfu-Liu** [comment]
Hi Kate,
   I just added a new file:
/gpfs/dell2/emc/modeling/noscrub/Qingfu.Liu/gfs.v16.1.7/docs/Release_Notes.gfs.v16.1.7.txt
It is based on the notes Release_Notes.gfs.v16.1.6.txt
Qingfu

**Comment by Qingfu-Liu** [comment]
Kate,
   How can I check out this new branch? (I can check out other branches
using "git clone", but not this one)
https://github.com/NOAA-EMC/global-workflow/tree/release/gfs.v16.1.7
Thanks.
Qingfu

**Comment by KateFriedman-NOAA** [comment]
@Qingfu-Liu You'll need to have the `release/gfs.v16.1.7` branch in your global-workflow fork. I'll send you an email explaining the process.

**Comment by Qingfu-Liu** [comment]
Thanks!

**Comment by KateFriedman-NOAA** [comment]
Updated `syndat_stmnames` file has been rsync'd into the staged FIX_DIR (`fix_nco_gfsv16/fix_am`) on WCOSS-Dell:
```
> diff /gpfs/dell2/emc/modeling/noscrub/Qingfu.Liu/gfs.v16.1.5/fix_am/syndat_stmnames fix_nco_gfsv16/fix_am/syndat_stmnames
64c64
< NAKRI    FENGSHEN KALMAEGI FUNG-WONGKOTO     NOKAEN   PENHA    NURI
---
> NAKRI    FENGSHEN KALMAEGI FUNG-WONGKOTO     NOKAEN   VONGFONG NURI
66,67c66,67
< NOUL     DOLPHIN  KUJIRA   CHAN-HOM PEILOU   NANGKA   SAUDEL   NARRA
< GAENARI  ATSANI   ETAU     BANG-LANGKROVANH  DUJUAN   SURIGAE  CHOI-WAN
---
> NOUL     DOLPHIN  KUJIRA   CHAN-HOM LINFA    NANGKA   SAUDEL   MOLAVE
> GONI     ATSANI   ETAU     VAMCO    KROVANH  DUJUAN   SURIGAE  CHOI-WAN
```
```
.../noscrub/emc.glopara/git/fv3gfs/fix_nco_gfsv16> pwd
/gpfs/dell2/emc/modeling/noscrub/emc.glopara/git/fv3gfs/fix_nco_gfsv16
.../noscrub/emc.glopara/git/fv3gfs/fix_nco_gfsv16> rsync -azv /gpfs/dell2/emc/modeling/noscrub/Qingfu.Liu/gfs.v16.1.5/fix/fix_am/syndat_stmnames fix_am/syndat_stmnames
```
...and rsync'd to the associated companion FIX_DIRs on supported platforms. 

New tarball of `fix_nco_gfsv16` has been made on HPSS:
/5year/NCEPDEV/emc-global/emc.glopara/fv3fix/fix_nco_gfsv16_20220330.tar

**Comment by KateFriedman-NOAA** [comment]
Also updated `fix_NEW` fix set with updated syndat_stmnames file. Discovered the file in `fix_NEW` was also missing the 2021 update.
```
[ =0 14:01:34 1024 emc.glopara@v72a1 ]
.../noscrub/emc.glopara/git/fv3gfs/fix_NEW> diff /gpfs/dell2/emc/modeling/noscrub/Qingfu.Liu/gfs.v16.1.5/fix/fix_am/syndat_stmnames fix_am/syndat_stmnames
60c60
< JEBI     MANGKHUT BARIJAT  TRAMI    KONG-REY YINXING  TORAJI   MAN-YI
---
> JEBI     MANGKHUT BARIJAT  TRAMI    KONG-REY YUTU     TORAJI   MAN-YI
62,64c62,64
< FRANCISCOCO-MAY   KROSA    BAILU    PODUL    LINGLING KAJIKI   NONGFA
< PEIPAH   TAPAH    MITAG    RAGASA   NEOGURI  BUALOI   MATMO    HALONG
< NAKRI    FENGSHEN KALMAEGI FUNG-WONGKOTO     NOKAEN   PENHA    NURI
---
> FRANCISCOLEKIMA   KROSA    BAILU    PODUL    LINGLING KAJIKI   FAXAI
> PEIPAH   TAPAH    MITAG    HAGIBIS  NEOGURI  BUALOI   MATMO    HALONG
> NAKRI    FENGSHEN KALMAEGI FUNG-WONGKAMMURI  PHANFONE VONGFONG NURI
66,67c66,67
< NOUL     DOLPHIN  KUJIRA   CHAN-HOM PEILOU   NANGKA   SAUDEL   NARRA
< GAENARI  ATSANI   ETAU     BANG-LANGKROVANH  DUJUAN   SURIGAE  CHOI-WAN
---
> NOUL     DOLPHIN  KUJIRA   CHAN-HOM LINFA    NANGKA   SAUDEL   MOLAVE
> GONI     ATSANI   ETAU     VAMCO    KROVANH  DUJUAN   SURIGAE  CHOI-WAN
[ =1 14:01:41 1025 emc.glopara@v72a1 ]
.../noscrub/emc.glopara/git/fv3gfs/fix_NEW> ll fix_am/syndat_stmnames
-rwxr-xr-x 1 emc.glopara emcmodel 4689 Mar 31  2020 fix_am/syndat_stmnames
[ =0 14:01:50 1026 emc.glopara@v72a1 ]
.../noscrub/emc.glopara/git/fv3gfs/fix_NEW> rsync -azv /gpfs/dell2/emc/modeling/noscrub/Qingfu.Liu/gfs.v16.1.5/fix/fix_am/syndat_stmnames fix_am/syndat_stmnames
sending incremental file list
syndat_stmnames

sent 2,093 bytes  received 35 bytes  1,418.67 bytes/sec
total size is 4,689  speedup is 2.20
```

Created new tarball of `fix_NEW` on HPSS: /5year/NCEPDEV/emc-global/emc.glopara/fv3fix/fix_NEW_20220330.tar

**Comment by KateFriedman-NOAA** [comment]
Merged `release/gfs.v16.1.7` into a copy of `feature/ops-wcoss2` on Dogwood:
```
Kate.Friedman@dlogin04:/lfs/h2/emc/global/noscrub/Kate.Friedman/git/feature-ops-wcoss2_sync_v16.1.7/sorc> ll syndat_getjtbul.fd/getjtbul.f
-rwxr-xr-x 1 Kate.Friedman global 8594 Mar 30 15:26 syndat_getjtbul.fd/getjtbul.f
```
...and ran `build_tropcy_NEMS.sh` to confirm updated  `syndat_getjtbul.fd/getjtbul.f` does not break build on WCOSS2. It built without issue:
```
+ cd syndat_getjtbul.fd
+ make clean
rm -f getjtbul.o
+ make -f makefile
ftn -O3 -g -traceback -assume noold_ldout_format   -c -o getjtbul.o getjtbul.f
ftn  -o syndat_getjtbul getjtbul.o /apps/ops/prod/libs/intel/19.1.3.304/w3nco/2.4.1/lib/libw3nco_4.a
+ make install
mv syndat_getjtbul ../../exec/syndat_getjtbul
```
```
Kate.Friedman@dlogin04:/lfs/h2/emc/global/noscrub/Kate.Friedman/git/feature-ops-wcoss2_sync_v16.1.7/sorc> ll ../exec/
total 6962
-rwxr-xr-x 1 Kate.Friedman global 1094808 Mar 30 15:27 supvit
-rwxr-xr-x 1 Kate.Friedman global  939528 Mar 30 15:27 syndat_getjtbul
-rwxr-xr-x 1 Kate.Friedman global  997768 Mar 30 15:27 syndat_maksynrc
-rwxr-xr-x 1 Kate.Friedman global 1796032 Mar 30 15:27 syndat_qctropcy
-rwxr-xr-x 1 Kate.Friedman global 3546664 Mar 30 15:27 tave.x
-rwxr-xr-x 1 Kate.Friedman global 3579840 Mar 30 15:27 vint.x
```

**Comment by KateFriedman-NOAA** [comment]
@Qingfu-Liu I think we are ready to cut the `EMC-v16.1.7` hand-off tag for you to submit in the CDF to NCO. Any final updates for this or may I proceed with cutting the hand-off tag?

**Comment by Qingfu-Liu** [comment]
Kate,
   Just wait, I will double check everything in the tag, and let you
know this afternoon. I think you can set the tag late this afternoon or
tomorrow.
Qingfu

**Comment by KateFriedman-NOAA** [comment]
@Qingfu-Liu Sounds good! Will wait to cut tag until you give me the go-ahead. Thanks!

**Comment by Qingfu-Liu** [comment]
Hi Kate,
   I have double-checked the file "syndat_stmnames" and the FORTRAN code
"getjtbul.f". Everything looks good. You can cut the EMC-v16.1.7 hand-off
tag.
   Thank you very much.
Qingfu

**Comment by KateFriedman-NOAA** [comment]
@Qingfu-Liu The hand-off tag for the CDF to NCO has been cut: [EMC-v16.1.7](https://github.com/NOAA-EMC/global-workflow/releases/tag/EMC-v16.1.7)

**Comment by KateFriedman-NOAA** [comment]
@Qingfu-Liu Please forward me a copy of the CDF email you get from the form after you've submitted it so I have it for my records. Thanks!

**Comment by KateFriedman-NOAA** [comment]
From April 15th, 2022 RFC memo:

```
RFC 9365 - On WCOSS, implement GFS v16.1.7 to update the tropical storm
names for the 2022 hurricane season and implement a syndat_getjtbul code
change for the JTWC tcvital information format change. To be implemented on
April 19 at 1430Z.
```

**Comment by KateFriedman-NOAA** [comment]
Synced `release/gfsv16.1.7` with `operations` branch update for v16.1.6 implementation @ 857c4246.

**Comment by KateFriedman-NOAA** [comment]
Work for this operational upgrade to GFSv16.1.7 is now complete. Closing issue.
