### ISSUE TITLE
eupd tasks intermittently failing on Orion with bus error (with possible resolution)

### ISSUE THREAD

**Issue by AndrewEichmann-NOAA** [NOAA-EMC/global-workflow#708]
**Expected behavior**

eupd completes reliably

**Current behavior**

eupd (using LETKF, not serial filter) fails intermittently in experiment with C384/C192 and 80 ensemble members with the following in stderr:

> srun: error: Orion-03-06: task 30: Bus error
> srun: launch/slurm: _step_signal: Terminating StepId=5076402.1
>   0: slurmstepd: error: *** STEP 5076402.1 ON Orion-03-05 CANCELLED AT 2022-03-31T04:51:05 ***
>  66: forrtl: error (78): process killed (SIGTERM)
>  66: Image              PC                Routine            Line        Source            
>  66: global_enkf.x      0000000000D1339E  Unknown               Unknown  Unknown

**Machines affected**
Orion

**To Reproduce**

rotdir /work2/noaa/stmp/aeichman/comrot/rodeo/
expdir /work/noaa/da/aeichman/para/rodeo

Most of the duplicates you see if you  `ls logs/*/gdaseupd.log*` are examples of this happening, except for 2020123112 when I was trying fixes

**Context**

These errors went unnoticed for a few walltime weeks of this experiment until the past week or two, when the automatic retrys became insufficient and rewinds were required more often. 

**Additional Information**

Thinking this was a system issue I contacted Orion helpdesk, and Jake Frulla offered this (posted with permission):

> When a process inside a job tries to access memory outside what was allocated to that job, the operating system tells your program that address is invalid with the fault "Bus Error". This usually means your job used more memory than it was allocated by Slurm.
> 
> By default, jobs that do not use the --exlusive option will no longer be given all available memory on the node. Standard compute nodes with 192GB memory will allocate 4608 Mb per core in each job allocation. Bigmem compute nodes with 384GB memory will allocate 9472 Mb per core in each job allocation.
> 
> In order to get a whole node while running on less than 40 cores, users must specify the "--exclusive" option in their runscripts or in their salloc/srun commands:
> 
> #SBATCH --exlusive
> 
> or
> 
> $ srun -n 10 -N 1 --exclusive ./example_program
> 
> It looks like you ran on 560 cores across 14 nodes (40 tasks per node). Your job was allocated 4.5GB per task, but the peak memory usage of individual tasks in the job was nearly 6GB (per task).
> 
> You may want to use the bigmem nodes with 384GB memory per node. You can submit to this partition with the parameter --partition=bigmem. You can also consider using more nodes with less tasks per node in order to allocate more of a node's memory per process:
> 
> --nodes=28 --ntasks-per-node=20 --exclusive
> 
> Let me know if you have any more issues after making that recommended adjustment.

**Possible Implementation**

I've changed the assignment for eupd in env/ORION.env from

   ` export APRUN_ENKF="$launcher"`
to
`   export APRUN_ENKF="srun --exclusive  --partition=bigmem -l --export=ALL "`

and in the xml file:

`<!ENTITY RESOURCES_EUPD_GDAS "<nodes>14:ppn=20:tpp=2</nodes>">`

to 

`<!ENTITY RESOURCES_EUPD_GDAS "<nodes>28:ppn=10:tpp=2</nodes>">`

This has made it more reliable, such that rewinds have not been necessary for several days of model time, but the errors do still occur on occasion.

**Comment by WalterKolczynski-NOAA** [comment]
You probably don't need to do both, probably more nodes. Will you have a PR that changes the resources when using LETKF? Or has this already been settled and we can close this issue?

**Comment by AndrewEichmann-NOAA** [comment]
@WalterKolczynski-NOAA I haven't changed this in anything besides the one experiment, and haven't encountered it since, so if nobody has been complaining about LETKF failing on Orion I think it can be closed.
