### ISSUE TITLE
Add a portable way to easily define experiment settings

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#710]
**Description**
Right now, in order to create an experiment that changes much more than the date may require the user to make modifications in several different config files. And to share that experiment with others, it requires providing a list of all those modifications for the second user to then reproduce, or an experiment directory to copy that then still needs to be modified manually for the new user. This makes it difficult to establish multiple standard experiments for different applications and workflow tests.

This capability is a prerequisite for expanding the number of applications global-workflow supports, as well as for providing a standardized testing package for future global-workflow updates.

**Requirements**
- The ability to define an experiment's settings from a single file beyond those that are necessarily user-dependent

**Acceptance Criteria (Definition of Done)**
- A system that meets the requirements above
- Draft case files that defines basic tests for atm-only cycled, atm-only forecast-only, and coupled forecast-only
- Case files for prototype 8b atm-only and full coupled

**Dependencies**
None

**Comment by aerorahul** [comment]
The mechanism to do this has been implemented in the global-workflow through the use of the `--yaml` option to `setup_expt.py`.
A limited set of variables are configurable through this yaml and can be expanded as user requirements grow.
This will mean creating templates `@TEMPLATE_VARIABLE@` in the config file and providing a `default` in the `yaml` file.
Documentation in the global-workflow also needs to be worked on and will be the subject of another issue.
