### ISSUE TITLE
[NCO Bug] Profile `enkf_chgres_recenter_nc.x`

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/global-workflow#713]
**Current behavior**
Runtime variability has been reported in the execution of `enkf_chgres_recenter_nc.x` on WCOSS2.

Difference between slow and fast runs are in the following code sequence.

```
adjust_for_terrain() --> vintg() -> terp3() / bsearch()
```

The slow runs are spending most of the extra time in `terp3` / `bsearch`

Is it possible that, depending on memory allocations in the program, there is uninitialized data causing additional interpolation and/or search cycles?

See pat_report output here
`cactus:/lfs/h2/hpc/support/Peter.Johnsen/4George`

**Expected behavior**
Identify cause of runtime variability and provide an explanation and/or fix.

**Machines affected**
WCOSS2

**Additional Information**
@RussTreadon-NOAA notes:
`enkf_chgres_recenter_nc.x` has passed through the hands of several developers.   We knew `vintg`, specifically `terp3`, was the location of variable run times prior GDIT's reply.   Their pointing specifically to `RSEARCH` (not `bsearch`) is useful.   Comments in `vintg`, `terp3`, and `RSEARCH`  have this code dating back to Mark(?) Iredell in the 1990s.   It seems we do not yet understand why this code, as is, shows run time variability on WCOSS2 but not WCOSS.

**Possible Implementation**
Unknown till investigation is carried out.

**Comment by KateFriedman-NOAA** [comment]
This issue is also documented as the first issue in the "GFS WCOSS2 reset/issue log":
https://docs.google.com/document/d/1v3pNtLJC7XhdeuzUnsCvIWI77QsWHg6pcKkGvJPJvlA/edit?pli=1#heading=h.s8j63b7gjxg2

**Comment by KateFriedman-NOAA** [comment]
@GeorgeVandenberghe-NOAA This is the related global-workflow issue for the runtime variability in the enkf chgres job. Please add details/information that is not already indicated above. Thanks!

**Comment by RussTreadon-NOAA** [comment]
The following EIB suggested tests have been run on Cactus:

**1) recompile enkf_chgres_recenter_nc with debug options and run**
Source code for enkf_chgres_recenter_nc.x was recompiled on Cactus with GSI debug flags

`export FFLAGS="-O0 -qopenmp -traceback -fp-model source -implicitnone -g -debug -ftrapuv -check all,noarg_temp_created -fp-stack-check -fstack-protector -warn all,nointerfaces,noexternal"`

The executable obviously ran longer but successfully completed.

**2) add #PBS -l hyper=true to jgdas_atmos_chgres_forenkf job card**
Even with `hyper=true`, some submissions run long on Cactus.   
```
gdas_atmos_enkf_chgres.o1306277:    resources_used.walltime = 00:04:45
gdas_atmos_enkf_chgres.o1306591:    resources_used.walltime = 00:04:49
gdas_atmos_enkf_chgres.o1306765:    resources_used.walltime = 00:04:48
gdas_atmos_enkf_chgres.o1307032:    resources_used.walltime = 00:04:49
gdas_atmos_enkf_chgres.o1307286:    resources_used.walltime = 00:08:12
gdas_atmos_enkf_chgres.o1307694:    resources_used.walltime = 00:08:10
gdas_atmos_enkf_chgres.o1307738:    resources_used.walltime = 00:07:11
gdas_atmos_enkf_chgres.o1310583:    resources_used.walltime = 00:03:58
gdas_atmos_enkf_chgres.o1311108:    resources_used.walltime = 00:03:57
gdas_atmos_enkf_chgres.o1311432:    resources_used.walltime = 00:03:59
gdas_atmos_enkf_chgres.o1311736:    resources_used.walltime = 00:07:40
gdas_atmos_enkf_chgres.o1312273:    resources_used.walltime = 00:03:58
gdas_atmos_enkf_chgres.o1312838:    resources_used.walltime = 00:04:00
gdas_atmos_enkf_chgres.o1313109:    resources_used.walltime = 00:07:38
gdas_atmos_enkf_chgres.o1313504:    resources_used.walltime = 00:06:12
```

**Comment by KateFriedman-NOAA** [comment]
@GeorgeVandenberghe-NOAA Feel free to use this issue to document investigations for this issue. Thanks!

**Comment by GeorgeGayno-NOAA** [comment]
GDIT rewrote 'rsearch' and 'terp3'.  I tested their update in the 'feature/ops-wcoss2' branch on one canned case. Wall clock time was reduced (408 to 207 seconds). The output files were bit identical.

Should I open a test branch?

**Comment by KateFriedman-NOAA** [comment]
> GDIT rewrote 'rsearch' and 'terp3'. I tested their update in the 'feature/ops-wcoss2' branch on one canned case. Wall clock time was reduced (408 to 207 seconds). The output files were bit identical.

Thanks for this update! This is great to hear! Is the runtime consistent from run to run? I can try it in a cycled plumbing test I have going on Dogwood to further check functionality and runtime.

My vote would be to get this into the `dev_v16` branch and then into the `release/gfs.v16.3.0` branch after that so we can get it into WCOSS2 ops via the GFSv16.3.0 upgrade. @aerorahul @emilyhcliu @arunchawla-NOAA thoughts? This is related to [one of the remaining open issues for the GFS on WCOSS2](https://docs.google.com/document/d/1v3pNtLJC7XhdeuzUnsCvIWI77QsWHg6pcKkGvJPJvlA/edit#heading=h.s8j63b7gjxg2).

**Comment by GeorgeGayno-NOAA** [comment]
> > GDIT rewrote 'rsearch' and 'terp3'. I tested their update in the 'feature/ops-wcoss2' branch on one canned case. Wall clock time was reduced (408 to 207 seconds). The output files were bit identical.
> 
> Thanks for this update! This is great to hear! Is the runtime consistent from run to run? I can try it in a cycled plumbing test I have going on Dogwood to further check functionality and runtime.
> 
> My vote would be to get this into the `dev_v16` branch and then into the `release/gfs.v16.3.0` branch after that so we can get it into WCOSS2 ops via the GFSv16.3.0 upgrade. @aerorahul @emilyhcliu @arunchawla-NOAA thoughts? This is related to [one of the remaining open issues for the GFS on WCOSS2](https://docs.google.com/document/d/1v3pNtLJC7XhdeuzUnsCvIWI77QsWHg6pcKkGvJPJvlA/edit#heading=h.s8j63b7gjxg2).

@KateFriedman-NOAA I ran the test five times on Dogwood. The run times were very consistent -

Original code / Updated code:

1. 397 vs. 229 seconds
2. 373 vs. 207 seconds
3. 378 vs. 227 seconds
4. 414 vs. 206 seconds
5. 334 vs. 185 seconds

Which branch should I update?

**Comment by KateFriedman-NOAA** [comment]
> ran the test five times on Dogwood. The run times were very consistent -

Awesome, thanks for that @GeorgeGayno-NOAA ! Please submit a PR into the `dev_v16` branch and we can discuss in there further as needed. Thanks!

**Comment by KateFriedman-NOAA** [comment]
I've merged the code update into the `dev_v16` branch and then synced that update into the `release/gfs.v16.3.0` branch. Thanks @GeorgeGayno-NOAA !

Are there any more updates for this issue or can we close it now?

**Comment by KateFriedman-NOAA** [comment]
Updated `enkf_chgres_recenter_nc` code has been committed to `develop`, `dev_v16`, and `release/gfs.v16.3.0` branches. Closing this issue now. Reopen as needed. Thanks @GeorgeGayno-NOAA !
