### ISSUE TITLE
err: unbound variable in scripts/exgfs_wave_init.sh

### ISSUE THREAD

**Issue by XianwuXue-NOAA** [NOAA-EMC/global-workflow#714]
**Expected behavior**

gfswaveinit may be failed due to lack of default value for err

**Current behavior**

In scripts/exgfs_wave_init.sh, when use "set -xue", the gfswaveinit task will be failed with error message: "line 234: err: unbound variable"

**Machines affected**

 Venus WCOSS_DELL_P3 and WCOSS_DELL_P35

**To Reproduce**

Line 31, change "set -x" to "set -xue" in  scripts/exgfs_wave_init.sh

**Context**

Add one line to set default value to err, such as: "err=0"

**Comment by KateFriedman-NOAA** [comment]
PR #715 submitted. Closing now.
