### ISSUE TITLE
Creating J jobs for archive

### ISSUE THREAD

**Issue by lgannoaa** [NOAA-EMC/global-workflow#720]
**Description**

Create JJOBs for archive
**Requirements**

The current rocoto workflow run archive and verification jobs using scripts under $HOMEgfs/jobs/rocoto. Manager has requested to create JJOBs for archive and verification jobs. Modify the $HOMEgfs/jobs/rocoto scripts to call the new JJOBs.
**Acceptance Criteria (Definition of Done)**

For workflow to run archive and verification jobs using JJOBs.

Verify jobs will be handled in the issue #235

**Comment by lgannoaa** [comment]
Removing metpg2gl, metppcpl, metpg2ol, and gplots (metplus and gplots) jobs. Because there is a new requirement to have a team discussion to discuss which part of the verification job do we want to run as part of the cycle and which should be run offline by the MEG team #726

**Comment by lgannoaa** [comment]
A rocoto workflow on wcoss2 has been setup to test: the JJOBs for gdas very, gfs very, gdas arch, gfs arch, and enkfgdas earc jobs 
expdir:  /lfs/h2/emc/global/noscrub/Lin.Gan/expdir/rjjobtest
com:     /lfs/h2/emc/ptmp/Lin.Gan/rjjobtest/
log:       /lfs/h2/emc/ptmp/Lin.Gan/rjjobtest/logs/

**Comment by aerorahul** [comment]
Closing as done via #1115
