### ISSUE TITLE
Merge wcoss2 cycled ecflow definition file into dev_v16

### ISSUE THREAD

**Issue by lgannoaa** [NOAA-EMC/global-workflow#721]
**Description**

This merge contains: 
1. The wcoss2 cycled ecflow definition files
2. Without the developer testing COM assignment change to dev_v16 $HOMEgfs/ecf/gfs $HOMEgfs/ecf/gdas and $HOMEgfs/ecf/enkfgdas
3. ecf/include files for developer
4. cycled workflow management jobs

**Requirements**

This is a partial merge for wcoss2 cycled ecflow with:
1. The wcoss2 cycled ecflow definition files
2. ecf/include files for developer
3. cycled workflow management jobs

**Comment by lgannoaa** [comment]
Rahul requested on week of April 10th to create new JJob for ecflow workflow_monitor job. [jobs/JECF_MONITOR](https://github.com/NOAA-EMC/global-workflow/pull/718/files#diff-e46fd1ed752e1a7de8514c28324463de03f7027adfd165d759155743e52512d3) was created.

**Comment by lgannoaa** [comment]
We had a meeting on 2022/04/14 to discuss verification jobs. Rahul decided not to do three metplus and the gplot job at this time. Therefore, these jobs will be removed from this ecflow commit.

**Comment by lgannoaa** [comment]
Add documentation ecflow_dev.md
Remove three metplus and gplot jobs. With new requirement on April 14th, 2022
Modify JECF_MONITOR to remove metplus monitoring.
New commit is done.
PR is now updated.

**Comment by lgannoaa** [comment]
New requirement to modify envir-p1.h to remove archive job related setting
and JECF_MONITOR cleanup

**Comment by WalterKolczynski-NOAA** [comment]
Can this be closed?

**Comment by lgannoaa** [comment]
Closing the ticket.
