### ISSUE TITLE
Merge wcoss2 cycled ecflow developer script with COM path assignment

### ISSUE THREAD

**Issue by lgannoaa** [NOAA-EMC/global-workflow#722]
**Description**

This is to merge those ecflow scripts with developer testing COM assignment change to dev_v16 $HOMEgfs/ecf/gfs $HOMEgfs/ecf/gdas and $HOMEgfs/ecf/enkfgdas

The developer enabled ecflow files - (modify the current dev_v16 with developer testing COM assignment)
It contains 25 *.ecf files that have "EMC developer only" area for COM path assignments to allow developer to run ecflow workflow to test jobs.

A meeting with NCO has changed the requirement of this task to use only one include file in include directory for all developer assigned path. Force developer to use NCO path assignment syntax.

**Comment by lgannoaa** [comment]
Meeting on April 21th, 2022 with NCO. Changed the requirement of this task:
1. NCO will modify compath.py utility to allow developer to overwrite.
2. EMC will modify ecflow script to remove EMC developer only area.
3. EMC will encode new compath.py in envir-p1.h with generalized high level path assignment.
4. EMC will modify the JJobs, and ex-scripts for these 25 jobs to use the new generalized high level path assignment.

**Comment by lgannoaa** [comment]
Script update is done. PR updated.

**Comment by KateFriedman-NOAA** [comment]
PR #719 has been merged. Closing this issue now since the PR didn't automatically close it like it was supposed to.
