### ISSUE TITLE
Test rocoto gdas arch, gfs arch, enkfgdas earc, gdas vrfy, and gfs vrfy jobs with new JJOBs and modify vrfy.sh arch.sh as needed

### ISSUE THREAD

**Issue by lgannoaa** [NOAA-EMC/global-workflow#725]
**Description**

This is to test the new archive and verification jobs with rocoto workflow.
Job to be tested:
gdas arch, gfs arch, enkfgdas earc, gdas vrfy, and gfs vrfy jobs
Script to be changed:
vrfy.sh arch.sh

**Requirements**

To ensure new JJobs created for ecflow workflow related gdas arch, gfs arch, enkfgdas earc, gdas vrfy, and gfs vrfy jobs works for rocoto workkflow and modify vrfy.sh arch.sh as needed.

**Comment by lgannoaa** [comment]
A rocoto workflow on wcoss2 has been setup to test: the JJOBs for gdas very, gfs very, gdas arch, gfs arch, and enkfgdas earc jobs
expdir: /lfs/h2/emc/global/noscrub/Lin.Gan/expdir/rjjobtest
com: /lfs/h2/emc/ptmp/Lin.Gan/rjjobtest/
log: /lfs/h2/emc/ptmp/Lin.Gan/rjjobtest/logs/

**Comment by lgannoaa** [comment]
Test is completed.

**Comment by WalterKolczynski-NOAA** [comment]
Can this be closed?

**Comment by lgannoaa** [comment]
Closing the ticket.
