### ISSUE TITLE
Fix wcoss2 module load in global workflow to allow nco/4.7.9 module to load

### ISSUE THREAD

**Issue by lgannoaa** [NOAA-EMC/global-workflow#728]
**Description**

 The wcoss2 dev_v16 module_base.wcoss2.lua need to load nco/4.7.9 module. However, this module's dependency has been changed. Fix is required to avoid error:
Lmod has detected the following error: Cannot load module "nco/4.7.9". At
least one of these module(s) must be loaded:
   gsl

This issue will be referenced by issues #399 and #665.
**Requirements**

Update module loading on wcoss2 configuration.
**Acceptance Criteria (Definition of Done)**

The goal is for this issue is for module loading nco/4.7.9 to success.

**Comment by KateFriedman-NOAA** [comment]
Created `dev_v16_nco_fix` branch for this fix.

**Comment by lgannoaa** [comment]
PR 730 created.

**Comment by KateFriedman-NOAA** [comment]
Complete. Closing now.

**Comment by lgannoaa** [comment]
Close this issue because PR is merged.
