### ISSUE TITLE
Modify checkout.sh to checkout verif_global_v2.9.0 tag in wcoss2

### ISSUE THREAD

**Issue by lgannoaa** [NOAA-EMC/global-workflow#732]
**Description**

EMC verification group released verif_global_v2.9.0 tag.
Will modify checkout.sh to checkout this tag for wcoss2.

**Acceptance Criteria (Definition of Done)**

Use checkout.sh within global_workflow to checkout verif_global_v2.9.0 tag on wcoss2

**Comment by lgannoaa** [comment]
Submitted PR 733.
Close this issue.

**Comment by KateFriedman-NOAA** [comment]
Update complete now that PR #733 has been merged. Closing manually since the PR didn't automatically close this even though it was linked to close.
