### ISSUE TITLE
Update wave related settings and code for P8c 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#736]
**Description**
A new mesh based cap (work by @DeniseWorthen) will be used in p8c. We will be updating which grid the wave model is using.  Updates for the new grid and new code will be required. 
 
**Requirements**
This will require an update to ufs-weather-model (PR is still under review), will require a new input grid, and various setting updates.  There will likely also be build updates that are required. 

**Acceptance Criteria (Definition of Done)**
Done means we can run prototype 8c from the workflow with the new wave cap and grids, setting up the input files correctly (if we do not use multi, a shel input file will have to be created), setting updates will need to be made in addition to creation of regular lat/lon gridded output. 

**Dependencies**
https://github.com/ufs-community/ufs-weather-model/pull/1131

**Comment by JessicaMeixner-NOAA** [comment]
@WalterKolczynski-NOAA @KateFriedman-NOAA @aerorahul One question with this upcoming work: Right now there is a different build for "ATMW" or "S2SW".  What are the requirements about maintaining the ATMW capabilities?  Many of those features are broken at this point, but if that flexibility for making that an option in the future is desired (my guess is yes), I want to know in advance so I can build in the potential flexibility as I go instead of retroactively.

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen I want to confirm with you that we'll be using ww3_shel.inp for p8c.

**Comment by WalterKolczynski-NOAA** [comment]
@JessicaMeixner-NOAA My position is to maintain (or fix) all current capabilities until told otherwise that they are no longer needed. So I've been dragging ATMW along with the assumption one of us will fix it at some point. I'm not even sure (or at least, don't remember) what is even broken with it.

**Comment by JessicaMeixner-NOAA** [comment]
@WalterKolczynski-NOAA thank you.  I will keep the flexibility.

**Comment by JessicaMeixner-NOAA** [comment]
The ufs-weather-model was [updated](https://github.com/ufs-community/ufs-weather-model/pull/1221) to use intel 2021/2022.  Should the base set of modules be updated to use this version or should a set of modules for the forecast be added?

**Comment by WalterKolczynski-NOAA** [comment]
> The ufs-weather-model was [updated](https://github.com/ufs-community/ufs-weather-model/pull/1221) to use intel 2021/2022. Should the base set of modules be updated to use this version or should a set of modules for the forecast be added?

I don't think it is a big deal that should hold this up, though it is something we need to do soon anyway. I opened a new issue (#812) for it.
