### ISSUE TITLE
Update geographical static data, ICs, and namelist settings in CCPP physics 

### ISSUE THREAD

**Issue by ChunxiZhang-NOAA** [NOAA-EMC/global-workflow#737]
**Description**
Following the P8C development, the geographical static data, ICs, and namelist settings in CCPP physics will be updated. Those updates will include but not limited to:
1) Ocean mask data, Orographic data and other geographical static data;
2) ATM ICs which are consistent to the orographic data and other geographical static data; ATM ICs with aerosols from MERRA2;
3) Thompson microphysics scheme related settings (sedi_semi=.true. and decfl=10);
4) NoahMP land surface model related settings (iopt_trs=2 for a placeholder);

**Requirements**
This will require an update to ufs-weather-model.

**Comment by JessicaMeixner-NOAA** [comment]
@ChunxiZhang-NOAA I will take care of 3 with this issue: https://github.com/NOAA-EMC/global-workflow/issues/736

**Comment by ChunxiZhang-NOAA** [comment]
@JessicaMeixner-NOAA Got it, thanks. I removed 3 from the description.
