### ISSUE TITLE
Improve the g-w workflow and fix some bugs

### ISSUE THREAD

**Issue by XianwuXue-NOAA** [NOAA-EMC/global-workflow#742]
Test, improve g-w workflow, especially for feature/continuous_aerosols and also do some bug fixing.

**Description**

**Requirements**

**Acceptance Criteria (Definition of Done)**

**Dependencies**

**Comment by WalterKolczynski-NOAA** [comment]
This is a very ambiguous issue. Improve it how? Fix what bugs? Each should be its own issue and PR.

**Comment by XianwuXue-NOAA** [comment]
OK. Thanks. since everything changed, so I agree with you to close it.
