### ISSUE TITLE
Consolidate UFS build

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#745]
**Description**
The UFS build currently requires a user to determine whether to build for atmosphere-only (ATMW) or coupled (S2SW). This is no longer necessary, as the coupled executable can be used for atmosphere-only runs. The two options build with different CCPP suite lists, so these lists need to be combined

**Requirements**
Removal of special switches for build_ufs and build_all.

**Acceptance Criteria (Definition of Done)**
A UFS executable that is usable for all global-workflow applications.

**Dependencies**
None

**Comment by JessicaMeixner-NOAA** [comment]
I thought an issue for this is that we cannot compile the coupled model with mixed-mode FMS yet and therefore this consolidation would greatly increase the runtime of those running just the ATM model.
