### ISSUE TITLE
Understand the workings of the global-workflow

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/global-workflow#749]
Familiarize the workings of the global-workflow.

Specifically, the `forecast-only` aspects of the workflow for `ATM` and `S2S` configurations.  The S2S configuration will be of relevance to those working on coupled model activity since it contains the aspects of setting up the model for the marine components.  

Particular attention should be given to the coupled prototypes, as the initial development of the data atmosphere capability will leverage the coupled prototyping effort.

Basic proficiency will be acquired in terms of:
- cloning, building of the global-workflow 
- setting up an experiment
- execution and monitoring of the workflow tasks for completion/errors

**Comment by aerorahul** [comment]
@binli2337 and @XianwuXue-NOAA expressed on 5/12 that they have a good understanding of the workings of the global-workflow and are ready to do a dive in its development.

@ryanlong1004 is likely waiting on getting access to Hera/Orion before he is ready to dive into this.  @aerorahul will follow up on account access issues.

**Comment by WalterKolczynski-NOAA** [comment]
@aerorahul I think this is ready to close?

**Comment by aerorahul** [comment]
Complete. Reopen/Recreate when necessary
