### ISSUE TITLE
Share understanding and workings of the global-workflow to MarineDA team

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/global-workflow#750]
Once a basic knowledge of exercising the global-workflow is acquired, transfer/train members from the ocean DA team on the use of the global-workflow
@guillaumevernieres will identify marine DA team members 

Basic training will be provided in terms of:
- cloning, building of the global-workflow 
- setting up an experiment
- execution and monitoring of the workflow tasks for completion/errors

**Comment by WalterKolczynski-NOAA** [comment]
Is still a pending task?

**Comment by aerorahul** [comment]
OBE
