### ISSUE TITLE
Orion:  err_chk does not abort job when processing non-zero return code

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/global-workflow#752]
**Expected behavior**
`export err=$?; err_chk` should cause a job to abort with a non-zero return code.

**Current behavior**
When global-workflow jobs on Orion return a non-zero return code, `err_chk` is run, information is written to the job log file, but the job is not aborted.   Execution continues to the normal end of the job.

**Machines affected**
I do not know if the above behavior exists on other RDHPCS machines.  My tests are limited to Orion.

**To Reproduce**
An example is shown in job log file `gdasatmanalrun.log.0` in directory `/work/noaa/stmp/rtreadon/comrot/prgdas/logs/2021122700/`.     The analysis executable fails with return code 143.  err_chk is executed but the job is not terminated.

**Context**
Since the analysis job continued executing after the non-zero return code a log file was created.   Presence of this log file triggered a downstream job.  This is wrong.  The analysis job should have aborted.  This would prevent creation of the log file and subsequent erroneous submission of the downstream job.

**Detailed Description**
It's my impression that `err_chk` should terminate job execution when processing a non-zero return code.   This behavior is not observed on Orion.`

**Additional Information**
The g-w used for the above test loads `prod_util/1.2.2` from `hpc/1.1.0`.

**Possible Implementation**
Update Orion `err_chk` to abort job for a non-zero return code.

**Comment by aerorahul** [comment]
Is it even possible to use `err_chk` on R&D machines.
From my faint memory  `err_chk` which calls `err_exit` is hard-wired for production HPC and we had to do manual over-rides though use of `ERRSCRIPT`.
Here is `err_exit` https://github.com/NOAA-EMC/NCEPLIBS-prod_util/blob/develop/ush/err_exit
See last if-block for LSB_JOBID, which will never be executed on Orion (or Hera for that matter)

**Comment by RussTreadon-NOAA** [comment]
Yes, I agree.   A check of the `hpc/1.1.0` `prod_util/1.2.2` finds references to `/gpfs/hps` in `err_chk` and `bkill` in `err_exit`.  These are not valid on Orion.

We may not intend or be able to support `err_exit` on multiple platforms.   If so, users should be aware of this and understand that errors may not be trapped as expected.   This can have unintended consequences beyond the process which failed.

**Comment by aerorahul** [comment]
@RussTreadon-NOAA 
Best short-term solution I can provide for you at this time for GDASApp is to not use `err_chk`.
Instead do something like
```
export ERR=$?
export err=$ERR
$ERRSCRIPT || exit $err
```
where 
```
ERRSCRIPT=${ERRSCRIPT:-'eval [[ $err = 0 ]]'}
```
and export and stick that `ERRSCRIPT` in one of your config's (likely `config.base`)

Long term, we have to work with NCO on writing a portable, usable `err_chk` and `err_exit` that is not hard-wired for 1 platform and 1 workflow engine.

Apologies in advance, but this is likely not going to be resolved anytime soon.

**Comment by RussTreadon-NOAA** [comment]
Thanks for the suggestion.   We avoided this solution given g-w issue #294.    That said, the suggested patch is an option.

Please feel free to close this issue while we engage NCO and work toward more generic versions of `err_chk` and `err_exit`.

**Comment by aerorahul** [comment]
I will keep the issue open as a reminder for the future.
It will likely be moved to the icebox until such time it is ready to be acted on.

**Comment by lgannoaa** [comment]
Issue #691 have similar issues.

**Comment by WalterKolczynski-NOAA** [comment]
I believe the workflow-wide imposition of `set -e` via the preamble should short-circuit this problem for the most part as long as `$USE_STRICT` is `YES`, but we probably should still find a way to make it work should strict be turned off.

**Comment by lgannoaa** [comment]
The installation of err_chk and err_exit did not work on development platform. err_chk has hardwired file system location. err_exit does not support SLURM.
The installation of err_chk and err_exit is under a personal location
pwd
/apps/contrib/NCEP/libs/hpc-stack/intel-2018.4/prod_util/1.2.2/bin
Orion-login-4[637] /apps/contrib/NCEP/libs/hpc-stack/intel-2018.4/prod_util/1.2.2/bin$ ls -al err_exit err_chk
-rwxr-xr-x 1 gkyle noaa-hpc 1282 Nov 24 2020 err_chk
-rwxr-xr-x 1 gkyle noaa-hpc 2053 Nov 24 2020 err_exit

I have a version of err_chk and err_exit that works for Orion. They are located in:
/work/noaa/global/lgan/git/PR/prod_util/1.2.2/bin 

@aerorahul please let me know how you want to proceed this.

**Comment by RussTreadon-NOAA** [comment]
Do we still need this issue?

**Comment by RussTreadon-NOAA** [comment]
Close with the option of reopening.  Alternatively, open a new issue if needed.

**Comment by aerorahul** [comment]
@RussTreadon-NOAA [prod_util/2.1.1 ](https://github.com/NOAA-EMC/NCEPLIBS-prod_util/releases/tag/v2.1.1) recently added support to kill slurm jobs.  This version of prod_util will be available w/ spack-stack 1.6.0 and we hope to start using the `err_chk` and `err_exit` functions on RDHPCS machines.

**Comment by RussTreadon-NOAA** [comment]
@aerorahul , should we link this issue to PR #2239?

**Comment by aerorahul** [comment]
@RussTreadon-NOAA I think #2239 will fix this particular issue (though that remains to be tested). 
We will likely need a dedicated issue or use #294 to cover all scripts in the global-workflow.  This will take some effort and time.

**Comment by RussTreadon-NOAA** [comment]
Got it.  Given #294 it seems this issue (#752) can remain closed.
