### ISSUE TITLE
Clean up unsupported global workflow configuration when ROTDIR_DUMP=NO in script and config file.

### ISSUE THREAD

**Issue by lgannoaa** [NOAA-EMC/global-workflow#754]
**Description**

Job prep.sh has code block on ROTDIR_DUMP = "NO" condition. However, config.base.emc.dyn in global workflow develop branch contain:

export ROTDIR_DUMP="YES"                #Note: A value of "NO" does not currently work

This indicated ROTDIR_DUMP="NO" should not be used in jobs. Therefore a cleanup is needed.
**Requirements**

If ROTDIR_DUMP=NO does not support, update prep.sh to remove all code segment where has ROTDIR_DUMP="NO".
If ROTDIR_DUMP=NO is supported, update config.base.emc.dyn to remove statement on related code remark.

**Comment by lgannoaa** [comment]
@KateFriedman-NOAA do you know if ROTDIR_DUMP = "NO" configuration is working for global workflow?

**Comment by KateFriedman-NOAA** [comment]
> @KateFriedman-NOAA do you know if ROTDIR_DUMP = "NO" configuration is working for global workflow?

I have not tested this in a while so I don't know.

**Comment by WalterKolczynski-NOAA** [comment]
This popped again as a more general issue in #999, so I'm going to close this one
