### ISSUE TITLE
Missing previous cycle snoprv (snogrb) COM path assignment in job enkfgdas_sfc 

### ISSUE THREAD

**Issue by lgannoaa** [NOAA-EMC/global-workflow#758]
This bug is in the WCOSS2 NCO production GFS gfs.v16.2.0

**Expected behavior**

FNSNOA=/lfs/h1/ops/prod/com/gfs/v16.2/gdas.20220426/00/atmos/gdas.t00z.snogrb_t1534.3072.1536
   snoprv=/lfs/h1/ops/prod/com/gfs/v16.2/gdas.20220425/18/atmos/gdas.t18z.snogrb_t1534.3072.1536
**Current behavior**

snoprv=/gdas.t18z.snogrb_t1534.3072.1536
**Machines affected**
WCOSS2 NCO production GFS gfs.v16.2.0

**Detailed Description**

/lfs/h1/ops/prod/output/20220426/enkfgdas_sfc_00.o2363050 indicated this bug:
/lfs/h1/ops/prod/packages/gfs.v16.2.0/scripts/exgdas_enkf_sfc.sh: line 121: [: 2022042500: unary operator expected
Code session:
if [ $($WGRIB -4yr $FNSNOA 2>/dev/null | grep -i snowc | awk -F: '{print $3}' | awk -F= '{print $2}') -le \
     $($WGRIB -4yr $snoprv 2>/dev/null | grep -i snowc | awk -F: '{print $3}' | awk -F= '{print $2}') ] ; then
    export FNSNOA=" "
    export CYCLVARS="FSNOL=99999.,FSNOS=99999.,"
else
    export SNOW_NUDGE_COEFF=${SNOW_NUDGE_COEFF:-0.}
    export CYCLVARS="FSNOL=${SNOW_NUDGE_COEFF},$CYCLVARS"
fi
Both $FNSNOA and $snoprv should have path assigned. However, $snoprv missing the leading COM path assignment. This bug caused the code incorrectly execute else statement and set:
export SNOW_NUDGE_COEFF=0.
export CYCLVARS=FSNOL=0.,FSNOL=-2.,FSNOS=99999.,
In comparison to WCOSS1 NCO GFS production, this part outputs:
0.217 + FNSNOA=' '
0.217 + export FNSNOA
0.218 + CYCLVARS=FSNOL='99999.,FSNOS=99999.,'
0.218 + export CYCLVARS

**Comment by RussTreadon-NOAA** [comment]
A check of `exgdas_enkf_sfc.sh` and `JGDAS_ENKF_SFC` found that while `exgdas_enkf.sfc.sh` uses `COMIN_GES`, this variable is not defined.   Given this, define `COMIN_GES` in `JGDAS_ENKF_SFC` as

`export COMIN_GES="$ROTDIR/$CDUMP.$gPDY/$gcyc/$COMPONENT"`

Rerun 2022042612 enkfgdas_sfc job on Cactus with updated `JGDAS_ENKF_SFC`.  The rerun sets 

```
1 + export 'FNSNOA= '
1 + FNSNOA=' '
1 + export CYCLVARS=FSNOL=99999.,FSNOS=99999.,
1 + CYCLVARS=FSNOL=99999.,FSNOS=99999.,
```
The modified `JGDAS_ENKF_SFC` yields ` FSNOL=99999.,FSNOS=99999.,` for the 12Z rerun.  This is consistent with WCOSS operations.

`JGDAS_ENKF_SFC` behaves differently depending on the cycle.   Using the operational WCOSS gfs.v16.1.7 as the control `FSNOL=99999.,FSNOS=99999.,` for 00, 06, and 12Z.   The 18Z run has `FSNOL=0.,FSNOL=-2.,FSNOS=99999.,`.  In contrast, the operational WCOSS2 gfs.v16.2 enkfgdas_sfc has `FSNOL=0.,FSNOL=-2.,FSNOS=99999.,` for all cycles.  

The 2022042618 `JGDAS_ENKF_SFC` was also rerun on Cactus.  The resulting job log file has  `FSNOL=0.,FSNOL=-2.,FSNOS=99999.,`.   Of course, the operational WCOSS2 `/lfs/h1/ops/prod/output/20220427/enkfgdas_sfc_18
.o2411523` also has `FSNOL=0.,FSNOL=-2.,FSNOS=99999.,`. 

The modified `JGDAS_ENKF_SFC` is on Cactus in `/lfs/h2/emc/da/noscrub/Russ.Treadon/git/global-workflow/feature-ops-wcoss2/sorc/gsi.fd/jobs`  A `git diff` of the modified file returns

```
 # COMIN, COMIN_ENS and COMIN_GES_ENS are used in script
 export COMIN="$ROTDIR/$CDUMP.$PDY/$cyc/$COMPONENT"
+export COMIN_GES="$ROTDIR/$CDUMP.$gPDY/$gcyc/$COMPONENT"
 export COMIN_ENS="$ROTDIR/enkf$CDUMP_ENKF.$PDY/$cyc/$COMPONENT"
```

Any changes to `JGDAS_ENKF_SFC` or `exgdas_enkf_sfc.sh` should be tested in all four daily cycles.

Adding @MichaelLueken-NOAA for his information.

**Comment by arunchawla-NOAA** [comment]
Hi

What is the impact of this bug ? @MichaelLueken-NOAA and @KateFriedman-NOAA do we need a fresh tag for this ? @lgannoaa thank you for finding this ! and @RussTreadon-NOAA for testing this out

**Comment by KateFriedman-NOAA** [comment]
> do we need a fresh tag for this ?

@arunchawla-NOAA We wouldn't need a new global-workflow tag for this update since Mike usually recuts the existing GSI tag name but we would need a fresh install in WCOSS2 ops to get this update in. We have several workflow-side updates brewing anyway so this can come into ops with the new global-workflow tag I will need to cut for those (possibly in the next few days).

Thanks for finding @lgannoaa and testing @RussTreadon-NOAA ! I can run this update in a four cycle test on WCOSS2 before promoting to ops if folks want, let me know!

**Comment by lgannoaa** [comment]
I got a copy of the modified JGDAS_ENKF_SFC from /lfs/h2/emc/da/noscrub/Russ.Treadon/git/global-workflow/feature-ops-wcoss2/sorc/gsi.fd/jobs. Testing start on today 2022042700 for 4 cycles using my realtime development ecflow workflow. Here is the information for this workflow:
HOMEgfs: /lfs/h2/emc/global/noscrub/Lin.Gan/git/feature-ops-wcoss2
expdir: /lfs/h2/emc/global/noscrub/Lin.Gan/git/feature-ops-wcoss2/parm/config
COM: /lfs/h2/emc/ptmp/Lin.Gan/ecfops/para/com/gfs/v16.2
log: /lfs/h2/emc/ptmp/Lin.Gan/ecfops/com/output/prod/today

**Comment by KateFriedman-NOAA** [comment]
> Testing start on today 2022042700 for 4 cycles using my realtime development ecflow workflow. 

Thanks for testing @lgannoaa !

**Comment by MichaelLueken** [comment]
@arunchawla-NOAA @KateFriedman-NOAA @RussTreadon-NOAA I have applied Russ' addition of COMIN_GES to jobs/JGDAS_ENKF_SFC to my local copy of release/gfsda.v16.2.0.  I'll keep an eye on the log files from the testing done by @lgannoaa.  I will push this update following the completion of the four cycles and will recreate the tags.

**Comment by lgannoaa** [comment]
The 4 cycle test on this issue is now completed. A check on the job log files indicated the error is resolved.

Lin.Gan@cdecflow02:/lfs/h2/emc/ptmp/Lin.Gan/ecfops/com/output/prod/today> ll enkfgdas_sfc_*.o*                                          
-rw-r--r-- 1 Lin.Gan emc 3.1M Apr 27 15:12 enkfgdas_sfc_00.o2452297
-rw-r--r-- 1 Lin.Gan emc 6.0M Apr 27 17:47 enkfgdas_sfc_06.o2458743
-rw-r--r-- 1 Lin.Gan emc 3.1M Apr 27 19:24 enkfgdas_sfc_12.o2462837
-rw-r--r-- 1 Lin.Gan emc 3.5M Apr 28 00:46 enkfgdas_sfc_18.o2479576
Lin.Gan@cdecflow02:/lfs/h2/emc/ptmp/Lin.Gan/ecfops/com/output/prod/today> grep "unary operator expected" enkfgdas_sfc_*.o*|wc -l
0

The variable CYCLVARS assignment matched the control (wcoss1 NCO production GFS): FSNOL=99999.,FSNOS=99999., for 00, 06, and 12Z. The 18Z run has FSNOL=0.,FSNOL=-2.,FSNOS=99999.

**Comment by RussTreadon-NOAA** [comment]
Good to hear that your test was successful.  I ran four cycles, 2022042612 through 2022042706, earlier today.  The WCOSS2 values for `FSNOL` and `FSNOS` matched WCOSS operations for each cycle.

**Comment by MichaelLueken** [comment]
Thanks for the confirmation of successful tests, @lgannoaa and @RussTreadon-NOAA!  I have pushed the changes to release/gfsda.v16.2.0 (at [c44800a](https://github.com/NOAA-EMC/GSI/commit/c44800ac7841a5a12bc9ab59e9c93664e531ebae)) and feature/gfsda.v16.1.5_wcoss2_port (at [468ecd0](https://github.com/NOAA-EMC/GSI/commit/468ecd02b5b05893591af83d859dfea4697ac86c)) and recreated the gfsda.v16.2.0 and gfsda.v16.2.0.1 tags, respectively.

**Comment by KateFriedman-NOAA** [comment]
Thanks all! This update will make it's way into WCOSS2 ops with the next fresh install of the GFS that SPA Wei will do. Likely soon, we have some other updates in the workflow that will need to get in as well.

**Comment by KateFriedman-NOAA** [comment]
This issue is complete. Related additional work is happening in issue #999.
