### ISSUE TITLE
Running ksh typeset instruction cause error in gfs gempak_meta job

### ISSUE THREAD

**Issue by lgannoaa** [NOAA-EMC/global-workflow#759]
This issue exist in NCO production GFS on both WCOSS1 and WCOSS2
**Expected behavior**

typeset -Z2 fhr should be run without issue
**Current behavior**

WCOSS2:
/lfs/h1/ops/prod/output/20220426/gfs_atmos_gempak_meta_00.o2355544 shown:
/lfs/h1/ops/prod/packages/gfs.v16.2.0/scripts/exgfs_atmos_gempak_meta.sh[86]: [: argument expected
WCOSS1:
/gpfs/dell1/nco/ops/com/output/prod/20220426/gfs_atmos_gempak_meta_00.o90798087 shown:
/gpfs/dell1/nco/ops/nwprod/gfs.v16.1.7/scripts/exgfs_atmos_gempak_meta.sh[88]: [: argument expected
**Machines affected**

WCOSS1 and WCOSS2

**Detailed Description**

$HOMEgfs/scripts/exgfs_atmos_gempak_meta.sh used a ksh shell commend "typeset -Z2 fhr"
This commend failed to evaluate the fhr. Instead, it unset this variable. This issue caused the script unable to see fhr variable and generated error in log file:
/lfs/h1/ops/prod/packages/gfs.v16.2.0/scripts/exgfs_atmos_gempak_meta.sh[86]: [: argument expected

**Possible Implementation**

Modify JJob to call this script by using ksh shell assignment

**Comment by WalterKolczynski-NOAA** [comment]
We should be moving away from both ksh (to bash) and using typeset for padding (to printf). So hopefully this will be mooted.

**Comment by WalterKolczynski-NOAA** [comment]
This is fixed in develop as part of #929. Do we need to keep this issue open to be addressed for v16, or can we close it now?

**Comment by lgannoaa** [comment]
Closing ticket.
