### ISSUE TITLE
Organize COM and refactor path definitions

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#761]
**Description**
The COM directory, particularly atmos, is currently very flat, with most files at the same level. This is already a bit unwieldy, a situation that would become much worse if ensembles were implemented without additional organization.

Original proposed organization: (**Please see PR #1421 for up-to-date reorg trees**)
```
$mem
|- atmos
  |- model_data
    |- analysis
    |- history
      |- (NetCDFs produced by model)
    |- input
    |- master
      |- (master files)
      |- (sfluxgrb files).
    |- restart
  |- products
    |- 0p25
    |- 1p00
    |- bufr [prod]
    |- gempak [prod]
    |- genesis_vital_$year [dev]
      |- all.vitals.gfs.gfso.$year
      |- genesis.vitals.gfso.$year
    |- goes_sim [prod]
      |- *.goessimpgrb2.*
    |- imagery [prod]
      |- *.gif
    |- minmon [prod]
    |- tracks [dev]
      |- storms.*
      |- trak.*
    |- wafs [prod]
      |- blended
      |- no_us
      |- unblended
    |- wmo [prod]
|- chem
  |- model_data
    |- history
|- ice
  |- model_data
    |- input
    |- history
    |- restart
  |- products
|- ocean
  |- model_data
    |- analysis
    |- history
    |- input
    |- restart
  |- products
    |- 0p25
    |- 0p50
|- wave
  |- model_data
    |- history
    |- prep
    |- restart
  |- products
    |- gridded
    |- station
```

**Requirements**
A sensible organization of output files into different directories, with each directory containing a reasonable number of files.

Ideally, this would be done using configurable filename templates to allow for easy changes in the future, assuming it can be done in bash in a sensible manner. Otherwise, it will have to wait until a possible future conversion to python.

**Acceptance Criteria (Definition of Done)**
End-to-end completion of workflow using the new COM structure.

**Dependencies**
Issues #679, #746, #769
With the understanding that any solution implemented now is only an interim solution until an agreement is reached with NCO on a final configuration.

Issue #1298

**Comment by WalterKolczynski-NOAA** [comment]
After discussion with the global-workflow team, we've decided on a tentative structure overall and for atmos. Modifications to other component directories may be added as we go. I will keep the first post updated with the current proposed structure.

@aerorahul @KateFriedman-NOAA I've added a bunch more trying to accommodate all the additional files created in production. There may be a few stragglers I need help categorizing.

Can we move the files from genesis_vital_$year to the new tracks directory?

@JessicaMeixner-NOAA I'll also take a crack at organizing the files in ocean and updating the filenames to the standard format. What's your opinion on moving the ice files in under ocean?

**Comment by JessicaMeixner-NOAA** [comment]
@WalterKolczynski-NOAA how about putting the ocean and ice grib files together under ocean (similarly to the way that land is still under atm) but we could still have the ice restart and model output in it's own directory.  Let me know if you'd like help with organizing ocean/ice.  I think it's mostly model output or run data, restarts, and then the grib.

**Comment by CoryMartin-NOAA** [comment]
Two comments/suggestions here:

1) What about DA? (tagging @CatherineThomas-NOAA ) Propose 'analysis' inline with INPUT/ RESTART/ for atmanl.nc, atminc.nc, and abias, etc. files
2) `nc` should be changed to `history`. RESTART also contains netCDF files produced by the model.

**Comment by WalterKolczynski-NOAA** [comment]
> Two comments/suggestions here:
> 
> 1. What about DA? (tagging @CatherineThomas-NOAA ) Propose 'analysis' inline with INPUT/ RESTART/ for atmanl.nc, atminc.nc, and abias, etc. files

I was probably going to put them in the nc directory, but this is probably a better option.

> 2. `nc` should be changed to `history`. RESTART also contains netCDF files produced by the model.

Good suggestion

**Comment by WalterKolczynski-NOAA** [comment]
Now able to run a vanilla atm-only cycled forecast with a few caveats:
- prepobs requires a minor change
- fit2obs also needs updates, but they will be deferred for the time being
- some output has not been verified yet

Here are the directory trees (directories only for brevity). Will also provide gists that include the files. Trees subject to change.
```
enkfgdas.20211221/00
├── earc00
├── ensstat
│   └── atmos
│       └── model_data
│           ├── analysis
│           │   └── gsidiags
│           │       ├── dir.0000
│           │       ├── dir.0001
│           │       ├── < Additional dir.* omitted for brevity >
│           │       └── dir.0039
│           └── history
├── mem001
│   └── atmos
│       └── model_data
│           ├── analysis
│           ├── history
│           ├── master
│           └── restart
└── mem002
    └── atmos
        └── model_data
            ├── analysis
            ├── history
            ├── master
            └── restart

61 directories
```
Tree with files: https://gist.github.com/WalterKolczynski-NOAA/860aaa804e3e70e191e7cae2ebb1055b

```
gdas.20211222/00/
├── atmos
│   ├── model_data
│   │   ├── analysis
│   │   │   └── gsidiags
│   │   │       ├── dir.0000
│   │   │       ├── dir.0001
│   │   │       ├── dir.0002
│   │   │       ├── (Additional dir.* directories omitted for brevity)
│   │   │       └── dir.0083
│   │   ├── history
│   │   ├── master
│   │   └── restart
│   └── products
│       ├── 0p25
│       ├── 0p50
│       ├── 1p00
│       └── cyclone
│           ├── genesis_vital
│           └── tracks
└── obs

98 directories

```
Tree with files: https://gist.github.com/WalterKolczynski-NOAA/f1de04901e2703fd24d38146d2669789

```
gfs.20211222/00
├── atmos
│   ├── model_data
│   │   ├── analysis
│   │   ├── history
│   │   ├── master
│   │   └── restart
│   └── products
│       ├── 0p25
│       ├── 0p50
│       ├── 1p00
│       ├── bufr
│       ├── cyclone
│       │   ├── genesis_vital
│       │   └── tracks
│       ├── gempak
│       └── wmo
└── obs

17 directories
```
Tree with files: https://gist.github.com/WalterKolczynski-NOAA/5d1b7c0a0f4b8cfff0be1ae54082316a
- NB: Looks like an empty `genesis_vital_2021` was created and needs to be removed.

**Comment by WalterKolczynski-NOAA** [comment]
Nominally completed the work on forecast-only S2SWA with similar caveats about the output not yet being verified.

Directory-only tree:
```
gfs.20130401/00/
├── atmos
│   ├── genesis_vital_2013
│   ├── model_data
│   │   ├── history
│   │   ├── input
│   │   ├── master
│   │   └── restart
│   └── products
│       ├── 0p25
│       ├── 0p50
│       ├── 1p00
│       └── cyclone
│           └── tracks
├── chem
│   └── model_data
│       └── history
├── ice
│   └── model_data
│       ├── history
│       ├── input
│       └── restart
├── med
│   └── model_data
│       └── restart
├── ocean
│   ├── model_data
│   │   ├── history
│   │   ├── input
│   │   └── restart
│   └── products
│       ├── 0p25
│       ├── 0p50
│       ├── 2D
│       ├── 3D
│       └── xsect
└── wave
    ├── model_data
    │   ├── history
    │   ├── prep
    │   └── restart
    └── products
        ├── gridded
        └── station

43 directories
```
Tree with files: https://gist.github.com/WalterKolczynski-NOAA/6ae90c6eafb573878f60682ce47179db

**Comment by WalterKolczynski-NOAA** [comment]
Also, a note: I found an issue with my prepobs changes for the cycled experiment, so it is missing things like prepbufr files in the obs directory. I think it is fixed and will update the trees when I am able.

**Comment by WalterKolczynski-NOAA** [comment]
Also also, here are the changes: https://github.com/NOAA-EMC/global-workflow/compare/develop...WalterKolczynski-NOAA:global-workflow:feature/com_reorg
