### ISSUE TITLE
GW checkout script failed to submodule update when checkout upp

### ISSUE THREAD

**Issue by lgannoaa** [NOAA-EMC/global-workflow#767]
**Expected behavior**

Checkout script show complete successful
**Current behavior**

+ git checkout upp_v10.0.11
...
HEAD is now at 0dc3c0c NOAA GSL UPP updates (#413)
+ git submodule update --init CMakeModules
error: pathspec 'CMakeModules' did not match any file(s) known to git.

**Machines affected**

WCOSS2 Hera
**To Reproduce**

Checkout develop and run checkout.sh

**Comment by WenMeng-NOAA** [comment]
@lgannoaa Can you point me the branch of the GW?

**Comment by aerorahul** [comment]
@lgannoaa 
https://github.com/NOAA-EMC/UPP/tree/upp_v10.0.11 removed all submodules.
Perhaps the issue is at the global-workflow end where this needs to be resolved.

**Comment by aerorahul** [comment]
@lgannoaa 
[This](https://github.com/NOAA-EMC/global-workflow/blob/a9fc0033b908aefb42d5b2d191c65af5cb7660c4/sorc/checkout.sh#L81) line needs to be removed from `checkout.sh` with the update to UPP to the above tag.

**Comment by lgannoaa** [comment]
@aerorahul ok.
@WenMeng-NOAA I used the latest global workflow develop branch.

**Comment by WenMeng-NOAA** [comment]
@lgannoaa I see. You might use the latest UPP revision from UPP develop. I sent you the changes vial email.
