### ISSUE TITLE
Move post scripts from UPP under global-workflow

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#769]
**Description**
Several scripts currently located under NOAA-EMC/UPP are only used for global and should be moved within global-workflow so they can be managed by the global-workflow team.

**Requirements**
All scripts that are global-specific added to this repository. Afterwards, they can presumably be removed from UPP.

**Acceptance Criteria (Definition of Done)**
No scripts copied from UPP.

**Dependencies**
None

**Comment by WalterKolczynski-NOAA** [comment]
This issue will also fix #520, as I am copying in from the current version of UPP where it has been fixed.

**Comment by WalterKolczynski-NOAA** [comment]
Tagging @WenMeng-NOAA to keep informed

**Comment by HuiyaChuang-NOAA** [comment]
@WalterKolczynski-NOAA @arunchawla-NOAA

Hi, Walter, I just spoke to Arun. We're supportive of EIB taking over GFS post processing scripts but given Wen is pretty busy and also her first check indicated your new scripts have inadvertently removed existing operational GFS products, I would
like to propose the followings going forward:

we will not remove any post processing scripts from UPP repository until EIB takes over all post processing scripts and both post processing team and EIB verify all operational capabilities are being replicated by EIB's new post processing scripts.
with that said, please proceed to transition all gfs post processing scripts to EIB workflow and when you've completed all transition, please reach out to us, and we will check the final scripts and products.
Again, I recommend that we try to replicate operational GFS post processing capabilities first. Thank you. I will also send this as an email to a bigger group.

**Comment by WalterKolczynski-NOAA** [comment]
To keep a record of it:

We had a meeting today to discuss the matter and how it is going to work, with a follow-up meeting on Tues May 10.
