### ISSUE TITLE
Update global-workflow scripts for running the NG-GODAS application

### ISSUE THREAD

**Issue by binli2337** [NOAA-EMC/global-workflow#774]
**Description**

The following four tasks are involved for running NG-GODAS application:
1. get initial condition
2. run the forecast
3. do ocean and ice post processing
4. save files to HPSS

**Requirements**

Some files in parm/config/, ush/, scripts/ need to be updated. Also the following python scripts need to be updated:
ush/rocoto/setup_expt.py
ush/rocoto/setup_workflow_fcstonly.py

Some options need to be introduced in the setup_workflow_fcstonly.py script. For example,
do_atm (YES or NO)
do_datm (YES or NO)
do post (YES or NO)

**Acceptance Criteria (Definition of Done)**

The global workflow can run the NG-GODAS application using any of the following data forcing sources:
CFSR forcing
GEFS forcing
GFSv16 forcing

**Dependencies**
#751 (build the NG-GODAS application)

**Comment by WalterKolczynski-NOAA** [comment]
IIRC, it was decided not to bring this into develop and a separate branch was made instead. That branch has since been cleaned up since Bin Li left.
