### ISSUE TITLE
Setting up of run directory for Data Atmosphere configuration

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/global-workflow#785]
**Description**

The atmosphere component is **always** `ON` in the workflow.
The `NG-GODAS` application of the ufs-weather-model does not have a live and interactive atmosphere.  It compiles the with a data-atmosphere component from `CDEPS`. 

The global-workflow does not have a `DO_ATM` switch.

**Requirements**
A `DO_ATM` switch shall be added to `config.base`
This switch shall be toggled based on `APP`.
The default value of `DO_ATM` shall be `YES`.
When `APP=NG-GODAS`, the value of `DO_ATM=NO`.

Update `exglobal_fcst.sh` and the scripts that it calls to implement the option for `DO_ATM=NO`  for data atmosphere specific configuration.

The run-directory for `DO_ATM=YES` will be validated against current `develop`
The run-directory for `DO_ATM=NO` will be spot checked for correctness in the configuration.

It is not necessary to have the forcing files present in the run directory for the completion of this work.
This will be the focus of another issue.

**Acceptance Criteria (Definition of Done)**
`APP=ATM|ATMW|S2S|S2SW` allows for business as usual. (`DO_ATM=YES`)
`APP=NG-GODAS` allows for setting up of a run directory for `DO_ATM=NO`

**Dependencies**
#751

**Comment by binli2337** [comment]
The following updates have been made:
1) Added 3 new switches in config.base.emc.dyn:
DO_ATM, DO_DATM,DO_POST

2) Updated ush/rocoto/setup_expt.py and ush/rocoto/setup_workflow_fcstonly.py for the NG-GODAS application.

**Comment by binli2337** [comment]
The following updates have been made:
1. Added ush/parsing_model_configure_DATM.sh
2. Added ush/nems.configure.datm_cdeps.IN
3. Modified ush/nems_configure.sh

**Comment by WalterKolczynski-NOAA** [comment]
IIRC, it was decided not to bring this into develop and a separate branch was made instead. That branch has since been cleaned up since Bin Li left.
