### ISSUE TITLE
Generate atmosphere forcings for NG-GODAS application in global-workflow

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/global-workflow#786]
**Description**
The data atmosphere configuration of the ufs-weather-model is being brought into the global-workflow for ocean data assimilation development activities.
Atmosphere forcings are required for driving the NG-GODAS application.

The utility to create the atmosphere forcing currently is hosted in the [GODAS](https://github.com/NOAA-EMC/godas) repository [here](https://github.com/NOAA-EMC/godas/tree/develop/forc/GFS).
It is maintained by @hyunchul386.

**Requirements**
1. Re-locate the forcing generator to [ufs-utils](https://github.com/ufs-community/UFS_UTILS)
2. Follow ufs-utils guidelines; build with `cmake`, add a regression test case.
3. Re-write scripts such that they can be used in the regression test in 2. as well as in the global-workflow.  See example [chgres_cube](https://github.com/ufs-community/UFS_UTILS/blob/develop/ush/chgres_cube.sh).

**Acceptance Criteria (Definition of Done)**
1. The forcing generator builds and runs on all platforms that global-workflow is supported.
2. The scripts can be exercised from said platforms.

Contact @guillaumevernieres if there are any questions or concerns.

**Comment by WalterKolczynski-NOAA** [comment]
IIRC, it was decided not to bring this into develop and a separate branch was made instead. That branch has since been cleaned up since Bin Li left.
