### ISSUE TITLE
Add tasks to get or create atmosphere forcings

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/global-workflow#788]
**Description**
To run the `NG-GODAS` application of the ufs-weather-model, tasks need to be added in the global workflow to either fetch already generated (and staged) forcings or create forcings from atmospheric analysis.

**Requirements**
Three tasks will be created.
Task 1 will be to get forcings from HPSS or some central location and stage them in ROTDIR:
location 1 will be HPSS
location 2 can be some central place on supported platforms.

Task 2 will get atmospheric analysis from HPSS or some central location and stage them in ROTDIR

Task 3 will be to create the forcings from atmospheric analysis already staged in ROTDIR

**Acceptance Criteria (Definition of Done)**
Related scripting for the above tasks includes:
j-jobs, ex or ush scripts as well as the rocoto job-card.

**Dependencies**
Depends on #786

**Comment by WalterKolczynski-NOAA** [comment]
IIRC, it was decided not to bring this into develop and a separate branch was made instead. That branch has since been cleaned up since Bin Li left.
