### ISSUE TITLE
Update experiment setup script for free-forecast ensemble

### ISSUE THREAD

**Issue by XianwuXue-NOAA** [NOAA-EMC/global-workflow#789]
**Description**
As we move towards the merger of GEFS into the GFS system, we need to be able to generate experiments with an arbitrary number of free-forecast ensemble members in addition to the number of EnKF members.

**Requirements**
Ability to generate experiments (using `setup_expt.py`) with a number of free-forecast ensemble members determined via a command-line switch similar to how the number of EnKF members is determined. The default should be 0, indicating no perturbed members (control only). This will require `config.base` to be updated to provide a corresponding new variable which will be used by all the job scripts later.

**Acceptance Criteria (Definition of Done)**
A `setup_expt.py` script that takes in a number of member for the free-forecast and sets an appropriate variable in `config.base`.

**Dependencies**
None

**Comment by aerorahul** [comment]
closing as OBE
