### ISSUE TITLE
Add atmos subfolder to GDA and relevant DMPDIR paths

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#802]
**Description**

It has been decided to add a `$COMPONENT` (`atmos`) subfolder into the global dump archive (GDA) folders:

`$CDUMP.$PDY/$cyc` -> `$CDUMP.$PDY/$cyc/atmos`

This will bring the GDA in alignment with related updates to add a `$COMPONENT` (`atmos`) subfolder into the GFS and OBSPROC com structures. This is also needed for running the GFS and using `compath.py` for defining `COM` paths.

This update is targeted for both the `develop` branch and the GFSv16.3 package, via the `dev_v16` branch before going into the `release/gfs.v16.3.0` branch. Updates will need to occur in the GDAs (WCOSS2, Hera, Orion), global-workflow scripts/configs, GSI scripts, and UFS_UTIL scripts (anything that references DMPDIR and a folder structure to find dump files).

The plan:

- [x] 1. Add an `atmos` subfolder symlink into existing GDA folders that point to the same level as `atmos` (pre-WCOSS2-go-live dates). This will maintain support for existing/older GFS packages (by not moving existing files) but also support the updated system running on pre-WCOSS2-go-live dates).

* - [x] WCOSS2 - Cactus
* - [x] WCOSS2 - Dogwood
* - [x] WCOSS1 - Mars
* - [x] WCOSS1 - Venus
* - [x] Hera
* - [x] Orion
* - [x] WCOSS1 real-time GDA job creates `atmos` symlinks and rsyncs to other GDAs

- [x] 2. As of the WCOSS2 go-live cycle, the GDA folders will contain an `atmos` folder and the dump files will live within it. The new WCOSS2 GDA job will begin populating the WCOSS2 GDA as of this go-live cycle and will be set up to use an `atmos` folder from the start and during pre-go-live testing.
- [x] 3. The global-workflow will update its files/scripts that contain a `DMPDIR` reference and folder structure to add the `atmos` subfolder (likely via the `$COMPONENT` variable if `COMPONENT=atmos`). Ensure step 1 is complete.
* - [x] `dev_v16` branch (PR #813)
* - [x] `develop` branch (PR #847)
- [x] 4. The GSI will make similar updates as step 3 in both their `develop` and GFSv16.3 branches (ensure step 1 is complete). https://github.com/NOAA-EMC/GSI/issues/391
- [x] 5. The UFS_UTILS will make similar updates as step 3 in both develop and GFSv16 branches (ensure step 1 is complete). https://github.com/ufs-community/UFS_UTILS/issues/652
- [x] 6. The GLDAS will update their `ush/gldas_forcing.sh` script to add `atmos` to the CPC gauge GDA path. New tag: gldas_gfsv16_release.v.2.1.0 @HelinWei-NOAA 

The following scripts/configs in global-workflow will need to be updated to add the `atmos` subfolder (in both the `develop` and `dev_v16` branches):

```
jobs/JGLOBAL_WAVE_PREP:    $NLN $DMPDIR/$CDUMP.${PDY}/$cyc/${WAVICEFILE} $ROTDIR/$CDUMP.${PDY}/$cyc/atmos/${WAVICEFILE}
jobs/rocoto/prep.sh:   $HOMEgfs/ush/getdump.sh $CDATE $CDUMP $DMPDIR/${CDUMP}${DUMP_SUFFIX}.${PDY}/${cyc} $COMOUT
jobs/rocoto/prep.sh:     $HOMEgfs/ush/getdump.sh $GDATE $GDUMP $DMPDIR/${GDUMP}${DUMP_SUFFIX}.${gPDY}/${gcyc} $gCOMOUT
jobs/rocoto/prep.sh:    [[ $ROTDIR_DUMP = "NO" ]] && cp $DMPDIR/${CDUMP}${DUMP_SUFFIX}.${PDY}/${cyc}/${CDUMP}.t${cyc}z.syndata.tcvitals.tm00 $COMOUT/
jobs/rocoto/prep.sh:      COMIN_OBS=${COMIN_OBS:-$DMPDIR/${CDUMP}${DUMP_SUFFIX}.${PDY}/${cyc}}
jobs/rocoto/prep.sh:    $NCP $DMPDIR/${CDUMP}${DUMP_SUFFIX}.${PDY}/${cyc}/${OPREFIX}prepbufr               $COMOUT/${OPREFIX}prepbufr
jobs/rocoto/prep.sh:    $NCP $DMPDIR/${CDUMP}${DUMP_SUFFIX}.${PDY}/${cyc}/${OPREFIX}prepbufr.acft_profiles $COMOUT/${OPREFIX}prepbufr.acft_profiles
jobs/rocoto/prep.sh:    [[ $DONST = "YES" ]] && $NCP $DMPDIR/${CDUMP}${DUMP_SUFFIX}.${PDY}/${cyc}/${OPREFIX}nsstbufr $COMOUT/${OPREFIX}nsstbufr
parm/config/config.anal:        export ABIBF="$DMPDIR/${CDUMP}x.${PDY}/${cyc}/${CDUMP}.t${cyc}z.gsrcsr.tm00.bufr_d"
parm/config/config.anal:            export ABIBF="$DMPDIR/${CDUMP}y.${PDY}/${cyc}/${CDUMP}.t${cyc}z.gsrcsr.tm00.bufr_d"
parm/config/config.anal:        export AHIBF="$DMPDIR/${CDUMP}x.${PDY}/${cyc}/${CDUMP}.t${cyc}z.ahicsr.tm00.bufr_d"
parm/config/config.anal:    export HDOB=$DMPDIR/${CDUMP}x.${PDY}/${cyc}/${CDUMP}.t${cyc}z.hdob.tm00.bufr_d
ush/getdump.sh:SOURCE_DIR=${3:-$DMPDIR/${CDUMP}${DUMP_SUFFIX}.${PDY}/${cyc}}
ush/drive_makeprepbufr.sh:COMIN_OBS=${COMIN_OBS:-"$DMPDIR/${CDUMP}${DUMP_SUFFIX}.${PDY}/${cyc}"}
ush/rocoto/setup_workflow.py:    data = f'&DMPDIR;/{cdump}{dumpsuffix}.@Y@m@d/@H/{cdump}.t@Hz.updated.status.tm00.bufr_d'
```

The following GSI scripts will need to be updated to add the `atmos` subfolder (in both the `develop` branch and GFSv16.3 package - @emilyhcliu @RussTreadon-NOAA @MichaelLueken-NOAA ):

```
jobs/JGDAS_ENKF_ECEN:    export COMIN_OBS="$DMPDIR/$CDUMP.$PDY/$cyc"
jobs/JGDAS_ENKF_ECEN:    export COMIN_GES_OBS="$DMPDIR/$GDUMP.$gPDY/$gcyc"
jobs/JGLOBAL_ATMOS_ANALYSIS:    export COMIN_OBS="$DMPDIR/$CDUMP.$PDY/$cyc"
jobs/JGLOBAL_ATMOS_ANALYSIS:    export COMIN_GES_OBS="$DMPDIR/$GDUMP.$gPDY/$gcyc"
jobs/JGLOBAL_ATMOS_ANALYSIS_CALC:    export COMIN_OBS="$DMPDIR/$CDUMP.$PDY/$cyc"
jobs/JGLOBAL_ATMOS_ANALYSIS_CALC:    export COMIN_GES_OBS="$DMPDIR/$GDUMP.$gPDY/$gcyc"
jobs/JGDAS_ENKF_SFC:    export COMIN_OBS="$DMPDIR/$CDUMP.$PDY/$cyc"
jobs/JGDAS_ENKF_SFC:    export COMIN_GES_OBS="$DMPDIR/$GDUMP.$gPDY/$gcyc"
jobs/JGDAS_ENKF_DIAG:    export COMIN_OBS="$DMPDIR/$CDUMP.$PDY/$cyc"
jobs/JGDAS_ENKF_DIAG:    export COMIN_GES_OBS="$DMPDIR/$GDUMP.$gPDY/$gcyc"
jobs/JGDAS_ATMOS_CHGRES_FORENKF:    export COMIN_OBS="$DMPDIR/$CDUMP.$PDY/$cyc"
jobs/JGDAS_ATMOS_CHGRES_FORENKF:    export COMIN_GES_OBS="$DMPDIR/$GDUMP.$gPDY/$gcyc"
jobs/JGDAS_ENKF_SELECT_OBS:    export COMIN_OBS="$DMPDIR/$CDUMP.$PDY/$cyc"
jobs/JGDAS_ENKF_SELECT_OBS:    export COMIN_GES_OBS="$DMPDIR/$GDUMP.$gPDY/$gcyc"
jobs/JGDAS_ATMOS_ANALYSIS_DIAG:    export COMIN_OBS="$DMPDIR/$CDUMP.$PDY/$cyc"
jobs/JGDAS_ATMOS_ANALYSIS_DIAG:    export COMIN_GES_OBS="$DMPDIR/$GDUMP.$gPDY/$gcyc"
```

The following UFS_UTILS paths need to be updated to add `atmos` and use the modern GDA structure anyway (@GeorgeGayno-NOAA ):

```
sorc/ufs_utils.fd/ush/global_cycle_driver.sh:export FNTSFA=${FNTSFA:-$DMPDIR/$CDATE/$CDUMP/${CDUMP}.t${cyc}z.rtgssthr.grb}
sorc/ufs_utils.fd/ush/global_cycle_driver.sh:export FNSNOA=${FNSNOA:-$DMPDIR/$CDATE/$CDUMP/${CDUMP}.t${cyc}z.snogrb_t1534.3072.1536}
sorc/ufs_utils.fd/ush/global_cycle_driver.sh:export FNACNA=${FNACNA:-$DMPDIR/$CDATE/$CDUMP/${CDUMP}.t${cyc}z.seaice.5min.blend.grb}
```

**Acceptance Criteria (Definition of Done)**

Both the `feature/ops-wcoss2` (pre-change version) and `dev_v16` (post-change versions) can use the GDA without issue.

**Caveats**

The `feature/ops-wcoss2` and older branches will not work for CDATEs after WCOSS2 go-live CDATE. The `dev_v16` branch will support GFSv16.2.0+ on supported platforms (WCOSS2, Hera, Orion) for all dates in all GDAs.

Refs: #665, #744

**Comment by KateFriedman-NOAA** [comment]
The `atmos` subfolder symlinks have been added to the WCOSS2 GDAs on Cactus and Dogwood (all existing dates). Here is a sample showing the new `atmos` subfolder symlink in the 2022052306 gfsx folder:
```
emc.global@dlogin07> ll /lfs/h2/emc/global/noscrub/emc.global/dump/gfsx.20220523/06
total 153396
lrwxrwxrwx 1 emc.global emc            2 May 23 18:37 atmos -> ./
-rw-r--r-- 1 emc.global emc     96041096 May 23 08:56 gfs.t06z.gmi1cr.tm00.bufr_d
-rw-r----- 1 emc.global rstprod 48399536 May 23 08:49 gfs.t06z.gpsro.tm00.bufr_d
-rw-r----- 1 emc.global rstprod 12193864 May 23 08:55 gfs.t06z.nsstbufr
-rw-r--r-- 1 emc.global emc            0 May 23 08:50 gfs.t06z.saldrn.tm00.bufr_d
-rw-r--r-- 1 emc.global emc       433520 May 23 08:50 gfs.t06z.subpfl.tm00.bufr_d
```

...and what is returned when you do a listing through the `atmos` symlink:
```
emc.global@dlogin07> ll /lfs/h2/emc/global/noscrub/emc.global/dump/gfsx.20220523/06/atmos
lrwxrwxrwx 1 emc.global emc 2 May 23 18:37 /lfs/h2/emc/global/noscrub/emc.global/dump/gfsx.20220523/06/atmos -> ./
emc.global@dlogin07> ll /lfs/h2/emc/global/noscrub/emc.global/dump/gfsx.20220523/06/atmos/
total 153396
lrwxrwxrwx 1 emc.global emc            2 May 23 18:37 atmos -> ./
-rw-r--r-- 1 emc.global emc     96041096 May 23 08:56 gfs.t06z.gmi1cr.tm00.bufr_d
-rw-r----- 1 emc.global rstprod 48399536 May 23 08:49 gfs.t06z.gpsro.tm00.bufr_d
-rw-r----- 1 emc.global rstprod 12193864 May 23 08:55 gfs.t06z.nsstbufr
-rw-r--r-- 1 emc.global emc            0 May 23 08:50 gfs.t06z.saldrn.tm00.bufr_d
-rw-r--r-- 1 emc.global emc       433520 May 23 08:50 gfs.t06z.subpfl.tm00.bufr_d
```

Next steps:

1. Add `atmos` "subfolder" symlinks to WCOSS1, Hera, and Orion GDAs.
2. Update WCOSS1 GDA job to create the `atmos` symlink in the WCOSS1 GDAs and include it in the rsync push to the Hera/WCOSS2 GDAs (so new real-time folders get the `atmos` symlink automatically).
3. After `atmos` symlinks are in place in all GDAs...update `DMPDIR` path structures to add `atmos` subfolder to scripts/files listed in first comment in issue.

**Comment by KateFriedman-NOAA** [comment]
Created branch [feature/dev_v16_gdaatmos](https://github.com/KateFriedman-NOAA/global-workflow/tree/feature/dev_v16_gdaatmos) in my global-workflow fork to add `atmos` subfolder to workflow files/scripts in `dev_v16`. Will make similar branch to add `atmos` to `develop` branch after testing for `dev_v16`.

**Comment by KateFriedman-NOAA** [comment]
Committed workflow updates to `feature/dev_v16_gdaatmos` branch @ baa5893. Testing on WCOSS2 now.

The `atmos` subfolder symlinks have been added to the Hera and Orion GDAs. Working on WCOSS1 and real-time job next.

**Comment by KateFriedman-NOAA** [comment]
The `atmos` subfolder symlinks have been added to the WCOSS1 GDAs (Mars and Venus). Working on adding `atmos` subfolder symlink to real-time GDA job on WCOSS1 for new subfolders next.

**Comment by KateFriedman-NOAA** [comment]
@MichaelLueken-NOAA The `atmos` subfolder symlinks are in place in all GDAs (WCOSS2, WCOSS1, Hera, and Orion). If you have a GFSv16.3 GSI branch that I can do a plumbing test within a global-workflow test on WCOSS2 let me know, I have a test running now to check the plumbing on the related workflow updates. The GDAs support pre-atmos-subfolder-symlinks still so my current GFSv16.2.0 GSI tag still works and I'm visually checking that "atmos" ends up in the relevant paths and then the relevant jobs grab GDA files correctly (mainly the prep job so far).. Let me know, thanks!

**Comment by KateFriedman-NOAA** [comment]
Creation of `atmos` subfolder symlinks in real-time GDA job on WCOSS1 is complete. New real-time GDA date subfolders will get an `atmos` subfolder symlink created before it's rsync'd to the other GDAs. The `atmos` symlink will accompany the dump files in the rsync to the other GDAs so the other GDAs get the symlink in real-time moving forward now too.

**Comment by MichaelLueken** [comment]
> @MichaelLueken-NOAA The `atmos` subfolder symlinks are in place in all GDAs (WCOSS2, WCOSS1, Hera, and Orion). If you have a GFSv16.3 GSI branch that I can do a plumbing test within a global-workflow test on WCOSS2 let me know, I have a test running now to check the plumbing on the related workflow updates. The GDAs support pre-atmos-subfolder-symlinks still so my current GFSv16.2.0 GSI tag still works and I'm visually checking that "atmos" ends up in the relevant paths and then the relevant jobs grab GDA files correctly (mainly the prep job so far).. Let me know, thanks!

@KateFriedman-NOAA I should have the release/gfsda.v16.3.0 branch created on Friday.  I still have a few more changes that need to go into develop before the creation of the branch (including the update to add `atmos` to the GDA path).  I will let you know once the release branch has been created.

**Comment by KateFriedman-NOAA** [comment]
> I should have the release/gfsda.v16.3.0 branch created on Friday. I still have a few more changes that need to go into develop before the creation of the branch (including the update to add atmos to the GDA path). I will let you know once the release branch has been created.

Sounds good, thanks @MichaelLueken-NOAA !

**Comment by KateFriedman-NOAA** [comment]
@HelinWei-NOAA Looks like we also need an update in the GLDAS to add the new `atmos` subfolder into the path for the PRCP CPC gauge files in the GDA. The [following line in `ush/gldas_forcing.sh`](https://github.com/NOAA-EMC/GLDAS/blob/master/ush/gldas_forcing.sh#L43) needs to add `atmos` to the path:

From this:
```
pathp1=$CPCGAUGE/gdas.$sdate/00
```
...to this:
```
COMPONENT=${COMPONENT:-"atmos"}
pathp1=$CPCGAUGE/gdas.$sdate/00/$COMPONENT
```

Would you mind making that change and cutting a new GLDAS tag? Thanks!

**Comment by KateFriedman-NOAA** [comment]
@MichaelLueken-NOAA Can you make the changes to add `atmos` into the GSI `gfsda.v16.2.0.1` tag version as well? We'll want it in the global-workflow `dev_v16` branch for users who will run GFSv16.2.0 before GFSv.16.3.0 is available and after the WCOSS2 go-live date. Thanks!

**Comment by MichaelLueken** [comment]
> @MichaelLueken-NOAA Can you make the changes to add `atmos` into the GSI `gfsda.v16.2.0.1` tag version as well? We'll want it in the global-workflow `dev_v16` branch for users who will run GFSv16.2.0 before GFSv.16.3.0 is available and after the WCOSS2 go-live date. Thanks!

@KateFriedman-NOAA The `gfsda.v16.2.0.1` tag has been updated to include `atmos` in the `DMPDIR` paths for the JJOBS via `$COMPONENT`.  The new tag was created at [4f42f7b](https://github.com/NOAA-EMC/GSI/commit/4f42f7be9cfe5c8a4867b2493cebd8e76606605a).

**Comment by KateFriedman-NOAA** [comment]
> The gfsda.v16.2.0.1 tag has been updated to include atmos in the DMPDIR paths for the JJOBS via $COMPONENT. The new tag was created at [4f42f7b](https://github.com/NOAA-EMC/GSI/commit/4f42f7be9cfe5c8a4867b2493cebd8e76606605a).

Awesome, thanks @MichaelLueken-NOAA !

**Comment by MichaelLueken** [comment]
@KateFriedman-NOAA The final changes have been merged to the authoritative GSI repository's `develop` branch and the `release/gfsda.v16.3.0` release branch has been created off of `develop`.  I should give fair warning that the likelihood of global-workflow working with the `release/gfsda.v16.3.0` release branch is fairly slim (due to removal of `fv3gfs_ncio` from the GSI repository, changes in location of installed executables, and naming of the executables following the CMake refactor).

**Comment by KateFriedman-NOAA** [comment]
Update to GLDAS has been made and a new tag cut by @HelinWei-NOAA : 
https://github.com/NOAA-EMC/GLDAS/releases/tag/gldas_gfsv16_release.v.2.1.0

**Comment by KateFriedman-NOAA** [comment]
All tasks for this issue are now complete. The new WCOSS2 GDA job is populating a test GDA with an `atmos` subfolder. As go-live on WCOSS2 occurs I will change the WCOSS2 GDA job to begin populating the official GDA folder. The work related to adding the `atmos` subfolder is complete though, so I will now close this issue. Thanks all!
