### ISSUE TITLE
Change in staged location of prototype ICs

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#810]
**Description**
The climate disk space on hera is changing from /scratch2 to /scratch1 therefore the staged location of ICs for the coupled prototype ICs will change.   A PR with the updated location will be submitted as soon as the data is moved.  **Note that this will mean that if trying to run old tags of the workflow on hera, the IC location will have to be updated manually.** 

**Requirements**
Point to updated  staged coupled IC location 

**Acceptance Criteria (Definition of Done)**
New IC location is used in the workflow. 

**Dependencies**
Data must be moved first (deadline of 6/2 for move).

**Comment by WalterKolczynski-NOAA** [comment]
Can we leave behind a symlink on scratch2?

**Comment by JessicaMeixner-NOAA** [comment]
> Can we leave behind a symlink on scratch2?

The /scratch2/NCEPDEV/climate space will be removed, so no.

**Comment by JessicaMeixner-NOAA** [comment]
The new directory is here: 

/scratch1/NCEPDEV/climate/role.ufscpara/IC
