### ISSUE TITLE
Add atm-only ensemble free-forecast

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#822]
**Description**
As we move towards the merger of GEFS into the GFS system, global workflow needs to be updated to incorporate additional capability to run forecast ensembles beyond that used for EnKF.

**Requirements**
Run forecast job from pre-staged GEFS initial conditions from the operational run. The additional jobs to produce those initial conditions will be added in a separate future issue.

Since post is now run in-line, the forecast job should generate the appropriate master grib2 files, including the ensemble headers, without the need for a separate post job.

**Acceptance Criteria (Definition of Done)**
Ability to run atm-only forecast job successfully for an ensemble from GEFS initial conditions that produces the correct master grib files.

**Dependencies**
Reorganize COM (#761)
Update workflow setup scripts (#789)
Add GEFS IC retrieval (#834)

**Comment by XianwuXue-NOAA** [comment]
@WalterKolczynski-NOAA Since the PR is merged in to develop. So we can close this issues.

**Comment by WalterKolczynski-NOAA** [comment]
> @WalterKolczynski-NOAA Since the PR is merged in to develop. So we can close this issues.

Next time, make sure the has a line that says `Fixes #822` at the end so the issue is properly attached and closed when merged.

**Comment by XianwuXue-NOAA** [comment]
I

> > @WalterKolczynski-NOAA Since the PR is merged in to develop. So we can close this issues.
> 
> Next time, make sure the has a line that says `Fixes #822` at the end so the issue is properly attached and closed when merged.

In git commit? like the Refs: #822?

**Comment by WalterKolczynski-NOAA** [comment]
> I
> 
> > > @WalterKolczynski-NOAA Since the PR is merged in to develop. So we can close this issues.
> > 
> > 
> > Next time, make sure the has a line that says `Fixes #822` at the end so the issue is properly attached and closed when merged.
> 
> In git commit? like the Refs: #822?

In the PR, you need to use `Fixes` or `Closes`. I also don't think you can include a colon if you want GitHub to pick up on it automatically.

**Comment by XianwuXue-NOAA** [comment]
> > I
> > > > @WalterKolczynski-NOAA Since the PR is merged in to develop. So we can close this issues.
> > > 
> > > 
> > > Next time, make sure the has a line that says `Fixes #822` at the end so the issue is properly attached and closed when merged.
> > 
> > 
> > In git commit? like the Refs: #822?
> 
> In the PR, you need to use `Fixes` or `Closes`. I also don't think you can include a colon if you want GitHub to pick up on it automatically.

Great. Thanks.
