### ISSUE TITLE
Add ensemble atmosphere initial condition generation for cycled mode

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#825]
**Description**
As we move towards the merger of GEFS into the GFS system, global workflow needs to be updated to incorporate the ability to create GEFS atmosphere initial conditions.

**Requirements**
Need to be able to generate free-forecast ensemble initial conditions from the EnKF of the previous cycle run by the same workflow when running in cycled mode.

**Acceptance Criteria (Definition of Done)**
The ability to generate ensemble initial conditions for a free-forecast ensemble in the same manner as GEFS using EnKF produced by the same workflow in cycled mode.

**Dependencies**
Update workflow setup scripts (https://github.com/NOAA-EMC/global-workflow/issues/789)
Restore cycled capability in develop (#711)

**Comment by aerorahul** [comment]
We will not be attempting to recreate GEFSv12 IC generation from previous cycle GDAS ensemble forecast.
This issue will not be worked on for GEFSv13.
