### ISSUE TITLE
Update archive to handle ensembles

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#832]
**Description**
As we move towards the merger of GEFS into the GFS system, global workflow needs to be updated to archive the additional output created when running a forecast ensemble.

**Requirements**
Need to expand the archive job to handle forecast ensemble outputs. Due to the multiplicity of the data, this may require a reevaluation of what gets archived, at least for ensemble members.

**Acceptance Criteria (Definition of Done)**
Given all of the workflow products, properly archive the key ensemble files to HPSS.

**Dependencies**
Add atm ensemble product generation (#823)

**Comment by aerorahul** [comment]
@EricSinsky-NOAA FYI

**Comment by WalterKolczynski-NOAA** [comment]
Duplicate of #2698
