### ISSUE TITLE
Generate workflow xml file used for the NG-GODAS applicaion

### ISSUE THREAD

**Issue by binli2337** [NOAA-EMC/global-workflow#838]
**Description**

Modify etup_workflow_fcstonly.py, setup_expt.py and several configuration files to generate the workflow xml file used by the NG-GODAS (MOM6_CICE6_CDEPS_DATM) application. A pull request will be submitted related to this issue. This issue is related to issue #785 .

**Requirements**

After modifications to the scripts, a new workflow xml file can be generated for the NG-GODAS application. Those modifications will not impact the current applications (ATM, ATMW, S2S and S2SW). 

**Acceptance Criteria (Definition of Done)**

A new xml file can be generated for the NG-GODAS application.

**Dependencies**
No

**Comment by WalterKolczynski-NOAA** [comment]
IIRC, it was decided not to bring this into develop and a separate branch was made instead. That branch has since been cleaned up since Bin Li left.
