### ISSUE TITLE
Update the link to historical GSI fix files in parm/config.anal for gfsv16.3 parallel experiment

### ISSUE THREAD

**Issue by emilyhcliu** [NOAA-EMC/global-workflow#877]
The gfsv16.3 parallel testing begins from 20211015 18Z.  
The relevant GSI fix files (convinfo and satinfo) were modify to include the observations to be assimilated operationally in real-time.  

The /parm/config.anal is modified for exporting the updated convinfo and satinfo files.
The correponding changes in the convinfo and satinfo files will be made in the GSI repository (gfsda.v16.3 release branch)

**Comment by KateFriedman-NOAA** [comment]
@emilyhcliu I think this is complete, please confirm and we can close this issue. Thanks!

**Comment by WalterKolczynski-NOAA** [comment]
@emilyhcliu Was this completed so we can close?

**Comment by emilyhcliu** [comment]
I got an email from Carlos (NCO). He still has a few questions.  I will forward the emails to POCs.  

Emily Huichun Liu

**Comment by emilyhcliu** [comment]
Oh sorry.   This is for a specific issue.  
Yes. This one can be closed.    

Thanks.  
Emily. 

Emily Huichun Liu
