### ISSUE TITLE
Update fix files 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#880]
**Description**
Add additional fix files for glopara/fix_NEW/fix_cpl for the following resolution combinations: 
aC192o050 aC48o400 aC96o100 
which exist in the regression test system but are not part of the g-w fix files.   

These files can be found here: 
/scratch1/NCEPDEV/climate/Jessica.Meixner/updatefornewwavemesh/global-workflow/fix/fix_cpl/* 
(These are part of the input for rt.sh so if the location is needed on another machine, just let me know and I can give you that instead). 

 An additional fix file for the wave model is needed in  glopara/fix_NEW/fix_wave 
which can be found on hera here: 
/scratch1/NCEPDEV/climate/Jessica.Meixner/updatefornewwavemesh/global-workflow/fix/fix_wave/mesh.gwes_30m.nc
(it's also in the rt input so it's likely on all machines if a different machine is easier).  

**Requirements**
It was noted by @NeilBarton-NOAA that the fix_cpl files were missing and would be useful to have in the official locations.  The fix_wav updated file is needed for p8. 

**Acceptance Criteria (Definition of Done)**
New fix files included in the global-workflow glopara fix_NEW directory 

**Dependencies**
None

**Comment by WalterKolczynski-NOAA** [comment]
@JessicaMeixner-NOAA can you just confirm this is a fix directory update only, with no code changes needed?

**Comment by KateFriedman-NOAA** [comment]
@JessicaMeixner-NOAA Do you have copies on WCOSS1 or WCOSS2 by chance? Thanks!

**Comment by JessicaMeixner-NOAA** [comment]
@WalterKolczynski-NOAA yes, this is just fix directory update, no code changes.  (I figured this was easier than an email, etc.) 

The cpl_fix files are on wcoss2 here: /lfs/h2/emc/nems/noscrub/emc.nems/RT/NEMSfv3gfs/input-data-20220414/CPL_FIX 

The fix_wav file is on wcoss2 here: /lfs/h2/emc/couple/noscrub/Jessica.Meixner/forkate/mesh.gwes_30m.nc

**Comment by WalterKolczynski-NOAA** [comment]
I think we prefer it to be an issue anyway. I just wanted to confirm.

**Comment by KateFriedman-NOAA** [comment]
@JessicaMeixner-NOAA I have pulled the new `fix_wave` and `fix_cpl` fix files into `fix_NEW` and rsync'd them to Venus, Mars, Dogwood, Cactus, Hera, and Jet. I will rsync them to Orion after today's monthly maintenance concludes.

```
fix_NEW/fix_cpl/
fix_NEW/fix_cpl/aC192o050/
fix_NEW/fix_cpl/aC192o050/grid_spec.nc
fix_NEW/fix_cpl/aC48o400/
fix_NEW/fix_cpl/aC48o400/grid_spec.nc
fix_NEW/fix_cpl/aC96o100/
fix_NEW/fix_cpl/aC96o100/grid_spec.nc
fix_NEW/fix_wave/
fix_NEW/fix_wave/mesh.gwes_30m.nc
```

I am also making a new tarball of `fix_NEW` on HPSS (/5year/NCEPDEV/emc-global/emc.glopara/fv3fix/fix_NEW_20220629.tar).

This is likely the last time I will update fix files on WCOSS1 (Mars/Venus) and use them as the primary copies. Will now use the WCOSS2 fix sets as primaries for updates moving forward.

**Comment by KateFriedman-NOAA** [comment]
The Orion `fix_NEW` set are also now updated.

**Comment by WalterKolczynski-NOAA** [comment]
Any reason not to close this issue out?
