### ISSUE TITLE
workflow updates: new ice climatology, cplmode=nems_orig for non-fractional grid, add cldfra 3D cloud in all diag_table

### ISSUE THREAD

**Issue by yangfanglin** [NOAA-EMC/global-workflow#886]
A new ICE climatology based IMS and NIC data has been developed to  replace the CFSR ice climatology used by UFS applications.  This new IMS-NIC climatology has a much higher resolution than CFSR and is based on more recent observations. ( Credit: Mike Barlage, Shan Sun,  and many others participated in the [development ](https://docs.google.com/presentation/d/1rf8Nrghtfi-3k0AThRR9rnyVrBzSJoqlFgKqMLJJeJ0/edit#slide=id.gf34d33e052_0_5)and [discussion ](https://docs.google.com/document/d/1PzNtcTwkJyzWAuGrQj4B6g41OcdgZf0fLbLK0OV-000/edit)of this new dataset).  This new dataset has been tested in both coupled and uncoupled UFS experiments. 

1) please copy /scratch1/NCEPDEV/stmp2/Michael.Barlage/data/ice_climatology/IMS-NIC.blended.ice.monthly.clim.grb from Hera to ./fix_NEW/fix_am on all supported platforms.

2) Please update ./ush/forecast_postdet.sh in global workflow
    replace
    FNAISC=${FNAISC:-"$FIX_AM/CFSR.SEAICE.1982.2012.monthly.clim.grb"}
   with 
   FNAISC=${FNAISC:-"$FIX_AM/IMS-NIC.blended.ice.monthly.clim.grb"}

3) make the same change in ./ush/global_cycle.sh

@GeorgeGayno-NOAA  George, please check if you need to make corresponding updates in ufs_util.

**Comment by JessicaMeixner-NOAA** [comment]
@yangfanglin this is supposed to be used by p8, correct?   Is this another case of only being used in the coupled model and not in standalone atm or is neither of the modes using the new climatology?    I thought all updates in fix files were in the PR from @ChunxiZhang-NOAA in the PR here: https://github.com/NOAA-EMC/global-workflow/pull/795

**Comment by GeorgeGayno-NOAA** [comment]
`./ush/global_cycle.sh` is owned by UFS_UTILS. I can open an issue to change the default FNAISC.

**Comment by JessicaMeixner-NOAA** [comment]
@yangfanglin @barlage this does not appear to be getting used in the ufs-weather-model regression tests either.  Is that correct?

**Comment by yangfanglin** [comment]
@JessicaMeixner-NOAA This new climatology should be used in both coupled and atmos-only runs; however, it does not have to be included in p8.   We can add them after p8, or whenever both the model RT and workflow scripts have been updated.  The first thing to do (@KateFriedman-NOAA ) is to make this file available on all platforms.   @ChunxiZhang-NOAA please check if it is still possible for  you to include this in the PR you are updating lheatstrg and dt_inner.    I'd also hope this one-line change for g-w can also be combined with another existing g-w PR.  Otherwise, I can tale a few minutes to create a PR.,

**Comment by ChunxiZhang-NOAA** [comment]
@JessicaMeixner-NOAA @yangfanglin I can add these changes into the PR for updating lheatstrg and dt_inner in Regression tests.

**Comment by KateFriedman-NOAA** [comment]
>please copy /scratch1/NCEPDEV/stmp2/Michael.Barlage/data/ice_climatology/IMS-NIC.blended.ice.monthly.clim.grb from Hera to ./fix_NEW/fix_am on all supported platforms.

@yangfanglin I copied this new fix file into `fix_NEW/fix_am` and rsync'd it to the other platforms (except Jet which is down for maintenance).

**Comment by ChunxiZhang-NOAA** [comment]
This is an issue created for global-workflow, but anyone can help to copy the new data to the RT's FV3_fix directory?

**Comment by yangfanglin** [comment]
One more change needs to be added to the workflow. In ./oarm/config/config.fcst,  please add the following if block for running the model without fractional grid.  

export FRAC_GRID=".true."
export cplmode="nems_frac"
if [ $FRAC_GRID = ".false." ]; then
  export cplmode="nems_orig"
fi

**Comment by yangfanglin** [comment]
A work flow branch has been created to add new ice climatology, set cplmode=nems_orig for non-fractional grid, and add cldfra 3D cloud in all diag_table 

https://github.com/yangfanglin/global-workflow/tree/update_scripts

       modified:   parm/config/config.fcst
        modified:   parm/parm_fv3diag/diag_table
        modified:   parm/parm_fv3diag/diag_table_cpl
        modified:   parm/parm_fv3diag/diag_table_da
        modified:   ush/forecast_postdet.sh

**Comment by yangfanglin** [comment]
pull request created https://github.com/NOAA-EMC/global-workflow/pull/902
