### ISSUE TITLE
Remove gfsmetp gfsarch dependency in dev_v16, release/gfs.v16.3.0

### ISSUE THREAD

**Issue by malloryprow** [NOAA-EMC/global-workflow#907]
**Description**
Back in late 2021, a commit was done to develop to update the gfsmetp dependencies (https://github.com/NOAA-EMC/global-workflow/commit/fdffeaaf013f638ac43ad421981e48fabf7a7070); it removed the dependency on the gfsarch from the previous GFS cycle. I met with @emilyhcliu today to figure out why .stat files for her experiment start date were not being produced for her GFSv16.3 experiment. We discovered that the setup_workflow.py script still contained the gfsmetp jobs having a dependency on the gfsarch from the previous GFS cycle. This is in the dev_v16 and release/gfs.v16.3.0 branches and should be removed.

**Requirements**
In both setup_workflow.py and setup_workflow_fcstonly.py, the gfsmetp on gfsarch removed (lines below):

> dep_dict = {'type':'task', 'name':f'{cdump}arch', 'offset':'-&INTERVAL_GFS;'}
> deps.append(rocoto.add_dependency(dep_dict))

**Acceptance Criteria (Definition of Done)**
The gfsmetp jobs no longer have a dependency on gfsarch from the previous cycle.

**Dependencies**

**Comment by KateFriedman-NOAA** [comment]
Good catch @malloryprow ! Please submit a PR into `dev_v16` with this two line change and I'll review/merge it into `dev_v16` once it's confirmed to be working in @emilyhcliu's test. I'll then sync merge it into `release/gfs.v16.3.0`. Thanks!

**Comment by emilyhcliu** [comment]
My test is running.  I will add comment once I have the test result.

**Comment by KateFriedman-NOAA** [comment]
This is working in my low res tests on Hera and Orion. Any update from your tests @emilyhcliu ?

**Comment by aerorahul** [comment]
> My test is running. I will add comment once I have the test result.

@emilyhcliu 
Can we merge this PR or are you still waiting for a test result?

**Comment by emilyhcliu** [comment]
@aerorahul @malloryprow 
I tested the changes and the metplus worked as expected.  
This is good to go!

**Comment by KateFriedman-NOAA** [comment]
Issue is now complete. Closing. Thanks @malloryprow !
