### ISSUE TITLE
Extend coupled IC job to handle ensemble staging

### ISSUE THREAD

**Issue by XianwuXue-NOAA** [NOAA-EMC/global-workflow#911]
**Description**
Allow staging of ensemble initial conditions for GEFS through the `coupled_ic.sh` job for `forecast-only` mode.

**Requirements**
- create  a j-job `JGLOBAL_STAGE_IC` and ex-script `exglobal_stage_ic.sh` to allow staging of initial conditions for GFS and GEFS **forecast-only** experiments.
- `coupled_ic.sh` (rename to `stage_ic.sh`) should be the rocoto wrapper on `JGLOBAL_STAGE_IC`.

The initial conditions should be ready to go -- i.e. all pre-processing has been done prior to staging.

**Acceptance Criteria (Definition of Done)**
Call sequence:
`stage_ic.sh -> JGLOBAL_STAGE_IC -> exglobal_stage_ic.sh`

**Dependencies**
May need an update in the files situated under `BASE_CPLIC` that serves as a repository for ICs.

**Comment by WalterKolczynski-NOAA** [comment]
OBE
