### ISSUE TITLE
Two sources of component versions

### ISSUE THREAD

**Issue by christopherwharrop-noaa** [NOAA-EMC/global-workflow#92]
There are currently two sources of truth for the versions of components to be checked out:

* Externals.cfg
* sorc/checkout.sh

This is a bug. 

This bug is causing consistency problems for downstream users of the global-workflow. All users of global-workflow need assurance that what they are checking out is correct. But that is impossible to guarantee because there are currently two sources of truth for controlling versions of global-workflow components. Consistency requires a single source of truth because reviewers of merges into feature/gfsv16b are fallible and cannot be guaranteed to 100% of the time ensure that changes to one of the above is also made in the other. Furthermore, the official instructions for checkout out the code and building state that `checkout_externals` is to be used for obtaining the code, not `sorc/checkout.sh`. Yet, `sorc/checkout.sh` is retained and is being updated by developers without making the same change in `Externals.cfg`.

One of the following paths needs to be taken:

* Delete `sorc/checkout.sh`
* Delete `Externals.cfg` and change the instructions in `README.md` to use `sorc/checkout.sh`

**Comment by KateFriedman-NOAA** [comment]
@christopherwharrop-noaa The checkout.sh script will be removed at the end of the v16 work but not before. I have updated README.md to revert it back to tell users to use checkout.sh and hopefully avoid future tickets like this.

Commit done at https://github.com/NOAA-EMC/global-workflow/commit/4f8d5a5f28c7120905fe36e9254f0199da986188
