### ISSUE TITLE
Port NCL scripts to python

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#923]
**Description**
NCL was deprecated in Sep 2019 and discontinued the follow summer. As such, it is no longer available on the operational machine and we should be moving to non-NCL alternatives for all scripts.

For global-workflow directly, this is mostly the new ice and ocean post. Otherwise. there are some gsi_utility plotting scripts and others are located in UFS components, none of which I think we use.

```
./sorc/ufs_model.fd/AQM/src/model/CMAQ/PREP/wbdust/scripts/monthly_to_daily.ncl
./sorc/ufs_model.fd/MOM6-interface/MOM6/pkg/CVMix-src/reg_tests/shear/plot_PP_diff_coeffs.ncl
./sorc/ufs_model.fd/MOM6-interface/MOM6/pkg/CVMix-src/reg_tests/shear/plot_LMD_diff_coeffs.ncl
./sorc/ufs_model.fd/MOM6-interface/MOM6/pkg/CVMix-src/reg_tests/double_diff/plot_diff_coeffs.ncl
./sorc/ufs_model.fd/MOM6-interface/MOM6/pkg/CVMix-src/reg_tests/kpp/plot_flux_profiles.ncl
./sorc/ufs_model.fd/MOM6-interface/MOM6/pkg/CVMix-src/reg_tests/kpp/compare_interpolation_methods.ncl
./sorc/ufs_model.fd/MOM6-interface/MOM6/pkg/CVMix-src/reg_tests/kpp/plot_bulk_Rich.ncl
./sorc/ufs_model.fd/MOM6-interface/MOM6/pkg/CVMix-src/reg_tests/tidal-Simmons/plot_diff_coeffs.ncl
./sorc/ufs_model.fd/MOM6-interface/MOM6/pkg/CVMix-src/reg_tests/tidal-Simmons/plot_tidal_energy_map.ncl
./sorc/ufs_model.fd/MOM6-interface/MOM6/pkg/CVMix-src/reg_tests/common/plot_settings.ncl
./sorc/ufs_model.fd/MOM6-interface/MOM6/pkg/CVMix-src/reg_tests/common/version_consistency.ncl
./sorc/ufs_model.fd/MOM6-interface/MOM6/pkg/CVMix-src/reg_tests/Bryan-Lewis/plot_diff_coeffs.ncl
./sorc/gsi_utils.fd/src/radar_process/reflectivity/plot_compositeRef.ncl
./sorc/gsi_utils.fd/src/Analysis_Utilities/plot_cost_grad/GSI_cost_gradient.ncl
./sorc/gsi_utils.fd/src/Analysis_Utilities/plots_ncl/GSI_singleobs_arw.ncl
./sorc/gsi_utils.fd/src/Analysis_Utilities/plots_ncl/Analysis_increment.ncl
./sorc/gsi_utils.fd/src/Analysis_Utilities/plots_ncl/fill_nmm_grid2.ncl
./sorc/gsi_utils.fd/src/Analysis_Utilities/plots_ncl/GSI_singleobs_nmm.ncl
./sorc/gsi_utils.fd/src/Analysis_Utilities/plots_ncl/Analysis_increment_nmm.ncl
./ush/ocnpost.ncl
./ush/icepost.ncl
```

**Requirements**
Replace all NCL scripts with scripts that accomplish the same task in supported languages (likely python).

**Acceptance Criteria (Definition of Done)**
No scripts actively used by global-workflow using NCL, with replacement scripts that do the same thing, ideally written in python.

**Dependencies**
None

**Comment by WalterKolczynski-NOAA** [comment]
Probably @JessicaMeixner-NOAA or someone she can identify. There's not a big rush, but I also don't think we'll be able to run the system on WCOSS2 until this is completed.

**Comment by jiandewang** [comment]
@WalterKolczynski-NOAA for all those ncl scripts under MOM6, they are not being used at all

**Comment by WalterKolczynski-NOAA** [comment]
> @WalterKolczynski-NOAA for all those ncl scripts under MOM6, they are not being used at all

Great, hopefully MOM6 can just remove them then. But, I'm less worried about UFS as long as we're not using the scripts ourselves, as the wider community might want to keep them for plotting for the time being. That said, it's probably a good idea to have a similar UFS (and component) issues to remove them at some point, since NCL is past EOL and who knows how much longer anyone will be able to use it.

**Comment by JessicaMeixner-NOAA** [comment]
@WalterKolczynski-NOAA MOM6 likely has other applications using the scripts in sorc/ufs_model.fd/MOM6-interface/MOM6 and removing them is likely out of our control.  

./ush/ocnpost.ncl and /ush/icepost.ncl are being used for the ocean/ice post and these will need to be converted to some other language.

**Comment by WalterKolczynski-NOAA** [comment]
@JessicaMeixner-NOAA has anyone started working on the ocean and ice post scripts yet? We won't be able to run coupled on WCOSS2 until they've been replaced.

**Comment by JessicaMeixner-NOAA** [comment]
@WalterKolczynski-NOAA  - I actually just had a conversation with @AvichalMehra-NOAA about this again.  The current issue is that there is no one in MDAB-C with NCL knowledge so he's hoping someone from VVPPPG can be engaged.

**Comment by DeniseWorthen** [comment]
As the original author of the NCL post scripts for ice and ocean, I would suggest pythonizing the scripts using the geocat examples page (https://geocat-examples.readthedocs.io/en/latest/). From what I can determine, geocat is a python based tool which leverages matplotlib and cartopy. It would probably be best for someone w/ more experience in how this all ties into a particular Python installation to determine if this is a viable option for WCOSS2.

**Comment by JessicaMeixner-NOAA** [comment]
The script from RTOFS that converts from tripolar to netcdf uses:  intel/19.1.3.304 and  cdo/1.9.8
and the script is here:  /lfs/h1/ops/prod/packages/rtofs.v2.3.0/ush/rtofs_nc2grib2.sh

VVPPPG uses CDO in EVS as well. 

While xESMF is not allowed on WCOSS, ESMPy (which some have confirmed is on wcoss2 via the ESMF installation/library) might be another alternative which could use the already generated ESMF weights.

**Comment by JessicaMeixner-NOAA** [comment]
An example from @bbakernoaa on using ESMPy: https://github.com/bbakernoaa/regrid_fengsha_esmpy

**Comment by WalterKolczynski-NOAA** [comment]
@JessicaMeixner-NOAA @aerorahul Do we have a final decision from management on whether this functionality will be required or not, and if so who is going to do the work?

**Comment by JessicaMeixner-NOAA** [comment]
@WalterKolczynski-NOAA no we do not.  I don't think we'll know for a while.

**Comment by EricSinsky-NOAA** [comment]
@JessicaMeixner-NOAA Since this functionality may be needed for the GEFS reforecast, I have been working on porting `./ush/ocnpost.ncl` to python on WCOSS2 using packages such as ESMPy and netCDF4.

**Comment by aerorahul** [comment]
@HenryWinterbottom-NOAA has a working bidirectional utility that can interpolate to/from tripolar/lat-lon grids using pre-generated weights.

**Comment by HenryRWinterbottom** [comment]
I am a bit late to this conversation, but we have built a package that has (1) ported the NCL methods to Python and (2) can handle the "back-and-forth" for remapping between projections using ESMF coefficients.

The heavy lifting is done by xESMF to generate the remapping files, which is done offline if I am not mistaken. Those coefficients can then be read in via FORTRAN, CPP, Python, etc., to do the remapping. The ESMF package is no longer required once the coefficients are defined. 

For example, here is the snippet of FORTRAN that remaps between projections provided the respective weights have been pre-computed.

```
do i = 1, n_s
       
       ! Compute the interpolated variable.
       output_var(row(i)) = output_var(row(i)) + S(i)*input_var(col(i))
       
end do ! do i = 1, n_s
```

**Comment by aerorahul** [comment]
@HenryWinterbottom-NOAA 
If I understand correctly,  there are 2 steps to performing interpolation:
1. pre-generate interpolation weights using `xESMF` -- this is a one time activity between the various source and target resolutions and can be done on any of the RDHPCS machines since `xESMF` is not available on WCOSS2 (it does not have to be available)
2. use the pre-generated weights from step 1 to perform the interpolation using the Fortran utility you have created.

**Comment by HenryRWinterbottom** [comment]
> @HenryWinterbottom-NOAA If I understand correctly, there are 2 steps to performing interpolation:
> 
>     1. pre-generate interpolation weights using `xESMF` -- this is a one time activity between the various source and target resolutions and can be done on any of the RDHPCS machines since `xESMF` is not available on WCOSS2 (it does not have to be available)
> 
>     2. use the pre-generated weights from step 1 to perform the interpolation using the Fortran utility you have created.

@aerorahul Yes, that is exactly it. 

This was an exercise that came out of NGGPS and I have tried to package it as best can for future (now??) applications.

**Comment by HenryRWinterbottom** [comment]
Is this still alive? If so I'd be happy to take it on.

**Comment by HenryRWinterbottom** [comment]
@JessicaMeixner-NOAA Are there existing ESMF coefficient files that are to be used for the remapping?

**Comment by JessicaMeixner-NOAA** [comment]
@HenryWinterbottom-NOAA Yes - @EricSinsky-NOAA has done this task in https://github.com/NOAA-EMC/global-workflow/pull/1736 using these same weights.

**Comment by EricSinsky-NOAA** [comment]
@HenryWinterbottom-NOAA Existing ESMF weights can be found in the global-workflow fix directory `./fix/reg2grb2/`

**Comment by HenryRWinterbottom** [comment]
Thank you @EricSinsky-NOAA.
