### ISSUE TITLE
Adding EFSOI to xml workflow generator

### ISSUE THREAD

**Issue by AndrewEichmann-NOAA** [NOAA-EMC/global-workflow#925]
**Description**

Change workflow/setup_xml.py to generate workflow to run EFSOI

**Acceptance Criteria (Definition of Done)**

Generates workflow that runs EFSOI tasks as before refactoring (on EFSOI development branch)

**Dependencies**

No current dependencies

This is required to have EFSOI functioning in global-workflow

**Comment by AndrewEichmann-NOAA** [comment]
@aerorahul @WalterKolczynski-NOAA 

A general question: Certain ensemble tasks that are mirrored in EFSOI tasks (eupd, ecen, esfc, efcs, and epos)  seem to be able to take a cdump of gdas or gfs. I have never seen these used with gfs - would the choice between gdas or gfs relevant to EFSOI?

**Comment by aerorahul** [comment]
@AndrewEichmann-NOAA 

The option to execute the perturbation update via the EnKF is operationally (default) done in the late (gdas) cycle.  However, it can also be executed in the early (gfs) cycle, or both.  This is controlled by the variable `EUPD_CYC` in `config.base`.

In PR #674, there were outstanding questions regarding duplication of the `config` files for EFSOI.  Will you be able to address those?

**Comment by AndrewEichmann-NOAA** [comment]
@aerorahul 

Yes, most of those now call the config files of their corresponding standard tasks.

**Comment by AndrewEichmann-NOAA** [comment]
Now in https://github.com/NOAA-EMC/global-workflow/pull/674

**Comment by AndrewEichmann-NOAA** [comment]
Folding into issue https://github.com/NOAA-EMC/global-workflow/issues/673
