### ISSUE TITLE
ocnpost dependency on logfHHH.txt is incorrect

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/global-workflow#935]
https://github.com/NOAA-EMC/global-workflow/blob/f04f3ba4dfd5b358aea425f65f82d40917597776/workflow/rocoto/workflow_tasks.py#L592

Ocean post-processing job is currently dependent upon a file `logfHHH.txt`.  The `logfHHH.txt` is a file written out by the write component in `fv3atm`.  
What would be the correct dependency for ocean post-processing be that depends on file(s) written out by the ocean component of the model?
This information is necessary to properly define the dependencies when running a data-atmosphere coupled model where the `logfHHH.txt` files are not produced by the model.

@JessicaMeixner-NOAA, who would be the appropriate person to request additional data points?

**Comment by JessicaMeixner-NOAA** [comment]
@aerorahul I believe @jiandewang should be able help you with this.  The non-atm components are not writing out equivalent "the file is done writing" type files.  The ocean post processes both ocean and ice files, so the dependency should likely be on both of their file names.

**Comment by jiandewang** [comment]
@aerorahul neither ocean nor ice will output any flag file so if you want to change the current dependency then the only solution is by using the ocean and ice output files

**Comment by aerorahul** [comment]
@jiandewang That is even better.
Just let us know what are the files that are written out by the ocean and ice components that the ocnpost job depends on.
Also, how do we know that the file being written out is complete and not in the process of writing.  Simply checking for an existence of a file might not be enough in case writing takes time.
Perhaps this is something that can be developed in the ocean and ice components.  The atm logfHHH.txt files were specifically introduced for that purpose -- to avoid false triggering of atmospheric post-processing while the output is being flushed to disk.

**Comment by WalterKolczynski-NOAA** [comment]
Is the writing synchronous with the model or asynchronous? If it is synchronous, we can just look for the next output file to appear in the interim. Alternatively, data dependencies have an optional "age" we could use to see how long the file has existed.

Ultimately, the best solution would be a log file as long as we are using data dependencies. Even better than that would be an ecflow trigger if we move away from rocoto to ecflow-only.

**Comment by jiandewang** [comment]
@WalterKolczynski-NOAA using the next output file is a good idea, then what about the last one ? for ocean writing is asynchronous. Final solution is we need FMS has this kind of capability to write out a flag file to indicate writing output is done.

**Comment by WalterKolczynski-NOAA** [comment]
the dependency could be the next file OR the forecast completing, which would catch the last output time. But if writing is completely asynchronous (multiple output times may be written at once), it won't work. If it is async with the model but the writing is still sequential, it would still work.

**Comment by jiandewang** [comment]
> the dependency could be the next file OR the forecast completing, which would catch the last output time. But if writing is completely asynchronous (multiple output times may be written at once), it won't work. If it is async with the model but the writing is still sequential, it would still work.

@WalterKolczynski-NOAA I guess I didn't fully understand what you mean "asynchronous". The writing is sequential. What I mean previously is when model is doing 7th hour of integration, the 6th hour of output may not be fully written yet.

**Comment by WalterKolczynski-NOAA** [comment]
That's my fault. Your definition is correct (and what I had in mind), but whether the writing is sequential is really the thing we care about (synchronous would implicitly be sequential).

**Comment by jiandewang** [comment]
> @jiandewang That is even better. Just let us know what are the files that are written out by the ocean and ice components that the ocnpost job depends on. Also, how do we know that the file being written out is complete and not in the process of writing. Simply checking for an existence of a file might not be enough in case writing takes time. Perhaps this is something that can be developed in the ocean and ice components. The atm logfHHH.txt files were specifically introduced for that purpose -- to avoid false triggering of atmospheric post-processing while the output is being flushed to disk.

@aerorahul I don't have the ocean file on disk at this moment, will have that for you shortly.

**Comment by jiandewang** [comment]
> > @jiandewang That is even better. Just let us know what are the files that are written out by the ocean and ice components that the ocnpost job depends on. Also, how do we know that the file being written out is complete and not in the process of writing. Simply checking for an existence of a file might not be enough in case writing takes time. Perhaps this is something that can be developed in the ocean and ice components. The atm logfHHH.txt files were specifically introduced for that purpose -- to avoid false triggering of atmospheric post-processing while the output is being flushed to disk.
> 
> @aerorahul I don't have the ocean file on disk at this moment, will have that for you shortly.

found the files, here is an example:
ocn2012010106.01.2012010100.nc  <--2012010100 is IC date, 012010106 means it is the 6th hour output
ice2012010106.01.2012010100.nc: same as ocean naming style

**Comment by aerorahul** [comment]
Thanks @jiandewang for providing the template of the filenames for updating the dependency.
We will update the dependencies for this filename in ocnpost, but I would like to reiterate that this can/may cause a triggering of the ocean post before the file is flushed to disk completely.

**Comment by jiandewang** [comment]
@aerorahul yes that is my worry too. Say in the near future we double or triple the ocean and ice resolution, writing output may take pretty long time (several minutes). Ideally solution is asking FMS group to have a corresponding flag files.

**Comment by aerorahul** [comment]
@jiandewang @JessicaMeixner-NOAA 
Please open a appropriate issue in the model and escalate as needed -- if necessary.
The `logfHHH.txt` is currently a dependency in the workflow for ocean post-processing.
This file is not written out when the model is run in `data-atmosphere` mode either.

**Comment by JessicaMeixner-NOAA** [comment]
@aerorahul can we temporarily use the files that @jiandewang pointed you to while the longer term issue of getting waves, ice and ocean to write log files for appropriate triggers?   This might mean temporarily we could run into issues of files not being completely written, but at least those files will exist?  As logfHHH.txt file isn't actually an ocean/ice file the same risk exists now.

**Comment by WalterKolczynski-NOAA** [comment]
@jiandewang @JessicaMeixner-NOAA @aerorahul was an issue ever opened for this? If so, would you please link it here so we can track it?

**Comment by JessicaMeixner-NOAA** [comment]
Looks as if we did not open other issues for this.   If this is still something we need to persue, we can open up issues in MOM6 (although that might be FMS not MOM6), WW3 and CICE.

**Comment by jiandewang** [comment]
~ half year ago Marshall helped us raised this requirement in FMS group meeting, but no follow up so far. Let me open an issue under FMS

**Comment by WalterKolczynski-NOAA** [comment]
Similar underlying problem to #1248

**Comment by JessicaMeixner-NOAA** [comment]
WW3 issue: https://github.com/NOAA-EMC/WW3/issues/921

**Comment by JessicaMeixner-NOAA** [comment]
@WalterKolczynski-NOAA and @aerorahul any request on how exactly this log file should look like ?

**Comment by JessicaMeixner-NOAA** [comment]
CICE issue: https://github.com/NOAA-EMC/CICE/issues/57

**Comment by JessicaMeixner-NOAA** [comment]
@jiandewang I am assuming you will take care of the MOM6/FMS issue creation - let me know if I need to instead.

**Comment by WalterKolczynski-NOAA** [comment]
> @WalterKolczynski-NOAA and @aerorahul any request on how exactly this log file should look like ?

@JessicaMeixner-NOAA It's named a "log" file, but it is really just an empty file (as `touch` would make) indicating the output for the forecast time is complete so it isn't processed prematurely. The name is not great, so feel free to use something more appropriate. Ideally standardized across UFS. `${component}_out_complete_f${HHH}` maybe?

**Comment by JessicaMeixner-NOAA** [comment]
@WalterKolczynski-NOAA  I guess I'm asking if you have a request for the name of the file.  "log.ww3.pnt.f${fhr}" , "log.ww3.grd.f$fhr" , do you have requirements or do I have freedom?  Obviously we don't want the same name as the atm model or other components,  but I'm assuming some level of consistency would be nice.

**Comment by WalterKolczynski-NOAA** [comment]
@junwang-noaa Do you have any preference for the format of these file names? It would be good if we can get FV3 updated and have it standard across UFS.

**Comment by junwang-noaa** [comment]
Currently the atmosphere component has logf name as: logfXXX, I'd suggest
having a consistent name: log.$component.fXXX for all the component models.
One log file at each output time for each model component. Some model
component outputs several history files, the log file will be written after
all the files are written. The content of the log file can be the starting
date and forecast time in hours.

Code example:
```
    if (mype == lead_write_task) then

open(newunit=nolog,file='log.'//trim(modelname)//'.f'//trim(cfhour),form='FORMATTED')
        write(nolog,100)nfhour,idate(1:6)
100     format(' completed fv3gfs fhour=',f10.3,2x,6(i4,2x))
      close(nolog)
    endif
```

**Comment by jiandewang** [comment]
just opened a FMS issue https://github.com/NOAA-GFDL/FMS/issues/1140

**Comment by DeniseWorthen** [comment]
@aerorahul The actual ice model output is ``history/iceh_06h.YYYY-MM-DD-SECS.nc`` for 6hourly average (ie, not instantaneous) history fields. At some point it gets renamed to the filename form Jiande gave you. 

While MOM6 output writing time may increase substantially when higher resolutions are reached, that is unlikely to be an issue w/ CICE since we write only 2-d variables----probably less data than writing the 3-D temperature field for MOM6 alone. 

CICE will abort if the file writing is not successfully completed. 

Each variable in CICE has the capability to be written at multiple frequencies, and all variables w/ a given output frequency will be in a single file. The successful writing of each file is already present in the CICE log. That file is named in ice_in 
```
diag_file      = 'ice_diag.d'
```

A message will appear in the main log, for example: `` Finished writing ./history/iceh_06h.2021-03-22-43200.nc``

**Comment by NeilBarton-NOAA** [comment]
If I'm understanding this correctly, the post-process jobs are kicked off from a file written by FV3 and something similar for MOM6 and CICE6 would kick off ocean and ice post-processing. 

I suggest to change the log file from being written by FV3 to be written by the mediator or driver so we are certain all components are past a particular time.

**Comment by JessicaMeixner-NOAA** [comment]
If any component has an asynchronous write capability (atm, wave) the mediator being at a certain time does not ensure that a file has been written out completely.

**Comment by junwang-noaa** [comment]
@NeilBarton-NOAA It might not be possible as each component currently controls its own history output frequency, it may not be the multiple of coupling frequency.

@jiandewang In my opinion, fms won't resolve this issue especially if MOM6 outputs several history files (SST*, OCN*, etc). To kick off the post job, we only need to check this log file to confirm that all the history files at that forecast time have been written out completely. So usually the model component writes out a log file to trigger workflow that will kick off the component post job.

**Comment by DeniseWorthen** [comment]
@aerorahul CICE has multiple streams output available (ie, daily,hourly,monthly). Can I assume only the hourly (in this case 6-hourly) output will be active in the workflow? Otherwise, each output stream would need a unique name. Currently the file is named 'ice.logfHHH'.

**Comment by JessicaMeixner-NOAA** [comment]
@WalterKolczynski-NOAA - This issue essentially came up again as it was observed that some of the HR2 runs did not complete writing the ocean post files before the ocean post acted on them.  We essentially got lucky in other situations.  @jiandewang and I discussed earlier and to add this to FMS the request was denied  but alternatives were suggested (https://github.com/NOAA-GFDL/FMS/issues/1140#issuecomment-1464059048).  Some other alternatives might be to write these files from the MOM6 cap (would have to see where the calls to writing things are done).      Anyone have thoughts on what the best path forward would be a better ocean post dependency would be?    For example, the next time steps output or a log file written by MOM6 but not FMS, or ??????

**Comment by jiandewang** [comment]
I will say using the next time steps output as a flag will be viable way (and is suggested by FMS group)

**Comment by WalterKolczynski-NOAA** [comment]
"Log" files being written by _some_ UFS component would be best. I don't know enough about the inner workings to know if the MOM6 cap is a valid alternative (i.e. written at the appropriate time after FMS is done writing the output).

**Comment by aerorahul** [comment]
I am aware of some work by @junwang-noaa and @DeniseWorthen being done to produce ocean and ice specific log files to indicate completion of processing at forecast hour.

**Comment by KateFriedman-NOAA** [comment]
Are there any updates for this? 

In recent testing I see that the ocnpost jobs still occasionally fail on their first attempt in the workflow because the file they need to process isn't ready or isn't fully ready yet. Fresh example on Orion shows the following timings for the atm.log file that the gfsocnpost_f078_f096 job fires off from, the file that the job actually processes (and dies on), and the log for the job's first attempt:
```
Orion-login-3[20] /work/noaa/stmp/kfriedma/comrot/testffsrunflag$ ll gfs.20210323/12//model_data/ocean/history/ocn2021032712.000.2021032312.nc logs/2021032312/gfsocnpost_f078-f096.log.0 gfs.20210323/12/model_data/atmos/history/gfs.t12z.atm.logf096.txt
-rw-r----- 1 kfriedma stmp      91 Nov 16 15:19 gfs.20210323/12/model_data/atmos/history/gfs.t12z.atm.logf096.txt
-rw-r----- 1 kfriedma stmp 1560348 Nov 16 15:20 gfs.20210323/12//model_data/ocean/history/ocn2021032712.000.2021032312.nc
-rw-r----- 1 kfriedma stmp   49632 Nov 16 15:20 logs/2021032312/gfsocnpost_f078-f096.log.0
```
Perhaps while we wait for ocean/ice log files to be available from the model we can adjust the data dependency to look for those ocn history files instead of the atm log file? That may be tricky with rocoto though because of the ocn filenames.

The job's second attempts always appear to succeed so this isn't critical but I wanted to make note that this is still an issue.

The error in the log, which is kind of funny ("NCO can receive this devilishly inscrutable error......Bad vibes"):
```
+ ocnpost.sh[77]: ncks -x -v vo,uo,so,temp /work/noaa/stmp/kfriedma/comrot/testffsrunflag/gfs.20210323/12//model_data/ocean/history/ocn2021032712.000.2021032312.nc /work/noaa/stmp/kfriedma/comrot/testffsrunflag/gfs.20210323/12//products/ocean/2D/ocn_2D_2021032712.000.2021032312.nc
nco_err_exit(): ERROR Short NCO-generated message (usually name of function that triggered error): nco__open()
nco_err_exit(): ERROR Error code is -101. Translation into English with nc_strerror(-101) is "NetCDF: HDF error"
ERROR: nco__open() unable to open file "/work/noaa/stmp/kfriedma/comrot/testffsrunflag/gfs.20210323/12//model_data/ocean/history/ocn2021032712.000.2021032312.nc"
ERROR NC_EHDFERR Error at HDF5 layer
HINT: NC_EHDFERR errors indicate that the HDF5-backend to netCDF is unable to perform the requested task. 
NCO can receive this devilishly inscrutable error for a variety of possible reasons including: 1) The run-time 
dynamic linker attempts to resolve calls from the netCDF library to the HDF library with an HDF5 libhdf5.a that 
is incompatible with the version used to build NCO and netCDF. 2) An incorrect netCDF4 library implementation 
of a procedure (e.g., nc_rename_var()) in terms of HDF function calls (e.g., HDF5Lmove()) manifests an error or 
inconsistent state within the HDF5 layer. This often occurs during renaming operations 
(https://github.com/Unidata/netcdf-c/issues/597). 3) Attempting to compress or decompress a netCDF4 dataset 
with a non-standard (i.e., non-DEFLATE) filter when the requisite shared library to encode/decode that 
compression filter is not present in either the default location (/usr/local/hdf5/lib/plugin) or in the
user-configurable location referred to by the HDF5_PLUGIN_PATH environment variable. One can determine 
if missing plugin libraries are the culprit by dumping the hidden attributes of the dataset with, e.g., 
ncks --hdn -m in.nc or ncdump -s -h in.nc. Any variables with (hidden) "_Filter" attributes require the 
corresponding shared libraries to be located in HDF5_PLUGIN_PATH. 4) Bad vibes.
nco_err_exit(): ERROR NCO will now exit with system call exit(EXIT_FAILURE)
+ ocnpost.sh[1]: postamble ocnpost.sh 1700169610 1
+ preamble.sh[68]: set +x
End ocnpost.sh at 21:20:19 with error code 1 (time elapsed: 00:00:09)
```

**Comment by HenryRWinterbottom** [comment]
@KateFriedman-NOAA I know I am tagged to work on this issue, but I haven't yet had a chance to try.

**Comment by KateFriedman-NOAA** [comment]
> @KateFriedman-NOAA I know I am tagged to work on this issue, but I haven't yet had a chance to try.

No worries @HenryWinterbottom-NOAA ! Will see if UWM folks know of the status of adding log files for the ocean/ice components.

**Comment by HenryRWinterbottom** [comment]
@KateFriedman-NOAA Thank you!

**Comment by WalterKolczynski-NOAA** [comment]
Looking at a run directory from current develop, ice log files are available but still no ocn log files. Not sure if switching to those would be better in the interim than using atm ones.
