### ISSUE TITLE
Add cycling of non-atmos restarts for DA runs

### ISSUE THREAD

**Issue by NeilBarton-NOAA** [NOAA-EMC/global-workflow#947]
**Description**
Enable the S2SW forecast model to cycle with atmos DA. This is a step toward weakly coupled DA. 

**Requirements**
This is a new feature in which the ocean, ice, and wave restart files will be copied to COM directory to be used for the next  cycling period. The changes are within the scripting and no updated software is needed. 

**Acceptance Criteria (Definition of Done)**
Cycle the S2SW app with atmos DA.

**Dependencies**

**Comment by NeilBarton-NOAA** [comment]
coping of restarts is added to my branch
https://github.com/NeilBarton-NOAA/global-workflow/tree/S2SW_atmosDA_dev

However, workflow/rocoto xml files needs edits. 
1) the gdaswaveprep needs to be removed for the S2S application 
2) the arch tasks causes the error "Error: Extra element task in interleave"

@aerorahul and/or @WalterKolczynski-NOAA. Could you look at these items and create a pull request against the above branch?  Thanks

**Comment by aerorahul** [comment]
@NeilBarton-NOAA 
Like we discussed the other day, can we focus on cycling with `APP=S2S`.
cycling with `APP=ATMW` is also currently broken and is likely a better candidate for resurrecting and testing waves in cycled mode.

I can try and jog my memory about what the `gdaswaveprep` job is doing in the context of cycling.

**Comment by NeilBarton-NOAA** [comment]
@aerorahul To my understanding, gdaswaveprep preps ocean currents from the offline ocean model for the wave model. Since the ocean model is coupled, this task isn't needed. @JessicaMeixner-NOAA may have more details.

**Comment by JessicaMeixner-NOAA** [comment]
GDASwave prep is needed to prep current and ice input if using APP=ATMW.    Starting with S2S and moving to S2SW also sounds like a good idea to me.  It's been a while since I know someone has run S2S only, so might triple check a free-forecast run works before diving into cycling.

**Comment by aerorahul** [comment]
Just an FYI, I ran a single `CDATE` case of `APP=S2S` run this week for PR #970.  I however was not paying attention to the correctness of the free-forecast model.

**Comment by JessicaMeixner-NOAA** [comment]
@aerorahul I would expect an immediate error or for it to work so I'd assume things are good to go!

**Comment by aerorahul** [comment]
I take it back.
I did not run the forecast (I compiled the package). I ran `reg2grb2.x` on existing model output.

So, I guess someone broke `APP=S2S` when the model tag was updated.  Lovely~

**Comment by JessicaMeixner-NOAA** [comment]
Well the standalone S2S app wasn't even supported by the ufs-weather-model for a while, so not super surprising as it's not a target configuration for development work.  Shouldn't be hard to fix.

**Comment by aerorahul** [comment]
Does that mean, these RT in the ufs-weather-model is not exercised?
These have been there for a while (I think).
<img width="1180" alt="Screen Shot 2022-08-16 at 4 45 02 PM" src="https://user-images.githubusercontent.com/11394126/184981673-104c6786-dcfc-487e-862f-74c034af7b19.png">

**Comment by JessicaMeixner-NOAA** [comment]
The control was updated to add aerosols and waves, an S2S compile was added though for CMEPS testing: https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/rt.conf#L5-L34 

Again, this is likely a small update and should be a big deal to get working and after all you can run S2SW or S2SWA if needed.

**Comment by aerorahul** [comment]
Ok.  Who should I ask to open an issue and address this?
This needs to be fixed ASAP.

**Comment by JessicaMeixner-NOAA** [comment]
It should not be a big task, the biggest question is if this is absolutely needed?  If @NeilBarton-NOAA needs this, I'm happy to help him make it work again and  already offered the help offline.

**Comment by NeilBarton-NOAA** [comment]
I'll start a test

**Comment by aerorahul** [comment]
Thanks @JessicaMeixner-NOAA and @NeilBarton-NOAA 
I opened an issue #977 to document the problem.

**Comment by WalterKolczynski-NOAA** [comment]
@aerorahul Is this also complete via #1274?

**Comment by aerorahul** [comment]
#1274 did not run with waves because the ICs that @guillaumevernieres provided did not have wave ICs.
I know one does not _need_ wave ICs to start, but I also don't have confidence I can do it correctly.
Having waves is not needed for WCDA prototyping efforts.

I think this issue should be closed and a more focussed issue on enabling waves in the cycling should be opened instead.

@NeilBarton-NOAA do you agree?

**Comment by NeilBarton-NOAA** [comment]
Closing this issue works for. In addition to waves, IAU and running the S2S+ app within the gdas ensemble is needed.
