### ISSUE TITLE
Fail forecast job if WAVE is turned on with warm_start=.true. and WAVE restart file in previous cycle

### ISSUE THREAD

**Issue by lgannoaa** [NOAA-EMC/global-workflow#955]
**Expected behavior**

Forecast job should fail if restart files are missing.
**Current behavior**

exglobal_forecast.sh log a warming message without fail the job.
**Machines affected**

All
**To Reproduce**

Get ICS without the wave restart files and run GDAS forecast job.

**Detailed Description**

The forecast script exglobal_forecast.sh only give a warning message if wave turned on and warm_start=.true. in parallel configuration. The job should fail instead of just a warning.
Jessica indicated the missing wave restart in first cycle is an error. The impact will be seen for about a month of the parallel until the waves spin-up from rest completely. The results for the first 2 weeks for waves will be very poor.  

User specify in parallel configuration to turn on WAVE and warm_start=.true. is indicated the use of restart file should be in place. Therefore, job should fail if restart files are missing.

**Comment by JessicaMeixner-NOAA** [comment]
@lgannoaa the current behavior was requested by NCO.  @aerorahul can chime in more when he's back from leave.

**Comment by WalterKolczynski-NOAA** [comment]
We probably should make it an option whether to fail or not. In operations it is important for the GFS suite to not fail entirely if the wave restart file is missing. But for development, it would be better to just stop.

**Comment by lgannoaa** [comment]
@aerorahul For the upcoming implementation, I recommend to fix it by modify production runhistory list to create a separate wave restart file. It will be in-line with current restart file naming used in production. It will help NCO with getting the right restart files if a restart is needed.
I also recommend to contact NCO and let them know that the /*gdaswave_keep/* file from the previous cycle is need to restart.

**Comment by lgannoaa** [comment]
> We probably should make it an option whether to fail or not. In operations it is important for the GFS suite to not fail entirely if the wave restart file is missing. But for development, it would be better to just stop.

If impact statement above is not acceptable from the operation, this job should fail as need.

**Comment by JessicaMeixner-NOAA** [comment]
@lgannoaa  please see this PR: https://github.com/NOAA-EMC/global-workflow/pull/874 which discussed in great detail if waves were going to fail, and wave restarts.  Based on this, I do no think this should be changing.  

I also do not think we need to be changing tar-ball names at this point.  Perhaps for v17 but it seems like we're adding unneeded changes that were not asked for.  @KateFriedman-NOAA and others have started parallels with wave restarts many times without issue, this seems like a fix to consider for future not current operations, in my opinion.

**Comment by lgannoaa** [comment]
> @lgannoaa please see this PR: #874 which discussed in great detail if waves were going to fail, and wave restarts. Based on this, I do no think this should be changing.
> 
> I also do not think we need to be changing tar-ball names at this point. Perhaps for v17 but it seems like we're adding unneeded changes that were not asked for. @KateFriedman-NOAA and others have started parallels with wave restarts many times without issue, this seems like a fix to consider for future not current operations, in my opinion.

@JessicaMeixner-NOAA I see PR #874 now. As noted above, staring parallel without wave restarts file will not fail the job. That is why we do not see issue when other people start the parallel with missing wave restart files. Hence this issue to do exception handling to fail the job if restart file is missing with the configuration noted above.

**Comment by JessicaMeixner-NOAA** [comment]
@aerorahul - can you advise as to how you'd like for this issue to proceed?  Do you want to keep things as is, fail if a wave restart does not exist, or add an option to fail or not?

**Comment by aerorahul** [comment]
I think the forecast should not fail if the wave restarts are not present.
It should however, post a message that restarts were not found (which it does), and continue with cold-starting the waves component (also which it does).
