### ISSUE TITLE
exglobal_forecast.sh unnecessary sCDATE in code

### ISSUE THREAD

**Issue by lgannoaa** [NOAA-EMC/global-workflow#956]
**Description**

https://github.com/NOAA-EMC/global-workflow/blob/feature/ops-wcoss2/scripts/exglobal_forecast.sh#L224-L238
Line 224 should be removed because sCDATE is set from the line 227 and 233.

**Comment by WalterKolczynski-NOAA** [comment]
[L252 of forecast_predet](https://github.com/NOAA-EMC/global-workflow/blob/develop/ush/forecast_predet.sh#L252) in develop.

This really isn't the kind of thing we need to worry about removing in the ops branch.

**Comment by lgannoaa** [comment]
> [L252 of forecast_predet](https://github.com/NOAA-EMC/global-workflow/blob/develop/ush/forecast_predet.sh#L252) in develop.
> 
> This really isn't the kind of thing we need to worry about removing in the ops branch.

This issue is not about removing in the ops branch. We know an issue noted in the issue where it is designed for. Why not fix it?
