### ISSUE TITLE
Absorb GSI monitor scripts

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#967]
**Description**
As part of the overarching goal of moving global workflow scripts out of component repositories and under global workflow, all of the scripts currently linked in GSI monitor should be moved to global workflow.

**Requirements**
All jobs, scripts, and ush scripts that are currently linked by global workflow added to the global workflow repo instead and removed from the ignore list.

**Acceptance Criteria (Definition of Done)**
No jobs, scripts, or ush scripts linked from GSI monitor.

**Dependencies**
None

**Comment by CoryMartin-NOAA** [comment]
Looking ahead to when we refactor the monitoring system, I'm not sure we will want `ush` scripts to be kept in the global-workflow. Is that the convention that is being followed now for all components? I think, for monitoring in particular, that could get messy fast. Thoughts? @aerorahul @EdwardSafford-NOAA @ADCollard @kevindougherty-noaa

**Comment by EdwardSafford-NOAA** [comment]
I've been viewing the monitoring refactor in terms of creating a new, wholly separate package and repo ("Monitoring 2.0") and letting the existing GSI-monitor repo sunset.  At the moment only the global workflow is using GSI-monitor, so I don't see an immediate problem with this convergence of the ush.   But you're right, Cory, when we get 2.0 built, putting the ush level scripts in a specific workflow could be awkward.

**Comment by WalterKolczynski-NOAA** [comment]
I had done the changes before these comments so I just brought the ush scripts that workflow was using over. We can move them back later if need be.

**Comment by CoryMartin-NOAA** [comment]
My comment was more "forward looking", I have no issues with doing it for the GSI monitor.
