### ISSUE TITLE
GFS v15.3.2 updates

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#97]
> RFC 7036 – On WCOSS, implement GFS.v15.3.2 updates to the GSI fix file and global_satinfo.txt. This change is being made to address minimization issues in the GSI and tighten quality control for the seven CrIS water vapor channels. To be implemented on July 6 at 1400Z.

@RussTreadon-NOAA @MichaelLueken-NOAA Is there a new GSI tag for this version? Thanks!

**Comment by RussTreadon-NOAA** [comment]
Yes, NOAA-EMC GSI tag gfsda.v15.3.2
<https://github.com/NOAA-EMC/GSI/releases/tag/gfsda.v15.3.2> has been
created.   Please note, however, that NCO checked out Vlab ProdGSI tag
gfsda.v15.3.2
<https://vlab.ncep.noaa.gov/redmine/projects/comgsi/repository?utf8=%E2%9C%93&rev=gfsda.v15.3.2>
for the implementation.

**Comment by KateFriedman-NOAA** [comment]
Gotcha, thanks for the tag! Do you happen to know why NCO checked out the VLab tag rather than the GitHub tag?

**Comment by RussTreadon-NOAA** [comment]
The quickest path for getting a tag to NCO was to  work from the existing DA_GFS_v15.3 branch in Vlab ProdGSI.    After NCO implemented GFS v15.3.2 we worked from NOAA-EMC GSI to create a comparable tag.   Both tags are functionally equivalent.

**Comment by KateFriedman-NOAA** [comment]
Gotcha, thanks!

**Comment by KateFriedman-NOAA** [comment]
The operations branch was updated for v15.3.2 at 7728ce1.

New tag off operations branch: NCO-v15.3.2

Closing issue now.
