### ISSUE TITLE
HELP with errors building GSI for release 16.2.2 on Hera

### ISSUE THREAD

**Issue by ghost** [NOAA-EMC/global-workflow#987]
Your bug may already be reported!
Please search on the [Issue tracker](https://github.com/NOAA-EMC/global-workflow/issues) before creating one.

**Expected behavior**
Attempting to build global_workflow on Hera under: /scratch1/BMC/qosap/Jorge.Guerra/gfs162_gpsro_dev/global-workflow/sorc/

**Current behavior**
There is an error when configuring GSI prior to compilation detailed in the following log: /scratch1/BMC/qosap/Jorge.Guerra/gfs162_gpsro_dev/global-workflow/sorc/logs/build_gsi.log

**Machines affected**

This problem is on Hera using my environment as defined in: /home/Jorge.Guerra/.bashrc
It also happens when I use the "machine_setup.sh" script to try and reset my environment. 

**To Reproduce**

Under:/scratch1/BMC/qosap/Jorge.Guerra/gfs162_gpsro_dev/global-workflow/sorc/ run the "build_all.sh" or "build_gsi.sh"

**Comment by WalterKolczynski-NOAA** [comment]
Your GSI clone failed because you have not [setup your gerrit alias properly](https://github.com/NOAA-EMC/global-workflow/wiki/Clone-and-build-global-workflow#set-up-gerrit-access-on-hpcs-to-properly-clone-the-gsi-submodules-from-vlab-gerrit-repeat-for-each-hpc), which made the build fail.

**Comment by ghost** [comment]
Thank you Walter! I updated my keys now on Vlab. Also, how does that error reveal that the gerritt alias was the problem?

**Comment by WalterKolczynski-NOAA** [comment]
It's a common enough issue that I knew to immediately look at the checkout log, where it was explicitly stated. We're trying to improve develop to remove this 'gotcha'.
