### ISSUE TITLE
need to reduce post job # in CROW workflow for ufs-s2s-model

### ISSUE THREAD

**Issue by jiandewang** [NOAA-EMC/global-workflow#99]
right now fv3 and ocean post jobs will be launched at every 6hr interval, this will bring ~300 jobs which is hard to manage. It will be good to reduce the total job numbers, for example, just split the 35 days post jobs into 5 sections.

**Comment by jkuang-exploro** [comment]
Now working on this issue in branch feature/splitpost

**Comment by jiandewang** [comment]
currently all working directories is named with a random number, if you can reduce the post to 5 sections, it will be nice to have post working directories named something like post.1, post.2....., in this way it will make life a bit easy when doing trouble shooting

**Comment by jkuang-exploro** [comment]
@jiandewang 1, They are not random numbers, instead they are indicating the hours of output; After this feature is implemented, each "grouped" post job will be named after the FIRST output hour in this group; 2, The ocnpost job is already grouped. The default setting is to group every 120 hours, but in the case file, it is set to 24 hours.

**Comment by jiandewang** [comment]
@JianKuang-NOAA can you tell me which parameter is used to control ocnpost group interval ?

**Comment by jkuang-exploro** [comment]
@jiandewang “OCN_INTERVAL: 120” in the case file, is controlling the group setting. This means every ocn post job will contain 120 hours of length (time stamp of model output is controlled by FHMIN FHMAX FHOUT parameters, same with atmospheric-only experiment )

**Comment by jkuang-exploro** [comment]
(continue) say, model output in 0, 6, 12, 18 will in included in the first ocnpost job, if you set OCN_INTERVAL: 24

**Comment by jkuang-exploro** [comment]
PR#107 created to enable this feature.

**Comment by KateFriedman-NOAA** [comment]
@jiandewang @JianKuang-NOAA Is this issue completed? If so, please close, thanks!

**Comment by JessicaMeixner-NOAA** [comment]
The path forward for this based on the coupled meeting on 10/7 is that we will start using the inline post for the coupled model and see if this issue remains.

**Comment by KateFriedman-NOAA** [comment]
@jiandewang @JessicaMeixner-NOAA Checking on the status of this issue. Please provide update or close as needed, thanks!

**Comment by JessicaMeixner-NOAA** [comment]
Still have not run enough jobs w/inline post to confirm if this is an issue still or not. Please keep issue open.

**Comment by KateFriedman-NOAA** [comment]
Roger that, thanks for the update!

**Comment by KateFriedman-NOAA** [comment]
Checking on this issue again. Please update or close, thanks!

**Comment by JessicaMeixner-NOAA** [comment]
We still have not run a full benchmark to see if this is an issue.  It will be done soon however.  Please keep this issue open.

**Comment by WalterKolczynski-NOAA** [comment]
I can handle this at some point, but it isn't currently a high priority.

**Comment by JessicaMeixner-NOAA** [comment]
@WalterKolczynski-NOAA - we aren't sure if moving to inline post (which we're struggling to do w/high number of x_layout, y_layout) and all the recent updates will make this a moot point or not.

**Comment by WalterKolczynski-NOAA** [comment]
Even with inline post, there would be jobs to produce the atmos products (regridding master to 1-deg or 0.5-deg or whatever). Right now these are still called "post" because GFS had combined the two steps into one job, but I am already writing a new script that just does the product generation step that also takes some of the techniques I used for the GEFS scripts to make it more generic/configurable.

**Comment by JoshuaFu-NOAA** [comment]
the current setting for ufs-model postprocessing is very time-consuming and error-prone, hope inline-post can help fix this issue.

**Comment by JoshuaFu-NOAA** [comment]
the current setting for ufs-model postprocessing is very time-consuming and error-prone, hope the inline post can help fix this problem.

**Comment by JessicaMeixner-NOAA** [comment]
@jiandewang: Now that we're almost done with P6 runs, what is your thought? Is this still a concern with inline post, etc? Do you still have to go back to re-run a lot of post jobs? Is the number of post jobs an issue?

**Comment by jiandewang** [comment]
@JessicaMeixner-NOAA no more FATAL ERROR in P6 with the inline post

**Comment by JessicaMeixner-NOAA** [comment]
@jiandewang good to hear! Can we close this issue then?

**Comment by WalterKolczynski-NOAA** [comment]
This will be covered by #270 anyway, whenever I finally get to it.

**Comment by JessicaMeixner-NOAA** [comment]
Okay - based on @WalterKolczynski-NOAA  @jiandewang comments.  I'm closing this issue and further comments can be added to #270.
