### ISSUE TITLE
S2SWA Fails with "cannot find output CA.bcEXTTAU in CA.bc" error

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/global-workflow#991]
**Expected behavior**

Forecast runs to completion

**Current behavior**

For a test case run on 2013040100 on Hera, the GFS forecast fails while initializing GOCART.  The error messages reported are

>   0: pe=00000 FAIL at line=05181    MAPL_HistoryGridComp.F90                 <Field CA.bcEXTTAU not found>
>   0:  ERROR: cannot find output CA.bcEXTTAU in CA.bc
>   0:  ERROR: cannot find output CA.ocEXTTAU in CA.oc
>   0: pe=00000 FAIL at line=05181    MAPL_HistoryGridComp.F90                 <Field CA.ocEXTTAU not found>
>   4: pe=00004 FAIL at line=05181    MAPL_HistoryGridComp.F90                 <Field CA.bcEXTTAU not found>

With more instances of the 'MAPL_HistoryGridComp.F90' message following.

See the complete log here: /scratch1/NESDIS/nesdis-rdo2/David.Huber/para/com/test_ff/logs/2013040100/gfsfcst.log

**Machines affected**

Hera

**To Reproduce**

Run a S2SWA (or possibly ATMA) free-forecast experiment on Hera.

**Context**

Encountered while porting on S4

**Detailed Description**

**Additional Information**

**Possible Implementation**

**Comment by JessicaMeixner-NOAA** [comment]
@DavidHuber-NOAA we have successfully run this IC date on Hera with S2SWA with the P8 tag which is pretty close to the top of develop.

**Comment by DavidHuber-NOAA** [comment]
@JessicaMeixner-NOAA Can you point me to that log?  Perhaps I could find where I'm going astray.

Also, I pulled the develop branch in and recompiled before running.  I will instead try a clean clone and see how it goes.

**Comment by JessicaMeixner-NOAA** [comment]
@DavidHuber-NOAA that log file is no longer on disk, but here's a different run date:  /scratch1/NCEPDEV/climate/role.ufscpara/Prototype8/work-P8/COMROOT/p82015040100/logs/2015040100/gfsfcst.log if that could be of help.  I think it's archived so we could look for it needed.

**Comment by DavidHuber-NOAA** [comment]
Thanks, I'll check out the 2015040100 log and see where I get.

**Comment by DavidHuber-NOAA** [comment]
Yeah, there is something wrong with my config files.  I will get it cleaned up and start fresh.  Will close this issue if it all runs well.

**Comment by DavidHuber-NOAA** [comment]
I believe I copied in an older version of the config files to my experiment directory, then pulled in the updates from the develop branch.  Regenerating the experiment from a fresh checkout allowed the forecast to run to completion.
