### ISSUE TITLE
Modify specification of MinMon tank (archive) directory for rocoto-based parallels

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/global-workflow#993]
**Expected behavior**
MinMon output from developer rocoto-based parallels should be saved in `$PSLOT` specific directories.

**Current behavior**
Execution of the gdas and gfs vrfy jobs from `release/gfs.v16.3.0` writes MinMon output to a non-`$PSLOT` specific directory.   If a developer runs multiple rocoto-based parallels with different `$PSLOT`, MinMon output from the current parallel will overwrite output from the previous parallel.

**Machines affected**
Only confirmed on WCOSS2 but expect similar behavior on other machines.

**To Reproduce**
To observe the current behavior
1. Install g-w `release/gfsda.v16.3.0` on WCOSS2
2. Set up `EXPDIR` for experiment `$PSLOT`
3. Populate `ROTDIR` with the files needed to run MinMon for gdas and gfs cycle
4. Submit gdas and gfs vrfy

MinMon output will be written to `M_TANKverf="$NOSCRUB/monitor/minmon"`.  This directory is not unique to the experiment `$PSLOT`.

**Detailed Description**
Proposed changes to `vrfy.sh` and `config.vrfy` will be committed to fork [Russ.Treadon-NOAA/global-workflow/release/gfs.v16.3.0
](https://github.com/RussTreadon-NOAA/global-workflow/tree/release/gfs.v16.3.0)

**Comment by RussTreadon-NOAA** [comment]
There appears to be a problem with how the gfs.v16.3.0 vrfy.sh sets tank directories for MinMon in developer rocoto-based parallels.

[`vrfy.sh`](https://github.com/NOAA-EMC/global-workflow/blob/release/gfs.v16.3.0/jobs/rocoto/vrfy.sh) currently has

```
 if [ $VRFYMINMON = "YES" -a $CDATE != $SDATE ]; then
 
     export COMOUT="$ROTDIR/$CDUMP.$PDY/$cyc/$COMPONENT"
     export M_TANKverfM0="$M_TANKverf/stats/$PSLOT/$CDUMP.$PDY"
     export M_TANKverfM1="$M_TANKverf/stats/$PSLOT/$CDUMP.$PDYm1"
     export MY_MACHINE=$machine
 
     $VRFYMINSH

fi
```

[`config.vrfy`](https://github.com/NOAA-EMC/global-workflow/blob/release/gfs.v16.3.0/parm/config/config.vrfy) defines `M_TANKverf` as

`
        export M_TANKverf="$NOSCRUB/monitor/minmon"
`

A check of `gfsda.v16.3.0` MinMon only finds `M_TANKverfM0` in `util/Minimization_Monitor/nwprod/nam_minmon/jobs/JNAM_MINMON`.    This job is not used in the GFS.   The GFS MinMon only uses `M_TANKverf` and `M_TANKverfM1`.   As shown above `M_TANKverf` does not include the experiment name whereas `M_TANKverfM1` does.   This seems wrong.

The follow modification results in MinMon output being written to a `$PSLOT` specific output (tank) directory.

[`vrfy.sh`](https://github.com/RussTreadon-NOAA/global-workflow/blob/release/gfs.v16.3.0/jobs/rocoto/vrfy.sh)
```
if [ $VRFYMINMON = "YES" -a $CDATE != $SDATE ]; then

    export COMOUT="$ROTDIR/$CDUMP.$PDY/$cyc/$COMPONENT"
    export M_TANKverf="$TANKverf_min/stats/$PSLOT/$CDUMP.$PDY"
    export M_TANKverfM1="$TANKverf_min/stats/$PSLOT/$CDUMP.$PDYm1"
    export MY_MACHINE=$machine

    $VRFYMINSH

fi
```

with [`config.vrfy`](https://github.com/RussTreadon-NOAA/global-workflow/blob/release/gfs.v16.3.0/parm/config/config.vrfy) defining

`
        export TANKverf_min="$NOSCRUB/monitor/minmon"
`

The above changes were committed to the forked release/gfs.v16.3.0 at f0c9630.

Rocoto-based developer parallels and NCO run the DA Monitoring packages differently.   The above changes only pertain to rocoto-based developer parallels.   The official EMC v16.3.0 retrospective and real-time parallels use ecflow, like NCO, to cycle the system.

**Comment by KateFriedman-NOAA** [comment]
The changes made for this issue in the v16.3 system need to be replicated in the `develop` branch. Will do.

**Comment by KateFriedman-NOAA** [comment]
@EdwardSafford-NOAA I am working to replicate the changes for v16.3 into `develop` while retaining other recent edits done @ https://github.com/NOAA-EMC/global-workflow/commit/fd771cb82ab603a64f16ba8639f3e71c8fc7440d.

It looks like I just need to rename `M_TANKverf` to `TANKverf_min` in both `parm/config/config.vrfy` and `jobs/rocoto/vrfy.sh`. Is that all?

I also see a difference between these two path variables between the v16 branch (`M_TANKverf`) and `develop` (`M_TANKverfM0`). Is the `develop` variable correct and should stay as is? Thanks!

* `dev/gfs.v16`: `export M_TANKverf="$TANKverf_min/stats/$PSLOT/$CDUMP.$PDY"`
https://github.com/NOAA-EMC/global-workflow/blob/dev/gfs.v16/jobs/rocoto/vrfy.sh#L163

* `develop`: `export M_TANKverfM0="${M_TANKverf}/stats/${PSLOT}/${CDUMP}.${PDY}/${cyc}"`
https://github.com/NOAA-EMC/global-workflow/blob/develop/jobs/rocoto/vrfy.sh#L119

**Comment by EdwardSafford-NOAA** [comment]
@KateFriedman-NOAA Actually I don't think that `TANKverf_min` change from v16.3 is needed.  Both `TANKverf_min` and `M_TANKverf` point to the same location and files in scripts and ush reference `M_TANKverf`.  

On the second question `M_TANKverfM0` is referenced by ush scripts and should remain.  So the development branch is OK as is.

**Comment by KateFriedman-NOAA** [comment]
@EdwardSafford-NOAA Awesome, this issue is complete then and I'll close it as such. I'll delete my fork branch that had the tentative path variable rename since that's not needed now. Thanks for your reply and confirmation that the `develop` branch is good.
